data = {
    ["Glowachromatic Diamond Solarix"] = {"Magic", "Power", "Powers", "Element", "Fairy", "Spells"},
    ["Salted & Buttered Popcorn"] = {"Snack", "Food"},
    ["Ice Berry Tea"] = {"Drink", "Soda", "Food"},
    ["Mystical Spices"] = {
        "Mermaid Sea Salt",
        "Dark Fairy Pepper",
        "Potion Poison",
        "Food",
        "Cafeteria",
        "Ketchup",
        "Mustard",
        "Salt",
        "Pepper"
    },
    ["Soft Locks Hair Brush & Mirror"] = {"Makeup", "Beauty", "Shower", "Bath", "Hygiene"},
    ["Orange Soda"] = {"Drink", "Soda", "Food"},
    ["Shimmerix Nail Polish"] = {"Makeup", "Beauty"},
    ["Glitterfrost Flurrix Blast"] = {"Magic", "Power", "Powers", "Element", "Fairy", "Spells"},
    ["Powder Puff"] = {"Makeup", "Beauty"},
    ["Hair Dryer"] = {"Blow Dryer", "Beauty", "Makeup", "Shower", "Bath", "Hygiene"},
    ["Fruity Lip Gloss"] = {"Makeup", "Beauty"},
    ["Your Highness Hot Popcorn"] = {"Snack", "Food"},
    ["Refreshing Water"] = {"Drink", "Soda", "Food"},
    ["Hair Straightener"] = {"Blow Dryer", "Beauty", "Makeup", "Shower", "Bath", "Hygiene"},
    ["Ember Flaria Ignitix"] = {"Magic", "Power", "Powers", "Element", "Fairy", "Spells"},
    ["Robux Mini Chocolate Chip Cookies"] = {"Snack", "Food"},
    ["Sour Cream & Onion Chippies"] = {"Snack", "Food", "Crisps"},
    ["Conditioner"] = {"Shower", "Bath", "Hygiene"},
    ["Knight's Peanut Butter Caramel Cups"] = {"Snack", "Food", "Candy"},
    ["Prince's Strawberry Crisped Rice Bar"] = {"Snack", "Food", "Candy"},
    ["Nail File"] = {"Makeup", "Beauty"},
    ["Cherry Soda"] = {"Drink", "Soda", "Food"},
    ["Prince's Chocolate Caramel Nougat Bar"] = {"Snack", "Food", "Candy"},
    ["Loofa"] = {"Shower", "Bath", "Hygiene"},
    ["Study Break Antioxidant Chocolate"] = {"Snack", "Food", "Candy"},
    ["Radiant Liquid Foundation"] = {"Makeup", "Beauty"},
    ["Shampoo"] = {"Shower", "Bath", "Hygiene"},
    ["Tray"] = {"Food", "Cafeteria"},
    ["Compact Hair Brush & Mirror"] = {"Makeup", "Beauty", "Shower", "Bath", "Hygiene"},
    ["Flowerix Shimmerdust"] = {"Magic", "Power", "Powers", "Element", "Fairy", "Spells"},
    ["Tropical Breeze Tea"] = {"Drink", "Soda", "Food"},
    ["Dreamy Star Hair Brush & Mirror"] = {"Makeup", "Beauty"},
    ["Goddess of Triumph Hair Brush & Mirror"] = {"Makeup", "Beauty"},
    ["Princess Hair Brush & Mirror"] = {"Makeup", "Beauty", "Shower", "Bath", "Hygiene"},
    ["Lemon Lime Soda"] = {"Drink", "Soda", "Food"},
    ["Caramel Popcorn"] = {"Snack", "Food"},
    ["Sweet Peach Tea"] = {"Drink", "Soda", "Food"},
    ["Magical Condiments"] = {
        "Ketchup",
        "Mustard",
        "Fairy Sprinkles",
        "Mermaid Magic Dressing",
        "Cafeteria",
        "Salt",
        "Pepper",
        "Food"
    },
    ["Sparkle Lotion"] = {"Makeup", "Beauty"},
    ["Mermaid Seashell Hair Brush & Mirror"] = {"Makeup", "Beauty", "Shower", "Bath", "Hygiene"},
    ["Cheesy Garlic Popcorn"] = {"Snack", "Food"},
    ["Rootbeer Soda"] = {"Drink", "Soda", "Food"},
    ["Laundry Basket"] = {"Clothes"},
    ["Luminix Highlighter Blush"] = {"Makeup", "Beauty"},
    ["Magical Crystal Perfume"] = {"Makeup", "Beauty"},
    ["Strawberry Punch"] = {"Drink", "Soda", "Food"},
    ["Luscious Lipstick"] = {"Makeup", "Beauty"},
    ["Magical Water"] = {"Drink", "Soda", "Food"},
    ["Grape Soda"] = {"Drink", "Soda", "Food"},
    ["Volumix Mascara & Mermaid Mirror"] = {"Makeup", "Beauty"},
    ["Roblox Cheezy Crackers"] = {"Snack", "Food"},
    ["Fluffy, Clean, Warm Towel"] = {"Shower", "Bath", "Hygiene"},
    ["Mermaidix Sparklefoam Rush"] = {"Magic", "Power", "Powers", "Element", "Fairy", "Spells"},
    ["Novamoon Nebula Sorcerix"] = {"Magic", "Power", "Powers", "Element", "Fairy", "Spells"},
    ["Dry Erase Board"] = {
        "White",
        "White Board",
        "Board",
        "Marker",
        "whiteboard",
        "message",
        "black",
        "drawing",
        "chalk"
    },
    ["Green Tea"] = {"Drink", "Soda", "Food"},
    ["BBQ Chippies"] = {"Snack", "Food", "Crisps"}
}
