data = {
    "- Hair Spikey Bun",
    "- Hair Man MiddlePart  (ColoringViaTexture)",
    "- Hair Man Buzzcut",
    "- Hair: Back Sweep Queen (ColoringViaTexture)",
    "- Hair: Side Sweep Queen (ColoringViaTexture)",
    "- Hair: Riko's Wavey Hair (ColoringViaTexture)",
    "- Hair: Summer Cute Split",
    "- Hair: Summer Cute",
    "- Hair: Summer Emo Jacob",
    "- Hair Bangs : Emo Jacob",
    "- Hair Bangs : Edges 4",
    "- Hair Bangs : Edges 3",
    "- Hair Bangs : Edges 2",
    "- Hair Bangs : Edges 1",
    "- Hair: Summer Boxbraids",
    "- Hair: Summer BHS Buns",
    "- Hair: Summer BHS 4 With Decor",
    "- Hair: Summer BHS 3 With Decor",
    "- Hair: Summer BHS 2",
    "- Hair: Summer BHS 1",
    "- Hair Neutral 2",
    "- Hair: Summer Bob",
    "- Hair: Summer Buns",
    "- Hair: Summer Riko (ColoringViaTexture)",
    "- Hair: Summer Neutral (ColoringViaTexture)",
    "- Hair: Summer Anna (ColoringViaTexture)",
    "- Hair: Summer Elsa (ColoringViaTexture)",
    "- Hair: Summer Half Up Half Down (ColoringViaTexture)",
    "- Hair: Goddess (ColoringViaTexture)",
    "- Hair: Male Braids Neutral",
    "- Hair Wavey Sidepart",
    "- Hair: Bun",
    "- Hair: Wavey Split Dye",
    "- Hair: Straight Split Dye",
    "- Hair: Long Single Braid",
    "- Hair Gyaru",
    "- Hair Bangs : Gyaru",
    "- Hair Bangs : Short Bang",
    "- Hair Bangs : Long Bang",
    "- Hair Bangs : Wavy Bang",
    "- Hair Bangs : Lisa Bangs",
    "- Hair Bangs : Front Pieces",
    "- Hair Bangs : Curtain Bangs",
    "- Hair 25",
    "- Hair 24",
    "- Hair 23",
    "- Hair Neutral 3",
    "- Hair Man 2",
    "- Hair Man 1",
    "- Hair 16",
    "- Hair 15 Dreads",
    "- Hair 22",
    "- Hair 21",
    "- Hair 19",
    "- Hair 17",
    "- Hair 14",
    "- Hair 13",
    "- Hair 12",
    "- Hair 11",
    "- Hair 10",
    "- Hair 7",
    "- Hair 5",
    "- Hair 4",
    "- Hair 3",
    "- Hair 2",
    "- Hair 1"
}
