data = {
    ["Robux"] = "",
    ["Product"] = {
        ["Permanent VIP Gift Porp"] = {
            ["AssetTypeId"] = 0,
            ["TargetId"] = 49008751,
            ["IsNew"] = false,
            ["Updated"] = "2024-03-30T16:54:51.523Z",
            ["AssetId"] = 0,
            ["ProductId"] = 1778174288,
            ["MinimumMembershipLevel"] = 0,
            ["PriceInRobux"] = 799,
            ["Created"] = "2024-03-16T22:10:01.28Z",
            ["ProductType"] = "Developer Product",
            ["IsLimited"] = false,
            ["IsLimitedUnique"] = false,
            ["Name"] = "VIP Permanent Gifting Prop",
            ["DisplayName"] = "VIP Permanent Gifting Prop",
            ["IsPublicDomain"] = false,
            ["DisplayIconImageAssetId"] = 16940655889,
            ["IsForSale"] = true,
            ["Creator"] = {["Id"] = 0, ["CreatorTargetId"] = 0},
            ["IconImageAssetId"] = 16940655889
        },
        ["Custom Makeup Gift"] = {
            ["AssetTypeId"] = 0,
            ["TargetId"] = 60799687,
            ["IsNew"] = false,
            ["Updated"] = "2024-08-06T11:52:03.303Z",
            ["AssetId"] = 0,
            ["ProductId"] = 1899684063,
            ["MinimumMembershipLevel"] = 0,
            ["PriceInRobux"] = 349,
            ["Created"] = "2024-08-06T11:52:00.317Z",
            ["ProductType"] = "Developer Product",
            ["IsLimited"] = false,
            ["IsLimitedUnique"] = false,
            ["Name"] = "Custom Makeup Gifting Prop",
            ["DisplayName"] = "Custom Makeup Gifting Prop",
            ["IsPublicDomain"] = false,
            ["DisplayIconImageAssetId"] = 18829792251,
            ["IsForSale"] = true,
            ["Creator"] = {["Id"] = 0, ["CreatorTargetId"] = 0},
            ["IconImageAssetId"] = 18829792251
        },
        {
            ["AssetTypeId"] = 0,
            ["TargetId"] = 49008751,
            ["IsNew"] = false,
            ["Updated"] = "2024-03-30T16:54:51.523Z",
            ["AssetId"] = 0,
            ["ProductId"] = 1778174288,
            ["MinimumMembershipLevel"] = 0,
            ["PriceInRobux"] = 799,
            ["Created"] = "2024-03-16T22:10:01.28Z",
            ["ProductType"] = "Developer Product",
            ["IsLimited"] = false,
            ["IsLimitedUnique"] = false,
            ["Name"] = "VIP Permanent Gifting Prop",
            ["DisplayName"] = "VIP Permanent Gifting Prop",
            ["IsPublicDomain"] = false,
            ["DisplayIconImageAssetId"] = 16940655889,
            ["IsForSale"] = true,
            ["Creator"] = {["Id"] = 0, ["CreatorTargetId"] = 0},
            ["IconImageAssetId"] = 16940655889
        },
        {
            ["AssetTypeId"] = 0,
            ["TargetId"] = 38462928,
            ["IsNew"] = false,
            ["Updated"] = "2024-03-30T16:55:33.02Z",
            ["AssetId"] = 0,
            ["ProductId"] = 1706713030,
            ["MinimumMembershipLevel"] = 0,
            ["PriceInRobux"] = 299,
            ["Created"] = "2023-12-16T09:29:09.813Z",
            ["ProductType"] = "Developer Product",
            ["IsLimited"] = false,
            ["IsLimitedUnique"] = false,
            ["Name"] = "VIP Monthly",
            ["DisplayName"] = "VIP Monthly",
            ["IsPublicDomain"] = false,
            ["DisplayIconImageAssetId"] = 16940666561,
            ["IsForSale"] = true,
            ["Creator"] = {["Id"] = 0, ["CreatorTargetId"] = 0},
            ["IconImageAssetId"] = 16940666561
        },
        {
            ["AssetTypeId"] = 0,
            ["TargetId"] = 49008794,
            ["IsNew"] = false,
            ["Updated"] = "2024-03-30T16:54:32.59Z",
            ["AssetId"] = 0,
            ["ProductId"] = 1778174609,
            ["MinimumMembershipLevel"] = 0,
            ["PriceInRobux"] = 299,
            ["Created"] = "2024-03-16T22:10:48.987Z",
            ["ProductType"] = "Developer Product",
            ["IsLimited"] = false,
            ["IsLimitedUnique"] = false,
            ["Name"] = "VIP One Month Gifting Prop",
            ["DisplayName"] = "VIP One Month Gifting Prop",
            ["IsPublicDomain"] = false,
            ["DisplayIconImageAssetId"] = 16940651338,
            ["IsForSale"] = true,
            ["Creator"] = {["Id"] = 0, ["CreatorTargetId"] = 0},
            ["IconImageAssetId"] = 16940651338
        },
        ["Monthly VIP"] = {
            ["AssetTypeId"] = 0,
            ["TargetId"] = 38462928,
            ["IsNew"] = false,
            ["Updated"] = "2024-03-30T16:55:33.02Z",
            ["AssetId"] = 0,
            ["ProductId"] = 1706713030,
            ["MinimumMembershipLevel"] = 0,
            ["PriceInRobux"] = 299,
            ["Created"] = "2023-12-16T09:29:09.813Z",
            ["ProductType"] = "Developer Product",
            ["IsLimited"] = false,
            ["IsLimitedUnique"] = false,
            ["Name"] = "VIP Monthly",
            ["DisplayName"] = "VIP Monthly",
            ["IsPublicDomain"] = false,
            ["DisplayIconImageAssetId"] = 16940666561,
            ["IsForSale"] = true,
            ["Creator"] = {["Id"] = 0, ["CreatorTargetId"] = 0},
            ["IconImageAssetId"] = 16940666561
        },
        ["Monthly VIP Gift Prop"] = {
            ["AssetTypeId"] = 0,
            ["TargetId"] = 49008794,
            ["IsNew"] = false,
            ["Updated"] = "2024-03-30T16:54:32.59Z",
            ["AssetId"] = 0,
            ["ProductId"] = 1778174609,
            ["MinimumMembershipLevel"] = 0,
            ["PriceInRobux"] = 299,
            ["Created"] = "2024-03-16T22:10:48.987Z",
            ["ProductType"] = "Developer Product",
            ["IsLimited"] = false,
            ["IsLimitedUnique"] = false,
            ["Name"] = "VIP One Month Gifting Prop",
            ["DisplayName"] = "VIP One Month Gifting Prop",
            ["IsPublicDomain"] = false,
            ["DisplayIconImageAssetId"] = 16940651338,
            ["IsForSale"] = true,
            ["Creator"] = {["Id"] = 0, ["CreatorTargetId"] = 0},
            ["IconImageAssetId"] = 16940651338
        },
        {
            ["AssetTypeId"] = 0,
            ["TargetId"] = 60799687,
            ["IsNew"] = false,
            ["Updated"] = "2024-08-06T11:52:03.303Z",
            ["AssetId"] = 0,
            ["ProductId"] = 1899684063,
            ["MinimumMembershipLevel"] = 0,
            ["PriceInRobux"] = 349,
            ["Created"] = "2024-08-06T11:52:00.317Z",
            ["ProductType"] = "Developer Product",
            ["IsLimited"] = false,
            ["IsLimitedUnique"] = false,
            ["Name"] = "Custom Makeup Gifting Prop",
            ["DisplayName"] = "Custom Makeup Gifting Prop",
            ["IsPublicDomain"] = false,
            ["DisplayIconImageAssetId"] = 18829792251,
            ["IsForSale"] = true,
            ["Creator"] = {["Id"] = 0, ["CreatorTargetId"] = 0},
            ["IconImageAssetId"] = 18829792251
        }
    },
    ["GamePass"] = {
        {
            ["AssetTypeId"] = 0,
            ["Description"] = "",
            ["IsNew"] = false,
            ["Updated"] = "2024-01-17T18:53:01.46Z",
            ["AssetId"] = 0,
            ["ProductId"] = 1734260110,
            ["MinimumMembershipLevel"] = 0,
            ["Created"] = "2024-01-17T18:53:01.457Z",
            ["ProductType"] = "Game Pass",
            ["IsLimited"] = false,
            ["Sales"] = 0,
            ["IconImageAssetId"] = 16934569639,
            ["IsPublicDomain"] = false,
            ["PriceInRobux"] = 99,
            ["Name"] = "Denim Bag",
            ["IsForSale"] = true,
            ["Creator"] = {
                ["Id"] = 4452561620,
                ["CreatorType"] = "Group",
                ["Name"] = "Dress To Impress Group",
                ["CreatorTargetId"] = 17264167
            },
            ["TargetId"] = 690730133,
            ["IsLimitedUnique"] = false
        },
        ["Denim Bag"] = {
            ["AssetTypeId"] = 0,
            ["Description"] = "",
            ["IsNew"] = false,
            ["Updated"] = "2024-01-17T18:53:01.46Z",
            ["AssetId"] = 0,
            ["ProductId"] = 1734260110,
            ["MinimumMembershipLevel"] = 0,
            ["Created"] = "2024-01-17T18:53:01.457Z",
            ["ProductType"] = "Game Pass",
            ["IsLimited"] = false,
            ["Sales"] = 0,
            ["IconImageAssetId"] = 16934569639,
            ["IsPublicDomain"] = false,
            ["PriceInRobux"] = 99,
            ["Name"] = "Denim Bag",
            ["IsForSale"] = true,
            ["Creator"] = {
                ["Id"] = 4452561620,
                ["CreatorType"] = "Group",
                ["Name"] = "Dress To Impress Group",
                ["CreatorTargetId"] = 17264167
            },
            ["TargetId"] = 690730133,
            ["IsLimitedUnique"] = false
        },
        {
            ["AssetTypeId"] = 0,
            ["Description"] = "Unlock the Limited Luxury Dress.",
            ["IsNew"] = false,
            ["Updated"] = "2023-11-19T17:54:06.023Z",
            ["AssetId"] = 0,
            ["ProductId"] = 1690657037,
            ["MinimumMembershipLevel"] = 0,
            ["Created"] = "2023-11-19T17:54:06.02Z",
            ["ProductType"] = "Game Pass",
            ["IsLimited"] = false,
            ["Sales"] = 0,
            ["IconImageAssetId"] = 16934548325,
            ["IsPublicDomain"] = false,
            ["PriceInRobux"] = 249,
            ["Name"] = "Limited Luxury Dress",
            ["IsForSale"] = true,
            ["Creator"] = {
                ["Id"] = 4452561620,
                ["CreatorType"] = "Group",
                ["Name"] = "Dress To Impress Group",
                ["CreatorTargetId"] = 17264167
            },
            ["TargetId"] = 659850359,
            ["IsLimitedUnique"] = false
        },
        ["x2 Money"] = {
            ["AssetTypeId"] = 0,
            ["Description"] = "",
            ["IsNew"] = false,
            ["Updated"] = "2024-08-07T22:19:32.438Z",
            ["AssetId"] = 0,
            ["ProductId"] = 0,
            ["MinimumMembershipLevel"] = 0,
            ["Created"] = "2024-08-07T22:19:32.438Z",
            ["Creator"] = {
                ["Id"] = 4452561620,
                ["CreatorType"] = "Group",
                ["Name"] = "Dress To Impress Group",
                ["CreatorTargetId"] = 17264167
            },
            ["IsLimited"] = false,
            ["Sales"] = 0,
            ["IconImageAssetId"] = 13600173502,
            ["IsPublicDomain"] = false,
            ["Name"] = "x2 Money",
            ["IsForSale"] = false,
            ["TargetId"] = 0,
            ["IsLimitedUnique"] = false
        },
        ["French Luxury Bag"] = {
            ["AssetTypeId"] = 0,
            ["Description"] = "",
            ["IsNew"] = false,
            ["Updated"] = "2023-12-02T18:37:55.913Z",
            ["AssetId"] = 0,
            ["ProductId"] = 1698179848,
            ["MinimumMembershipLevel"] = 0,
            ["Created"] = "2023-12-02T18:37:55.907Z",
            ["ProductType"] = "Game Pass",
            ["IsLimited"] = false,
            ["Sales"] = 0,
            ["IconImageAssetId"] = 16934562075,
            ["IsPublicDomain"] = false,
            ["PriceInRobux"] = 199,
            ["Name"] = "French Luxury Bag",
            ["IsForSale"] = true,
            ["Creator"] = {
                ["Id"] = 4452561620,
                ["CreatorType"] = "Group",
                ["Name"] = "Dress To Impress Group",
                ["CreatorTargetId"] = 17264167
            },
            ["TargetId"] = 665604712,
            ["IsLimitedUnique"] = false
        },
        {
            ["AssetTypeId"] = 0,
            ["Description"] = "",
            ["IsNew"] = false,
            ["Updated"] = "2023-11-25T13:00:09.707Z",
            ["AssetId"] = 0,
            ["ProductId"] = 1694147847,
            ["MinimumMembershipLevel"] = 0,
            ["Created"] = "2023-11-25T13:00:09.703Z",
            ["ProductType"] = "Game Pass",
            ["IsLimited"] = false,
            ["Sales"] = 0,
            ["IconImageAssetId"] = 16934553552,
            ["IsPublicDomain"] = false,
            ["PriceInRobux"] = 149,
            ["Name"] = "Run Faster",
            ["IsForSale"] = true,
            ["Creator"] = {
                ["Id"] = 4452561620,
                ["CreatorType"] = "Group",
                ["Name"] = "Dress To Impress Group",
                ["CreatorTargetId"] = 17264167
            },
            ["TargetId"] = 662806020,
            ["IsLimitedUnique"] = false
        },
        {
            ["AssetTypeId"] = 0,
            ["Description"] = "Upon purchasing this game pass, you gain the ability to create customized makeup, including personalized lip colors, eyebrows, and more!",
            ["IsNew"] = false,
            ["Updated"] = "2023-11-19T23:46:58.877Z",
            ["AssetId"] = 0,
            ["ProductId"] = 1683765779,
            ["MinimumMembershipLevel"] = 0,
            ["Created"] = "2023-11-07T17:55:34.733Z",
            ["ProductType"] = "Game Pass",
            ["IsLimited"] = false,
            ["Sales"] = 0,
            ["IconImageAssetId"] = 16934539993,
            ["IsPublicDomain"] = false,
            ["PriceInRobux"] = 349,
            ["Name"] = "Custom Makeup",
            ["IsForSale"] = true,
            ["Creator"] = {
                ["Id"] = 4452561620,
                ["CreatorType"] = "Group",
                ["Name"] = "Dress To Impress Group",
                ["CreatorTargetId"] = 17264167
            },
            ["TargetId"] = 646065677,
            ["IsLimitedUnique"] = false
        },
        {
            ["AssetTypeId"] = 0,
            ["Description"] = "",
            ["IsNew"] = false,
            ["Updated"] = "2024-03-30T16:07:53.967Z",
            ["AssetId"] = 0,
            ["ProductId"] = 1791384793,
            ["MinimumMembershipLevel"] = 0,
            ["Created"] = "2024-03-30T16:07:53.96Z",
            ["ProductType"] = "Game Pass",
            ["IsLimited"] = false,
            ["Sales"] = 0,
            ["IconImageAssetId"] = 16934589277,
            ["IsPublicDomain"] = false,
            ["PriceInRobux"] = 200,
            ["Name"] = "Moongazer Girl Set",
            ["IsForSale"] = true,
            ["Creator"] = {
                ["Id"] = 4452561620,
                ["CreatorType"] = "Group",
                ["Name"] = "Dress To Impress Group",
                ["CreatorTargetId"] = 17264167
            },
            ["TargetId"] = 767077894,
            ["IsLimitedUnique"] = false
        },
        ["Run Faster"] = {
            ["AssetTypeId"] = 0,
            ["Description"] = "",
            ["IsNew"] = false,
            ["Updated"] = "2023-11-25T13:00:09.707Z",
            ["AssetId"] = 0,
            ["ProductId"] = 1694147847,
            ["MinimumMembershipLevel"] = 0,
            ["Created"] = "2023-11-25T13:00:09.703Z",
            ["ProductType"] = "Game Pass",
            ["IsLimited"] = false,
            ["Sales"] = 0,
            ["IconImageAssetId"] = 16934553552,
            ["IsPublicDomain"] = false,
            ["PriceInRobux"] = 149,
            ["Name"] = "Run Faster",
            ["IsForSale"] = true,
            ["Creator"] = {
                ["Id"] = 4452561620,
                ["CreatorType"] = "Group",
                ["Name"] = "Dress To Impress Group",
                ["CreatorTargetId"] = 17264167
            },
            ["TargetId"] = 662806020,
            ["IsLimitedUnique"] = false
        },
        {
            ["AssetTypeId"] = 0,
            ["Description"] = "",
            ["IsNew"] = false,
            ["Updated"] = "2023-12-02T18:37:55.913Z",
            ["AssetId"] = 0,
            ["ProductId"] = 1698179848,
            ["MinimumMembershipLevel"] = 0,
            ["Created"] = "2023-12-02T18:37:55.907Z",
            ["ProductType"] = "Game Pass",
            ["IsLimited"] = false,
            ["Sales"] = 0,
            ["IconImageAssetId"] = 16934562075,
            ["IsPublicDomain"] = false,
            ["PriceInRobux"] = 199,
            ["Name"] = "French Luxury Bag",
            ["IsForSale"] = true,
            ["Creator"] = {
                ["Id"] = 4452561620,
                ["CreatorType"] = "Group",
                ["Name"] = "Dress To Impress Group",
                ["CreatorTargetId"] = 17264167
            },
            ["TargetId"] = 665604712,
            ["IsLimitedUnique"] = false
        },
        ["Rich Girl Bag"] = {
            ["AssetTypeId"] = 0,
            ["Description"] = "",
            ["IsNew"] = false,
            ["Updated"] = "2023-12-16T16:47:16.173Z",
            ["AssetId"] = 0,
            ["ProductId"] = 1707011010,
            ["MinimumMembershipLevel"] = 0,
            ["Created"] = "2023-12-16T16:47:16.167Z",
            ["ProductType"] = "Game Pass",
            ["IsLimited"] = false,
            ["Sales"] = 0,
            ["IconImageAssetId"] = 16934565940,
            ["IsPublicDomain"] = false,
            ["PriceInRobux"] = 149,
            ["Name"] = "Rich Girl Bag",
            ["IsForSale"] = true,
            ["Creator"] = {
                ["Id"] = 4452561620,
                ["CreatorType"] = "Group",
                ["Name"] = "Dress To Impress Group",
                ["CreatorTargetId"] = 17264167
            },
            ["TargetId"] = 672950406,
            ["IsLimitedUnique"] = false
        },
        {
            ["AssetTypeId"] = 0,
            ["Description"] = "",
            ["IsNew"] = false,
            ["Updated"] = "2024-08-07T22:19:32.438Z",
            ["AssetId"] = 0,
            ["ProductId"] = 0,
            ["MinimumMembershipLevel"] = 0,
            ["Created"] = "2024-08-07T22:19:32.438Z",
            ["Creator"] = {
                ["Id"] = 4452561620,
                ["CreatorType"] = "Group",
                ["Name"] = "Dress To Impress Group",
                ["CreatorTargetId"] = 17264167
            },
            ["IsLimited"] = false,
            ["Sales"] = 0,
            ["IconImageAssetId"] = 13600173502,
            ["IsPublicDomain"] = false,
            ["Name"] = "x2 Money",
            ["IsForSale"] = false,
            ["TargetId"] = 0,
            ["IsLimitedUnique"] = false
        },
        ["Limited Luxury Dress"] = {
            ["AssetTypeId"] = 0,
            ["Description"] = "Unlock the Limited Luxury Dress.",
            ["IsNew"] = false,
            ["Updated"] = "2023-11-19T17:54:06.023Z",
            ["AssetId"] = 0,
            ["ProductId"] = 1690657037,
            ["MinimumMembershipLevel"] = 0,
            ["Created"] = "2023-11-19T17:54:06.02Z",
            ["ProductType"] = "Game Pass",
            ["IsLimited"] = false,
            ["Sales"] = 0,
            ["IconImageAssetId"] = 16934548325,
            ["IsPublicDomain"] = false,
            ["PriceInRobux"] = 249,
            ["Name"] = "Limited Luxury Dress",
            ["IsForSale"] = true,
            ["Creator"] = {
                ["Id"] = 4452561620,
                ["CreatorType"] = "Group",
                ["Name"] = "Dress To Impress Group",
                ["CreatorTargetId"] = 17264167
            },
            ["TargetId"] = 659850359,
            ["IsLimitedUnique"] = false
        },
        ["Moongazer Girl Set"] = {
            ["AssetTypeId"] = 0,
            ["Description"] = "",
            ["IsNew"] = false,
            ["Updated"] = "2024-03-30T16:07:53.967Z",
            ["AssetId"] = 0,
            ["ProductId"] = 1791384793,
            ["MinimumMembershipLevel"] = 0,
            ["Created"] = "2024-03-30T16:07:53.96Z",
            ["ProductType"] = "Game Pass",
            ["IsLimited"] = false,
            ["Sales"] = 0,
            ["IconImageAssetId"] = 16934589277,
            ["IsPublicDomain"] = false,
            ["PriceInRobux"] = 200,
            ["Name"] = "Moongazer Girl Set",
            ["IsForSale"] = true,
            ["Creator"] = {
                ["Id"] = 4452561620,
                ["CreatorType"] = "Group",
                ["Name"] = "Dress To Impress Group",
                ["CreatorTargetId"] = 17264167
            },
            ["TargetId"] = 767077894,
            ["IsLimitedUnique"] = false
        },
        {
            ["AssetTypeId"] = 0,
            ["Description"] = "",
            ["IsNew"] = false,
            ["Updated"] = "2023-11-25T12:56:04.947Z",
            ["AssetId"] = 0,
            ["ProductId"] = 1694145917,
            ["MinimumMembershipLevel"] = 0,
            ["Created"] = "2023-11-25T12:56:04.937Z",
            ["ProductType"] = "Game Pass",
            ["IsLimited"] = false,
            ["Sales"] = 0,
            ["IconImageAssetId"] = 16934558463,
            ["IsPublicDomain"] = false,
            ["PriceInRobux"] = 59,
            ["Name"] = "Futuristic Suit",
            ["IsForSale"] = true,
            ["Creator"] = {
                ["Id"] = 4452561620,
                ["CreatorType"] = "Group",
                ["Name"] = "Dress To Impress Group",
                ["CreatorTargetId"] = 17264167
            },
            ["TargetId"] = 662838771,
            ["IsLimitedUnique"] = false
        },
        {
            ["AssetTypeId"] = 0,
            ["Description"] = "",
            ["IsNew"] = false,
            ["Updated"] = "2023-12-16T16:47:16.173Z",
            ["AssetId"] = 0,
            ["ProductId"] = 1707011010,
            ["MinimumMembershipLevel"] = 0,
            ["Created"] = "2023-12-16T16:47:16.167Z",
            ["ProductType"] = "Game Pass",
            ["IsLimited"] = false,
            ["Sales"] = 0,
            ["IconImageAssetId"] = 16934565940,
            ["IsPublicDomain"] = false,
            ["PriceInRobux"] = 149,
            ["Name"] = "Rich Girl Bag",
            ["IsForSale"] = true,
            ["Creator"] = {
                ["Id"] = 4452561620,
                ["CreatorType"] = "Group",
                ["Name"] = "Dress To Impress Group",
                ["CreatorTargetId"] = 17264167
            },
            ["TargetId"] = 672950406,
            ["IsLimitedUnique"] = false
        },
        {
            ["AssetTypeId"] = 0,
            ["Description"] = "Unlock the VIP Room by acquiring this incredible game pass! Once inside the room you can adorn yourself with stunning, exclusive items to enhance your outfit's allure.",
            ["IsNew"] = false,
            ["Updated"] = "2023-12-13T10:45:52.177Z",
            ["AssetId"] = 0,
            ["ProductId"] = 1683662864,
            ["MinimumMembershipLevel"] = 0,
            ["Created"] = "2023-11-07T13:41:49.76Z",
            ["ProductType"] = "Game Pass",
            ["IsLimited"] = false,
            ["Sales"] = 0,
            ["IconImageAssetId"] = 16934535009,
            ["IsPublicDomain"] = false,
            ["PriceInRobux"] = 799,
            ["Name"] = "VIP Pass",
            ["IsForSale"] = true,
            ["Creator"] = {
                ["Id"] = 4452561620,
                ["CreatorType"] = "Group",
                ["Name"] = "Dress To Impress Group",
                ["CreatorTargetId"] = 17264167
            },
            ["TargetId"] = 647191068,
            ["IsLimitedUnique"] = false
        },
        ["Permanent VIP"] = {
            ["AssetTypeId"] = 0,
            ["Description"] = "Unlock the VIP Room by acquiring this incredible game pass! Once inside the room you can adorn yourself with stunning, exclusive items to enhance your outfit's allure.",
            ["IsNew"] = false,
            ["Updated"] = "2023-12-13T10:45:52.177Z",
            ["AssetId"] = 0,
            ["ProductId"] = 1683662864,
            ["MinimumMembershipLevel"] = 0,
            ["Created"] = "2023-11-07T13:41:49.76Z",
            ["ProductType"] = "Game Pass",
            ["IsLimited"] = false,
            ["Sales"] = 0,
            ["IconImageAssetId"] = 16934535009,
            ["IsPublicDomain"] = false,
            ["PriceInRobux"] = 799,
            ["Name"] = "VIP Pass",
            ["IsForSale"] = true,
            ["Creator"] = {
                ["Id"] = 4452561620,
                ["CreatorType"] = "Group",
                ["Name"] = "Dress To Impress Group",
                ["CreatorTargetId"] = 17264167
            },
            ["TargetId"] = 647191068,
            ["IsLimitedUnique"] = false
        },
        ["Custom Makeup"] = {
            ["AssetTypeId"] = 0,
            ["Description"] = "Upon purchasing this game pass, you gain the ability to create customized makeup, including personalized lip colors, eyebrows, and more!",
            ["IsNew"] = false,
            ["Updated"] = "2023-11-19T23:46:58.877Z",
            ["AssetId"] = 0,
            ["ProductId"] = 1683765779,
            ["MinimumMembershipLevel"] = 0,
            ["Created"] = "2023-11-07T17:55:34.733Z",
            ["ProductType"] = "Game Pass",
            ["IsLimited"] = false,
            ["Sales"] = 0,
            ["IconImageAssetId"] = 16934539993,
            ["IsPublicDomain"] = false,
            ["PriceInRobux"] = 349,
            ["Name"] = "Custom Makeup",
            ["IsForSale"] = true,
            ["Creator"] = {
                ["Id"] = 4452561620,
                ["CreatorType"] = "Group",
                ["Name"] = "Dress To Impress Group",
                ["CreatorTargetId"] = 17264167
            },
            ["TargetId"] = 646065677,
            ["IsLimitedUnique"] = false
        },
        ["Futuristic Suit"] = {
            ["AssetTypeId"] = 0,
            ["Description"] = "",
            ["IsNew"] = false,
            ["Updated"] = "2023-11-25T12:56:04.947Z",
            ["AssetId"] = 0,
            ["ProductId"] = 1694145917,
            ["MinimumMembershipLevel"] = 0,
            ["Created"] = "2023-11-25T12:56:04.937Z",
            ["ProductType"] = "Game Pass",
            ["IsLimited"] = false,
            ["Sales"] = 0,
            ["IconImageAssetId"] = 16934558463,
            ["IsPublicDomain"] = false,
            ["PriceInRobux"] = 59,
            ["Name"] = "Futuristic Suit",
            ["IsForSale"] = true,
            ["Creator"] = {
                ["Id"] = 4452561620,
                ["CreatorType"] = "Group",
                ["Name"] = "Dress To Impress Group",
                ["CreatorTargetId"] = 17264167
            },
            ["TargetId"] = 662838771,
            ["IsLimitedUnique"] = false
        }
    }
}
