data = {
    ["Premium"] = {
        {"Title", "Swashbuckler"},
        {"Trail", "BeachBallsTrail"},
        {"Weapon", "PlasticShovel"},
        {"Emote", "Facepalm"},
        {"Title", "Scallywag"},
        {"Tool", "Pineapple"},
        {"Trail", "LemonTrail"},
        {"Title", "Breezy"},
        {"Potions", "Rating", 6, "rbxassetid://17173419208"},
        {"Emote", "Rushin"},
        {"Emote", "Clap"},
        {"Trail", "SandTrail"},
        {"Title", "Unreliable"},
        {"Chest", "TropicalChest", 8},
        {"Title", "Bombastic"},
        {"Weapon", "Surfboard"},
        {"Trail", "CrabTrail"},
        {"Car", "WatermelonGoKart"},
        {"Emote", "Open"},
        {"Title", "ManOWar"},
        {"Weapon", "Umbrella"},
        {"Title", "Buccaneer"},
        {"Emote", "AthleticFlip"},
        {"Chest", "FurryChest", 8},
        {"Title", "Bandit"},
        {"Coins", 10000},
        {"Emote", "Wings"},
        {"Chest", "GamerChest", 8},
        {"Title", "Peaceful"},
        {"Weapon", "GiantIceCream"},
        {"Chest", "HeavenlyChest", 8},
        {"Trail", "HeartsTrail"},
        {"Coins", 10000},
        {"Car", "Galleon"},
        {"Trail", "LabTrail"},
        {"Potions", "Rating", 6, "rbxassetid://17173419208"},
        {"Emote", "Cross"},
        {"Weapon", "WatermelonHammer"},
        {"Trail", "FireFlyTrail"},
        {"Emote", "Breakdance"},
        {"Title", "Marvelous"},
        {"Trail", "OceanTrail"},
        {"Chest", "UnderworldChest", 8},
        {"Weapon", "LightningCutlasses"},
        {"Weapon", "PianoBlade"},
        {"Emote", "Mashin"},
        {"Title", "LootGoblin"},
        {"Coins", 10000},
        {"Emote", "HitIt"},
        {"Car", "FlyingPhoenix"}
    },
    ["Total"] = 50,
    ["EndTimestamp"] = 1721795140,
    ["Free"] = {
        {"Weapon", "Coral"},
        {"Coins", 1000},
        {"Trail", "FairyTrail"},
        {"Potions", "Luck", 2, "rbxassetid://17173424966"},
        {"Weapon", "AnchorSword"},
        {"Emote", "Salute"},
        {"Coins", 1000},
        {"Chest", "IcyChest", 3},
        {"Coins", 1000},
        {"Title", "Mogger"},
        {"Trail", "PalmTreesTrail"},
        {"Coins", 1000},
        {"Title", "Scenic"},
        {"Potions", "Rating", 2, "rbxassetid://17173419208"},
        {"Trail", "WatermelonTrail"},
        {"Chest", "CyberpunkChest", 3},
        {"Emote", "Pump"},
        {"Chest", "MedievalChest", 3},
        {"Coins", 1000},
        {"Trail", "TimeLordTrail"},
        {"Coins", 1000},
        {"Car", "BeachGoKart"},
        {"Coins", 1000},
        {"Chest", "UndeadChest", 3},
        {"Emote", "ErickDance"},
        {"Potions", "Coins", 2, "rbxassetid://17173428777"},
        {"Coins", 1000},
        {"Chest", "PartyChest", 3},
        {"Trail", "MysticTrail"},
        {"Emote", "Bollywood"},
        {"Coins", 1000},
        {"Potions", "Rating", 2, "rbxassetid://17173419208"},
        {"Trail", "BeesTrail"},
        {"Coins", 1000},
        {"Emote", "Freedom"},
        {"Chest", "CircusChest", 3},
        {"Weapon", "Cutlass"},
        {"Chest", "WildChest", 3},
        {"Coins", 1000},
        {"Car", "UnderworldTruck"},
        {"Chest", "GamerChest", 3},
        {"Coins", 1000},
        {"Chest", "FurryChest", 3},
        {"Coins", 1000},
        {"Title", "Dangerous"},
        {"Potions", "Luck", 2, "rbxassetid://17173424966"},
        {"Coins", 1000},
        {"Chest", "FantasyChest", 8},
        {"Coins", 1000},
        {"Title", "Unhinged"}
    }
}
