--Rare Items are found in boxes
data = {
    ["ChestItemChance"] = 3,
    ["ExtraItemAmount"] = 1000,
    ["RareChestSpawnChance"] = 1,
    ["StartingCash"] = 2500,
    ["GamepassId"] = 232401693,
    ["DailyRewardsDayNotCompletedImage"] = "rbxassetid://15383127595",
    ["ExtraGamepassId"] = 664568290,
    ["RareBroadcastColor"] = "rgb(255, 217, 0)",
    ["ChestItems"] = {
        "Smore",
        "Sandwich",
        "Jiggly Cheesecake",
        "Bread rolls",
        "Loaf Of Bread",
        "Mushroom Plush",
        "Round Frog",
        "Pink Strawberry Cake",
        "Cupcake",
        "Double Chocolate Cupcake",
        "Chocolate Milk Carton",
        "Strawberry Milk Carton",
        "Vanilla Milk Carton",
        "Boba Tea",
        "Milk Boba Tea",
        "Blue Boba Tea",
        "Ube Boba Tea",
        "Strawberry Boba Tea",
        "Milk Bottle",
        "Strawberry Milk Bottle",
        "Chocolate Milk Bottle"
    },
    ["Top3Badge"] = 1869542375922766,
    ["ServerBoxRushProductId"] = 1719071547,
    ["ExtraBlanketsPlacedGamepassId"] = 658417099,
    ["RareItems"] = {
        {["name"] = "Samson", ["desc"] = "A rare samson, found only in chests"},
        {["name"] = "Apple Quackles", ["desc"] = "Dont take a bite!"},
        {["name"] = "Orange Quackles", ["desc"] = "Dont take a bite!"},
        {["name"] = "Swag Pony", ["desc"] = "Too much swag it has to be rare"},
        {["name"] = "Berry", ["desc"] = "Its Berry!"},
        {["name"] = "Strawbie", ["desc"] = "Its Strawbie!"},
        {["name"] = "Bella", ["desc"] = "Bella loves picnics and blueberries"},
        {["name"] = "Elena", ["desc"] = "Elena is Bella's best friend"},
        {["name"] = "Ruba", ["desc"] = "..."},
        {["name"] = "Aruba", ["desc"] = "..."},
        {["name"] = "Bunny Bear", ["desc"] = "..."},
        {["name"] = "Burger Kitty", ["desc"] = "Om nom nom"},
        {["name"] = "Clown Kitty", ["desc"] = "..."},
        {["name"] = "Magica Scarlet", ["desc"] = "..."},
        {["name"] = "Beear", ["desc"] = "..."},
        {["name"] = "Neon Heart", ["desc"] = "..."},
        {["name"] = "Onesie Bunny Bear", ["desc"] = "..."},
        {["name"] = "Fall Time Aruba", ["desc"] = "Matching with her bestie, Ruba!"},
        {["name"] = "Fall Time Ruba", ["desc"] = "Matching with her bestie, Aruba!"},
        {["name"] = "Sweater Bear", ["desc"] = "..."},
        {["name"] = "Jingle Bella", ["desc"] = "Happy Holidays!"},
        {["name"] = "Santa Burger Kitty", ["desc"] = "Happy Holidays!"},
        {["name"] = "Penguini", ["desc"] = "Happy Holidays!"},
        {["name"] = "Cozy Penguini", ["desc"] = "Happy Holidays!"},
        {["name"] = "Rudolph", ["desc"] = "Happy Holidays!"},
        {["name"] = "Reindeer", ["desc"] = "Happy Holidays!"},
        {["name"] = "The Winch", ["desc"] = "Unhappy Holidays."}
    },
    ["WheelCashAmounts"] = {500, 500, 500, 500, 1000, 1000, 1000, 1500, 2000, 2500, 5000, 10000},
    ["Day14Reward"] = 50000,
    ["Items"] = {
        ["Seasonal"] = {
            {["price"] = 250, ["name"] = "Candy Cane", ["desc"] = "Happy Holidays, Click this item to eat it!"},
            {["price"] = 250, ["name"] = "Standing Candy Cane", ["desc"] = "Happy Holidays, Click this item to eat it!"},
            {["price"] = 1000, ["name"] = "Giant Candy Cane", ["desc"] = "Happy Holidays, Click this item to eat it!"},
            {["price"] = 1000, ["name"] = "Giant Glowing Candy Cane", ["desc"] = "Happy Holidays"},
            {["price"] = 350, ["name"] = "Gingerbread Man", ["desc"] = "New"},
            {["price"] = 350, ["name"] = "Gingerbread Woman", ["desc"] = "New"},
            {["price"] = 6000, ["name"] = "Tiny Festive Tree", ["desc"] = "New"},
            {["price"] = 9500, ["name"] = "Tiny Plastic Christmas Tree", ["desc"] = "New"},
            {["price"] = 200, ["name"] = "Ornament", ["desc"] = "New"},
            {["price"] = 250, ["name"] = "Striped Ornament", ["desc"] = "New"},
            {["price"] = 200, ["name"] = "Tall Ornament", ["desc"] = "New"},
            {["price"] = 850, ["name"] = "Present", ["desc"] = "New"},
            {["price"] = 300, ["name"] = "Tiny Present", ["desc"] = "New"},
            {["price"] = 800, ["name"] = "Flat Present", ["desc"] = "New"},
            {["price"] = 850, ["name"] = "Tall Present", ["desc"] = "New"},
            {["price"] = 1300, ["name"] = "Giant Present", ["desc"] = "New"},
            {["price"] = 500, ["name"] = "Stocking", ["desc"] = "New"},
            {["price"] = 3000, ["name"] = "Hanging Holiday Lights", ["desc"] = "New"},
            {["price"] = 3000, ["name"] = "Short Holiday Lights", ["desc"] = "New"},
            {["price"] = 9000, ["name"] = "Dangling Lights", ["desc"] = "New"},
            {["price"] = 10000, ["name"] = "Long Dangling Lights", ["desc"] = "New"},
            {["price"] = 9500, ["name"] = "Dangling Star Lights", ["desc"] = "New"},
            {["price"] = 600, ["name"] = "Big Gumdrop", ["desc"] = "Happy Holidays"},
            {["price"] = 1000, ["name"] = "Big Neon Outline Cube", ["desc"] = "New"},
            {["price"] = 500, ["name"] = "Heart Mittens", ["desc"] = "New"},
            {["price"] = 500, ["name"] = "Mittens", ["desc"] = "New"},
            {["price"] = 700, ["name"] = "Holiday Bells", ["desc"] = "New"},
            {["price"] = 800, ["name"] = "Holiday Wreath", ["desc"] = "New"},
            {["price"] = 510, ["name"] = "Hot Chocolate", ["desc"] = "New"},
            {["price"] = 510, ["name"] = "Hot Chocolate 2", ["desc"] = "New"},
            {["price"] = 650, ["name"] = "Holiday Drink", ["desc"] = "New"},
            {["price"] = 500, ["name"] = "Icicle", ["desc"] = "New"},
            {["price"] = 1000, ["name"] = "Icicles", ["desc"] = "New"},
            {["price"] = 500, ["name"] = "Neon Outline Cube", ["desc"] = "New"},
            {["price"] = 1000, ["name"] = "Neon Outline Lantern", ["desc"] = "New"},
            {["price"] = 2000, ["name"] = "Fluffy Cloud Pillow", ["desc"] = "New"},
            {["price"] = 350, ["name"] = "Snowflake", ["desc"] = "New"},
            {["price"] = 350, ["name"] = "Christmas Cookie", ["desc"] = "Click this item to eat it!"},
            {["price"] = 350, ["name"] = "Star Cookie", ["desc"] = "Click this item to eat it!"},
            {["price"] = 2500, ["name"] = "Colorable Flower Pillow", ["desc"] = "New"},
            {["price"] = 2000, ["name"] = "Massive Glowing Candy Cane", ["desc"] = "New"},
            {["price"] = 2000, ["name"] = "Massive Candy Cane", ["desc"] = "New"},
            {["price"] = 600, ["name"] = "Peppermint Pole", ["desc"] = "New"},
            {["price"] = 600, ["name"] = "Sideways Peppermint Pole", ["desc"] = "New"},
            {["price"] = 650, ["name"] = "Glowing Peppermint Pole", ["desc"] = "New"},
            {["price"] = 650, ["name"] = "Sideways Glowing Peppermint Pole", ["desc"] = "New"},
            {["price"] = 350, ["name"] = "Glowing Ball", ["desc"] = "New"},
            {["price"] = 350, ["name"] = "Scaffolding 1 Stud", ["desc"] = "Used to easily elevate where you can place"},
            {["price"] = 350, ["name"] = "Scaffolding 2 Studs", ["desc"] = "Used to easily elevate where you can place"},
            {["price"] = 350, ["name"] = "Scaffolding 3 Studs", ["desc"] = "Used to easily elevate where you can place"},
            {["price"] = 350, ["name"] = "Scaffolding 4 Studs", ["desc"] = "Used to easily elevate where you can place"},
            {["price"] = 350, ["name"] = "Scaffolding 5 Studs", ["desc"] = "Used to easily elevate where you can place"},
            {["price"] = 350, ["name"] = "Scaffolding 6 Studs", ["desc"] = "Used to easily elevate where you can place"}
        },
        ["Food"] = {
            {["name"] = "Turkey", ["price"] = 800},
            {["name"] = "Kawaii Turkey", ["price"] = 800},
            {["name"] = "Turkey Leg", ["price"] = 400},
            {["name"] = "Smore", ["price"] = 100},
            {["name"] = "Cookie", ["price"] = 100},
            {["name"] = "Flan", ["price"] = 150},
            {["name"] = "Pancakes", ["price"] = 250},
            {["name"] = "Jelly", ["price"] = 150},
            {["name"] = "Lollipop 1", ["price"] = 150},
            {["name"] = "Lollipop 2", ["price"] = 150},
            {["name"] = "Candy Corn", ["price"] = 800},
            {["name"] = "Candy Bowl", ["price"] = 1000},
            {["name"] = "Rainbow Frosted Cookie", ["price"] = 200},
            {["name"] = "Pink Frosted Cookie", ["price"] = 200},
            {["name"] = "Yellow Frosted Cookie", ["price"] = 200},
            {["name"] = "White Frosted Cookie", ["price"] = 200},
            {["name"] = "Flower Cat Cookie", ["price"] = 300},
            {["name"] = "Blue Flower Cat Cookie", ["price"] = 300},
            {["name"] = "Donut", ["price"] = 120},
            {["name"] = "Donut (Sprinkles)", ["price"] = 120},
            {["name"] = "Donut (Rainbow Sprinkles)", ["price"] = 120},
            {["name"] = "Mochi Bowl", ["price"] = 400},
            {["name"] = "Strawberry Bowl", ["price"] = 1000},
            {["name"] = "Apple Pie", ["price"] = 1000},
            {["name"] = "Cherry Pie", ["price"] = 1000},
            {["name"] = "Blueberry Pie", ["price"] = 1000},
            {["name"] = "Pumpkin Pie", ["price"] = 1000},
            {["name"] = "Apple Pie Slice", ["price"] = 300},
            {["name"] = "Cherry Pie Slice", ["price"] = 300},
            {["name"] = "Blueberry Pie Slice", ["price"] = 300},
            {["name"] = "Pumpkin Pie Slice", ["price"] = 300},
            {["name"] = "Strawberry Cake Slice", ["price"] = 250},
            {["name"] = "Cake Slice Vanilla", ["price"] = 200},
            {["name"] = "Sprinkles Slice Vanilla", ["price"] = 200},
            {["name"] = "Cake Slice Chocolate", ["price"] = 200},
            {["name"] = "Sprinkles Slice Chocolate", ["price"] = 200},
            {["name"] = "Cake 1", ["price"] = 1000},
            {["name"] = "Cake 2", ["price"] = 1000},
            {["name"] = "Big Cake 1", ["price"] = 1500},
            {["name"] = "Big Cake 2", ["price"] = 1500},
            {["name"] = "Cake Candle", ["price"] = 100},
            {["name"] = "Ice Cream Cone", ["price"] = 500},
            {["name"] = "Soft Serve Ice Cream Cone", ["price"] = 500},
            {["name"] = "Vanilla Ice Cream", ["price"] = 400},
            {["name"] = "Chocolate Ice Cream", ["price"] = 400},
            {["name"] = "Strawberry Ice Cream", ["price"] = 400},
            {["name"] = "Waffle", ["price"] = 115},
            {["name"] = "Cereal", ["price"] = 120},
            {["name"] = "Sandwich", ["price"] = 200},
            {["name"] = "Lunch Bag", ["price"] = 500},
            {["name"] = "Hot Dog", ["price"] = 500},
            {["name"] = "Hot Dog 2", ["price"] = 500},
            {["name"] = "Chicken Sandwich", ["price"] = 400},
            {["name"] = "Burger", ["price"] = 900},
            {["name"] = "Chicken Nuggets", ["price"] = 300},
            {["name"] = "Red Chicken Nuggets Box", ["price"] = 350},
            {["name"] = "White Chicken Nuggets Box", ["price"] = 350},
            {["name"] = "Black Chicken Nuggets Box", ["price"] = 350},
            {["name"] = "Rice Bowl", ["price"] = 150},
            {["name"] = "Bento Box", ["price"] = 2000},
            {["name"] = "Mac and Cheese Bowl", ["price"] = 300},
            {["name"] = "Pizza", ["price"] = 800},
            {["name"] = "Jiggly Cheesecake", ["price"] = 700},
            {["name"] = "Bread rolls", ["price"] = 500},
            {["name"] = "Ketchup & Mustard", ["price"] = 120},
            {["name"] = "Nacho Chips", ["price"] = 200},
            {["name"] = "Cool Cowboy Chips", ["price"] = 200},
            {["name"] = "Bananas", ["price"] = 400},
            {["name"] = "Loaf Of Bread", ["price"] = 280},
            {["name"] = "Peanut Butter", ["price"] = 400},
            {["name"] = "Strawberry Jam", ["price"] = 200},
            {["name"] = "Grape Jam", ["price"] = 200},
            {["name"] = "Blueberry Jam", ["price"] = 200},
            {["name"] = "Orange Marmelade", ["price"] = 200},
            {["name"] = "Pink Strawberry Cake", ["price"] = 200},
            {["name"] = "Cupcake", ["price"] = 300},
            {["name"] = "White Cupcake", ["price"] = 300},
            {["name"] = "Double Chocolate Cupcake", ["price"] = 300},
            {["name"] = "Blue Cupcake", ["price"] = 300},
            {["name"] = "Cherry Cupcake", ["price"] = 300},
            {["name"] = "Kitty Cupcake", ["price"] = 800},
            {["name"] = "Cheesecake", ["price"] = 270},
            {["name"] = "New York Cheesecake", ["price"] = 270},
            {["name"] = "Strawberry Cheesecake", ["price"] = 270},
            {["name"] = "Watermelon Slice", ["price"] = 150},
            {["name"] = "Watermelon Line", ["price"] = 150},
            {["name"] = "Watermelons", ["price"] = 150},
            {["name"] = "Strawberry Basket", ["price"] = 150},
            {["name"] = "Blueberry Basket", ["price"] = 150},
            {["name"] = "Raspberry Basket", ["price"] = 150}
        },
        ["Plates"] = {
            {["name"] = "Plate", ["price"] = 300},
            {["name"] = "Tea Plate", ["price"] = 150},
            {["name"] = "Medium Plate", ["price"] = 400},
            {["name"] = "Large Plate", ["price"] = 500},
            {["name"] = "Oval Plate", ["price"] = 700},
            {["name"] = "Square Plate", ["price"] = 300},
            {["name"] = "Square Plate Large", ["price"] = 500},
            {["name"] = "Rectangle Plate", ["price"] = 700},
            {["name"] = "Rectangle Platter", ["price"] = 600},
            {["name"] = "Heart Plate", ["price"] = 1500},
            {["name"] = "Wooden Platter", ["price"] = 2000},
            {["name"] = "Fork", ["price"] = 250},
            {["name"] = "Spoon", ["price"] = 250},
            {["name"] = "Knife", ["price"] = 800}
        },
        ["Special"] = {
            {["name"] = "Pink Round Bunny Plush", ["price"] = 5000},
            {["name"] = "White Round Bunny Plush", ["price"] = 5000},
            {["name"] = "Blue Round Bunny Plush", ["price"] = 5000},
            {["name"] = "Black Round Bunny Plush", ["price"] = 5000},
            {["name"] = "Round Bear Plush", ["price"] = 5000},
            {["name"] = "Round Panda Plush", ["price"] = 5000},
            {["name"] = "Round Frog", ["price"] = 5000},
            {["name"] = "Squid Plushie", ["price"] = 5000},
            {["name"] = "Mushroom Plush", ["price"] = 5500},
            {["name"] = "Tiny Mushroom Plush", ["price"] = 5000},
            {["name"] = "Green Mushroom Plush", ["price"] = 5500},
            {["name"] = "Tiny Green Mushroom Plush", ["price"] = 5000},
            {["name"] = "Purple Mushroom Plush", ["price"] = 5500},
            {["name"] = "Tiny Purple Mushroom Plush", ["price"] = 5000},
            {["name"] = "Proto Bunny", ["price"] = 3000},
            {["name"] = "Build A Bear", ["price"] = 12000},
            {["name"] = "Build A Bear (Sweater)", ["price"] = 15000},
            {["name"] = "Build A Kitty", ["price"] = 9000},
            {["name"] = "Build A Pony", ["price"] = 9000},
            {["name"] = "Build A Pony 2", ["price"] = 9000},
            {["name"] = "Quackles", ["price"] = 8000},
            {["name"] = "Round Cat", ["price"] = 8000},
            {["name"] = "Small Loaf Cat", ["price"] = 6500},
            {["name"] = "Loaf Cat", ["price"] = 7000},
            {["name"] = "Big Loaf Cat", ["price"] = 10000},
            {["name"] = "Beige Big Teddy Bear", ["price"] = 15000},
            {["name"] = "Brown Big Teddy Bear", ["price"] = 15000},
            {["price"] = 30000, ["name"] = "The Grand Princess Palace", ["desc"] = "The ultimate doll house"},
            {["name"] = "Suspicious Bunny", ["price"] = 8000},
            {["name"] = "Bat Cat", ["price"] = 8500},
            {["name"] = "Bat Cat 2", ["price"] = 8500},
            {
                ["price"] = 999999999,
                ["name"] = "Morphist Plushie",
                ["desc"] = "Rarely given out for free by the game owner, Morphist"
            },
            {
                ["price"] = 999999999,
                ["name"] = "Festive Morphist Plushie",
                ["desc"] = "use code Present1 to claim, limited time only"
            },
            {["price"] = 999999999, ["name"] = "Snowson", ["desc"] = "use code Present2 to claim, limited time only"}
        },
        ["Drinks"] = {
            {["name"] = "Pitcher Glass", ["price"] = 300},
            {["name"] = "Drink Glass", ["price"] = 150},
            {["name"] = "Drink Glass (Straw)", ["price"] = 150},
            {["name"] = "Short Drink Glass", ["price"] = 150},
            {["name"] = "Tall Drink Glass", ["price"] = 200},
            {["name"] = "Tropical Drink Glass", ["price"] = 200},
            {["name"] = "Slushie", ["price"] = 600},
            {["name"] = "Tropical Ice Drink", ["price"] = 700},
            {["name"] = "Fancy Glass", ["price"] = 600},
            {["name"] = "Tall Fancy Glass", ["price"] = 600},
            {["name"] = "Soda Bottle", ["price"] = 200},
            {["name"] = "Soda Can", ["price"] = 120},
            {["name"] = "Chocolate Milk Carton", ["price"] = 250},
            {["name"] = "Strawberry Milk Carton", ["price"] = 250},
            {["name"] = "Vanilla Milk Carton", ["price"] = 250},
            {["name"] = "Milk Bottle", ["price"] = 300},
            {["name"] = "Chocolate Milk Bottle", ["price"] = 300},
            {["name"] = "Strawberry Milk Bottle", ["price"] = 300},
            {["name"] = "Pink Baby Milk Bottle", ["price"] = 550},
            {["name"] = "Blue Baby Milk Bottle", ["price"] = 550},
            {["name"] = "Teacup", ["price"] = 300},
            {["name"] = "Teapot (White Accent)", ["price"] = 800},
            {["name"] = "Teapot (Black Accent)", ["price"] = 800},
            {["name"] = "Floral Teapot", ["price"] = 850},
            {["name"] = "Boba Tea", ["price"] = 500},
            {["name"] = "Milk Boba Tea", ["price"] = 500},
            {["name"] = "Blue Boba Tea", ["price"] = 500},
            {["name"] = "Ube Boba Tea", ["price"] = 500},
            {["name"] = "Strawberry Boba Tea", ["price"] = 500},
            {["name"] = "Vanilla Milkshake", ["price"] = 650},
            {["name"] = "Chocolate Milkshake", ["price"] = 650},
            {["name"] = "Strawberry Milkshake", ["price"] = 650}
        },
        ["Decor"] = {
            {["price"] = 3000, ["name"] = "Skull", ["desc"] = "Seasonal Item"},
            {["price"] = 8000, ["name"] = "Bean Bag", ["desc"] = "..."},
            {["price"] = 9000, ["name"] = "Kitty Bean Bag", ["desc"] = "..."},
            {["price"] = 4500, ["name"] = "Glowing Skull", ["desc"] = "Seasonal Item"},
            {["price"] = 4500, ["name"] = "Standing Glowing Skull", ["desc"] = "Seasonal Item"},
            {["price"] = 1800, ["name"] = "Wall Skull", ["desc"] = "Seasonal Item"},
            {["price"] = 1000, ["name"] = "Pumpkin", ["desc"] = "Seasonal Item"},
            {["price"] = 1000, ["name"] = "Tiny Pumpkin", ["desc"] = "Seasonal Item"},
            {["price"] = 1000, ["name"] = "Flat Pumpkin", ["desc"] = "Seasonal Item"},
            {["price"] = 1000, ["name"] = "Square Pumpkin", ["desc"] = "Seasonal Item"},
            {["price"] = 1000, ["name"] = "Tall Pumpkin", ["desc"] = "Seasonal Item"},
            {["price"] = 5000, ["name"] = "Prize Winning Pumpkin", ["desc"] = "Seasonal Item"},
            {["price"] = 6500, ["name"] = "Cauldron", ["desc"] = "Seasonal Item"},
            {["price"] = 1500, ["name"] = "Bone", ["desc"] = "Seasonal Item"},
            {["price"] = 1500, ["name"] = "Standing Bone", ["desc"] = "Seasonal Item"},
            {["price"] = 2500, ["name"] = "Pile Of Bones", ["desc"] = "Seasonal Item"},
            {["price"] = 9000, ["name"] = "Sharp Bones", ["desc"] = "Seasonal Item"},
            {["price"] = 3000, ["name"] = "Gravestone 1", ["desc"] = "Seasonal Item"},
            {["price"] = 3000, ["name"] = "Gravestone 2", ["desc"] = "Seasonal Item"},
            {["price"] = 4000, ["name"] = "Hanging Chain", ["desc"] = "Seasonal Item"},
            {["price"] = 7000, ["name"] = "Chain", ["desc"] = "Seasonal Item"},
            {["price"] = 800, ["name"] = "Beaker 1", ["desc"] = "Seasonal Item"},
            {["price"] = 800, ["name"] = "Beaker 2", ["desc"] = "Seasonal Item"},
            {["price"] = 800, ["name"] = "Beaker 3", ["desc"] = "Seasonal Item"},
            {["price"] = 500, ["name"] = "Test Tube", ["desc"] = "Seasonal Item"},
            {["price"] = 1500, ["name"] = "Test Tube Rack", ["desc"] = "Seasonal Item"},
            {["price"] = 15000, ["name"] = "Kiddie Pool Side", ["desc"] = "Seasonal Item"},
            {["price"] = 5000, ["name"] = "Pool Water", ["desc"] = "Seasonal Item"},
            {["price"] = 1000, ["name"] = "Starfish", ["desc"] = "Seasonal Item"},
            {["price"] = 1000, ["name"] = "Big Starfish", ["desc"] = "Seasonal Item"},
            {["price"] = 100, ["name"] = "Wood Block", ["desc"] = "A wooden block"},
            {["price"] = 100, ["name"] = "Plastic Block", ["desc"] = "A plastic block"},
            {["price"] = 200, ["name"] = "Slab", ["desc"] = "For building"},
            {["price"] = 200, ["name"] = "Vertical Slab", ["desc"] = "For building"},
            {["price"] = 200, ["name"] = "Wood Slab", ["desc"] = "For building"},
            {["price"] = 200, ["name"] = "Vertical Wood Slab", ["desc"] = "For building"},
            {["price"] = 200, ["name"] = "Brick Slab", ["desc"] = "For building"},
            {["price"] = 200, ["name"] = "Vertical Brick Slab", ["desc"] = "For building"},
            {["price"] = 200, ["name"] = "Glass Slab", ["desc"] = "For building"},
            {["price"] = 200, ["name"] = "Vertical Glass Slab", ["desc"] = "For building"},
            {["price"] = 100, ["name"] = "Brick Block", ["desc"] = "A brick block"},
            {["price"] = 100, ["name"] = "Stone Block", ["desc"] = "A stone block"},
            {["price"] = 300, ["name"] = "Metal Block", ["desc"] = "A metal block"},
            {["price"] = 800, ["name"] = "Bow", ["desc"] = "A Decoration"},
            {["price"] = 500, ["name"] = "Heart", ["desc"] = "A Decoration"},
            {["price"] = 1000, ["name"] = "Glowing Heart", ["desc"] = "A Decoration"},
            {["price"] = 500, ["name"] = "Star", ["desc"] = "A Decoration"},
            {["price"] = 500, ["name"] = "Flat Star", ["desc"] = "A Decoration"},
            {["price"] = 1000, ["name"] = "Glowing Star", ["desc"] = "A Decoration"},
            {["price"] = 1000, ["name"] = "Glowing Flat Star", ["desc"] = "A Decoration"},
            {["price"] = 1000, ["name"] = "Cute Flower", ["desc"] = "A Decoration"},
            {["price"] = 300, ["name"] = "Transparent Block", ["desc"] = "A glowing neon block"},
            {["price"] = 400, ["name"] = "Neon Block", ["desc"] = "A glowing neon block"},
            {["name"] = "Plastic Ball", ["price"] = 130},
            {["price"] = 600, ["name"] = "Pillar", ["desc"] = "Who on Earth brings this to a picnic?"},
            {["price"] = 500, ["name"] = "Pillar Single", ["desc"] = "Who on Earth brings this to a picnic?"},
            {["price"] = 300, ["name"] = "Display Pole", ["desc"] = "A Decoration"},
            {["price"] = 300, ["name"] = "Pole", ["desc"] = "A Decoration"},
            {["price"] = 300, ["name"] = "Pole Thin", ["desc"] = "A Decoration"},
            {["price"] = 100, ["name"] = "Picnic Basket", ["desc"] = "An essential item to every picnic"},
            {["price"] = 2000, ["name"] = "Cute Picnic Basket", ["desc"] = "An essential item to every picnic"},
            {["price"] = 1500, ["name"] = "Balloons", ["desc"] = "A Decoration"},
            {["price"] = 800, ["name"] = "Candles", ["desc"] = "3 candles is better than one"},
            {["price"] = 250, ["name"] = "Tall Candle", ["desc"] = "A Decoration"},
            {["price"] = 500, ["name"] = "Iron Candle", ["desc"] = "A Decoration"},
            {["price"] = 500, ["name"] = "Torch", ["desc"] = "Light up the night"},
            {["price"] = 600, ["name"] = "Candle Lantern", ["desc"] = "A Decoration"},
            {["price"] = 15000, ["name"] = "Neon Arch", ["desc"] = "A Decoration"},
            {["price"] = 1500, ["name"] = "High Tech Lamp (Black base)", ["desc"] = "A Decoration"},
            {["price"] = 1500, ["name"] = "High Tech Lamp (White base)", ["desc"] = "A Decoration"},
            {["price"] = 8000, ["name"] = "Leaf Wreath", ["desc"] = "A Decoration"},
            {["price"] = 800, ["name"] = "Mushroom", ["desc"] = "A Decoration"},
            {["price"] = 1000, ["name"] = "Glowing Mushroom", ["desc"] = "A Decoration"},
            {["price"] = 800, ["name"] = "Mushroom 2", ["desc"] = "A Decoration"},
            {["price"] = 1000, ["name"] = "Glowing Mushroom 2", ["desc"] = "A Decoration"},
            {["price"] = 8000, ["name"] = "Fairy Lights", ["desc"] = "A Decoration"},
            {["price"] = 5000, ["name"] = "Fairy Lights Pole (black)", ["desc"] = "A Decoration"},
            {["price"] = 5000, ["name"] = "Fairy Lights Pole (white)", ["desc"] = "A Decoration"},
            {["price"] = 5000, ["name"] = "Fairy Lights Pole (pink)", ["desc"] = "A Decoration"},
            {["price"] = 9000, ["name"] = "Silk Curtains Open", ["desc"] = "A Decoration"},
            {["price"] = 9000, ["name"] = "Tattered Curtains Open", ["desc"] = "A Decoration"},
            {["price"] = 7000, ["name"] = "Silk Curtains", ["desc"] = "A Decoration"},
            {["price"] = 6000, ["name"] = "Silk Curtain Roof", ["desc"] = "A Decoration"},
            {["price"] = 6000, ["name"] = "Silk Curtain Roof 2", ["desc"] = "A Decoration"},
            {["price"] = 15000, ["name"] = "Fluffy Clouds", ["desc"] = "Fluffy soft clouds to relax on"},
            {["price"] = 20000, ["name"] = "Magical Clouds", ["desc"] = "These clouds sparkle"},
            {["price"] = 4000, ["name"] = "Spikes", ["desc"] = "A Decoration"},
            {["price"] = 5500, ["name"] = "Spike Row", ["desc"] = "A Decoration"},
            {["price"] = 2000, ["name"] = "Colorable Standing Book", ["desc"] = "A Decoration"},
            {["price"] = 2000, ["name"] = "Colorable Book", ["desc"] = "A Decoration"},
            {["price"] = 2000, ["name"] = "Colorable Book Open", ["desc"] = "A Decoration"},
            {["price"] = 800, ["name"] = "Book 1", ["desc"] = "A Decoration"},
            {["price"] = 800, ["name"] = "Book 2", ["desc"] = "A Decoration"},
            {["price"] = 800, ["name"] = "Open Book 1", ["desc"] = "A Decoration"},
            {["price"] = 800, ["name"] = "Open Book 2", ["desc"] = "A Decoration"},
            {["price"] = 800, ["name"] = "Photo Frame 1", ["desc"] = "Nom"},
            {["price"] = 800, ["name"] = "Photo Frame 2", ["desc"] = "The cat"},
            {["price"] = 800, ["name"] = "Photo Frame 3", ["desc"] = "you rn"},
            {["price"] = 800, ["name"] = "Photo Frame 4", ["desc"] = "Refreshment"},
            {
                ["price"] = 500,
                ["name"] = "Summer Contest Winner 2023",
                ["desc"] = "Winning summer themed blanket made by wymi (quokyi)"
            },
            {["price"] = 1500, ["name"] = "Strawberry Pillow", ["desc"] = "A Decoration"},
            {["price"] = 1500, ["name"] = "Pink Strawberry Pillow", ["desc"] = "A Decoration"},
            {["price"] = 700, ["name"] = "Pillow", ["desc"] = "A Decoration"},
            {["price"] = 600, ["name"] = "Square Pillow", ["desc"] = "A Decoration"},
            {["price"] = 600, ["name"] = "Striped Pillow", ["desc"] = "A Decoration"},
            {["price"] = 650, ["name"] = "Plaid Pillow", ["desc"] = "A Decoration"},
            {["price"] = 650, ["name"] = "Polka Dots Pillow", ["desc"] = "A Decoration"},
            {["price"] = 2000, ["name"] = "Star Pillow", ["desc"] = "A Decoration"},
            {["price"] = 2000, ["name"] = "Round Cushion", ["desc"] = "A Decoration"},
            {["price"] = 2500, ["name"] = "Yellow Flower Pillow", ["desc"] = "A Decoration"},
            {["price"] = 2500, ["name"] = "Green Flower Pillow", ["desc"] = "A Decoration"},
            {["price"] = 2500, ["name"] = "Black Flower Pillow", ["desc"] = "A Decoration"},
            {["price"] = 2500, ["name"] = "Brown Flower Pillow", ["desc"] = "A Decoration"},
            {["price"] = 2500, ["name"] = "Orange Flower Pillow", ["desc"] = "A Decoration"},
            {["price"] = 2500, ["name"] = "Blue Flower Pillow", ["desc"] = "A Decoration"},
            {["price"] = 2500, ["name"] = "Red Flower Pillow", ["desc"] = "A Decoration"},
            {["price"] = 600, ["name"] = "Scented Candle", ["desc"] = "A Decoration"},
            {["price"] = 2250, ["name"] = "Potted Plant 1", ["desc"] = "A Decoration"},
            {["price"] = 2250, ["name"] = "Potted Plant 2", ["desc"] = "A Decoration"},
            {["price"] = 2250, ["name"] = "Potted Plant 3", ["desc"] = "A Decoration"},
            {["price"] = 2250, ["name"] = "Potted Plant 4", ["desc"] = "A Decoration"},
            {["price"] = 2000, ["name"] = "Pink Heart Light", ["desc"] = "A Decoration"},
            {["price"] = 2000, ["name"] = "White Heart Light", ["desc"] = "A Decoration"},
            {["price"] = 2000, ["name"] = "Yellow Star Light", ["desc"] = "A Decoration"},
            {["price"] = 2000, ["name"] = "White Star Light", ["desc"] = "A Decoration"},
            {["price"] = 1500, ["name"] = "Neon Blocks Light", ["desc"] = "A Decoration"}
        }
    },
    ["WheelItemsRewarded"] = {
        "Jingle Bella",
        "Cozy Penguini",
        "Santa Burger Kitty",
        "Rudolph",
        "Reindeer",
        "Swag Pony",
        "Strawbie"
    },
    ["LikeBroadcastColor"] = "rgb(255, 170, 255)",
    ["DailyRewardsDayCompletedImage"] = "rbxassetid://15383077013",
    ["WishChance"] = 3,
    ["x2CashGamepassId"] = 659630123
}
