data = {
    ["Items"] = {
        ["Shotgun"] = {
            ["OverviewDetails"] = {{1, "• Deadly up close"}},
            ["DataNames"] = {
                "StatisticPlaytime",
                "StatisticPlaytimeUnequipped",
                "StatisticRoundsPlayed",
                "StatisticRoundsWon",
                "StatisticRoundsLost",
                "StatisticRoundsWinPercent",
                "StatisticDamageDealt",
                "StatisticDamageDealtSliding",
                "StatisticDamageDealtCrouching",
                "StatisticDamageDealtAirborne",
                "StatisticDamageDealtBlinded",
                "StatisticDamageDealtDead",
                "StatisticEliminations",
                "StatisticEliminationsSliding",
                "StatisticEliminationsCrouching",
                "StatisticEliminationsAirborne",
                "StatisticEliminationsBlinded",
                "StatisticEliminationsDead",
                "StatisticDeaths",
                "StatisticDeathsRatio",
                "StatisticAssists",
                "StatisticAssistsDead",
                "StatisticUses",
                "StatisticUsesHits",
                "StatisticUsesHitPercent",
                "StatisticUsesCriticalHits",
                "StatisticUsesCriticalHitPercent",
                "StatisticInspects",
                "StatisticInspectsAfterElimination",
                "StatisticAmmoUsed",
                "StatisticReloads"
            }
        },
        ["Grenade Launcher"] = {
            ["OverviewDetails"] = {{2, "• Quickly rain explosives on your enemies"}},
            ["DataNames"] = {
                "StatisticPlaytime",
                "StatisticPlaytimeUnequipped",
                "StatisticRoundsPlayed",
                "StatisticRoundsWon",
                "StatisticRoundsLost",
                "StatisticRoundsWinPercent",
                "StatisticDamageDealt",
                "StatisticDamageDealtSliding",
                "StatisticDamageDealtCrouching",
                "StatisticDamageDealtAirborne",
                "StatisticDamageDealtBlinded",
                "StatisticDamageDealtDead",
                "StatisticEliminations",
                "StatisticEliminationsSliding",
                "StatisticEliminationsCrouching",
                "StatisticEliminationsAirborne",
                "StatisticEliminationsBlinded",
                "StatisticEliminationsDead",
                "StatisticDeaths",
                "StatisticDeathsRatio",
                "StatisticAssists",
                "StatisticAssistsDead",
                "StatisticUses",
                "StatisticUsesHitsSelf",
                "StatisticUsesHits",
                "StatisticUsesHitPercent",
                "StatisticUsesHitsDirect",
                "StatisticInspects",
                "StatisticInspectsAfterElimination",
                "StatisticAmmoUsed",
                "StatisticReloads"
            }
        },
        ["Medkit"] = {
            ["OverviewDetails"] = {{3, "• Allows you to heal in the midst of a battle"}},
            ["DataNames"] = {
                "StatisticPlaytime",
                "StatisticPlaytimeUnequipped",
                "StatisticRoundsPlayed",
                "StatisticRoundsWon",
                "StatisticRoundsLost",
                "StatisticRoundsWinPercent",
                "StatisticDeaths",
                "StatisticUses",
                "StatisticUsesQuick",
                "StatisticInspects",
                "StatisticInspectsAfterElimination",
                "StatisticHealsGiven"
            }
        },
        ["Burst Rifle"] = {
            ["OverviewDetails"] = {{2, "• Hit and run with this three-round burst rifle"}},
            ["DataNames"] = {
                "StatisticPlaytime",
                "StatisticPlaytimeUnequipped",
                "StatisticRoundsPlayed",
                "StatisticRoundsWon",
                "StatisticRoundsLost",
                "StatisticRoundsWinPercent",
                "StatisticDamageDealt",
                "StatisticDamageDealtSliding",
                "StatisticDamageDealtCrouching",
                "StatisticDamageDealtAirborne",
                "StatisticDamageDealtBlinded",
                "StatisticDamageDealtDead",
                "StatisticEliminations",
                "StatisticEliminationsSliding",
                "StatisticEliminationsCrouching",
                "StatisticEliminationsAirborne",
                "StatisticEliminationsBlinded",
                "StatisticEliminationsDead",
                "StatisticDeaths",
                "StatisticDeathsRatio",
                "StatisticAssists",
                "StatisticAssistsDead",
                "StatisticUses",
                "StatisticUsesHits",
                "StatisticUsesHitPercent",
                "StatisticUsesCriticalHits",
                "StatisticUsesCriticalHitPercent",
                "StatisticInspects",
                "StatisticInspectsAfterElimination",
                "StatisticAmmoUsed",
                "StatisticReloads"
            }
        },
        ["Sniper"] = {
            ["OverviewDetails"] = {{3, "• Long ranged rifle that can deal devastating damage"}},
            ["DataNames"] = {
                "StatisticPlaytime",
                "StatisticPlaytimeUnequipped",
                "StatisticRoundsPlayed",
                "StatisticRoundsWon",
                "StatisticRoundsLost",
                "StatisticRoundsWinPercent",
                "StatisticDamageDealt",
                "StatisticDamageDealtSliding",
                "StatisticDamageDealtCrouching",
                "StatisticDamageDealtAirborne",
                "StatisticDamageDealtBlinded",
                "StatisticDamageDealtDead",
                "StatisticDamageDealtNoscope",
                "StatisticEliminations",
                "StatisticEliminationsSliding",
                "StatisticEliminationsCrouching",
                "StatisticEliminationsAirborne",
                "StatisticEliminationsBlinded",
                "StatisticEliminationsDead",
                "StatisticEliminationsNoscope",
                "StatisticDeaths",
                "StatisticDeathsRatio",
                "StatisticAssists",
                "StatisticAssistsDead",
                "StatisticUses",
                "StatisticUsesHits",
                "StatisticUsesHitPercent",
                "StatisticUsesCriticalHits",
                "StatisticUsesCriticalHitPercent",
                "StatisticInspects",
                "StatisticInspectsAfterElimination",
                "StatisticAmmoUsed",
                "StatisticReloads"
            }
        },
        ["Freeze Ray"] = {
            ["OverviewDetails"] = {
                {3, "• Freeze your enemies with this splash projectile weapon!"},
                {3, "• Frozen enemies can't move but can still shoot back!"}
            },
            ["DataNames"] = {
                "StatisticPlaytime",
                "StatisticPlaytimeUnequipped",
                "StatisticRoundsPlayed",
                "StatisticRoundsWon",
                "StatisticRoundsLost",
                "StatisticRoundsWinPercent",
                "StatisticEliminations",
                "StatisticEliminationsSliding",
                "StatisticEliminationsCrouching",
                "StatisticEliminationsAirborne",
                "StatisticEliminationsBlinded",
                "StatisticEliminationsDead",
                "StatisticDeaths",
                "StatisticDeathsRatio",
                "StatisticAssists",
                "StatisticAssistsDead",
                "StatisticUses",
                "StatisticUsesQuick",
                "StatisticUsesHits",
                "StatisticUsesHitPercent",
                "StatisticInspects",
                "StatisticInspectsAfterElimination",
                "StatisticAmmoUsed",
                "StatisticFreezes",
                "StatisticFreezesSelf",
                "StatisticFreezesEnemies"
            }
        },
        ["Flashbang"] = {
            ["OverviewDetails"] = {{2, "• Blinds enemies for a long time"}},
            ["DataNames"] = {
                "StatisticPlaytime",
                "StatisticPlaytimeUnequipped",
                "StatisticRoundsPlayed",
                "StatisticRoundsWon",
                "StatisticRoundsLost",
                "StatisticRoundsWinPercent",
                "StatisticDamageDealt",
                "StatisticDamageDealtSliding",
                "StatisticDamageDealtCrouching",
                "StatisticDamageDealtAirborne",
                "StatisticDamageDealtBlinded",
                "StatisticDamageDealtDead",
                "StatisticEliminations",
                "StatisticEliminationsSliding",
                "StatisticEliminationsCrouching",
                "StatisticEliminationsAirborne",
                "StatisticEliminationsBlinded",
                "StatisticEliminationsDead",
                "StatisticDeaths",
                "StatisticDeathsRatio",
                "StatisticAssists",
                "StatisticAssistsDead",
                "StatisticUses",
                "StatisticUsesQuick",
                "StatisticUsesHits",
                "StatisticUsesHitPercent",
                "StatisticUsesCriticalHits",
                "StatisticUsesCriticalHitPercent",
                "StatisticInspects",
                "StatisticInspectsAfterElimination",
                "StatisticBlinds",
                "StatisticBlindsSelf",
                "StatisticBlindsEnemies",
                "StatisticBlindsTeammates"
            }
        },
        ["Shorty"] = {
            ["OverviewDetails"] = {{2, "• A quick sidearm that can be deadly up close"}},
            ["DataNames"] = {
                "StatisticPlaytime",
                "StatisticPlaytimeUnequipped",
                "StatisticRoundsPlayed",
                "StatisticRoundsWon",
                "StatisticRoundsLost",
                "StatisticRoundsWinPercent",
                "StatisticDamageDealt",
                "StatisticDamageDealtSliding",
                "StatisticDamageDealtCrouching",
                "StatisticDamageDealtAirborne",
                "StatisticDamageDealtBlinded",
                "StatisticDamageDealtDead",
                "StatisticEliminations",
                "StatisticEliminationsSliding",
                "StatisticEliminationsCrouching",
                "StatisticEliminationsAirborne",
                "StatisticEliminationsBlinded",
                "StatisticEliminationsDead",
                "StatisticDeaths",
                "StatisticDeathsRatio",
                "StatisticAssists",
                "StatisticAssistsDead",
                "StatisticUses",
                "StatisticUsesHits",
                "StatisticUsesHitPercent",
                "StatisticUsesCriticalHits",
                "StatisticUsesCriticalHitPercent",
                "StatisticInspects",
                "StatisticInspectsAfterElimination",
                "StatisticAmmoUsed",
                "StatisticReloads"
            }
        },
        ["Flamethrower"] = {
            ["OverviewDetails"] = {
                {1, "• Set your enemies on fire"},
                {3, "• Use the Airblast to push enemies away and to clear up any smoke clouds"}
            },
            ["DataNames"] = {
                "StatisticPlaytime",
                "StatisticPlaytimeUnequipped",
                "StatisticRoundsPlayed",
                "StatisticRoundsWon",
                "StatisticRoundsLost",
                "StatisticRoundsWinPercent",
                "StatisticDamageDealt",
                "StatisticDamageDealtSliding",
                "StatisticDamageDealtCrouching",
                "StatisticDamageDealtAirborne",
                "StatisticDamageDealtBlinded",
                "StatisticDamageDealtDead",
                "StatisticEliminations",
                "StatisticEliminationsSliding",
                "StatisticEliminationsCrouching",
                "StatisticEliminationsAirborne",
                "StatisticEliminationsBlinded",
                "StatisticEliminationsDead",
                "StatisticDeaths",
                "StatisticDeathsRatio",
                "StatisticAssists",
                "StatisticAssistsDead",
                "StatisticUses",
                "StatisticUsesQuick",
                "StatisticUsesHits",
                "StatisticUsesHitPercent",
                "StatisticInspects",
                "StatisticInspectsAfterElimination",
                "StatisticAmmoUsed",
                "StatisticAirblasts",
                "StatisticAirblastsHits",
                "StatisticAirblastsSmokesCleared"
            }
        },
        ["Subspace Tripmine"] = {
            ["OverviewDetails"] = {{3, "• This invisible explosive deals heavy damage and sends enemies flying"}},
            ["DataNames"] = {
                "StatisticPlaytime",
                "StatisticPlaytimeUnequipped",
                "StatisticRoundsPlayed",
                "StatisticRoundsWon",
                "StatisticRoundsLost",
                "StatisticRoundsWinPercent",
                "StatisticDamageDealt",
                "StatisticDamageDealtSliding",
                "StatisticDamageDealtCrouching",
                "StatisticDamageDealtAirborne",
                "StatisticDamageDealtBlinded",
                "StatisticDamageDealtDead",
                "StatisticEliminations",
                "StatisticEliminationsSliding",
                "StatisticEliminationsCrouching",
                "StatisticEliminationsAirborne",
                "StatisticEliminationsBlinded",
                "StatisticEliminationsDead",
                "StatisticDeaths",
                "StatisticDeathsRatio",
                "StatisticAssists",
                "StatisticAssistsDead",
                "StatisticUses",
                "StatisticUsesQuick",
                "StatisticUsesHitsSelf",
                "StatisticUsesHits",
                "StatisticUsesHitPercent",
                "StatisticInspects",
                "StatisticInspectsAfterElimination"
            }
        },
        ["Knife"] = {
            ["OverviewDetails"] = {{2, "• Backstab enemies for an instant elimination"}},
            ["DataNames"] = {
                "StatisticPlaytime",
                "StatisticPlaytimeUnequipped",
                "StatisticRoundsPlayed",
                "StatisticRoundsWon",
                "StatisticRoundsLost",
                "StatisticRoundsWinPercent",
                "StatisticDamageDealt",
                "StatisticDamageDealtSliding",
                "StatisticDamageDealtCrouching",
                "StatisticDamageDealtAirborne",
                "StatisticDamageDealtBlinded",
                "StatisticDamageDealtDead",
                "StatisticEliminations",
                "StatisticEliminationsSliding",
                "StatisticEliminationsCrouching",
                "StatisticEliminationsAirborne",
                "StatisticEliminationsBlinded",
                "StatisticEliminationsDead",
                "StatisticDeaths",
                "StatisticDeathsRatio",
                "StatisticAssists",
                "StatisticAssistsDead",
                "StatisticUses",
                "StatisticUsesQuick",
                "StatisticUsesHits",
                "StatisticUsesHitPercent",
                "StatisticUsesCriticalHits",
                "StatisticUsesCriticalHitPercent",
                "StatisticInspects",
                "StatisticInspectsAfterElimination"
            }
        },
        ["Chainsaw"] = {
            ["OverviewDetails"] = {{2, "• Mow enemies down at frightening speeds"}},
            ["DataNames"] = {
                "StatisticPlaytime",
                "StatisticPlaytimeUnequipped",
                "StatisticRoundsPlayed",
                "StatisticRoundsWon",
                "StatisticRoundsLost",
                "StatisticRoundsWinPercent",
                "StatisticDamageDealt",
                "StatisticDamageDealtSliding",
                "StatisticDamageDealtCrouching",
                "StatisticDamageDealtAirborne",
                "StatisticDamageDealtBlinded",
                "StatisticDamageDealtDead",
                "StatisticEliminations",
                "StatisticEliminationsSliding",
                "StatisticEliminationsCrouching",
                "StatisticEliminationsAirborne",
                "StatisticEliminationsBlinded",
                "StatisticEliminationsDead",
                "StatisticDeaths",
                "StatisticDeathsRatio",
                "StatisticAssists",
                "StatisticAssistsDead",
                "StatisticUses",
                "StatisticUsesQuick",
                "StatisticUsesHits",
                "StatisticUsesHitPercent",
                "StatisticInspects",
                "StatisticInspectsAfterElimination",
                "StatisticAmmoUsed"
            }
        },
        ["Bow"] = {
            ["OverviewDetails"] = {
                {2, "• Projectile weapon that rewards accuracy"},
                {2, "• Charge up your arrows to deal heavy damage"},
                {1, "• Allows you to double jump"}
            },
            ["DataNames"] = {
                "StatisticPlaytime",
                "StatisticPlaytimeUnequipped",
                "StatisticRoundsPlayed",
                "StatisticRoundsWon",
                "StatisticRoundsLost",
                "StatisticRoundsWinPercent",
                "StatisticDamageDealt",
                "StatisticDamageDealtSliding",
                "StatisticDamageDealtCrouching",
                "StatisticDamageDealtAirborne",
                "StatisticDamageDealtBlinded",
                "StatisticDamageDealtDead",
                "StatisticEliminations",
                "StatisticEliminationsSliding",
                "StatisticEliminationsCrouching",
                "StatisticEliminationsAirborne",
                "StatisticEliminationsBlinded",
                "StatisticEliminationsDead",
                "StatisticDeaths",
                "StatisticDeathsRatio",
                "StatisticAssists",
                "StatisticAssistsDead",
                "StatisticUses",
                "StatisticUsesHits",
                "StatisticUsesHitPercent",
                "StatisticUsesCriticalHits",
                "StatisticUsesCriticalHitPercent",
                "StatisticInspects",
                "StatisticInspectsAfterElimination",
                "StatisticAmmoUsed",
                "StatisticReloads"
            }
        },
        ["Paintball Gun"] = {
            ["OverviewDetails"] = {{3, "• Splatter your enemies screens with this colorful rifle"}},
            ["DataNames"] = {
                "StatisticPlaytime",
                "StatisticPlaytimeUnequipped",
                "StatisticRoundsPlayed",
                "StatisticRoundsWon",
                "StatisticRoundsLost",
                "StatisticRoundsWinPercent",
                "StatisticDamageDealt",
                "StatisticDamageDealtSliding",
                "StatisticDamageDealtCrouching",
                "StatisticDamageDealtAirborne",
                "StatisticDamageDealtBlinded",
                "StatisticDamageDealtDead",
                "StatisticEliminations",
                "StatisticEliminationsSliding",
                "StatisticEliminationsCrouching",
                "StatisticEliminationsAirborne",
                "StatisticEliminationsBlinded",
                "StatisticEliminationsDead",
                "StatisticDeaths",
                "StatisticDeathsRatio",
                "StatisticAssists",
                "StatisticAssistsDead",
                "StatisticUses",
                "StatisticUsesHits",
                "StatisticUsesHitPercent",
                "StatisticUsesCriticalHits",
                "StatisticUsesCriticalHitPercent",
                "StatisticInspects",
                "StatisticInspectsAfterElimination",
                "StatisticAmmoUsed",
                "StatisticReloads"
            }
        },
        ["Smoke Grenade"] = {
            ["OverviewDetails"] = {{3, "• Creates a smoke cloud which obscures vision and extinguishes all flames"}},
            ["DataNames"] = {
                "StatisticPlaytime",
                "StatisticPlaytimeUnequipped",
                "StatisticRoundsPlayed",
                "StatisticRoundsWon",
                "StatisticRoundsLost",
                "StatisticRoundsWinPercent",
                "StatisticDamageDealt",
                "StatisticDamageDealtSliding",
                "StatisticDamageDealtCrouching",
                "StatisticDamageDealtAirborne",
                "StatisticDamageDealtBlinded",
                "StatisticDamageDealtDead",
                "StatisticEliminations",
                "StatisticEliminationsSliding",
                "StatisticEliminationsCrouching",
                "StatisticEliminationsAirborne",
                "StatisticEliminationsBlinded",
                "StatisticEliminationsDead",
                "StatisticDeaths",
                "StatisticDeathsRatio",
                "StatisticAssists",
                "StatisticAssistsDead",
                "StatisticUses",
                "StatisticUsesQuick",
                "StatisticUsesHits",
                "StatisticUsesHitPercent",
                "StatisticUsesCriticalHits",
                "StatisticUsesCriticalHitPercent",
                "StatisticInspects",
                "StatisticInspectsAfterElimination",
                "StatisticSmokeds",
                "StatisticSmokedsSelf",
                "StatisticSmokedsEnemies",
                "StatisticSmokedsTeammates",
                "StatisticExtinguishes",
                "StatisticExtinguishesPlayers",
                "StatisticExtinguishesMolotovs",
                "StatisticExtinguishesFlareGuns",
                "StatisticExtinguishesFlamethrowers"
            }
        },
        ["Exogun"] = {
            ["OverviewDetails"] = {{1, "• Pew pew pew"}},
            ["DataNames"] = {
                "StatisticPlaytime",
                "StatisticPlaytimeUnequipped",
                "StatisticRoundsPlayed",
                "StatisticRoundsWon",
                "StatisticRoundsLost",
                "StatisticRoundsWinPercent",
                "StatisticDamageDealt",
                "StatisticDamageDealtSliding",
                "StatisticDamageDealtCrouching",
                "StatisticDamageDealtAirborne",
                "StatisticDamageDealtBlinded",
                "StatisticDamageDealtDead",
                "StatisticEliminations",
                "StatisticEliminationsSliding",
                "StatisticEliminationsCrouching",
                "StatisticEliminationsAirborne",
                "StatisticEliminationsBlinded",
                "StatisticEliminationsDead",
                "StatisticDeaths",
                "StatisticDeathsRatio",
                "StatisticAssists",
                "StatisticAssistsDead",
                "StatisticUses",
                "StatisticUsesHits",
                "StatisticUsesHitPercent",
                "StatisticInspects",
                "StatisticInspectsAfterElimination",
                "StatisticAmmoUsed",
                "StatisticReloads"
            }
        },
        ["Fists"] = {
            ["OverviewDetails"] = {{1, "• Allows you to double jump"}},
            ["DataNames"] = {
                "StatisticPlaytime",
                "StatisticPlaytimeUnequipped",
                "StatisticRoundsPlayed",
                "StatisticRoundsWon",
                "StatisticRoundsLost",
                "StatisticRoundsWinPercent",
                "StatisticDamageDealt",
                "StatisticDamageDealtSliding",
                "StatisticDamageDealtCrouching",
                "StatisticDamageDealtAirborne",
                "StatisticDamageDealtBlinded",
                "StatisticDamageDealtDead",
                "StatisticEliminations",
                "StatisticEliminationsSliding",
                "StatisticEliminationsCrouching",
                "StatisticEliminationsAirborne",
                "StatisticEliminationsBlinded",
                "StatisticEliminationsDead",
                "StatisticDeaths",
                "StatisticDeathsRatio",
                "StatisticAssists",
                "StatisticAssistsDead",
                "StatisticUses",
                "StatisticUsesQuick",
                "StatisticUsesHits",
                "StatisticUsesHitPercent",
                "StatisticInspects",
                "StatisticInspectsAfterElimination"
            }
        },
        ["Handgun"] = {
            ["OverviewDetails"] = {{2, "• A reliable sidearm useful in all scenarios"}},
            ["DataNames"] = {
                "StatisticPlaytime",
                "StatisticPlaytimeUnequipped",
                "StatisticRoundsPlayed",
                "StatisticRoundsWon",
                "StatisticRoundsLost",
                "StatisticRoundsWinPercent",
                "StatisticDamageDealt",
                "StatisticDamageDealtSliding",
                "StatisticDamageDealtCrouching",
                "StatisticDamageDealtAirborne",
                "StatisticDamageDealtBlinded",
                "StatisticDamageDealtDead",
                "StatisticEliminations",
                "StatisticEliminationsSliding",
                "StatisticEliminationsCrouching",
                "StatisticEliminationsAirborne",
                "StatisticEliminationsBlinded",
                "StatisticEliminationsDead",
                "StatisticDeaths",
                "StatisticDeathsRatio",
                "StatisticAssists",
                "StatisticAssistsDead",
                "StatisticUses",
                "StatisticUsesHits",
                "StatisticUsesHitPercent",
                "StatisticUsesCriticalHits",
                "StatisticUsesCriticalHitPercent",
                "StatisticInspects",
                "StatisticInspectsAfterElimination",
                "StatisticAmmoUsed",
                "StatisticReloads"
            }
        },
        ["RPG"] = {
            ["OverviewDetails"] = {{2, "• A powerful explosive launcher"}},
            ["DataNames"] = {
                "StatisticPlaytime",
                "StatisticPlaytimeUnequipped",
                "StatisticRoundsPlayed",
                "StatisticRoundsWon",
                "StatisticRoundsLost",
                "StatisticRoundsWinPercent",
                "StatisticDamageDealt",
                "StatisticDamageDealtSliding",
                "StatisticDamageDealtCrouching",
                "StatisticDamageDealtAirborne",
                "StatisticDamageDealtBlinded",
                "StatisticDamageDealtDead",
                "StatisticEliminations",
                "StatisticEliminationsSliding",
                "StatisticEliminationsCrouching",
                "StatisticEliminationsAirborne",
                "StatisticEliminationsBlinded",
                "StatisticEliminationsDead",
                "StatisticDeaths",
                "StatisticDeathsRatio",
                "StatisticAssists",
                "StatisticAssistsDead",
                "StatisticUses",
                "StatisticUsesHitsSelf",
                "StatisticUsesHits",
                "StatisticUsesHitPercent",
                "StatisticUsesHitsDirect",
                "StatisticInspects",
                "StatisticInspectsAfterElimination",
                "StatisticAmmoUsed",
                "StatisticReloads"
            }
        },
        ["Minigun"] = {
            ["OverviewDetails"] = {{1, "• Probably dangerous"}},
            ["DataNames"] = {
                "StatisticPlaytime",
                "StatisticPlaytimeUnequipped",
                "StatisticRoundsPlayed",
                "StatisticRoundsWon",
                "StatisticRoundsLost",
                "StatisticRoundsWinPercent",
                "StatisticDamageDealt",
                "StatisticDamageDealtSliding",
                "StatisticDamageDealtCrouching",
                "StatisticDamageDealtAirborne",
                "StatisticDamageDealtBlinded",
                "StatisticDamageDealtDead",
                "StatisticEliminations",
                "StatisticEliminationsSliding",
                "StatisticEliminationsCrouching",
                "StatisticEliminationsAirborne",
                "StatisticEliminationsBlinded",
                "StatisticEliminationsDead",
                "StatisticDeaths",
                "StatisticDeathsRatio",
                "StatisticAssists",
                "StatisticAssistsDead",
                "StatisticUses",
                "StatisticUsesHits",
                "StatisticUsesHitPercent",
                "StatisticUsesCriticalHits",
                "StatisticUsesCriticalHitPercent",
                "StatisticInspects",
                "StatisticInspectsAfterElimination",
                "StatisticAmmoUsed"
            }
        },
        ["Grenade"] = {
            ["OverviewDetails"] = {{1, "• Quick & reliable explosive"}},
            ["DataNames"] = {
                "StatisticPlaytime",
                "StatisticPlaytimeUnequipped",
                "StatisticRoundsPlayed",
                "StatisticRoundsWon",
                "StatisticRoundsLost",
                "StatisticRoundsWinPercent",
                "StatisticDamageDealt",
                "StatisticDamageDealtSliding",
                "StatisticDamageDealtCrouching",
                "StatisticDamageDealtAirborne",
                "StatisticDamageDealtBlinded",
                "StatisticDamageDealtDead",
                "StatisticEliminations",
                "StatisticEliminationsSliding",
                "StatisticEliminationsCrouching",
                "StatisticEliminationsAirborne",
                "StatisticEliminationsBlinded",
                "StatisticEliminationsDead",
                "StatisticDeaths",
                "StatisticDeathsRatio",
                "StatisticAssists",
                "StatisticAssistsDead",
                "StatisticUses",
                "StatisticUsesQuick",
                "StatisticUsesHitsSelf",
                "StatisticUsesHits",
                "StatisticUsesHitPercent",
                "StatisticUsesCriticalHits",
                "StatisticUsesCriticalHitPercent",
                "StatisticInspects",
                "StatisticInspectsAfterElimination"
            }
        },
        ["Scythe"] = {
            ["OverviewDetails"] = {{2, "• Allows you to quickly dash in any direction"}},
            ["DataNames"] = {
                "StatisticPlaytime",
                "StatisticPlaytimeUnequipped",
                "StatisticRoundsPlayed",
                "StatisticRoundsWon",
                "StatisticRoundsLost",
                "StatisticRoundsWinPercent",
                "StatisticDamageDealt",
                "StatisticDamageDealtSliding",
                "StatisticDamageDealtCrouching",
                "StatisticDamageDealtAirborne",
                "StatisticDamageDealtBlinded",
                "StatisticDamageDealtDead",
                "StatisticDamageDealtDashing",
                "StatisticEliminations",
                "StatisticEliminationsSliding",
                "StatisticEliminationsCrouching",
                "StatisticEliminationsAirborne",
                "StatisticEliminationsBlinded",
                "StatisticEliminationsDead",
                "StatisticEliminationsDashing",
                "StatisticDeaths",
                "StatisticDeathsRatio",
                "StatisticAssists",
                "StatisticAssistsDead",
                "StatisticUses",
                "StatisticUsesQuick",
                "StatisticUsesHits",
                "StatisticUsesHitPercent",
                "StatisticInspects",
                "StatisticInspectsAfterElimination",
                "StatisticDashes"
            }
        },
        ["Uzi"] = {
            ["OverviewDetails"] = {{2, "• Light enemies up with this automatic sidearm"}, {1, "• Slightly innaccurate"}},
            ["DataNames"] = {
                "StatisticPlaytime",
                "StatisticPlaytimeUnequipped",
                "StatisticRoundsPlayed",
                "StatisticRoundsWon",
                "StatisticRoundsLost",
                "StatisticRoundsWinPercent",
                "StatisticDamageDealt",
                "StatisticDamageDealtSliding",
                "StatisticDamageDealtCrouching",
                "StatisticDamageDealtAirborne",
                "StatisticDamageDealtBlinded",
                "StatisticDamageDealtDead",
                "StatisticEliminations",
                "StatisticEliminationsSliding",
                "StatisticEliminationsCrouching",
                "StatisticEliminationsAirborne",
                "StatisticEliminationsBlinded",
                "StatisticEliminationsDead",
                "StatisticDeaths",
                "StatisticDeathsRatio",
                "StatisticAssists",
                "StatisticAssistsDead",
                "StatisticUses",
                "StatisticUsesHits",
                "StatisticUsesHitPercent",
                "StatisticUsesCriticalHits",
                "StatisticUsesCriticalHitPercent",
                "StatisticInspects",
                "StatisticInspectsAfterElimination",
                "StatisticAmmoUsed",
                "StatisticReloads"
            }
        },
        ["Slingshot"] = {
            ["OverviewDetails"] = {{2, "• Unleash a barrage of bouncy balls"}},
            ["DataNames"] = {
                "StatisticPlaytime",
                "StatisticPlaytimeUnequipped",
                "StatisticRoundsPlayed",
                "StatisticRoundsWon",
                "StatisticRoundsLost",
                "StatisticRoundsWinPercent",
                "StatisticDamageDealt",
                "StatisticDamageDealtSliding",
                "StatisticDamageDealtCrouching",
                "StatisticDamageDealtAirborne",
                "StatisticDamageDealtBlinded",
                "StatisticDamageDealtDead",
                "StatisticDamageDealtBouncing",
                "StatisticEliminations",
                "StatisticEliminationsSliding",
                "StatisticEliminationsCrouching",
                "StatisticEliminationsAirborne",
                "StatisticEliminationsBlinded",
                "StatisticEliminationsDead",
                "StatisticEliminationsBouncing",
                "StatisticDeaths",
                "StatisticDeathsRatio",
                "StatisticAssists",
                "StatisticAssistsDead",
                "StatisticUses",
                "StatisticUsesHits",
                "StatisticUsesHitPercent",
                "StatisticUsesCriticalHits",
                "StatisticUsesCriticalHitPercent",
                "StatisticInspects",
                "StatisticInspectsAfterElimination",
                "StatisticAmmoUsed"
            }
        },
        ["Trowel"] = {
            ["OverviewDetails"] = {
                {2, "• Build walls to defend yourself"},
                {2, "• Send the bricks flying to harden them in place"}
            },
            ["DataNames"] = {
                "StatisticPlaytime",
                "StatisticPlaytimeUnequipped",
                "StatisticRoundsPlayed",
                "StatisticRoundsWon",
                "StatisticRoundsLost",
                "StatisticRoundsWinPercent",
                "StatisticDamageDealt",
                "StatisticDamageDealtSliding",
                "StatisticDamageDealtCrouching",
                "StatisticDamageDealtAirborne",
                "StatisticDamageDealtBlinded",
                "StatisticDamageDealtDead",
                "StatisticEliminations",
                "StatisticEliminationsSliding",
                "StatisticEliminationsCrouching",
                "StatisticEliminationsAirborne",
                "StatisticEliminationsBlinded",
                "StatisticEliminationsDead",
                "StatisticDeaths",
                "StatisticDeathsRatio",
                "StatisticAssists",
                "StatisticAssistsDead",
                "StatisticUses",
                "StatisticUsesQuick",
                "StatisticUsesHits",
                "StatisticUsesHitPercent",
                "StatisticInspects",
                "StatisticInspectsAfterElimination",
                "StatisticWallsBuilt",
                "StatisticWallsBuiltBricksLayed"
            }
        },
        ["Katana"] = {
            ["OverviewDetails"] = {{2, "• Can deflect bullets back at enemies"}},
            ["DataNames"] = {
                "StatisticPlaytime",
                "StatisticPlaytimeUnequipped",
                "StatisticRoundsPlayed",
                "StatisticRoundsWon",
                "StatisticRoundsLost",
                "StatisticRoundsWinPercent",
                "StatisticDamageDealt",
                "StatisticDamageDealtSliding",
                "StatisticDamageDealtCrouching",
                "StatisticDamageDealtAirborne",
                "StatisticDamageDealtBlinded",
                "StatisticDamageDealtDead",
                "StatisticDamageDealtDeflecting",
                "StatisticEliminations",
                "StatisticEliminationsSliding",
                "StatisticEliminationsCrouching",
                "StatisticEliminationsAirborne",
                "StatisticEliminationsBlinded",
                "StatisticEliminationsDead",
                "StatisticEliminationsDeflecting",
                "StatisticDeaths",
                "StatisticDeathsRatio",
                "StatisticAssists",
                "StatisticAssistsDead",
                "StatisticUses",
                "StatisticUsesQuick",
                "StatisticUsesHits",
                "StatisticUsesHitPercent",
                "StatisticInspects",
                "StatisticInspectsAfterElimination",
                "StatisticDeflects",
                "StatisticDeflectsHits",
                "StatisticDeflectsCriticalHits"
            }
        },
        ["Flare Gun"] = {
            ["OverviewDetails"] = {{3, "• Shoots a fireball that constantly burns nearby enemies"}},
            ["DataNames"] = {
                "StatisticPlaytime",
                "StatisticPlaytimeUnequipped",
                "StatisticRoundsPlayed",
                "StatisticRoundsWon",
                "StatisticRoundsLost",
                "StatisticRoundsWinPercent",
                "StatisticDamageDealt",
                "StatisticDamageDealtSliding",
                "StatisticDamageDealtCrouching",
                "StatisticDamageDealtAirborne",
                "StatisticDamageDealtBlinded",
                "StatisticDamageDealtDead",
                "StatisticEliminations",
                "StatisticEliminationsSliding",
                "StatisticEliminationsCrouching",
                "StatisticEliminationsAirborne",
                "StatisticEliminationsBlinded",
                "StatisticEliminationsDead",
                "StatisticDeaths",
                "StatisticDeathsRatio",
                "StatisticAssists",
                "StatisticAssistsDead",
                "StatisticUses",
                "StatisticUsesHits",
                "StatisticUsesHitPercent",
                "StatisticInspects",
                "StatisticInspectsAfterElimination",
                "StatisticAmmoUsed"
            }
        },
        ["Molotov"] = {
            ["OverviewDetails"] = {{3, "• An unethical way of setting your enemies on fire"}},
            ["DataNames"] = {
                "StatisticPlaytime",
                "StatisticPlaytimeUnequipped",
                "StatisticRoundsPlayed",
                "StatisticRoundsWon",
                "StatisticRoundsLost",
                "StatisticRoundsWinPercent",
                "StatisticDamageDealt",
                "StatisticDamageDealtSliding",
                "StatisticDamageDealtCrouching",
                "StatisticDamageDealtAirborne",
                "StatisticDamageDealtBlinded",
                "StatisticDamageDealtDead",
                "StatisticEliminations",
                "StatisticEliminationsSliding",
                "StatisticEliminationsCrouching",
                "StatisticEliminationsAirborne",
                "StatisticEliminationsBlinded",
                "StatisticEliminationsDead",
                "StatisticDeaths",
                "StatisticDeathsRatio",
                "StatisticAssists",
                "StatisticAssistsDead",
                "StatisticUses",
                "StatisticUsesQuick",
                "StatisticUsesHits",
                "StatisticUsesHitPercent",
                "StatisticUsesCriticalHits",
                "StatisticUsesCriticalHitPercent",
                "StatisticInspects",
                "StatisticInspectsAfterElimination"
            }
        },
        ["Assault Rifle"] = {
            ["OverviewDetails"] = {{2, "• A standard rifle useful in all scenarios"}},
            ["DataNames"] = {
                "StatisticPlaytime",
                "StatisticPlaytimeUnequipped",
                "StatisticRoundsPlayed",
                "StatisticRoundsWon",
                "StatisticRoundsLost",
                "StatisticRoundsWinPercent",
                "StatisticDamageDealt",
                "StatisticDamageDealtSliding",
                "StatisticDamageDealtCrouching",
                "StatisticDamageDealtAirborne",
                "StatisticDamageDealtBlinded",
                "StatisticDamageDealtDead",
                "StatisticEliminations",
                "StatisticEliminationsSliding",
                "StatisticEliminationsCrouching",
                "StatisticEliminationsAirborne",
                "StatisticEliminationsBlinded",
                "StatisticEliminationsDead",
                "StatisticDeaths",
                "StatisticDeathsRatio",
                "StatisticAssists",
                "StatisticAssistsDead",
                "StatisticUses",
                "StatisticUsesHits",
                "StatisticUsesHitPercent",
                "StatisticUsesCriticalHits",
                "StatisticUsesCriticalHitPercent",
                "StatisticInspects",
                "StatisticInspectsAfterElimination",
                "StatisticAmmoUsed",
                "StatisticReloads"
            }
        },
        ["Revolver"] = {
            ["OverviewDetails"] = {
                {2, "• A slow but powerful handgun"},
                {2, "• Fan the hammer to unload the entire chamber"}
            },
            ["DataNames"] = {
                "StatisticPlaytime",
                "StatisticPlaytimeUnequipped",
                "StatisticRoundsPlayed",
                "StatisticRoundsWon",
                "StatisticRoundsLost",
                "StatisticRoundsWinPercent",
                "StatisticDamageDealt",
                "StatisticDamageDealtSliding",
                "StatisticDamageDealtCrouching",
                "StatisticDamageDealtAirborne",
                "StatisticDamageDealtBlinded",
                "StatisticDamageDealtDead",
                "StatisticEliminations",
                "StatisticEliminationsSliding",
                "StatisticEliminationsCrouching",
                "StatisticEliminationsAirborne",
                "StatisticEliminationsBlinded",
                "StatisticEliminationsDead",
                "StatisticDeaths",
                "StatisticDeathsRatio",
                "StatisticAssists",
                "StatisticAssistsDead",
                "StatisticUses",
                "StatisticUsesHits",
                "StatisticUsesHitPercent",
                "StatisticUsesCriticalHits",
                "StatisticUsesCriticalHitPercent",
                "StatisticInspects",
                "StatisticInspectsAfterElimination",
                "StatisticAmmoUsed",
                "StatisticReloads"
            }
        }
    },
    ["Info"] = {
        ["StatisticPlaytimeUnequipped"] = {
            ["TostringFunction"] = "function: 0x8fc6b684a20b4a89",
            ["Image"] = "rbxassetid://17156089790",
            ["ParentDataName"] = "StatisticPlaytime",
            ["FullDisplayName"] = "Playtime while unequipped",
            ["DataName"] = "StatisticPlaytimeUnequipped",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "while unequipped"
        },
        ["StatisticFavoriteWeaponSecondary"] = {
            ["TostringFunction"] = "function: 0x8b0ce297a63c1e59",
            ["Image"] = "",
            ["ParentDataName"] = "StatisticFavoriteWeapon",
            ["FullDisplayName"] = "Favorite Weapon secondary",
            ["DataName"] = "StatisticFavoriteWeaponSecondary",
            ["DefaultValue"] = "N/A",
            ["DisplayName"] = "secondary"
        },
        ["StatisticEliminationsDead"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "rbxassetid://17736790660",
            ["ParentDataName"] = "StatisticEliminations",
            ["FullDisplayName"] = "Eliminations while dead",
            ["DataName"] = "StatisticEliminationsDead",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "while dead"
        },
        ["StatisticDuelsWonSuddenDeath"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["ParentDataName"] = "StatisticDuelsPlayed",
            ["FullDisplayName"] = "Duels Played sudden death wins",
            ["DataName"] = "StatisticDuelsWonSuddenDeath",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "sudden death wins"
        },
        ["StatisticDamageDealtBlinded"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["ParentDataName"] = "StatisticDamageDealt",
            ["FullDisplayName"] = "Damage Dealt while blinded",
            ["DataName"] = "StatisticDamageDealtBlinded",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "while blinded"
        },
        ["StatisticEliminationsNoscope"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "rbxassetid://17736790660",
            ["ParentDataName"] = "StatisticEliminations",
            ["FullDisplayName"] = "Eliminations while noscoping",
            ["DataName"] = "StatisticEliminationsNoscope",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "while noscoping"
        },
        ["StatisticHealsReceived"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["FullDisplayName"] = "Heals Received",
            ["DataName"] = "StatisticHealsReceived",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "Heals Received"
        },
        ["StatisticDuelsWon"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["ParentDataName"] = "StatisticDuelsPlayed",
            ["FullDisplayName"] = "Duels Played wins",
            ["DataName"] = "StatisticDuelsWon",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "wins"
        },
        ["StatisticUsesCriticalHits"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["ParentDataName"] = "StatisticUses",
            ["FullDisplayName"] = "Uses critical hits",
            ["DataName"] = "StatisticUsesCriticalHits",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "critical hits"
        },
        ["StatisticEliminationsSliding"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "rbxassetid://17736790660",
            ["ParentDataName"] = "StatisticEliminations",
            ["FullDisplayName"] = "Eliminations while sliding",
            ["DataName"] = "StatisticEliminationsSliding",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "while sliding"
        },
        ["StatisticDamageDealtBouncing"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["ParentDataName"] = "StatisticDamageDealt",
            ["FullDisplayName"] = "Damage Dealt after a bounce",
            ["DataName"] = "StatisticDamageDealtBouncing",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "after a bounce"
        },
        ["StatisticDuelsWonFlawless"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["ParentDataName"] = "StatisticDuelsPlayed",
            ["FullDisplayName"] = "Duels Played flawless wins",
            ["DataName"] = "StatisticDuelsWonFlawless",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "flawless wins"
        },
        ["StatisticFavoriteWeaponPrimary"] = {
            ["TostringFunction"] = "function: 0x0b8f1fd5f625d5f9",
            ["Image"] = "",
            ["ParentDataName"] = "StatisticFavoriteWeapon",
            ["FullDisplayName"] = "Favorite Weapon primary",
            ["DataName"] = "StatisticFavoriteWeaponPrimary",
            ["DefaultValue"] = "N/A",
            ["DisplayName"] = "primary"
        },
        ["StatisticUsesHits"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["ParentDataName"] = "StatisticUses",
            ["FullDisplayName"] = "Uses hits",
            ["DataName"] = "StatisticUsesHits",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "hits"
        },
        ["StatisticFavoriteWeaponMelee"] = {
            ["TostringFunction"] = "function: 0x19ad6090663f9139",
            ["Image"] = "",
            ["ParentDataName"] = "StatisticFavoriteWeapon",
            ["FullDisplayName"] = "Favorite Weapon melee",
            ["DataName"] = "StatisticFavoriteWeaponMelee",
            ["DefaultValue"] = "N/A",
            ["DisplayName"] = "melee"
        },
        ["StatisticDeflectsCriticalHits"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["ParentDataName"] = "StatisticDeflects",
            ["FullDisplayName"] = "Deflects critical hits",
            ["DataName"] = "StatisticDeflectsCriticalHits",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "critical hits"
        },
        ["StatisticRoundsWon"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["ParentDataName"] = "StatisticRoundsPlayed",
            ["FullDisplayName"] = "Rounds Played wins",
            ["DataName"] = "StatisticRoundsWon",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "wins"
        },
        ["StatisticHealsGiven"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["FullDisplayName"] = "Heals Given",
            ["DataName"] = "StatisticHealsGiven",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "Heals Given"
        },
        ["StatisticReloads"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["FullDisplayName"] = "Reloads",
            ["DataName"] = "StatisticReloads",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "Reloads"
        },
        ["StatisticDuelsLost"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["ParentDataName"] = "StatisticDuelsPlayed",
            ["FullDisplayName"] = "Duels Played losses",
            ["DataName"] = "StatisticDuelsLost",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "losses"
        },
        ["StatisticAssistsDead"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["ParentDataName"] = "StatisticAssists",
            ["FullDisplayName"] = "Assists while dead",
            ["DataName"] = "StatisticAssistsDead",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "while dead"
        },
        ["StatisticPlaytime"] = {
            ["TostringFunction"] = "function: 0x8fc6b684a20b4a89",
            ["Image"] = "rbxassetid://17156089790",
            ["FullDisplayName"] = "Playtime",
            ["DataName"] = "StatisticPlaytime",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "Playtime"
        },
        ["StatisticSmokedsTeammates"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "rbxassetid://18387088796",
            ["ParentDataName"] = "StatisticSmokeds",
            ["FullDisplayName"] = "Players Smoked teammates smoked",
            ["DataName"] = "StatisticSmokedsTeammates",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "teammates smoked"
        },
        ["StatisticUsesQuick"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["ParentDataName"] = "StatisticUses",
            ["FullDisplayName"] = "Uses quick uses",
            ["DataName"] = "StatisticUsesQuick",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "quick uses"
        },
        ["StatisticTasksCompleted"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["FullDisplayName"] = "Tasks Completed",
            ["DataName"] = "StatisticTasksCompleted",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "Tasks Completed"
        },
        ["StatisticUsesHitsSelf"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["ParentDataName"] = "StatisticUses",
            ["FullDisplayName"] = "Uses self hits",
            ["DataName"] = "StatisticUsesHitsSelf",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "self hits"
        },
        ["StatisticDamageDealtSliding"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["ParentDataName"] = "StatisticDamageDealt",
            ["FullDisplayName"] = "Damage Dealt while sliding",
            ["DataName"] = "StatisticDamageDealtSliding",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "while sliding"
        },
        ["StatisticEliminations"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "rbxassetid://17736790660",
            ["FullDisplayName"] = "Eliminations",
            ["DataName"] = "StatisticEliminations",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "Eliminations"
        },
        ["StatisticDuelsMVPs"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["ParentDataName"] = "StatisticDuelsPlayed",
            ["FullDisplayName"] = "Duels Played MVPs",
            ["DataName"] = "StatisticDuelsMVPs",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "MVPs"
        },
        ["StatisticDashes"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["FullDisplayName"] = "Dashes",
            ["DataName"] = "StatisticDashes",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "Dashes"
        },
        ["StatisticAirblastsSmokesCleared"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["ParentDataName"] = "StatisticAirblasts",
            ["FullDisplayName"] = "Airblasts smoke clouds cleared",
            ["DataName"] = "StatisticAirblastsSmokesCleared",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "smoke clouds cleared"
        },
        ["StatisticUsesHitPercent"] = {
            ["TostringFunction"] = "function: 0x3aaf196d05a32ab9",
            ["Image"] = "",
            ["ParentDataName"] = "StatisticUses",
            ["FullDisplayName"] = "Uses hit %",
            ["DataName"] = "StatisticUsesHitPercent",
            ["DefaultValue"] = -1,
            ["DisplayName"] = "hit %"
        },
        ["StatisticAmmoUsed"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["FullDisplayName"] = "Ammo Used",
            ["DataName"] = "StatisticAmmoUsed",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "Ammo Used"
        },
        ["StatisticFreezesEnemies"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "rbxassetid://18428668944",
            ["ParentDataName"] = "StatisticFreezes",
            ["FullDisplayName"] = "Enemies Frozen",
            ["DataName"] = "StatisticFreezesEnemies",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "enemies frozen"
        },
        ["StatisticExtinguishesPlayers"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["ParentDataName"] = "StatisticExtinguishes",
            ["FullDisplayName"] = "Extinguishes players",
            ["DataName"] = "StatisticExtinguishesPlayers",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "players"
        },
        ["StatisticAirblastsHits"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["ParentDataName"] = "StatisticAirblasts",
            ["FullDisplayName"] = "Airblasts players blasted",
            ["DataName"] = "StatisticAirblastsHits",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "players blasted"
        },
        ["StatisticFreezesSelf"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "rbxassetid://18428668944",
            ["ParentDataName"] = "StatisticFreezes",
            ["FullDisplayName"] = "Players Frozen self freezes",
            ["DataName"] = "StatisticFreezesSelf",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "self freezes"
        },
        ["StatisticDuelsWinStreaksTaken"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["ParentDataName"] = "StatisticDuelsPlayed",
            ["FullDisplayName"] = "Duels Played highest win streak ended",
            ["DataName"] = "StatisticDuelsWinStreaksTaken",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "highest win streak ended"
        },
        ["StatisticFreezes"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "rbxassetid://18428668944",
            ["FullDisplayName"] = "Players Frozen",
            ["DataName"] = "StatisticFreezes",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "Players Frozen"
        },
        ["StatisticFavoriteWeapon"] = {
            ["TostringFunction"] = "function: 0x9a6f1ad456c74919",
            ["Image"] = "",
            ["FullDisplayName"] = "Favorite Weapon",
            ["DataName"] = "StatisticFavoriteWeapon",
            ["DefaultValue"] = "N/A",
            ["DisplayName"] = "Favorite Weapon"
        },
        ["StatisticDamageReceived"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["FullDisplayName"] = "Damage Received",
            ["DataName"] = "StatisticDamageReceived",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "Damage Received"
        },
        ["StatisticDamageDealtDead"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["ParentDataName"] = "StatisticDamageDealt",
            ["FullDisplayName"] = "Damage Dealt while dead",
            ["DataName"] = "StatisticDamageDealtDead",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "while dead"
        },
        ["StatisticSmokeds"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "rbxassetid://18387088796",
            ["FullDisplayName"] = "Players Smoked",
            ["DataName"] = "StatisticSmokeds",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "Players Smoked"
        },
        ["StatisticUsesCriticalHitPercent"] = {
            ["TostringFunction"] = "function: 0x3aaf196d05a32ab9",
            ["Image"] = "",
            ["ParentDataName"] = "StatisticUses",
            ["FullDisplayName"] = "Uses critical hit %",
            ["DataName"] = "StatisticUsesCriticalHitPercent",
            ["DefaultValue"] = -1,
            ["DisplayName"] = "critical hit %"
        },
        ["StatisticBlindsEnemies"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "rbxassetid://17814211801",
            ["ParentDataName"] = "StatisticBlinds",
            ["FullDisplayName"] = "Enemies Blinded",
            ["DataName"] = "StatisticBlindsEnemies",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "enemies blinded"
        },
        ["StatisticDeflects"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["FullDisplayName"] = "Deflects",
            ["DataName"] = "StatisticDeflects",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "Deflects"
        },
        ["StatisticBlinds"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "rbxassetid://17814211801",
            ["FullDisplayName"] = "Players Blinded",
            ["DataName"] = "StatisticBlinds",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "Players Blinded"
        },
        ["StatisticDuelsWinStreaksTakenTotal"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["ParentDataName"] = "StatisticDuelsPlayed",
            ["FullDisplayName"] = "Duels Played total win streaks ended",
            ["DataName"] = "StatisticDuelsWinStreaksTakenTotal",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "total win streaks ended"
        },
        ["StatisticDeathsRatio"] = {
            ["TostringFunction"] = "function: 0x08cd6cd2b3baf679",
            ["Image"] = "",
            ["ParentDataName"] = "StatisticDeaths",
            ["FullDisplayName"] = "Deaths eliminations ratio",
            ["DataName"] = "StatisticDeathsRatio",
            ["DefaultValue"] = -1,
            ["DisplayName"] = "eliminations ratio"
        },
        ["StatisticExtinguishesFlareGuns"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["ParentDataName"] = "StatisticExtinguishes",
            ["FullDisplayName"] = "Extinguishes flare guns",
            ["DataName"] = "StatisticExtinguishesFlareGuns",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "flare guns"
        },
        ["StatisticExtinguishesMolotovs"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["ParentDataName"] = "StatisticExtinguishes",
            ["FullDisplayName"] = "Extinguishes molotovs",
            ["DataName"] = "StatisticExtinguishesMolotovs",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "molotovs"
        },
        ["StatisticExtinguishes"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["FullDisplayName"] = "Extinguishes",
            ["DataName"] = "StatisticExtinguishes",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "Extinguishes"
        },
        ["StatisticEliminationsDashing"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "rbxassetid://17736790660",
            ["ParentDataName"] = "StatisticEliminations",
            ["FullDisplayName"] = "Eliminations while dashing",
            ["DataName"] = "StatisticEliminationsDashing",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "while dashing"
        },
        ["StatisticUses"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["FullDisplayName"] = "Uses",
            ["DataName"] = "StatisticUses",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "Uses"
        },
        ["StatisticBlindsSelf"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "rbxassetid://17814211801",
            ["ParentDataName"] = "StatisticBlinds",
            ["FullDisplayName"] = "Players Blinded self blinded",
            ["DataName"] = "StatisticBlindsSelf",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "self blinded"
        },
        ["StatisticDamageDealtAirborne"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["ParentDataName"] = "StatisticDamageDealt",
            ["FullDisplayName"] = "Damage Dealt while airborne",
            ["DataName"] = "StatisticDamageDealtAirborne",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "while airborne"
        },
        ["StatisticEliminationsCrouching"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "rbxassetid://17736790660",
            ["ParentDataName"] = "StatisticEliminations",
            ["FullDisplayName"] = "Eliminations while crouching",
            ["DataName"] = "StatisticEliminationsCrouching",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "while crouching"
        },
        ["StatisticInspects"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["FullDisplayName"] = "Inspects",
            ["DataName"] = "StatisticInspects",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "Inspects"
        },
        ["StatisticWallsBuilt"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["FullDisplayName"] = "Walls Built",
            ["DataName"] = "StatisticWallsBuilt",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "Walls Built"
        },
        ["StatisticRoundsLost"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["ParentDataName"] = "StatisticRoundsPlayed",
            ["FullDisplayName"] = "Rounds Played losses",
            ["DataName"] = "StatisticRoundsLost",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "losses"
        },
        ["StatisticAirblasts"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["FullDisplayName"] = "Airblasts",
            ["DataName"] = "StatisticAirblasts",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "Airblasts"
        },
        ["StatisticEliminationsDeflecting"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "rbxassetid://17736790660",
            ["ParentDataName"] = "StatisticEliminations",
            ["FullDisplayName"] = "Eliminations from deflecting",
            ["DataName"] = "StatisticEliminationsDeflecting",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "from deflecting"
        },
        ["StatisticEliminationsBlinded"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "rbxassetid://17736790660",
            ["ParentDataName"] = "StatisticEliminations",
            ["FullDisplayName"] = "Eliminations while blinded",
            ["DataName"] = "StatisticEliminationsBlinded",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "while blinded"
        },
        ["StatisticEliminationsBouncing"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "rbxassetid://17736790660",
            ["ParentDataName"] = "StatisticEliminations",
            ["FullDisplayName"] = "Eliminations after a bounce",
            ["DataName"] = "StatisticEliminationsBouncing",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "after a bounce"
        },
        ["StatisticInspectsAfterElimination"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["ParentDataName"] = "StatisticInspects",
            ["FullDisplayName"] = "Inspects after an elimination",
            ["DataName"] = "StatisticInspectsAfterElimination",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "after an elimination"
        },
        ["StatisticDuelsLostFlawless"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["ParentDataName"] = "StatisticDuelsPlayed",
            ["FullDisplayName"] = "Duels Played flawless losses",
            ["DataName"] = "StatisticDuelsLostFlawless",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "flawless losses"
        },
        ["StatisticDamageDealtDashing"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["ParentDataName"] = "StatisticDamageDealt",
            ["FullDisplayName"] = "Damage Dealt while dashing",
            ["DataName"] = "StatisticDamageDealtDashing",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "while dashing"
        },
        ["StatisticUsesHitsDirect"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["ParentDataName"] = "StatisticUses",
            ["FullDisplayName"] = "Uses direct hits",
            ["DataName"] = "StatisticUsesHitsDirect",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "direct hits"
        },
        ["StatisticDamageDealtDeflecting"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["ParentDataName"] = "StatisticDamageDealt",
            ["FullDisplayName"] = "Damage Dealt from deflecting",
            ["DataName"] = "StatisticDamageDealtDeflecting",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "from deflecting"
        },
        ["StatisticRoundsPlayed"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["FullDisplayName"] = "Rounds Played",
            ["DataName"] = "StatisticRoundsPlayed",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "Rounds Played"
        },
        ["StatisticEliminationsAirborne"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "rbxassetid://17736790660",
            ["ParentDataName"] = "StatisticEliminations",
            ["FullDisplayName"] = "Eliminations while airborne",
            ["DataName"] = "StatisticEliminationsAirborne",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "while airborne"
        },
        ["StatisticDamageDealtNoscope"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["ParentDataName"] = "StatisticDamageDealt",
            ["FullDisplayName"] = "Damage Dealt while noscoping",
            ["DataName"] = "StatisticDamageDealtNoscope",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "while noscoping"
        },
        ["StatisticBlindsTeammates"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "rbxassetid://17814211801",
            ["ParentDataName"] = "StatisticBlinds",
            ["FullDisplayName"] = "Players Blinded teammates blinded",
            ["DataName"] = "StatisticBlindsTeammates",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "teammates blinded"
        },
        ["StatisticContractsCompleted"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["FullDisplayName"] = "Contracts Completed",
            ["DataName"] = "StatisticContractsCompleted",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "Contracts Completed"
        },
        ["StatisticWallsBuiltBricksLayed"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["ParentDataName"] = "StatisticWallsBuilt",
            ["FullDisplayName"] = "Walls Built bricks layed",
            ["DataName"] = "StatisticWallsBuiltBricksLayed",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "bricks layed"
        },
        ["StatisticDuelsWinStreakHighest"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["ParentDataName"] = "StatisticDuelsPlayed",
            ["FullDisplayName"] = "Duels Played highest ever win streak",
            ["DataName"] = "StatisticDuelsWinStreakHighest",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "highest ever win streak"
        },
        ["StatisticDuelsWinStreak"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["ParentDataName"] = "StatisticDuelsPlayed",
            ["FullDisplayName"] = "Duels Played current win streak",
            ["DataName"] = "StatisticDuelsWinStreak",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "current win streak"
        },
        ["StatisticAssists"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["FullDisplayName"] = "Assists",
            ["DataName"] = "StatisticAssists",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "Assists"
        },
        ["StatisticFavoriteWeaponUtility"] = {
            ["TostringFunction"] = "function: 0xf86de1d2eabd2c99",
            ["Image"] = "",
            ["ParentDataName"] = "StatisticFavoriteWeapon",
            ["FullDisplayName"] = "Favorite Weapon utility",
            ["DataName"] = "StatisticFavoriteWeaponUtility",
            ["DefaultValue"] = "N/A",
            ["DisplayName"] = "utility"
        },
        ["StatisticDuelsLostSuddenDeath"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["ParentDataName"] = "StatisticDuelsPlayed",
            ["FullDisplayName"] = "Duels Played sudden death losses",
            ["DataName"] = "StatisticDuelsLostSuddenDeath",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "sudden death losses"
        },
        ["StatisticDuelsWinPercent"] = {
            ["TostringFunction"] = "function: 0x3aaf196d05a32ab9",
            ["Image"] = "",
            ["ParentDataName"] = "StatisticDuelsPlayed",
            ["FullDisplayName"] = "Duels Played win %",
            ["DataName"] = "StatisticDuelsWinPercent",
            ["DefaultValue"] = -1,
            ["DisplayName"] = "win %"
        },
        ["StatisticDeaths"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["FullDisplayName"] = "Deaths",
            ["DataName"] = "StatisticDeaths",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "Deaths"
        },
        ["StatisticDeflectsHits"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["ParentDataName"] = "StatisticDeflects",
            ["FullDisplayName"] = "Deflects hits",
            ["DataName"] = "StatisticDeflectsHits",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "hits"
        },
        ["StatisticDamageDealt"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["FullDisplayName"] = "Damage Dealt",
            ["DataName"] = "StatisticDamageDealt",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "Damage Dealt"
        },
        ["StatisticDamageDealtCrouching"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["ParentDataName"] = "StatisticDamageDealt",
            ["FullDisplayName"] = "Damage Dealt while crouching",
            ["DataName"] = "StatisticDamageDealtCrouching",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "while crouching"
        },
        ["StatisticSmokedsEnemies"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "rbxassetid://18387088796",
            ["ParentDataName"] = "StatisticSmokeds",
            ["FullDisplayName"] = "Enemies Smoked",
            ["DataName"] = "StatisticSmokedsEnemies",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "enemies smoked"
        },
        ["StatisticExtinguishesFlamethrowers"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["ParentDataName"] = "StatisticExtinguishes",
            ["FullDisplayName"] = "Extinguishes flamethrowers",
            ["DataName"] = "StatisticExtinguishesFlamethrowers",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "flamethrowers"
        },
        ["StatisticSmokedsSelf"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "rbxassetid://18387088796",
            ["ParentDataName"] = "StatisticSmokeds",
            ["FullDisplayName"] = "Players Smoked self smoked",
            ["DataName"] = "StatisticSmokedsSelf",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "self smoked"
        },
        ["StatisticDuelsPlayed"] = {
            ["TostringFunction"] = "function: 0x52b6735592577ff9",
            ["Image"] = "",
            ["FullDisplayName"] = "Duels Played",
            ["DataName"] = "StatisticDuelsPlayed",
            ["DefaultValue"] = 0,
            ["DisplayName"] = "Duels Played"
        },
        ["StatisticRoundsWinPercent"] = {
            ["TostringFunction"] = "function: 0x3aaf196d05a32ab9",
            ["Image"] = "",
            ["ParentDataName"] = "StatisticRoundsPlayed",
            ["FullDisplayName"] = "Rounds Played win %",
            ["DataName"] = "StatisticRoundsWinPercent",
            ["DefaultValue"] = -1,
            ["DisplayName"] = "win %"
        }
    },
    ["Order"] = {
        "StatisticPlaytime",
        "StatisticPlaytimeUnequipped",
        "StatisticTasksCompleted",
        "StatisticContractsCompleted",
        "StatisticFavoriteWeapon",
        "StatisticFavoriteWeaponPrimary",
        "StatisticFavoriteWeaponSecondary",
        "StatisticFavoriteWeaponMelee",
        "StatisticFavoriteWeaponUtility",
        "StatisticDuelsPlayed",
        "StatisticDuelsWon",
        "StatisticDuelsLost",
        "StatisticDuelsWinPercent",
        "StatisticDuelsWonFlawless",
        "StatisticDuelsLostFlawless",
        "StatisticDuelsWonSuddenDeath",
        "StatisticDuelsLostSuddenDeath",
        "StatisticDuelsWinStreak",
        "StatisticDuelsWinStreakHighest",
        "StatisticDuelsWinStreaksTaken",
        "StatisticDuelsWinStreaksTakenTotal",
        "StatisticDuelsMVPs",
        "StatisticRoundsPlayed",
        "StatisticRoundsWon",
        "StatisticRoundsLost",
        "StatisticRoundsWinPercent",
        "StatisticDamageDealt",
        "StatisticDamageDealtSliding",
        "StatisticDamageDealtCrouching",
        "StatisticDamageDealtAirborne",
        "StatisticDamageDealtBlinded",
        "StatisticDamageDealtDead",
        "StatisticDamageDealtNoscope",
        "StatisticDamageDealtDashing",
        "StatisticDamageDealtDeflecting",
        "StatisticDamageDealtBouncing",
        "StatisticEliminations",
        "StatisticEliminationsSliding",
        "StatisticEliminationsCrouching",
        "StatisticEliminationsAirborne",
        "StatisticEliminationsBlinded",
        "StatisticEliminationsDead",
        "StatisticEliminationsNoscope",
        "StatisticEliminationsDashing",
        "StatisticEliminationsDeflecting",
        "StatisticEliminationsBouncing",
        "StatisticDeaths",
        "StatisticDeathsRatio",
        "StatisticAssists",
        "StatisticAssistsDead",
        "StatisticDamageReceived",
        "StatisticHealsReceived",
        "StatisticHealsGiven",
        "StatisticUses",
        "StatisticUsesQuick",
        "StatisticUsesHits",
        "StatisticUsesHitPercent",
        "StatisticUsesCriticalHits",
        "StatisticUsesCriticalHitPercent",
        "StatisticUsesHitsSelf",
        "StatisticUsesHitsDirect",
        "StatisticInspects",
        "StatisticInspectsAfterElimination",
        "StatisticAmmoUsed",
        "StatisticReloads",
        "StatisticAirblasts",
        "StatisticAirblastsHits",
        "StatisticAirblastsSmokesCleared",
        "StatisticDashes",
        "StatisticWallsBuilt",
        "StatisticWallsBuiltBricksLayed",
        "StatisticDeflects",
        "StatisticDeflectsHits",
        "StatisticDeflectsCriticalHits",
        "StatisticExtinguishes",
        "StatisticExtinguishesPlayers",
        "StatisticExtinguishesMolotovs",
        "StatisticExtinguishesFlareGuns",
        "StatisticExtinguishesFlamethrowers",
        "StatisticBlinds",
        "StatisticBlindsSelf",
        "StatisticBlindsEnemies",
        "StatisticBlindsTeammates",
        "StatisticSmokeds",
        "StatisticSmokedsSelf",
        "StatisticSmokedsEnemies",
        "StatisticSmokedsTeammates",
        "StatisticFreezes",
        "StatisticFreezesSelf",
        "StatisticFreezesEnemies"
    },
    ["VisiblePersonalStatistics"] = {
        "StatisticPlaytime",
        "StatisticTasksCompleted",
        "StatisticContractsCompleted",
        "StatisticFavoriteWeapon",
        "StatisticFavoriteWeaponPrimary",
        "StatisticFavoriteWeaponSecondary",
        "StatisticFavoriteWeaponMelee",
        "StatisticFavoriteWeaponUtility",
        "StatisticDuelsPlayed",
        "StatisticDuelsWon",
        "StatisticDuelsLost",
        "StatisticDuelsWinPercent",
        "StatisticDuelsWonFlawless",
        "StatisticDuelsLostFlawless",
        "StatisticDuelsWonSuddenDeath",
        "StatisticDuelsLostSuddenDeath",
        "StatisticDuelsWinStreak",
        "StatisticDuelsWinStreakHighest",
        "StatisticDuelsWinStreaksTaken",
        "StatisticDuelsWinStreaksTakenTotal",
        "StatisticDuelsMVPs",
        "StatisticRoundsPlayed",
        "StatisticRoundsWon",
        "StatisticRoundsLost",
        "StatisticRoundsWinPercent",
        "StatisticDamageDealt",
        "StatisticDamageDealtSliding",
        "StatisticDamageDealtCrouching",
        "StatisticDamageDealtAirborne",
        "StatisticDamageDealtBlinded",
        "StatisticDamageDealtDead",
        "StatisticDamageDealtNoscope",
        "StatisticDamageDealtDashing",
        "StatisticDamageDealtDeflecting",
        "StatisticDamageDealtBouncing",
        "StatisticEliminations",
        "StatisticEliminationsSliding",
        "StatisticEliminationsCrouching",
        "StatisticEliminationsAirborne",
        "StatisticEliminationsBlinded",
        "StatisticEliminationsDead",
        "StatisticEliminationsNoscope",
        "StatisticEliminationsDashing",
        "StatisticEliminationsDeflecting",
        "StatisticEliminationsBouncing",
        "StatisticDeaths",
        "StatisticDeathsRatio",
        "StatisticAssists",
        "StatisticAssistsDead",
        "StatisticDamageReceived",
        "StatisticHealsReceived",
        "StatisticHealsGiven",
        "StatisticUses",
        "StatisticUsesQuick",
        "StatisticUsesHits",
        "StatisticUsesHitPercent",
        "StatisticUsesCriticalHits",
        "StatisticUsesCriticalHitPercent",
        "StatisticUsesHitsSelf",
        "StatisticUsesHitsDirect",
        "StatisticInspects",
        "StatisticInspectsAfterElimination",
        "StatisticAmmoUsed",
        "StatisticReloads",
        "StatisticAirblasts",
        "StatisticAirblastsHits",
        "StatisticAirblastsSmokesCleared",
        "StatisticDashes",
        "StatisticWallsBuilt",
        "StatisticWallsBuiltBricksLayed",
        "StatisticDeflects",
        "StatisticDeflectsHits",
        "StatisticDeflectsCriticalHits",
        "StatisticExtinguishes",
        "StatisticExtinguishesPlayers",
        "StatisticExtinguishesMolotovs",
        "StatisticExtinguishesFlareGuns",
        "StatisticExtinguishesFlamethrowers",
        "StatisticBlinds",
        "StatisticBlindsSelf",
        "StatisticBlindsEnemies",
        "StatisticBlindsTeammates",
        "StatisticSmokeds",
        "StatisticSmokedsSelf",
        "StatisticSmokedsEnemies",
        "StatisticSmokedsTeammates",
        "StatisticFreezes",
        "StatisticFreezesSelf",
        "StatisticFreezesEnemies"
    },
    ["GetRecoverWinStreakCost"] = "function: 0x85cd150efa8dfcd9",
    ["GetPercent"] = "function: 0x0ccd12e8b3ae2379"
}
