data = {
    ["getQueueMeta"] = "function: 0x00000000d822c18b",
    ["QueueMeta"] = {
        ["bedwars_mega"] = {
            ["ignorePlayFabTeamMatching"] = true,
            ["maps"] = {
                {["mapName"] = "royale_Mega-Plains", ["weight"] = 1},
                {["mapName"] = "royale_Mega-Tundra", ["weight"] = 1},
                {["mapName"] = "royale_Gorge", ["weight"] = 1}
            },
            ["queueSize"] = {["min"] = 1, ["max"] = 4},
            ["placeId"] = 8444591321,
            ["eventText"] = [[🚀 <font color="rgb(255,85,255)">LIMITED TIME MODE!</font> 🚀]],
            ["title"] = "Bed Royale (100 PLAYERS)",
            ["killBounties"] = true,
            ["disabled"] = true,
            ["game"] = "bedwars",
            ["matchStartTime"] = 60,
            ["teams"] = {
                {["id"] = "1", ["displayName"] = "Blue Alpha", ["colorHex"] = 4830450, ["maxPlayers"] = 4},
                {["id"] = "2", ["displayName"] = "Red Alpha", ["colorHex"] = 14886723, ["maxPlayers"] = 4},
                {["id"] = "3", ["displayName"] = "Green Alpha", ["colorHex"] = 2536780, ["maxPlayers"] = 4},
                {["id"] = "4", ["displayName"] = "Yellow Alpha", ["colorHex"] = 16777045, ["maxPlayers"] = 4},
                {["id"] = "5", ["displayName"] = "Orange Alpha", ["colorHex"] = 15896105, ["maxPlayers"] = 4},
                {["id"] = "6", ["displayName"] = "Pink Alpha", ["colorHex"] = 16733695, ["maxPlayers"] = 4},
                {["id"] = "7", ["displayName"] = "Cyan Alpha", ["colorHex"] = 5636095, ["maxPlayers"] = 4},
                {["id"] = "8", ["displayName"] = "Purple Alpha", ["colorHex"] = 11141290, ["maxPlayers"] = 4},
                {["id"] = "9", ["displayName"] = "Blue Beta", ["colorHex"] = 4830460, ["maxPlayers"] = 4},
                {["id"] = "10", ["displayName"] = "Red Beta", ["colorHex"] = 14886733, ["maxPlayers"] = 4},
                {["id"] = "11", ["displayName"] = "Green Beta", ["colorHex"] = 2536790, ["maxPlayers"] = 4},
                {["id"] = "12", ["displayName"] = "Yellow Beta", ["colorHex"] = 16777055, ["maxPlayers"] = 4},
                {["id"] = "13", ["displayName"] = "Orange Beta", ["colorHex"] = 15896115, ["maxPlayers"] = 4},
                {["id"] = "14", ["displayName"] = "Pink Beta", ["colorHex"] = 16733705, ["maxPlayers"] = 4},
                {["id"] = "15", ["displayName"] = "Cyan Beta", ["colorHex"] = 5636105, ["maxPlayers"] = 4},
                {["id"] = "16", ["displayName"] = "Purple Beta", ["colorHex"] = 11141300, ["maxPlayers"] = 4},
                {["id"] = "17", ["displayName"] = "Blue Charlie", ["colorHex"] = 4830470, ["maxPlayers"] = 4},
                {["id"] = "18", ["displayName"] = "Red Charlie", ["colorHex"] = 14886743, ["maxPlayers"] = 4},
                {["id"] = "19", ["displayName"] = "Green Charlie", ["colorHex"] = 2536800, ["maxPlayers"] = 4},
                {["id"] = "20", ["displayName"] = "Yellow Charlie", ["colorHex"] = 16777065, ["maxPlayers"] = 4},
                {["id"] = "21", ["displayName"] = "Orange Charlie", ["colorHex"] = 15896125, ["maxPlayers"] = 4},
                {["id"] = "22", ["displayName"] = "Pink Charlie", ["colorHex"] = 16733715, ["maxPlayers"] = 4},
                {["id"] = "23", ["displayName"] = "Cyan Charlie", ["colorHex"] = 5636115, ["maxPlayers"] = 4},
                {["id"] = "24", ["displayName"] = "Purple Charlie", ["colorHex"] = 11141310, ["maxPlayers"] = 4}
            }
        },
        ["tnt_wars"] = {
            ["noKits"] = true,
            ["maps"] = {
                {["mapName"] = "tnt_Ruins", ["weight"] = 1},
                {["mapName"] = "tnt_Shore", ["weight"] = 1},
                {["mapName"] = "tnt_Plaza", ["weight"] = 1}
            },
            ["queueSize"] = {["min"] = 1, ["max"] = 8},
            ["placeId"] = 6872274481,
            ["disabledFeatures"] = {["disableEnchantTable"] = true, ["disableTitan"] = true},
            ["killBounties"] = true,
            ["eventText"] = [[🔥 <font color="rgb(85,255,85)"><b>LIMITED TIME MODE!</b></font> 🔥]],
            ["title"] = "TNT Wars",
            ["disabled"] = true,
            ["disableRelics"] = true,
            ["game"] = "tnt-wars",
            ["teams"] = {
                {["id"] = "1", ["displayName"] = "Blue", ["colorHex"] = 4830450, ["maxPlayers"] = 8},
                {["id"] = "2", ["displayName"] = "Yellow", ["colorHex"] = 16777045, ["maxPlayers"] = 8}
            },
            ["hudWidgets"] = {}
        },
        ["juggernaut_tdm"] = {
            ["winConInfoHud"] = "Ends in 10:00!",
            ["ignorePlayFabTeamMatching"] = true,
            ["maps"] = {{["mapName"] = "jugg_Outskirts", ["weight"] = 1}},
            ["queueSize"] = {["min"] = 1, ["max"] = 8},
            ["placeId"] = 8444591321,
            ["disableInCustom"] = true,
            ["eventText"] = [[🚨 <font color="rgb(255,85,85)">LIMITED TIME MODE!</font> 🚨]],
            ["title"] = "Juggernaut TDM",
            ["disabled"] = true,
            ["disableRelics"] = true,
            ["game"] = "juggernaut",
            ["teams"] = {
                {["id"] = "1", ["displayName"] = "Blue", ["colorHex"] = 4830450, ["maxPlayers"] = 30},
                {["id"] = "2", ["displayName"] = "Red", ["colorHex"] = 14886723, ["maxPlayers"] = 30}
            },
            ["hudWidgets"] = {"score"}
        },
        ["bedwars_20v20"] = {
            ["glickoCategory"] = "NORMALS",
            ["ignorePlayFabTeamMatching"] = true,
            ["maps"] = {
                {["mapName"] = "to30_Grandpeak", ["weight"] = 1},
                {["mapName"] = "to30_Skull-Island", ["weight"] = 1},
                {["mapName"] = "to30_Desert-Shrine", ["weight"] = 1},
                {["mapName"] = "to30_Fortress", ["weight"] = 1},
                {["mapName"] = "to30_Sanctuary", ["weight"] = 1},
                {["mapName"] = "to30_Kingdom-Gardens", ["weight"] = 1},
                {["mapName"] = "to30_Reservoir", ["weight"] = 1},
                {["mapName"] = "to30_Ships-Ahoy", ["weight"] = 1}
            },
            ["queueSize"] = {["min"] = 1, ["max"] = 8},
            ["placeId"] = 8444591321,
            ["eventText"] = [[<font color="rgb(85,255,255)">FUN!</font>]],
            ["title"] = "BedWars (30v30)",
            ["killBounties"] = true,
            ["game"] = "bedwars",
            ["disabled"] = false,
            ["teams"] = {
                {["id"] = "1", ["displayName"] = "Blue", ["colorHex"] = 4830450, ["maxPlayers"] = 30},
                {["id"] = "2", ["displayName"] = "Orange", ["colorHex"] = 15896105, ["maxPlayers"] = 30}
            }
        },
        ["infected"] = {
            ["winConInfoHud"] = "Win at 12:00",
            ["ignorePlayFabTeamMatching"] = true,
            ["maps"] = {
                {["mapName"] = "infected_IndustryV2", ["weight"] = 1},
                {["mapName"] = "infected_Frost-Site-v2", ["weight"] = 1}
            },
            ["queueSize"] = {["min"] = 1, ["max"] = 16},
            ["placeId"] = 8444591321,
            ["disabled"] = true,
            ["eventText"] = [[🧟‍♀️ <font color="rgb(255,85,255)">LIMITED TIME MODE!</font> 🧟‍♂️]],
            ["title"] = "⚠ Infected ⚠",
            ["disableMatchStatsProgression"] = true,
            ["disableRelics"] = true,
            ["disableLeaderboardProgression"] = true,
            ["game"] = "infected",
            ["teams"] = {
                {["id"] = "1", ["displayName"] = "Humans", ["colorHex"] = 4830450, ["maxPlayers"] = 30},
                {["id"] = "2", ["displayName"] = "Infected", ["colorHex"] = 14886723, ["maxPlayers"] = 5}
            }
        },
        ["gun_game"] = {
            ["noKits"] = true,
            ["ignorePlayFabTeamMatching"] = true,
            ["maps"] = {
                {["mapName"] = "gg_Siege", ["weight"] = 1},
                {["mapName"] = "gg_Ruins", ["weight"] = 1},
                {["mapName"] = "gg_Treetop", ["weight"] = 1},
                {["mapName"] = "gg_Hydroplant", ["weight"] = 1},
                {["mapName"] = "gg_Harbour", ["weight"] = 1}
            },
            ["queueSize"] = {["min"] = 1, ["max"] = 6},
            ["placeId"] = 6872274481,
            ["disabled"] = false,
            ["disableRecalling"] = true,
            ["eventText"] = [[🔥 <font color="rgb(85,255,85)"><b>LIMITED TIME MODE!</b></font> 🔥]],
            ["title"] = "Gun Game",
            ["autoQueue"] = false,
            ["disableRelics"] = true,
            ["game"] = "gun-game",
            ["teams"] = {
                {["id"] = "1", ["displayName"] = "Blue Alpha", ["colorHex"] = 4830450, ["maxPlayers"] = 1},
                {["id"] = "2", ["displayName"] = "Red Alpha", ["colorHex"] = 14886723, ["maxPlayers"] = 1},
                {["id"] = "3", ["displayName"] = "Green Alpha", ["colorHex"] = 2536780, ["maxPlayers"] = 1},
                {["id"] = "4", ["displayName"] = "Yellow Alpha", ["colorHex"] = 16777045, ["maxPlayers"] = 1},
                {["id"] = "5", ["displayName"] = "Orange Alpha", ["colorHex"] = 15896105, ["maxPlayers"] = 1},
                {["id"] = "6", ["displayName"] = "Pink Alpha", ["colorHex"] = 16733695, ["maxPlayers"] = 1},
                {["id"] = "7", ["displayName"] = "Cyan Alpha", ["colorHex"] = 5636095, ["maxPlayers"] = 1},
                {["id"] = "8", ["displayName"] = "Purple Alpha", ["colorHex"] = 11141290, ["maxPlayers"] = 1},
                {["id"] = "9", ["displayName"] = "Blue Beta", ["colorHex"] = 4830460, ["maxPlayers"] = 1},
                {["id"] = "10", ["displayName"] = "Red Beta", ["colorHex"] = 14886733, ["maxPlayers"] = 1},
                {["id"] = "11", ["displayName"] = "Green Beta", ["colorHex"] = 2536790, ["maxPlayers"] = 1},
                {["id"] = "12", ["displayName"] = "Yellow Beta", ["colorHex"] = 16777055, ["maxPlayers"] = 1}
            },
            ["hudWidgets"] = {}
        },
        ["bedwars_ranked_s7"] = {
            ["glickoCategory"] = "RANKED_S7",
            ["disableInCustom"] = true,
            ["maps"] = {
                {["mapName"] = "to5_Champions-Valley", ["weight"] = 1},
                {["mapName"] = "to5_Blossom", ["weight"] = 4},
                {["mapName"] = "to5_Sanctuary", ["weight"] = 1},
                {["mapName"] = "to5_Citadel_Towers", ["weight"] = 1},
                {["mapName"] = "to5_Summit", ["weight"] = 1}
            },
            ["queueSize"] = {["min"] = 1, ["max"] = 5},
            ["partyGlickoFunction"] = "max",
            ["placeId"] = 6872274481,
            ["killBounties"] = true,
            ["disabled"] = true,
            ["eventText"] = "SEASON 7",
            ["title"] = "Ranked (5v5)",
            ["disableRelics"] = true,
            ["rankCategory"] = "RANKED_S7",
            ["game"] = "bedwars",
            ["playerLevelReq"] = 10,
            ["teams"] = {
                {["id"] = "1", ["displayName"] = "Blue", ["colorHex"] = 4830450, ["maxPlayers"] = 5},
                {["id"] = "2", ["displayName"] = "Red", ["colorHex"] = 14886723, ["maxPlayers"] = 5}
            }
        },
        ["bedwars_ranked_s8"] = {
            ["glickoCategory"] = "RANKED_S8",
            ["disableInCustom"] = true,
            ["maps"] = {
                {["mapName"] = "to5_Champions-Valley", ["weight"] = 1},
                {["mapName"] = "to5_Blossom", ["weight"] = 4},
                {["mapName"] = "to5_Sanctuary", ["weight"] = 1},
                {["mapName"] = "to5_Citadel_Towers", ["weight"] = 1},
                {["mapName"] = "to5_Summit", ["weight"] = 1}
            },
            ["queueSize"] = {["min"] = 1, ["max"] = 5},
            ["partyGlickoFunction"] = "max",
            ["placeId"] = 6872274481,
            ["disableVolcanicForge"] = true,
            ["killBounties"] = true,
            ["disabled"] = true,
            ["eventText"] = "Season 8 (ENDED)",
            ["title"] = "Ranked (5v5)",
            ["disableRelics"] = true,
            ["rankCategory"] = "RANKED_S8",
            ["game"] = "bedwars",
            ["playerLevelReq"] = 10,
            ["teams"] = {
                {["id"] = "1", ["displayName"] = "Blue", ["colorHex"] = 4830450, ["maxPlayers"] = 5},
                {["id"] = "2", ["displayName"] = "Red", ["colorHex"] = 14886723, ["maxPlayers"] = 5}
            }
        },
        ["survival"] = {
            ["noKits"] = false,
            ["ignorePlayFabTeamMatching"] = true,
            ["maps"] = {{["mapName"] = "pve_Tropica", ["weight"] = 1}},
            ["queueSize"] = {["min"] = 1, ["max"] = 10},
            ["placeId"] = 6872274481,
            ["disableLeaderboardProgression"] = true,
            ["disableInCustom"] = false,
            ["winConInfoHud"] = "Win at Wave 10",
            ["eventText"] = [[🐧 <font color="rgb(255,85,255)">Limited Time Event!</font> 🐧]],
            ["title"] = "Penguin Survival V2",
            ["disableMatchStatsProgression"] = true,
            ["disableRelics"] = true,
            ["game"] = "survival",
            ["disabled"] = true,
            ["teams"] = {{["id"] = "1", ["displayName"] = "Alive", ["colorHex"] = 4830450, ["maxPlayers"] = 10}}
        },
        ["winter_event"] = {
            ["ignorePlayFabTeamMatching"] = true,
            ["disabled"] = true,
            ["placeId"] = 6872274481,
            ["disableSpectatePlatform"] = true,
            ["ignoreBoundaryDamage"] = true,
            ["eventText"] = [[<font color="rgb(85,255,255)">Fun!</font>]],
            ["disableMatchStatsProgression"] = true,
            ["noKits"] = true,
            ["disableInCustom"] = true,
            ["maps"] = {},
            ["queueSize"] = {["min"] = 1, ["max"] = 4},
            ["disableFreecam"] = true,
            ["title"] = "Minigame Mountain",
            ["teams"] = {
                {["id"] = "1", ["displayName"] = "Blue", ["colorHex"] = 4830450, ["maxPlayers"] = 4},
                {["id"] = "2", ["displayName"] = "Red", ["colorHex"] = 14886723, ["maxPlayers"] = 4},
                {["id"] = "3", ["displayName"] = "Green", ["colorHex"] = 2536780, ["maxPlayers"] = 4},
                {["id"] = "4", ["displayName"] = "Yellow", ["colorHex"] = 16777045, ["maxPlayers"] = 4},
                {["id"] = "5", ["displayName"] = "Orange", ["colorHex"] = 15896105, ["maxPlayers"] = 4},
                {["id"] = "6", ["displayName"] = "Pink", ["colorHex"] = 16733695, ["maxPlayers"] = 4},
                {["id"] = "7", ["displayName"] = "Cyan", ["colorHex"] = 5636095, ["maxPlayers"] = 4},
                {["id"] = "8", ["displayName"] = "Purple", ["colorHex"] = 11141290, ["maxPlayers"] = 4}
            },
            ["disableRelics"] = true,
            ["game"] = "winter-event",
            ["scene"] = "winter_minigame_mountain",
            ["customLeaderStats"] = {}
        },
        ["halloween_event"] = {
            ["ignorePlayFabTeamMatching"] = true,
            ["disabled"] = true,
            ["placeId"] = 6872274481,
            ["disableSpectatePlatform"] = true,
            ["ignoreBoundaryDamage"] = true,
            ["eventText"] = [[<font color="rgb(85,255,255)">FREE KIT!</font>]],
            ["disableRecalling"] = true,
            ["hudWidgets"] = {},
            ["noKits"] = true,
            ["disableInCustom"] = true,
            ["maps"] = {},
            ["queueSize"] = {["min"] = 1, ["max"] = 4},
            ["disableFreecam"] = true,
            ["disableVolcanicForge"] = true,
            ["teams"] = {{["id"] = "1", ["displayName"] = "Explorers", ["colorHex"] = 4830450, ["maxPlayers"] = 4}},
            ["scene"] = "halloween_graveyard_2023",
            ["requiredKeys"] = {{["keyType"] = "halloween_2022_ltm", ["partyLeaderOnly"] = true, ["amount"] = 1}},
            ["title"] = "Crypt's Coven",
            ["disabledFeatures"] = {["disableEnchantTable"] = true, ["hideHpBar"] = true, ["disableTitan"] = true},
            ["disableRelics"] = true,
            ["game"] = "halloween-event",
            ["disableMatchStatsProgression"] = true,
            ["customLeaderStats"] = {}
        },
        ["bedwars_nb4"] = {
            ["glickoCategory"] = "NORMALS",
            ["maps"] = {
                {["mapName"] = "nb4_Aztec", ["weight"] = 1},
                {["mapName"] = "nb4_Blossom", ["weight"] = 1},
                {["mapName"] = "nb4_Sanctum", ["weight"] = 1},
                {["mapName"] = "nb4_Shrine", ["weight"] = 1},
                {["mapName"] = "nb4_Dome", ["weight"] = 1}
            },
            ["queueSize"] = {["min"] = 1, ["max"] = 4},
            ["placeId"] = 6872274481,
            ["eventText"] = [[🚀 <font color="rgb(255,85,255)">LIMITED TIME MODE!</font> 🚀]],
            ["title"] = "No-Build BedWars (Squads)",
            ["disabled"] = true,
            ["autoBedDefense"] = true,
            ["game"] = "bedwars",
            ["killBounties"] = true,
            ["teams"] = {
                {["id"] = "1", ["displayName"] = "Blue", ["colorHex"] = 4830450, ["maxPlayers"] = 4},
                {["id"] = "2", ["displayName"] = "Orange", ["colorHex"] = 15896105, ["maxPlayers"] = 4},
                {["id"] = "3", ["displayName"] = "Pink", ["colorHex"] = 16733695, ["maxPlayers"] = 4},
                {["id"] = "4", ["displayName"] = "Yellow", ["colorHex"] = 16777045, ["maxPlayers"] = 4}
            }
        },
        ["bedwars_ranked_s9"] = {
            ["glickoCategory"] = "RANKED_S9",
            ["disabled"] = false,
            ["placeId"] = 6872274481,
            ["eventText"] = "Season 9",
            ["disableInCustom"] = true,
            ["maps"] = {
                {["mapName"] = "to5_Champions-Valley", ["weight"] = 1},
                {["mapName"] = "to5_Blossom", ["weight"] = 4},
                {["mapName"] = "to5_Sanctuary", ["weight"] = 1},
                {["mapName"] = "to5_Citadel_Towers", ["weight"] = 1},
                {["mapName"] = "to5_Summit", ["weight"] = 1}
            },
            ["queueSize"] = {["min"] = 1, ["max"] = 5},
            ["partyGlickoFunction"] = "max",
            ["disableVolcanicForge"] = true,
            ["killBounties"] = true,
            ["enableBlockDecay"] = true,
            ["title"] = "Ranked (5v5)",
            ["disableRelics"] = true,
            ["rankCategory"] = "RANKED_S9",
            ["game"] = "bedwars",
            ["playerLevelReq"] = 10,
            ["teams"] = {
                {["id"] = "1", ["displayName"] = "Blue", ["colorHex"] = 4830450, ["maxPlayers"] = 5},
                {["id"] = "2", ["displayName"] = "Orange", ["colorHex"] = 15896105, ["maxPlayers"] = 5}
            }
        },
        ["bedwars_disasters_20v20"] = {
            ["ignorePlayFabTeamMatching"] = true,
            ["maps"] = {
                {["mapName"] = "to30_Grandpeak", ["weight"] = 1},
                {["mapName"] = "to30_Skull-Island", ["weight"] = 1},
                {["mapName"] = "to30_Desert-Shrine", ["weight"] = 1},
                {["mapName"] = "to30_Fortress", ["weight"] = 1},
                {["mapName"] = "to30_Sanctuary", ["weight"] = 1},
                {["mapName"] = "to30_Kingdom-Gardens", ["weight"] = 1},
                {["mapName"] = "to30_Reservoir", ["weight"] = 1},
                {["mapName"] = "to30_Ships-Ahoy", ["weight"] = 1}
            },
            ["queueSize"] = {["min"] = 1, ["max"] = 8},
            ["placeId"] = 8444591321,
            ["eventText"] = [[🚀 <font color="rgb(255,85,255)">LIMITED TIME MODE!</font> 🚀]],
            ["title"] = "Disasters (30v30)",
            ["killBounties"] = true,
            ["disabled"] = true,
            ["game"] = "bedwars",
            ["disasters"] = true,
            ["teams"] = {
                {["id"] = "1", ["displayName"] = "Blue", ["colorHex"] = 4830450, ["maxPlayers"] = 30},
                {["id"] = "2", ["displayName"] = "Red", ["colorHex"] = 14886723, ["maxPlayers"] = 30}
            }
        },
        ["hyper_gen_to4"] = {
            ["glickoCategory"] = "NORMALS",
            ["maps"] = {
                {["mapName"] = "to4_Sandbox", ["weight"] = 1},
                {["mapName"] = "to4_Blossom", ["weight"] = 6},
                {["mapName"] = "to4_Voidlands", ["weight"] = 6},
                {["mapName"] = "to4_Airship", ["weight"] = 2},
                {["mapName"] = "to4_Cobblestone-Gardens", ["weight"] = 2},
                {["mapName"] = "to4_Craglands", ["weight"] = 2},
                {["mapName"] = "to4_Fungi-Land", ["weight"] = 2},
                {["mapName"] = "to4_Pond", ["weight"] = 2},
                {["mapName"] = "to4_Swamp", ["weight"] = 2},
                {["mapName"] = "to4_Treehouse", ["weight"] = 2},
                {["mapName"] = "to4_Seasonal", ["weight"] = 1},
                {["mapName"] = "to4_Darkholm", ["weight"] = 1},
                {["mapName"] = "to4_SandShrine", ["weight"] = 1},
                {["mapName"] = "to4_Aztec", ["weight"] = 1},
                {["mapName"] = "to4_Nordic", ["weight"] = 1}
            },
            ["queueSize"] = {["min"] = 1, ["max"] = 4},
            ["placeId"] = 6872274481,
            ["eventText"] = [[<font color="rgb(85,255,85)"><b>Fast!</b></font>]],
            ["title"] = "Hyper Gen (Squads)",
            ["hyperGenGamemode"] = true,
            ["disabled"] = true,
            ["game"] = "bedwars",
            ["killBounties"] = true,
            ["teams"] = {
                {["id"] = "1", ["displayName"] = "Blue", ["colorHex"] = 4830450, ["maxPlayers"] = 4},
                {["id"] = "2", ["displayName"] = "Orange", ["colorHex"] = 15896105, ["maxPlayers"] = 4},
                {["id"] = "3", ["displayName"] = "Pink", ["colorHex"] = 16733695, ["maxPlayers"] = 4},
                {["id"] = "4", ["displayName"] = "Yellow", ["colorHex"] = 16777045, ["maxPlayers"] = 4}
            }
        },
        ["bedwars_5v5"] = {
            ["glickoCategory"] = "NORMALS",
            ["maps"] = {
                {["mapName"] = "to5_Champions-Valley", ["weight"] = 1},
                {["mapName"] = "to5_Blossom", ["weight"] = 4},
                {["mapName"] = "to5_Sanctuary", ["weight"] = 1},
                {["mapName"] = "to5_Citadel_Towers", ["weight"] = 1},
                {["mapName"] = "to5_Summit", ["weight"] = 1}
            },
            ["queueSize"] = {["min"] = 1, ["max"] = 5},
            ["disableLimitedTimeItems"] = true,
            ["placeId"] = 6872274481,
            ["enableBlockDecay"] = true,
            ["title"] = "BedWars (5v5)",
            ["killBounties"] = true,
            ["disableRelics"] = true,
            ["game"] = "bedwars",
            ["disabled"] = false,
            ["teams"] = {
                {["id"] = "1", ["displayName"] = "Blue", ["colorHex"] = 4830450, ["maxPlayers"] = 5},
                {["id"] = "2", ["displayName"] = "Orange", ["colorHex"] = 15896105, ["maxPlayers"] = 5}
            }
        },
        ["bedwars_to4"] = {
            ["glickoCategory"] = "NORMALS",
            ["maps"] = {
                {["mapName"] = "to4_Sandbox", ["weight"] = 1},
                {["mapName"] = "to4_Blossom", ["weight"] = 6},
                {["mapName"] = "to4_Voidlands", ["weight"] = 6},
                {["mapName"] = "to4_Airship", ["weight"] = 2},
                {["mapName"] = "to4_Cobblestone-Gardens", ["weight"] = 2},
                {["mapName"] = "to4_Craglands", ["weight"] = 2},
                {["mapName"] = "to4_Fungi-Land", ["weight"] = 2},
                {["mapName"] = "to4_Pond", ["weight"] = 2},
                {["mapName"] = "to4_Swamp", ["weight"] = 2},
                {["mapName"] = "to4_Treehouse", ["weight"] = 2},
                {["mapName"] = "to4_Seasonal", ["weight"] = 1},
                {["mapName"] = "to4_Darkholm", ["weight"] = 1},
                {["mapName"] = "to4_SandShrine", ["weight"] = 1},
                {["mapName"] = "to4_Aztec", ["weight"] = 1},
                {["mapName"] = "to4_Nordic", ["weight"] = 1}
            },
            ["queueSize"] = {["min"] = 1, ["max"] = 4},
            ["placeId"] = 6872274481,
            ["eventText"] = [[<font color="rgb(85,255,85)"><b>POPULAR!!</b></font>]],
            ["title"] = "BedWars (Squads)",
            ["enableBlockDecay"] = true,
            ["game"] = "bedwars",
            ["killBounties"] = true,
            ["teams"] = {
                {["id"] = "1", ["displayName"] = "Blue", ["colorHex"] = 4830450, ["maxPlayers"] = 4},
                {["id"] = "2", ["displayName"] = "Orange", ["colorHex"] = 15896105, ["maxPlayers"] = 4},
                {["id"] = "3", ["displayName"] = "Pink", ["colorHex"] = 16733695, ["maxPlayers"] = 4},
                {["id"] = "4", ["displayName"] = "Yellow", ["colorHex"] = 16777045, ["maxPlayers"] = 4}
            }
        },
        ["sandbox"] = {
            ["disabled"] = false,
            ["title"] = "Sandbox",
            ["queueSize"] = {["min"] = 1, ["max"] = 1},
            ["game"] = "sandbox",
            ["placeId"] = 8444591321,
            ["maps"] = {{["mapName"] = "to4_Sandbox", ["weight"] = 1}},
            ["teams"] = {
                {["id"] = "1", ["displayName"] = "Blue", ["colorHex"] = 4830450, ["maxPlayers"] = 32},
                {["id"] = "2", ["displayName"] = "Orange", ["colorHex"] = 15896105, ["maxPlayers"] = 32},
                {["id"] = "3", ["displayName"] = "Pink", ["colorHex"] = 16733695, ["maxPlayers"] = 32},
                {["id"] = "4", ["displayName"] = "Yellow", ["colorHex"] = 16777045, ["maxPlayers"] = 32}
            }
        },
        ["juggernaut_v2"] = {
            ["noKits"] = true,
            ["ignorePlayFabTeamMatching"] = true,
            ["maps"] = {{["mapName"] = "jugg_Outskirts", ["weight"] = 1}},
            ["queueSize"] = {["min"] = 1, ["max"] = 12},
            ["disableDamageHighlight"] = true,
            ["placeId"] = 6872274481,
            ["customLeaderStats"] = {},
            ["teams"] = {
                {["id"] = "1", ["displayName"] = "Players", ["colorHex"] = 4830450, ["maxPlayers"] = 16},
                {["id"] = "2", ["displayName"] = "Juggernaut", ["colorHex"] = 14886723, ["maxPlayers"] = 0}
            },
            ["disabled"] = true,
            ["eventText"] = [[🔥 <font color="rgb(85,255,85)"><b>LIMITED TIME MODE!</b></font> 🔥]],
            ["title"] = "Juggernaut",
            ["autoQueue"] = false,
            ["disableRelics"] = true,
            ["game"] = "jugg-v2",
            ["winConInfoHud"] = "First to 20 Kills",
            ["hudWidgets"] = {}
        },
        ["bedwars_test"] = {
            ["disableInCustom"] = true,
            ["maps"] = {{["mapName"] = "to4_Aztec", ["weight"] = 1}},
            ["queueSize"] = {["min"] = 1, ["max"] = 4},
            ["placeId"] = 8444591321,
            ["eventText"] = [[<font color="rgb(85,255,85)"><b>POPULAR!!</b></font>]],
            ["title"] = "BedWars (Testing)",
            ["game"] = "bedwars",
            ["disabled"] = true,
            ["teams"] = {
                {["id"] = "1", ["displayName"] = "Blue", ["colorHex"] = 4830450, ["maxPlayers"] = 4},
                {["id"] = "2", ["displayName"] = "Orange", ["colorHex"] = 15896105, ["maxPlayers"] = 4},
                {["id"] = "3", ["displayName"] = "Pink", ["colorHex"] = 16733695, ["maxPlayers"] = 4},
                {["id"] = "4", ["displayName"] = "Yellow", ["colorHex"] = 16777045, ["maxPlayers"] = 4}
            }
        },
        ["bedwars_20v20_lb"] = {
            ["glickoCategory"] = "LUCKY_BLOCK",
            ["ignorePlayFabTeamMatching"] = true,
            ["maps"] = {
                {["mapName"] = "to30_Grandpeak", ["weight"] = 1},
                {["mapName"] = "to30_Skull-Island", ["weight"] = 1},
                {["mapName"] = "to30_Desert-Shrine", ["weight"] = 1},
                {["mapName"] = "to30_Fortress", ["weight"] = 1},
                {["mapName"] = "to30_Sanctuary", ["weight"] = 1},
                {["mapName"] = "to30_Kingdom-Gardens", ["weight"] = 1},
                {["mapName"] = "to30_Reservoir", ["weight"] = 1},
                {["mapName"] = "to30_Ships-Ahoy", ["weight"] = 1}
            },
            ["queueSize"] = {["min"] = 1, ["max"] = 8},
            ["placeId"] = 8444591321,
            ["eventText"] = [[✨ <font color="rgb(85,255,255)">LIMITED TIME MODE!</font> ✨]],
            ["title"] = "Lucky Block (30v30)",
            ["killBounties"] = true,
            ["disabled"] = true,
            ["game"] = "bedwars",
            ["luckyBlock"] = true,
            ["teams"] = {
                {["id"] = "1", ["displayName"] = "Blue", ["colorHex"] = 4830450, ["maxPlayers"] = 30},
                {["id"] = "2", ["displayName"] = "Red", ["colorHex"] = 14886723, ["maxPlayers"] = 30}
            }
        },
        ["winstreak_1v1"] = {
            ["glickoCategory"] = "DUELS",
            ["maps"] = {
                {["mapName"] = "duels_Volatile", ["weight"] = 1},
                {["mapName"] = "duels_Ruins", ["weight"] = 1},
                {["mapName"] = "duels_Glacier", ["weight"] = 1},
                {["mapName"] = "duels_Blossom", ["weight"] = 6},
                {["mapName"] = "duels_Sand-Temple", ["weight"] = 1},
                {["mapName"] = "duels_Glade", ["weight"] = 1},
                {["mapName"] = "duels_Canyon", ["weight"] = 1},
                {["mapName"] = "duels_Mystic", ["weight"] = 1},
                {["mapName"] = "duels_Farmland", ["weight"] = 1},
                {["mapName"] = "duels_Nordic", ["weight"] = 1},
                {["mapName"] = "duels_Desert-Shrine", ["weight"] = 1}
            },
            ["queueSize"] = {["min"] = 1, ["max"] = 1},
            ["placeId"] = 8560631822,
            ["killBounties"] = true,
            ["eventText"] = [[🥳 <font color="rgb(255,85,255)">LIMITED TIME MODE!</font> 🥳]],
            ["title"] = "Winstreak (1v1)",
            ["disabledFeatures"] = {["disableBedPlating"] = true},
            ["game"] = "bedwars",
            ["disableLeaderboardProgression"] = true,
            ["disabled"] = false,
            ["teams"] = {
                {["id"] = "1", ["displayName"] = "Blue", ["colorHex"] = 4830450, ["maxPlayers"] = 1},
                {["id"] = "2", ["displayName"] = "Orange", ["colorHex"] = 15896105, ["maxPlayers"] = 1}
            }
        },
        ["all_same_kit_to4"] = {
            ["glickoCategory"] = "NORMALS",
            ["maps"] = {
                {["mapName"] = "to4_Sandbox", ["weight"] = 1},
                {["mapName"] = "to4_Blossom", ["weight"] = 6},
                {["mapName"] = "to4_Voidlands", ["weight"] = 6},
                {["mapName"] = "to4_Airship", ["weight"] = 2},
                {["mapName"] = "to4_Cobblestone-Gardens", ["weight"] = 2},
                {["mapName"] = "to4_Craglands", ["weight"] = 2},
                {["mapName"] = "to4_Fungi-Land", ["weight"] = 2},
                {["mapName"] = "to4_Pond", ["weight"] = 2},
                {["mapName"] = "to4_Swamp", ["weight"] = 2},
                {["mapName"] = "to4_Treehouse", ["weight"] = 2},
                {["mapName"] = "to4_Seasonal", ["weight"] = 1},
                {["mapName"] = "to4_Darkholm", ["weight"] = 1},
                {["mapName"] = "to4_SandShrine", ["weight"] = 1},
                {["mapName"] = "to4_Aztec", ["weight"] = 1},
                {["mapName"] = "to4_Nordic", ["weight"] = 1}
            },
            ["queueSize"] = {["min"] = 1, ["max"] = 4},
            ["placeId"] = 6872274481,
            ["eventText"] = [[🚀 <font color="rgb(255,85,255)">LIMITED TIME MODE!</font> 🚀]],
            ["title"] = "All Same Kit (Squads)",
            ["disabled"] = true,
            ["game"] = "bedwars",
            ["killBounties"] = true,
            ["teams"] = {
                {["id"] = "1", ["displayName"] = "Blue", ["colorHex"] = 4830450, ["maxPlayers"] = 4},
                {["id"] = "2", ["displayName"] = "Orange", ["colorHex"] = 15896105, ["maxPlayers"] = 4},
                {["id"] = "3", ["displayName"] = "Pink", ["colorHex"] = 16733695, ["maxPlayers"] = 4},
                {["id"] = "4", ["displayName"] = "Yellow", ["colorHex"] = 16777045, ["maxPlayers"] = 4}
            }
        },
        ["bedwars_ranked_beta"] = {
            ["glickoCategory"] = "RANKED_BETA",
            ["disableInCustom"] = true,
            ["maps"] = {
                {["mapName"] = "to4_Sandbox", ["weight"] = 1},
                {["mapName"] = "to4_Blossom", ["weight"] = 6},
                {["mapName"] = "to4_Voidlands", ["weight"] = 6},
                {["mapName"] = "to4_Airship", ["weight"] = 2},
                {["mapName"] = "to4_Cobblestone-Gardens", ["weight"] = 2},
                {["mapName"] = "to4_Craglands", ["weight"] = 2},
                {["mapName"] = "to4_Fungi-Land", ["weight"] = 2},
                {["mapName"] = "to4_Pond", ["weight"] = 2},
                {["mapName"] = "to4_Swamp", ["weight"] = 2},
                {["mapName"] = "to4_Treehouse", ["weight"] = 2},
                {["mapName"] = "to4_Seasonal", ["weight"] = 1},
                {["mapName"] = "to4_Darkholm", ["weight"] = 1},
                {["mapName"] = "to4_SandShrine", ["weight"] = 1},
                {["mapName"] = "to4_Aztec", ["weight"] = 1},
                {["mapName"] = "to4_Nordic", ["weight"] = 1}
            },
            ["queueSize"] = {["min"] = 1, ["max"] = 4},
            ["partyGlickoFunction"] = "max",
            ["placeId"] = 6872274481,
            ["eventText"] = "BETA SEASON",
            ["title"] = "Ranked (Squads)",
            ["rankCategory"] = "RANKED_BETA",
            ["game"] = "bedwars",
            ["disabled"] = true,
            ["teams"] = {
                {["id"] = "1", ["displayName"] = "Blue", ["colorHex"] = 4830450, ["maxPlayers"] = 4},
                {["id"] = "2", ["displayName"] = "Red", ["colorHex"] = 14886723, ["maxPlayers"] = 4},
                {["id"] = "3", ["displayName"] = "Green", ["colorHex"] = 2536780, ["maxPlayers"] = 4},
                {["id"] = "4", ["displayName"] = "Yellow", ["colorHex"] = 16777045, ["maxPlayers"] = 4}
            }
        },
        ["skywars_to2"] = {
            ["noKits"] = true,
            ["maps"] = {
                {["mapName"] = "sw_Cistern", ["weight"] = 1},
                {["mapName"] = "sw_Wasteland", ["weight"] = 1},
                {["mapName"] = "sw_Volatile", ["weight"] = 1},
                {["mapName"] = "sw_Tundra", ["weight"] = 1},
                {["mapName"] = "sw_Glade", ["weight"] = 1},
                {["mapName"] = "sw_Bamboo-Garden", ["weight"] = 1},
                {["mapName"] = "sw_Bloom", ["weight"] = 1},
                {["mapName"] = "sw_Palace", ["weight"] = 1},
                {["mapName"] = "sw_Sandy-Cove", ["weight"] = 1},
                {["mapName"] = "sw_Pinewood", ["weight"] = 1},
                {["mapName"] = "sw_Grim-Glade", ["weight"] = 1},
                {["mapName"] = "sw_Frosty-Woods", ["weight"] = 1},
                {["mapName"] = "sw_Desert-Shrine", ["weight"] = 1},
                {["mapName"] = "sw_Cobblestone-Gardens", ["weight"] = 1}
            },
            ["queueSize"] = {["min"] = 1, ["max"] = 2},
            ["placeId"] = 6872274481,
            ["glickoCategory"] = "SKYWARS",
            ["autoQueue"] = false,
            ["disableRecalling"] = true,
            ["eventText"] = [[⚔️ <font color="rgb(255,85,85)">FAST PACED!</font> ⚔️]],
            ["title"] = "SkyWars (Doubles)",
            ["teams"] = {
                {["id"] = "1", ["displayName"] = "Blue", ["colorHex"] = 4830450, ["maxPlayers"] = 2},
                {["id"] = "2", ["displayName"] = "Orange", ["colorHex"] = 15896105, ["maxPlayers"] = 2},
                {["id"] = "3", ["displayName"] = "Pink", ["colorHex"] = 16733695, ["maxPlayers"] = 2},
                {["id"] = "4", ["displayName"] = "Yellow", ["colorHex"] = 16777045, ["maxPlayers"] = 2},
                {["id"] = "5", ["displayName"] = "Brown", ["colorHex"] = 10117924, ["maxPlayers"] = 2},
                {["id"] = "6", ["displayName"] = "White", ["colorHex"] = 15990527, ["maxPlayers"] = 2},
                {["id"] = "7", ["displayName"] = "Cyan", ["colorHex"] = 5636095, ["maxPlayers"] = 2},
                {["id"] = "8", ["displayName"] = "Purple", ["colorHex"] = 11141290, ["maxPlayers"] = 2},
                {["id"] = "9", ["displayName"] = "Black", ["colorHex"] = 0, ["maxPlayers"] = 2},
                {["id"] = "10", ["displayName"] = "Gray", ["colorHex"] = 11119017, ["maxPlayers"] = 2},
                {["id"] = "11", ["displayName"] = "Lime", ["colorHex"] = 12578629, ["maxPlayers"] = 2},
                {["id"] = "12", ["displayName"] = "Red", ["colorHex"] = 14886723, ["maxPlayers"] = 2}
            },
            ["disableRelics"] = true,
            ["game"] = "skywars",
            ["disabled"] = false,
            ["hudWidgets"] = {"players_alive"}
        },
        ["bedwars_ranked_s6"] = {
            ["minWinReq"] = 100,
            ["disableInCustom"] = true,
            ["maps"] = {
                {["mapName"] = "to4_Sandbox", ["weight"] = 1},
                {["mapName"] = "to4_Blossom", ["weight"] = 6},
                {["mapName"] = "to4_Voidlands", ["weight"] = 6},
                {["mapName"] = "to4_Airship", ["weight"] = 2},
                {["mapName"] = "to4_Cobblestone-Gardens", ["weight"] = 2},
                {["mapName"] = "to4_Craglands", ["weight"] = 2},
                {["mapName"] = "to4_Fungi-Land", ["weight"] = 2},
                {["mapName"] = "to4_Pond", ["weight"] = 2},
                {["mapName"] = "to4_Swamp", ["weight"] = 2},
                {["mapName"] = "to4_Treehouse", ["weight"] = 2},
                {["mapName"] = "to4_Seasonal", ["weight"] = 1},
                {["mapName"] = "to4_Darkholm", ["weight"] = 1},
                {["mapName"] = "to4_SandShrine", ["weight"] = 1},
                {["mapName"] = "to4_Aztec", ["weight"] = 1},
                {["mapName"] = "to4_Nordic", ["weight"] = 1}
            },
            ["queueSize"] = {["min"] = 1, ["max"] = 4},
            ["partyGlickoFunction"] = "max",
            ["placeId"] = 6872274481,
            ["disabled"] = true,
            ["eventText"] = "SEASON 6",
            ["title"] = "Ranked (Squads)",
            ["disableRelics"] = true,
            ["rankCategory"] = "RANKED_S6",
            ["game"] = "bedwars",
            ["glickoCategory"] = "RANKED_S6",
            ["teams"] = {
                {["id"] = "1", ["displayName"] = "Blue", ["colorHex"] = 4830450, ["maxPlayers"] = 4},
                {["id"] = "2", ["displayName"] = "Red", ["colorHex"] = 14886723, ["maxPlayers"] = 4},
                {["id"] = "3", ["displayName"] = "Green", ["colorHex"] = 2536780, ["maxPlayers"] = 4},
                {["id"] = "4", ["displayName"] = "Yellow", ["colorHex"] = 16777045, ["maxPlayers"] = 4}
            }
        },
        ["bedwars_disasters_to4"] = {
            ["maps"] = {
                {["mapName"] = "to4_Sandbox", ["weight"] = 1},
                {["mapName"] = "to4_Blossom", ["weight"] = 6},
                {["mapName"] = "to4_Voidlands", ["weight"] = 6},
                {["mapName"] = "to4_Airship", ["weight"] = 2},
                {["mapName"] = "to4_Cobblestone-Gardens", ["weight"] = 2},
                {["mapName"] = "to4_Craglands", ["weight"] = 2},
                {["mapName"] = "to4_Fungi-Land", ["weight"] = 2},
                {["mapName"] = "to4_Pond", ["weight"] = 2},
                {["mapName"] = "to4_Swamp", ["weight"] = 2},
                {["mapName"] = "to4_Treehouse", ["weight"] = 2},
                {["mapName"] = "to4_Seasonal", ["weight"] = 1},
                {["mapName"] = "to4_Darkholm", ["weight"] = 1},
                {["mapName"] = "to4_SandShrine", ["weight"] = 1},
                {["mapName"] = "to4_Aztec", ["weight"] = 1},
                {["mapName"] = "to4_Nordic", ["weight"] = 1}
            },
            ["queueSize"] = {["min"] = 1, ["max"] = 4},
            ["placeId"] = 6872274481,
            ["eventText"] = [[🔥 <font color="rgb(255,85,85)">LIMITED TIME MODE!</font> 🔥]],
            ["title"] = "Disasters (Squads)",
            ["killBounties"] = true,
            ["disabled"] = true,
            ["game"] = "bedwars",
            ["disasters"] = true,
            ["teams"] = {
                {["id"] = "1", ["displayName"] = "Blue", ["colorHex"] = 4830450, ["maxPlayers"] = 4},
                {["id"] = "2", ["displayName"] = "Orange", ["colorHex"] = 15896105, ["maxPlayers"] = 4},
                {["id"] = "3", ["displayName"] = "Pink", ["colorHex"] = 16733695, ["maxPlayers"] = 4},
                {["id"] = "4", ["displayName"] = "Yellow", ["colorHex"] = 16777045, ["maxPlayers"] = 4}
            }
        },
        ["bedwars_lucky_block"] = {
            ["glickoCategory"] = "LUCKY_BLOCK",
            ["maps"] = {
                {["mapName"] = "to4_Sandbox", ["weight"] = 1},
                {["mapName"] = "to4_Blossom", ["weight"] = 6},
                {["mapName"] = "to4_Voidlands", ["weight"] = 6},
                {["mapName"] = "to4_Airship", ["weight"] = 2},
                {["mapName"] = "to4_Cobblestone-Gardens", ["weight"] = 2},
                {["mapName"] = "to4_Craglands", ["weight"] = 2},
                {["mapName"] = "to4_Fungi-Land", ["weight"] = 2},
                {["mapName"] = "to4_Pond", ["weight"] = 2},
                {["mapName"] = "to4_Swamp", ["weight"] = 2},
                {["mapName"] = "to4_Treehouse", ["weight"] = 2},
                {["mapName"] = "to4_Seasonal", ["weight"] = 1},
                {["mapName"] = "to4_Darkholm", ["weight"] = 1},
                {["mapName"] = "to4_SandShrine", ["weight"] = 1},
                {["mapName"] = "to4_Aztec", ["weight"] = 1},
                {["mapName"] = "to4_Nordic", ["weight"] = 1}
            },
            ["queueSize"] = {["min"] = 1, ["max"] = 4},
            ["placeId"] = 6872274481,
            ["title"] = "Lucky Block (Squads)",
            ["killBounties"] = true,
            ["game"] = "bedwars",
            ["disableLeaderboardProgression"] = true,
            ["luckyBlock"] = true,
            ["teams"] = {
                {["id"] = "1", ["displayName"] = "Blue", ["colorHex"] = 4830450, ["maxPlayers"] = 4},
                {["id"] = "2", ["displayName"] = "Orange", ["colorHex"] = 15896105, ["maxPlayers"] = 4},
                {["id"] = "3", ["displayName"] = "Pink", ["colorHex"] = 16733695, ["maxPlayers"] = 4},
                {["id"] = "4", ["displayName"] = "Yellow", ["colorHex"] = 16777045, ["maxPlayers"] = 4}
            }
        },
        ["bridge_duel"] = {
            ["glickoCategory"] = "BRIDGE_DUELS",
            ["disableCharacterReset"] = true,
            ["maps"] = {
                {["mapName"] = "bridgeDuel_Dunes", ["weight"] = 1},
                {["mapName"] = "bridgeDuel_Wonderland", ["weight"] = 1},
                {["mapName"] = "bridgeDuel_Blossom", ["weight"] = 2},
                {["mapName"] = "bridgeDuel_Desert", ["weight"] = 1}
            },
            ["queueSize"] = {["min"] = 1, ["max"] = 1},
            ["disabledFeatures"] = {
                ["disableEnchantTable"] = true,
                ["disableBedPlating"] = true,
                ["disableTitan"] = true
            },
            ["placeId"] = 8560631822,
            ["teams"] = {
                {["id"] = "1", ["displayName"] = "Blue", ["colorHex"] = 4830450, ["maxPlayers"] = 1},
                {["id"] = "2", ["displayName"] = "Orange", ["colorHex"] = 15896105, ["maxPlayers"] = 1}
            },
            ["killBounties"] = false,
            ["disableRecalling"] = true,
            ["eventText"] = [[🚀 <font color="rgb(255,85,255)">LIMITED TIME MODE!</font> 🚀]],
            ["title"] = "Bridge Battle",
            ["noKits"] = true,
            ["disableLeaderboardProgression"] = true,
            ["game"] = "bridge-duel",
            ["disabled"] = true,
            ["hudWidgets"] = {"bridge_duel_score"}
        },
        ["block_hunt"] = {
            ["ignorePlayFabTeamMatching"] = true,
            ["disabled"] = true,
            ["placeId"] = 8444591321,
            ["ignoreBoundaryDamage"] = true,
            ["eventText"] = [[🥳 <font color="rgb(255,85,255)">LIMITED TIME MODE!</font> 🥳]],
            ["disableLeaderboardProgression"] = true,
            ["winConInfoHud"] = "Win at 8:45",
            ["disableInCustom"] = false,
            ["maps"] = {{["mapName"] = "BH_Kingdom", ["weight"] = 1}, {["mapName"] = "BH_Excavation", ["weight"] = 1}},
            ["queueSize"] = {["min"] = 1, ["max"] = 22},
            ["disabledMatchEndScreens"] = {},
            ["disableVolcanicForge"] = true,
            ["noKits"] = true,
            ["disabledFeatures"] = {["disableEnchantTable"] = true, ["hideHpBar"] = true, ["disableTitan"] = true},
            ["title"] = "Block Hunt",
            ["disableRecalling"] = true,
            ["killBounties"] = false,
            ["game"] = "block-hunt",
            ["disableMatchStatsProgression"] = true,
            ["teams"] = {
                {["id"] = "2", ["displayName"] = "Hiders", ["colorHex"] = 4830450, ["maxPlayers"] = 20},
                {["id"] = "1", ["displayName"] = "Hunter", ["colorHex"] = 14886723, ["maxPlayers"] = 2}
            }
        },
        ["bedwars_og_to4"] = {
            ["noKits"] = true,
            ["maps"] = {
                {["mapName"] = "to4OG_Old-Aztec", ["weight"] = 1},
                {["mapName"] = "to4OG_Old-Blossom", ["weight"] = 1},
                {["mapName"] = "to4OG_Old-Glacier", ["weight"] = 1},
                {["mapName"] = "to4OG_Old-Mini-Golf", ["weight"] = 1}
            },
            ["queueSize"] = {["min"] = 1, ["max"] = 4},
            ["placeId"] = 6872274481,
            ["disableRecalling"] = true,
            ["eventText"] = [[<font color="rgb(254,171,0)"><b>OLD SCHOOL!</b></font>]],
            ["title"] = "OG BedWars",
            ["disabledFeatures"] = {["disableEnchantTable"] = true, ["hideHpBar"] = true, ["disableTitan"] = true},
            ["disabled"] = true,
            ["game"] = "bedwars",
            ["killBounties"] = false,
            ["teams"] = {
                {["id"] = "1", ["displayName"] = "Blue", ["colorHex"] = 4830450, ["maxPlayers"] = 4},
                {["id"] = "2", ["displayName"] = "Orange", ["colorHex"] = 15896105, ["maxPlayers"] = 4},
                {["id"] = "3", ["displayName"] = "Pink", ["colorHex"] = 16733695, ["maxPlayers"] = 4},
                {["id"] = "4", ["displayName"] = "Yellow", ["colorHex"] = 16777045, ["maxPlayers"] = 4}
            }
        },
        ["bedwars_ranked_s4"] = {
            ["glickoCategory"] = "RANKED_S4",
            ["disableInCustom"] = true,
            ["maps"] = {
                {["mapName"] = "to4_Sandbox", ["weight"] = 1},
                {["mapName"] = "to4_Blossom", ["weight"] = 6},
                {["mapName"] = "to4_Voidlands", ["weight"] = 6},
                {["mapName"] = "to4_Airship", ["weight"] = 2},
                {["mapName"] = "to4_Cobblestone-Gardens", ["weight"] = 2},
                {["mapName"] = "to4_Craglands", ["weight"] = 2},
                {["mapName"] = "to4_Fungi-Land", ["weight"] = 2},
                {["mapName"] = "to4_Pond", ["weight"] = 2},
                {["mapName"] = "to4_Swamp", ["weight"] = 2},
                {["mapName"] = "to4_Treehouse", ["weight"] = 2},
                {["mapName"] = "to4_Seasonal", ["weight"] = 1},
                {["mapName"] = "to4_Darkholm", ["weight"] = 1},
                {["mapName"] = "to4_SandShrine", ["weight"] = 1},
                {["mapName"] = "to4_Aztec", ["weight"] = 1},
                {["mapName"] = "to4_Nordic", ["weight"] = 1}
            },
            ["queueSize"] = {["min"] = 1, ["max"] = 4},
            ["partyGlickoFunction"] = "max",
            ["placeId"] = 6872274481,
            ["eventText"] = "SEASON 4",
            ["title"] = "Ranked (Squads)",
            ["rankCategory"] = "RANKED_S4",
            ["game"] = "bedwars",
            ["disabled"] = true,
            ["teams"] = {
                {["id"] = "1", ["displayName"] = "Blue", ["colorHex"] = 4830450, ["maxPlayers"] = 4},
                {["id"] = "2", ["displayName"] = "Red", ["colorHex"] = 14886723, ["maxPlayers"] = 4},
                {["id"] = "3", ["displayName"] = "Green", ["colorHex"] = 2536780, ["maxPlayers"] = 4},
                {["id"] = "4", ["displayName"] = "Yellow", ["colorHex"] = 16777045, ["maxPlayers"] = 4}
            }
        },
        ["flag_capture"] = {
            ["noKits"] = true,
            ["maps"] = {
                {["mapName"] = "to30_Campsite", ["weight"] = 1},
                {["mapName"] = "to30_Ships-Ahoy", ["weight"] = 1},
                {["mapName"] = "to30_Reservoir", ["weight"] = 1},
                {["mapName"] = "to30_Castle", ["weight"] = 1},
                {["mapName"] = "to30_Fortress", ["weight"] = 1}
            },
            ["queueSize"] = {["min"] = 1, ["max"] = 12},
            ["placeId"] = 6872274481,
            ["killBounties"] = true,
            ["eventText"] = [[🚨 <font color="rgb(255,85,85)">LIMITED TIME MODE!</font> 🚨]],
            ["title"] = "Capture the Flag",
            ["disabled"] = true,
            ["winConInfoHud"] = "Ends at 20:00",
            ["game"] = "FLAG_CAPTURE",
            ["teams"] = {
                {["id"] = "1", ["displayName"] = "Blue", ["colorHex"] = 4830450, ["maxPlayers"] = 12},
                {["id"] = "2", ["displayName"] = "Yellow", ["colorHex"] = 16777045, ["maxPlayers"] = 12}
            },
            ["hudWidgets"] = {}
        },
        ["skull_drop"] = {
            ["glickoCategory"] = "NORMALS",
            ["ignorePlayFabTeamMatching"] = true,
            ["disabled"] = true,
            ["disableBlockPlace"] = true,
            ["placeId"] = 8444591321,
            ["ignoreBoundaryDamage"] = true,
            ["eventText"] = [[🚀 <font color="rgb(255,85,255)">LIMITED TIME MODE!</font> 🚀]],
            ["disableMatchStatsProgression"] = true,
            ["noKits"] = true,
            ["maps"] = {{["mapName"] = "BH_Castle", ["weight"] = 1}},
            ["queueSize"] = {["min"] = 1, ["max"] = 10},
            ["disableVolcanicForge"] = true,
            ["disabledFeatures"] = {["disableEnchantTable"] = true, ["disableTitan"] = true},
            ["title"] = "Skull Drop",
            ["disableRecalling"] = true,
            ["disableKillEffects"] = true,
            ["game"] = "skull-drop",
            ["killBounties"] = false,
            ["teams"] = {
                {["id"] = "1", ["displayName"] = "Blue Alpha", ["colorHex"] = 4830450, ["maxPlayers"] = 1},
                {["id"] = "2", ["displayName"] = "White Alpha", ["colorHex"] = 15990527, ["maxPlayers"] = 1},
                {["id"] = "3", ["displayName"] = "Brown Alpha", ["colorHex"] = 10117924, ["maxPlayers"] = 1},
                {["id"] = "4", ["displayName"] = "Yellow Alpha", ["colorHex"] = 16777045, ["maxPlayers"] = 1},
                {["id"] = "5", ["displayName"] = "Orange Alpha", ["colorHex"] = 15896105, ["maxPlayers"] = 1},
                {["id"] = "6", ["displayName"] = "Pink Alpha", ["colorHex"] = 16733695, ["maxPlayers"] = 1},
                {["id"] = "7", ["displayName"] = "Cyan Alpha", ["colorHex"] = 5636095, ["maxPlayers"] = 1},
                {["id"] = "8", ["displayName"] = "Purple Alpha", ["colorHex"] = 11141290, ["maxPlayers"] = 1},
                {["id"] = "9", ["displayName"] = "Blue Beta", ["colorHex"] = 4830460, ["maxPlayers"] = 1},
                {["id"] = "10", ["displayName"] = "Orange Beta", ["colorHex"] = 15896115, ["maxPlayers"] = 1}
            }
        },
        ["bedwars_duels"] = {
            ["glickoCategory"] = "DUELS",
            ["maps"] = {
                {["mapName"] = "duels_Volatile", ["weight"] = 1},
                {["mapName"] = "duels_Ruins", ["weight"] = 1},
                {["mapName"] = "duels_Glacier", ["weight"] = 1},
                {["mapName"] = "duels_Blossom", ["weight"] = 6},
                {["mapName"] = "duels_Sand-Temple", ["weight"] = 1},
                {["mapName"] = "duels_Glade", ["weight"] = 1},
                {["mapName"] = "duels_Canyon", ["weight"] = 1},
                {["mapName"] = "duels_Mystic", ["weight"] = 1},
                {["mapName"] = "duels_Farmland", ["weight"] = 1},
                {["mapName"] = "duels_Nordic", ["weight"] = 1},
                {["mapName"] = "duels_Desert-Shrine", ["weight"] = 1}
            },
            ["queueSize"] = {["min"] = 1, ["max"] = 2},
            ["placeId"] = 8560631822,
            ["killBounties"] = true,
            ["eventText"] = [[🥳 <font color="rgb(255,85,255)">LIMITED TIME MODE!</font> 🥳]],
            ["title"] = "Duels (2v2)",
            ["disabledFeatures"] = {["disableBedPlating"] = true},
            ["game"] = "bedwars",
            ["disableLeaderboardProgression"] = true,
            ["disabled"] = false,
            ["teams"] = {
                {["id"] = "1", ["displayName"] = "Blue", ["colorHex"] = 4830450, ["maxPlayers"] = 2},
                {["id"] = "2", ["displayName"] = "Orange", ["colorHex"] = 15896105, ["maxPlayers"] = 2}
            }
        },
        ["royale"] = {
            ["ignorePlayFabTeamMatching"] = true,
            ["maps"] = {},
            ["queueSize"] = {["min"] = 1, ["max"] = 4},
            ["placeId"] = 9903116309,
            ["eventText"] = [[🚧 <font color="rgb(85,255,255)">PUBLIC BETA!</font> 🚧]],
            ["title"] = "Battle Royale",
            ["disabled"] = true,
            ["disableLeaderboardProgression"] = true,
            ["game"] = "bedwars",
            ["disableInCustom"] = true,
            ["teams"] = {}
        },
        ["bedwars_lucky_block_to2"] = {
            ["glickoCategory"] = "LUCKY_BLOCK",
            ["maps"] = {
                {["mapName"] = "to2_Blossom", ["weight"] = 5},
                {["mapName"] = "to2_Seasonal", ["weight"] = 1},
                {["mapName"] = "to2_Darkholm", ["weight"] = 1},
                {["mapName"] = "to2_SandShrine", ["weight"] = 1},
                {["mapName"] = "to2_Aztec", ["weight"] = 1},
                {["mapName"] = "to2_Citadel", ["weight"] = 1},
                {["mapName"] = "to2_Cobblestone-Gardens", ["weight"] = 1},
                {["mapName"] = "to2_Fungi-Land", ["weight"] = 1},
                {["mapName"] = "to2_Swamp", ["weight"] = 1},
                {["mapName"] = "to2_Vineyard", ["weight"] = 1},
                {["mapName"] = "to2_Nordic", ["weight"] = 1},
                {["mapName"] = "to2_Autumn", ["weight"] = 3}
            },
            ["queueSize"] = {["min"] = 1, ["max"] = 2},
            ["placeId"] = 6872274481,
            ["title"] = "Lucky Block (Doubles)",
            ["killBounties"] = true,
            ["game"] = "bedwars",
            ["disableLeaderboardProgression"] = true,
            ["luckyBlock"] = true,
            ["teams"] = {
                {["id"] = "1", ["displayName"] = "Blue", ["colorHex"] = 4830450, ["maxPlayers"] = 2},
                {["id"] = "2", ["displayName"] = "Orange", ["colorHex"] = 15896105, ["maxPlayers"] = 2},
                {["id"] = "3", ["displayName"] = "Pink", ["colorHex"] = 16733695, ["maxPlayers"] = 2},
                {["id"] = "4", ["displayName"] = "Yellow", ["colorHex"] = 16777045, ["maxPlayers"] = 2},
                {["id"] = "5", ["displayName"] = "Brown", ["colorHex"] = 10117924, ["maxPlayers"] = 2},
                {["id"] = "6", ["displayName"] = "White", ["colorHex"] = 15990527, ["maxPlayers"] = 2},
                {["id"] = "7", ["displayName"] = "Cyan", ["colorHex"] = 5636095, ["maxPlayers"] = 2},
                {["id"] = "8", ["displayName"] = "Purple", ["colorHex"] = 11141290, ["maxPlayers"] = 2}
            }
        },
        ["bedwars_to2"] = {
            ["glickoCategory"] = "NORMALS",
            ["maps"] = {
                {["mapName"] = "to2_Blossom", ["weight"] = 5},
                {["mapName"] = "to2_Seasonal", ["weight"] = 1},
                {["mapName"] = "to2_Darkholm", ["weight"] = 1},
                {["mapName"] = "to2_SandShrine", ["weight"] = 1},
                {["mapName"] = "to2_Aztec", ["weight"] = 1},
                {["mapName"] = "to2_Citadel", ["weight"] = 1},
                {["mapName"] = "to2_Cobblestone-Gardens", ["weight"] = 1},
                {["mapName"] = "to2_Fungi-Land", ["weight"] = 1},
                {["mapName"] = "to2_Swamp", ["weight"] = 1},
                {["mapName"] = "to2_Vineyard", ["weight"] = 1},
                {["mapName"] = "to2_Nordic", ["weight"] = 1},
                {["mapName"] = "to2_Autumn", ["weight"] = 3}
            },
            ["queueSize"] = {["min"] = 1, ["max"] = 2},
            ["placeId"] = 6872274481,
            ["enableBlockDecay"] = true,
            ["title"] = "BedWars (Doubles)",
            ["killBounties"] = true,
            ["disabledMessage"] = "DISABLED",
            ["game"] = "bedwars",
            ["disabled"] = false,
            ["teams"] = {
                {["id"] = "1", ["displayName"] = "Blue", ["colorHex"] = 4830450, ["maxPlayers"] = 2},
                {["id"] = "2", ["displayName"] = "Orange", ["colorHex"] = 15896105, ["maxPlayers"] = 2},
                {["id"] = "3", ["displayName"] = "Pink", ["colorHex"] = 16733695, ["maxPlayers"] = 2},
                {["id"] = "4", ["displayName"] = "Yellow", ["colorHex"] = 16777045, ["maxPlayers"] = 2},
                {["id"] = "5", ["displayName"] = "Brown", ["colorHex"] = 10117924, ["maxPlayers"] = 2},
                {["id"] = "6", ["displayName"] = "White", ["colorHex"] = 15990527, ["maxPlayers"] = 2},
                {["id"] = "7", ["displayName"] = "Cyan", ["colorHex"] = 5636095, ["maxPlayers"] = 2},
                {["id"] = "8", ["displayName"] = "Purple", ["colorHex"] = 11141290, ["maxPlayers"] = 2}
            }
        },
        ["murder_game_vc"] = {
            ["autoQueue"] = false,
            ["ignorePlayFabTeamMatching"] = true,
            ["disabled"] = true,
            ["disableDamageHighlight"] = true,
            ["disableScoreboardStats"] = true,
            ["placeId"] = 6872274481,
            ["ignoreBoundaryDamage"] = true,
            ["eventText"] = "🔊 VOICE CHAT ONLY 🔊",
            ["disableRecalling"] = true,
            ["enableFriendlyFire"] = true,
            ["hudWidgets"] = {},
            ["noKits"] = true,
            ["maps"] = {{["mapName"] = "nm_Castle-Grounds", ["weight"] = 1}},
            ["queueSize"] = {["min"] = 1, ["max"] = 12},
            ["disabledMatchEndScreens"] = {4},
            ["disableKillEffects"] = true,
            ["disableMatchStatsProgression"] = true,
            ["disableLeaderboardProgression"] = true,
            ["disableKillFeed"] = true,
            ["title"] = "Murder in Bedtown (Voice Chat)",
            ["teams"] = {
                {["id"] = "1", ["displayName"] = "Innocent", ["colorHex"] = 4830450, ["maxPlayers"] = 12},
                {["id"] = "2", ["displayName"] = "Murderer", ["colorHex"] = 14886723, ["maxPlayers"] = 0}
            },
            ["voiceChatOnly"] = true,
            ["game"] = "murderer-game",
            ["disableRelics"] = true,
            ["customLeaderStats"] = {}
        },
        ["skywars_royale"] = {
            ["autoQueue"] = false,
            ["matchStartTime"] = 60,
            ["disabled"] = true,
            ["placeId"] = 8444591321,
            ["eventText"] = [[🔥 <font color="rgb(85,255,85)">50 PLAYER ROYALE</font> 🔥]],
            ["disableRecalling"] = true,
            ["hudWidgets"] = {"players_alive"},
            ["noKits"] = true,
            ["maps"] = {{["mapName"] = "swroyale_Skyfield", ["weight"] = 1}},
            ["queueSize"] = {["min"] = 1, ["max"] = 3},
            ["ignorePlayFabTeamMatching"] = true,
            ["title"] = "SkyWars Royale (Trios)",
            ["glickoCategory"] = "SKYWARS",
            ["disableRelics"] = true,
            ["game"] = "skywars",
            ["killBounties"] = false,
            ["teams"] = {
                {["id"] = "1", ["displayName"] = "Blue Alpha", ["colorHex"] = 4830450, ["maxPlayers"] = 3},
                {["id"] = "2", ["displayName"] = "Red Alpha", ["colorHex"] = 14886723, ["maxPlayers"] = 3},
                {["id"] = "3", ["displayName"] = "Green Alpha", ["colorHex"] = 2536780, ["maxPlayers"] = 3},
                {["id"] = "4", ["displayName"] = "Yellow Alpha", ["colorHex"] = 16777045, ["maxPlayers"] = 3},
                {["id"] = "5", ["displayName"] = "Orange Alpha", ["colorHex"] = 15896105, ["maxPlayers"] = 3},
                {["id"] = "6", ["displayName"] = "Pink Alpha", ["colorHex"] = 16733695, ["maxPlayers"] = 3},
                {["id"] = "7", ["displayName"] = "Cyan Alpha", ["colorHex"] = 5636095, ["maxPlayers"] = 3},
                {["id"] = "8", ["displayName"] = "Purple Alpha", ["colorHex"] = 11141290, ["maxPlayers"] = 3},
                {["id"] = "9", ["displayName"] = "Blue Beta", ["colorHex"] = 4830460, ["maxPlayers"] = 3},
                {["id"] = "10", ["displayName"] = "Red Beta", ["colorHex"] = 14886733, ["maxPlayers"] = 3},
                {["id"] = "11", ["displayName"] = "Green Beta", ["colorHex"] = 2536790, ["maxPlayers"] = 3},
                {["id"] = "12", ["displayName"] = "Yellow Beta", ["colorHex"] = 16777055, ["maxPlayers"] = 3},
                {["id"] = "13", ["displayName"] = "Orange Beta", ["colorHex"] = 15896115, ["maxPlayers"] = 3},
                {["id"] = "14", ["displayName"] = "Pink Beta", ["colorHex"] = 16733705, ["maxPlayers"] = 3},
                {["id"] = "15", ["displayName"] = "Cyan Beta", ["colorHex"] = 5636105, ["maxPlayers"] = 3},
                {["id"] = "16", ["displayName"] = "Purple Beta", ["colorHex"] = 11141300, ["maxPlayers"] = 3},
                {["id"] = "17", ["displayName"] = "Blue Charlie", ["colorHex"] = 4830470, ["maxPlayers"] = 3},
                {["id"] = "18", ["displayName"] = "Red Charlie", ["colorHex"] = 14886743, ["maxPlayers"] = 3},
                {["id"] = "19", ["displayName"] = "Green Charlie", ["colorHex"] = 2536800, ["maxPlayers"] = 3},
                {["id"] = "20", ["displayName"] = "Yellow Charlie", ["colorHex"] = 16777065, ["maxPlayers"] = 3},
                {["id"] = "21", ["displayName"] = "Orange Charlie", ["colorHex"] = 15896125, ["maxPlayers"] = 3},
                {["id"] = "22", ["displayName"] = "Pink Charlie", ["colorHex"] = 16733715, ["maxPlayers"] = 3},
                {["id"] = "23", ["displayName"] = "Cyan Charlie", ["colorHex"] = 5636115, ["maxPlayers"] = 3},
                {["id"] = "24", ["displayName"] = "Purple Charlie", ["colorHex"] = 11141310, ["maxPlayers"] = 3}
            }
        },
        ["murder_game"] = {
            ["autoQueue"] = false,
            ["ignorePlayFabTeamMatching"] = true,
            ["disabled"] = true,
            ["disableDamageHighlight"] = true,
            ["disableScoreboardStats"] = true,
            ["placeId"] = 6872274481,
            ["ignoreBoundaryDamage"] = true,
            ["eventText"] = [[🔥 <font color="rgb(85,255,85)"><b>LIMITED TIME MODE!</b></font> 🔥]],
            ["disableRecalling"] = true,
            ["enableFriendlyFire"] = true,
            ["hudWidgets"] = {},
            ["noKits"] = true,
            ["maps"] = {{["mapName"] = "nm_Castle-Grounds", ["weight"] = 1}},
            ["queueSize"] = {["min"] = 1, ["max"] = 12},
            ["disabledMatchEndScreens"] = {4},
            ["disableKillEffects"] = true,
            ["disableMatchStatsProgression"] = true,
            ["disableLeaderboardProgression"] = true,
            ["title"] = "Murder in Bedtown",
            ["disableKillFeed"] = true,
            ["disableRelics"] = true,
            ["game"] = "murderer-game",
            ["teams"] = {
                {["id"] = "1", ["displayName"] = "Innocent", ["colorHex"] = 4830450, ["maxPlayers"] = 12},
                {["id"] = "2", ["displayName"] = "Murderer", ["colorHex"] = 14886723, ["maxPlayers"] = 0}
            },
            ["customLeaderStats"] = {}
        },
        ["bedwars_to1"] = {
            ["glickoCategory"] = "NORMALS",
            ["disableInCustom"] = true,
            ["maps"] = {
                {["mapName"] = "to2_Blossom", ["weight"] = 5},
                {["mapName"] = "to2_Seasonal", ["weight"] = 1},
                {["mapName"] = "to2_Darkholm", ["weight"] = 1},
                {["mapName"] = "to2_SandShrine", ["weight"] = 1},
                {["mapName"] = "to2_Aztec", ["weight"] = 1},
                {["mapName"] = "to2_Citadel", ["weight"] = 1},
                {["mapName"] = "to2_Cobblestone-Gardens", ["weight"] = 1},
                {["mapName"] = "to2_Fungi-Land", ["weight"] = 1},
                {["mapName"] = "to2_Swamp", ["weight"] = 1},
                {["mapName"] = "to2_Vineyard", ["weight"] = 1},
                {["mapName"] = "to2_Nordic", ["weight"] = 1},
                {["mapName"] = "to2_Autumn", ["weight"] = 3}
            },
            ["queueSize"] = {["min"] = 1, ["max"] = 1},
            ["placeId"] = 8560631822,
            ["enableBlockDecay"] = true,
            ["title"] = "BedWars (Solo)",
            ["game"] = "bedwars",
            ["killBounties"] = true,
            ["teams"] = {
                {["id"] = "1", ["displayName"] = "Blue", ["colorHex"] = 4830450, ["maxPlayers"] = 1},
                {["id"] = "2", ["displayName"] = "Orange", ["colorHex"] = 15896105, ["maxPlayers"] = 1},
                {["id"] = "3", ["displayName"] = "Pink", ["colorHex"] = 16733695, ["maxPlayers"] = 1},
                {["id"] = "4", ["displayName"] = "Yellow", ["colorHex"] = 16777045, ["maxPlayers"] = 1},
                {["id"] = "5", ["displayName"] = "Brown", ["colorHex"] = 10117924, ["maxPlayers"] = 1},
                {["id"] = "6", ["displayName"] = "White", ["colorHex"] = 15990527, ["maxPlayers"] = 1},
                {["id"] = "7", ["displayName"] = "Cyan", ["colorHex"] = 5636095, ["maxPlayers"] = 1},
                {["id"] = "8", ["displayName"] = "Purple", ["colorHex"] = 11141290, ["maxPlayers"] = 1}
            }
        },
        ["skywars_to4"] = {
            ["noKits"] = true,
            ["maps"] = {
                {["mapName"] = "sw4_Wasteland", ["weight"] = 1},
                {["mapName"] = "sw4_Volatile", ["weight"] = 1},
                {["mapName"] = "sw4_Tundra", ["weight"] = 1},
                {["mapName"] = "sw4_Glade", ["weight"] = 1},
                {["mapName"] = "sw4_Cistern", ["weight"] = 1},
                {["mapName"] = "sw4_BambooGarden", ["weight"] = 1}
            },
            ["queueSize"] = {["min"] = 1, ["max"] = 4},
            ["placeId"] = 6872274481,
            ["glickoCategory"] = "SKYWARS",
            ["disabled"] = true,
            ["eventText"] = [[⚔️ <font color="rgb(85,255,85)">FAST PACED!</font> ⚔️]],
            ["title"] = "SkyWars (Squads)",
            ["disableRecalling"] = true,
            ["disableRelics"] = true,
            ["game"] = "skywars",
            ["teams"] = {
                {["id"] = "1", ["displayName"] = "Blue", ["colorHex"] = 4830450, ["maxPlayers"] = 4},
                {["id"] = "2", ["displayName"] = "Brown", ["colorHex"] = 10117924, ["maxPlayers"] = 4},
                {["id"] = "3", ["displayName"] = "White", ["colorHex"] = 15990527, ["maxPlayers"] = 4},
                {["id"] = "4", ["displayName"] = "Yellow", ["colorHex"] = 16777045, ["maxPlayers"] = 4},
                {["id"] = "5", ["displayName"] = "Orange", ["colorHex"] = 15896105, ["maxPlayers"] = 4},
                {["id"] = "6", ["displayName"] = "Pink", ["colorHex"] = 16733695, ["maxPlayers"] = 4},
                {["id"] = "7", ["displayName"] = "Cyan", ["colorHex"] = 5636095, ["maxPlayers"] = 4},
                {["id"] = "8", ["displayName"] = "Purple", ["colorHex"] = 11141290, ["maxPlayers"] = 4}
            },
            ["hudWidgets"] = {"players_alive"}
        },
        ["bedwars_voice_chat"] = {
            ["maps"] = {
                {["mapName"] = "to4_Sandbox", ["weight"] = 1},
                {["mapName"] = "to4_Blossom", ["weight"] = 6},
                {["mapName"] = "to4_Voidlands", ["weight"] = 6},
                {["mapName"] = "to4_Airship", ["weight"] = 2},
                {["mapName"] = "to4_Cobblestone-Gardens", ["weight"] = 2},
                {["mapName"] = "to4_Craglands", ["weight"] = 2},
                {["mapName"] = "to4_Fungi-Land", ["weight"] = 2},
                {["mapName"] = "to4_Pond", ["weight"] = 2},
                {["mapName"] = "to4_Swamp", ["weight"] = 2},
                {["mapName"] = "to4_Treehouse", ["weight"] = 2},
                {["mapName"] = "to4_Seasonal", ["weight"] = 1},
                {["mapName"] = "to4_Darkholm", ["weight"] = 1},
                {["mapName"] = "to4_SandShrine", ["weight"] = 1},
                {["mapName"] = "to4_Aztec", ["weight"] = 1},
                {["mapName"] = "to4_Nordic", ["weight"] = 1}
            },
            ["queueSize"] = {["min"] = 1, ["max"] = 4},
            ["placeId"] = 6872274481,
            ["enableBlockDecay"] = true,
            ["eventText"] = "🔊 VOICE CHAT ONLY 🔊",
            ["title"] = "BedWars Voice Chat (Squads)",
            ["killBounties"] = true,
            ["voiceChatOnly"] = true,
            ["game"] = "bedwars",
            ["disableLeaderboardProgression"] = true,
            ["teams"] = {
                {["id"] = "1", ["displayName"] = "Blue", ["colorHex"] = 4830450, ["maxPlayers"] = 4},
                {["id"] = "2", ["displayName"] = "Orange", ["colorHex"] = 15896105, ["maxPlayers"] = 4},
                {["id"] = "3", ["displayName"] = "Pink", ["colorHex"] = 16733695, ["maxPlayers"] = 4},
                {["id"] = "4", ["displayName"] = "Yellow", ["colorHex"] = 16777045, ["maxPlayers"] = 4}
            }
        },
        ["bedwars_ranked_s5"] = {
            ["minWinReq"] = 100,
            ["disableInCustom"] = true,
            ["maps"] = {
                {["mapName"] = "to4_Sandbox", ["weight"] = 1},
                {["mapName"] = "to4_Blossom", ["weight"] = 6},
                {["mapName"] = "to4_Voidlands", ["weight"] = 6},
                {["mapName"] = "to4_Airship", ["weight"] = 2},
                {["mapName"] = "to4_Cobblestone-Gardens", ["weight"] = 2},
                {["mapName"] = "to4_Craglands", ["weight"] = 2},
                {["mapName"] = "to4_Fungi-Land", ["weight"] = 2},
                {["mapName"] = "to4_Pond", ["weight"] = 2},
                {["mapName"] = "to4_Swamp", ["weight"] = 2},
                {["mapName"] = "to4_Treehouse", ["weight"] = 2},
                {["mapName"] = "to4_Seasonal", ["weight"] = 1},
                {["mapName"] = "to4_Darkholm", ["weight"] = 1},
                {["mapName"] = "to4_SandShrine", ["weight"] = 1},
                {["mapName"] = "to4_Aztec", ["weight"] = 1},
                {["mapName"] = "to4_Nordic", ["weight"] = 1}
            },
            ["queueSize"] = {["min"] = 1, ["max"] = 4},
            ["partyGlickoFunction"] = "max",
            ["placeId"] = 6872274481,
            ["disabled"] = true,
            ["eventText"] = "SEASON 5",
            ["title"] = "Ranked (Squads)",
            ["disableRelics"] = true,
            ["rankCategory"] = "RANKED_S5",
            ["game"] = "bedwars",
            ["glickoCategory"] = "RANKED_S5",
            ["teams"] = {
                {["id"] = "1", ["displayName"] = "Blue", ["colorHex"] = 4830450, ["maxPlayers"] = 4},
                {["id"] = "2", ["displayName"] = "Red", ["colorHex"] = 14886723, ["maxPlayers"] = 4},
                {["id"] = "3", ["displayName"] = "Green", ["colorHex"] = 2536780, ["maxPlayers"] = 4},
                {["id"] = "4", ["displayName"] = "Yellow", ["colorHex"] = 16777045, ["maxPlayers"] = 4}
            }
        }
    },
    ["StudioQueueType"] = "bedwars_to4"
}
