data = {
    ["CoinJar"] = {
        ["BreakingRequirement"] = 5,
        ["Color"] = Color3.fromRGB(255, 220, 19),
        ["Duration"] = 600,
        ["AllowInZones"] = true,
        ["_id"] = "CoinJar",
        ["_script"] = "RandomEvent | CoinJar",
        ["AllowInInstances"] = false,
        ["Name"] = "Coin Jar",
        ["PlaytimeRequirement"] = 5,
        ["Chance"] = 42.5,
        ["AreaWhitelist"] = {["Main_Magma"] = true, ["Main"] = true, ["Main_Ice"] = true},
        ["AllowMultiple"] = true,
        ["Icon"] = "rbxassetid://15000811448"
    },
    ["GiantExclusiveEgg"] = {
        ["AllowInZones"] = true,
        ["Color"] = Color3.fromRGB(255, 220, 19),
        ["Duration"] = 600,
        ["PlaytimeRequirement"] = 5,
        ["Chance"] = 0,
        ["Icon"] = "rbxassetid://17014122346",
        ["MinimumZone"] = inf,
        ["BreakingRequirement"] = 5,
        ["_script"] = "RandomEvent | GiantExclusiveEgg",
        ["Name"] = "Giant Exclusive Egg",
        ["_id"] = "GiantExclusiveEgg",
        ["AreaWhitelist"] = {["Main_Magma"] = true, ["Main"] = true, ["Main_Ice"] = true},
        ["AllowMultiple"] = false,
        ["AllowInInstances"] = false
    },
    ["Pinata"] = {
        ["AllowInZones"] = true,
        ["Color"] = Color3.fromRGB(255, 220, 19),
        ["Duration"] = 600,
        ["PlaytimeRequirement"] = 5,
        ["Chance"] = 5,
        ["Icon"] = "rbxassetid://15938616489",
        ["MinimumZone"] = 70,
        ["BreakingRequirement"] = 5,
        ["_script"] = "RandomEvent | Pinata",
        ["Name"] = "Piñata",
        ["_id"] = "Pinata",
        ["AreaWhitelist"] = {["Main_Magma"] = true, ["Main"] = true, ["Main_Ice"] = true},
        ["AllowMultiple"] = true,
        ["AllowInInstances"] = false
    },
    ["ItemJar"] = {
        ["BreakingRequirement"] = 5,
        ["Color"] = Color3.fromRGB(255, 220, 19),
        ["Duration"] = 600,
        ["AllowInZones"] = true,
        ["_id"] = "ItemJar",
        ["_script"] = "RandomEvent | ItemJar",
        ["AllowInInstances"] = false,
        ["Name"] = "Item Jar",
        ["PlaytimeRequirement"] = 5,
        ["Chance"] = 10,
        ["AreaWhitelist"] = {["Main_Magma"] = true, ["Main"] = true, ["Main_Ice"] = true},
        ["AllowMultiple"] = true,
        ["Icon"] = "rbxassetid://16717382310"
    },
    ["LuckyBlock"] = {
        ["AllowInZones"] = true,
        ["Color"] = Color3.fromRGB(44, 255, 255),
        ["Duration"] = 120,
        ["PlaytimeRequirement"] = 5,
        ["Chance"] = 10,
        ["Icon"] = "rbxassetid://15938616838",
        ["MinimumZone"] = 55,
        ["BreakingRequirement"] = 5,
        ["_script"] = "RandomEvent | LuckyBlock",
        ["Name"] = "Lucky Block",
        ["_id"] = "LuckyBlock",
        ["AreaWhitelist"] = {["Main_Magma"] = true, ["Main"] = true, ["Main_Ice"] = true},
        ["AllowMultiple"] = true,
        ["AllowInInstances"] = false
    },
    ["Comet"] = {
        ["BreakingRequirement"] = 5,
        ["Color"] = Color3.fromRGB(44, 255, 255),
        ["Duration"] = 600,
        ["AllowInZones"] = true,
        ["_id"] = "Comet",
        ["_script"] = "RandomEvent | Comet",
        ["AllowInInstances"] = false,
        ["Name"] = "Comet",
        ["PlaytimeRequirement"] = 5,
        ["Chance"] = 42.5,
        ["AreaWhitelist"] = {["Main_Magma"] = true, ["Main"] = true, ["Main_Ice"] = true},
        ["AllowMultiple"] = true,
        ["Icon"] = "rbxassetid://15000811043"
    }
}
