data = {
    ["Peryton"] = {
        ["TamingNeedleSpeed"] = 275,
        ["RequiredLasso"] = {"CloudLasso", "MysticCloudLasso"},
        ["MoveSpeed"] = 27,
        ["Name"] = "Peryton",
        ["AggroDistance"] = 40,
        ["TamingSmallRegionChance"] = 0.5,
        ["TamingNeedleReverseChance"] = 0.65,
        ["MaxDistanceFromSpawn"] = 100,
        ["PreferredFoodRarity"] = "Epic",
        ["TamingMaxPoints"] = 18,
        ["Flier"] = true,
        ["TamingNeedleLastHeartSpeed"] = 1.5
    },
    ["Unicorn"] = {
        ["TamingNeedleSpeed"] = 250,
        ["RequiredLasso"] = {"WeakMagicLasso", "MagicalLasso"},
        ["MoveSpeed"] = 27,
        ["AggroDistance"] = 35,
        ["TamingSmallRegionChance"] = 0.4,
        ["TamingNeedleReverseChance"] = 0.35,
        ["PreferredFoodRarity"] = "Rare",
        ["TamingMaxPoints"] = 14,
        ["Name"] = "Unicorn",
        ["TamingNeedleLastHeartSpeed"] = 1.5
    },
    ["Fae"] = {
        ["TamingNeedleSpeed"] = 275,
        ["RequiredLasso"] = {"WebLasso", "MysticWebLasso"},
        ["TamingFailDistance"] = 70,
        ["MoveSpeed"] = 65,
        ["CalmTimer"] = 3,
        ["Name"] = "Fae",
        ["AggroDistance"] = 100,
        ["TamingSmallRegionChance"] = 0.75,
        ["TamingNeedleReverseChance"] = 1,
        ["AttackSpeed"] = 90,
        ["PreferredFoodRarity"] = "Legendary",
        ["TamingMaxPoints"] = 26,
        ["NoiseMultiplier"] = 3,
        ["TamingNeedleLastHeartSpeed"] = 1.5
    },
    ["Plush"] = {
        ["AggroDistance"] = 32,
        ["TamingNeedleReverseChance"] = 0,
        ["MoveSpeed"] = 20,
        ["Name"] = "Plush",
        ["TamingNeedleLastHeartSpeed"] = 1.35,
        ["PreferredFoodRarity"] = "Common"
    },
    ["Gargoyle"] = {
        ["TamingNeedleSpeed"] = 275,
        ["RequiredLasso"] = {"StoneLasso", "OvergrownLasso"},
        ["MoveSpeed"] = 27,
        ["AggroDistance"] = 40,
        ["TamingSmallRegionChance"] = 0.5,
        ["TamingNeedleReverseChance"] = 0.65,
        ["PreferredFoodRarity"] = "Epic",
        ["TamingMaxPoints"] = 18,
        ["Name"] = "Gargoyle",
        ["TamingNeedleLastHeartSpeed"] = 1.5
    },
    ["Bisorse"] = {
        ["TamingNeedleSpeed"] = 230,
        ["RequiredLasso"] = {"RopeLasso", "WesternLasso"},
        ["MoveSpeed"] = 30,
        ["AggroDistance"] = 65,
        ["TamingSmallRegionChance"] = 0.35,
        ["TamingNeedleReverseChance"] = 1,
        ["Name"] = "Bisorse",
        ["Ragdolls"] = true,
        ["TamingMaxPoints"] = 12,
        ["PreferredFoodRarity"] = "Uncommon",
        ["TamingNeedleLastHeartSpeed"] = 1.5
    },
    ["Flora"] = {
        ["AggroDistance"] = 32,
        ["TamingNeedleReverseChance"] = 0,
        ["MoveSpeed"] = 20,
        ["Name"] = "Flora",
        ["TamingNeedleLastHeartSpeed"] = 1.35,
        ["PreferredFoodRarity"] = "Common"
    },
    ["Horse_Boss"] = {
        ["AggroDistance"] = 100,
        ["Charges"] = true,
        ["Name"] = "Horse_Boss",
        ["Ragdolls"] = true,
        ["TamingMaxPoints"] = 2,
        ["Attacks"] = {"Slam", "Meteor", "Jump", "Fireball"},
        ["MoveSpeed"] = 45
    },
    ["Fairy"] = {
        ["AggroDistance"] = 65,
        ["RequiredLasso"] = {"FairyNet", "MagicFairyNet"},
        ["Name"] = "Fairy",
        ["MaxDistanceFromSpawn"] = 100,
        ["MoveSpeed"] = 30,
        ["TamingMaxPoints"] = 20,
        ["CalmTimer"] = 1,
        ["Flier"] = true
    },
    ["Kirin"] = {["MoveSpeed"] = 26, ["RequiredLasso"] = {}, ["Name"] = "Kirin", ["AggroDistance"] = 32},
    ["Equus"] = {
        ["TamingNeedleSpeed"] = 200,
        ["MoveSpeed"] = 26,
        ["TamingNeedleLastHeartSpeed"] = 1.5,
        ["TamingSmallRegionChance"] = 0.35,
        ["TamingNeedleReverseChance"] = 1,
        ["PreferredFoodRarity"] = "Uncommon",
        ["TamingMaxPoints"] = 10,
        ["Name"] = "Equus",
        ["AggroDistance"] = 50
    },
    ["Caprine"] = {
        ["TamingNeedleSpeed"] = 240,
        ["Charges"] = true,
        ["MoveSpeed"] = 25,
        ["AggroDistance"] = 40,
        ["Name"] = "Caprine",
        ["TamingNeedleReverseChance"] = 0,
        ["RequiredLasso"] = {"BrightLasso", "VibrantLasso"},
        ["Ragdolls"] = true,
        ["TamingMaxPoints"] = 12,
        ["TamingNeedleLastHeartSpeed"] = 1.35,
        ["PreferredFoodRarity"] = "Rare"
    },
    ["Kelpie"] = {
        ["TamingNeedleSpeed"] = 200,
        ["RequiredLasso"] = {"KelpLasso"},
        ["MoveSpeed"] = 40,
        ["CalmTimer"] = 1.5,
        ["AggroDistance"] = 50,
        ["TamingSmallRegionChance"] = 0.75,
        ["TamingNeedleReverseChance"] = 0.75,
        ["Name"] = "Kelpie",
        ["Ragdolls"] = true,
        ["TamingMaxPoints"] = 20,
        ["PreferredFoodRarity"] = "Epic",
        ["TamingNeedleLastHeartSpeed"] = 1.5
    },
    ["Horse"] = {
        ["AggroDistance"] = 32,
        ["TamingNeedleReverseChance"] = 0,
        ["MoveSpeed"] = 20,
        ["Name"] = "Horse",
        ["TamingNeedleLastHeartSpeed"] = 1.35,
        ["PreferredFoodRarity"] = "Common"
    },
    ["Pony"] = {
        ["TamingNeedleSpeed"] = 190,
        ["MoveSpeed"] = 42,
        ["TamingNeedleLastHeartSpeed"] = 1.5,
        ["TamingSmallRegionChance"] = 0.25,
        ["TamingNeedleReverseChance"] = 1,
        ["PreferredFoodRarity"] = "Uncommon",
        ["TamingMaxPoints"] = 8,
        ["Name"] = "Pony",
        ["AggroDistance"] = 40
    },
    ["Ghoulsteed"] = {
        ["TamingNeedleSpeed"] = 200,
        ["Charges"] = true,
        ["TamingFailDistance"] = 70,
        ["MoveSpeed"] = 40,
        ["CalmTimer"] = 3,
        ["AggroDistance"] = 50,
        ["TamingSmallRegionChance"] = 0.75,
        ["Name"] = "Ghoulsteed",
        ["RequiredLasso"] = {"GhostLasso", "UndeadLasso"},
        ["Ragdolls"] = true,
        ["TamingMaxPoints"] = 30,
        ["NoiseMultiplier"] = 2,
        ["PreferredFoodRarity"] = "Legendary"
    }
}
