data = {
    ["DAILY_REWARD_PLAY_TIME_REQUIRED"] = 600,
    ["HOLIDAY_RUSH_LIMIT"] = 5000,
    ["IS_TESTING_SERVER"] = false,
    ["MODERATOR_GROUP_RANK"] = 245,
    ["IS_RESERVED_SERVER"] = false,
    ["STATS_INFO"] = {
        {"Health", Color3.fromRGB(100, 255, 50)},
        {"Strength", Color3.fromRGB(255, 50, 50)},
        {"Magic", Color3.fromRGB(149, 0, 255)},
        {"Ranged", Color3.fromRGB(0, 190, 255)}
    },
    ["RESET_HOLIDAY_CURRENCY_COUNTER"] = 35,
    ["PRO_LOBBY_PLACE_ID"] = 7681237385,
    ["HOLIDAY_CURRENCY_PER_QUEST"] = 50,
    ["HOLIDAY_CURRENCY_IMAGE_PLURAL"] = "rbxassetid://12860733335",
    ["MAIN_LOBBY_PLACE_ID"] = 2960777560,
    ["HOLIDAY_CURRENCY_PER_MONSTER"] = 1,
    ["GROUP_ID"] = 3461453,
    ["LOBBY_PLACE_ID"] = 2960777560,
    ["GAMEPASS_VIP_GOLD_BOOST"] = 0.5,
    ["ITEM_EFFECT_CHANCE"] = 0.05,
    ["HOLIDAY_RAIN_AMOUNT"] = 75,
    ["IS_VIP_SERVER"] = false,
    ["MAIN_DUNGEON_PLACE_ID"] = 2978518061,
    ["DEVICE"] = "Mobile",
    ["HOLIDAY_CURRENCY_COLOR"] = Color3.fromRGB(130, 255, 47),
    ["BASE_JUMP_POWER"] = 40,
    ["IS_RUNNING"] = true,
    ["GAMEPASS_LUCK_BOOST"] = 1,
    ["TESTING_LOBBY_PLACE_ID"] = 6433052952,
    ["LOW_GRAPHICS_MODE"] = true,
    ["POTION_REGEN_PER_SECOND"] = 0.01,
    ["POTION_SUPER_LUCK_BOOST"] = 2,
    ["PENTAGON_IMAGES"] = {
        "rbxassetid://12898359607",
        "rbxassetid://12898359774",
        "rbxassetid://12898359964",
        "rbxassetid://12898360128"
    },
    ["POTION_POWER_ATTACK_SPEED_BOOST"] = 0.5,
    ["DUAL_WIELD_BOWS_ACTIVE"] = true,
    ["TRADE_LOG_SIZE"] = 20,
    ["DEFAULT_ALERT_DISTANCE"] = 40,
    ["PRIVATE_SERVER_OWNER_ID"] = false,
    ["HOLIDAY_DUNGEON_NAME"] = "Flower Field",
    ["IS_SERVER"] = false,
    ["GAMEPASS_HOLIDAY_BOOST"] = 1,
    ["HOLIDAY_CURRENCY_NAME_PLURAL"] = "Eggs",
    ["POTION_GOLD_BOOST"] = 1,
    ["GAMEPASS_NINJA_JUMP_AMOUNT"] = 1,
    ["BASE_WALK_SPEED"] = 16,
    ["IS_CLIENT"] = true,
    ["POTION_WARRIOR_DAMAGE_BOOST"] = 0.25,
    ["PRIVATE_SERVER_ID"] = false,
    ["SPECIAL_QUESTS_RESET_COUNTER"] = 18,
    ["GAMEPASS_VIP_LUCK_BOOST"] = 0.5,
    ["TWITTER_LUCK_BOOST"] = 0.25,
    ["POTION_DAMAGE_BOOST"] = 0.5,
    ["GAMEPASS_GOLD_BOOST"] = 1,
    ["IS_HOLIDAY"] = true,
    ["DUAL_WIELD_BOWS_ANGLE"] = 0.4363323129985824,
    ["IS_PRIVATE_SERVER"] = false,
    ["DEVELOPER_GROUP_RANK"] = 254,
    ["POTION_SUPER_HEALTH_BOOST"] = 1,
    ["POTION_JUMP_AMOUNT"] = 1,
    ["POTION_SHARPNESS_BOOST"] = 0.25,
    ["POTION_ARCHER_DAMAGE_BOOST"] = 0.25,
    ["DEBUG_WHITELIST"] = {["20349956"] = true, ["15941965"] = true},
    ["POTION_WIZARD_DAMAGE_BOOST"] = 0.25,
    ["GAMEPASS_VIP_XP_BOOST"] = 0.5,
    ["ALLOWED_EQUIP_INPUTS"] = {
        ["ItemsEquipped"] = {["RightHand"] = true, ["LeftHand"] = true, ["Helmet1"] = true},
        ["CosmeticsEquipped"] = {
            ["LeftHand"] = true,
            ["Helmet3"] = true,
            ["RightHand"] = true,
            ["Helmet1"] = true,
            ["Helmet2"] = true
        }
    },
    ["POTION_ABILITY_BOOST"] = 1,
    ["GET_TIPS"] = "function: 0xa20afdfe36ac44e8",
    ["POTION_CRIT_DAMAGE_BOOST"] = 1,
    ["POTION_SPEED_BOOST"] = 0.5,
    ["POTION_UNIQUE_CHANCE"] = 0.05,
    ["PLACE_ID"] = 2960777560,
    ["PENTAGON_IMAGES_FILLED"] = {
        "rbxassetid://12898401117",
        "rbxassetid://12898401249",
        "rbxassetid://12898401520",
        "rbxassetid://12898401744"
    },
    ["EQUIPMENT"] = {["Helmet"] = true, ["Weapon"] = true},
    ["HOLIDAY_CURRENCY_IMAGE_OUTLINE"] = "rbxassetid://12860733488",
    ["GAMEPASS_NINJA_SPRINT_BOOST"] = 0.5,
    ["GAMEPASS_XP_BOOST"] = 1,
    ["POTION_HEALTH_BOOST"] = 0.5,
    ["HOLIDAY_QUEST_REWARDS"] = {"Graceful Bow", "Graceful Rapier", "Graceful Staff"},
    ["TESTING_PRO_LOBBY_PLACE_ID"] = 7673694903,
    ["VALID_DAMAGE_TYPES"] = {["Ranged"] = true, ["Strength"] = true, ["Magic"] = true},
    ["HAS_DEBUG_ACCESS"] = "function: 0x23b02db74e7ea868",
    ["IS_LOBBY_SERVER"] = true,
    ["POTION_XP_BOOST"] = 1,
    ["HEADSHOT_IMAGE_ENDPOINT"] = "https://www.roblox.com/headshot-thumbnail/image?userId=%s&width=420&height=420&format=png",
    ["TESTING_DUNGEON_PLACE_ID"] = 6433087127,
    ["HOLIDAY_CURRENCY_COLOR_DARK"] = Color3.fromRGB(65, 127, 23),
    ["HOLIDAY_CURRENCY_PER_PRIZE_BOX"] = 2,
    ["HOLIDAY_RUSH_BOOST"] = 9,
    ["HOLIDAY_CURRENCY_PURCHASE_IMAGES"] = {
        "rbxassetid://12860749877",
        "rbxassetid://12860749797",
        "rbxassetid://12860749725",
        "rbxassetid://12860749551",
        "rbxassetid://12860750082",
        "rbxassetid://12860749984"
    },
    ["HOLIDAY_RAIN_VALUE"] = 100,
    ["HOLIDAY_CURRENCY_IMAGE_GREY"] = "rbxassetid://12860737270",
    ["IS_MAIN_SERVER"] = true,
    ["SPECIAL_QUESTS_HOLIDAY_CURRENCY_REWARDS"] = {["1"] = 100, ["4"] = 400, ["3"] = 300, ["2"] = 200},
    ["HOLIDAY_DAILY_REWARD_BONUS_BOSS_CHANCE"] = 0.005,
    ["IS_DUNGEON_SERVER"] = false,
    ["EVIL_HUMANOID_NAME"] = "EvilHumanoid",
    ["HOLIDAY_NAME"] = "Spring",
    ["SPECIAL_QUESTS_ACTIVE"] = true,
    ["SECRET_MINIBOSS_NAME"] = "Shogun",
    ["MAIN_PRO_LOBBY_PLACE_ID"] = 7681237385,
    ["HOLIDAY_CURRENCY_NAME"] = "Egg",
    ["GAME_VERSION"] = 133,
    ["POTION_SUPER_DAMAGE_BOOST"] = 1,
    ["SPECIAL_QUESTS_REWARD"] = "Pond Wings",
    ["JOB_ID"] = "aec90b27-dcc3-42af-b58e-6f9fb50cee4d",
    ["SPECIAL_QUESTS_NAMES"] = {"Monster Kills", "Miniboss Kills", "Boss Kills", "Treasure Chests", "Complete Dungeon"},
    ["GAMEPASS_VIP_ITEM_DROP_CHANCE"] = 0.1,
    ["LEVEL_REQUIREMENTS"] = {
        ["AFK_MODE"] = 10,
        ["TRADING_HUB"] = 15,
        ["MISC_LOBBY_BUTTONS"] = {["Gifting"] = 15, ["Promos"] = 10, ["Codes"] = 5},
        ["TRADING"] = 15,
        ["BACKPACK_BUTTONS"] = {["Collection"] = 5, ["Statistics"] = 10, ["Loadouts"] = 15, ["Customize"] = 20},
        ["BANK"] = 15
    },
    ["IS_STUDIO"] = false,
    ["POTION_LUCK_BOOST"] = 1,
    ["HAS_MODERATOR_ACCESS"] = "function: 0x73e0ebb86159b478",
    ["POTION_SUPER_GOLD_BOOST"] = 2,
    ["HOLIDAY_CURRENCY_IMAGE"] = "rbxassetid://12860733552",
    ["IS_PRO_LOBBY_SERVER"] = false,
    ["DUNGEON_PLACE_ID"] = 2978518061,
    ["POTION_SUPER_XP_BOOST"] = 2
}
