data = {
    ["HasAnyRecipeUnlocked"] = "function: 0x4fa81340752ac2a8",
    ["IsUnlocked"] = "function: 0x06f934343ccff188",
    ["CheckForRecipe"] = "function: 0xe85aaf0a48f1fe88",
    ["RecipeWorks"] = "function: 0x884bc8637e0e0618",
    ["Recipes"] = {
        {
            ["Unlocked"] = true,
            ["Ingredients"] = {"Mysteggal Bow", "Garden Bow", "Dreggon's Bow", "Leafy Bow", "Skybow", "Honeycomb Bow"},
            ["Name"] = "Twistwood Bow",
            ["Results"] = {"Twistwood Bow"}
        },
        {
            ["Unlocked"] = true,
            ["Ingredients"] = {
                "Mantis Claw",
                "Predator",
                "Fantasy Hammer",
                "Honey Popsicle",
                "Ultraviolet",
                "Nature Claymore",
                "Floral Lyre",
                "Vine Scythe",
                "Skytana",
                "Eggscalibur",
                "Woodland Saw",
                "Shell Dagger",
                "Reggal Axe",
                "Grass Knife",
                "Leafy Axe"
            },
            ["Name"] = "Twistwood Scythe",
            ["Results"] = {"Twistwood Scythe"}
        },
        {
            ["Unlocked"] = true,
            ["Ingredients"] = {
                "Lotus Parasol",
                "Dreggon's Staff",
                "Lotus Circle",
                "Bloom",
                "Etheggrial",
                "Firefly Summoner",
                "Metamorphosis",
                "Daisy Wand",
                "Leafy Skateboard",
                "Reggal Staff"
            },
            ["Name"] = "Twistwood Scepter",
            ["Results"] = {"Twistwood Scepter"}
        },
        {
            ["Unlocked"] = true,
            ["Ingredients"] = {"Red Egg", "Orange Egg", "Yellow Egg", "Green Egg", "Blue Egg", "Purple Egg"},
            ["Name"] = "Egg Jump",
            ["Results"] = {"Egg Jump"}
        },
        {
            ["Ingredients"] = {"Red Rage", "Orange Rage", "Yellow Rage", "Green Rage", "Blue Rage", "Purple Rage"},
            ["Name"] = "Rainbow Rage",
            ["Results"] = {"Rainbow Rage"}
        },
        {
            ["Ingredients"] = {
                "Lava Blade",
                "Grass Blade",
                "Thunder Blade",
                "Crystal Blade",
                "Ice Blade",
                "Shadow Blade"
            },
            ["Name"] = "Elemental Blade",
            ["Results"] = {"Elemental Blade"}
        },
        {
            ["Ingredients"] = {"Ban Hammer", "Demon Slayer", "Inferno"},
            ["Name"] = "Devastator",
            ["Results"] = {"Devastator"}
        },
        {
            ["Ingredients"] = {"Candy Katana", "Samurai Blade", "Demon Slayer"},
            ["Name"] = "Torment",
            ["Results"] = {"Torment"}
        },
        {["Ingredients"] = {"Firebrand", "Yellow Katana", "Inferno"}, ["Name"] = "Demon", ["Results"] = {"Demon"}},
        {["Ingredients"] = {"Demon", "Torment", "Death Hammer"}, ["Name"] = "Drake", ["Results"] = {"Drake"}},
        {["Ingredients"] = {"Darkheart", "Katana", "Ban Hammer"}, ["Name"] = "Void", ["Results"] = {"Void"}},
        {
            ["Ingredients"] = {"Demon", "Venomshank", "Venomshank", "Poison Reaper", "Gamma", "Cactus Blade"},
            ["Name"] = "Corrosive",
            ["Results"] = {"Corrosive"}
        },
        {
            ["Ingredients"] = {"Tempest", "Saber", "Illumina", "Crystal Edge", "Thunderbolt", "Water Blade"},
            ["Name"] = "Blizzard",
            ["Results"] = {"Blizzard"}
        },
        {
            ["Ingredients"] = {"Galaxy Saber", "Eternal", "Bloxy", "Ivory"},
            ["Name"] = "Arcane Dragon Staff",
            ["Results"] = {"Arcane Dragon Staff"}
        },
        {
            ["Ingredients"] = {"Galactic Chainsword", "Immortal", "Red Katana", "Cosmic Egg Caster"},
            ["Name"] = "Tectonic",
            ["Results"] = {"Tectonic"}
        },
        {
            ["Ingredients"] = {
                "Red Katana",
                "Orange Katana",
                "Yellow Katana",
                "Green Katana",
                "Blue Katana",
                "Purple Katana"
            },
            ["Name"] = "Epic Katana",
            ["Results"] = {"Epic Katana"}
        },
        {
            ["Ingredients"] = {"Ban Hammer", "Death Hammer", "Royal Hammer"},
            ["Name"] = "King Hammer",
            ["Results"] = {"King Hammer"}
        },
        {
            ["Ingredients"] = {"Firebrand", "Darkheart", "Illumina"},
            ["Name"] = "Shadow King",
            ["Results"] = {"Shadow King"}
        },
        {
            ["Ingredients"] = {"Galaxy Saber", "Purple Katana", "Darkheart"},
            ["Name"] = "Poison Fang",
            ["Results"] = {"Poison Fang"}
        },
        {
            ["Ingredients"] = {
                "Dark Saber",
                "Energy Saber",
                "Crimson Saber",
                "Bubblegum Saber",
                "Galaxy Saber",
                "Saber"
            },
            ["Name"] = "Epic Saber",
            ["Results"] = {"Epic Saber"}
        },
        {
            ["Ingredients"] = {
                "Santa's Saber",
                "Diamond Bloxy",
                "Elf Caster",
                "Ice Dagger",
                "Candy Cane Blade",
                "Elf Staff"
            },
            ["Name"] = "Krampus",
            ["Results"] = {"Krampus"}
        },
        {
            ["Ingredients"] = {"Empyreus", "Frigidus", "Aureus", "Smaragdus", "Tenebris", "Praefectus"},
            ["Name"] = "Epic Dominus",
            ["Results"] = {"Epic Dominus"}
        },
        {
            ["Ingredients"] = {"Lady", "Duke", "Earl", "Baron", "Viscount", "Viscountess"},
            ["Name"] = "Epic Federation",
            ["Results"] = {"Epic Federation"}
        },
        {
            ["Ingredients"] = {"Doomfire", "Soul Blade", "Soul Reaver", "Soul Chakram", "Soul Shuriken", "Shock Blade"},
            ["Name"] = "Soulfire",
            ["Results"] = {"Soulfire"}
        },
        {
            ["Ingredients"] = {
                "Red Energy Blade",
                "Orange Energy Blade",
                "Yellow Energy Blade",
                "Green Energy Blade",
                "Blue Energy Blade",
                "Purple Energy Blade"
            },
            ["Name"] = "Omega Energy Blade",
            ["Results"] = {"Omega Energy Blade"}
        },
        {["Ingredients"] = {"Poison Head", "Toxic Head", "Venom Head"}, ["Name"] = "Bane", ["Results"] = {"Bane"}},
        {["Ingredients"] = {"Venenum", "Toxicus", "Morbus"}, ["Name"] = "Plaga", ["Results"] = {"Plaga"}},
        {
            ["Ingredients"] = {
                "Gunblade",
                "Smogpunk Gauntlet",
                "Smogpunk Sword",
                "Smogpunk Saw",
                "Gear Slammer",
                "Smogpunk Dagger",
                "Pipe Hammer",
                "Cog Axe",
                "Cog Slasher",
                "Spanner"
            },
            ["Name"] = "Smogpunk Scythe",
            ["Results"] = {"Smogpunk Scythe"}
        },
        {
            ["Ingredients"] = {"Tech Wings", "Hexilite", "Tech Vision", "Hex Mask", "Hex Visor"},
            ["Name"] = "Hex Wings",
            ["Results"] = {"Hex Wings"}
        },
        {
            ["Ingredients"] = {
                "Solar Pickaxe",
                "Lobster Striker",
                "Temple Blade",
                "Tidal",
                "Sea Anchor",
                "Clam Caster",
                "Squid Zapper",
                "Orbcean",
                "Brightboard",
                "Seabed Rapier",
                "Seabed Staff",
                "Ukulele",
                "Beach Balloon",
                "Colorful Umbrella",
                "Fire Torch",
                "Radio",
                "Giant Soda Can",
                "Ice Cream",
                "Ice Pop",
                "Luggage",
                "Soda Cup"
            },
            ["Name"] = "Shark Bow",
            ["Results"] = {"Shark Bow"}
        },
        {
            ["Ingredients"] = {
                "Colossus",
                "Fruit Slice Wings",
                "Underwater Ninja",
                "Underwater King",
                "Solar Prince",
                "Sand Castle Top Hat",
                "Axolotl Helmet",
                "Life Buoy Crown",
                "Sandy Squire",
                "Sandy Crown"
            },
            ["Name"] = "Shark Quiver",
            ["Results"] = {"Shark Quiver"}
        },
        {
            ["Ingredients"] = {
                "Turmoil",
                "Sinister Striker",
                "Gleyeve",
                "Grave Digger",
                "Bat Saber",
                "Bat Claw",
                "Ghostly Claw",
                "Night Cutlass"
            },
            ["Name"] = "Ghoul Claw",
            ["Results"] = {"Ghoul Claw"}
        },
        {
            ["Ingredients"] = {
                "Bat Saber",
                "Bat Saber",
                "Bat Saber",
                "Bat Saber",
                "Bat Saber",
                "Bat Saber",
                "Bat Saber",
                "Bat Saber",
                "Bat Saber"
            },
            ["Name"] = "The Bat Saber",
            ["Results"] = {"The Bat Saber"}
        }
    },
    ["Ingredients"] = {
        ["Shock Blade"] = true,
        ["Smogpunk Gauntlet"] = true,
        ["Shadow Blade"] = true,
        ["Lotus Circle"] = true,
        ["Red Rage"] = true,
        ["Samurai Blade"] = true,
        ["Fantasy Hammer"] = true,
        ["Soda Cup"] = true,
        ["Beach Balloon"] = true,
        ["Life Buoy Crown"] = true,
        ["Colorful Umbrella"] = true,
        ["Etheggrial"] = true,
        ["Grass Blade"] = true,
        ["Green Energy Blade"] = true,
        ["Toxic Head"] = true,
        ["Purple Rage"] = true,
        ["Orange Egg"] = true,
        ["Daisy Wand"] = true,
        ["Yellow Rage"] = true,
        ["Viscount"] = true,
        ["Poison Head"] = true,
        ["Purple Egg"] = true,
        ["Eternal"] = true,
        ["Leafy Axe"] = true,
        ["Demon"] = true,
        ["Poison Reaper"] = true,
        ["Water Blade"] = true,
        ["Elf Staff"] = true,
        ["Leafy Skateboard"] = true,
        ["Crystal Edge"] = true,
        ["Bat Claw"] = true,
        ["Grass Knife"] = true,
        ["Duke"] = true,
        ["Illumina"] = true,
        ["Saber"] = true,
        ["Eggscalibur"] = true,
        ["Royal Hammer"] = true,
        ["Purple Energy Blade"] = true,
        ["Soul Shuriken"] = true,
        ["Lobster Striker"] = true,
        ["Immortal"] = true,
        ["Radio"] = true,
        ["Doomfire"] = true,
        ["Vine Scythe"] = true,
        ["Firefly Summoner"] = true,
        ["Dreggon's Staff"] = true,
        ["Yellow Katana"] = true,
        ["Reggal Staff"] = true,
        ["Ice Blade"] = true,
        ["Aureus"] = true,
        ["Frigidus"] = true,
        ["Galactic Chainsword"] = true,
        ["Metamorphosis"] = true,
        ["Thunderbolt"] = true,
        ["Skytana"] = true,
        ["Smogpunk Dagger"] = true,
        ["Orange Energy Blade"] = true,
        ["Orbcean"] = true,
        ["Crystal Blade"] = true,
        ["Elf Caster"] = true,
        ["Green Egg"] = true,
        ["Blue Rage"] = true,
        ["Lava Blade"] = true,
        ["Temple Blade"] = true,
        ["Torment"] = true,
        ["Giant Soda Can"] = true,
        ["Fruit Slice Wings"] = true,
        ["Ivory"] = true,
        ["Empyreus"] = true,
        ["Shell Dagger"] = true,
        ["Red Katana"] = true,
        ["Venenum"] = true,
        ["Smaragdus"] = true,
        ["Energy Saber"] = true,
        ["Bloxy"] = true,
        ["Mysteggal Bow"] = true,
        ["Yellow Energy Blade"] = true,
        ["Nature Claymore"] = true,
        ["Honey Popsicle"] = true,
        ["Underwater Ninja"] = true,
        ["Night Cutlass"] = true,
        ["Baron"] = true,
        ["Sand Castle Top Hat"] = true,
        ["Turmoil"] = true,
        ["Tech Vision"] = true,
        ["Reggal Axe"] = true,
        ["Grave Digger"] = true,
        ["Venomshank"] = true,
        ["Gleyeve"] = true,
        ["Sinister Striker"] = true,
        ["Bat Saber"] = true,
        ["Sandy Crown"] = true,
        ["Sandy Squire"] = true,
        ["Axolotl Helmet"] = true,
        ["Lady"] = true,
        ["Solar Prince"] = true,
        ["Underwater King"] = true,
        ["Colossus"] = true,
        ["Orange Rage"] = true,
        ["Ice Pop"] = true,
        ["Blue Egg"] = true,
        ["Woodland Saw"] = true,
        ["Cog Axe"] = true,
        ["Katana"] = true,
        ["Gear Slammer"] = true,
        ["Firebrand"] = true,
        ["Ukulele"] = true,
        ["Tempest"] = true,
        ["Seabed Rapier"] = true,
        ["Brightboard"] = true,
        ["Squid Zapper"] = true,
        ["Clam Caster"] = true,
        ["Sea Anchor"] = true,
        ["Tidal"] = true,
        ["Hex Mask"] = true,
        ["Solar Pickaxe"] = true,
        ["Skybow"] = true,
        ["Hex Visor"] = true,
        ["Hexilite"] = true,
        ["Tech Wings"] = true,
        ["Diamond Bloxy"] = true,
        ["Ultraviolet"] = true,
        ["Candy Katana"] = true,
        ["Cog Slasher"] = true,
        ["Ice Cream"] = true,
        ["Pipe Hammer"] = true,
        ["Fire Torch"] = true,
        ["Dreggon's Bow"] = true,
        ["Smogpunk Saw"] = true,
        ["Soul Chakram"] = true,
        ["Leafy Bow"] = true,
        ["Gunblade"] = true,
        ["Honeycomb Bow"] = true,
        ["Purple Katana"] = true,
        ["Toxicus"] = true,
        ["Ban Hammer"] = true,
        ["Venom Head"] = true,
        ["Inferno"] = true,
        ["Santa's Saber"] = true,
        ["Blue Energy Blade"] = true,
        ["Predator"] = true,
        ["Mantis Claw"] = true,
        ["Bloom"] = true,
        ["Ice Dagger"] = true,
        ["Yellow Egg"] = true,
        ["Red Energy Blade"] = true,
        ["Cactus Blade"] = true,
        ["Smogpunk Sword"] = true,
        ["Lotus Parasol"] = true,
        ["Soul Blade"] = true,
        ["Thunder Blade"] = true,
        ["Garden Bow"] = true,
        ["Crimson Saber"] = true,
        ["Cosmic Egg Caster"] = true,
        ["Viscountess"] = true,
        ["Ghostly Claw"] = true,
        ["Spanner"] = true,
        ["Demon Slayer"] = true,
        ["Praefectus"] = true,
        ["Bubblegum Saber"] = true,
        ["Tenebris"] = true,
        ["Earl"] = true,
        ["Green Rage"] = true,
        ["Candy Cane Blade"] = true,
        ["Seabed Staff"] = true,
        ["Soul Reaver"] = true,
        ["Orange Katana"] = true,
        ["Red Egg"] = true,
        ["Morbus"] = true,
        ["Blue Katana"] = true,
        ["Green Katana"] = true,
        ["Galaxy Saber"] = true,
        ["Luggage"] = true,
        ["Floral Lyre"] = true,
        ["Death Hammer"] = true,
        ["Gamma"] = true,
        ["Darkheart"] = true,
        ["Dark Saber"] = true
    },
    ["Results"] = {
        "Twistwood Bow",
        "Twistwood Scythe",
        "Twistwood Scepter",
        "Egg Jump",
        "Rainbow Rage",
        "Elemental Blade",
        "Devastator",
        "Torment",
        "Demon",
        "Drake",
        "Void",
        "Corrosive",
        "Blizzard",
        "Arcane Dragon Staff",
        "Tectonic",
        "Epic Katana",
        "King Hammer",
        "Shadow King",
        "Poison Fang",
        "Epic Saber",
        "Krampus",
        "Epic Dominus",
        "Epic Federation",
        "Soulfire",
        "Omega Energy Blade",
        "Bane",
        "Plaga",
        "Smogpunk Scythe",
        "Hex Wings",
        "Shark Bow",
        "Shark Quiver",
        "Ghoul Claw",
        "The Bat Saber"
    }
}
