data = {
    ["Paid"] = {
        {["Class"] = "Camo", ["Amount"] = 1, ["Reward"] = "Ripple"},
        {["Class"] = "Secondary", ["Amount"] = 1, ["Reward"] = "DE50X"},
        {["Class"] = "Camo", ["Amount"] = 1, ["Reward"] = "Gem Palace"},
        {["Class"] = "Secondary", ["Amount"] = 1, ["Reward"] = "EVO"},
        {["Class"] = "Prize Wheel", ["Amount"] = 3, ["Reward"] = "Free Spin"},
        {["Class"] = "Primary", ["Amount"] = 1, ["Reward"] = "MX-K"},
        {["Class"] = "Camo", ["Amount"] = 1, ["Reward"] = "Splatter"},
        {["Class"] = "Primary", ["Amount"] = 1, ["Reward"] = "G37X"},
        {["Class"] = "Camo", ["Amount"] = 1, ["Reward"] = "Premium"},
        {["Class"] = "Secondary", ["Amount"] = 1, ["Reward"] = "Magnum"},
        {["Class"] = "Camo", ["Amount"] = 1, ["Reward"] = "Cats"},
        {["Class"] = "Primary", ["Amount"] = 1, ["Reward"] = "KSG12"},
        {["Class"] = "Camo", ["Amount"] = 1, ["Reward"] = "Black Ice"},
        {["Class"] = "Primary", ["Amount"] = 1, ["Reward"] = "MBAK"},
        {["Class"] = "Camo", ["Amount"] = 1, ["Reward"] = "Medium Rare"},
        {["Class"] = "Primary", ["Amount"] = 1, ["Reward"] = "HYPR 94"},
        {["Class"] = "Credits", ["Amount"] = 500000, ["Reward"] = "500k"},
        {["Class"] = "Primary", ["Amount"] = 1, ["Reward"] = "Ballista"},
        {["Class"] = "Camo", ["Amount"] = 1, ["Reward"] = "Cooked"},
        {["Class"] = "Primary", ["Amount"] = 1, ["Reward"] = "Mini 14"},
        {["Class"] = "Primary", ["Amount"] = 1, ["Reward"] = "MDXL"},
        {["Class"] = "Camo", ["Amount"] = 1, ["Reward"] = "Seastorm"},
        {["Class"] = "Primary", ["Amount"] = 1, ["Reward"] = "M249"},
        {["Class"] = "Camo", ["Amount"] = 1, ["Reward"] = "Nero"}
    },
    ["Free"] = {
        {["Class"] = "Secondary", ["Amount"] = 1, ["Reward"] = "Gepard"},
        {["Class"] = "Camo", ["Amount"] = 1, ["Reward"] = "Bullet Time"},
        {["Class"] = "Primary", ["Amount"] = 1, ["Reward"] = "G36C"},
        {["Class"] = "Camo", ["Amount"] = 1, ["Reward"] = "Pointed"},
        {["Class"] = "Primary", ["Amount"] = 1, ["Reward"] = "MPX"},
        {["Class"] = "Bonus", ["Amount"] = 1800, ["Reward"] = "2X Credits"},
        {["Class"] = "Prize Wheel", ["Amount"] = 3, ["Reward"] = "3 Spins"},
        {["Class"] = "Camo", ["Amount"] = 1, ["Reward"] = "Cookie"},
        {["Class"] = "Secondary", ["Amount"] = 1, ["Reward"] = "G18C"},
        {["Class"] = "Bonus", ["Amount"] = 1800, ["Reward"] = "Faster Leveling"},
        {["Class"] = "Camo", ["Amount"] = 1, ["Reward"] = "Wagyu"},
        {["Class"] = "Camo", ["Amount"] = 1, ["Reward"] = "Obsidian"},
        {["Class"] = "Primary", ["Amount"] = 1, ["Reward"] = "Bizon"},
        {["Class"] = "Prize Wheel", ["Amount"] = 3, ["Reward"] = "3 Spins"},
        {["Class"] = "Primary", ["Amount"] = 1, ["Reward"] = "AN94"},
        {["Class"] = "Camo", ["Amount"] = 1, ["Reward"] = "Hexclad"},
        {["Class"] = "Credits", ["Amount"] = 250000, ["Reward"] = "250k"},
        {["Class"] = "Camo", ["Amount"] = 1, ["Reward"] = "Ruby"},
        {["Class"] = "Primary", ["Amount"] = 1, ["Reward"] = "MDR38"},
        {["Class"] = "Camo", ["Amount"] = 1, ["Reward"] = "XRay"},
        {["Class"] = "Bonus", ["Amount"] = 1800, ["Reward"] = "3X Credits"},
        {["Class"] = "Credits", ["Amount"] = 1000000, ["Reward"] = "1 Million"},
        {["Class"] = "Camo", ["Amount"] = 1, ["Reward"] = "Bubbles"},
        {["Class"] = "Primary", ["Amount"] = 1, ["Reward"] = "Lynx"}
    }
}
