data = {
    ["Wood"] = {
        ["Description"] = "Craftable ingredient. Used to create base buildings.",
        ["Origin"] = "Lobby",
        ["SetOriginFromNode"] = true,
        ["Image"] = "rbxthumb://type=Asset&id=8829253876&w=150&h=150",
        ["Name"] = "Wood",
        ["Category"] = "Resources",
        ["ItemType"] = "Resources",
        ["Sell"] = 5,
        ["Rarity"] = {
            ["Index"] = 2,
            ["Drops"] = {["DropChance"] = 6, ["Amount"] = 2},
            ["Fishing"] = {
                ["WaitTime"] = 10,
                ["RequiredSuccesses"] = {["Min"] = 5, ["Max"] = 6},
                ["DropChance"] = 30,
                ["SpinSpeed"] = {["Min"] = 250, ["Max"] = 350}
            },
            ["TextStrokeColor"] = Color3.fromRGB(52, 127, 23),
            ["Alchemy"] = {["DropChance"] = 30, ["ElixirRecyleAmount"] = 50},
            ["Auction"] = {["MinAmount"] = 5000},
            ["Name"] = "Uncommon",
            ["BreedCost"] = {["MinAmount"] = 700},
            ["Bosses"] = {["Amount"] = 100},
            ["SpinnerWheel"] = {["DropChance"] = 20, ["Amount"] = 50},
            ["RecyleAccessory"] = true,
            ["TextColor"] = Color3.fromRGB(82, 199, 36)
        },
        ["Buy"] = 10
    },
    ["PeachSeed"] = {
        ["ToCraft"] = "Plant_Peach",
        ["Rarity"] = {
            ["Index"] = 2,
            ["Drops"] = {["DropChance"] = 6, ["Amount"] = 2},
            ["Fishing"] = {
                ["WaitTime"] = 10,
                ["RequiredSuccesses"] = {["Min"] = 5, ["Max"] = 6},
                ["DropChance"] = 30,
                ["SpinSpeed"] = {["Min"] = 250, ["Max"] = 350}
            },
            ["TextStrokeColor"] = Color3.fromRGB(52, 127, 23),
            ["Alchemy"] = {["DropChance"] = 30, ["ElixirRecyleAmount"] = 50},
            ["Auction"] = {["MinAmount"] = 5000},
            ["Name"] = "Uncommon",
            ["BreedCost"] = {["MinAmount"] = 700},
            ["Bosses"] = {["Amount"] = 100},
            ["SpinnerWheel"] = {["DropChance"] = 20, ["Amount"] = 50},
            ["RecyleAccessory"] = true,
            ["TextColor"] = Color3.fromRGB(82, 199, 36)
        },
        ["Origin"] = "Jungle",
        ["NotInGeneralStore"] = true,
        ["Image"] = "rbxthumb://type=Asset&id=8828077386&w=150&h=150",
        ["Name"] = "PeachSeed",
        ["Category"] = "Resources",
        ["ItemType"] = "Resources",
        ["Sell"] = 8,
        ["Description"] = "Craftable ingredient. Used to create base buildings.",
        ["Buy"] = 150
    },
    ["Bamboo"] = {
        ["Description"] = "Craftable ingredient. Used to create base buildings.",
        ["Origin"] = "Jungle",
        ["SetOriginFromNode"] = true,
        ["Image"] = "rbxthumb://type=Asset&id=8829248476&w=150&h=150",
        ["Name"] = "Bamboo",
        ["Category"] = "Resources",
        ["ItemType"] = "Resources",
        ["Sell"] = 1,
        ["Rarity"] = {
            ["Index"] = 1,
            ["Drops"] = {["DropChance"] = 12, ["Amount"] = 4},
            ["Fishing"] = {
                ["WaitTime"] = 10,
                ["RequiredSuccesses"] = {["Min"] = 4, ["Max"] = 5},
                ["DropChance"] = 55,
                ["SpinSpeed"] = {["Min"] = 200, ["Max"] = 300}
            },
            ["TextStrokeColor"] = Color3.fromRGB(89, 89, 89),
            ["Alchemy"] = {["DropChance"] = 30, ["ElixirRecyleAmount"] = 250},
            ["Auction"] = {["MinAmount"] = 1000},
            ["Name"] = "Common",
            ["BreedCost"] = {["MinAmount"] = 250},
            ["Bosses"] = {["Amount"] = 100},
            ["SpinnerWheel"] = {["DropChance"] = 50, ["Amount"] = 100},
            ["RecyleAccessory"] = true,
            ["TextColor"] = Color3.fromRGB(181, 181, 181)
        },
        ["Buy"] = 6
    },
    ["FertilizerPristine"] = {
        ["CantTrade"] = true,
        ["Description"] = "The best Fertilizer for your farm!",
        ["FertilityToAdd"] = 80,
        ["DisplayName"] = "PristineFertilizer",
        ["Image"] = "rbxthumb://type=Asset&id=135179147360403&w=150&h=150",
        ["Name"] = "FertilizerPristine",
        ["Category"] = "Resources",
        ["ItemType"] = "Resources",
        ["Rarity"] = {
            ["Index"] = 4,
            ["Fishing"] = {
                ["SpinSpeed"] = {["Min"] = 350, ["Max"] = 450},
                ["AnnounceReward"] = true,
                ["WaitTime"] = 10,
                ["RequiredSuccesses"] = {["Min"] = 7, ["Max"] = 8},
                ["DropChance"] = 5
            },
            ["Hatching"] = {["AnnounceReward"] = true},
            ["TextStrokeColor"] = Color3.fromRGB(106, 19, 149),
            ["Auction"] = {["MinAmount"] = 25000},
            ["AccessoryGamepassEffect"] = true,
            ["Name"] = "Epic",
            ["BreedCost"] = {["MinAmount"] = 25000},
            ["Bosses"] = {["Amount"] = 1, ["AnnounceReward"] = true},
            ["SpinnerWheel"] = {["Amount"] = 10, ["DropChance"] = 4, ["AnnounceReward"] = true},
            ["Alchemy"] = {["DropChance"] = 30, ["ElixirRecyleAmount"] = 10},
            ["TextColor"] = Color3.fromRGB(182, 34, 255)
        }
    },
    ["GhostEssence"] = {
        ["CantTrade"] = true,
        ["Description"] = "Craftable ingredient. Used to create base buildings.",
        ["ItemType"] = "Resources",
        ["NotSuitableForChina"] = true,
        ["Image"] = "rbxthumb://type=Asset&id=8829210651&w=150&h=150",
        ["Name"] = "GhostEssence",
        ["Category"] = "Resources",
        ["Rarity"] = {
            ["Index"] = 4,
            ["Fishing"] = {
                ["SpinSpeed"] = {["Min"] = 350, ["Max"] = 450},
                ["AnnounceReward"] = true,
                ["WaitTime"] = 10,
                ["RequiredSuccesses"] = {["Min"] = 7, ["Max"] = 8},
                ["DropChance"] = 5
            },
            ["Hatching"] = {["AnnounceReward"] = true},
            ["TextStrokeColor"] = Color3.fromRGB(106, 19, 149),
            ["Auction"] = {["MinAmount"] = 25000},
            ["AccessoryGamepassEffect"] = true,
            ["Name"] = "Epic",
            ["BreedCost"] = {["MinAmount"] = 25000},
            ["Bosses"] = {["Amount"] = 1, ["AnnounceReward"] = true},
            ["SpinnerWheel"] = {["Amount"] = 10, ["DropChance"] = 4, ["AnnounceReward"] = true},
            ["Alchemy"] = {["DropChance"] = 30, ["ElixirRecyleAmount"] = 10},
            ["TextColor"] = Color3.fromRGB(182, 34, 255)
        },
        ["Sell"] = 30,
        ["NotPurchasable"] = true,
        ["Buy"] = 285
    },
    ["FairyJar"] = {
        ["Description"] = "Craftable ingredient. Used to create base buildings.",
        ["Origin"] = "Fantasy",
        ["SetOriginFromNode"] = true,
        ["Image"] = "rbxthumb://type=Asset&id=8829239769&w=150&h=150",
        ["Name"] = "FairyJar",
        ["Category"] = "Resources",
        ["ItemType"] = "Resources",
        ["Sell"] = 5,
        ["Rarity"] = {
            ["Index"] = 2,
            ["Drops"] = {["DropChance"] = 6, ["Amount"] = 2},
            ["Fishing"] = {
                ["WaitTime"] = 10,
                ["RequiredSuccesses"] = {["Min"] = 5, ["Max"] = 6},
                ["DropChance"] = 30,
                ["SpinSpeed"] = {["Min"] = 250, ["Max"] = 350}
            },
            ["TextStrokeColor"] = Color3.fromRGB(52, 127, 23),
            ["Alchemy"] = {["DropChance"] = 30, ["ElixirRecyleAmount"] = 50},
            ["Auction"] = {["MinAmount"] = 5000},
            ["Name"] = "Uncommon",
            ["BreedCost"] = {["MinAmount"] = 700},
            ["Bosses"] = {["Amount"] = 100},
            ["SpinnerWheel"] = {["DropChance"] = 20, ["Amount"] = 50},
            ["RecyleAccessory"] = true,
            ["TextColor"] = Color3.fromRGB(82, 199, 36)
        },
        ["Buy"] = 80
    },
    ["Sandstone"] = {
        ["Description"] = "Craftable ingredient. Used to create base buildings.",
        ["Origin"] = "Desert",
        ["SetOriginFromNode"] = true,
        ["Image"] = "rbxthumb://type=Asset&id=8829236004&w=150&h=150",
        ["Name"] = "Sandstone",
        ["Category"] = "Resources",
        ["ItemType"] = "Resources",
        ["Sell"] = 5,
        ["Rarity"] = {
            ["Index"] = 2,
            ["Drops"] = {["DropChance"] = 6, ["Amount"] = 2},
            ["Fishing"] = {
                ["WaitTime"] = 10,
                ["RequiredSuccesses"] = {["Min"] = 5, ["Max"] = 6},
                ["DropChance"] = 30,
                ["SpinSpeed"] = {["Min"] = 250, ["Max"] = 350}
            },
            ["TextStrokeColor"] = Color3.fromRGB(52, 127, 23),
            ["Alchemy"] = {["DropChance"] = 30, ["ElixirRecyleAmount"] = 50},
            ["Auction"] = {["MinAmount"] = 5000},
            ["Name"] = "Uncommon",
            ["BreedCost"] = {["MinAmount"] = 700},
            ["Bosses"] = {["Amount"] = 100},
            ["SpinnerWheel"] = {["DropChance"] = 20, ["Amount"] = 50},
            ["RecyleAccessory"] = true,
            ["TextColor"] = Color3.fromRGB(82, 199, 36)
        },
        ["Buy"] = 70
    },
    ["IronWood"] = {
        ["Description"] = "Craftable ingredient. Used to create base buildings.",
        ["Origin"] = "Volcano",
        ["SetOriginFromNode"] = true,
        ["Image"] = "rbxthumb://type=Asset&id=8829268023&w=150&h=150",
        ["Name"] = "IronWood",
        ["Category"] = "Resources",
        ["ItemType"] = "Resources",
        ["Sell"] = 5,
        ["Rarity"] = {
            ["Index"] = 2,
            ["Drops"] = {["DropChance"] = 6, ["Amount"] = 2},
            ["Fishing"] = {
                ["WaitTime"] = 10,
                ["RequiredSuccesses"] = {["Min"] = 5, ["Max"] = 6},
                ["DropChance"] = 30,
                ["SpinSpeed"] = {["Min"] = 250, ["Max"] = 350}
            },
            ["TextStrokeColor"] = Color3.fromRGB(52, 127, 23),
            ["Alchemy"] = {["DropChance"] = 30, ["ElixirRecyleAmount"] = 50},
            ["Auction"] = {["MinAmount"] = 5000},
            ["Name"] = "Uncommon",
            ["BreedCost"] = {["MinAmount"] = 700},
            ["Bosses"] = {["Amount"] = 100},
            ["SpinnerWheel"] = {["DropChance"] = 20, ["Amount"] = 50},
            ["RecyleAccessory"] = true,
            ["TextColor"] = Color3.fromRGB(82, 199, 36)
        },
        ["Buy"] = 40
    },
    ["Icicle"] = {
        ["Description"] = "Craftable ingredient. Used to create base buildings.",
        ["Origin"] = "Tundra",
        ["SetOriginFromNode"] = true,
        ["Image"] = "rbxthumb://type=Asset&id=8829264488&w=150&h=150",
        ["Name"] = "Icicle",
        ["Category"] = "Resources",
        ["ItemType"] = "Resources",
        ["Sell"] = 5,
        ["Rarity"] = {
            ["Index"] = 2,
            ["Drops"] = {["DropChance"] = 6, ["Amount"] = 2},
            ["Fishing"] = {
                ["WaitTime"] = 10,
                ["RequiredSuccesses"] = {["Min"] = 5, ["Max"] = 6},
                ["DropChance"] = 30,
                ["SpinSpeed"] = {["Min"] = 250, ["Max"] = 350}
            },
            ["TextStrokeColor"] = Color3.fromRGB(52, 127, 23),
            ["Alchemy"] = {["DropChance"] = 30, ["ElixirRecyleAmount"] = 50},
            ["Auction"] = {["MinAmount"] = 5000},
            ["Name"] = "Uncommon",
            ["BreedCost"] = {["MinAmount"] = 700},
            ["Bosses"] = {["Amount"] = 100},
            ["SpinnerWheel"] = {["DropChance"] = 20, ["Amount"] = 50},
            ["RecyleAccessory"] = true,
            ["TextColor"] = Color3.fromRGB(82, 199, 36)
        },
        ["Buy"] = 50
    },
    ["Aloe"] = {
        ["Description"] = "Craftable ingredient. Used to create base buildings.",
        ["Origin"] = "Jungle",
        ["SetOriginFromNode"] = true,
        ["Image"] = "rbxthumb://type=Asset&id=8829247183&w=150&h=150",
        ["Name"] = "Aloe",
        ["Category"] = "Resources",
        ["ItemType"] = "Resources",
        ["Sell"] = 5,
        ["Rarity"] = {
            ["Index"] = 2,
            ["Drops"] = {["DropChance"] = 6, ["Amount"] = 2},
            ["Fishing"] = {
                ["WaitTime"] = 10,
                ["RequiredSuccesses"] = {["Min"] = 5, ["Max"] = 6},
                ["DropChance"] = 30,
                ["SpinSpeed"] = {["Min"] = 250, ["Max"] = 350}
            },
            ["TextStrokeColor"] = Color3.fromRGB(52, 127, 23),
            ["Alchemy"] = {["DropChance"] = 30, ["ElixirRecyleAmount"] = 50},
            ["Auction"] = {["MinAmount"] = 5000},
            ["Name"] = "Uncommon",
            ["BreedCost"] = {["MinAmount"] = 700},
            ["Bosses"] = {["Amount"] = 100},
            ["SpinnerWheel"] = {["DropChance"] = 20, ["Amount"] = 50},
            ["RecyleAccessory"] = true,
            ["TextColor"] = Color3.fromRGB(82, 199, 36)
        },
        ["Buy"] = 30
    },
    ["PineappleSeed"] = {
        ["ToCraft"] = "Plant_Pineapple",
        ["Rarity"] = {
            ["Index"] = 2,
            ["Drops"] = {["DropChance"] = 6, ["Amount"] = 2},
            ["Fishing"] = {
                ["WaitTime"] = 10,
                ["RequiredSuccesses"] = {["Min"] = 5, ["Max"] = 6},
                ["DropChance"] = 30,
                ["SpinSpeed"] = {["Min"] = 250, ["Max"] = 350}
            },
            ["TextStrokeColor"] = Color3.fromRGB(52, 127, 23),
            ["Alchemy"] = {["DropChance"] = 30, ["ElixirRecyleAmount"] = 50},
            ["Auction"] = {["MinAmount"] = 5000},
            ["Name"] = "Uncommon",
            ["BreedCost"] = {["MinAmount"] = 700},
            ["Bosses"] = {["Amount"] = 100},
            ["SpinnerWheel"] = {["DropChance"] = 20, ["Amount"] = 50},
            ["RecyleAccessory"] = true,
            ["TextColor"] = Color3.fromRGB(82, 199, 36)
        },
        ["Origin"] = "Fantasy",
        ["NotInGeneralStore"] = true,
        ["Image"] = "rbxthumb://type=Asset&id=8828078219&w=150&h=150",
        ["Name"] = "PineappleSeed",
        ["Category"] = "Resources",
        ["ItemType"] = "Resources",
        ["Sell"] = 13,
        ["Description"] = "Craftable ingredient. Used to create base buildings.",
        ["Buy"] = 400
    },
    ["DragonfruitSeed"] = {
        ["ToCraft"] = "Plant_Dragonfruit",
        ["Rarity"] = {
            ["Index"] = 2,
            ["Drops"] = {["DropChance"] = 6, ["Amount"] = 2},
            ["Fishing"] = {
                ["WaitTime"] = 10,
                ["RequiredSuccesses"] = {["Min"] = 5, ["Max"] = 6},
                ["DropChance"] = 30,
                ["SpinSpeed"] = {["Min"] = 250, ["Max"] = 350}
            },
            ["TextStrokeColor"] = Color3.fromRGB(52, 127, 23),
            ["Alchemy"] = {["DropChance"] = 30, ["ElixirRecyleAmount"] = 50},
            ["Auction"] = {["MinAmount"] = 5000},
            ["Name"] = "Uncommon",
            ["BreedCost"] = {["MinAmount"] = 700},
            ["Bosses"] = {["Amount"] = 100},
            ["SpinnerWheel"] = {["DropChance"] = 20, ["Amount"] = 50},
            ["RecyleAccessory"] = true,
            ["TextColor"] = Color3.fromRGB(82, 199, 36)
        },
        ["Origin"] = "Toxic",
        ["NotInGeneralStore"] = true,
        ["Image"] = "rbxthumb://type=Asset&id=8828075204&w=150&h=150",
        ["Name"] = "DragonfruitSeed",
        ["Category"] = "Resources",
        ["ItemType"] = "Resources",
        ["Sell"] = 14,
        ["Description"] = "Craftable ingredient. Used to create base buildings.",
        ["Buy"] = 450
    },
    ["Honeycomb"] = {
        ["Description"] = "Craftable ingredient. Used to create base buildings.",
        ["Origin"] = "Grassland",
        ["SetOriginFromNode"] = true,
        ["Image"] = "rbxthumb://type=Asset&id=8829240733&w=150&h=150",
        ["Name"] = "Honeycomb",
        ["Category"] = "Resources",
        ["ItemType"] = "Resources",
        ["Sell"] = 10,
        ["Rarity"] = {
            ["Index"] = 3,
            ["Drops"] = {["DropChance"] = 1, ["Amount"] = 1},
            ["Fishing"] = {
                ["SpinSpeed"] = {["Min"] = 300, ["Max"] = 400},
                ["AnnounceReward"] = false,
                ["WaitTime"] = 10,
                ["RequiredSuccesses"] = {["Min"] = 6, ["Max"] = 7},
                ["DropChance"] = 10
            },
            ["TextStrokeColor"] = Color3.fromRGB(17, 130, 175),
            ["Alchemy"] = {["DropChance"] = 3, ["ElixirRecyleAmount"] = 25},
            ["Auction"] = {["MinAmount"] = 10000},
            ["Name"] = "Rare",
            ["BreedCost"] = {["MinAmount"] = 1500},
            ["Bosses"] = {["Amount"] = 100},
            ["SpinnerWheel"] = {["DropChance"] = 10, ["Amount"] = 25},
            ["RecyleAccessory"] = true,
            ["TextColor"] = Color3.fromRGB(26, 183, 255)
        },
        ["Buy"] = 200
    },
    ["MagicCrystal"] = {
        ["Description"] = "Craftable ingredient. Used to create base buildings.",
        ["Origin"] = "Ocean",
        ["SetOriginFromNode"] = true,
        ["Image"] = "rbxthumb://type=Asset&id=8829255607&w=150&h=150",
        ["Name"] = "MagicCrystal",
        ["Category"] = "Resources",
        ["ItemType"] = "Resources",
        ["Sell"] = 10,
        ["Rarity"] = {
            ["Index"] = 3,
            ["Drops"] = {["DropChance"] = 1, ["Amount"] = 1},
            ["Fishing"] = {
                ["SpinSpeed"] = {["Min"] = 300, ["Max"] = 400},
                ["AnnounceReward"] = false,
                ["WaitTime"] = 10,
                ["RequiredSuccesses"] = {["Min"] = 6, ["Max"] = 7},
                ["DropChance"] = 10
            },
            ["TextStrokeColor"] = Color3.fromRGB(17, 130, 175),
            ["Alchemy"] = {["DropChance"] = 3, ["ElixirRecyleAmount"] = 25},
            ["Auction"] = {["MinAmount"] = 10000},
            ["Name"] = "Rare",
            ["BreedCost"] = {["MinAmount"] = 1500},
            ["Bosses"] = {["Amount"] = 100},
            ["SpinnerWheel"] = {["DropChance"] = 10, ["Amount"] = 25},
            ["RecyleAccessory"] = true,
            ["TextColor"] = Color3.fromRGB(26, 183, 255)
        },
        ["Buy"] = 600
    },
    ["OnionSeed"] = {
        ["ToCraft"] = "Plant_Onion",
        ["Rarity"] = {
            ["Index"] = 2,
            ["Drops"] = {["DropChance"] = 6, ["Amount"] = 2},
            ["Fishing"] = {
                ["WaitTime"] = 10,
                ["RequiredSuccesses"] = {["Min"] = 5, ["Max"] = 6},
                ["DropChance"] = 30,
                ["SpinSpeed"] = {["Min"] = 250, ["Max"] = 350}
            },
            ["TextStrokeColor"] = Color3.fromRGB(52, 127, 23),
            ["Alchemy"] = {["DropChance"] = 30, ["ElixirRecyleAmount"] = 50},
            ["Auction"] = {["MinAmount"] = 5000},
            ["Name"] = "Uncommon",
            ["BreedCost"] = {["MinAmount"] = 700},
            ["Bosses"] = {["Amount"] = 100},
            ["SpinnerWheel"] = {["DropChance"] = 20, ["Amount"] = 50},
            ["RecyleAccessory"] = true,
            ["TextColor"] = Color3.fromRGB(82, 199, 36)
        },
        ["Origin"] = "Tundra",
        ["NotInGeneralStore"] = true,
        ["Image"] = "rbxthumb://type=Asset&id=8828076251&w=150&h=150",
        ["Name"] = "OnionSeed",
        ["Category"] = "Resources",
        ["ItemType"] = "Resources",
        ["Sell"] = 10,
        ["Description"] = "Craftable ingredient. Used to create base buildings.",
        ["Buy"] = 250
    },
    ["Geode"] = {
        ["Description"] = "Craftable ingredient. Used to create base buildings.",
        ["Origin"] = "Prehistoric",
        ["SetOriginFromNode"] = true,
        ["Image"] = "rbxthumb://type=Asset&id=8829261817&w=150&h=150",
        ["Name"] = "Geode",
        ["Category"] = "Resources",
        ["ItemType"] = "Resources",
        ["Sell"] = 10,
        ["Rarity"] = {
            ["Index"] = 3,
            ["Drops"] = {["DropChance"] = 1, ["Amount"] = 1},
            ["Fishing"] = {
                ["SpinSpeed"] = {["Min"] = 300, ["Max"] = 400},
                ["AnnounceReward"] = false,
                ["WaitTime"] = 10,
                ["RequiredSuccesses"] = {["Min"] = 6, ["Max"] = 7},
                ["DropChance"] = 10
            },
            ["TextStrokeColor"] = Color3.fromRGB(17, 130, 175),
            ["Alchemy"] = {["DropChance"] = 3, ["ElixirRecyleAmount"] = 25},
            ["Auction"] = {["MinAmount"] = 10000},
            ["Name"] = "Rare",
            ["BreedCost"] = {["MinAmount"] = 1500},
            ["Bosses"] = {["Amount"] = 100},
            ["SpinnerWheel"] = {["DropChance"] = 10, ["Amount"] = 25},
            ["RecyleAccessory"] = true,
            ["TextColor"] = Color3.fromRGB(26, 183, 255)
        },
        ["Buy"] = 1000
    },
    ["IceCrystal"] = {
        ["Description"] = "Craftable ingredient. Used to create base buildings.",
        ["Origin"] = "Tundra",
        ["SetOriginFromNode"] = true,
        ["Image"] = "rbxthumb://type=Asset&id=8829263065&w=150&h=150",
        ["Name"] = "IceCrystal",
        ["Category"] = "Resources",
        ["ItemType"] = "Resources",
        ["Sell"] = 10,
        ["Rarity"] = {
            ["Index"] = 3,
            ["Drops"] = {["DropChance"] = 1, ["Amount"] = 1},
            ["Fishing"] = {
                ["SpinSpeed"] = {["Min"] = 300, ["Max"] = 400},
                ["AnnounceReward"] = false,
                ["WaitTime"] = 10,
                ["RequiredSuccesses"] = {["Min"] = 6, ["Max"] = 7},
                ["DropChance"] = 10
            },
            ["TextStrokeColor"] = Color3.fromRGB(17, 130, 175),
            ["Alchemy"] = {["DropChance"] = 3, ["ElixirRecyleAmount"] = 25},
            ["Auction"] = {["MinAmount"] = 10000},
            ["Name"] = "Rare",
            ["BreedCost"] = {["MinAmount"] = 1500},
            ["Bosses"] = {["Amount"] = 100},
            ["SpinnerWheel"] = {["DropChance"] = 10, ["Amount"] = 25},
            ["RecyleAccessory"] = true,
            ["TextColor"] = Color3.fromRGB(26, 183, 255)
        },
        ["Buy"] = 500
    },
    ["AppleSeed"] = {
        ["ToCraft"] = "Plant_Apple",
        ["Rarity"] = {
            ["Index"] = 2,
            ["Drops"] = {["DropChance"] = 6, ["Amount"] = 2},
            ["Fishing"] = {
                ["WaitTime"] = 10,
                ["RequiredSuccesses"] = {["Min"] = 5, ["Max"] = 6},
                ["DropChance"] = 30,
                ["SpinSpeed"] = {["Min"] = 250, ["Max"] = 350}
            },
            ["TextStrokeColor"] = Color3.fromRGB(52, 127, 23),
            ["Alchemy"] = {["DropChance"] = 30, ["ElixirRecyleAmount"] = 50},
            ["Auction"] = {["MinAmount"] = 5000},
            ["Name"] = "Uncommon",
            ["BreedCost"] = {["MinAmount"] = 700},
            ["Bosses"] = {["Amount"] = 100},
            ["SpinnerWheel"] = {["DropChance"] = 20, ["Amount"] = 50},
            ["RecyleAccessory"] = true,
            ["TextColor"] = Color3.fromRGB(82, 199, 36)
        },
        ["Origin"] = "Lobby",
        ["NotInGeneralStore"] = true,
        ["Image"] = "rbxthumb://type=Asset&id=8828069000&w=150&h=150",
        ["Name"] = "AppleSeed",
        ["Category"] = "Resources",
        ["ItemType"] = "Resources",
        ["Sell"] = 5,
        ["Description"] = "Craftable ingredient. Used to create base buildings.",
        ["Buy"] = 50
    },
    ["Amber"] = {
        ["Description"] = "Craftable ingredient. Used to create base buildings.",
        ["Origin"] = "Prehistoric",
        ["SetOriginFromNode"] = true,
        ["Image"] = "rbxthumb://type=Asset&id=8829258120&w=150&h=150",
        ["Name"] = "Amber",
        ["Category"] = "Resources",
        ["ItemType"] = "Resources",
        ["Sell"] = 5,
        ["Rarity"] = {
            ["Index"] = 2,
            ["Drops"] = {["DropChance"] = 6, ["Amount"] = 2},
            ["Fishing"] = {
                ["WaitTime"] = 10,
                ["RequiredSuccesses"] = {["Min"] = 5, ["Max"] = 6},
                ["DropChance"] = 30,
                ["SpinSpeed"] = {["Min"] = 250, ["Max"] = 350}
            },
            ["TextStrokeColor"] = Color3.fromRGB(52, 127, 23),
            ["Alchemy"] = {["DropChance"] = 30, ["ElixirRecyleAmount"] = 50},
            ["Auction"] = {["MinAmount"] = 5000},
            ["Name"] = "Uncommon",
            ["BreedCost"] = {["MinAmount"] = 700},
            ["Bosses"] = {["Amount"] = 100},
            ["SpinnerWheel"] = {["DropChance"] = 20, ["Amount"] = 50},
            ["RecyleAccessory"] = true,
            ["TextColor"] = Color3.fromRGB(82, 199, 36)
        },
        ["Buy"] = 100
    },
    ["BunnyFur"] = {
        ["CantTrade"] = true,
        ["Description"] = "Craftable ingredient. Used to create base buildings.",
        ["ItemType"] = "Resources",
        ["Image"] = "rbxthumb://type=Asset&id=8829202632&w=150&h=150",
        ["Name"] = "BunnyFur",
        ["Category"] = "Resources",
        ["Rarity"] = {
            ["Index"] = 4,
            ["Fishing"] = {
                ["SpinSpeed"] = {["Min"] = 350, ["Max"] = 450},
                ["AnnounceReward"] = true,
                ["WaitTime"] = 10,
                ["RequiredSuccesses"] = {["Min"] = 7, ["Max"] = 8},
                ["DropChance"] = 5
            },
            ["Hatching"] = {["AnnounceReward"] = true},
            ["TextStrokeColor"] = Color3.fromRGB(106, 19, 149),
            ["Auction"] = {["MinAmount"] = 25000},
            ["AccessoryGamepassEffect"] = true,
            ["Name"] = "Epic",
            ["BreedCost"] = {["MinAmount"] = 25000},
            ["Bosses"] = {["Amount"] = 1, ["AnnounceReward"] = true},
            ["SpinnerWheel"] = {["Amount"] = 10, ["DropChance"] = 4, ["AnnounceReward"] = true},
            ["Alchemy"] = {["DropChance"] = 30, ["ElixirRecyleAmount"] = 10},
            ["TextColor"] = Color3.fromRGB(182, 34, 255)
        },
        ["Sell"] = 25,
        ["NotPurchasable"] = true,
        ["Buy"] = 150
    },
    ["Shell"] = {
        ["Description"] = "Craftable ingredient. Used to create base buildings.",
        ["Origin"] = "Ocean",
        ["SetOriginFromNode"] = true,
        ["Image"] = "rbxthumb://type=Asset&id=8829259345&w=150&h=150",
        ["Name"] = "Shell",
        ["Category"] = "Resources",
        ["ItemType"] = "Resources",
        ["Sell"] = 1,
        ["Rarity"] = {
            ["Index"] = 1,
            ["Drops"] = {["DropChance"] = 12, ["Amount"] = 4},
            ["Fishing"] = {
                ["WaitTime"] = 10,
                ["RequiredSuccesses"] = {["Min"] = 4, ["Max"] = 5},
                ["DropChance"] = 55,
                ["SpinSpeed"] = {["Min"] = 200, ["Max"] = 300}
            },
            ["TextStrokeColor"] = Color3.fromRGB(89, 89, 89),
            ["Alchemy"] = {["DropChance"] = 30, ["ElixirRecyleAmount"] = 250},
            ["Auction"] = {["MinAmount"] = 1000},
            ["Name"] = "Common",
            ["BreedCost"] = {["MinAmount"] = 250},
            ["Bosses"] = {["Amount"] = 100},
            ["SpinnerWheel"] = {["DropChance"] = 50, ["Amount"] = 100},
            ["RecyleAccessory"] = true,
            ["TextColor"] = Color3.fromRGB(181, 181, 181)
        },
        ["Buy"] = 12
    },
    ["AuroraBorealisJar"] = {
        ["CantTrade"] = true,
        ["Description"] = "Craftable ingredient. Used to create base buildings.",
        ["ItemType"] = "Resources",
        ["Image"] = "rbxthumb://type=Asset&id=8829199419&w=150&h=150",
        ["Name"] = "AuroraBorealisJar",
        ["Category"] = "Resources",
        ["Rarity"] = {
            ["Index"] = 4,
            ["Fishing"] = {
                ["SpinSpeed"] = {["Min"] = 350, ["Max"] = 450},
                ["AnnounceReward"] = true,
                ["WaitTime"] = 10,
                ["RequiredSuccesses"] = {["Min"] = 7, ["Max"] = 8},
                ["DropChance"] = 5
            },
            ["Hatching"] = {["AnnounceReward"] = true},
            ["TextStrokeColor"] = Color3.fromRGB(106, 19, 149),
            ["Auction"] = {["MinAmount"] = 25000},
            ["AccessoryGamepassEffect"] = true,
            ["Name"] = "Epic",
            ["BreedCost"] = {["MinAmount"] = 25000},
            ["Bosses"] = {["Amount"] = 1, ["AnnounceReward"] = true},
            ["SpinnerWheel"] = {["Amount"] = 10, ["DropChance"] = 4, ["AnnounceReward"] = true},
            ["Alchemy"] = {["DropChance"] = 30, ["ElixirRecyleAmount"] = 10},
            ["TextColor"] = Color3.fromRGB(182, 34, 255)
        },
        ["Sell"] = 30,
        ["NotPurchasable"] = true,
        ["Buy"] = 285
    },
    ["Fossil"] = {
        ["Description"] = "Craftable ingredient. Used to create base buildings.",
        ["Origin"] = "Prehistoric",
        ["SetOriginFromNode"] = true,
        ["Image"] = "rbxthumb://type=Asset&id=8829260553&w=150&h=150",
        ["Name"] = "Fossil",
        ["Category"] = "Resources",
        ["ItemType"] = "Resources",
        ["Sell"] = 1,
        ["Rarity"] = {
            ["Index"] = 1,
            ["Drops"] = {["DropChance"] = 12, ["Amount"] = 4},
            ["Fishing"] = {
                ["WaitTime"] = 10,
                ["RequiredSuccesses"] = {["Min"] = 4, ["Max"] = 5},
                ["DropChance"] = 55,
                ["SpinSpeed"] = {["Min"] = 200, ["Max"] = 300}
            },
            ["TextStrokeColor"] = Color3.fromRGB(89, 89, 89),
            ["Alchemy"] = {["DropChance"] = 30, ["ElixirRecyleAmount"] = 250},
            ["Auction"] = {["MinAmount"] = 1000},
            ["Name"] = "Common",
            ["BreedCost"] = {["MinAmount"] = 250},
            ["Bosses"] = {["Amount"] = 100},
            ["SpinnerWheel"] = {["DropChance"] = 50, ["Amount"] = 100},
            ["RecyleAccessory"] = true,
            ["TextColor"] = Color3.fromRGB(181, 181, 181)
        },
        ["Buy"] = 20
    },
    ["ToxicWaste"] = {
        ["Description"] = "Craftable ingredient. Used to create base buildings.",
        ["Origin"] = "Toxic",
        ["SetOriginFromNode"] = true,
        ["Image"] = "rbxthumb://type=Asset&id=8829274454&w=150&h=150",
        ["Name"] = "ToxicWaste",
        ["Category"] = "Resources",
        ["ItemType"] = "Resources",
        ["Sell"] = 1,
        ["Rarity"] = {
            ["Index"] = 1,
            ["Drops"] = {["DropChance"] = 12, ["Amount"] = 4},
            ["Fishing"] = {
                ["WaitTime"] = 10,
                ["RequiredSuccesses"] = {["Min"] = 4, ["Max"] = 5},
                ["DropChance"] = 55,
                ["SpinSpeed"] = {["Min"] = 200, ["Max"] = 300}
            },
            ["TextStrokeColor"] = Color3.fromRGB(89, 89, 89),
            ["Alchemy"] = {["DropChance"] = 30, ["ElixirRecyleAmount"] = 250},
            ["Auction"] = {["MinAmount"] = 1000},
            ["Name"] = "Common",
            ["BreedCost"] = {["MinAmount"] = 250},
            ["Bosses"] = {["Amount"] = 100},
            ["SpinnerWheel"] = {["DropChance"] = 50, ["Amount"] = 100},
            ["RecyleAccessory"] = true,
            ["TextColor"] = Color3.fromRGB(181, 181, 181)
        },
        ["Buy"] = 18
    },
    ["Sand"] = {
        ["Description"] = "Craftable ingredient. Used to create base buildings.",
        ["Origin"] = "Desert",
        ["SetOriginFromNode"] = true,
        ["Image"] = "rbxthumb://type=Asset&id=8829234635&w=150&h=150",
        ["Name"] = "Sand",
        ["Category"] = "Resources",
        ["ItemType"] = "Resources",
        ["Sell"] = 1,
        ["Rarity"] = {
            ["Index"] = 1,
            ["Drops"] = {["DropChance"] = 12, ["Amount"] = 4},
            ["Fishing"] = {
                ["WaitTime"] = 10,
                ["RequiredSuccesses"] = {["Min"] = 4, ["Max"] = 5},
                ["DropChance"] = 55,
                ["SpinSpeed"] = {["Min"] = 200, ["Max"] = 300}
            },
            ["TextStrokeColor"] = Color3.fromRGB(89, 89, 89),
            ["Alchemy"] = {["DropChance"] = 30, ["ElixirRecyleAmount"] = 250},
            ["Auction"] = {["MinAmount"] = 1000},
            ["Name"] = "Common",
            ["BreedCost"] = {["MinAmount"] = 250},
            ["Bosses"] = {["Amount"] = 100},
            ["SpinnerWheel"] = {["DropChance"] = 50, ["Amount"] = 100},
            ["RecyleAccessory"] = true,
            ["TextColor"] = Color3.fromRGB(181, 181, 181)
        },
        ["Buy"] = 14
    },
    ["FertilizerCrude"] = {
        ["CantTrade"] = true,
        ["Description"] = "Basic fertilizer for your farm!",
        ["FertilityToAdd"] = 20,
        ["DisplayName"] = "CrudeFertilizer",
        ["Image"] = "rbxthumb://type=Asset&id=91005297945913&w=150&h=150",
        ["Name"] = "FertilizerCrude",
        ["Category"] = "Resources",
        ["ItemType"] = "Resources",
        ["Rarity"] = {
            ["Index"] = 2,
            ["Drops"] = {["DropChance"] = 6, ["Amount"] = 2},
            ["Fishing"] = {
                ["WaitTime"] = 10,
                ["RequiredSuccesses"] = {["Min"] = 5, ["Max"] = 6},
                ["DropChance"] = 30,
                ["SpinSpeed"] = {["Min"] = 250, ["Max"] = 350}
            },
            ["TextStrokeColor"] = Color3.fromRGB(52, 127, 23),
            ["Alchemy"] = {["DropChance"] = 30, ["ElixirRecyleAmount"] = 50},
            ["Auction"] = {["MinAmount"] = 5000},
            ["Name"] = "Uncommon",
            ["BreedCost"] = {["MinAmount"] = 700},
            ["Bosses"] = {["Amount"] = 100},
            ["SpinnerWheel"] = {["DropChance"] = 20, ["Amount"] = 50},
            ["RecyleAccessory"] = true,
            ["TextColor"] = Color3.fromRGB(82, 199, 36)
        }
    },
    ["BoneMeal"] = {
        ["CantTrade"] = true,
        ["Image"] = "rbxthumb://type=Asset&id=119352621999220&w=150&h=150",
        ["Rarity"] = {
            ["Index"] = 1,
            ["Drops"] = {["DropChance"] = 12, ["Amount"] = 4},
            ["Fishing"] = {
                ["WaitTime"] = 10,
                ["RequiredSuccesses"] = {["Min"] = 4, ["Max"] = 5},
                ["DropChance"] = 55,
                ["SpinSpeed"] = {["Min"] = 200, ["Max"] = 300}
            },
            ["TextStrokeColor"] = Color3.fromRGB(89, 89, 89),
            ["Alchemy"] = {["DropChance"] = 30, ["ElixirRecyleAmount"] = 250},
            ["Auction"] = {["MinAmount"] = 1000},
            ["Name"] = "Common",
            ["BreedCost"] = {["MinAmount"] = 250},
            ["Bosses"] = {["Amount"] = 100},
            ["SpinnerWheel"] = {["DropChance"] = 50, ["Amount"] = 100},
            ["RecyleAccessory"] = true,
            ["TextColor"] = Color3.fromRGB(181, 181, 181)
        },
        ["FertilityToAdd"] = 4,
        ["ItemType"] = "Resources",
        ["Name"] = "BoneMeal",
        ["Category"] = "Resources",
        ["Description"] = "Used in Compost Bins to create Fertilizer for your farm!"
    },
    ["Coal"] = {
        ["Description"] = "Craftable ingredient. Used to create base buildings.",
        ["Origin"] = "Volcano",
        ["SetOriginFromNode"] = true,
        ["Image"] = "rbxthumb://type=Asset&id=8829266667&w=150&h=150",
        ["Name"] = "Coal",
        ["Category"] = "Resources",
        ["ItemType"] = "Resources",
        ["Sell"] = 1,
        ["Rarity"] = {
            ["Index"] = 1,
            ["Drops"] = {["DropChance"] = 12, ["Amount"] = 4},
            ["Fishing"] = {
                ["WaitTime"] = 10,
                ["RequiredSuccesses"] = {["Min"] = 4, ["Max"] = 5},
                ["DropChance"] = 55,
                ["SpinSpeed"] = {["Min"] = 200, ["Max"] = 300}
            },
            ["TextStrokeColor"] = Color3.fromRGB(89, 89, 89),
            ["Alchemy"] = {["DropChance"] = 30, ["ElixirRecyleAmount"] = 250},
            ["Auction"] = {["MinAmount"] = 1000},
            ["Name"] = "Common",
            ["BreedCost"] = {["MinAmount"] = 250},
            ["Bosses"] = {["Amount"] = 100},
            ["SpinnerWheel"] = {["DropChance"] = 50, ["Amount"] = 100},
            ["RecyleAccessory"] = true,
            ["TextColor"] = Color3.fromRGB(181, 181, 181)
        },
        ["Buy"] = 8
    },
    ["Blossom"] = {
        ["Description"] = "Craftable ingredient. Used to create base buildings.",
        ["Origin"] = "Fantasy",
        ["SetOriginFromNode"] = true,
        ["Image"] = "rbxthumb://type=Asset&id=8829238627&w=150&h=150",
        ["Name"] = "Blossom",
        ["Category"] = "Resources",
        ["ItemType"] = "Resources",
        ["Sell"] = 1,
        ["Rarity"] = {
            ["Index"] = 1,
            ["Drops"] = {["DropChance"] = 12, ["Amount"] = 4},
            ["Fishing"] = {
                ["WaitTime"] = 10,
                ["RequiredSuccesses"] = {["Min"] = 4, ["Max"] = 5},
                ["DropChance"] = 55,
                ["SpinSpeed"] = {["Min"] = 200, ["Max"] = 300}
            },
            ["TextStrokeColor"] = Color3.fromRGB(89, 89, 89),
            ["Alchemy"] = {["DropChance"] = 30, ["ElixirRecyleAmount"] = 250},
            ["Auction"] = {["MinAmount"] = 1000},
            ["Name"] = "Common",
            ["BreedCost"] = {["MinAmount"] = 250},
            ["Bosses"] = {["Amount"] = 100},
            ["SpinnerWheel"] = {["DropChance"] = 50, ["Amount"] = 100},
            ["RecyleAccessory"] = true,
            ["TextColor"] = Color3.fromRGB(181, 181, 181)
        },
        ["Buy"] = 16
    },
    ["FertilizerRegular"] = {
        ["CantTrade"] = true,
        ["Description"] = "Improved fertilizer for your farm!",
        ["FertilityToAdd"] = 40,
        ["DisplayName"] = "Fertilizer",
        ["Image"] = "rbxthumb://type=Asset&id=137252630281330&w=150&h=150",
        ["Name"] = "FertilizerRegular",
        ["Category"] = "Resources",
        ["ItemType"] = "Resources",
        ["Rarity"] = {
            ["Index"] = 3,
            ["Drops"] = {["DropChance"] = 1, ["Amount"] = 1},
            ["Fishing"] = {
                ["SpinSpeed"] = {["Min"] = 300, ["Max"] = 400},
                ["AnnounceReward"] = false,
                ["WaitTime"] = 10,
                ["RequiredSuccesses"] = {["Min"] = 6, ["Max"] = 7},
                ["DropChance"] = 10
            },
            ["TextStrokeColor"] = Color3.fromRGB(17, 130, 175),
            ["Alchemy"] = {["DropChance"] = 3, ["ElixirRecyleAmount"] = 25},
            ["Auction"] = {["MinAmount"] = 10000},
            ["Name"] = "Rare",
            ["BreedCost"] = {["MinAmount"] = 1500},
            ["Bosses"] = {["Amount"] = 100},
            ["SpinnerWheel"] = {["DropChance"] = 10, ["Amount"] = 25},
            ["RecyleAccessory"] = true,
            ["TextColor"] = Color3.fromRGB(26, 183, 255)
        }
    },
    ["Leaf"] = {
        ["Description"] = "Craftable ingredient. Used to create base buildings.",
        ["Origin"] = "Lobby",
        ["SetOriginFromNode"] = true,
        ["Image"] = "rbxthumb://type=Asset&id=8829252598&w=150&h=150",
        ["Name"] = "Leaf",
        ["Category"] = "Resources",
        ["ItemType"] = "Resources",
        ["Sell"] = 1,
        ["Rarity"] = {
            ["Index"] = 1,
            ["Drops"] = {["DropChance"] = 12, ["Amount"] = 4},
            ["Fishing"] = {
                ["WaitTime"] = 10,
                ["RequiredSuccesses"] = {["Min"] = 4, ["Max"] = 5},
                ["DropChance"] = 55,
                ["SpinSpeed"] = {["Min"] = 200, ["Max"] = 300}
            },
            ["TextStrokeColor"] = Color3.fromRGB(89, 89, 89),
            ["Alchemy"] = {["DropChance"] = 30, ["ElixirRecyleAmount"] = 250},
            ["Auction"] = {["MinAmount"] = 1000},
            ["Name"] = "Common",
            ["BreedCost"] = {["MinAmount"] = 250},
            ["Bosses"] = {["Amount"] = 100},
            ["SpinnerWheel"] = {["DropChance"] = 50, ["Amount"] = 100},
            ["RecyleAccessory"] = true,
            ["TextColor"] = Color3.fromRGB(181, 181, 181)
        },
        ["Buy"] = 2
    },
    ["PetrifiedStone"] = {
        ["CantTrade"] = true,
        ["Description"] = "Craftable ingredient. Used to create base buildings.",
        ["ItemType"] = "Resources",
        ["Image"] = "rbxthumb://type=Asset&id=8829217294&w=150&h=150",
        ["Name"] = "PetrifiedStone",
        ["Category"] = "Resources",
        ["Rarity"] = {
            ["Index"] = 4,
            ["Fishing"] = {
                ["SpinSpeed"] = {["Min"] = 350, ["Max"] = 450},
                ["AnnounceReward"] = true,
                ["WaitTime"] = 10,
                ["RequiredSuccesses"] = {["Min"] = 7, ["Max"] = 8},
                ["DropChance"] = 5
            },
            ["Hatching"] = {["AnnounceReward"] = true},
            ["TextStrokeColor"] = Color3.fromRGB(106, 19, 149),
            ["Auction"] = {["MinAmount"] = 25000},
            ["AccessoryGamepassEffect"] = true,
            ["Name"] = "Epic",
            ["BreedCost"] = {["MinAmount"] = 25000},
            ["Bosses"] = {["Amount"] = 1, ["AnnounceReward"] = true},
            ["SpinnerWheel"] = {["Amount"] = 10, ["DropChance"] = 4, ["AnnounceReward"] = true},
            ["Alchemy"] = {["DropChance"] = 30, ["ElixirRecyleAmount"] = 10},
            ["TextColor"] = Color3.fromRGB(182, 34, 255)
        },
        ["Sell"] = 30,
        ["NotPurchasable"] = true,
        ["Buy"] = 285
    },
    ["Amethyst"] = {
        ["Description"] = "Craftable ingredient. Used to create base buildings.",
        ["Origin"] = "Fantasy",
        ["SetOriginFromNode"] = true,
        ["Image"] = "rbxthumb://type=Asset&id=8829237560&w=150&h=150",
        ["Name"] = "Amethyst",
        ["Category"] = "Resources",
        ["ItemType"] = "Resources",
        ["Sell"] = 10,
        ["Rarity"] = {
            ["Index"] = 3,
            ["Drops"] = {["DropChance"] = 1, ["Amount"] = 1},
            ["Fishing"] = {
                ["SpinSpeed"] = {["Min"] = 300, ["Max"] = 400},
                ["AnnounceReward"] = false,
                ["WaitTime"] = 10,
                ["RequiredSuccesses"] = {["Min"] = 6, ["Max"] = 7},
                ["DropChance"] = 10
            },
            ["TextStrokeColor"] = Color3.fromRGB(17, 130, 175),
            ["Alchemy"] = {["DropChance"] = 3, ["ElixirRecyleAmount"] = 25},
            ["Auction"] = {["MinAmount"] = 10000},
            ["Name"] = "Rare",
            ["BreedCost"] = {["MinAmount"] = 1500},
            ["Bosses"] = {["Amount"] = 100},
            ["SpinnerWheel"] = {["DropChance"] = 10, ["Amount"] = 25},
            ["RecyleAccessory"] = true,
            ["TextColor"] = Color3.fromRGB(26, 183, 255)
        },
        ["Buy"] = 800
    },
    ["CoconutSeed"] = {
        ["ToCraft"] = "Plant_Coconut",
        ["Rarity"] = {
            ["Index"] = 2,
            ["Drops"] = {["DropChance"] = 6, ["Amount"] = 2},
            ["Fishing"] = {
                ["WaitTime"] = 10,
                ["RequiredSuccesses"] = {["Min"] = 5, ["Max"] = 6},
                ["DropChance"] = 30,
                ["SpinSpeed"] = {["Min"] = 250, ["Max"] = 350}
            },
            ["TextStrokeColor"] = Color3.fromRGB(52, 127, 23),
            ["Alchemy"] = {["DropChance"] = 30, ["ElixirRecyleAmount"] = 50},
            ["Auction"] = {["MinAmount"] = 5000},
            ["Name"] = "Uncommon",
            ["BreedCost"] = {["MinAmount"] = 700},
            ["Bosses"] = {["Amount"] = 100},
            ["SpinnerWheel"] = {["DropChance"] = 20, ["Amount"] = 50},
            ["RecyleAccessory"] = true,
            ["TextColor"] = Color3.fromRGB(82, 199, 36)
        },
        ["Origin"] = "Prehistoric",
        ["NotInGeneralStore"] = true,
        ["Image"] = "rbxthumb://type=Asset&id=8828073837&w=150&h=150",
        ["Name"] = "CoconutSeed",
        ["Category"] = "Resources",
        ["ItemType"] = "Resources",
        ["Sell"] = 15,
        ["Description"] = "Craftable ingredient. Used to create base buildings.",
        ["Buy"] = 500
    },
    ["Lotus"] = {
        ["CantTrade"] = true,
        ["Description"] = "Craftable ingredient. Used to create base buildings.",
        ["ItemType"] = "Resources",
        ["Image"] = "rbxthumb://type=Asset&id=8829204143&w=150&h=150",
        ["Name"] = "Lotus",
        ["Category"] = "Resources",
        ["Rarity"] = {
            ["Index"] = 4,
            ["Fishing"] = {
                ["SpinSpeed"] = {["Min"] = 350, ["Max"] = 450},
                ["AnnounceReward"] = true,
                ["WaitTime"] = 10,
                ["RequiredSuccesses"] = {["Min"] = 7, ["Max"] = 8},
                ["DropChance"] = 5
            },
            ["Hatching"] = {["AnnounceReward"] = true},
            ["TextStrokeColor"] = Color3.fromRGB(106, 19, 149),
            ["Auction"] = {["MinAmount"] = 25000},
            ["AccessoryGamepassEffect"] = true,
            ["Name"] = "Epic",
            ["BreedCost"] = {["MinAmount"] = 25000},
            ["Bosses"] = {["Amount"] = 1, ["AnnounceReward"] = true},
            ["SpinnerWheel"] = {["Amount"] = 10, ["DropChance"] = 4, ["AnnounceReward"] = true},
            ["Alchemy"] = {["DropChance"] = 30, ["ElixirRecyleAmount"] = 10},
            ["TextColor"] = Color3.fromRGB(182, 34, 255)
        },
        ["Sell"] = 25,
        ["NotPurchasable"] = true,
        ["Buy"] = 150
    },
    ["WatermelonSeed"] = {
        ["ToCraft"] = "Plant_Watermelon",
        ["Rarity"] = {
            ["Index"] = 2,
            ["Drops"] = {["DropChance"] = 6, ["Amount"] = 2},
            ["Fishing"] = {
                ["WaitTime"] = 10,
                ["RequiredSuccesses"] = {["Min"] = 5, ["Max"] = 6},
                ["DropChance"] = 30,
                ["SpinSpeed"] = {["Min"] = 250, ["Max"] = 350}
            },
            ["TextStrokeColor"] = Color3.fromRGB(52, 127, 23),
            ["Alchemy"] = {["DropChance"] = 30, ["ElixirRecyleAmount"] = 50},
            ["Auction"] = {["MinAmount"] = 5000},
            ["Name"] = "Uncommon",
            ["BreedCost"] = {["MinAmount"] = 700},
            ["Bosses"] = {["Amount"] = 100},
            ["SpinnerWheel"] = {["DropChance"] = 20, ["Amount"] = 50},
            ["RecyleAccessory"] = true,
            ["TextColor"] = Color3.fromRGB(82, 199, 36)
        },
        ["Origin"] = "Ocean",
        ["NotInGeneralStore"] = true,
        ["Image"] = "rbxthumb://type=Asset&id=8828081605&w=150&h=150",
        ["Name"] = "WatermelonSeed",
        ["Category"] = "Resources",
        ["ItemType"] = "Resources",
        ["Sell"] = 12,
        ["Description"] = "Craftable ingredient. Used to create base buildings.",
        ["Buy"] = 300
    },
    ["Snow"] = {
        ["Description"] = "Craftable ingredient. Used to create base buildings.",
        ["Origin"] = "Tundra",
        ["SetOriginFromNode"] = true,
        ["Image"] = "rbxthumb://type=Asset&id=8829265373&w=150&h=150",
        ["Name"] = "Snow",
        ["Category"] = "Resources",
        ["ItemType"] = "Resources",
        ["Sell"] = 1,
        ["Rarity"] = {
            ["Index"] = 1,
            ["Drops"] = {["DropChance"] = 12, ["Amount"] = 4},
            ["Fishing"] = {
                ["WaitTime"] = 10,
                ["RequiredSuccesses"] = {["Min"] = 4, ["Max"] = 5},
                ["DropChance"] = 55,
                ["SpinSpeed"] = {["Min"] = 200, ["Max"] = 300}
            },
            ["TextStrokeColor"] = Color3.fromRGB(89, 89, 89),
            ["Alchemy"] = {["DropChance"] = 30, ["ElixirRecyleAmount"] = 250},
            ["Auction"] = {["MinAmount"] = 1000},
            ["Name"] = "Common",
            ["BreedCost"] = {["MinAmount"] = 250},
            ["Bosses"] = {["Amount"] = 100},
            ["SpinnerWheel"] = {["DropChance"] = 50, ["Amount"] = 100},
            ["RecyleAccessory"] = true,
            ["TextColor"] = Color3.fromRGB(181, 181, 181)
        },
        ["Buy"] = 10
    },
    ["FellCrystal"] = {
        ["Description"] = "Craftable ingredient. Used to create base buildings.",
        ["Origin"] = "Toxic",
        ["SetOriginFromNode"] = true,
        ["Image"] = "rbxthumb://type=Asset&id=8829271584&w=150&h=150",
        ["Name"] = "FellCrystal",
        ["Category"] = "Resources",
        ["ItemType"] = "Resources",
        ["Sell"] = 10,
        ["Rarity"] = {
            ["Index"] = 3,
            ["Drops"] = {["DropChance"] = 1, ["Amount"] = 1},
            ["Fishing"] = {
                ["SpinSpeed"] = {["Min"] = 300, ["Max"] = 400},
                ["AnnounceReward"] = false,
                ["WaitTime"] = 10,
                ["RequiredSuccesses"] = {["Min"] = 6, ["Max"] = 7},
                ["DropChance"] = 10
            },
            ["TextStrokeColor"] = Color3.fromRGB(17, 130, 175),
            ["Alchemy"] = {["DropChance"] = 3, ["ElixirRecyleAmount"] = 25},
            ["Auction"] = {["MinAmount"] = 10000},
            ["Name"] = "Rare",
            ["BreedCost"] = {["MinAmount"] = 1500},
            ["Bosses"] = {["Amount"] = 100},
            ["SpinnerWheel"] = {["DropChance"] = 10, ["Amount"] = 25},
            ["RecyleAccessory"] = true,
            ["TextColor"] = Color3.fromRGB(26, 183, 255)
        },
        ["Buy"] = 900
    },
    ["CactusPiece"] = {
        ["Description"] = "Craftable ingredient. Used to create base buildings.",
        ["Origin"] = "Desert",
        ["SetOriginFromNode"] = true,
        ["Image"] = "rbxthumb://type=Asset&id=8829233103&w=150&h=150",
        ["Name"] = "CactusPiece",
        ["Category"] = "Resources",
        ["ItemType"] = "Resources",
        ["Sell"] = 10,
        ["Rarity"] = {
            ["Index"] = 3,
            ["Drops"] = {["DropChance"] = 1, ["Amount"] = 1},
            ["Fishing"] = {
                ["SpinSpeed"] = {["Min"] = 300, ["Max"] = 400},
                ["AnnounceReward"] = false,
                ["WaitTime"] = 10,
                ["RequiredSuccesses"] = {["Min"] = 6, ["Max"] = 7},
                ["DropChance"] = 10
            },
            ["TextStrokeColor"] = Color3.fromRGB(17, 130, 175),
            ["Alchemy"] = {["DropChance"] = 3, ["ElixirRecyleAmount"] = 25},
            ["Auction"] = {["MinAmount"] = 10000},
            ["Name"] = "Rare",
            ["BreedCost"] = {["MinAmount"] = 1500},
            ["Bosses"] = {["Amount"] = 100},
            ["SpinnerWheel"] = {["DropChance"] = 10, ["Amount"] = 25},
            ["RecyleAccessory"] = true,
            ["TextColor"] = Color3.fromRGB(26, 183, 255)
        },
        ["Buy"] = 700
    },
    ["Copper"] = {
        ["Description"] = "Craftable ingredient. Used to create base buildings.",
        ["Origin"] = "Lobby",
        ["SetOriginFromNode"] = true,
        ["Image"] = "rbxthumb://type=Asset&id=8829251458&w=150&h=150",
        ["Name"] = "Copper",
        ["Category"] = "Resources",
        ["ItemType"] = "Resources",
        ["Sell"] = 10,
        ["Rarity"] = {
            ["Index"] = 3,
            ["Drops"] = {["DropChance"] = 1, ["Amount"] = 1},
            ["Fishing"] = {
                ["SpinSpeed"] = {["Min"] = 300, ["Max"] = 400},
                ["AnnounceReward"] = false,
                ["WaitTime"] = 10,
                ["RequiredSuccesses"] = {["Min"] = 6, ["Max"] = 7},
                ["DropChance"] = 10
            },
            ["TextStrokeColor"] = Color3.fromRGB(17, 130, 175),
            ["Alchemy"] = {["DropChance"] = 3, ["ElixirRecyleAmount"] = 25},
            ["Auction"] = {["MinAmount"] = 10000},
            ["Name"] = "Rare",
            ["BreedCost"] = {["MinAmount"] = 1500},
            ["Bosses"] = {["Amount"] = 100},
            ["SpinnerWheel"] = {["DropChance"] = 10, ["Amount"] = 25},
            ["RecyleAccessory"] = true,
            ["TextColor"] = Color3.fromRGB(26, 183, 255)
        },
        ["Buy"] = 100
    },
    ["GhoulWood"] = {
        ["CantTrade"] = true,
        ["Description"] = "Craftable ingredient. Used to create base buildings.",
        ["ItemType"] = "Resources",
        ["NotSuitableForChina"] = true,
        ["Image"] = "rbxthumb://type=Asset&id=8829211880&w=150&h=150",
        ["Name"] = "GhoulWood",
        ["Category"] = "Resources",
        ["Rarity"] = {
            ["Index"] = 4,
            ["Fishing"] = {
                ["SpinSpeed"] = {["Min"] = 350, ["Max"] = 450},
                ["AnnounceReward"] = true,
                ["WaitTime"] = 10,
                ["RequiredSuccesses"] = {["Min"] = 7, ["Max"] = 8},
                ["DropChance"] = 5
            },
            ["Hatching"] = {["AnnounceReward"] = true},
            ["TextStrokeColor"] = Color3.fromRGB(106, 19, 149),
            ["Auction"] = {["MinAmount"] = 25000},
            ["AccessoryGamepassEffect"] = true,
            ["Name"] = "Epic",
            ["BreedCost"] = {["MinAmount"] = 25000},
            ["Bosses"] = {["Amount"] = 1, ["AnnounceReward"] = true},
            ["SpinnerWheel"] = {["Amount"] = 10, ["DropChance"] = 4, ["AnnounceReward"] = true},
            ["Alchemy"] = {["DropChance"] = 30, ["ElixirRecyleAmount"] = 10},
            ["TextColor"] = Color3.fromRGB(182, 34, 255)
        },
        ["Sell"] = 30,
        ["NotPurchasable"] = true,
        ["Buy"] = 285
    },
    ["BananaSeed"] = {
        ["ToCraft"] = "Plant_Banana",
        ["Rarity"] = {
            ["Index"] = 2,
            ["Drops"] = {["DropChance"] = 6, ["Amount"] = 2},
            ["Fishing"] = {
                ["WaitTime"] = 10,
                ["RequiredSuccesses"] = {["Min"] = 5, ["Max"] = 6},
                ["DropChance"] = 30,
                ["SpinSpeed"] = {["Min"] = 250, ["Max"] = 350}
            },
            ["TextStrokeColor"] = Color3.fromRGB(52, 127, 23),
            ["Alchemy"] = {["DropChance"] = 30, ["ElixirRecyleAmount"] = 50},
            ["Auction"] = {["MinAmount"] = 5000},
            ["Name"] = "Uncommon",
            ["BreedCost"] = {["MinAmount"] = 700},
            ["Bosses"] = {["Amount"] = 100},
            ["SpinnerWheel"] = {["DropChance"] = 20, ["Amount"] = 50},
            ["RecyleAccessory"] = true,
            ["TextColor"] = Color3.fromRGB(82, 199, 36)
        },
        ["Origin"] = "Volcano",
        ["NotInGeneralStore"] = true,
        ["Image"] = "rbxthumb://type=Asset&id=8828070316&w=150&h=150",
        ["Name"] = "BananaSeed",
        ["Category"] = "Resources",
        ["ItemType"] = "Resources",
        ["Sell"] = 10,
        ["Description"] = "Craftable ingredient. Used to create base buildings.",
        ["Buy"] = 200
    },
    ["CarrotSeed"] = {
        ["ToCraft"] = "Plant_Carrot",
        ["Rarity"] = {
            ["Index"] = 2,
            ["Drops"] = {["DropChance"] = 6, ["Amount"] = 2},
            ["Fishing"] = {
                ["WaitTime"] = 10,
                ["RequiredSuccesses"] = {["Min"] = 5, ["Max"] = 6},
                ["DropChance"] = 30,
                ["SpinSpeed"] = {["Min"] = 250, ["Max"] = 350}
            },
            ["TextStrokeColor"] = Color3.fromRGB(52, 127, 23),
            ["Alchemy"] = {["DropChance"] = 30, ["ElixirRecyleAmount"] = 50},
            ["Auction"] = {["MinAmount"] = 5000},
            ["Name"] = "Uncommon",
            ["BreedCost"] = {["MinAmount"] = 700},
            ["Bosses"] = {["Amount"] = 100},
            ["SpinnerWheel"] = {["DropChance"] = 20, ["Amount"] = 50},
            ["RecyleAccessory"] = true,
            ["TextColor"] = Color3.fromRGB(82, 199, 36)
        },
        ["Origin"] = "Grassland",
        ["NotInGeneralStore"] = true,
        ["Image"] = "rbxthumb://type=Asset&id=8828071721&w=150&h=150",
        ["Name"] = "CarrotSeed",
        ["Category"] = "Resources",
        ["ItemType"] = "Resources",
        ["Sell"] = 7,
        ["Description"] = "Craftable ingredient. Used to create base buildings.",
        ["Buy"] = 100
    },
    ["ConcentratedPoison"] = {
        ["Description"] = "Craftable ingredient. Used to create base buildings.",
        ["Origin"] = "Toxic",
        ["SetOriginFromNode"] = true,
        ["Image"] = "rbxthumb://type=Asset&id=8829270448&w=150&h=150",
        ["Name"] = "ConcentratedPoison",
        ["Category"] = "Resources",
        ["ItemType"] = "Resources",
        ["Sell"] = 5,
        ["Rarity"] = {
            ["Index"] = 2,
            ["Drops"] = {["DropChance"] = 6, ["Amount"] = 2},
            ["Fishing"] = {
                ["WaitTime"] = 10,
                ["RequiredSuccesses"] = {["Min"] = 5, ["Max"] = 6},
                ["DropChance"] = 30,
                ["SpinSpeed"] = {["Min"] = 250, ["Max"] = 350}
            },
            ["TextStrokeColor"] = Color3.fromRGB(52, 127, 23),
            ["Alchemy"] = {["DropChance"] = 30, ["ElixirRecyleAmount"] = 50},
            ["Auction"] = {["MinAmount"] = 5000},
            ["Name"] = "Uncommon",
            ["BreedCost"] = {["MinAmount"] = 700},
            ["Bosses"] = {["Amount"] = 100},
            ["SpinnerWheel"] = {["DropChance"] = 20, ["Amount"] = 50},
            ["RecyleAccessory"] = true,
            ["TextColor"] = Color3.fromRGB(82, 199, 36)
        },
        ["Buy"] = 90
    },
    ["Ashes"] = {
        ["Image"] = "rbxthumb://type=Asset&id=8828116422&w=150&h=150",
        ["Rarity"] = {
            ["Index"] = 1,
            ["Drops"] = {["DropChance"] = 12, ["Amount"] = 4},
            ["Fishing"] = {
                ["WaitTime"] = 10,
                ["RequiredSuccesses"] = {["Min"] = 4, ["Max"] = 5},
                ["DropChance"] = 55,
                ["SpinSpeed"] = {["Min"] = 200, ["Max"] = 300}
            },
            ["TextStrokeColor"] = Color3.fromRGB(89, 89, 89),
            ["Alchemy"] = {["DropChance"] = 30, ["ElixirRecyleAmount"] = 250},
            ["Auction"] = {["MinAmount"] = 1000},
            ["Name"] = "Common",
            ["BreedCost"] = {["MinAmount"] = 250},
            ["Bosses"] = {["Amount"] = 100},
            ["SpinnerWheel"] = {["DropChance"] = 50, ["Amount"] = 100},
            ["RecyleAccessory"] = true,
            ["TextColor"] = Color3.fromRGB(181, 181, 181)
        },
        ["Category"] = "Resources",
        ["ItemType"] = "Resources",
        ["Sell"] = 1,
        ["Name"] = "Ashes",
        ["Description"] = "Craftable ingredient. Used to create base buildings."
    },
    ["Snowflake"] = {
        ["CantTrade"] = true,
        ["Description"] = "Craftable ingredient. Used to create base buildings.",
        ["ItemType"] = "Resources",
        ["Image"] = "rbxthumb://type=Asset&id=8829201136&w=150&h=150",
        ["Name"] = "Snowflake",
        ["Category"] = "Resources",
        ["Rarity"] = {
            ["Index"] = 2,
            ["Drops"] = {["DropChance"] = 6, ["Amount"] = 2},
            ["Fishing"] = {
                ["WaitTime"] = 10,
                ["RequiredSuccesses"] = {["Min"] = 5, ["Max"] = 6},
                ["DropChance"] = 30,
                ["SpinSpeed"] = {["Min"] = 250, ["Max"] = 350}
            },
            ["TextStrokeColor"] = Color3.fromRGB(52, 127, 23),
            ["Alchemy"] = {["DropChance"] = 30, ["ElixirRecyleAmount"] = 50},
            ["Auction"] = {["MinAmount"] = 5000},
            ["Name"] = "Uncommon",
            ["BreedCost"] = {["MinAmount"] = 700},
            ["Bosses"] = {["Amount"] = 100},
            ["SpinnerWheel"] = {["DropChance"] = 20, ["Amount"] = 50},
            ["RecyleAccessory"] = true,
            ["TextColor"] = Color3.fromRGB(82, 199, 36)
        },
        ["Sell"] = 30,
        ["NotPurchasable"] = true,
        ["Buy"] = 285
    },
    ["PumpkinSeed"] = {
        ["ToCraft"] = "Plant_Pumpkin",
        ["Rarity"] = {
            ["Index"] = 2,
            ["Drops"] = {["DropChance"] = 6, ["Amount"] = 2},
            ["Fishing"] = {
                ["WaitTime"] = 10,
                ["RequiredSuccesses"] = {["Min"] = 5, ["Max"] = 6},
                ["DropChance"] = 30,
                ["SpinSpeed"] = {["Min"] = 250, ["Max"] = 350}
            },
            ["TextStrokeColor"] = Color3.fromRGB(52, 127, 23),
            ["Alchemy"] = {["DropChance"] = 30, ["ElixirRecyleAmount"] = 50},
            ["Auction"] = {["MinAmount"] = 5000},
            ["Name"] = "Uncommon",
            ["BreedCost"] = {["MinAmount"] = 700},
            ["Bosses"] = {["Amount"] = 100},
            ["SpinnerWheel"] = {["DropChance"] = 20, ["Amount"] = 50},
            ["RecyleAccessory"] = true,
            ["TextColor"] = Color3.fromRGB(82, 199, 36)
        },
        ["Origin"] = "Desert",
        ["NotInGeneralStore"] = true,
        ["Image"] = "rbxthumb://type=Asset&id=8828079385&w=150&h=150",
        ["Name"] = "PumpkinSeed",
        ["Category"] = "Resources",
        ["ItemType"] = "Resources",
        ["Sell"] = 12,
        ["Description"] = "Craftable ingredient. Used to create base buildings.",
        ["Buy"] = 350
    },
    ["EvilBat"] = {
        ["CantTrade"] = true,
        ["Description"] = "Craftable ingredient. Used to create base buildings.",
        ["ItemType"] = "Resources",
        ["NotSuitableForChina"] = true,
        ["Image"] = "rbxthumb://type=Asset&id=8829205910&w=150&h=150",
        ["Name"] = "EvilBat",
        ["Category"] = "Resources",
        ["Rarity"] = {
            ["Index"] = 4,
            ["Fishing"] = {
                ["SpinSpeed"] = {["Min"] = 350, ["Max"] = 450},
                ["AnnounceReward"] = true,
                ["WaitTime"] = 10,
                ["RequiredSuccesses"] = {["Min"] = 7, ["Max"] = 8},
                ["DropChance"] = 5
            },
            ["Hatching"] = {["AnnounceReward"] = true},
            ["TextStrokeColor"] = Color3.fromRGB(106, 19, 149),
            ["Auction"] = {["MinAmount"] = 25000},
            ["AccessoryGamepassEffect"] = true,
            ["Name"] = "Epic",
            ["BreedCost"] = {["MinAmount"] = 25000},
            ["Bosses"] = {["Amount"] = 1, ["AnnounceReward"] = true},
            ["SpinnerWheel"] = {["Amount"] = 10, ["DropChance"] = 4, ["AnnounceReward"] = true},
            ["Alchemy"] = {["DropChance"] = 30, ["ElixirRecyleAmount"] = 10},
            ["TextColor"] = Color3.fromRGB(182, 34, 255)
        },
        ["Sell"] = 30,
        ["NotPurchasable"] = true,
        ["Buy"] = 285
    },
    ["Stone"] = {
        ["Description"] = "Craftable ingredient. Used to create base buildings.",
        ["Origin"] = "Grassland",
        ["SetOriginFromNode"] = true,
        ["Image"] = "rbxthumb://type=Asset&id=8829243156&w=150&h=150",
        ["Name"] = "Stone",
        ["Category"] = "Resources",
        ["ItemType"] = "Resources",
        ["Sell"] = 1,
        ["Rarity"] = {
            ["Index"] = 1,
            ["Drops"] = {["DropChance"] = 12, ["Amount"] = 4},
            ["Fishing"] = {
                ["WaitTime"] = 10,
                ["RequiredSuccesses"] = {["Min"] = 4, ["Max"] = 5},
                ["DropChance"] = 55,
                ["SpinSpeed"] = {["Min"] = 200, ["Max"] = 300}
            },
            ["TextStrokeColor"] = Color3.fromRGB(89, 89, 89),
            ["Alchemy"] = {["DropChance"] = 30, ["ElixirRecyleAmount"] = 250},
            ["Auction"] = {["MinAmount"] = 1000},
            ["Name"] = "Common",
            ["BreedCost"] = {["MinAmount"] = 250},
            ["Bosses"] = {["Amount"] = 100},
            ["SpinnerWheel"] = {["DropChance"] = 50, ["Amount"] = 100},
            ["RecyleAccessory"] = true,
            ["TextColor"] = Color3.fromRGB(181, 181, 181)
        },
        ["Buy"] = 4
    },
    ["Petal"] = {
        ["Description"] = "Craftable ingredient. Used to create base buildings.",
        ["Origin"] = "Grassland",
        ["SetOriginFromNode"] = true,
        ["Image"] = "rbxthumb://type=Asset&id=8829241772&w=150&h=150",
        ["Name"] = "Petal",
        ["Category"] = "Resources",
        ["ItemType"] = "Resources",
        ["Sell"] = 5,
        ["Rarity"] = {
            ["Index"] = 2,
            ["Drops"] = {["DropChance"] = 6, ["Amount"] = 2},
            ["Fishing"] = {
                ["WaitTime"] = 10,
                ["RequiredSuccesses"] = {["Min"] = 5, ["Max"] = 6},
                ["DropChance"] = 30,
                ["SpinSpeed"] = {["Min"] = 250, ["Max"] = 350}
            },
            ["TextStrokeColor"] = Color3.fromRGB(52, 127, 23),
            ["Alchemy"] = {["DropChance"] = 30, ["ElixirRecyleAmount"] = 50},
            ["Auction"] = {["MinAmount"] = 5000},
            ["Name"] = "Uncommon",
            ["BreedCost"] = {["MinAmount"] = 700},
            ["Bosses"] = {["Amount"] = 100},
            ["SpinnerWheel"] = {["DropChance"] = 20, ["Amount"] = 50},
            ["RecyleAccessory"] = true,
            ["TextColor"] = Color3.fromRGB(82, 199, 36)
        },
        ["Buy"] = 20
    },
    ["LavaCrystal"] = {
        ["Description"] = "Craftable ingredient. Used to create base buildings.",
        ["Origin"] = "Volcano",
        ["SetOriginFromNode"] = true,
        ["Image"] = "rbxthumb://type=Asset&id=8829269110&w=150&h=150",
        ["Name"] = "LavaCrystal",
        ["Category"] = "Resources",
        ["ItemType"] = "Resources",
        ["Sell"] = 10,
        ["Rarity"] = {
            ["Index"] = 3,
            ["Drops"] = {["DropChance"] = 1, ["Amount"] = 1},
            ["Fishing"] = {
                ["SpinSpeed"] = {["Min"] = 300, ["Max"] = 400},
                ["AnnounceReward"] = false,
                ["WaitTime"] = 10,
                ["RequiredSuccesses"] = {["Min"] = 6, ["Max"] = 7},
                ["DropChance"] = 10
            },
            ["TextStrokeColor"] = Color3.fromRGB(17, 130, 175),
            ["Alchemy"] = {["DropChance"] = 3, ["ElixirRecyleAmount"] = 25},
            ["Auction"] = {["MinAmount"] = 10000},
            ["Name"] = "Rare",
            ["BreedCost"] = {["MinAmount"] = 1500},
            ["Bosses"] = {["Amount"] = 100},
            ["SpinnerWheel"] = {["DropChance"] = 10, ["Amount"] = 25},
            ["RecyleAccessory"] = true,
            ["TextColor"] = Color3.fromRGB(26, 183, 255)
        },
        ["Buy"] = 400
    },
    ["Quartz"] = {
        ["Description"] = "Craftable ingredient. Used to create base buildings.",
        ["Origin"] = "Jungle",
        ["SetOriginFromNode"] = true,
        ["Image"] = "rbxthumb://type=Asset&id=8829250000&w=150&h=150",
        ["Name"] = "Quartz",
        ["Category"] = "Resources",
        ["ItemType"] = "Resources",
        ["Sell"] = 10,
        ["Rarity"] = {
            ["Index"] = 3,
            ["Drops"] = {["DropChance"] = 1, ["Amount"] = 1},
            ["Fishing"] = {
                ["SpinSpeed"] = {["Min"] = 300, ["Max"] = 400},
                ["AnnounceReward"] = false,
                ["WaitTime"] = 10,
                ["RequiredSuccesses"] = {["Min"] = 6, ["Max"] = 7},
                ["DropChance"] = 10
            },
            ["TextStrokeColor"] = Color3.fromRGB(17, 130, 175),
            ["Alchemy"] = {["DropChance"] = 3, ["ElixirRecyleAmount"] = 25},
            ["Auction"] = {["MinAmount"] = 10000},
            ["Name"] = "Rare",
            ["BreedCost"] = {["MinAmount"] = 1500},
            ["Bosses"] = {["Amount"] = 100},
            ["SpinnerWheel"] = {["DropChance"] = 10, ["Amount"] = 25},
            ["RecyleAccessory"] = true,
            ["TextColor"] = Color3.fromRGB(26, 183, 255)
        },
        ["Buy"] = 300
    },
    ["SeaStar"] = {
        ["Description"] = "Craftable ingredient. Used to create base buildings.",
        ["Origin"] = "Ocean",
        ["SetOriginFromNode"] = true,
        ["Image"] = "rbxthumb://type=Asset&id=8829256484&w=150&h=150",
        ["Name"] = "SeaStar",
        ["Category"] = "Resources",
        ["ItemType"] = "Resources",
        ["Sell"] = 5,
        ["Rarity"] = {
            ["Index"] = 2,
            ["Drops"] = {["DropChance"] = 6, ["Amount"] = 2},
            ["Fishing"] = {
                ["WaitTime"] = 10,
                ["RequiredSuccesses"] = {["Min"] = 5, ["Max"] = 6},
                ["DropChance"] = 30,
                ["SpinSpeed"] = {["Min"] = 250, ["Max"] = 350}
            },
            ["TextStrokeColor"] = Color3.fromRGB(52, 127, 23),
            ["Alchemy"] = {["DropChance"] = 30, ["ElixirRecyleAmount"] = 50},
            ["Auction"] = {["MinAmount"] = 5000},
            ["Name"] = "Uncommon",
            ["BreedCost"] = {["MinAmount"] = 700},
            ["Bosses"] = {["Amount"] = 100},
            ["SpinnerWheel"] = {["DropChance"] = 20, ["Amount"] = 50},
            ["RecyleAccessory"] = true,
            ["TextColor"] = Color3.fromRGB(82, 199, 36)
        },
        ["Buy"] = 60
    }
}
