data = {
    ["GetPartOffset"] = "function: 0xb4f3516016329043",
    ["ItemSaveResolutionY"] = 0.05,
    ["GetChildItemWithProperty"] = "function: 0x0af1ae1bcea1e4c3",
    ["NormalizeAssetID"] = "function: 0x8600358608d1e443",
    ["SetTransparency"] = "function: 0x2b505868523f7183",
    ["GetSurfaceDistance"] = "function: 0xc1b6e9ce155ecc43",
    ["RoundVectorToSaveResolution"] = "function: 0x590ec927ac888b53",
    ["GetPlotItems"] = "function: 0x79fa94a129448a73",
    ["GetClosestAttachOrigin"] = "function: 0x9494cbf7a2a2f9c3",
    ["HookChildItemChanged"] = "function: 0x05a2170f56a2cd23",
    ["CheckUsed"] = "function: 0xb8d1da6b04323fa3",
    ["CanSetPicture"] = "function: 0x275c76ff12c8be33",
    ["GetItemHolder"] = "function: 0x63e9c8dcd404dc93",
    ["CheckMaxNestedObjects"] = "function: 0x162ccdc82f1be413",
    ["ItemHolderName"] = "ItemHolder",
    ["_materialData"] = {
        ["Wood"] = {["ID"] = 19, ["Name"] = "Wood", ["Main"] = 2393010987, ["Group"] = "Wood"},
        ["*TwistedWood"] = {
            ["Overlay"] = 319943200,
            ["Group"] = "Wood",
            ["Name"] = "*TwistedWood",
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "Plastic",
            ["TextureTransparency"] = 0.20000000298023224,
            ["ID"] = 62,
            ["TileY"] = 1.6,
            ["TileX"] = 1.6,
            ["Texture"] = "TwistedWood"
        },
        ["Roof Shingles"] = {
            ["IsVariant"] = true,
            ["Main"] = "SmoothPlastic",
            ["Group"] = "Pattern",
            ["Name"] = "Roof Shingles",
            ["ID"] = 122
        },
        ["*HerringboneWood"] = {
            ["Overlay"] = 2394473012,
            ["Group"] = "Wood",
            ["Name"] = "*HerringboneWood",
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "SmoothPlastic",
            ["TextureTransparency"] = 0,
            ["ID"] = 49,
            ["TileY"] = 1,
            ["TileX"] = 1,
            ["Texture"] = "HerringboneWood"
        },
        ["*OverlappingCircles"] = {
            ["Overlay"] = 3488680179,
            ["Group"] = "Pattern",
            ["Name"] = "*OverlappingCircles",
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "SmoothPlastic",
            ["TextureTransparency"] = 0.5,
            ["ID"] = 32,
            ["TileY"] = 0.2,
            ["TileX"] = 0.2,
            ["Texture"] = "OverlappingCircles"
        },
        ["*RainbowDots"] = {
            ["Overlay"] = 3488683546,
            ["Group"] = "Pattern",
            ["Name"] = "*RainbowDots",
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "SmoothPlastic",
            ["TextureTransparency"] = 0.30000001192092896,
            ["ID"] = 28,
            ["TileY"] = 2,
            ["TileX"] = 2,
            ["Texture"] = "RainbowDots"
        },
        ["SmallSquarePlaid"] = {
            ["IsVariant"] = true,
            ["Main"] = "Fabric",
            ["Group"] = "Fabric",
            ["Name"] = "SmallSquarePlaid",
            ["ID"] = 88
        },
        ["WideVerticalPlanks"] = {
            ["IsVariant"] = true,
            ["Main"] = "WoodPlanks",
            ["Group"] = "Wood",
            ["Name"] = "WideVerticalPlanks",
            ["ID"] = 118
        },
        ["Polished Vertical Woodplanks"] = {
            ["IsVariant"] = true,
            ["Main"] = "WoodPlanks",
            ["Group"] = "Regular",
            ["Name"] = "Polished Vertical Woodplanks",
            ["ID"] = 127
        },
        ["*ModernTrellis"] = {
            ["Overlay"] = 2413365316,
            ["Group"] = "Pattern",
            ["Name"] = "*ModernTrellis",
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "SmoothPlastic",
            ["TextureTransparency"] = 0,
            ["ID"] = 56,
            ["TileY"] = 0.4,
            ["TileX"] = 0.4,
            ["Texture"] = "ModernTrellis"
        },
        ["CorrodedMetal"] = {
            ["Overlay"] = 2393332137,
            ["Main"] = 2392991694,
            ["ID"] = 4,
            ["Name"] = "CorrodedMetal",
            ["Group"] = "Metal"
        },
        ["*PlanksLong"] = {
            ["Overlay"] = 201130786,
            ["Group"] = "Wood",
            ["Name"] = "*PlanksLong",
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "Wood",
            ["TextureTransparency"] = 0,
            ["ID"] = 39,
            ["TileY"] = 1.2,
            ["TileX"] = 1.2,
            ["Texture"] = "PlanksLong"
        },
        ["LargeLeaves"] = {
            ["IsVariant"] = true,
            ["Main"] = "Grass",
            ["Group"] = "Organic",
            ["Name"] = "LargeLeaves",
            ["ID"] = 86
        },
        ["*AsphaltShingles"] = {
            ["Overlay"] = 296397676,
            ["Group"] = "Roof",
            ["Name"] = "*AsphaltShingles",
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "Concrete",
            ["TextureTransparency"] = 0,
            ["ID"] = 65,
            ["TileY"] = 1,
            ["TileX"] = 1,
            ["Texture"] = "AsphaltShingles"
        },
        ["*StoneLines"] = {
            ["Overlay"] = 2393599467,
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "Plastic",
            ["Name"] = "*StoneLines",
            ["ID"] = 43,
            ["TextureTransparency"] = 0,
            ["Group"] = "Stone",
            ["Texture"] = "StoneLines"
        },
        ["OldWideVerticalPlanks"] = {
            ["IsVariant"] = true,
            ["Main"] = "WoodPlanks",
            ["Group"] = "Wood",
            ["Name"] = "OldWideVerticalPlanks",
            ["ID"] = 116
        },
        ["*Edge"] = {
            ["Overlay"] = 2413366646,
            ["Group"] = "Pattern",
            ["Name"] = "*Edge",
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "SmoothPlastic",
            ["TextureTransparency"] = 0,
            ["ID"] = 29,
            ["TileY"] = 0.6,
            ["TileX"] = 0.5,
            ["Texture"] = "Edge"
        },
        ["SmoothPlastic"] = {["ID"] = 16, ["Name"] = "SmoothPlastic", ["Main"] = 2393008845, ["Group"] = "Plastic"},
        ["OldWideHorizontalPlanks"] = {
            ["IsVariant"] = true,
            ["Main"] = "WoodPlanks",
            ["Group"] = "Wood",
            ["Name"] = "OldWideHorizontalPlanks",
            ["ID"] = 115
        },
        ["*ClassicTrellis"] = {
            ["Overlay"] = 2393600470,
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "SmoothPlastic",
            ["Name"] = "*ClassicTrellis",
            ["ID"] = 30,
            ["TextureTransparency"] = 0,
            ["Group"] = "Pattern",
            ["Texture"] = "ClassicTrellis"
        },
        ["*LargeBricks"] = {
            ["Overlay"] = 2413364829,
            ["Group"] = "Bricks",
            ["Name"] = "*LargeBricks",
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "Plastic",
            ["TextureTransparency"] = 0,
            ["ID"] = 44,
            ["TileY"] = 1,
            ["TileX"] = 1,
            ["Texture"] = "LargeBricks"
        },
        ["*MarbleBricks"] = {
            ["Overlay"] = 27690789,
            ["Group"] = "Bricks",
            ["Name"] = "*MarbleBricks",
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "Marble",
            ["TextureTransparency"] = 0,
            ["ID"] = 41,
            ["TileY"] = 0.24000000953674316,
            ["TileX"] = 0.24000000953674316,
            ["Texture"] = "MarbleBricks"
        },
        ["*Leather"] = {
            ["Overlay"] = 4560039288,
            ["Group"] = "Organic",
            ["Name"] = "*Leather",
            ["TextureColor"] = Color3.fromRGB(32, 32, 34),
            ["Main"] = "Plastic",
            ["TextureTransparency"] = 0.6499999761581421,
            ["ID"] = 82,
            ["TileY"] = 0.2200000047683716,
            ["TileX"] = 0.2200000047683716,
            ["Texture"] = "Leather"
        },
        ["*DiagonalStripes"] = {
            ["Overlay"] = 2393602213,
            ["Group"] = "Stripes",
            ["Name"] = "*DiagonalStripes",
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "Plastic",
            ["TextureTransparency"] = 0,
            ["ID"] = 20,
            ["TileY"] = 0.8,
            ["TileX"] = 0.8,
            ["Texture"] = "DiagonalStripes"
        },
        ["Vertical Painted Wood Panels"] = {
            ["IsVariant"] = true,
            ["Main"] = "WoodPlanks",
            ["Group"] = "Regular",
            ["Name"] = "Vertical Painted Wood Panels",
            ["ID"] = 129
        },
        ["*GroovyLines"] = {
            ["Overlay"] = 2394809465,
            ["Group"] = "Pattern",
            ["Name"] = "*GroovyLines",
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "Plastic",
            ["TextureTransparency"] = 0,
            ["ID"] = 51,
            ["TileY"] = 1.2,
            ["TileX"] = 0.6,
            ["Texture"] = "GroovyLines"
        },
        ["*DetailedTiles"] = {
            ["Overlay"] = 232876941,
            ["Group"] = "Tiles",
            ["Name"] = "*DetailedTiles",
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "Sand",
            ["TextureTransparency"] = 0,
            ["ID"] = 63,
            ["TileY"] = 1,
            ["TileX"] = 1,
            ["Texture"] = "DetailedTiles"
        },
        ["*HerringboneTiles"] = {
            ["Overlay"] = 319942905,
            ["Group"] = "Wood",
            ["Name"] = "*HerringboneTiles",
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "Concrete",
            ["TextureTransparency"] = 0,
            ["ID"] = 59,
            ["TileY"] = 1.2,
            ["TileX"] = 1.2,
            ["Texture"] = "HerringboneTiles"
        },
        ["Granite"] = {["ID"] = 8, ["Name"] = "Granite", ["Main"] = 2393007187, ["Group"] = "Stone"},
        ["*Bark"] = {
            ["Overlay"] = 321649055,
            ["Group"] = "Wood",
            ["Name"] = "*Bark",
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "Wood",
            ["TextureTransparency"] = 0.4000000059604645,
            ["ID"] = 71,
            ["TileY"] = 0.6,
            ["TileX"] = 0.4,
            ["Texture"] = "Bark"
        },
        ["*SquareTiles"] = {
            ["Overlay"] = 2393597816,
            ["Group"] = "Tiles",
            ["Name"] = "*SquareTiles",
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "Wood",
            ["TextureTransparency"] = 0,
            ["ID"] = 36,
            ["TileY"] = 1.6,
            ["TileX"] = 1.6,
            ["Texture"] = "SquareTiles"
        },
        ["Polished Horizontal Woodplanks"] = {
            ["IsVariant"] = true,
            ["Main"] = "WoodPlanks",
            ["Group"] = "Regular",
            ["Name"] = "Polished Horizontal Woodplanks",
            ["ID"] = 126
        },
        ["WoodDeckTiles"] = {
            ["IsVariant"] = true,
            ["Main"] = "Wood",
            ["Group"] = "Wood",
            ["Name"] = "WoodDeckTiles",
            ["ID"] = 95
        },
        ["LargeSnowflakes"] = {
            ["IsVariant"] = true,
            ["Main"] = "SmoothPlastic",
            ["Name"] = "LargeSnowflakes",
            ["Group"] = "Pattern",
            ["_isSpecial"] = true,
            ["ID"] = 103,
            ["Seasonal"] = "Winter"
        },
        ["LushGrass"] = {
            ["IsVariant"] = true,
            ["Main"] = "Grass",
            ["Group"] = "Organic",
            ["Name"] = "LushGrass",
            ["ID"] = 100
        },
        ["Sand"] = {["ID"] = 17, ["Name"] = "Sand", ["Main"] = 2393009347, ["Group"] = "Organic"},
        ["*RectangularTile"] = {
            ["Overlay"] = 4553851308,
            ["Group"] = "Tiles",
            ["Name"] = "*RectangularTile",
            ["TextureColor"] = Color3.fromRGB(139, 137, 137),
            ["Main"] = "SmoothPlastic",
            ["TextureTransparency"] = 0.4000000059604645,
            ["ID"] = 79,
            ["TileY"] = 1,
            ["TileX"] = 1,
            ["Texture"] = "RectangularTile"
        },
        ["*HorizontalPlanks"] = {
            ["Overlay"] = 2394604692,
            ["Group"] = "Wood",
            ["Name"] = "*HorizontalPlanks",
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "Wood",
            ["TextureTransparency"] = 0,
            ["ID"] = 50,
            ["TileY"] = 0.12000000476837158,
            ["TileX"] = 20,
            ["Texture"] = "HorizontalPlanks"
        },
        ["*DoubleBricks"] = {
            ["Overlay"] = 113031256,
            ["Group"] = "Bricks",
            ["Name"] = "*DoubleBricks",
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "Concrete",
            ["TextureTransparency"] = 0,
            ["ID"] = 68,
            ["TileY"] = 0.6,
            ["TileX"] = 0.6,
            ["Texture"] = "DoubleBricks"
        },
        ["SmallFlowers"] = {
            ["IsVariant"] = true,
            ["Main"] = "Grass",
            ["Group"] = "Organic",
            ["Name"] = "SmallFlowers",
            ["ID"] = 91
        },
        ["MowedGrassPattern"] = {
            ["IsVariant"] = true,
            ["Main"] = "Grass",
            ["Group"] = "Organic",
            ["Name"] = "MowedGrassPattern",
            ["ID"] = 93
        },
        ["OverlappingPanels"] = {
            ["IsVariant"] = true,
            ["Main"] = "SmoothPlastic",
            ["Group"] = "Regular",
            ["Name"] = "OverlappingPanels",
            ["ID"] = 125
        },
        ["SmallSnowflakes"] = {
            ["IsVariant"] = true,
            ["Main"] = "SmoothPlastic",
            ["Name"] = "SmallSnowflakes",
            ["Group"] = "Pattern",
            ["_isSpecial"] = true,
            ["ID"] = 102,
            ["Seasonal"] = "Winter"
        },
        ["*Logs"] = {
            ["Overlay"] = 186405689,
            ["Group"] = "Wood",
            ["Name"] = "*Logs",
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "Wood",
            ["TextureTransparency"] = 0.5,
            ["ID"] = 45,
            ["TileY"] = 1,
            ["TileX"] = 1,
            ["Texture"] = "Logs"
        },
        ["Sequins"] = {
            ["IsVariant"] = true,
            ["Main"] = "Metal",
            ["Group"] = "Organic",
            ["Name"] = "Sequins",
            ["ID"] = 108
        },
        ["*SmallRoundedTiles"] = {
            ["Overlay"] = 2413366364,
            ["Group"] = "Tiles",
            ["Name"] = "*SmallRoundedTiles",
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "SmoothPlastic",
            ["TextureTransparency"] = 0,
            ["ID"] = 24,
            ["TileY"] = 1,
            ["TileX"] = 1,
            ["Texture"] = "SmallRoundedTiles"
        },
        ["*PolkaDots"] = {
            ["Overlay"] = 6126950144,
            ["Group"] = "Pattern",
            ["Name"] = "*PolkaDots",
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "SmoothPlastic",
            ["TextureTransparency"] = 0,
            ["ID"] = 83,
            ["TileY"] = 0.3200000047683716,
            ["TileX"] = 0.3200000047683716,
            ["Texture"] = "PolkaDots"
        },
        ["Pebble"] = {["ID"] = 13, ["Name"] = "Pebble", ["Main"] = 2393008438, ["Group"] = "Stone"},
        ["Ice"] = {["ID"] = 10, ["Name"] = "Ice", ["Main"] = 2393007663, ["Group"] = "Organic"},
        ["*VerticalStripes"] = {
            ["Overlay"] = 2393599082,
            ["Group"] = "Stripes",
            ["Name"] = "*VerticalStripes",
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "Plastic",
            ["TextureTransparency"] = 0,
            ["ID"] = 21,
            ["TileY"] = 20,
            ["TileX"] = 0.1799999952316284,
            ["Texture"] = "VerticalStripes"
        },
        ["VerticalPlanks"] = {
            ["IsVariant"] = true,
            ["Main"] = "WoodPlanks",
            ["Group"] = "Wood",
            ["Name"] = "VerticalPlanks",
            ["ID"] = 97
        },
        ["FloralStems"] = {
            ["IsVariant"] = true,
            ["Main"] = "Plastic",
            ["Group"] = "Pattern",
            ["Name"] = "FloralStems",
            ["ID"] = 114
        },
        ["Brick"] = {["ID"] = 1, ["Name"] = "Brick", ["Main"] = 2392990461, ["Group"] = "Bricks"},
        ["*RoofTiles"] = {
            ["Overlay"] = 126342209,
            ["Group"] = "Roof",
            ["Name"] = "*RoofTiles",
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "Concrete",
            ["TextureTransparency"] = 0,
            ["ID"] = 48,
            ["TileY"] = 1,
            ["TileX"] = 1,
            ["Texture"] = "RoofTiles"
        },
        ["*Giraffe"] = {
            ["Overlay"] = 988383812,
            ["Group"] = "Pattern",
            ["Name"] = "*Giraffe",
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "SmoothPlastic",
            ["TextureTransparency"] = 0,
            ["ID"] = 34,
            ["TileY"] = 0.8,
            ["TileX"] = 0.8,
            ["Texture"] = "Giraffe"
        },
        ["*Swirls"] = {
            ["Overlay"] = 3488681554,
            ["Group"] = "Pattern",
            ["Name"] = "*Swirls",
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "SmoothPlastic",
            ["TextureTransparency"] = 0.8500000238418579,
            ["ID"] = 26,
            ["TileY"] = 1,
            ["TileX"] = 1,
            ["Texture"] = "Swirls"
        },
        ["*CheckeredTiles"] = {
            ["Overlay"] = 2408844496,
            ["Group"] = "Tiles",
            ["Name"] = "*CheckeredTiles",
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "SmoothPlastic",
            ["TextureTransparency"] = 0,
            ["ID"] = 54,
            ["TileY"] = 0.5,
            ["TileX"] = 0.5,
            ["Texture"] = "CheckeredTiles"
        },
        ["*Hexagon"] = {
            ["Overlay"] = 2393601441,
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "SmoothPlastic",
            ["Name"] = "*Hexagon",
            ["ID"] = 31,
            ["TextureTransparency"] = 0,
            ["Group"] = "Pattern",
            ["Texture"] = "Hexagon"
        },
        ["*ClassicCarpet"] = {
            ["Overlay"] = 4553320029,
            ["Group"] = "Fabric",
            ["Name"] = "*ClassicCarpet",
            ["TextureColor"] = Color3.fromRGB(163, 162, 165),
            ["Main"] = "Plastic",
            ["TextureTransparency"] = 0,
            ["ID"] = 77,
            ["TileY"] = 0.7,
            ["TileX"] = 0.7,
            ["Texture"] = "ClassicCarpet"
        },
        ["RubberInterlockingTiles"] = {
            ["IsVariant"] = true,
            ["Main"] = "Plastic",
            ["Group"] = "Tiles",
            ["Name"] = "RubberInterlockingTiles",
            ["ID"] = 98
        },
        ["*GroutlessBricks"] = {
            ["Overlay"] = 187626500,
            ["Group"] = "Bricks",
            ["Name"] = "*GroutlessBricks",
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "Concrete",
            ["TextureTransparency"] = 0,
            ["ID"] = 47,
            ["TileY"] = 1.6,
            ["TileX"] = 1.6,
            ["Texture"] = "GroutlessBricks"
        },
        ["*LargeMosaicTiles"] = {
            ["Overlay"] = 2408843501,
            ["Group"] = "Tiles",
            ["Name"] = "*LargeMosaicTiles",
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "SmoothPlastic",
            ["TextureTransparency"] = 0,
            ["ID"] = 38,
            ["TileY"] = 0.5,
            ["TileX"] = 0.5,
            ["Texture"] = "LargeMosaicTiles"
        },
        ["*RoughStoneBricks"] = {
            ["Overlay"] = 319942978,
            ["Group"] = "Bricks",
            ["Name"] = "*RoughStoneBricks",
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "Concrete",
            ["TextureTransparency"] = 0,
            ["ID"] = 46,
            ["TileY"] = 1.6,
            ["TileX"] = 1.6,
            ["Texture"] = "RoughStoneBricks"
        },
        ["Marble"] = {["ID"] = 11, ["Name"] = "Marble", ["Main"] = 2393007864, ["Group"] = "Stone"},
        ["*UnevenStains"] = {
            ["Overlay"] = 3488686014,
            ["Group"] = "Pattern",
            ["Name"] = "*UnevenStains",
            ["TextureColor"] = Color3.fromRGB(0, 0, 0),
            ["Main"] = "Sand",
            ["TextureTransparency"] = 0.30000001192092896,
            ["ID"] = 74,
            ["TileY"] = 1.2,
            ["TileX"] = 1.2,
            ["Texture"] = "UnevenStains"
        },
        ["Confetti"] = {
            ["IsVariant"] = true,
            ["Main"] = "SmoothPlastic",
            ["Group"] = "Pattern",
            ["Name"] = "Confetti",
            ["ID"] = 106
        },
        ["*MetalRoof"] = {
            ["Overlay"] = 296397709,
            ["Group"] = "Roof",
            ["Name"] = "*MetalRoof",
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "Metal",
            ["TextureTransparency"] = 0,
            ["ID"] = 66,
            ["TileY"] = 1.5,
            ["TileX"] = 1.5,
            ["Texture"] = "MetalRoof"
        },
        ["HalfCircle"] = {
            ["IsVariant"] = true,
            ["Main"] = "Plastic",
            ["Group"] = "Pattern",
            ["Name"] = "HalfCircle",
            ["ID"] = 112
        },
        ["*Zebra"] = {
            ["Overlay"] = 2393598705,
            ["Group"] = "Pattern",
            ["Name"] = "*Zebra",
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "Plastic",
            ["TextureTransparency"] = 0,
            ["ID"] = 23,
            ["TileY"] = 1.6,
            ["TileX"] = 1.6,
            ["Texture"] = "Zebra"
        },
        ["*SmoothPebble"] = {
            ["Overlay"] = 319942918,
            ["Group"] = "Stone",
            ["Name"] = "*SmoothPebble",
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "Plastic",
            ["TextureTransparency"] = 0,
            ["ID"] = 57,
            ["TileY"] = 0.8,
            ["TileX"] = 0.8,
            ["Texture"] = "SmoothPebble"
        },
        ["*DiamondTiles"] = {
            ["Overlay"] = 410627688,
            ["Group"] = "Tiles",
            ["Name"] = "*DiamondTiles",
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "Concrete",
            ["TextureTransparency"] = 0,
            ["ID"] = 60,
            ["TileY"] = 1.2,
            ["TileX"] = 1.2,
            ["Texture"] = "DiamondTiles"
        },
        ["Concrete"] = {["ID"] = 3, ["Name"] = "Concrete", ["Main"] = 2392991225, ["Group"] = "Stone"},
        ["LargeHearts"] = {
            ["IsVariant"] = true,
            ["Main"] = "SmoothPlastic",
            ["Name"] = "LargeHearts",
            ["Group"] = "Pattern",
            ["_isSpecial"] = true,
            ["ID"] = 111,
            ["Seasonal"] = "Valentines"
        },
        ["Fabric"] = {["ID"] = 6, ["Name"] = "Fabric", ["Main"] = 2393006282, ["Group"] = "Fabric"},
        ["*Birds"] = {
            ["Overlay"] = 3488686583,
            ["Group"] = "Pattern",
            ["Name"] = "*Birds",
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "Plastic",
            ["TextureTransparency"] = 0.10000000149011612,
            ["ID"] = 35,
            ["TileY"] = 0.8,
            ["TileX"] = 0.8,
            ["Texture"] = "Birds"
        },
        ["*WaterCaustics"] = {
            ["Overlay"] = 9858782361,
            ["Group"] = "Pattern",
            ["Name"] = "*WaterCaustics",
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "Plastic",
            ["TextureTransparency"] = 0,
            ["ID"] = 84,
            ["TileY"] = 1.2,
            ["TileX"] = 1.2,
            ["Texture"] = "WaterCaustics"
        },
        ["VerticalWoodLogs"] = {
            ["IsVariant"] = true,
            ["Main"] = "Plastic",
            ["Group"] = "Wood",
            ["Name"] = "VerticalWoodLogs",
            ["ID"] = 104
        },
        ["*RoughBricks"] = {
            ["Overlay"] = 27899086,
            ["Group"] = "Bricks",
            ["Name"] = "*RoughBricks",
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "Slate",
            ["TextureTransparency"] = 0,
            ["ID"] = 40,
            ["TileY"] = 0.8,
            ["TileX"] = 0.8,
            ["Texture"] = "RoughBricks"
        },
        ["*Wicker"] = {
            ["Overlay"] = 10093857374,
            ["Group"] = "Pattern",
            ["Name"] = "*Wicker",
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "Plastic",
            ["TextureTransparency"] = 0,
            ["ID"] = 85,
            ["TileY"] = 0.3,
            ["TileX"] = 0.2,
            ["Texture"] = "Wicker"
        },
        ["*UnevenVerticalStripes"] = {
            ["Overlay"] = 2408843191,
            ["Group"] = "Stripes",
            ["Name"] = "*UnevenVerticalStripes",
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "Plastic",
            ["TextureTransparency"] = 0,
            ["ID"] = 22,
            ["TileY"] = 2,
            ["TileX"] = 0.5,
            ["Texture"] = "UnevenVerticalStripes"
        },
        ["Foil"] = {["ID"] = 7, ["Name"] = "Foil", ["Main"] = 2393006903, ["Group"] = "Metal"},
        ["Cobblestone"] = {["ID"] = 2, ["Name"] = "Cobblestone", ["Main"] = 2392990850, ["Group"] = "Stone"},
        ["Slate"] = {["ID"] = 18, ["Name"] = "Slate", ["Main"] = 2393010383, ["Group"] = "Stone"},
        ["*BigPlaid"] = {
            ["Overlay"] = 17586283155,
            ["Group"] = "Fabric",
            ["Name"] = "*BigPlaid",
            ["_isNew"] = true,
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "Plastic",
            ["TextureTransparency"] = 0,
            ["ID"] = 130,
            ["TileY"] = 0.4,
            ["TileX"] = 0.4,
            ["Texture"] = "BigPlaid"
        },
        ["DirtStains"] = {
            ["IsVariant"] = true,
            ["Main"] = "Plastic",
            ["Group"] = "Pattern",
            ["Name"] = "DirtStains",
            ["ID"] = 121
        },
        ["WoodPlanks"] = {["ID"] = 14, ["Name"] = "WoodPlanks", ["Main"] = 2393008630, ["Group"] = "Wood"},
        ["Corrugated Vertical Metal"] = {
            ["IsVariant"] = true,
            ["Main"] = "Metal",
            ["Group"] = "Regular",
            ["Name"] = "Corrugated Vertical Metal",
            ["ID"] = 124
        },
        ["Plastic"] = {["ID"] = 15, ["Name"] = "Plastic", ["Main"] = 2393008845, ["Group"] = "Plastic"},
        ["*Puzzle"] = {
            ["Overlay"] = 3488678381,
            ["Group"] = "Pattern",
            ["Name"] = "*Puzzle",
            ["TextureColor"] = Color3.fromRGB(0, 0, 0),
            ["Main"] = "Plastic",
            ["TextureTransparency"] = 0.20000000298023224,
            ["ID"] = 25,
            ["TileY"] = 0.8,
            ["TileX"] = 0.8,
            ["Texture"] = "Puzzle"
        },
        ["*IrregularStone"] = {
            ["Overlay"] = 319942978,
            ["Group"] = "Bricks",
            ["Name"] = "*IrregularStone",
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "Metal",
            ["TextureTransparency"] = 0,
            ["ID"] = 69,
            ["TileY"] = 0.8,
            ["TileX"] = 0.8,
            ["Texture"] = "IrregularStone"
        },
        ["*Plaster"] = {
            ["Overlay"] = 321649619,
            ["Group"] = "Stone",
            ["Name"] = "*Plaster",
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "SmoothPlastic",
            ["TextureTransparency"] = 0.20000000298023224,
            ["ID"] = 70,
            ["TileY"] = 1.2,
            ["TileX"] = 1.2,
            ["Texture"] = "Plaster"
        },
        ["Corrugated Horizontal Metal"] = {
            ["IsVariant"] = true,
            ["Main"] = "Metal",
            ["Group"] = "Regular",
            ["Name"] = "Corrugated Horizontal Metal",
            ["ID"] = 123
        },
        ["Painted Brickwall"] = {
            ["IsVariant"] = true,
            ["Main"] = "Brick",
            ["Group"] = "Regular",
            ["Name"] = "Painted Brickwall",
            ["ID"] = 128
        },
        ["StainedUnevenStripes"] = {
            ["IsVariant"] = true,
            ["Main"] = "Plastic",
            ["Group"] = "Regular",
            ["Name"] = "StainedUnevenStripes",
            ["ID"] = 120
        },
        ["BrokenTiles"] = {
            ["IsVariant"] = true,
            ["Main"] = "Plastic",
            ["Group"] = "Tiles",
            ["Name"] = "BrokenTiles",
            ["ID"] = 119
        },
        ["*CozyFabric"] = {
            ["Overlay"] = 321324826,
            ["Group"] = "Fabric",
            ["Name"] = "*CozyFabric",
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "Sand",
            ["TextureTransparency"] = 0,
            ["ID"] = 42,
            ["TileY"] = 0.6,
            ["TileX"] = 0.6,
            ["Texture"] = "CozyFabric"
        },
        ["RoundedRectangles"] = {
            ["IsVariant"] = true,
            ["Main"] = "Plastic",
            ["Group"] = "Pattern",
            ["Name"] = "RoundedRectangles",
            ["ID"] = 113
        },
        ["*DottedTiles"] = {
            ["Overlay"] = 321533803,
            ["Group"] = "Tiles",
            ["Name"] = "*DottedTiles",
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "Sand",
            ["TextureTransparency"] = 0,
            ["ID"] = 58,
            ["TileY"] = 0.8,
            ["TileX"] = 0.8,
            ["Texture"] = "DottedTiles"
        },
        ["Grass"] = {["ID"] = 9, ["Name"] = "Grass", ["Main"] = 2393007415, ["Group"] = "Organic"},
        ["SmallHearts"] = {
            ["IsVariant"] = true,
            ["Main"] = "SmoothPlastic",
            ["Name"] = "SmallHearts",
            ["Group"] = "Pattern",
            ["_isSpecial"] = true,
            ["ID"] = 110,
            ["Seasonal"] = "Valentines"
        },
        ["*SubwayTile"] = {
            ["Overlay"] = 4553740452,
            ["Group"] = "Tiles",
            ["Name"] = "*SubwayTile",
            ["TextureColor"] = Color3.fromRGB(163, 162, 165),
            ["Main"] = "SmoothPlastic",
            ["TextureTransparency"] = 0.30000001192092896,
            ["ID"] = 78,
            ["TileY"] = 0.25,
            ["TileX"] = 0.25,
            ["Texture"] = "SubwayTile"
        },
        ["PartyCubes"] = {
            ["IsVariant"] = true,
            ["Main"] = "Metal",
            ["Group"] = "Regular",
            ["Name"] = "PartyCubes",
            ["ID"] = 107
        },
        ["HorizontalWoodLogs"] = {
            ["IsVariant"] = true,
            ["Main"] = "Plastic",
            ["Group"] = "Wood",
            ["Name"] = "HorizontalWoodLogs",
            ["ID"] = 105
        },
        ["IceBlocks"] = {
            ["IsVariant"] = true,
            ["Main"] = "SmoothPlastic",
            ["Group"] = "Organic",
            ["Name"] = "IceBlocks",
            ["ID"] = 101
        },
        ["*DiagonalBorderedMarble"] = {
            ["Overlay"] = 4559845323,
            ["Group"] = "Tiles",
            ["Name"] = "*DiagonalBorderedMarble",
            ["TextureColor"] = Color3.fromRGB(163, 162, 165),
            ["Main"] = "Marble",
            ["TextureTransparency"] = 0.20000000298023224,
            ["ID"] = 81,
            ["TileY"] = 1,
            ["TileX"] = 1,
            ["Texture"] = "DiagonalBorderedMarble"
        },
        ["SpeckledRubber"] = {
            ["IsVariant"] = true,
            ["Main"] = "Plastic",
            ["Group"] = "Tiles",
            ["Name"] = "SpeckledRubber",
            ["ID"] = 99
        },
        ["WoodGrain"] = {
            ["IsVariant"] = true,
            ["Main"] = "Wood",
            ["Group"] = "Wood",
            ["Name"] = "WoodGrain",
            ["ID"] = 96
        },
        ["CircularStone"] = {
            ["IsVariant"] = true,
            ["Main"] = "Brick",
            ["Group"] = "Tiles",
            ["Name"] = "CircularStone",
            ["ID"] = 94
        },
        ["MowedGrassLines"] = {
            ["IsVariant"] = true,
            ["Main"] = "Grass",
            ["Group"] = "Organic",
            ["Name"] = "MowedGrassLines",
            ["ID"] = 92
        },
        ["LargeFlowers"] = {
            ["IsVariant"] = true,
            ["Main"] = "Grass",
            ["Group"] = "Organic",
            ["Name"] = "LargeFlowers",
            ["ID"] = 90
        },
        ["HerringboneBrickPavers"] = {
            ["IsVariant"] = true,
            ["Main"] = "Brick",
            ["Group"] = "Tiles",
            ["Name"] = "HerringboneBrickPavers",
            ["ID"] = 89
        },
        ["SmallLeaves"] = {
            ["IsVariant"] = true,
            ["Main"] = "Grass",
            ["Group"] = "Organic",
            ["Name"] = "SmallLeaves",
            ["ID"] = 87
        },
        ["*LinearCarpetTiles"] = {
            ["Overlay"] = 4559890170,
            ["Group"] = "Fabric",
            ["Name"] = "*LinearCarpetTiles",
            ["TextureColor"] = Color3.fromRGB(163, 162, 165),
            ["Main"] = "Plastic",
            ["TextureTransparency"] = 0.30000001192092896,
            ["ID"] = 80,
            ["TileY"] = 1,
            ["TileX"] = 1,
            ["Texture"] = "LinearCarpetTiles"
        },
        ["Snow"] = {["IsVariant"] = true, ["Main"] = "Grass", ["Group"] = "Organic", ["Name"] = "Snow", ["ID"] = 109},
        ["*Plaid"] = {
            ["Overlay"] = 4034007400,
            ["Group"] = "Fabric",
            ["Name"] = "*Plaid",
            ["TextureColor"] = Color3.fromRGB(190, 190, 190),
            ["Main"] = "Plastic",
            ["TextureTransparency"] = 0,
            ["ID"] = 76,
            ["TileY"] = 0.4,
            ["TileX"] = 0.4,
            ["Texture"] = "Plaid"
        },
        ["*FuturisticPattern"] = {
            ["Overlay"] = 230235743,
            ["Group"] = "Pattern",
            ["Name"] = "*FuturisticPattern",
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "SmoothPlastic",
            ["TextureTransparency"] = 0,
            ["ID"] = 61,
            ["TileY"] = 0.8,
            ["TileX"] = 0.8,
            ["Texture"] = "FuturisticPattern"
        },
        ["*JungleLeaves"] = {
            ["Overlay"] = 3488687401,
            ["Group"] = "Pattern",
            ["Name"] = "*JungleLeaves",
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "Sand",
            ["TextureTransparency"] = 0.30000001192092896,
            ["ID"] = 73,
            ["TileY"] = 1.2,
            ["TileX"] = 1.4,
            ["Texture"] = "JungleLeaves"
        },
        ["*TiltedTiles"] = {
            ["Overlay"] = 321533772,
            ["Group"] = "Tiles",
            ["Name"] = "*TiltedTiles",
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "Metal",
            ["TextureTransparency"] = 0.20000000298023224,
            ["ID"] = 72,
            ["TileY"] = 0.6,
            ["TileX"] = 0.6,
            ["Texture"] = "TiltedTiles"
        },
        ["WideHorizontalPlanks"] = {
            ["IsVariant"] = true,
            ["Main"] = "Wood",
            ["Group"] = "Wood",
            ["Name"] = "WideHorizontalPlanks",
            ["ID"] = 117
        },
        ["*WoodTiles"] = {
            ["Overlay"] = 319943215,
            ["Group"] = "Wood",
            ["Name"] = "*WoodTiles",
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "Wood",
            ["TextureTransparency"] = 0,
            ["ID"] = 37,
            ["TileY"] = 1.6,
            ["TileX"] = 1.6,
            ["Texture"] = "WoodTiles"
        },
        ["*Plywood"] = {
            ["Overlay"] = 230540127,
            ["Group"] = "Wood",
            ["Name"] = "*Plywood",
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "SmoothPlastic",
            ["TextureTransparency"] = 0,
            ["ID"] = 64,
            ["TileY"] = 1,
            ["TileX"] = 1,
            ["Texture"] = "Plywood"
        },
        ["*AcousticalCeilingTiles"] = {
            ["Overlay"] = 3488687906,
            ["Group"] = "Tiles",
            ["Name"] = "*AcousticalCeilingTiles",
            ["TextureColor"] = Color3.fromRGB(140, 162, 181),
            ["Main"] = "Plastic",
            ["TextureTransparency"] = 0.20000000298023224,
            ["ID"] = 75,
            ["TileY"] = 1,
            ["TileX"] = 1,
            ["Texture"] = "AcousticalCeilingTiles"
        },
        ["*Bubbles"] = {
            ["Overlay"] = 2409875152,
            ["Group"] = "Pattern",
            ["Name"] = "*Bubbles",
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "Plastic",
            ["TextureTransparency"] = 0,
            ["ID"] = 55,
            ["TileY"] = 1.2,
            ["TileX"] = 1.2,
            ["Texture"] = "Bubbles"
        },
        ["*ZigZag"] = {
            ["Overlay"] = 2408841599,
            ["Group"] = "Pattern",
            ["Name"] = "*ZigZag",
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "Plastic",
            ["TextureTransparency"] = 0,
            ["ID"] = 53,
            ["TileY"] = 0.4,
            ["TileX"] = 0.5,
            ["Texture"] = "ZigZag"
        },
        ["*Camo"] = {
            ["Overlay"] = 2394914255,
            ["Group"] = "Pattern",
            ["Name"] = "*Camo",
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "Plastic",
            ["TextureTransparency"] = 0,
            ["ID"] = 52,
            ["TileY"] = 1.6,
            ["TileX"] = 1.6,
            ["Texture"] = "Camo"
        },
        ["*SymmetricalBricks"] = {
            ["Overlay"] = 410628125,
            ["Group"] = "Bricks",
            ["Name"] = "*SymmetricalBricks",
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "Concrete",
            ["TextureTransparency"] = 0,
            ["ID"] = 67,
            ["TileY"] = 1.6,
            ["TileX"] = 1.6,
            ["Texture"] = "SymmetricalBricks"
        },
        ["*ColorfulCubes"] = {
            ["Overlay"] = 3488680804,
            ["Group"] = "Pattern",
            ["Name"] = "*ColorfulCubes",
            ["TextureColor"] = Color3.fromRGB(255, 255, 255),
            ["Main"] = "SmoothPlastic",
            ["TextureTransparency"] = 0.5,
            ["ID"] = 27,
            ["TileY"] = 1.2,
            ["TileX"] = 1.2,
            ["Texture"] = "ColorfulCubes"
        },
        ["*Elephants"] = {
            ["Overlay"] = 3488684485,
            ["Group"] = "Pattern",
            ["Name"] = "*Elephants",
            ["TextureColor"] = Color3.fromRGB(0, 0, 0),
            ["Main"] = "Plastic",
            ["TextureTransparency"] = 0.5,
            ["ID"] = 33,
            ["TileY"] = 1.2,
            ["TileX"] = 1.2,
            ["Texture"] = "Elephants"
        },
        ["DiamondPlate"] = {["ID"] = 5, ["Name"] = "DiamondPlate", ["Main"] = 2393005984, ["Group"] = "Metal"},
        ["Metal"] = {["ID"] = 12, ["Name"] = "Metal", ["Main"] = 2393008224, ["Group"] = "Metal"}
    },
    ["GetPartOffsets"] = "function: 0x44da51d090364e83",
    ["HideModel"] = "function: 0xc6b3b1451e4d31f3",
    ["MarkUsed"] = "function: 0x576bf2ba8c55e4a3",
    ["GetNestedObjectsLevel"] = "function: 0x3192fc3ce37b5703",
    ["RoundToSaveResolution"] = "function: 0x52e13891ffefb7a3",
    ["GetChildItem"] = "function: 0xe801e940ca6ebb63",
    ["GetChildItems"] = "function: 0x329919ad404157b3",
    ["MarkGrounded"] = "function: 0x986ca709be0ecec3",
    ["GetHideModel"] = "function: 0x86ce20cf6b897d03",
    ["CheckGrounded"] = "function: 0x75314ca56c9ecae3",
    ["SetPicture"] = "function: 0xf63bb385b79a9b43",
    ["ToggleObjectTags"] = "function: 0x5783de2a02bd7853",
    ["SetObjectCFrame"] = "function: 0xb5bee1e0a67c2723",
    ["GetPlotObjectTag"] = "function: 0x86ab0d24bf1d3463",
    ["GetPoolContent"] = "function: 0x64c495659d2b11e3",
    ["ItemSaveResolutionRot"] = 4.5,
    ["IsPoolFull"] = "function: 0xf668e45ce0a4ae83",
    ["ItemPlacementResolution"] = 0.25,
    ["GetAllChildItems"] = "function: 0x044a7b79d38111d3",
    ["ToggleEffects"] = "function: 0x91fa365d45e97283",
    ["SetModelTransparency"] = "function: 0xfc38880ba8c7e2f3",
    ["ItemSaveResolutionXZ"] = 0.125
}
