data = {
    ["GameRules"] = {
        ["CombatLog"] = {},
        ["Config"] = {
            ["InjuredDamage"] = 45,
            ["AgeRestrictEnabled"] = true,
            ["RunWalkSpeed"] = 24,
            ["CoreGuiPlayerList"] = true,
            ["ProneWalksSpeed"] = 3,
            ["JumpCoolDown"] = 0.7,
            ["BloodMult"] = 1.75,
            ["TeamTags"] = false,
            ["EnableFallDamage"] = true,
            ["EnableHunger"] = false,
            ["HeavyMult"] = 0.75,
            ["InjuredWalksSpeed"] = 8,
            ["EnableRagdoll"] = true,
            ["DamageMult"] = 1,
            ["TopBarTransparency"] = 1,
            ["Version"] = "ACS 2.0.1 - R6",
            ["CrouchWalkSpeed"] = 6,
            ["Blacklist"] = {},
            ["EnableMedSys"] = false,
            ["EnableStatusUI"] = false,
            ["WaterMark"] = false,
            ["InjuredCrouchWalkSpeed"] = 4,
            ["VehicleMaxZoom"] = 150,
            ["AntiBunnyHop"] = true,
            ["AgeLimit"] = 2,
            ["ReplicatedBullets"] = true,
            ["BuildingEnabled"] = false,
            ["PainMult"] = 1.5,
            ["KODamage"] = 85,
            ["BleedDamage"] = 30,
            ["TeamKill"] = false,
            ["HitmarkerSound"] = false,
            ["BuildingKey"] = Enum.KeyCode.RightAlt,
            ["ReplicatedFlashlight"] = true,
            ["MaxVelocity"] = 75,
            ["CoreGuiHealth"] = false,
            ["CanDrown"] = true,
            ["HungerWaitTime"] = 25,
            ["SlowPaceWalkSpeed"] = 6,
            ["NormalWalkSpeed"] = 12,
            ["JumpPower"] = 30,
            ["RealisticLaser"] = true,
            ["ReplicatedLaser"] = true,
            ["CrosshairOffset"] = 5,
            ["Crosshair"] = false,
            ["TeamDmgMult"] = 1
        }
    },
    ["AttModules"] = {
        ["Compensator"] = {
            ["AimSpreadReduction"] = 1,
            ["EnableFlashlight"] = false,
            ["SightZoom"] = 0,
            ["gunRecoil"] = {["RecoilRight"] = 0.9, ["RecoilLeft"] = 0.9, ["RecoilTilt"] = 1, ["RecoilUp"] = 1.1},
            ["RecoilPowerStepAmount"] = 1,
            ["MaxSpread"] = 1,
            ["MuzzleVelocityMod"] = 1,
            ["camRecoil"] = {["RecoilRight"] = 0.9, ["RecoilLeft"] = 0.9, ["RecoilTilt"] = 1, ["RecoilUp"] = 1.1},
            ["AimInaccuracyDecrease"] = 1,
            ["DamageMod"] = 1,
            ["EnableLaser"] = false,
            ["minDamageMod"] = 1,
            ["InfraRed"] = false,
            ["AimInaccuracyStepAmount"] = 1,
            ["WalkMult"] = 1,
            ["AimRecoilReduction"] = 1,
            ["MinSpread"] = 1,
            ["MaxRecoilPower"] = 1,
            ["IsSuppressor"] = false,
            ["MinRecoilPower"] = 1,
            ["SightZoom2"] = 0,
            ["IsBipod"] = false,
            ["IsFlashHider"] = false
        },
        ["Reflex"] = {
            ["AimSpreadReduction"] = 1,
            ["EnableFlashlight"] = false,
            ["SightZoom"] = 0,
            ["gunRecoil"] = {["RecoilRight"] = 1, ["RecoilLeft"] = 1, ["RecoilTilt"] = 1, ["RecoilUp"] = 1},
            ["RecoilPowerStepAmount"] = 1,
            ["MaxSpread"] = 1,
            ["MuzzleVelocityMod"] = 1,
            ["camRecoil"] = {["RecoilRight"] = 1, ["RecoilLeft"] = 1, ["RecoilTilt"] = 1, ["RecoilUp"] = 1},
            ["AimInaccuracyDecrease"] = 1,
            ["DamageMod"] = 1,
            ["EnableLaser"] = false,
            ["minDamageMod"] = 1,
            ["InfraRed"] = false,
            ["AimInaccuracyStepAmount"] = 1,
            ["WalkMult"] = 1,
            ["AimRecoilReduction"] = 1,
            ["MinSpread"] = 1,
            ["MaxRecoilPower"] = 1,
            ["IsSuppressor"] = false,
            ["MinRecoilPower"] = 1,
            ["SightZoom2"] = 0,
            ["IsBipod"] = false,
            ["IsFlashHider"] = false
        },
        ["Laser"] = {
            ["AimSpreadReduction"] = 1,
            ["EnableFlashlight"] = false,
            ["SightZoom"] = 0,
            ["gunRecoil"] = {["RecoilRight"] = 1, ["RecoilLeft"] = 1, ["RecoilTilt"] = 1, ["RecoilUp"] = 1},
            ["RecoilPowerStepAmount"] = 1,
            ["MaxSpread"] = 0.75,
            ["MuzzleVelocityMod"] = 1,
            ["camRecoil"] = {["RecoilRight"] = 1, ["RecoilLeft"] = 1, ["RecoilTilt"] = 1, ["RecoilUp"] = 1},
            ["AimInaccuracyDecrease"] = 1.5,
            ["DamageMod"] = 1,
            ["EnableLaser"] = true,
            ["minDamageMod"] = 1,
            ["InfraRed"] = false,
            ["AimInaccuracyStepAmount"] = 1,
            ["WalkMult"] = 0.75,
            ["AimRecoilReduction"] = 1,
            ["MinSpread"] = 0.75,
            ["MaxRecoilPower"] = 1,
            ["IsSuppressor"] = false,
            ["MinRecoilPower"] = 1,
            ["SightZoom2"] = 0,
            ["IsBipod"] = false,
            ["IsFlashHider"] = false
        },
        ["Angled Grip"] = {
            ["AimSpreadReduction"] = 1,
            ["EnableFlashlight"] = false,
            ["SightZoom"] = 0,
            ["gunRecoil"] = {["RecoilRight"] = 0.8, ["RecoilLeft"] = 0.8, ["RecoilTilt"] = 0.75, ["RecoilUp"] = 1},
            ["RecoilPowerStepAmount"] = 1,
            ["MaxSpread"] = 1,
            ["MuzzleVelocityMod"] = 1,
            ["camRecoil"] = {["RecoilRight"] = 0.8, ["RecoilLeft"] = 0.8, ["RecoilTilt"] = 0.75, ["RecoilUp"] = 1},
            ["AimInaccuracyDecrease"] = 1,
            ["DamageMod"] = 1,
            ["EnableLaser"] = false,
            ["minDamageMod"] = 1,
            ["InfraRed"] = false,
            ["AimInaccuracyStepAmount"] = 1,
            ["WalkMult"] = 1,
            ["AimRecoilReduction"] = 1,
            ["MinSpread"] = 1,
            ["MaxRecoilPower"] = 1,
            ["IsSuppressor"] = false,
            ["MinRecoilPower"] = 1,
            ["SightZoom2"] = 0,
            ["IsBipod"] = false,
            ["IsFlashHider"] = false
        },
        ["Vertical Grip"] = {
            ["AimSpreadReduction"] = 1,
            ["EnableFlashlight"] = false,
            ["SightZoom"] = 0,
            ["gunRecoil"] = {["RecoilRight"] = 1.1, ["RecoilLeft"] = 1.1, ["RecoilTilt"] = 1, ["RecoilUp"] = 0.8},
            ["RecoilPowerStepAmount"] = 1,
            ["MaxSpread"] = 1,
            ["MuzzleVelocityMod"] = 1,
            ["camRecoil"] = {["RecoilRight"] = 1.1, ["RecoilLeft"] = 1.1, ["RecoilTilt"] = 1, ["RecoilUp"] = 0.8},
            ["AimInaccuracyDecrease"] = 1,
            ["DamageMod"] = 1,
            ["EnableLaser"] = false,
            ["minDamageMod"] = 1,
            ["InfraRed"] = false,
            ["AimInaccuracyStepAmount"] = 1,
            ["WalkMult"] = 1,
            ["AimRecoilReduction"] = 0.9,
            ["MinSpread"] = 1,
            ["MaxRecoilPower"] = 1,
            ["IsSuppressor"] = false,
            ["MinRecoilPower"] = 1,
            ["SightZoom2"] = 0,
            ["IsBipod"] = false,
            ["IsFlashHider"] = false
        },
        ["Base"] = {
            ["AimSpreadReduction"] = 1,
            ["EnableFlashlight"] = false,
            ["SightZoom"] = 0,
            ["gunRecoil"] = {["RecoilRight"] = 1, ["RecoilLeft"] = 1, ["RecoilTilt"] = 1, ["RecoilUp"] = 1},
            ["RecoilPowerStepAmount"] = 1,
            ["MaxSpread"] = 1,
            ["MuzzleVelocityMod"] = 1,
            ["camRecoil"] = {["RecoilRight"] = 1, ["RecoilLeft"] = 1, ["RecoilTilt"] = 1, ["RecoilUp"] = 1},
            ["AimInaccuracyDecrease"] = 1,
            ["DamageMod"] = 1,
            ["EnableLaser"] = false,
            ["minDamageMod"] = 1,
            ["InfraRed"] = false,
            ["AimInaccuracyStepAmount"] = 1,
            ["WalkMult"] = 1,
            ["AimRecoilReduction"] = 1,
            ["MinSpread"] = 1,
            ["MaxRecoilPower"] = 1,
            ["IsSuppressor"] = false,
            ["MinRecoilPower"] = 1,
            ["SightZoom2"] = 0,
            ["IsBipod"] = false,
            ["IsFlashHider"] = false
        },
        ["TA33 Acog"] = {
            ["AimSpreadReduction"] = 1,
            ["EnableFlashlight"] = false,
            ["SightZoom"] = 10,
            ["gunRecoil"] = {["RecoilRight"] = 1, ["RecoilLeft"] = 1, ["RecoilTilt"] = 1, ["RecoilUp"] = 1},
            ["RecoilPowerStepAmount"] = 1,
            ["MaxSpread"] = 1,
            ["MuzzleVelocityMod"] = 1,
            ["camRecoil"] = {["RecoilRight"] = 1, ["RecoilLeft"] = 1, ["RecoilTilt"] = 1, ["RecoilUp"] = 1},
            ["AimInaccuracyDecrease"] = 1,
            ["DamageMod"] = 1,
            ["EnableLaser"] = false,
            ["minDamageMod"] = 1,
            ["InfraRed"] = false,
            ["AimInaccuracyStepAmount"] = 1,
            ["WalkMult"] = 1,
            ["AimRecoilReduction"] = 0.9,
            ["MinSpread"] = 1,
            ["MaxRecoilPower"] = 1,
            ["IsSuppressor"] = false,
            ["MinRecoilPower"] = 1,
            ["SightZoom2"] = 0,
            ["IsBipod"] = false,
            ["IsFlashHider"] = false
        },
        ["PM II"] = {
            ["AimSpreadReduction"] = 1,
            ["EnableFlashlight"] = false,
            ["SightZoom"] = 5,
            ["gunRecoil"] = {["RecoilRight"] = 1, ["RecoilLeft"] = 1, ["RecoilTilt"] = 1, ["RecoilUp"] = 1},
            ["RecoilPowerStepAmount"] = 1,
            ["MaxSpread"] = 1,
            ["MuzzleVelocityMod"] = 1,
            ["camRecoil"] = {["RecoilRight"] = 1, ["RecoilLeft"] = 1, ["RecoilTilt"] = 1, ["RecoilUp"] = 1},
            ["AimInaccuracyDecrease"] = 1,
            ["DamageMod"] = 1,
            ["EnableLaser"] = false,
            ["minDamageMod"] = 1,
            ["InfraRed"] = false,
            ["AimInaccuracyStepAmount"] = 1,
            ["WalkMult"] = 1,
            ["AimRecoilReduction"] = 0.85,
            ["MinSpread"] = 1,
            ["MaxRecoilPower"] = 1,
            ["IsSuppressor"] = false,
            ["MinRecoilPower"] = 1,
            ["SightZoom2"] = 0,
            ["IsBipod"] = false,
            ["IsFlashHider"] = false
        },
        ["MG42 Bipod"] = {
            ["AimSpreadReduction"] = 1,
            ["EnableFlashlight"] = false,
            ["SightZoom"] = 0,
            ["gunRecoil"] = {["RecoilRight"] = 0.4, ["RecoilLeft"] = 0.4, ["RecoilTilt"] = 0.4, ["RecoilUp"] = 1},
            ["RecoilPowerStepAmount"] = 1,
            ["MaxSpread"] = 1,
            ["MuzzleVelocityMod"] = 1,
            ["camRecoil"] = {["RecoilRight"] = 0.4, ["RecoilLeft"] = 0.4, ["RecoilTilt"] = 0.4, ["RecoilUp"] = 1},
            ["AimInaccuracyDecrease"] = 1,
            ["DamageMod"] = 1,
            ["EnableLaser"] = false,
            ["minDamageMod"] = 1,
            ["InfraRed"] = false,
            ["AimInaccuracyStepAmount"] = 1,
            ["WalkMult"] = 1,
            ["AimRecoilReduction"] = 2,
            ["MinSpread"] = 1,
            ["MaxRecoilPower"] = 0.8,
            ["IsSuppressor"] = false,
            ["MinRecoilPower"] = 0.4,
            ["SightZoom2"] = 0,
            ["IsBipod"] = true,
            ["IsFlashHider"] = false
        },
        ["Acog"] = {
            ["AimSpreadReduction"] = 1,
            ["EnableFlashlight"] = false,
            ["SightZoom"] = 28,
            ["gunRecoil"] = {["RecoilRight"] = 1, ["RecoilLeft"] = 1, ["RecoilTilt"] = 1, ["RecoilUp"] = 1},
            ["RecoilPowerStepAmount"] = 1,
            ["MaxSpread"] = 1,
            ["MuzzleVelocityMod"] = 1,
            ["camRecoil"] = {["RecoilRight"] = 1, ["RecoilLeft"] = 1, ["RecoilTilt"] = 1, ["RecoilUp"] = 1},
            ["AimInaccuracyDecrease"] = 1,
            ["DamageMod"] = 1,
            ["EnableLaser"] = false,
            ["minDamageMod"] = 1,
            ["InfraRed"] = false,
            ["AimInaccuracyStepAmount"] = 1,
            ["WalkMult"] = 1,
            ["AimRecoilReduction"] = 0.95,
            ["MinSpread"] = 1,
            ["MaxRecoilPower"] = 1,
            ["IsSuppressor"] = false,
            ["MinRecoilPower"] = 1,
            ["SightZoom2"] = 0,
            ["IsBipod"] = false,
            ["IsFlashHider"] = false
        },
        ["Flash Hider"] = {
            ["AimSpreadReduction"] = 1,
            ["EnableFlashlight"] = false,
            ["SightZoom"] = 0,
            ["gunRecoil"] = {["RecoilRight"] = 1, ["RecoilLeft"] = 1, ["RecoilTilt"] = 1, ["RecoilUp"] = 1},
            ["RecoilPowerStepAmount"] = 1,
            ["MaxSpread"] = 1,
            ["MuzzleVelocityMod"] = 1,
            ["camRecoil"] = {["RecoilRight"] = 1, ["RecoilLeft"] = 1, ["RecoilTilt"] = 1, ["RecoilUp"] = 1},
            ["AimInaccuracyDecrease"] = 1,
            ["DamageMod"] = 1,
            ["EnableLaser"] = false,
            ["minDamageMod"] = 1,
            ["InfraRed"] = false,
            ["AimInaccuracyStepAmount"] = 1,
            ["WalkMult"] = 1,
            ["AimRecoilReduction"] = 1,
            ["MinSpread"] = 1,
            ["MaxRecoilPower"] = 1,
            ["IsSuppressor"] = false,
            ["MinRecoilPower"] = 1,
            ["SightZoom2"] = 0,
            ["IsBipod"] = false,
            ["IsFlashHider"] = true
        },
        ["EOTech"] = {
            ["AimSpreadReduction"] = 1,
            ["EnableFlashlight"] = false,
            ["SightZoom"] = 0,
            ["gunRecoil"] = {["RecoilRight"] = 1, ["RecoilLeft"] = 1, ["RecoilTilt"] = 1, ["RecoilUp"] = 1},
            ["RecoilPowerStepAmount"] = 1,
            ["MaxSpread"] = 1,
            ["MuzzleVelocityMod"] = 1,
            ["camRecoil"] = {["RecoilRight"] = 1, ["RecoilLeft"] = 1, ["RecoilTilt"] = 1, ["RecoilUp"] = 1},
            ["AimInaccuracyDecrease"] = 1,
            ["DamageMod"] = 1,
            ["EnableLaser"] = false,
            ["minDamageMod"] = 1,
            ["InfraRed"] = false,
            ["AimInaccuracyStepAmount"] = 1,
            ["WalkMult"] = 1,
            ["AimRecoilReduction"] = 1,
            ["MinSpread"] = 1,
            ["MaxRecoilPower"] = 1,
            ["IsSuppressor"] = false,
            ["MinRecoilPower"] = 1,
            ["SightZoom2"] = 0,
            ["IsBipod"] = false,
            ["IsFlashHider"] = false
        },
        ["Bipod"] = {
            ["AimSpreadReduction"] = 1,
            ["EnableFlashlight"] = false,
            ["SightZoom"] = 0,
            ["gunRecoil"] = {["RecoilRight"] = 0.4, ["RecoilLeft"] = 0.4, ["RecoilTilt"] = 0.4, ["RecoilUp"] = 1},
            ["RecoilPowerStepAmount"] = 1,
            ["MaxSpread"] = 1,
            ["MuzzleVelocityMod"] = 1,
            ["camRecoil"] = {["RecoilRight"] = 0.4, ["RecoilLeft"] = 0.4, ["RecoilTilt"] = 0.4, ["RecoilUp"] = 1},
            ["AimInaccuracyDecrease"] = 1,
            ["DamageMod"] = 1,
            ["EnableLaser"] = false,
            ["minDamageMod"] = 1,
            ["InfraRed"] = false,
            ["AimInaccuracyStepAmount"] = 1,
            ["WalkMult"] = 1,
            ["AimRecoilReduction"] = 2,
            ["MinSpread"] = 1,
            ["MaxRecoilPower"] = 0.8,
            ["IsSuppressor"] = false,
            ["MinRecoilPower"] = 0.4,
            ["SightZoom2"] = 0,
            ["IsBipod"] = true,
            ["IsFlashHider"] = false
        },
        ["Muzzle Brake"] = {
            ["AimSpreadReduction"] = 1,
            ["EnableFlashlight"] = false,
            ["SightZoom"] = 0,
            ["gunRecoil"] = {["RecoilRight"] = 1.1, ["RecoilLeft"] = 1.1, ["RecoilTilt"] = 1, ["RecoilUp"] = 0.9},
            ["RecoilPowerStepAmount"] = 1,
            ["MaxSpread"] = 1,
            ["MuzzleVelocityMod"] = 1,
            ["camRecoil"] = {["RecoilRight"] = 1.05, ["RecoilLeft"] = 1.05, ["RecoilTilt"] = 1, ["RecoilUp"] = 0.9},
            ["AimInaccuracyDecrease"] = 1,
            ["DamageMod"] = 1,
            ["EnableLaser"] = false,
            ["minDamageMod"] = 1,
            ["InfraRed"] = false,
            ["AimInaccuracyStepAmount"] = 1,
            ["WalkMult"] = 1,
            ["AimRecoilReduction"] = 1,
            ["MinSpread"] = 1,
            ["MaxRecoilPower"] = 1,
            ["IsSuppressor"] = false,
            ["MinRecoilPower"] = 1,
            ["SightZoom2"] = 0,
            ["IsBipod"] = false,
            ["IsFlashHider"] = false
        },
        ["AN PEQ"] = {
            ["AimSpreadReduction"] = 1,
            ["EnableFlashlight"] = true,
            ["SightZoom"] = 0,
            ["gunRecoil"] = {["RecoilRight"] = 1, ["RecoilLeft"] = 1, ["RecoilTilt"] = 1, ["RecoilUp"] = 1},
            ["RecoilPowerStepAmount"] = 1,
            ["MaxSpread"] = 1,
            ["MuzzleVelocityMod"] = 1,
            ["camRecoil"] = {["RecoilRight"] = 1, ["RecoilLeft"] = 1, ["RecoilTilt"] = 1, ["RecoilUp"] = 1},
            ["AimInaccuracyDecrease"] = 1,
            ["DamageMod"] = 1,
            ["EnableLaser"] = true,
            ["minDamageMod"] = 1,
            ["InfraRed"] = true,
            ["AimInaccuracyStepAmount"] = 1,
            ["WalkMult"] = 1,
            ["AimRecoilReduction"] = 1,
            ["MinSpread"] = 1,
            ["MaxRecoilPower"] = 1,
            ["IsSuppressor"] = false,
            ["MinRecoilPower"] = 1,
            ["SightZoom2"] = 0,
            ["IsBipod"] = false,
            ["IsFlashHider"] = false
        },
        ["Flashlight"] = {
            ["AimSpreadReduction"] = 1,
            ["EnableFlashlight"] = true,
            ["SightZoom"] = 0,
            ["gunRecoil"] = {["RecoilRight"] = 1, ["RecoilLeft"] = 1, ["RecoilTilt"] = 1, ["RecoilUp"] = 1},
            ["RecoilPowerStepAmount"] = 1,
            ["MaxSpread"] = 1,
            ["MuzzleVelocityMod"] = 1,
            ["camRecoil"] = {["RecoilRight"] = 1, ["RecoilLeft"] = 1, ["RecoilTilt"] = 1, ["RecoilUp"] = 1},
            ["AimInaccuracyDecrease"] = 1,
            ["DamageMod"] = 1,
            ["EnableLaser"] = false,
            ["minDamageMod"] = 1,
            ["InfraRed"] = false,
            ["AimInaccuracyStepAmount"] = 1,
            ["WalkMult"] = 1,
            ["AimRecoilReduction"] = 1,
            ["MinSpread"] = 1,
            ["MaxRecoilPower"] = 1,
            ["IsSuppressor"] = false,
            ["MinRecoilPower"] = 1,
            ["SightZoom2"] = 0,
            ["IsBipod"] = false,
            ["IsFlashHider"] = false
        },
        ["Suppressor"] = {
            ["AimSpreadReduction"] = 1,
            ["EnableFlashlight"] = false,
            ["SightZoom"] = 0,
            ["gunRecoil"] = {["RecoilRight"] = 1.05, ["RecoilLeft"] = 1.05, ["RecoilTilt"] = 1, ["RecoilUp"] = 0.9},
            ["RecoilPowerStepAmount"] = 1,
            ["MaxSpread"] = 1,
            ["MuzzleVelocityMod"] = 0.75,
            ["camRecoil"] = {["RecoilRight"] = 1.05, ["RecoilLeft"] = 1.05, ["RecoilTilt"] = 1, ["RecoilUp"] = 0.9},
            ["AimInaccuracyDecrease"] = 1,
            ["DamageMod"] = 0.85,
            ["EnableLaser"] = false,
            ["minDamageMod"] = 1,
            ["InfraRed"] = false,
            ["AimInaccuracyStepAmount"] = 1,
            ["WalkMult"] = 1,
            ["AimRecoilReduction"] = 1,
            ["MinSpread"] = 1.5,
            ["MaxRecoilPower"] = 1,
            ["IsSuppressor"] = true,
            ["MinRecoilPower"] = 1,
            ["SightZoom2"] = 0,
            ["IsBipod"] = false,
            ["IsFlashHider"] = true
        },
        ["Aimpoint"] = {
            ["AimSpreadReduction"] = 1,
            ["EnableFlashlight"] = false,
            ["SightZoom"] = 0,
            ["gunRecoil"] = {["RecoilRight"] = 1, ["RecoilLeft"] = 1, ["RecoilTilt"] = 1, ["RecoilUp"] = 1},
            ["RecoilPowerStepAmount"] = 1,
            ["MaxSpread"] = 1,
            ["MuzzleVelocityMod"] = 1,
            ["camRecoil"] = {["RecoilRight"] = 1, ["RecoilLeft"] = 1, ["RecoilTilt"] = 1, ["RecoilUp"] = 1},
            ["AimInaccuracyDecrease"] = 1,
            ["DamageMod"] = 1,
            ["EnableLaser"] = false,
            ["minDamageMod"] = 1,
            ["InfraRed"] = false,
            ["AimInaccuracyStepAmount"] = 1,
            ["WalkMult"] = 1,
            ["AimRecoilReduction"] = 1,
            ["MinSpread"] = 1,
            ["MaxRecoilPower"] = 1,
            ["IsSuppressor"] = false,
            ["MinRecoilPower"] = 1,
            ["SightZoom2"] = 0,
            ["IsBipod"] = false,
            ["IsFlashHider"] = false
        }
    },
    ["Modules"] = {
        ["Ragdoll"] = "function: 0x6e375b8cc4251002",
        ["Spring"] = {["new"] = "function: 0x66f1ddb8d8909d22"},
        ["Utilities"] = {
            ["WeldComplex"] = "function: 0xd377db4abaf492a2",
            ["Weld"] = "function: 0x996fdadcbff31842",
            ["CheckForHumanoid"] = "function: 0x375f2427b5de0b02"
        },
        ["Hitmarker"] = {["Explosion"] = "function: 0xe70dc7a0b74970a2"},
        ["Thread"] = {
            ["Spawn"] = "function: 0x56d924533f327462",
            ["Delay"] = "function: 0xab31f937232cbe42",
            ["Wait"] = "function: 0x718d32a580c44a92"
        }
    }
}
