Basic = {["Blue"] = {["Price"]={["Value"]=500,["Type"]="2"},["Rarity"]="1",["Name"]="Blue",["Description"]="Blue nametag"},
["Default"] = {["Rarity"]="1",["Name"]="Default",["Description"]="The default nametag"},
["Green"] = {["Price"]={["Value"]=500,["Type"]="2"},["Rarity"]="1",["Name"]="Green",["Description"]="Green nametag"},
["Inverted"] = {["Price"]={["Value"]=2000,["Type"]="2"},["Rarity"]="3",["Name"]="Inverted",["Description"]="Inverted nametag"},
["Miami"] = {["Price"]={["Value"]=2000,["Type"]="2"},["Rarity"]="3",["Name"]="Miami",["Description"]="Miami nametag"},
["Mirror"] = {["Price"]={["Value"]=1000,["Type"]="2"},["Rarity"]="2",["Name"]="Mirror",["Description"]="A relection"},
["Noob"] = {["Price"]={["Value"]=1000,["Type"]="2"},["Rarity"]="2",["Name"]="Noob",["Description"]="Noob nametag"},
["Ocean"] = {["Price"]={["Value"]=2000,["Type"]="2"},["Rarity"]="3",["Name"]="Ocean",["Description"]="Ocean man, take me by the hand."},
["Orange"] = {["Price"]={["Value"]=500,["Type"]="2"},["Rarity"]="1",["Name"]="Orange",["Description"]="Orange nametag"},
["Pig"] = {["Price"]={["Value"]=2000,["Type"]="2"},["Rarity"]="3",["Name"]="Pig",["Description"]="Oink!"},
["Pink"] = {["Price"]={["Value"]=1000,["Type"]="2"},["Rarity"]="2",["Name"]="Pink",["Description"]="Pink nametag"},
["Purple"] = {["Price"]={["Value"]=1000,["Type"]="2"},["Rarity"]="2",["Name"]="Purple",["Description"]="Purple nametag"},
["Red"] = {["Price"]={["Value"]=500,["Type"]="2"},["Rarity"]="1",["Name"]="Red",["Description"]="Red nametag"},
["Retro"] = {["Price"]={["Value"]=1000,["Type"]="2"},["Rarity"]="2",["Name"]="Retro",["Description"]="Retro nametag"},
["Sour"] = {["Price"]={["Value"]=1000,["Type"]="2"},["Rarity"]="2",["Name"]="Sour",["Description"]="Sour nametag"},
["Sunset"] = {["Price"]={["Value"]=2000,["Type"]="2"},["Rarity"]="3",["Name"]="Sunset",["Description"]="Sunset nametag"},
}
Exclusive = {["Champion"] = {["Rarity"]="6",["Name"]="Champion",["Description"]="Only for the best of players.."},
["Chatty"] = {["Rarity"]="6",["Name"]="Chatty",["Description"]="Join our chat and talk with others! ðŸ’¬"},
["Cloudy"] = {["Price"]={["Value"]=5000,["Type"]="2"},["Rarity"]="4",["Name"]="Cloudy",["Description"]="Clouds."},
["Doge"] = {["Price"]={["Value"]=5000,["Type"]="2"},["Rarity"]="4",["Name"]="Doge",["Description"]="Wow! So nametag! Is this meme still relevant?!"},
["Fallen"] = {["Rarity"]="6",["Name"]="Fallen",["Description"]="Redeemed from Fallen King plushie."},
["Follower"] = {["Rarity"]="6",["Name"]="Follower",["Description"]="Follow @paradoxum_games! â¤ï¸"},
["Glitchy"] = {["Rarity"]="6",["Name"]="Glitchy",["Description"]="..."},
["GraveDigger"] = {["Rarity"]="6",["Name"]="GraveDigger",["Description"]="Redeemed from GraveDigger plushie."},
["GunSlinger"] = {["Rarity"]="6",["Name"]="GunSlinger",["Description"]="Redeemed from GunSlinger plushie."},
["Lava"] = {["Price"]={["Value"]=5000,["Type"]="2"},["Rarity"]="4",["Name"]="Lava",["Description"]="Ouch! So hot!"},
["Lightning"] = {["Price"]={["Value"]=5000,["Type"]="2"},["Rarity"]="4",["Name"]="Lightning",["Description"]="ZAPP!! âš¡"},
["Molten"] = {["Rarity"]="6",["Name"]="Molten",["Description"]="Redeemed from Molten Boss plushie."},
["Polluted"] = {["Rarity"]="6",["Name"]="Polluted",["Description"]="Redeemed from Nuclear Monster plushie."},
["Rainbow"] = {["Rarity"]="6",["Name"]="Rainbow",["Description"]="A special nametag for being V.I.P!"},
["Rainy"] = {["Price"]={["Value"]=5000,["Type"]="2"},["Rarity"]="4",["Name"]="Rainy",["Description"]="Oh, this is so sad!"},
["Rich"] = {["Price"]={["Value"]=5000,["Type"]="2"},["Rarity"]="4",["Name"]="Rich",["Description"]="Loadsamoney, MONEH MONEH MONEH!"},
["SparkleTime"] = {["Price"]={["Value"]=5000,["Type"]="2"},["Rarity"]="4",["Name"]="SparkleTime",["Description"]="Mr. Sparkle! I am disrespectful to dirt! Can you see I am serious!"},
["Static"] = {["Rarity"]="6",["Name"]="Static",["Description"]="Developer Exclusive"},
}
