data = {
    "Visit the Glider shop for a free Glider!",
    "Everyday you earn free rocket fuel.",
    "Use rocket fuel in your car to fly through the air!",
    "Use a helicopter spotlight to slow down criminals!",
    "Donuts give you health! Grab one at the Donut Shop.",
    "Got to go fast? Grab an energy drink at the Gas Station!",
    "Use Keycards to gain access to locked doors.",
    "Police might drop a keycard when they're defeated.",
    "You can pickpocket police by standing behind them.",
    "To rob the mansion, find an invite from an airdrop battle!",
    "Some cars have cool tricks! Use their special action key...",
    "Wanna bribe a cop? Drop some cash on the ground.",
    "Use your taser to briefly ragdoll criminals!",
    "Hold Shift to make your car drift!",
    "You can drop a rope from your helicopter to pick up cars.",
    "You can drop a rope from your helicopter to pick up players.",
    "You'll need C4 to rob the Bank Truck.",
    "You can break fellow criminals out of their handcuffs!",
    "Spawn any of your cars in any Garage location.",
    "Police can bump into a criminal's car to slow them down.",
    "Shoot enemy vehicle tires to stop their getaway!",
    "You can shoot aerial vehicles to bring them down.",
    "Pick up a friend at the Pet Store. They'll guard you!",
    "Change a trains direction by interacting with track switches!",
    "Review live security footage at any Police Station!",
    "Players caught on a security camera will be highlighted!",
    "Find the jetpack atop the highest mountains.",
    "Homes are available for you to buy and customize.",
    "Homes can act as your spawnpoint and offer weapons.",
    "Police can eject criminals out of cars with their handcuffs!",
    "Use the Flashlight in dark spaces.",
    "The Plasma Pistol can shoot through shields!",
    "You can put skins on any of your weapons! Visit a weapon shop.",
    "Rocket Launchers and Jets can lock on to cars with explosives!",
    "Extensively customize your ride at any Garage!",
    "Visit the Trade World to obtain rare vehicles and items.",
    "Complete contracts to earn XP towards free seasonal rewards!",
    "Use ramps and tunnels to your advantage in a car chase.",
    "Escape the Museum by pulling both levers at the same time.",
    "Watch for airdrops from the sky, but prepare for a fight!",
    "Use a helicopter to pick up crates from the cargo ship!",
    "Find more weapons at any of the Gun Stores.",
    "Spawn and customize vehicles anywhere with the Garage Gamepass!",
    "Rob the red boxcars from the Cargo Train for cash.",
    "Use a bridge or tall vehicle to jump onto a train.",
    "Trains are deadly! Look both ways before crossing.",
    "Players on the opposite team will blink on your minimap.",
    "Open your Minimap for a fullscreen view.",
    "Lost? Place waypoints from your fullscreen Minimap.",
    "Hyperchromes are one of the rarest rewards you can find.",
    "Obtain all of the Hyperchromes and you'll be given the rare HyperShift.",
    "A different type of train appears in the night.",
    "Seeasons refresh every few months with new prizes.",
    "You can spawn many of your vehicles even without a garage.",
    "There is a criminal base within the Volcano.",
    "There is a criminal base behind Rising City.",
    "Select your next spawn in the Spawn Choice menu.",
    "The Museum won't alert police unless a criminal trips the alarm.",
    "Tasers and Handcuffs have reload times. Use them wisely!",
    "Dodge attacks or gain some ground with Rolling.",
    "Use your headlights and glows for better visibility.",
    "The Duffel Bag and VIP Gamepass are great ways to get more cash.",
    "Police are paid bonuses at sunrise for their work.",
    "Banks and Jewelry Stores change layouts every time they open.",
    "Switch sides with the Change Team button for a different way to play.",
    "Make or join a Crew for competitive battles with other players!",
    "There are more than 800 items to trade in the Trade World!",
    "Visit the trade ship to trade with other players!",
    "Sale items can be found within Garages every week.",
    "Complete contracts to level up faster.",
    "The Cargo Plane crates have a chance of giving you a keycard.",
    "Gliders offer a great way to glide across the map.",
    "Private Servers offer additional ways to play, with Admin Commands!",
    "In a Private Server? Try using the freecam command.",
    "Vehicles are more slippery when it's raining.",
    "Press the Settings button for additional options.",
    "Watch out, Police might be waiting for you outside!",
    "Give Prisoner Rusty a Donut for another way to escape.",
    "You can play the game with a controller!",
    "Raise the Red Bridge by sailing a boat underneath.",
    "You'll be sent to the Security Prison if your bounty is too high upon capture.",
    "Police vehicles have locks you'll need to hijack.",
    "Level 10 gives you a Nuke you can launch from the Military Base.",
    "The Cargo Plane will fly over the map before it lands.",
    "Police vehicles have lightbars on top.",
    "Try switching between skydiving and parachuting in a single dive.",
    "You can drop your friends into the Volcano.",
    "Raise your vehicle suspension to go offroad.",
    "Trains will briefly stop if they pass through the train station",
    "Find the Tomb within the dunes. You'll need three players to get inside.",
    "Police can place Spiketraps across any surface.",
    "Return to the prison to jailbreak fellow prisoners!",
    "You can find a flyable UFO inside the Military Base!",
    "Earn every badge for the MVP badge and Superstar Rims!",
    "You can shuffle items in your hotbar. Try it out!",
    "Take the highway for the fastest road to Rising City.",
    "3D Markers show where robberies are and if they're open.",
    "Crouch to hide in the grass or crawl under walls.",
    "Bring enough weapons, and a donut, before entering The Mansion.",
    "The Tomb has two minecart escapes.",
    "Police earn more cash when arresting players with a high bounty.",
    "There are 100+ help tips! You can turn them off in Settings."
}
