data = {
    "Primary Coat",
    "Secondary Coat",
    "Tertiary Coat",
    "Pattern",
    "Pattern Primary",
    "Pattern Secondary",
    "Pattern Tertiary",
    "Feather Tip",
    "Feathers",
    "Under Wing",
    "Upper Wing",
    "Wing Trim",
    "Wing Webbing",
    "Claws",
    "Speckle",
    "Scales",
    "Spikes",
    "Spine",
    "Underbelly",
    "Webbing",
    "Back Fin",
    "Crest",
    "Crest Trim",
    "Fins",
    "Frill",
    "Fur",
    "Gills",
    "Hoof",
    "Horns",
    "Legs",
    "Paw Pad",
    "Scale Trim",
    "Antenna",
    "Beak",
    "Cornea",
    "Eye",
    "Eye Shadow",
    "Eyeliner",
    "Gums",
    "Head Fin",
    "Pupil",
    "Teeth",
    "Throat",
    "Tongue",
    "Dust",
    "Smoke",
    "Misc"
}
