data = {
    {
        ["Screws"] = {100, 1, 1, false, 0, false, 0, "General", 2, "Box", "Trucker", false, "Screws"},
        ["Laptops"] = {200, 5, 1, false, 0, false, 0, "General", 7, "Box", "Trucker", false, "Laptops"},
        ["Dishwashers"] = {200, 5, 1, false, 0, false, 0, "General", 5, "Box", "Trucker", false, "Dishwashers"},
        ["Lumber"] = {40, 3, 1, false, 0, false, 0, "Flatbed", 3, "Model", "Trucker", false, "Lumber"},
        ["Shorts"] = {60, 1, 1, false, 0, false, 0, "General", 2, "Box", "Trucker", false, "Shorts"},
        ["Tar"] = {100, 3, 2, false, 0, false, 0, "Bucket", 3, "Fill", "Trucker", false, "Road Tar"},
        ["Passengers_VIP"] = {63, 1, 0, true, 0, false, 0, "VIP", 8, "Fill", "Transit", false, "Executive Passengers"},
        ["Chips"] = {9, 2, 1, false, 0, false, 0, "General", 1, "Box", "Trucker", false, "Potato chips"},
        ["LightBulbs"] = {20, 5, 0, false, 0, false, 0, "General", 2, "Box", "Trucker", false, "Light bulbs"},
        ["Cars"] = {200, 3, 1, false, 0, false, 0, "CarCarrier", 6, "Box", "Trucker", false, "Cars"},
        ["Mail"] = {1, 2, 1, false, 0, false, 0, "Mail", 0, "Box", "Trucker", false, "Mail"},
        ["Computers"] = {200, 5, 1, false, 0, false, 0, "General", 7, "Box", "Trucker", false, "Computers"},
        ["IceCream"] = {60, 2, 0, false, 0, false, 0, "Fridge", 1, "Box", "Trucker", false, "Ice cream"},
        ["Glass"] = {161, 5, 1, false, 0, false, 0, "Slab", 3, "Model", "Trucker", false, "Glass sheet"},
        ["Excavator"] = {200, 3, 0, false, 0, true, 0, "Oversized", 4, "Model", "Trucker", false, "Excavator"},
        ["Gravel"] = {95, 1, 0, false, 0, false, 0, "Bucket", 5, "Fill", "Trucker", false, "Crushed gravel"},
        ["Package"] = {3, 2, 1, false, 0, false, 50, "Mail", 0, "Box", "Trucker", false, "Package"},
        ["CrudeOil"] = {55, 5, 2, false, 0, false, 0, "Tanker", 5, "Tank", "Trucker", false, "Crude oil"},
        ["Water"] = {62, 1, 0, false, 0, false, 0, "Tanker", 2, "Tank", "Trucker", false, "Water"},
        ["Toilets"] = {100, 5, 1, false, 0, false, 0, "General", 4, "Box", "Trucker", false, "Toilets"},
        ["Sheetrock"] = {161, 5, 1, false, 0, false, 0, "Slab", 3, "Model", "Trucker", false, "Sheet rock"},
        ["Milk"] = {62, 1, 0, false, 0, false, 0, "Tanker", 2, "Tank", "Trucker", false, "Milk"},
        ["Passengers_UDer"] = {63, 0, 0, true, 0, false, 0, "UDer", 3, "Fill", "Transit", false, "UDer Passengers"},
        ["Passengers_Taxi"] = {63, 0, 0, true, 0, false, 0, "Taxi", 3, "Fill", "Transit", false, "Taxi Passengers"},
        ["Tea"] = {5, 1, 1, false, 0, false, 0, "General", 1, "Box", "Trucker", false, "Tea bags"},
        ["Refrigerators"] = {200, 5, 1, false, 0, false, 0, "General", 6, "Box", "Trucker", false, "Refrigerators"},
        ["Documents2"] = {75, 2, 1, false, 0, false, 0, "Armored", 7, "Box", "Trucker", false, "Classified documents"},
        ["Soil"] = {78, 1, 0, false, 0, false, 0, "Bucket", 4, "Fill", "Trucker", false, "Soil"},
        ["Soda"] = {64, 2, 0, false, 0, false, 0, "Beverage", 1, "Box", "Trucker", false, "Bottled soda"},
        ["Passengers_School_Morning"] = {
            63,
            2,
            0,
            true,
            0,
            false,
            0,
            "School",
            4,
            "Fill",
            "Transit",
            false,
            "School Bus Passengers"
        },
        ["Passengers_Expedition"] = {
            63,
            1,
            0,
            true,
            0,
            false,
            0,
            "Expedition",
            5,
            "Fill",
            "Transit",
            false,
            "Expedition Bus Passengers"
        },
        ["Passengers_Tourist"] = {
            63,
            1,
            0,
            true,
            0,
            false,
            0,
            "Tourist",
            4,
            "Fill",
            "Transit",
            false,
            "Tourist Bus Passengers"
        },
        ["Sewage"] = {75, 2, 0, false, 0, false, 0, "Tanker", 2, "Tank", "Trucker", false, "Raw sewage"},
        ["Cookies"] = {37, 2, 1, false, 0, false, 0, "General", 1, "Box", "Trucker", false, "Cookies"},
        ["Logs"] = {40, 1, 1, false, 0, false, 0, "Logger", 3, "Model", "Trucker", false, "Logs"},
        ["XRayTubes"] = {50, 5, 4, false, 0, false, 0, "General", 7, "Box", "Trucker", false, "X-Ray Tubes"},
        ["Bricks"] = {120, 3, 0, false, 0, false, 0, "Flatbed", 3, "Model", "Trucker", false, "Bricks"},
        ["CellPhones"] = {100, 5, 1, false, 0, false, 0, "General", 4, "Box", "Trucker", false, "Cell phones"},
        ["Combine"] = {200, 4, 0, false, 0, true, 0, "Oversized", 5, "Model", "Trucker", false, "Combine Harvester"},
        ["TurbineMotor"] = {
            200,
            5,
            0,
            false,
            0,
            true,
            0,
            "Oversized",
            5,
            "Model",
            "Trucker",
            false,
            "Wind Turbine Motor"
        },
        ["TurbineBlade"] = {
            200,
            4,
            0,
            false,
            0,
            true,
            0,
            "Oversized",
            3,
            "Model",
            "Trucker",
            false,
            "Wind Turbine Blade"
        },
        ["Monitors"] = {200, 5, 1, false, 0, false, 0, "General", 6, "Box", "Trucker", false, "Computer monitors"},
        ["Stone"] = {105, 1, 0, false, 0, false, 0, "Bucket", 5, "Fill", "Trucker", false, "Stone"},
        ["DumpTruck"] = {200, 3, 0, false, 0, true, 0, "Oversized", 4, "Model", "Trucker", false, "Dump Truck"},
        ["Silver"] = {655, 1, 0, false, 0, false, 0, "Armored", 6, "Box", "Trucker", false, "Silver bars"},
        ["MonsterTruck"] = {200, 3, 0, false, 0, true, 0, "Oversized", 3, "Model", "Trucker", false, "Monster Truck"},
        ["ModularHome"] = {200, 5, 1, false, 0, true, 0, "Oversized", 5, "Model", "Trucker", false, "Modular Home"},
        ["Flour"] = {37, 1, 1, false, 0, false, 0, "General", 1, "Box", "Trucker", false, "Flour"},
        ["Hypercars"] = {200, 5, 1, false, 0, false, 0, "CarCarrier", 9, "Box", "Trucker", false, "Hypercars"},
        ["Fries"] = {65, 2, 0, false, 0, false, 0, "Fridge", 1, "Box", "Trucker", false, "Fries"},
        ["Supercars"] = {200, 4, 1, false, 0, false, 0, "CarCarrier", 8, "Box", "Trucker", false, "Supercars"},
        ["CoalOre"] = {105, 1, 0, false, 0, false, 0, "Bucket", 6, "Fill", "Trucker", false, "Coal ore"},
        ["Pool"] = {200, 5, 0, false, 0, true, 0, "Flatbed", 7, "Model", "Trucker", false, "Fiberglass pool"},
        ["Gold"] = {1206, 1, 0, false, 0, false, 0, "Armored", 7, "Box", "Trucker", false, "Gold bars"},
        ["Cows"] = {50, 5, 0, true, 0, false, 0, "Livestock", 5, "Model", "Trucker", false, "Cattle"},
        ["Bees"] = {10, 5, 0, true, 0, false, 0, "Flatbed", 5, "Model", "Trucker", false, "Bees"},
        ["ToiletPaper"] = {75, 2, 1, false, 0, false, 0, "General", 1, "Box", "Trucker", false, "Toilet Paper"},
        ["Lawnmowers"] = {200, 5, 1, false, 0, false, 0, "General", 5, "Model", "Trucker", false, "Lawnmowers"},
        ["Chickens"] = {50, 5, 0, true, 0, false, 0, "Livestock", 5, "Model", "Trucker", false, "Chickens"},
        ["Bathtubs"] = {100, 5, 1, false, 0, false, 0, "General", 5, "Box", "Trucker", false, "Bathtubs"},
        ["GraniteCounters"] = {
            168,
            5,
            1,
            false,
            0,
            false,
            0,
            "Slab",
            5,
            "Model",
            "Trucker",
            false,
            "Granite countertops"
        },
        ["GreetingCards"] = {80, 2, 1, false, 0, false, 0, "General", 1, "Box", "Trucker", false, "Greeting cards"},
        ["Grain"] = {49, 1, 1, false, 0, false, 0, "Bucket", 3, "Fill", "Trucker", false, "Grain"},
        ["LabSamples"] = {50, 5, 1, false, 3, false, 0, "General", 6, "Box", "Trucker", false, "Lab Samples"},
        ["Salt"] = {95, 1, 0, false, 0, false, 0, "Bucket", 6, "Fill", "Trucker", false, "Road salt"},
        ["Batteries"] = {120, 5, 2, false, 1, false, 0, "General", 2, "Box", "Trucker", false, "Batteries"},
        ["GraphicsCards"] = {200, 5, 1, false, 0, false, 0, "General", 6, "Box", "Trucker", false, "Graphics cards"},
        ["IronOre"] = {105, 1, 0, false, 0, false, 0, "Bucket", 7, "Fill", "Trucker", false, "Iron ore"},
        ["Platinum"] = {1339, 1, 0, false, 0, false, 0, "Armored", 8, "Box", "Trucker", false, "Platinum bars"},
        ["ChickenMeat"] = {60, 2, 0, false, 0, false, 0, "Fridge", 1, "Box", "Trucker", false, "Chicken meat"},
        ["Steel"] = {503, 3, 0, false, 0, false, 0, "Flatbed", 5, "Model", "Trucker", false, "Steel beams"},
        ["BottledWater"] = {64, 2, 0, false, 0, false, 0, "Beverage", 1, "Box", "Trucker", false, "Bottled water"},
        ["Passengers_School_Evening"] = {
            63,
            2,
            0,
            true,
            0,
            false,
            0,
            "School",
            4,
            "Fill",
            "Transit",
            false,
            "School Bus Passengers"
        },
        ["Asphalt"] = {60, 3, 1, false, 0, false, 0, "Bucket", 3, "Fill", "Trucker", false, "Asphalt"},
        ["Sinks"] = {100, 5, 1, false, 0, false, 0, "General", 4, "Box", "Trucker", false, "Sinks"},
        ["NaturalGas"] = {5, 1, 2, false, 0, false, 0, "Tanker", 3, "Tank", "Trucker", false, "Natural gas"},
        ["Passengers_City"] = {63, 1, 0, true, 0, false, 0, "City", 3, "Fill", "Transit", false, "City Bus Passengers"},
        ["Vaccines"] = {50, 5, 1, false, 3, false, 0, "General", 6, "Box", "Trucker", false, "Vaccines"},
        ["Cement"] = {40, 1, 0, false, 0, false, 0, "CementMixer", 5, "Fill", "Trucker", false, "Cement"},
        ["TShirts"] = {60, 1, 1, false, 0, false, 0, "General", 2, "Box", "Trucker", false, "T-Shirts"},
        ["Coal"] = {84, 1, 0, false, 0, false, 0, "Bucket", 7, "Fill", "Trucker", false, "Coal"},
        ["Shrimp"] = {40, 2, 0, false, 0, false, 0, "Fridge", 2, "Box", "Trucker", false, "Shrimp"},
        ["Medicine"] = {50, 5, 1, false, 2, false, 0, "General", 5, "Box", "Trucker", false, "Medicine"},
        ["Fish"] = {40, 2, 0, false, 0, false, 0, "Fridge", 2, "Box", "Trucker", false, "Fish"},
        ["Ice"] = {57, 1, 0, false, 0, false, 0, "Fridge", 1, "Box", "Trucker", false, "Ice"},
        ["Documents"] = {75, 2, 1, false, 0, false, 0, "Armored", 6, "Box", "Trucker", false, "Important documents"},
        ["Fruit"] = {55, 4, 0, false, 0, false, 0, "Fridge", 1, "Box", "Trucker", false, "Fruit"},
        ["Bread"] = {37, 3, 1, false, 0, false, 0, "General", 1, "Box", "Trucker", false, "Bread"},
        ["Vegetables"] = {55, 4, 0, false, 0, false, 0, "Fridge", 1, "Box", "Trucker", false, "Vegetables"},
        ["MedicalWaste"] = {50, 5, 1, false, 3, false, 0, "General", 5, "Box", "Trucker", false, "Medical Waste"},
        ["TVs"] = {200, 5, 1, false, 0, false, 0, "General", 6, "Box", "Trucker", false, "TVs"},
        ["Corn"] = {49, 1, 1, false, 0, false, 0, "Bucket", 3, "Fill", "Trucker", false, "Corn"},
        ["BottledMilk"] = {64, 2, 0, false, 0, false, 0, "Beverage", 1, "Box", "Trucker", false, "Milk jugs"},
        ["WashingMachines"] = {200, 5, 1, false, 0, false, 0, "General", 6, "Box", "Trucker", false, "Washing machines"},
        ["Headphones"] = {50, 5, 1, false, 0, false, 0, "General", 5, "Box", "Trucker", false, "Headphones"},
        ["Candy"] = {20, 2, 1, false, 0, false, 0, "General", 1, "Box", "Trucker", false, "Candy"},
        ["Petroleum"] = {55, 5, 2, false, 0, false, 0, "Tanker", 5, "Tank", "Trucker", false, "Petroleum"},
        ["Passengers_Pres"] = {
            63,
            1,
            0,
            true,
            0,
            false,
            0,
            "President",
            12,
            "Fill",
            "Transit",
            false,
            "Presidential Entourage"
        },
        ["Missile"] = {200, 5, 4, false, 0, true, 0, "MissileTruck", 10, "Model", "Trucker", false, "Nuclear Warhead"},
        ["Diamonds"] = {219, 1, 0, false, 0, false, 0, "Armored", 9, "Box", "Trucker", false, "Diamonds"},
        ["PowerTools"] = {500, 4, 0, false, 0, false, 0, "General", 4, "Box", "Trucker", false, "Power tools"},
        ["Jeans"] = {60, 1, 1, false, 0, false, 0, "General", 2, "Box", "Trucker", false, "Jeans"},
        ["Beef"] = {65, 2, 0, false, 0, false, 0, "Fridge", 2, "Box", "Trucker", false, "Beef"},
        ["Paper"] = {75, 2, 1, false, 0, false, 0, "General", 1, "Box", "Trucker", false, "Paper"},
        ["Cheese"] = {59, 2, 0, false, 0, false, 0, "Fridge", 1, "Box", "Trucker", false, "Cheese"},
        ["Cash"] = {75, 2, 0, false, 0, false, 0, "Armored", 6, "Box", "Trucker", false, "Stacks of money"}
    },
    {
        ["Type"] = 8,
        ["Harmful"] = 5,
        ["Live"] = 4,
        ["FullName"] = 13,
        ["FillType"] = 10,
        ["Density"] = 1,
        ["Explosivity"] = 3,
        ["Oversized"] = 6,
        ["Fragility"] = 2,
        ["Value"] = 9,
        ["NewCargo"] = 12,
        ["Team"] = 11,
        ["Rank"] = 7
    }
}
