data = {
    ["Sapphire"] = {["Rarity"] = 6},
    ["Fiesta"] = {["Rarity"] = 1},
    ["Stars"] = {["Rarity"] = 5},
    ["Ruby"] = {["Rarity"] = 6},
    ["Popsicles"] = {["Rarity"] = 5},
    ["Clouds"] = {["Rarity"] = 1},
    ["Hot Orange"] = {["Rarity"] = 2},
    ["Zebra"] = {["Rarity"] = 5},
    ["Emerald"] = {["Rarity"] = 6},
    ["Checkerboard"] = {["Rarity"] = 4},
    ["Tribal 2"] = {["Rarity"] = 2},
    ["Deep Blue"] = {["Rarity"] = 3},
    ["Flowers 2"] = {["Rarity"] = 3},
    ["Bronze Island"] = {["Rarity"] = 2},
    ["Crimson Web"] = {["Rarity"] = 6},
    ["Asimov"] = {["Rarity"] = 6},
    ["Frost"] = {["Rarity"] = 4},
    ["Urban Camo"] = {["Rarity"] = 3},
    ["Bolt"] = {["Rarity"] = 1},
    ["Diamond"] = {["Rarity"] = 5},
    ["Lime"] = {["Rarity"] = 2},
    ["Blue Clovers"] = {["Rarity"] = 2},
    ["Hot Red"] = {["Rarity"] = 3},
    ["Silver"] = {["Rarity"] = 6},
    ["Sunset"] = {["Rarity"] = 1},
    ["Fade"] = {["Rarity"] = 6},
    ["Party"] = {["Rarity"] = 1},
    ["Gold"] = {["Rarity"] = 6},
    ["Hot Purple"] = {["Rarity"] = 2},
    ["Tribal 1"] = {["Rarity"] = 2},
    ["Cow"] = {["Rarity"] = 1},
    ["Tribal 3"] = {["Rarity"] = 2},
    ["Granite"] = {["Rarity"] = 4},
    ["Cotton Candy"] = {["Rarity"] = 3},
    ["Geometry"] = {["Rarity"] = 1},
    ["Geometry 2"] = {["Rarity"] = 3},
    ["Peach"] = {["Rarity"] = 4},
    ["Blue Island"] = {["Rarity"] = 2},
    ["Lightning"] = {["Rarity"] = 5},
    ["Dragon Scroll"] = {["Rarity"] = 3},
    ["Rainbow Zebra"] = {["Rarity"] = 6},
    ["Tribal 4"] = {["Rarity"] = 2},
    ["Stripes"] = {["Rarity"] = 5},
    ["Hexagons 2"] = {["Rarity"] = 3},
    ["Blocks"] = {["Rarity"] = 4},
    ["Dark Granite"] = {["Rarity"] = 4},
    ["Trisilver"] = {["Rarity"] = 3},
    ["Space"] = {["Rarity"] = 4},
    ["Polka Dots"] = {["Rarity"] = 2},
    ["Aqua"] = {["Rarity"] = 4},
    ["Tiger"] = {["Rarity"] = 4},
    ["Nuclear"] = {["Rarity"] = 5},
    ["Coral"] = {["Rarity"] = 3},
    ["Cracked Earth"] = {["Rarity"] = 2},
    ["Beach"] = {["Rarity"] = 5},
    ["Rainbow"] = {["Rarity"] = 5},
    ["Molten"] = {["Rarity"] = 6},
    ["Easter"] = {["Rarity"] = 3},
    ["Scorch"] = {["Rarity"] = 5},
    ["Flowers"] = {["Rarity"] = 1},
    ["Black&White"] = {["Rarity"] = 1},
    ["Hexagons"] = {["Rarity"] = 5},
    ["Pink Camo"] = {["Rarity"] = 5},
    ["America"] = {["Rarity"] = 2},
    ["Camo"] = {["Rarity"] = 1},
    ["Cheese"] = {["Rarity"] = 1},
    ["Metal"] = {["Rarity"] = 1}
}
