data = {
    ["NTP_PaidHouse_005"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["MiniIcon"] = "rbxassetid://15165340078",
        ["RequireFriends"] = "",
        ["Id"] = "NTP_PaidHouse_005",
        ["HouseAssetId"] = 16980891643,
        ["RequireFriendEndTime"] = "",
        ["ConfirmBuyTag"] = "",
        ["ConfirmInviteTag"] = "",
        ["ConfirmDescTag"] = "",
        ["Sort"] = 15,
        ["UpdateTime"] = "",
        ["IsNew"] = "",
        ["Disable"] = "",
        ["Icon"] = "rbxassetid://15165338130",
        ["RequireProduct"] = "NTP_PaidHouse_005"
    },
    ["NTP_PaidHouse_003"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["MiniIcon"] = "rbxassetid://14452183019",
        ["RequireFriends"] = "",
        ["Id"] = "NTP_PaidHouse_003",
        ["HouseAssetId"] = "14778084807",
        ["RequireFriendEndTime"] = "",
        ["ConfirmBuyTag"] = "",
        ["ConfirmInviteTag"] = "",
        ["ConfirmDescTag"] = "",
        ["Sort"] = 13,
        ["UpdateTime"] = "",
        ["IsNew"] = "",
        ["Disable"] = "",
        ["Icon"] = "rbxassetid://13465432575",
        ["RequireProduct"] = "NTP_PaidHouse_003"
    },
    ["NTP_FreeHouse_022"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["MiniIcon"] = "rbxassetid://16563376138",
        ["RequireFriends"] = "",
        ["Id"] = "NTP_FreeHouse_022",
        ["HouseAssetId"] = "17890392780",
        ["RequireFriendEndTime"] = "",
        ["ConfirmBuyTag"] = "",
        ["ConfirmInviteTag"] = "",
        ["ConfirmDescTag"] = "",
        ["Sort"] = 108,
        ["UpdateTime"] = "",
        ["IsNew"] = "",
        ["Disable"] = "",
        ["Icon"] = "rbxassetid://16563379436",
        ["RequireProduct"] = ""
    },
    ["NTP_PaidHouse_001"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["MiniIcon"] = "rbxassetid://14452183297",
        ["RequireFriends"] = 5,
        ["Id"] = "NTP_PaidHouse_001",
        ["HouseAssetId"] = "14358575756",
        ["RequireFriendEndTime"] = "2023-6-16 6:59:59",
        ["ConfirmBuyTag"] = "K_UI_PURCHASE",
        ["ConfirmInviteTag"] = "K_INVITE",
        ["ConfirmDescTag"] = "K_FRIENDS_UNLOCK",
        ["Sort"] = 11,
        ["UpdateTime"] = "",
        ["IsNew"] = "",
        ["Disable"] = "",
        ["Icon"] = "rbxassetid://13255937320",
        ["RequireProduct"] = "NTP_PaidHouse_001"
    },
    ["NTP_FreeHouse_026"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["MiniIcon"] = "rbxassetid://17422667939",
        ["RequireFriends"] = "",
        ["Id"] = "NTP_FreeHouse_026",
        ["HouseAssetId"] = "",
        ["RequireFriendEndTime"] = "",
        ["ConfirmBuyTag"] = "",
        ["ConfirmInviteTag"] = "",
        ["ConfirmDescTag"] = "",
        ["Sort"] = 112,
        ["UpdateTime"] = "",
        ["IsNew"] = "",
        ["Disable"] = "",
        ["Icon"] = "rbxassetid://17422671533",
        ["RequireProduct"] = ""
    },
    ["NTP_FreeHouse_025"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["MiniIcon"] = "rbxassetid://17262587770",
        ["RequireFriends"] = "",
        ["Id"] = "NTP_FreeHouse_025",
        ["HouseAssetId"] = "17890419708",
        ["RequireFriendEndTime"] = "",
        ["ConfirmBuyTag"] = "",
        ["ConfirmInviteTag"] = "",
        ["ConfirmDescTag"] = "",
        ["Sort"] = 111,
        ["UpdateTime"] = "",
        ["IsNew"] = "",
        ["Disable"] = "",
        ["Icon"] = "rbxassetid://17262585132",
        ["RequireProduct"] = ""
    },
    ["NTP_PaidHouse_004"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["MiniIcon"] = "rbxassetid://14452182854",
        ["RequireFriends"] = "",
        ["Id"] = "NTP_PaidHouse_004",
        ["HouseAssetId"] = "",
        ["RequireFriendEndTime"] = "",
        ["ConfirmBuyTag"] = "",
        ["ConfirmInviteTag"] = "",
        ["ConfirmDescTag"] = "",
        ["Sort"] = 14,
        ["UpdateTime"] = "",
        ["IsNew"] = "",
        ["Disable"] = "",
        ["Icon"] = "rbxassetid://14370031768",
        ["RequireProduct"] = "NTP_PaidHouse_004"
    },
    ["NTP_FreeHouse_002"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["MiniIcon"] = "rbxassetid://14452184542",
        ["RequireFriends"] = "",
        ["Id"] = "NTP_FreeHouse_002",
        ["HouseAssetId"] = "14358562644",
        ["RequireFriendEndTime"] = "",
        ["ConfirmBuyTag"] = "",
        ["ConfirmInviteTag"] = "",
        ["ConfirmDescTag"] = "",
        ["Sort"] = 88,
        ["UpdateTime"] = "",
        ["IsNew"] = "",
        ["Disable"] = "",
        ["Icon"] = "rbxassetid://13255937665",
        ["RequireProduct"] = ""
    },
    ["NTP_FreeHouse_018"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["MiniIcon"] = "rbxassetid://15853883819",
        ["RequireFriends"] = "",
        ["Id"] = "NTP_FreeHouse_018",
        ["HouseAssetId"] = "16980833108",
        ["RequireFriendEndTime"] = "",
        ["ConfirmBuyTag"] = "",
        ["ConfirmInviteTag"] = "",
        ["ConfirmDescTag"] = "",
        ["Sort"] = 102,
        ["UpdateTime"] = "",
        ["IsNew"] = "",
        ["Disable"] = "",
        ["Icon"] = "rbxassetid://15853862264",
        ["RequireProduct"] = ""
    },
    ["NTP_FreeHouse_017"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["MiniIcon"] = "rbxassetid://15681092145",
        ["RequireFriends"] = "",
        ["Id"] = "NTP_FreeHouse_017",
        ["HouseAssetId"] = "16980772930",
        ["RequireFriendEndTime"] = "",
        ["ConfirmBuyTag"] = "",
        ["ConfirmInviteTag"] = "",
        ["ConfirmDescTag"] = "",
        ["Sort"] = 101,
        ["UpdateTime"] = "",
        ["IsNew"] = "",
        ["Disable"] = "",
        ["Icon"] = "rbxassetid://15681085932",
        ["RequireProduct"] = ""
    },
    ["NTP_PaidHouse_006"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["MiniIcon"] = "rbxassetid://16095876049",
        ["RequireFriends"] = "",
        ["Id"] = "NTP_PaidHouse_006",
        ["HouseAssetId"] = "",
        ["RequireFriendEndTime"] = "",
        ["ConfirmBuyTag"] = "",
        ["ConfirmInviteTag"] = "",
        ["ConfirmDescTag"] = "",
        ["Sort"] = 19,
        ["UpdateTime"] = "",
        ["IsNew"] = "",
        ["Disable"] = "",
        ["Icon"] = "rbxassetid://16095816832",
        ["RequireProduct"] = "NTP_PaidHouse_006"
    },
    ["NTP_FreeHouse_029"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["MiniIcon"] = "rbxassetid://18118159878",
        ["RequireFriends"] = "",
        ["Id"] = "NTP_FreeHouse_029",
        ["HouseAssetId"] = "",
        ["RequireFriendEndTime"] = "",
        ["ConfirmBuyTag"] = "",
        ["ConfirmInviteTag"] = "",
        ["ConfirmDescTag"] = "",
        ["Sort"] = 116,
        ["UpdateTime"] = "",
        ["IsNew"] = "2024-06-30",
        ["Disable"] = "",
        ["Icon"] = "rbxassetid://18118153686",
        ["RequireProduct"] = ""
    },
    ["NTP_FreeHouse_016"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["MiniIcon"] = "rbxassetid://15556941238",
        ["RequireFriends"] = "",
        ["Id"] = "NTP_FreeHouse_016",
        ["HouseAssetId"] = "16980762708",
        ["RequireFriendEndTime"] = "",
        ["ConfirmBuyTag"] = "",
        ["ConfirmInviteTag"] = "",
        ["ConfirmDescTag"] = "",
        ["Sort"] = 100,
        ["UpdateTime"] = "",
        ["IsNew"] = "",
        ["Disable"] = "",
        ["Icon"] = "rbxassetid://15556939928",
        ["RequireProduct"] = ""
    },
    ["NTP_FreeHouse_020"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["MiniIcon"] = "rbxassetid://16193335984",
        ["RequireFriends"] = "",
        ["Id"] = "NTP_FreeHouse_020",
        ["HouseAssetId"] = "17404691487",
        ["RequireFriendEndTime"] = "",
        ["ConfirmBuyTag"] = "",
        ["ConfirmInviteTag"] = "",
        ["ConfirmDescTag"] = "",
        ["Sort"] = 106,
        ["UpdateTime"] = "",
        ["IsNew"] = "",
        ["Disable"] = "",
        ["Icon"] = "rbxassetid://16193337099",
        ["RequireProduct"] = ""
    },
    ["NTP_FreeHouse_009"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["MiniIcon"] = "rbxassetid://14610980467",
        ["RequireFriends"] = "",
        ["Id"] = "NTP_FreeHouse_009",
        ["HouseAssetId"] = 15853910204,
        ["RequireFriendEndTime"] = "",
        ["ConfirmBuyTag"] = "",
        ["ConfirmInviteTag"] = "",
        ["ConfirmDescTag"] = "",
        ["Sort"] = 96,
        ["UpdateTime"] = "",
        ["IsNew"] = "",
        ["Disable"] = "",
        ["Icon"] = "rbxassetid://14610782759",
        ["RequireProduct"] = ""
    },
    ["NTP_PaidHouse_002"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "VIP",
        ["MiniIcon"] = "rbxassetid://14452183143",
        ["RequireFriends"] = "",
        ["Id"] = "NTP_PaidHouse_002",
        ["HouseAssetId"] = "14358578660",
        ["RequireFriendEndTime"] = "",
        ["ConfirmBuyTag"] = "",
        ["ConfirmInviteTag"] = "",
        ["ConfirmDescTag"] = "",
        ["Sort"] = 12,
        ["UpdateTime"] = "",
        ["IsNew"] = "",
        ["Disable"] = "",
        ["Icon"] = "rbxassetid://13255937095",
        ["RequireProduct"] = ""
    },
    ["NTP_FreeHouse_005"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["MiniIcon"] = "rbxassetid://14452238125",
        ["RequireFriends"] = "",
        ["Id"] = "NTP_FreeHouse_005",
        ["HouseAssetId"] = "14358570227",
        ["RequireFriendEndTime"] = "",
        ["ConfirmBuyTag"] = "",
        ["ConfirmInviteTag"] = "",
        ["ConfirmDescTag"] = "",
        ["Sort"] = 92,
        ["UpdateTime"] = "",
        ["IsNew"] = "",
        ["Disable"] = "",
        ["Icon"] = "rbxassetid://13535664236",
        ["RequireProduct"] = ""
    },
    ["NTP_HousePass_001"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "HousePass",
        ["MiniIcon"] = "rbxassetid://15494723459",
        ["RequireFriends"] = "",
        ["Id"] = "NTP_HousePass_001",
        ["HouseAssetId"] = "16980864181",
        ["RequireFriendEndTime"] = "",
        ["ConfirmBuyTag"] = "",
        ["ConfirmInviteTag"] = "",
        ["ConfirmDescTag"] = "",
        ["Sort"] = 16,
        ["UpdateTime"] = "",
        ["IsNew"] = "",
        ["Disable"] = "",
        ["Icon"] = "rbxassetid://15494721278",
        ["RequireProduct"] = ""
    },
    ["NTP_FreeHouse_011"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["MiniIcon"] = "rbxassetid://14887524770",
        ["RequireFriends"] = "",
        ["Id"] = "NTP_FreeHouse_011",
        ["HouseAssetId"] = "15557631737",
        ["RequireFriendEndTime"] = "",
        ["ConfirmBuyTag"] = "",
        ["ConfirmInviteTag"] = "",
        ["ConfirmDescTag"] = "",
        ["Sort"] = 97,
        ["UpdateTime"] = "",
        ["IsNew"] = "",
        ["Disable"] = "",
        ["Icon"] = "rbxassetid://14887522692",
        ["RequireProduct"] = ""
    },
    ["NTP_FreeHouse_028"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["MiniIcon"] = "rbxassetid://17738600428",
        ["RequireFriends"] = "",
        ["Id"] = "NTP_FreeHouse_028",
        ["HouseAssetId"] = "",
        ["RequireFriendEndTime"] = "",
        ["ConfirmBuyTag"] = "",
        ["ConfirmInviteTag"] = "",
        ["ConfirmDescTag"] = "",
        ["Sort"] = 115,
        ["UpdateTime"] = "",
        ["IsNew"] = "",
        ["Disable"] = "",
        ["Icon"] = "rbxassetid://17738596817",
        ["RequireProduct"] = ""
    },
    ["NTP_FreeHouse_010"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["MiniIcon"] = "rbxassetid://14828517270",
        ["RequireFriends"] = "",
        ["Id"] = "NTP_FreeHouse_010",
        ["HouseAssetId"] = 15557665619,
        ["RequireFriendEndTime"] = "",
        ["ConfirmBuyTag"] = "",
        ["ConfirmInviteTag"] = "",
        ["ConfirmDescTag"] = "",
        ["Sort"] = 94,
        ["UpdateTime"] = "",
        ["IsNew"] = "",
        ["Disable"] = "",
        ["Icon"] = "rbxassetid://14828509777",
        ["RequireProduct"] = ""
    },
    ["NTP_FreeHouse_014"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["MiniIcon"] = "rbxassetid://15297748861",
        ["RequireFriends"] = "",
        ["Id"] = "NTP_FreeHouse_014",
        ["HouseAssetId"] = "16237623864",
        ["RequireFriendEndTime"] = "",
        ["ConfirmBuyTag"] = "",
        ["ConfirmInviteTag"] = "",
        ["ConfirmDescTag"] = "",
        ["Sort"] = 104,
        ["UpdateTime"] = "",
        ["IsNew"] = "",
        ["Disable"] = "",
        ["Icon"] = "rbxassetid://15297747082",
        ["RequireProduct"] = ""
    },
    ["__index"] = {
        "NTP_PaidHouse_001",
        "NTP_PaidHouse_002",
        "NTP_PaidHouse_003",
        "NTP_PaidHouse_004",
        "NTP_PaidHouse_005",
        "NTP_HousePass_001",
        "NTP_HousePass_002",
        "NTP_ChristmasPass_001",
        "NTP_PaidHouse_006",
        "NTP_PaidHouse_007",
        "NTP_FreeHouse_002",
        "NTP_FreeHouse_003",
        "NTP_FreeHouse_004",
        "NTP_FreeHouse_001",
        "NTP_FreeHouse_005",
        "NTP_FreeHouse_007",
        "NTP_FreeHouse_010",
        "NTP_FreeHouse_008",
        "NTP_FreeHouse_009",
        "NTP_FreeHouse_011",
        "NTP_FreeHouse_012",
        "NTP_FreeHouse_013",
        "NTP_FreeHouse_016",
        "NTP_FreeHouse_017",
        "NTP_FreeHouse_018",
        "NTP_FreeHouse_019",
        "NTP_FreeHouse_014",
        "NTP_FreeHouse_015",
        "NTP_FreeHouse_020",
        "NTP_FreeHouse_021",
        "NTP_FreeHouse_022",
        "NTP_FreeHouse_023",
        "NTP_FreeHouse_024",
        "NTP_FreeHouse_025",
        "NTP_FreeHouse_026",
        "NTP_FreeHouse_027",
        "NTP_FreeHouse_006",
        "NTP_FreeHouse_028",
        "NTP_FreeHouse_029"
    },
    ["NTP_FreeHouse_006"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["MiniIcon"] = "rbxassetid://14452183834",
        ["RequireFriends"] = "",
        ["Id"] = "NTP_FreeHouse_006",
        ["HouseAssetId"] = "14778040711",
        ["RequireFriendEndTime"] = "",
        ["ConfirmBuyTag"] = "",
        ["ConfirmInviteTag"] = "",
        ["ConfirmDescTag"] = "",
        ["Sort"] = 114,
        ["UpdateTime"] = "",
        ["IsNew"] = "",
        ["Disable"] = "",
        ["Icon"] = "rbxassetid://13959888411",
        ["RequireProduct"] = ""
    },
    ["NTP_FreeHouse_004"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["MiniIcon"] = "rbxassetid://14452184231",
        ["RequireFriends"] = "",
        ["Id"] = "NTP_FreeHouse_004",
        ["HouseAssetId"] = "14358567684",
        ["RequireFriendEndTime"] = "",
        ["ConfirmBuyTag"] = "",
        ["ConfirmInviteTag"] = "",
        ["ConfirmDescTag"] = "",
        ["Sort"] = 90,
        ["UpdateTime"] = "",
        ["IsNew"] = "",
        ["Disable"] = "",
        ["Icon"] = "rbxassetid://13255937456",
        ["RequireProduct"] = ""
    },
    ["NTP_FreeHouse_008"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["MiniIcon"] = "rbxassetid://14452183498",
        ["RequireFriends"] = "",
        ["Id"] = "NTP_FreeHouse_008",
        ["HouseAssetId"] = "15853908196",
        ["RequireFriendEndTime"] = "",
        ["ConfirmBuyTag"] = "",
        ["ConfirmInviteTag"] = "",
        ["ConfirmDescTag"] = "",
        ["Sort"] = 95,
        ["UpdateTime"] = "",
        ["IsNew"] = "",
        ["Disable"] = "",
        ["Icon"] = "rbxassetid://14285136294",
        ["RequireProduct"] = ""
    },
    ["NTP_FreeHouse_023"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["MiniIcon"] = "rbxassetid://16729975663",
        ["RequireFriends"] = "",
        ["Id"] = "NTP_FreeHouse_023",
        ["HouseAssetId"] = "17890400675",
        ["RequireFriendEndTime"] = "",
        ["ConfirmBuyTag"] = "",
        ["ConfirmInviteTag"] = "",
        ["ConfirmDescTag"] = "",
        ["Sort"] = 109,
        ["UpdateTime"] = "",
        ["IsNew"] = "",
        ["Disable"] = "",
        ["Icon"] = "rbxassetid://16729970336",
        ["RequireProduct"] = ""
    },
    ["NTP_HousePass_002"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "HousePass",
        ["MiniIcon"] = "rbxassetid://15493052748",
        ["RequireFriends"] = "",
        ["Id"] = "NTP_HousePass_002",
        ["HouseAssetId"] = "16980873379",
        ["RequireFriendEndTime"] = "",
        ["ConfirmBuyTag"] = "",
        ["ConfirmInviteTag"] = "",
        ["ConfirmDescTag"] = "",
        ["Sort"] = 17,
        ["UpdateTime"] = "",
        ["IsNew"] = "",
        ["Disable"] = "",
        ["Icon"] = "rbxassetid://15493049299",
        ["RequireProduct"] = ""
    },
    ["NTP_FreeHouse_019"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["MiniIcon"] = "rbxassetid://16011112090",
        ["RequireFriends"] = "",
        ["Id"] = "NTP_FreeHouse_019",
        ["HouseAssetId"] = "16980842794",
        ["RequireFriendEndTime"] = "",
        ["ConfirmBuyTag"] = "",
        ["ConfirmInviteTag"] = "",
        ["ConfirmDescTag"] = "",
        ["Sort"] = 103,
        ["UpdateTime"] = "",
        ["IsNew"] = "",
        ["Disable"] = "",
        ["Icon"] = "rbxassetid://16011103952",
        ["RequireProduct"] = ""
    },
    ["NTP_FreeHouse_007"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["MiniIcon"] = "rbxassetid://14452183646",
        ["RequireFriends"] = "",
        ["Id"] = "NTP_FreeHouse_007",
        ["HouseAssetId"] = "14778042262",
        ["RequireFriendEndTime"] = "",
        ["ConfirmBuyTag"] = "",
        ["ConfirmInviteTag"] = "",
        ["ConfirmDescTag"] = "",
        ["Sort"] = 93,
        ["UpdateTime"] = "",
        ["IsNew"] = "",
        ["Disable"] = "",
        ["Icon"] = "rbxassetid://14107369270",
        ["RequireProduct"] = ""
    },
    ["NTP_PaidHouse_007"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["MiniIcon"] = "rbxassetid://16253866054",
        ["RequireFriends"] = "",
        ["Id"] = "NTP_PaidHouse_007",
        ["HouseAssetId"] = "",
        ["RequireFriendEndTime"] = "",
        ["ConfirmBuyTag"] = "",
        ["ConfirmInviteTag"] = "",
        ["ConfirmDescTag"] = "",
        ["Sort"] = 20,
        ["UpdateTime"] = "",
        ["IsNew"] = "",
        ["Disable"] = "",
        ["Icon"] = "rbxassetid://16253870780",
        ["RequireProduct"] = "NTP_PaidHouse_007"
    },
    ["NTP_FreeHouse_027"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["MiniIcon"] = "rbxassetid://17572750231",
        ["RequireFriends"] = "",
        ["Id"] = "NTP_FreeHouse_027",
        ["HouseAssetId"] = "",
        ["RequireFriendEndTime"] = "",
        ["ConfirmBuyTag"] = "",
        ["ConfirmInviteTag"] = "",
        ["ConfirmDescTag"] = "",
        ["Sort"] = 113,
        ["UpdateTime"] = "",
        ["IsNew"] = "",
        ["Disable"] = "",
        ["Icon"] = "rbxassetid://17572746508",
        ["RequireProduct"] = ""
    },
    ["NTP_FreeHouse_024"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["MiniIcon"] = "rbxassetid://17089602337",
        ["RequireFriends"] = "",
        ["Id"] = "NTP_FreeHouse_024",
        ["HouseAssetId"] = "17890416235",
        ["RequireFriendEndTime"] = "",
        ["ConfirmBuyTag"] = "",
        ["ConfirmInviteTag"] = "",
        ["ConfirmDescTag"] = "",
        ["Sort"] = 110,
        ["UpdateTime"] = "",
        ["IsNew"] = "",
        ["Disable"] = "",
        ["Icon"] = "rbxassetid://17089594556",
        ["RequireProduct"] = ""
    },
    ["NTP_FreeHouse_021"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["MiniIcon"] = "rbxassetid://16263241256",
        ["RequireFriends"] = "",
        ["Id"] = "NTP_FreeHouse_021",
        ["HouseAssetId"] = "17404694131",
        ["RequireFriendEndTime"] = "",
        ["ConfirmBuyTag"] = "",
        ["ConfirmInviteTag"] = "",
        ["ConfirmDescTag"] = "",
        ["Sort"] = 107,
        ["UpdateTime"] = "",
        ["IsNew"] = "",
        ["Disable"] = "",
        ["Icon"] = "rbxassetid://16283224369",
        ["RequireProduct"] = ""
    },
    ["NTP_FreeHouse_015"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["MiniIcon"] = "rbxassetid://15425901324",
        ["RequireFriends"] = "",
        ["Id"] = "NTP_FreeHouse_015",
        ["HouseAssetId"] = "16622658107",
        ["RequireFriendEndTime"] = "",
        ["ConfirmBuyTag"] = "",
        ["ConfirmInviteTag"] = "",
        ["ConfirmDescTag"] = "",
        ["Sort"] = 105,
        ["UpdateTime"] = "",
        ["IsNew"] = "",
        ["Disable"] = "",
        ["Icon"] = "rbxassetid://15425895634",
        ["RequireProduct"] = ""
    },
    ["NTP_FreeHouse_013"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["MiniIcon"] = "rbxassetid://15156618446",
        ["RequireFriends"] = "",
        ["Id"] = "NTP_FreeHouse_013",
        ["HouseAssetId"] = "16980749837",
        ["RequireFriendEndTime"] = "",
        ["ConfirmBuyTag"] = "",
        ["ConfirmInviteTag"] = "",
        ["ConfirmDescTag"] = "",
        ["Sort"] = 99,
        ["UpdateTime"] = "",
        ["IsNew"] = "",
        ["Disable"] = "",
        ["Icon"] = "rbxassetid://15156616090",
        ["RequireProduct"] = ""
    },
    ["NTP_FreeHouse_001"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["MiniIcon"] = "rbxassetid://14452184666",
        ["RequireFriends"] = "",
        ["Id"] = "NTP_FreeHouse_001",
        ["HouseAssetId"] = "14358554722",
        ["RequireFriendEndTime"] = "",
        ["ConfirmBuyTag"] = "",
        ["ConfirmInviteTag"] = "",
        ["ConfirmDescTag"] = "",
        ["Sort"] = 91,
        ["UpdateTime"] = "",
        ["IsNew"] = "",
        ["Disable"] = "",
        ["Icon"] = "rbxassetid://13255937767",
        ["RequireProduct"] = ""
    },
    ["NTP_FreeHouse_003"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["MiniIcon"] = "rbxassetid://14452184382",
        ["RequireFriends"] = "",
        ["Id"] = "NTP_FreeHouse_003",
        ["HouseAssetId"] = "14358565022",
        ["RequireFriendEndTime"] = "",
        ["ConfirmBuyTag"] = "",
        ["ConfirmInviteTag"] = "",
        ["ConfirmDescTag"] = "",
        ["Sort"] = 89,
        ["UpdateTime"] = "",
        ["IsNew"] = "",
        ["Disable"] = "",
        ["Icon"] = "rbxassetid://13255937555",
        ["RequireProduct"] = ""
    },
    ["NTP_FreeHouse_012"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["MiniIcon"] = "rbxassetid://15092798036",
        ["RequireFriends"] = "",
        ["Id"] = "NTP_FreeHouse_012",
        ["HouseAssetId"] = "15989833507",
        ["RequireFriendEndTime"] = "",
        ["ConfirmBuyTag"] = "",
        ["ConfirmInviteTag"] = "",
        ["ConfirmDescTag"] = "",
        ["Sort"] = 98,
        ["UpdateTime"] = "",
        ["IsNew"] = "",
        ["Disable"] = "",
        ["Icon"] = "rbxassetid://15092794456",
        ["RequireProduct"] = ""
    },
    ["NTP_ChristmasPass_001"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "ChristmasPass",
        ["MiniIcon"] = "rbxassetid://15681092443",
        ["RequireFriends"] = "",
        ["Id"] = "NTP_ChristmasPass_001",
        ["HouseAssetId"] = "16980848317",
        ["RequireFriendEndTime"] = "",
        ["ConfirmBuyTag"] = "",
        ["ConfirmInviteTag"] = "",
        ["ConfirmDescTag"] = "",
        ["Sort"] = 18,
        ["UpdateTime"] = "",
        ["IsNew"] = "",
        ["Disable"] = "",
        ["Icon"] = "rbxassetid://15681086030",
        ["RequireProduct"] = ""
    }
}
