data = {
    ["QuestionnaireNPC_A17"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "K_QUESTIONNAIRE_3STAR",
        ["Option1"] = "K_QUESTIONNAIRE_4STAR",
        ["ID"] = "QuestionnaireNPC_A17",
        ["Option4"] = "K_QUESTIONNAIRE_1STAR",
        ["Content"] = "K_QUESTIONNAIRE_Q_17",
        ["Option3"] = "K_QUESTIONNAIRE_2STAR"
    },
    ["HotelC1"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "HotelC2",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "OpenDialog;DialogHostel;string,CheckIn,Hotel",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "K_HOTEL_NPC_CHOICE_CHAT",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_CHECKIN",
        ["ID"] = "HotelC1",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_C01",
        ["Option3"] = ""
    },
    ["HotelO5"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "",
        ["ID"] = "HotelO5",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_O05",
        ["Option3"] = ""
    },
    ["HotelD2"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "HotelD4",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "HotelD3",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "K_HOTEL_NPC_CHOICE_D2_2",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_D2_1",
        ["ID"] = "HotelD2",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_D02",
        ["Option3"] = ""
    },
    ["HotelC2"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "HotelC4",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "HotelC3",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "K_HOTEL_NPC_CHOICE_C2_2",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_C2_1",
        ["ID"] = "HotelC2",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_C02",
        ["Option3"] = ""
    },
    ["HotelG4"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "HotelG6",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_G4_1",
        ["ID"] = "HotelG4",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_G04",
        ["Option3"] = ""
    },
    ["HotelL3"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "HotelL5",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_L3_1",
        ["ID"] = "HotelL3",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_L03",
        ["Option3"] = ""
    },
    ["HotelH4"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "HotelH6",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_H4_1",
        ["ID"] = "HotelH4",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_H04",
        ["Option3"] = ""
    },
    ["RobloxTheHunt6"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "",
        ["ID"] = "RobloxTheHunt6",
        ["Option4"] = "",
        ["Content"] = "K_ROBLOX315_NPC9",
        ["Option3"] = ""
    },
    ["HotelN1"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "HotelN2",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "OpenDialog;DialogHostel;string,CheckIn,Hotel",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "K_HOTEL_NPC_CHOICE_CHAT",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_CHECKIN",
        ["ID"] = "HotelN1",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_N01",
        ["Option3"] = ""
    },
    ["HotelA5"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "",
        ["ID"] = "HotelA5",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_A05",
        ["Option3"] = ""
    },
    ["HotelB3"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "HotelB5",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_B3_1",
        ["ID"] = "HotelB3",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_B03",
        ["Option3"] = ""
    },
    ["QuestionnaireNPC_A6"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "K_QUESTIONNAIRE_3STAR",
        ["Option1"] = "K_QUESTIONNAIRE_4STAR",
        ["ID"] = "QuestionnaireNPC_A6",
        ["Option4"] = "K_QUESTIONNAIRE_1STAR",
        ["Content"] = "K_QUESTIONNAIRE_Q_6",
        ["Option3"] = "K_QUESTIONNAIRE_2STAR"
    },
    ["HotelE2"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "HotelE4",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "HotelE3",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "K_HOTEL_NPC_CHOICE_E2_2",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_E2_1",
        ["ID"] = "HotelE2",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_E02",
        ["Option3"] = ""
    },
    ["HotelB5"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "",
        ["ID"] = "HotelB5",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_B05",
        ["Option3"] = ""
    },
    ["DM4_GruB1"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "DM4_GruB2",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "K_DM4_GRUB_P1",
        ["ID"] = "DM4_GruB1",
        ["Option4"] = "",
        ["Content"] = "K_DM4_GRUB_1",
        ["Option3"] = ""
    },
    ["HotelI2"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "HotelI4",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "HotelI3",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "K_HOTEL_NPC_CHOICE_I2_2",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_I2_1",
        ["ID"] = "HotelI2",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_I02",
        ["Option3"] = ""
    },
    ["HotelA3"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "HotelA5",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_A3_1",
        ["ID"] = "HotelA3",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_A03",
        ["Option3"] = ""
    },
    ["HalloweenGhost2"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "HalloweenGhost3",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "HalloweenCallback",
        ["Option2"] = "K_HALLOWEEN_GHOST_EXCHANGE",
        ["Option1"] = "K_NEXT",
        ["ID"] = "HalloweenGhost2",
        ["Option4"] = "",
        ["Content"] = "K_HALLOWEEN_GHOST_4",
        ["Option3"] = ""
    },
    ["HotelN2"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "HotelN4",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "HotelN3",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "K_HOTEL_NPC_CHOICE_N2_2",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_N2_1",
        ["ID"] = "HotelN2",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_N02",
        ["Option3"] = ""
    },
    ["HotelE4"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "HotelE6",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_E4_1",
        ["ID"] = "HotelE4",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_E04",
        ["Option3"] = ""
    },
    ["QuestionnaireNPC_START_A1"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "K_QUESTIONNAIRE_BEGIN_A1",
        ["ID"] = "QuestionnaireNPC_START_A1",
        ["Option4"] = "",
        ["Content"] = "K_QUESTIONNAIRE_BEGIN",
        ["Option3"] = ""
    },
    ["HotelO2"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "HotelO4",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "HotelO3",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "K_HOTEL_NPC_CHOICE_O2_2",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_O2_1",
        ["ID"] = "HotelO2",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_O02",
        ["Option3"] = ""
    },
    ["HalloweenGhost4"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "HalloweenCallback",
        ["Option2"] = "K_HALLOWEEN_GHOST_EXCHANGE",
        ["Option1"] = "K_HALLOWEEN_GHOST_8",
        ["ID"] = "HalloweenGhost4",
        ["Option4"] = "",
        ["Content"] = "K_HALLOWEEN_GHOST_6",
        ["Option3"] = ""
    },
    ["QuestionnaireNPC_A16"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "K_QUESTIONNAIRE_Q14_A3",
        ["Option1"] = "K_QUESTIONNAIRE_Q14_A4",
        ["ID"] = "QuestionnaireNPC_A16",
        ["Option4"] = "K_QUESTIONNAIRE_Q14_A1",
        ["Content"] = "K_QUESTIONNAIRE_Q_16",
        ["Option3"] = "K_QUESTIONNAIRE_Q14_A2"
    },
    ["HotelM4"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "HotelM6",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_M4_1",
        ["ID"] = "HotelM4",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_M04",
        ["Option3"] = ""
    },
    ["HotelJ6"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "",
        ["ID"] = "HotelJ6",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_J06",
        ["Option3"] = ""
    },
    ["HotelB6"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "",
        ["ID"] = "HotelB6",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_B06",
        ["Option3"] = ""
    },
    ["HotelH5"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "",
        ["ID"] = "HotelH5",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_H05",
        ["Option3"] = ""
    },
    ["RobloxTheHunt5"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "",
        ["ID"] = "RobloxTheHunt5",
        ["Option4"] = "",
        ["Content"] = "K_ROBLOX315_NPC7",
        ["Option3"] = ""
    },
    ["HotelO6"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "",
        ["ID"] = "HotelO6",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_O06",
        ["Option3"] = ""
    },
    ["HotelM2"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "HotelM4",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "HotelM3",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "K_HOTEL_NPC_CHOICE_M2_2",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_M2_1",
        ["ID"] = "HotelM2",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_M02",
        ["Option3"] = ""
    },
    ["HotelE5"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "",
        ["ID"] = "HotelE5",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_E05",
        ["Option3"] = ""
    },
    ["HotelB1"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "HotelB2",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "OpenDialog;DialogHostel;string,CheckIn,Hotel",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "K_HOTEL_NPC_CHOICE_CHAT",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_CHECKIN",
        ["ID"] = "HotelB1",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_B01",
        ["Option3"] = ""
    },
    ["HotelL6"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "",
        ["ID"] = "HotelL6",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_L06",
        ["Option3"] = ""
    },
    ["HotelA2"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "HotelA4",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "HotelA3",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "K_HOTEL_NPC_CHOICE_A2_2",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_A2_1",
        ["ID"] = "HotelA2",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_A02",
        ["Option3"] = ""
    },
    ["HotelD4"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "HotelD6",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_D4_1",
        ["ID"] = "HotelD4",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_D04",
        ["Option3"] = ""
    },
    ["HotelI5"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "",
        ["ID"] = "HotelI5",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_I05",
        ["Option3"] = ""
    },
    ["HotelJ1"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "HotelJ2",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "OpenDialog;DialogHostel;string,CheckIn,Hotel",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "K_HOTEL_NPC_CHOICE_CHAT",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_CHECKIN",
        ["ID"] = "HotelJ1",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_J01",
        ["Option3"] = ""
    },
    ["HotelO1"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "HotelO2",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "OpenDialog;DialogHostel;string,CheckIn,Hotel",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "K_HOTEL_NPC_CHOICE_CHAT",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_CHECKIN",
        ["ID"] = "HotelO1",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_O01",
        ["Option3"] = ""
    },
    ["HotelG3"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "HotelG5",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_G3_1",
        ["ID"] = "HotelG3",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_G03",
        ["Option3"] = ""
    },
    ["NPC_VV1"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "GiveTool;ProfileDIY:SmallStick_Free09",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "K_NPC_VV_1",
        ["ID"] = "NPC_VV1",
        ["Option4"] = "",
        ["Content"] = "K_NPC_VV",
        ["Option3"] = ""
    },
    ["HotelO3"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "HotelO5",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_O3_1",
        ["ID"] = "HotelO3",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_O03",
        ["Option3"] = ""
    },
    ["HotelK2"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "HotelK4",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "HotelK3",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "K_HOTEL_NPC_CHOICE_K2_2",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_K2_1",
        ["ID"] = "HotelK2",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_K02",
        ["Option3"] = ""
    },
    ["QuestionnaireNPC_A14"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "K_QUESTIONNAIRE_Q14_A3",
        ["Option1"] = "K_QUESTIONNAIRE_Q14_A4",
        ["ID"] = "QuestionnaireNPC_A14",
        ["Option4"] = "K_QUESTIONNAIRE_Q14_A1",
        ["Content"] = "K_QUESTIONNAIRE_Q_14",
        ["Option3"] = "K_QUESTIONNAIRE_Q14_A2"
    },
    ["QuestionnaireNPC_A7"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "K_QUESTIONNAIRE_3STAR",
        ["Option1"] = "K_QUESTIONNAIRE_4STAR",
        ["ID"] = "QuestionnaireNPC_A7",
        ["Option4"] = "K_QUESTIONNAIRE_1STAR",
        ["Content"] = "K_QUESTIONNAIRE_Q_7",
        ["Option3"] = "K_QUESTIONNAIRE_2STAR"
    },
    ["HotelL4"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "HotelL6",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_L4_1",
        ["ID"] = "HotelL4",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_L04",
        ["Option3"] = ""
    },
    ["HotelK6"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "",
        ["ID"] = "HotelK6",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_K06",
        ["Option3"] = ""
    },
    ["HotelK1"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "HotelK2",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "OpenDialog;DialogHostel;string,CheckIn,Hotel",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "K_HOTEL_NPC_CHOICE_CHAT",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_CHECKIN",
        ["ID"] = "HotelK1",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_K01",
        ["Option3"] = ""
    },
    ["HotelI6"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "",
        ["ID"] = "HotelI6",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_I06",
        ["Option3"] = ""
    },
    ["HotelN6"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "",
        ["ID"] = "HotelN6",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_N06",
        ["Option3"] = ""
    },
    ["__index"] = {
        "HotelA1",
        "HotelA2",
        "HotelA3",
        "HotelA4",
        "HotelA5",
        "HotelA6",
        "HotelB1",
        "HotelB2",
        "HotelB3",
        "HotelB4",
        "HotelB5",
        "HotelB6",
        "HotelC1",
        "HotelC2",
        "HotelC3",
        "HotelC4",
        "HotelC5",
        "HotelC6",
        "HotelD1",
        "HotelD2",
        "HotelD3",
        "HotelD4",
        "HotelD5",
        "HotelD6",
        "HotelE1",
        "HotelE2",
        "HotelE3",
        "HotelE4",
        "HotelE5",
        "HotelE6",
        "HotelF1",
        "HotelF2",
        "HotelF3",
        "HotelF4",
        "HotelF5",
        "HotelF6",
        "HotelG1",
        "HotelG2",
        "HotelG3",
        "HotelG4",
        "HotelG5",
        "HotelG6",
        "HotelH1",
        "HotelH2",
        "HotelH3",
        "HotelH4",
        "HotelH5",
        "HotelH6",
        "HotelI1",
        "HotelI2",
        "HotelI3",
        "HotelI4",
        "HotelI5",
        "HotelI6",
        "HotelJ1",
        "HotelJ2",
        "HotelJ3",
        "HotelJ4",
        "HotelJ5",
        "HotelJ6",
        "HotelK1",
        "HotelK2",
        "HotelK3",
        "HotelK4",
        "HotelK5",
        "HotelK6",
        "HotelL1",
        "HotelL2",
        "HotelL3",
        "HotelL4",
        "HotelL5",
        "HotelL6",
        "HotelM1",
        "HotelM2",
        "HotelM3",
        "HotelM4",
        "HotelM5",
        "HotelM6",
        "HotelN1",
        "HotelN2",
        "HotelN3",
        "HotelN4",
        "HotelN5",
        "HotelN6",
        "HotelO1",
        "HotelO2",
        "HotelO3",
        "HotelO4",
        "HotelO5",
        "HotelO6",
        "AirportA1",
        "HalloweenGhost1",
        "HalloweenGhost2",
        "HalloweenGhost3",
        "HalloweenGhost4",
        "RobloxTheHunt1",
        "RobloxTheHunt2",
        "RobloxTheHunt3",
        "RobloxTheHunt4",
        "RobloxTheHunt5",
        "RobloxTheHunt6",
        "QuestionnaireNPC_START_A1",
        "QuestionnaireNPC_A1",
        "QuestionnaireNPC_A2",
        "QuestionnaireNPC_A3",
        "QuestionnaireNPC_A4",
        "QuestionnaireNPC_A5",
        "QuestionnaireNPC_A6",
        "QuestionnaireNPC_A7",
        "QuestionnaireNPC_A8",
        "QuestionnaireNPC_A9",
        "QuestionnaireNPC_A10",
        "QuestionnaireNPC_A11",
        "QuestionnaireNPC_A12",
        "QuestionnaireNPC_A13",
        "QuestionnaireNPC_A14",
        "QuestionnaireNPC_A15",
        "QuestionnaireNPC_A16",
        "QuestionnaireNPC_A17",
        "QuestionnaireNPC_A18",
        "QuestionnaireNPC_A19",
        "QuestionnaireNPC_A20",
        "QuestionnaireNPC_END",
        "FoolsDayNPC1",
        "FoolsDayNPC2",
        "AnniversaryNPC1",
        "NPC_CC1",
        "NPC_VV1",
        "NPC_YJ1",
        "DM4_Phil1",
        "DM4_GruC1",
        "DM4_GruB1",
        "DM4_GruB2",
        "DM4_GruA1",
        "DM4_GruA2",
        "DM4_AVL1",
        "Mayor1"
    },
    ["HotelD5"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "",
        ["ID"] = "HotelD5",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_D05",
        ["Option3"] = ""
    },
    ["DM4_GruB2"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "K_DM4_GRUB_P2",
        ["ID"] = "DM4_GruB2",
        ["Option4"] = "",
        ["Content"] = "K_DM4_GRUB_2",
        ["Option3"] = ""
    },
    ["HalloweenGhost1"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "HalloweenGhost4",
        ["CallBackParam3"] = "HalloweenCallback",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "HalloweenGhost2",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "K_HALLOWEEN_GHOST_3",
        ["Option1"] = "K_HALLOWEEN_GHOST_2",
        ["ID"] = "HalloweenGhost1",
        ["Option4"] = "",
        ["Content"] = "K_HALLOWEEN_GHOST_1",
        ["Option3"] = "K_HALLOWEEN_GHOST_EXCHANGE"
    },
    ["HotelH1"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "HotelH2",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "OpenDialog;DialogHostel;string,CheckIn,Hotel",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "K_HOTEL_NPC_CHOICE_CHAT",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_CHECKIN",
        ["ID"] = "HotelH1",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_H01",
        ["Option3"] = ""
    },
    ["DM4_Phil1"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "K_DM4_PHIL_P1",
        ["ID"] = "DM4_Phil1",
        ["Option4"] = "",
        ["Content"] = "K_DM4_PHIL_1",
        ["Option3"] = ""
    },
    ["AnniversaryNPC1"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "GiveTool;AnniversaryNPC",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "K_QUESTIONNAIRE_END_A",
        ["ID"] = "AnniversaryNPC1",
        ["Option4"] = "",
        ["Content"] = "K_ANNIVERSARY_DIALOG_1",
        ["Option3"] = ""
    },
    ["HotelD1"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "HotelD2",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "OpenDialog;DialogHostel;string,CheckIn,Hotel",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "K_HOTEL_NPC_CHOICE_CHAT",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_CHECKIN",
        ["ID"] = "HotelD1",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_D01",
        ["Option3"] = ""
    },
    ["HotelM5"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "",
        ["ID"] = "HotelM5",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_M05",
        ["Option3"] = ""
    },
    ["FoolsDayNPC1"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "FoolsDayNPC2",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "K_FOOLSDAYNPC_DIALOG_A1",
        ["ID"] = "FoolsDayNPC1",
        ["Option4"] = "",
        ["Content"] = "K_FOOLSDAYNPC_DIALOG_1",
        ["Option3"] = ""
    },
    ["HotelC5"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "",
        ["ID"] = "HotelC5",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_C05",
        ["Option3"] = ""
    },
    ["HotelF1"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "HotelF2",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "OpenDialog;DialogHostel;string,CheckIn,Hotel",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "K_HOTEL_NPC_CHOICE_CHAT",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_CHECKIN",
        ["ID"] = "HotelF1",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_F01",
        ["Option3"] = ""
    },
    ["HotelN5"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "",
        ["ID"] = "HotelN5",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_N05",
        ["Option3"] = ""
    },
    ["HotelH2"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "HotelH4",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "HotelH3",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "K_HOTEL_NPC_CHOICE_H2_2",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_H2_1",
        ["ID"] = "HotelH2",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_H02",
        ["Option3"] = ""
    },
    ["HotelI4"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "HotelI6",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_I4_1",
        ["ID"] = "HotelI4",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_I04",
        ["Option3"] = ""
    },
    ["QuestionnaireNPC_A15"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "K_QUESTIONNAIRE_Q15_A3",
        ["Option1"] = "K_QUESTIONNAIRE_Q15_A4",
        ["ID"] = "QuestionnaireNPC_A15",
        ["Option4"] = "K_QUESTIONNAIRE_Q15_A1",
        ["Content"] = "K_QUESTIONNAIRE_Q_15",
        ["Option3"] = "K_QUESTIONNAIRE_Q15_A2"
    },
    ["QuestionnaireNPC_A20"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "K_QUESTIONNAIRE_Q20_A3",
        ["Option1"] = "K_QUESTIONNAIRE_Q19_A4",
        ["ID"] = "QuestionnaireNPC_A20",
        ["Option4"] = "K_QUESTIONNAIRE_Q20_A1",
        ["Content"] = "K_QUESTIONNAIRE_Q_20",
        ["Option3"] = "K_QUESTIONNAIRE_Q20_A2"
    },
    ["HotelI3"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "HotelI5",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_I3_1",
        ["ID"] = "HotelI3",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_I03",
        ["Option3"] = ""
    },
    ["HotelF2"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "HotelF4",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "HotelF3",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "K_HOTEL_NPC_CHOICE_F2_2",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_F2_1",
        ["ID"] = "HotelF2",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_F02",
        ["Option3"] = ""
    },
    ["QuestionnaireNPC_A4"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "K_QUESTIONNAIRE_3STAR",
        ["Option1"] = "K_QUESTIONNAIRE_4STAR",
        ["ID"] = "QuestionnaireNPC_A4",
        ["Option4"] = "K_QUESTIONNAIRE_1STAR",
        ["Content"] = "K_QUESTIONNAIRE_Q_4",
        ["Option3"] = "K_QUESTIONNAIRE_2STAR"
    },
    ["HotelM6"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "",
        ["ID"] = "HotelM6",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_M06",
        ["Option3"] = ""
    },
    ["HotelG6"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "",
        ["ID"] = "HotelG6",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_G06",
        ["Option3"] = ""
    },
    ["HotelH3"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "HotelH5",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_H3_1",
        ["ID"] = "HotelH3",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_H03",
        ["Option3"] = ""
    },
    ["HotelA4"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "HotelA6",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_A4_1",
        ["ID"] = "HotelA4",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_A04",
        ["Option3"] = ""
    },
    ["HotelG2"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "HotelG4",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "HotelG3",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "K_HOTEL_NPC_CHOICE_G2_2",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_G2_1",
        ["ID"] = "HotelG2",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_G02",
        ["Option3"] = ""
    },
    ["QuestionnaireNPC_A3"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "K_QUESTIONNAIRE_3STAR",
        ["Option1"] = "K_QUESTIONNAIRE_4STAR",
        ["ID"] = "QuestionnaireNPC_A3",
        ["Option4"] = "K_QUESTIONNAIRE_1STAR",
        ["Content"] = "K_QUESTIONNAIRE_Q_3",
        ["Option3"] = "K_QUESTIONNAIRE_2STAR"
    },
    ["HotelC4"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "HotelC6",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_C4_1",
        ["ID"] = "HotelC4",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_C04",
        ["Option3"] = ""
    },
    ["HotelC3"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "HotelC5",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_C3_1",
        ["ID"] = "HotelC3",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_C03",
        ["Option3"] = ""
    },
    ["HotelO4"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "HotelO6",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_O4_1",
        ["ID"] = "HotelO4",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_O04",
        ["Option3"] = ""
    },
    ["HotelA1"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "HotelA2",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "OpenDialog;DialogHostel;string,CheckIn,Hotel",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "K_HOTEL_NPC_CHOICE_CHAT",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_CHECKIN",
        ["ID"] = "HotelA1",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_A01",
        ["Option3"] = ""
    },
    ["HotelJ4"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "HotelJ6",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_J4_1",
        ["ID"] = "HotelJ4",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_J04",
        ["Option3"] = ""
    },
    ["QuestionnaireNPC_A18"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "K_QUESTIONNAIRE_Q18_A3",
        ["Option1"] = "K_QUESTIONNAIRE_Q18_A4",
        ["ID"] = "QuestionnaireNPC_A18",
        ["Option4"] = "K_QUESTIONNAIRE_Q18_A1",
        ["Content"] = "K_QUESTIONNAIRE_Q_18",
        ["Option3"] = "K_QUESTIONNAIRE_Q18_A2"
    },
    ["QuestionnaireNPC_A1"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "K_QUESTIONNAIRE_3STAR",
        ["Option1"] = "K_QUESTIONNAIRE_4STAR",
        ["ID"] = "QuestionnaireNPC_A1",
        ["Option4"] = "K_QUESTIONNAIRE_1STAR",
        ["Content"] = "K_QUESTIONNAIRE_Q_1",
        ["Option3"] = "K_QUESTIONNAIRE_2STAR"
    },
    ["HotelE6"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "",
        ["ID"] = "HotelE6",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_E06",
        ["Option3"] = ""
    },
    ["QuestionnaireNPC_A13"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "K_QUESTIONNAIRE_3STAR",
        ["Option1"] = "K_QUESTIONNAIRE_4STAR",
        ["ID"] = "QuestionnaireNPC_A13",
        ["Option4"] = "K_QUESTIONNAIRE_1STAR",
        ["Content"] = "K_QUESTIONNAIRE_Q_13",
        ["Option3"] = "K_QUESTIONNAIRE_2STAR"
    },
    ["HotelM1"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "HotelM2",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "OpenDialog;DialogHostel;string,CheckIn,Hotel",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "K_HOTEL_NPC_CHOICE_CHAT",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_CHECKIN",
        ["ID"] = "HotelM1",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_M01",
        ["Option3"] = ""
    },
    ["HotelK4"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "HotelK6",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_K4_1",
        ["ID"] = "HotelK4",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_K04",
        ["Option3"] = ""
    },
    ["Mayor1"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "K_MAYOR_NPC_P1",
        ["ID"] = "Mayor1",
        ["Option4"] = "",
        ["Content"] = "K_MAYOR_NPC_1",
        ["Option3"] = ""
    },
    ["HotelK3"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "HotelK5",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_K3_1",
        ["ID"] = "HotelK3",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_K03",
        ["Option3"] = ""
    },
    ["HotelJ2"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "HotelJ4",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "HotelJ3",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "K_HOTEL_NPC_CHOICE_J2_2",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_J2_1",
        ["ID"] = "HotelJ2",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_J02",
        ["Option3"] = ""
    },
    ["DM4_GruA2"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "TeleportToDMGame",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "K_DM4_GRUA_P2",
        ["ID"] = "DM4_GruA2",
        ["Option4"] = "",
        ["Content"] = "K_DM4_GRUA_2",
        ["Option3"] = ""
    },
    ["QuestionnaireNPC_A12"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "K_QUESTIONNAIRE_Q8_A3",
        ["Option1"] = "K_QUESTIONNAIRE_Q8_A4",
        ["ID"] = "QuestionnaireNPC_A12",
        ["Option4"] = "K_QUESTIONNAIRE_Q8_A1",
        ["Content"] = "K_QUESTIONNAIRE_Q_12",
        ["Option3"] = "K_QUESTIONNAIRE_Q8_A2"
    },
    ["RobloxTheHunt4"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "RobloxTheHunt1",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "K_NEXT",
        ["ID"] = "RobloxTheHunt4",
        ["Option4"] = "",
        ["Content"] = "K_ROBLOX315_NPC8",
        ["Option3"] = ""
    },
    ["NPC_YJ1"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = " ",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "K_NPC_YJ_1",
        ["ID"] = "NPC_YJ1",
        ["Option4"] = "",
        ["Content"] = "K_NPC_YJ",
        ["Option3"] = ""
    },
    ["NPC_CC1"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "GiveTool;ProfileDIY:SmallStick_Free08",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "K_NPC_CC_1",
        ["ID"] = "NPC_CC1",
        ["Option4"] = "",
        ["Content"] = "K_NPC_CC",
        ["Option3"] = ""
    },
    ["FoolsDayNPC2"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "GiveTool;BigStick_Free08",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "K_QUESTIONNAIRE_END_A",
        ["ID"] = "FoolsDayNPC2",
        ["Option4"] = "",
        ["Content"] = "K_FOOLSDAYNPC_DIALOG_2",
        ["Option3"] = ""
    },
    ["QuestionnaireNPC_END"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "GiveTool;QuestB",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "K_QUESTIONNAIRE_END_A",
        ["ID"] = "QuestionnaireNPC_END",
        ["Option4"] = "",
        ["Content"] = "K_QUESTIONNAIRE_END",
        ["Option3"] = ""
    },
    ["RobloxTheHunt3"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "RobloxTheHunt1",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "K_NEXT",
        ["ID"] = "RobloxTheHunt3",
        ["Option4"] = "",
        ["Content"] = "K_ROBLOX315_NPC6",
        ["Option3"] = ""
    },
    ["QuestionnaireNPC_A19"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "K_QUESTIONNAIRE_Q19_A3",
        ["Option1"] = "K_QUESTIONNAIRE_Q19_A4",
        ["ID"] = "QuestionnaireNPC_A19",
        ["Option4"] = "K_QUESTIONNAIRE_Q19_A1",
        ["Content"] = "K_QUESTIONNAIRE_Q_19",
        ["Option3"] = "K_QUESTIONNAIRE_Q19_A2"
    },
    ["HotelJ3"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "HotelJ5",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_J3_1",
        ["ID"] = "HotelJ3",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_J03",
        ["Option3"] = ""
    },
    ["QuestionnaireNPC_A5"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "K_QUESTIONNAIRE_3STAR",
        ["Option1"] = "K_QUESTIONNAIRE_4STAR",
        ["ID"] = "QuestionnaireNPC_A5",
        ["Option4"] = "K_QUESTIONNAIRE_1STAR",
        ["Content"] = "K_QUESTIONNAIRE_Q_5",
        ["Option3"] = "K_QUESTIONNAIRE_2STAR"
    },
    ["DM4_GruA1"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "DM4_GruA2",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "K_DM4_GRUA_P1",
        ["ID"] = "DM4_GruA1",
        ["Option4"] = "",
        ["Content"] = "K_DM4_GRUA_1",
        ["Option3"] = ""
    },
    ["QuestionnaireNPC_A11"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "K_QUESTIONNAIRE_3STAR",
        ["Option1"] = "K_QUESTIONNAIRE_4STAR",
        ["ID"] = "QuestionnaireNPC_A11",
        ["Option4"] = "K_QUESTIONNAIRE_1STAR",
        ["Content"] = "K_QUESTIONNAIRE_Q_11",
        ["Option3"] = "K_QUESTIONNAIRE_2STAR"
    },
    ["HotelN4"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "HotelN6",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_N4_1",
        ["ID"] = "HotelN4",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_N04",
        ["Option3"] = ""
    },
    ["QuestionnaireNPC_A9"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "K_QUESTIONNAIRE_3STAR",
        ["Option1"] = "K_QUESTIONNAIRE_4STAR",
        ["ID"] = "QuestionnaireNPC_A9",
        ["Option4"] = "K_QUESTIONNAIRE_1STAR",
        ["Content"] = "K_QUESTIONNAIRE_Q_9",
        ["Option3"] = "K_QUESTIONNAIRE_2STAR"
    },
    ["HotelA6"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "",
        ["ID"] = "HotelA6",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_A06",
        ["Option3"] = ""
    },
    ["QuestionnaireNPC_A8"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "K_QUESTIONNAIRE_Q8_A3",
        ["Option1"] = "K_QUESTIONNAIRE_Q8_A4",
        ["ID"] = "QuestionnaireNPC_A8",
        ["Option4"] = "K_QUESTIONNAIRE_Q8_A1",
        ["Content"] = "K_QUESTIONNAIRE_Q_8",
        ["Option3"] = "K_QUESTIONNAIRE_Q8_A2"
    },
    ["QuestionnaireNPC_A2"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "K_QUESTIONNAIRE_3STAR",
        ["Option1"] = "K_QUESTIONNAIRE_4STAR",
        ["ID"] = "QuestionnaireNPC_A2",
        ["Option4"] = "K_QUESTIONNAIRE_1STAR",
        ["Content"] = "K_QUESTIONNAIRE_Q_2",
        ["Option3"] = "K_QUESTIONNAIRE_2STAR"
    },
    ["DM4_GruC1"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "K_DM4_GRUC_P1",
        ["ID"] = "DM4_GruC1",
        ["Option4"] = "",
        ["Content"] = "K_DM4_GRUC_1",
        ["Option3"] = ""
    },
    ["HotelG5"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "",
        ["ID"] = "HotelG5",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_G05",
        ["Option3"] = ""
    },
    ["RobloxTheHunt2"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "RobloxTheHunt1",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "K_NEXT",
        ["ID"] = "RobloxTheHunt2",
        ["Option4"] = "",
        ["Content"] = "K_ROBLOX315_NPC5",
        ["Option3"] = ""
    },
    ["HotelE3"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "HotelE5",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_E3_1",
        ["ID"] = "HotelE3",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_E03",
        ["Option3"] = ""
    },
    ["RobloxTheHunt1"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "RobloxTheHunt3",
        ["CallBackParam3"] = "TheHuntBadgeCallback;KeepDialog",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "RobloxTheHunt2",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "K_ROBLOX315_NPC3",
        ["Option1"] = "K_ROBLOX315_NPC2",
        ["ID"] = "RobloxTheHunt1",
        ["Option4"] = "",
        ["Content"] = "K_ROBLOX315_NPC1",
        ["Option3"] = "K_ROBLOX315_NPC4"
    },
    ["HotelC6"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "",
        ["ID"] = "HotelC6",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_C06",
        ["Option3"] = ""
    },
    ["HotelE1"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "HotelE2",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "OpenDialog;DialogHostel;string,CheckIn,Hotel",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "K_HOTEL_NPC_CHOICE_CHAT",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_CHECKIN",
        ["ID"] = "HotelE1",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_E01",
        ["Option3"] = ""
    },
    ["HalloweenGhost3"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "HalloweenGhost4",
        ["CallBackParam3"] = "HalloweenCallback",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "K_HALLOWEEN_GHOST_3",
        ["Option1"] = "K_HALLOWEEN_GHOST_7",
        ["ID"] = "HalloweenGhost3",
        ["Option4"] = "",
        ["Content"] = "K_HALLOWEEN_GHOST_5",
        ["Option3"] = "K_HALLOWEEN_GHOST_EXCHANGE"
    },
    ["AirportA1"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "K_HOTEL_NPC_CHOICE_CHAT",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_CHECKIN",
        ["ID"] = "AirportA1",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_O01",
        ["Option3"] = ""
    },
    ["HotelH6"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "",
        ["ID"] = "HotelH6",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_H06",
        ["Option3"] = ""
    },
    ["QuestionnaireNPC_A10"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "K_QUESTIONNAIRE_Q8_A3",
        ["Option1"] = "K_QUESTIONNAIRE_Q8_A4",
        ["ID"] = "QuestionnaireNPC_A10",
        ["Option4"] = "K_QUESTIONNAIRE_Q8_A1",
        ["Content"] = "K_QUESTIONNAIRE_Q_10",
        ["Option3"] = "K_QUESTIONNAIRE_Q8_A2"
    },
    ["HotelB4"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "HotelB6",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_B4_1",
        ["ID"] = "HotelB4",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_B04",
        ["Option3"] = ""
    },
    ["HotelM3"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "HotelM5",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_M3_1",
        ["ID"] = "HotelM3",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_M03",
        ["Option3"] = ""
    },
    ["HotelN3"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "HotelN5",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_N3_1",
        ["ID"] = "HotelN3",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_N03",
        ["Option3"] = ""
    },
    ["DM4_AVL1"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "K_DM4_AVL_P1",
        ["ID"] = "DM4_AVL1",
        ["Option4"] = "",
        ["Content"] = "K_DM4_AVL_1",
        ["Option3"] = ""
    },
    ["HotelL2"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "HotelL4",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "HotelL3",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "K_HOTEL_NPC_CHOICE_L2_2",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_L2_1",
        ["ID"] = "HotelL2",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_L02",
        ["Option3"] = ""
    },
    ["HotelL1"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "HotelL2",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "OpenDialog;DialogHostel;string,CheckIn,Hotel",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "K_HOTEL_NPC_CHOICE_CHAT",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_CHECKIN",
        ["ID"] = "HotelL1",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_L01",
        ["Option3"] = ""
    },
    ["HotelK5"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "",
        ["ID"] = "HotelK5",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_K05",
        ["Option3"] = ""
    },
    ["HotelF6"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "",
        ["ID"] = "HotelF6",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_F06",
        ["Option3"] = ""
    },
    ["HotelF3"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "HotelF5",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_F3_1",
        ["ID"] = "HotelF3",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_F03",
        ["Option3"] = ""
    },
    ["HotelD3"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "HotelD5",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_D3_1",
        ["ID"] = "HotelD3",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_D03",
        ["Option3"] = ""
    },
    ["HotelI1"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "HotelI2",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "OpenDialog;DialogHostel;string,CheckIn,Hotel",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "K_HOTEL_NPC_CHOICE_CHAT",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_CHECKIN",
        ["ID"] = "HotelI1",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_I01",
        ["Option3"] = ""
    },
    ["HotelF4"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "HotelF6",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_F4_1",
        ["ID"] = "HotelF4",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_F04",
        ["Option3"] = ""
    },
    ["HotelJ5"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "",
        ["ID"] = "HotelJ5",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_J05",
        ["Option3"] = ""
    },
    ["HotelB2"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "HotelB4",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "HotelB3",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "K_HOTEL_NPC_CHOICE_B2_2",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_B2_1",
        ["ID"] = "HotelB2",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_B02",
        ["Option3"] = ""
    },
    ["HotelL5"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "",
        ["ID"] = "HotelL5",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_L05",
        ["Option3"] = ""
    },
    ["HotelD6"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "",
        ["ID"] = "HotelD6",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_D06",
        ["Option3"] = ""
    },
    ["HotelF5"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "",
        ["Option1"] = "",
        ["ID"] = "HotelF5",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_F05",
        ["Option3"] = ""
    },
    ["HotelG1"] = {
        ["ToNext4"] = "",
        ["ToNext2"] = "HotelG2",
        ["CallBackParam3"] = "",
        ["CallBackParam1"] = "OpenDialog;DialogHostel;string,CheckIn,Hotel",
        ["ToNext1"] = "",
        ["CallBackParam4"] = "",
        ["ToNext3"] = "",
        ["CallBackParam2"] = "",
        ["Option2"] = "K_HOTEL_NPC_CHOICE_CHAT",
        ["Option1"] = "K_HOTEL_NPC_CHOICE_CHECKIN",
        ["ID"] = "HotelG1",
        ["Option4"] = "",
        ["Content"] = "K_HOTEL_NPC_G01",
        ["Option3"] = ""
    }
}
