data = {
    ["Frame_Free01"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["Frame_Impact"] = "",
        ["Categoty"] = "Frame",
        ["Img"] = "rbxassetid://16532178678",
        ["IsNew"] = "",
        ["Desc"] = "",
        ["Frame_Out"] = "",
        ["Font"] = "",
        ["Name"] = "",
        ["RequireFriends"] = "",
        ["ID"] = "Frame_Free01",
        ["RequireProduct"] = "",
        ["Order"] = 4,
        ["Disable"] = ""
    },
    ["__index"] = {
        "BasePic_Free01",
        "BasePic_Free02",
        "Frame_Free01",
        "Frame_Free02",
        "Frame_Free03",
        "Frame_OneYear",
        "BigStick_Free01",
        "BigStick_Free02",
        "BigStick_Free03",
        "BigStick_Free04",
        "BigStick_Free05",
        "BigStick_Free06",
        "BigStick_Free07",
        "BigStick_Free08",
        "BigStick_Free09",
        "SmallStick_Free01",
        "SmallStick_Free02",
        "SmallStick_Free03",
        "SmallStick_Free04",
        "SmallStick_Free05",
        "SmallStick_Free06",
        "SmallStick_Free07",
        "SmallStick_Free08",
        "SmallStick_Free09",
        "Text_Free01",
        "Text_Free02",
        "Text_Free03",
        "Text_Free04"
    },
    ["SmallStick_Free03"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["Frame_Impact"] = "",
        ["Categoty"] = "SmallStick",
        ["Img"] = "rbxassetid://16531286568",
        ["IsNew"] = "",
        ["Desc"] = "",
        ["Frame_Out"] = "",
        ["Font"] = "",
        ["Name"] = "",
        ["RequireFriends"] = "",
        ["ID"] = "SmallStick_Free03",
        ["RequireProduct"] = "",
        ["Order"] = 97,
        ["Disable"] = ""
    },
    ["SmallStick_Free04"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["Frame_Impact"] = "",
        ["Categoty"] = "SmallStick",
        ["Img"] = "rbxassetid://16531286422",
        ["IsNew"] = "",
        ["Desc"] = "",
        ["Frame_Out"] = "",
        ["Font"] = "",
        ["Name"] = "",
        ["RequireFriends"] = "",
        ["ID"] = "SmallStick_Free04",
        ["RequireProduct"] = "",
        ["Order"] = 96,
        ["Disable"] = ""
    },
    ["BigStick_Free03"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["Frame_Impact"] = "",
        ["Categoty"] = "BigStick",
        ["Img"] = "rbxassetid://16531287494",
        ["IsNew"] = "",
        ["Desc"] = "",
        ["Frame_Out"] = "",
        ["Font"] = "",
        ["Name"] = "",
        ["RequireFriends"] = "",
        ["ID"] = "BigStick_Free03",
        ["RequireProduct"] = "",
        ["Order"] = 97,
        ["Disable"] = ""
    },
    ["BasePic_Free01"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["Frame_Impact"] = "",
        ["Categoty"] = "BasePic",
        ["Img"] = "rbxassetid://16532395466",
        ["IsNew"] = "",
        ["Desc"] = "",
        ["Frame_Out"] = "",
        ["Font"] = "",
        ["Name"] = "",
        ["RequireFriends"] = "",
        ["ID"] = "BasePic_Free01",
        ["RequireProduct"] = "",
        ["Order"] = 2,
        ["Disable"] = ""
    },
    ["BigStick_Free02"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["Frame_Impact"] = "",
        ["Categoty"] = "BigStick",
        ["Img"] = "rbxassetid://16531287617",
        ["IsNew"] = "",
        ["Desc"] = "",
        ["Frame_Out"] = "",
        ["Font"] = "",
        ["Name"] = "",
        ["RequireFriends"] = "",
        ["ID"] = "BigStick_Free02",
        ["RequireProduct"] = "",
        ["Order"] = 98,
        ["Disable"] = ""
    },
    ["Frame_Free03"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["Frame_Impact"] = "",
        ["Categoty"] = "Frame",
        ["Img"] = "rbxassetid://16532179199",
        ["IsNew"] = "",
        ["Desc"] = "",
        ["Frame_Out"] = "",
        ["Font"] = "",
        ["Name"] = "",
        ["RequireFriends"] = "",
        ["ID"] = "Frame_Free03",
        ["RequireProduct"] = "",
        ["Order"] = 2,
        ["Disable"] = ""
    },
    ["Text_Free04"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["Frame_Impact"] = "",
        ["Categoty"] = "Text",
        ["Img"] = "rbxassetid://16459423204",
        ["IsNew"] = "",
        ["Desc"] = "",
        ["Frame_Out"] = "",
        ["Font"] = "GrenzeGotisch",
        ["Name"] = "",
        ["RequireFriends"] = "",
        ["ID"] = "Text_Free04",
        ["RequireProduct"] = "",
        ["Order"] = 1,
        ["Disable"] = ""
    },
    ["Text_Free01"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["Frame_Impact"] = "",
        ["Categoty"] = "Text",
        ["Img"] = "rbxassetid://16459423204",
        ["IsNew"] = "",
        ["Desc"] = "",
        ["Frame_Out"] = "",
        ["Font"] = "Bangers",
        ["Name"] = "",
        ["RequireFriends"] = "",
        ["ID"] = "Text_Free01",
        ["RequireProduct"] = "",
        ["Order"] = 4,
        ["Disable"] = ""
    },
    ["SmallStick_Free07"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["Frame_Impact"] = "",
        ["Categoty"] = "SmallStick",
        ["Img"] = "rbxassetid://16793982096",
        ["IsNew"] = "2024-04-03",
        ["Desc"] = "",
        ["Frame_Out"] = "",
        ["Font"] = "",
        ["Name"] = "",
        ["RequireFriends"] = "",
        ["ID"] = "SmallStick_Free07",
        ["RequireProduct"] = "",
        ["Order"] = 93,
        ["Disable"] = true
    },
    ["SmallStick_Free08"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["Frame_Impact"] = "",
        ["Categoty"] = "SmallStick",
        ["Img"] = "rbxassetid://17261637487",
        ["IsNew"] = "2029-05-05",
        ["Desc"] = "",
        ["Frame_Out"] = "",
        ["Font"] = "",
        ["Name"] = "",
        ["RequireFriends"] = "",
        ["ID"] = "SmallStick_Free08",
        ["RequireProduct"] = "",
        ["Order"] = 92,
        ["Disable"] = true
    },
    ["Text_Free03"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["Frame_Impact"] = "",
        ["Categoty"] = "Text",
        ["Img"] = "rbxassetid://16459423204",
        ["IsNew"] = "",
        ["Desc"] = "",
        ["Frame_Out"] = "",
        ["Font"] = "AmaticSC",
        ["Name"] = "",
        ["RequireFriends"] = "",
        ["ID"] = "Text_Free03",
        ["RequireProduct"] = "",
        ["Order"] = 2,
        ["Disable"] = ""
    },
    ["BigStick_Free04"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["Frame_Impact"] = "",
        ["Categoty"] = "BigStick",
        ["Img"] = "rbxassetid://16531287327",
        ["IsNew"] = "",
        ["Desc"] = "",
        ["Frame_Out"] = "",
        ["Font"] = "",
        ["Name"] = "",
        ["RequireFriends"] = "",
        ["ID"] = "BigStick_Free04",
        ["RequireProduct"] = "",
        ["Order"] = 96,
        ["Disable"] = ""
    },
    ["Text_Free02"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["Frame_Impact"] = "",
        ["Categoty"] = "Text",
        ["Img"] = "rbxassetid://16459423204",
        ["IsNew"] = "",
        ["Desc"] = "",
        ["Frame_Out"] = "",
        ["Font"] = "Creepster",
        ["Name"] = "",
        ["RequireFriends"] = "",
        ["ID"] = "Text_Free02",
        ["RequireProduct"] = "",
        ["Order"] = 3,
        ["Disable"] = ""
    },
    ["BigStick_Free08"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["Frame_Impact"] = "",
        ["Categoty"] = "BigStick",
        ["Img"] = "rbxassetid://16793982277",
        ["IsNew"] = "2024-04-03",
        ["Desc"] = "",
        ["Frame_Out"] = "",
        ["Font"] = "",
        ["Name"] = "",
        ["RequireFriends"] = "",
        ["ID"] = "BigStick_Free08",
        ["RequireProduct"] = "",
        ["Order"] = 92,
        ["Disable"] = true
    },
    ["BasePic_Free02"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["Frame_Impact"] = "",
        ["Categoty"] = "BasePic",
        ["Img"] = "rbxassetid://16532395229",
        ["IsNew"] = "",
        ["Desc"] = "",
        ["Frame_Out"] = "",
        ["Font"] = "",
        ["Name"] = "",
        ["RequireFriends"] = "",
        ["ID"] = "BasePic_Free02",
        ["RequireProduct"] = "",
        ["Order"] = 1,
        ["Disable"] = ""
    },
    ["BigStick_Free07"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["Frame_Impact"] = "",
        ["Categoty"] = "BigStick",
        ["Img"] = "rbxassetid://16793982449",
        ["IsNew"] = "2024-04-03",
        ["Desc"] = "",
        ["Frame_Out"] = "",
        ["Font"] = "",
        ["Name"] = "",
        ["RequireFriends"] = "",
        ["ID"] = "BigStick_Free07",
        ["RequireProduct"] = "",
        ["Order"] = 93,
        ["Disable"] = true
    },
    ["SmallStick_Free09"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["Frame_Impact"] = "",
        ["Categoty"] = "SmallStick",
        ["Img"] = "rbxassetid://17261637422",
        ["IsNew"] = "2029-05-05",
        ["Desc"] = "",
        ["Frame_Out"] = "",
        ["Font"] = "",
        ["Name"] = "",
        ["RequireFriends"] = "",
        ["ID"] = "SmallStick_Free09",
        ["RequireProduct"] = "",
        ["Order"] = 91,
        ["Disable"] = true
    },
    ["SmallStick_Free06"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["Frame_Impact"] = "",
        ["Categoty"] = "SmallStick",
        ["Img"] = "rbxassetid://16531286039",
        ["IsNew"] = "",
        ["Desc"] = "",
        ["Frame_Out"] = "",
        ["Font"] = "",
        ["Name"] = "",
        ["RequireFriends"] = "",
        ["ID"] = "SmallStick_Free06",
        ["RequireProduct"] = "",
        ["Order"] = 94,
        ["Disable"] = ""
    },
    ["SmallStick_Free05"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["Frame_Impact"] = "",
        ["Categoty"] = "SmallStick",
        ["Img"] = "rbxassetid://16531286270",
        ["IsNew"] = "",
        ["Desc"] = "",
        ["Frame_Out"] = "",
        ["Font"] = "",
        ["Name"] = "",
        ["RequireFriends"] = "",
        ["ID"] = "SmallStick_Free05",
        ["RequireProduct"] = "",
        ["Order"] = 95,
        ["Disable"] = ""
    },
    ["Frame_OneYear"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["Frame_Impact"] = "",
        ["Categoty"] = "Frame",
        ["Img"] = "rbxassetid://16993807914",
        ["IsNew"] = "2024-04-17",
        ["Desc"] = "",
        ["Frame_Out"] = "",
        ["Font"] = "",
        ["Name"] = "",
        ["RequireFriends"] = "",
        ["ID"] = "Frame_OneYear",
        ["RequireProduct"] = "",
        ["Order"] = 1,
        ["Disable"] = true
    },
    ["BigStick_Free01"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["Frame_Impact"] = "",
        ["Categoty"] = "BigStick",
        ["Img"] = "rbxassetid://16531287738",
        ["IsNew"] = "",
        ["Desc"] = "",
        ["Frame_Out"] = "",
        ["Font"] = "",
        ["Name"] = "",
        ["RequireFriends"] = "",
        ["ID"] = "BigStick_Free01",
        ["RequireProduct"] = "",
        ["Order"] = 99,
        ["Disable"] = ""
    },
    ["SmallStick_Free02"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["Frame_Impact"] = "",
        ["Categoty"] = "SmallStick",
        ["Img"] = "rbxassetid://16531286723",
        ["IsNew"] = "",
        ["Desc"] = "",
        ["Frame_Out"] = "",
        ["Font"] = "",
        ["Name"] = "",
        ["RequireFriends"] = "",
        ["ID"] = "SmallStick_Free02",
        ["RequireProduct"] = "",
        ["Order"] = 98,
        ["Disable"] = ""
    },
    ["BigStick_Free05"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["Frame_Impact"] = "",
        ["Categoty"] = "BigStick",
        ["Img"] = "rbxassetid://16531286930",
        ["IsNew"] = "",
        ["Desc"] = "",
        ["Frame_Out"] = "",
        ["Font"] = "",
        ["Name"] = "",
        ["RequireFriends"] = "",
        ["ID"] = "BigStick_Free05",
        ["RequireProduct"] = "",
        ["Order"] = 95,
        ["Disable"] = ""
    },
    ["SmallStick_Free01"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["Frame_Impact"] = "",
        ["Categoty"] = "SmallStick",
        ["Img"] = "rbxassetid://16531287168",
        ["IsNew"] = "",
        ["Desc"] = "",
        ["Frame_Out"] = "",
        ["Font"] = "",
        ["Name"] = "",
        ["RequireFriends"] = "",
        ["ID"] = "SmallStick_Free01",
        ["RequireProduct"] = "",
        ["Order"] = 99,
        ["Disable"] = ""
    },
    ["BigStick_Free09"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["Frame_Impact"] = "",
        ["Categoty"] = "BigStick",
        ["Img"] = "rbxassetid://17261637577",
        ["IsNew"] = "2029-05-05",
        ["Desc"] = "",
        ["Frame_Out"] = "",
        ["Font"] = "",
        ["Name"] = "",
        ["RequireFriends"] = "",
        ["ID"] = "BigStick_Free09",
        ["RequireProduct"] = "",
        ["Order"] = 91,
        ["Disable"] = true
    },
    ["Frame_Free02"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["Frame_Impact"] = "",
        ["Categoty"] = "Frame",
        ["Img"] = "rbxassetid://16532178930",
        ["IsNew"] = "",
        ["Desc"] = "",
        ["Frame_Out"] = "",
        ["Font"] = "",
        ["Name"] = "",
        ["RequireFriends"] = "",
        ["ID"] = "Frame_Free02",
        ["RequireProduct"] = "",
        ["Order"] = 3,
        ["Disable"] = ""
    },
    ["BigStick_Free06"] = {
        ["RequireLikes"] = "",
        ["RequirePass"] = "",
        ["Frame_Impact"] = "",
        ["Categoty"] = "BigStick",
        ["Img"] = "rbxassetid://16531285547",
        ["IsNew"] = "",
        ["Desc"] = "",
        ["Frame_Out"] = "",
        ["Font"] = "",
        ["Name"] = "",
        ["RequireFriends"] = "",
        ["ID"] = "BigStick_Free06",
        ["RequireProduct"] = "",
        ["Order"] = 94,
        ["Disable"] = ""
    }
}
