data = {
    ["BlackList"] = {
        "Attack",
        "Idle",
        "Cost",
        "Icon",
        "Image",
        "Noise",
        "Model",
        "Visual",
        "Desc",
        "KeyFrame",
        "CatchAnim",
        "Repeat",
        "HideAnim",
        "SAanim",
        "ATANIM",
        "PointAttack",
        "Stats",
        "Flight.Base",
        "Flight.Animation",
        "SpecialAbility.Title",
        "SpecialAbility.Desc",
        "SpecialAbility.Cost",
        "SpecialAbility.OnUse",
        "HideCenter",
        "Sound",
        "Angry",
        "SpawnCost",
        "noLook",
        "HideRate",
        "Walk",
        "AnimSpeed",
        "Boss",
        "EnemyType",
        "HiddenHide",
        "IdleSpeed",
        "NoShow",
        "StopAnim",
        "Color",
        "ExtraStats",
        "EnemySpecies",
        "DefaultVariant",
        "Effect.Visual",
        "Effect.Sound",
        "Effect.Icon"
    },
    ["getStat"] = "function: 0x5ca04ba4bfbde89e",
    ["SummonFix"] = "function: 0x4618cbe453e82d4e",
    ["GetDesc"] = "function: 0x1c3865fb6ea87d2e",
    ["UpdateTroop"] = "function: 0x95b077921d45067e",
    ["Desc"] = {
        ["SpecialAbility.Duration"] = "How long the special ability will last.",
        ["Ability.Spawner"] = "This summon can spawn mobs or it has an attack.",
        ["Effect.Duration"] = "The status effect will last this long.",
        ["Offense.Damage"] = "How much damage the summon deals.",
        ["Range"] = "The distance this hero is able to reach.",
        ["FriendlyEffect.MaxHP"] = "This status effect will only affect enemies with less than this much hp.",
        ["SelfBonus.Damage"] = "Boost applied to damage of hero.",
        ["SummonLimit"] = "The hero can only have so many summons out at a time.",
        ["Flight.Offset"] = "The hero's offset from its placement origin.",
        ["FriendlyEffect.BaseDuration"] = "The status effect will last this long. Changed by the hero during runtime.",
        ["Offense.Range"] = "The range of the summon.",
        ["EffectPriority"] = "This hero will prioritize summons/enemies without status effects.",
        ["NoStun"] = "The hero is unable to be stunned.",
        ["BaseDamage"] = "How much damage this hero is able to deal each time it attacks. Changed by the hero during runtime.",
        ["FriendlyEffect.NoStack"] = "List of status effects that this effect is unable to be stacked with.",
        ["DamageRange.High"] = "The high end of the damage range.",
        ["BaseRate"] = "How often the hero will attack. Changed by the hero during runtime.",
        ["SelfBonus.Cost"] = "Discount applied to hero.",
        ["FriendlyEffect.BaseDamage"] = "The enemy take this much damage every tick. Changed by the hero during runtime.",
        ["SummonStats.[]"] = "The stats of the summon.",
        ["BaseRange"] = "The distance this hero is able to reach. Changed by the hero during runtime.",
        ["Offense"] = "This summon has an attack and range.",
        ["Ability.Friendly"] = "This summon is friendly and will harm enemies.",
        ["FriendlyEffect.Title"] = "The name of the status effect.",
        ["ViewRange"] = "The hero will look at but not attack heroes within this range.",
        ["Speed"] = "How fast the summon will move.",
        ["SpecialAbility.Limit"] = "How many times you can use the special.",
        ["SelfBonus.Range"] = "Boost applied to range of hero.",
        ["Tax"] = "How much mana the hero will take away each wave, this is multiplied by the number of players other than you.",
        ["Bonus.Cost"] = "Discount applied to cost of heroes within it's own range.",
        ["AreaDamage"] = "The hero will apply partial splash damage to enemies nearby the target, this is the splash range.",
        ["Ability.Spawner.Enemy"] = "Name of the summon this summon can spawn.",
        ["Name"] = "The name of the summon.",
        ["TrapType"] = "The type of trap El Goblino will place on the path.",
        ["FriendlyEffect.Damage"] = "The enemy take this much damage every tick.",
        ["Effect.MaxHP"] = "This status effect will only affect enemies with less than this much hp.",
        ["SummonCount"] = "The number of summons that will spawner per attack.",
        ["FriendlyEffect.BaseSpeed"] = "The enemy will have its speed multiplied by this much. Changed by the hero during runtime.",
        ["SummonRange"] = "The hero summons are connected to its range.",
        ["SelfBonus.Rate"] = "Boost applied to rate of hero.",
        ["SpecialAbility"] = "This hero has a special attack/ability.",
        ["Ability.FullImmunity"] = "This summon cannot be affected by status effects.",
        ["FriendlyEffect.Splash"] = "The Effect will be applied to nearby enemies.",
        ["Bonus.Range"] = "Boost applied to range of heroes within it's own range.",
        ["FriendlyEffect.Cooldown"] = "The enemy will not be able to be affected by this status effect for this much time.",
        ["FriendlyEffect.Duration"] = "The status effect will last this long.",
        ["FriendlyEffect.Speed"] = "The enemy will have its speed multiplied by this much.",
        ["FriendlyEffect"] = "The hero will apply this status effect to the summon when it attacks.",
        ["Effect.BaseDuration"] = "The status effect will last this long. Changed by the hero during runtime.",
        ["Title"] = "The name of the summon.",
        ["Effect.BaseDamage"] = "The enemy take this much damage every tick. Changed by the hero during runtime.",
        ["DamageMin"] = "This hero will deal atleast this much damage when it attacks.",
        ["Flight.NoLook"] = "Determines whether the hero looks at the target it is attacking.",
        ["Effect.Damage"] = "The enemy take this much damage every tick.",
        ["ChainMultiple"] = "This damage will be multiplied by this amount for each enemy chained.",
        ["SummonStats"] = "A list of stats for the summon.",
        ["Flight"] = "This hero is offset from its placement origin.",
        ["Effect.Splash"] = "The Effect will be applied to nearby enemies.",
        ["Effect.NoStack"] = "List of status effects that this effect is unable to be stacked with.",
        ["RatePause"] = "How long the hero will wait between quick fire attacks.",
        ["Effect.Speed"] = "The enemy will have its speed multiplied by this much.",
        ["Health"] = "How much health the summon has.",
        ["Effect.Title"] = "The name of the status effect.",
        ["Effect"] = "The hero will apply this status effect to the enemy when it attacks.",
        ["SpecialAbility.AddSell"] = "The special ability will add its cost times this number to the hero sell amount.",
        ["SpecialAbility.Cooldown"] = "How long it takes the special to be used again.",
        ["DamageRange"] = "The hero can will deal between high and low damage, calculation may vary per hero.",
        ["Flight.Flat"] = "The hero will remain flat instead of tilting towards enemies.",
        ["Flight.Speed"] = "The speed at which the hero will travel about its origin.",
        ["Ability.NoBump"] = "This summon does not deal damage by running into enemies.",
        ["SelfBonus"] = "The hero boosts its own stats.",
        ["RocketDamage"] = "How much damge Spark's Rockets deal.",
        ["Duration"] = "How long the hero will attack for.",
        ["Bonus.Damage"] = "Boost applied to damage of heroes within it's own range.",
        ["CenterArea"] = "Attacks will originate from the center of the hero instead of the enemy.",
        ["Bonus.Rate"] = "Boost applied to rate of heroes within it's own range.",
        ["ProjectileArc"] = "How high the projectile will travel in the air.",
        ["Bonus"] = "The hero boosts the stats of other heroes.",
        ["Offense.HiddenDetection"] = "Can the summon attack hidden enemies?",
        ["Offense.Rate"] = "How fast the summon attacks.",
        ["TargetFriend"] = "This hero will target friendly summons.",
        ["HiddenDetection"] = "Is the hero able to attack hidden enemies?",
        ["Ability.Spawner.Rate"] = "How fast the summons/attack happens.",
        ["Ability.Invincible"] = "This summon cannot die.",
        ["SlowTarget"] = "This hero will slow down while it is attacking.",
        ["Effect.Cooldown"] = "The enemy will not be able to be affected by this status effect for this much time.",
        ["DragonFlame"] = "Yasuke special ability.",
        ["Ability"] = "A list of special abilities that the summon has.",
        ["Effect.BaseSpeed"] = "The enemy will have its speed multiplied by this much. Changed by the hero during runtime.",
        ["Rate"] = "How often the hero will attack.",
        ["Summon"] = "The hero will spawn/summon this when it attacks.",
        ["DamagePercent"] = "This hero will attack the enemy for a percentage of its health.",
        ["ProjectileSpeed"] = "How speed at which the projectile will travel.",
        ["Ability.DamageBoost"] = "The health of the summon will be affected by the hero's damage boost.",
        ["Farm"] = "How much mana the hero will give you each wave.",
        ["MaxHit"] = "The max number of enemies this hero can hit.",
        ["DamageRange.Low"] = "The low end of the damage range.",
        ["Damage"] = "How much damage this hero is able to deal each time it attacks.",
        ["TargetClosest"] = "This hero will target the enemy closest to it instead of the enemy closest to the end."
    }
}
