data = {
    ["Runes"] = {
        {"Somberock Rune"},
        {"Archopos Rune", "Grufflin Rune"},
        {"Groato Rune", "Hattrix Rune"},
        {"Skadean Rune"},
        {"Umaisho Matcha"},
        {"Calamander Candy"},
        {"Cacmeow Rune"},
        {"Cragildae Rune"},
        {"Maskomedy Rune", "Theaterror Rune"},
        {"Nyanto Rune"},
        {"Vigimantè Rune"},
        {"Daeferno Rune", "Cragildae Rune"},
        {"Umaisho Matcha", "Lumiline Rune", "Bionotic Rune", "Mourveil Rune", "Bubbull Rune", "Staligant Rune"},
        {"Tulenna Rune", "Daeferno Rune"},
        {"Voltenchant Rune"},
        {"Partybug Rune"},
        {"Cryotera Rune", "Mawthra Rune", "Tufflaze Rune"},
        {"Spectatik Rune"},
        {"Cerebopod Rune", "Malotrick Rune"},
        {"Hattrix Rune"},
        {"Thornet Rune", "Calamander Candy"},
        {"Suomous Rune", "Nyanto Rune"}
    },
    ["Doodles"] = {
        {"Bellbird"},
        {"Prarnaw"},
        {"Oribirb"},
        {"Kitsen", "Chronos", "Kowosu", "Shyce", "Malotrick", "Coalt"},
        {"Pebblett"},
        {"Mold", "Moss"},
        {"Twigon", "Agotoad", "Yagoat", "Faunsprout", "Larvennae"},
        {
            "Buoyanseal",
            "Glimring",
            "Zerzura",
            "Parabite",
            "Sizzlrimp",
            "Dizipore",
            "Auron",
            "Jestwirl",
            "Rheode",
            "Fluppy",
            "Wiglet",
            "Flaskit",
            "Junipyro",
            "Maskrow",
            "Sharpup",
            "Squonk",
            "Azúpion",
            "Qilintel",
            "Potunk",
            "Koriyu",
            "Gekotta",
            "Squinana"
        },
        {"Cocosquid"},
        {"Springling"},
        {"Bearby", "Fishel", "Ahket", "Griblo", "Skoplet", "Saltot", "Threec", "Artifixie", "Edibebi"},
        {"Vipember", "Zapion"},
        {"Cacmeow"},
        {
            "Blossaur",
            "Foxsy",
            "Bearby",
            "Fishel",
            "Infurnius",
            "Squonk",
            "Ostigon",
            "Foyal",
            "Exiled",
            "Minjoule",
            "Gekotta",
            "Mauspunch",
            "Ahket",
            "Lizzerts"
        },
        {"Artifixie", "Mauspunch", "Scorm", "Saltot", "Threec", "Diyossua", "Buoyanseal", "Jewelit", "Edibebi"},
        {"Dodotor"},
        {"Dustoon"},
        {"Hyekeke", "Gorpo", "Foxsy", "Mabat", "Fishel", "Perfumi", "Impling", "Fledgeo", "Reliconis", "Sobbuoy"},
        {"Foresatl", "Wisp"},
        {"Potunk"},
        {"Squinana"},
        {"Hopolatte"},
        {"Ahket", "Potunk"},
        {"Floxy"},
        {
            "Hyekeke",
            "Foxsy",
            "Mabat",
            "Snobobo",
            "Bellbird",
            "Ciyrup",
            "Artifixie",
            "Oribirb",
            "Aquafi",
            "Trilosect",
            "Allicute",
            "Hippop",
            "Foresatl",
            "Riffrat",
            "Appluff",
            "Rosebug",
            "Coalt",
            "Muncheez",
            "Slibble",
            "Dewaffe",
            "Ahket",
            "Hollihare",
            "Exiled",
            "Gekotta"
        },
        {"Glimring"},
        {"Ciyrup", "Grimsugar", "Skitis", "Saltot"},
        {"Threasant"},
        {"Zapion", "Mant"},
        {"Jellupy"},
        {"Foyal", "Potunk", "Maximutt"},
        {"Cranigunk", "Cinderling"},
        {"Lacergen"},
        {"Eftue"},
        {"Yonna"},
        {"Trilosect"},
        {"Tyki"},
        {"Scorm"},
        {"Dramask", "Xenoxious", "Nibblen"},
        {"Alptusk"},
        {"Tasjoney"},
        {"Bowlinguin", "Feesh", "Lizzerts"},
        {"Allicute"},
        {"Mold", "Snobat"},
        {"Lilbulb"},
        {"Jewelit", "Fluffi", "Pubu", "Minjoule", "Weecub", "Cthuwu", "Infurnius", "Dizipore", "Gauzli"},
        {"Spunny"},
        {"Schiwi"},
        {"Kelpie"},
        {"Blossaur", "Aquafi", "Shmellow", "Gekotta", "Rheode", "Prophant"},
        {"Dramask", "Maximutt", "Allicute"},
        {"Tortles"},
        {"Grunkul", "Potunk", "Arachniak"},
        {"Crystik"},
        {"Sprubble"},
        {"Partybug"},
        {"Tortles"},
        {"Megglit", "Grom"}
    },
    ["Skins"] = {
        {["Spunny"] = {4}},
        {["Louis"] = {4}},
        {["Groato"] = {4}},
        {
            ["Bunswirl"] = {5},
            ["Moss"] = {6},
            ["Horbeast"] = {3},
            ["Gowatt"] = {4},
            ["Jelluminous"] = {6},
            ["Partybug"] = {6},
            ["Octonut"] = {5},
            ["Cryotera"] = {2},
            ["Louis"] = {7}
        },
        {["Henchum"] = {4}},
        {["Fruitoad"] = {1}},
        {["Voltatoo"] = {3}},
        {["Polargeist"] = {3}},
        {["Voltenchant"] = {3}, ["Grufflin"] = {6}, ["Frigale"] = {2}},
        {["Voltatoo"] = {3}, ["Humbiscus"] = {4}},
        {["Springling"] = {4}},
        {["Humbiscus"] = {4}},
        {["Skadean"] = {5}, ["Gowatt"] = {3}, ["Corrolizard"] = {3}},
        {["Louis"] = {6}},
        {["Magmotode"] = {1}},
        {["Mold"] = {5}, ["Moss"] = {4}, ["Swoptar"] = {5}},
        {["Swoptar"] = {4}},
        {["Fruitoad"] = {5}},
        {["Humbiscus"] = {5}, ["Mold"] = {3}},
        {
            ["Springling"] = {4},
            ["Mawthra"] = {3},
            ["Megortles"] = {1},
            ["Partybug"] = {4},
            ["Spirasol"] = {5},
            ["Prickles"] = {1},
            ["Klydaskunk"] = {4},
            ["Archopos"] = {2},
            ["Tulenna"] = {2},
            ["Cacmeow"] = {4},
            ["Antenaflight"] = {4},
            ["Vixalor"] = {2},
            ["Grufflin"] = {4},
            ["Octonut"] = {1, 6},
            ["Fruitoad"] = {5},
            ["Polargeist"] = {3},
            ["Magmotode"] = {1},
            ["Jelluminous"] = {5},
            ["Glubbie"] = {5}
        },
        {["Horbeast"] = {4}},
        {["Calamander"] = {4}},
        {["Somberock"] = {4}},
        {["Moyai"] = {4}},
        {["Somberock"] = {3}},
        {["Gomutt"] = {2}},
        {["Jelluminous"] = {5}},
        {["Megortles"] = {3}, ["Candeigon"] = {3}, ["Klydaskunk"] = {2}, ["Maelzuri"] = {6, 7}},
        {["Moss"] = {5}},
        {["Henchum"] = {6}},
        {["Voltatoo"] = {3}},
        {["Groato"] = {2}},
        {["Pompaboar"] = {6}},
        {["Bunswirl"] = {3}},
        {["Partybug"] = {6}, ["Corrolizard"] = {4}, ["Spirasol"] = {3}},
        {["Humbiscus"] = {4}},
        {["Polargeist"] = {2}, ["Kelpimer"] = {4}, ["Jelluminous"] = {6}},
        {["Groato"] = {5}},
        {["Springling"] = {2}, ["Skadean"] = {4}},
        {["Octonut"] = {6}},
        {
            ["Bunswirl"] = {2, 4},
            ["Henchum"] = {2, 4},
            ["Lumiline"] = {1},
            ["Antenaflight"] = {1},
            ["Spectatik"] = {3, 4},
            ["Leazar"] = {3, 4},
            ["Gowatt"] = {5},
            ["Thornet"] = {3},
            ["Magmotode"] = {2},
            ["Djinneko"] = {2},
            ["Maelzuri"] = {6}
        },
        {["Staligant"] = {2}},
        {["Mawthra"] = {2}},
        {["Spectatik"] = {3}, ["Frigale"] = {5}, ["Klydaskunk"] = {1}},
        {["Leazar"] = {3}},
        {["Maskomedy"] = {1}},
        {["Monolugg"] = {5}},
        {["Louis"] = {7}},
        {["Mourveil"] = {4}},
        {["Kelpimer"] = {3}, ["Malotrick"] = {1}},
        {["Octonut"] = 5},
        {["Thornet"] = {4}},
        {["Cryotera"] = {3}},
        {["Gomutt"] = {3}},
        {["Antenaflight"] = {3}, ["Lumiline"] = {3}},
        {["Swoptar"] = {3}},
        {["Tufflaze"] = {1}},
        {["Megortles"] = {2}},
        {["Swoptar"] = {1}},
        {["Kelpimer"] = {2}},
        {["Vuliable"] = {1}, ["Bionotic"] = {2}, ["Lumiline"] = {4}},
        {["Zapoeira"] = {4}, ["Fruitoad"] = {3}},
        {["Grufflin"] = {3}},
        {["Tufflaze"] = {2}, ["Partybug"] = {4}, ["Djinneko"] = {2}},
        {["Tulenna"] = {1}},
        {
            ["Mawthra"] = {2},
            ["Mold"] = {4},
            ["Somberock"] = {3},
            ["Lumiline"] = {3, 4},
            ["Gomutt"] = {2},
            ["Vuliable"] = {1},
            ["Spunny"] = {2},
            ["Horbeast"] = {2},
            ["Spectatik"] = {4},
            ["Kelpimer"] = {2, 3},
            ["Incinelisk"] = {3},
            ["Junipyro"] = {1},
            ["Abyssent"] = {2, 3},
            ["Klydaskunk"] = {1},
            ["Cryotera"] = {3},
            ["Humbiscus"] = {5},
            ["Candeigon"] = {2},
            ["Swoptar"] = {4, 5},
            ["Henchum"] = {5},
            ["Tulenna"] = {1},
            ["Voltenchant"] = {3},
            ["Antenaflight"] = {3},
            ["Groato"] = {5},
            ["Malotrick"] = {1},
            ["Skadean"] = {4},
            ["Grufflin"] = {5},
            ["Gowatt"] = {3},
            ["Fruitoad"] = {3, 4},
            ["Polargeist"] = {2},
            ["Pompaboar"] = {4, 6},
            ["Mourveil"] = {4},
            ["Maelzuri"] = {7}
        },
        {["Frigale"] = {4}},
        {["Prickles"] = {1}},
        {["Springling"] = {4}},
        {["Jelluminous"] = {4}},
        {["Corrolizard"] = {2}},
        {["Springling"] = {5}},
        {["Moyai"] = {3}, ["Horbeast"] = {2}},
        {["Archopos"] = {1}, ["Monolugg"] = {6}},
        {["Polargeist"] = {4}},
        {["Horbeast"] = {3}},
        {["Pompaboar"] = {5}},
        {["Mold"] = {4}},
        {["Gowatt"] = {5}, ["Vixalor"] = {2}},
        {["Calamander"] = {1}},
        {["Xenoxious"] = {3}, ["Partybug"] = {5}},
        {["Louis"] = {5}},
        {
            ["Marigrimm"] = {1},
            ["Archopos"] = {2},
            ["Cacmeow"] = {4},
            ["Skadean"] = {5},
            ["Grufflin"] = {6},
            ["Xenoxious"] = {2},
            ["Spirasol"] = {4},
            ["Kibara"] = {1},
            ["Incinelisk"] = {4}
        },
        {["Maelzuri"] = {4}},
        {
            ["Candeigon"] = {2},
            ["Moss"] = {6},
            ["Gomutt"] = {4},
            ["Malotrick"] = {2},
            ["Leazar"] = {5},
            ["Abyssent"] = {2, 3},
            ["Bionotic"] = {1},
            ["Magmotode"] = {2},
            ["Incinelisk"] = {4}
        },
        {["Bunswirl"] = {3}},
        {["Horbeast"] = {1}},
        {["Horbeast"] = {2}},
        {["Spirasol"] = {2}},
        {["Tufflaze"] = {3}, ["Moss"] = {5}},
        {
            ["Springling"] = {5},
            ["Somberock"] = {2},
            ["Moyai"] = {2},
            ["Louis"] = {6},
            ["Partybug"] = {2},
            ["Leazar"] = {5},
            ["Spirasol"] = {2},
            ["Zapoeira"] = {4},
            ["Gomutt"] = {4},
            ["Incinelisk"] = {3},
            ["Cacmeow"] = {3},
            ["Pompaboar"] = {5},
            ["Voltatoo"] = {1},
            ["Skadean"] = {3},
            ["Grufflin"] = {4},
            ["Octonut"] = {4},
            ["Fruitoad"] = {4},
            ["Tufflaze"] = {3},
            ["Bionotic"] = {3},
            ["Monolugg"] = {3},
            ["Groato"] = {4}
        },
        {["Jelluminous"] = {3}},
        {["Marigrimm"] = {1}},
        {["Calamander"] = {5}, ["Bionotic"] = {3}, ["Marigrimm"] = {2}},
        {
            ["Mold"] = {5},
            ["Moss"] = {4},
            ["Vuliable"] = {1},
            ["Frigale"] = {5},
            ["Somberock"] = {4},
            ["Megortles"] = {2, 3},
            ["Partybug"] = {5, 7},
            ["Xenoxious"] = {3},
            ["Voltatoo"] = {3},
            ["Kelpimer"] = {4},
            ["Candeigon"] = {3},
            ["Polargeist"] = {4},
            ["Klydaskunk"] = {2, 4},
            ["Marigrimm"] = {2},
            ["Jelluminous"] = {4},
            ["Henchum"] = {3, 6},
            ["Tulenna"] = {2},
            ["Horbeast"] = {4},
            ["Corrolizard"] = {3},
            ["Calamander"] = {5},
            ["Malotrick"] = {2},
            ["Spirasol"] = {3},
            ["Staligant"] = {2},
            ["Bionotic"] = {2, 4},
            ["Archopos"] = {1},
            ["Tufflaze"] = {2},
            ["Mourveil"] = {3},
            ["Monolugg"] = {6},
            ["Groato"] = {6}
        },
        {["Megortles"] = {3}},
        {["Somberock"] = {2}, ["Grufflin"] = {5}},
        {["Bionotic"] = {4}},
        {["Horbeast"] = {2}},
        {["Spirasol"] = {4}},
        {["Mourveil"] = {3}},
        {["Louis"] = {2}},
        {
            ["Spunny"] = {4},
            ["Mawthra"] = {3},
            ["Partybug"] = {7},
            ["Octonut"] = {4},
            ["Moyai"] = {2, 3, 4},
            ["Cacmeow"] = {1},
            ["Clangutang"] = {3},
            ["Mourveil"] = {2},
            ["Skadean"] = {3},
            ["Grufflin"] = {4},
            ["Xenoxious"] = {2},
            ["Frigale"] = {4},
            ["Thornet"] = {1},
            ["Zapoeira"] = {3},
            ["Monolugg"] = {4},
            ["Corrolizard"] = {2}
        },
        {["Spirasol"] = {5}},
        {
            ["Springling"] = {3},
            ["Candeigon"] = {1},
            ["Somberock"] = {3},
            ["Djinneko"] = {1},
            ["Gowatt"] = {2},
            ["Spunny"] = {3},
            ["Spectatik"] = {2},
            ["Partybug"] = {1},
            ["Spirasol"] = {1},
            ["Swoptar"] = {2},
            ["Voltenchant"] = {1},
            ["Terruma"] = {1},
            ["Medikrow"] = {1},
            ["Skadean"] = {1},
            ["Grufflin"] = {3},
            ["Octonut"] = {2},
            ["Junipyro"] = {2},
            ["Calamander"] = {3, 4},
            ["Pompaboar"] = {2},
            ["Megortles"] = {1},
            ["Maelzuri"] = {4}
        },
        {["Groato"] = {6}},
        {["Henchum"] = {5}},
        {["Spirasol"] = {2}},
        {["Cacmeow"] = {3}},
        {["Kibara"] = {1}, ["Bunswirl"] = {5}, ["Antenaflight"] = {4}, ["Gowatt"] = {4}}
    },
    ["BPRunes"] = {
        {"Academy Theaterror Rune", "Academy Maskomedy Rune"},
        {"Zenith Groato Rune", "Solidarity Hattrix Rune"},
        {"Auric Spectatik Rune"},
        {"Kitty Bionotic Rune"},
        {"Admiral Nyanto Rune"},
        {"Carnelian Lumiline Rune"},
        {"Crimson Cryotera Rune"},
        {"Blossom Tufflaze Rune"},
        {"Crimson Cryotera Rune"},
        {"Pristine Thornet Rune"},
        {"Celestial Somberock Rune"},
        {"Exalted Malotrick Rune"},
        {"Alacritous Archopos Rune"},
        {"Alacritous Archopos Rune"},
        {"Azure Partybug Rune"},
        {"Litterfall Cacmeow Rune", "Galaxy Staligant Rune"},
        {"Lemondrop Vigimantè Rune"}
    },
    ["Mounts"] = {{"31"}, {"26"}, {"10"}, {"9"}, {"21"}, {"20", "25"}, {"20", "21", "22", "23", "24", "33"}, {"22"}}
}
