data = {
    ["HalloweenCapsules"] = {
        {["LayoutOrder"] = 1, ["Name"] = "Winged Capsule", ["Cost"] = 6},
        {["LayoutOrder"] = 2, ["Name"] = "Cauldron Capsule", ["Cost"] = 6},
        {["LayoutOrder"] = 3, ["Name"] = "Witch Capsule", ["Cost"] = 6}
    },
    ["Encounterable"] = {
        ["Mold"] = {["Rarity"] = 2, ["Skin"] = 9},
        ["Hattrix"] = {["Rarity"] = 1, ["Skin"] = 1},
        ["Archuma"] = {["Rarity"] = 2, ["Skin"] = 7},
        ["Glummish"] = {["Rarity"] = 2, ["Skin"] = 8},
        ["Partybug"] = {["Rarity"] = 2, ["Skin"] = 9},
        ["Bunsweet"] = {["Rarity"] = 2, ["Skin"] = 10},
        ["Plipo"] = {["Rarity"] = 3, ["Skin"] = 9},
        ["Tortles"] = {["Rarity"] = 2, ["Skin"] = 9},
        ["Squed"] = {["Rarity"] = 3, ["Skin"] = 8},
        ["Shmellow"] = {["Rarity"] = 3, ["Skin"] = 4},
        ["Skrappey"] = {["Rarity"] = 1, ["Skin"] = 6},
        ["Wisp"] = {["Rarity"] = 2, ["Skin"] = 5},
        ["Glubbie"] = {["Rarity"] = 1, ["Skin"] = 7},
        ["Moss"] = {["Rarity"] = 2, ["Skin"] = 10},
        ["Snobat"] = {["Rarity"] = 3, ["Skin"] = 7},
        ["Pupskey"] = {["Rarity"] = 1, ["Skin"] = 6},
        ["Wiglet"] = {["Rarity"] = 3, ["Skin"] = 8},
        ["Riffrat"] = {["Rarity"] = 3, ["Skin"] = 8},
        ["Geckgoo"] = {["Rarity"] = 3, ["Skin"] = 7},
        ["Squonk"] = {["Rarity"] = 1, ["Skin"] = 8},
        ["Klydaskunk"] = {["Rarity"] = 2, ["Skin"] = 8},
        ["Swoptar"] = {["Rarity"] = 2, ["Skin"] = 9},
        ["Rosebug"] = {["Rarity"] = 3, ["Skin"] = 6},
        ["Borbo"] = {["Rarity"] = 3, ["Skin"] = 8},
        ["Kitsen"] = {["Rarity"] = 1, ["Skin"] = 7},
        ["Statikeet"] = {["Rarity"] = 3, ["Skin"] = 8},
        ["Vipember"] = {["Rarity"] = 1, ["Skin"] = 7},
        ["Tabbolt"] = {["Rarity"] = 1, ["Skin"] = 6},
        ["Slibble"] = {["Rarity"] = 3, ["Skin"] = 5},
        ["Junipyro"] = {["Rarity"] = 1, ["Skin"] = 5},
        ["Yagoat"] = {["Rarity"] = 3, ["Skin"] = 7},
        ["Nibblen"] = {["Rarity"] = 3, ["Skin"] = 6},
        ["Grimsugar"] = {["Rarity"] = 2, ["Skin"] = 8},
        ["Pandishi"] = {["Rarity"] = 1, ["Skin"] = 7}
    },
    ["Purchasable"] = {
        ["Chronos"] = {["Cost"] = 2000, ["Skin"] = 6, ["Name"] = "Chronos", ["Showcase"] = "Chronos"},
        ["Candeigon"] = {["Showcase"] = "Indigoo", ["Cost"] = 45, ["Name"] = "Candeigon", ["Skin"] = 7},
        ["Leazar"] = {["Showcase"] = "Leapo", ["Cost"] = 80, ["Name"] = "Leazar", ["Skin"] = 8},
        ["Djinneko"] = {["Showcase"] = "Apurrition", ["Cost"] = 250, ["Name"] = "Djinneko", ["Skin"] = 7},
        ["Gomutt"] = {["Cost"] = 120, ["Skin"] = 10, ["Name"] = "Gomutt", ["Showcase"] = "Muttish"},
        ["Louis"] = {["Showcase"] = "Louis", ["Cost"] = 180, ["Name"] = "Louis", ["Skin"] = 10},
        ["Spunny"] = {["Showcase"] = "Spunny", ["Cost"] = 210, ["Name"] = "Spunny", ["Skin"] = 8},
        ["Hattrix"] = {["Showcase"] = "Hattrix", ["Cost"] = 200, ["Name"] = "Hattrix", ["Skin"] = 1},
        ["Jelluminous"] = {["Cost"] = 60, ["Skin"] = 8, ["Name"] = "Jelluminous", ["Showcase"] = "Lilbulb"},
        ["Kelpimer"] = {["Showcase"] = "Kelpie", ["Cost"] = 300, ["Name"] = "Kelpimer", ["Skin"] = 8},
        ["Xenoxious"] = {["Cost"] = 800, ["Showcase"] = "Xenoxious", ["Name"] = "Xenoxious", ["Skin"] = 10},
        ["Spirasol"] = {["Cost"] = 500, ["Skin"] = 8, ["Name"] = "Spirasol", ["Showcase"] = "Kowosu"},
        ["Abyssent"] = {["Showcase"] = "Angerler", ["Cost"] = 275, ["Name"] = "Abyssent", ["Skin"] = 9},
        ["Prickles"] = {["Showcase"] = "Needling", ["Cost"] = 100, ["Name"] = "Prickles", ["Skin"] = 6},
        ["Theaterror"] = {["Cost"] = 110, ["Skin"] = 7, ["Name"] = "Theaterror", ["Showcase"] = "Dramask"},
        ["Humbiscus"] = {["Showcase"] = "Flittum", ["Cost"] = 65, ["Name"] = "Humbiscus", ["Skin"] = 7},
        ["Marigrimm"] = {["Showcase"] = "Wydling", ["Cost"] = 140, ["Name"] = "Marigrimm", ["Skin"] = 7},
        ["Zapoeira"] = {["Showcase"] = "Tabbolt", ["Cost"] = 395, ["Name"] = "Zapoeira", ["Skin"] = 6},
        ["Clangutang"] = {["Showcase"] = "Skrappey", ["Cost"] = 390, ["Name"] = "Clangutang", ["Skin"] = 6},
        ["Wolfreeze"] = {["Showcase"] = "Pupskey", ["Cost"] = 400, ["Name"] = "Wolfreeze", ["Skin"] = 6},
        ["Horbeast"] = {["Cost"] = 600, ["Skin"] = 10, ["Name"] = "Horbeast", ["Showcase"] = "Shelldo"},
        ["Cacmeow"] = {["Cost"] = 95, ["Showcase"] = "Cacmeow", ["Name"] = "Cacmeow", ["Skin"] = 8},
        ["Skadean"] = {["Showcase"] = "Schiwi", ["Cost"] = 190, ["Name"] = "Skadean", ["Skin"] = 8},
        ["Malotrick"] = {["Cost"] = 220, ["Showcase"] = "Malotrick", ["Name"] = "Malotrick", ["Skin"] = 6},
        ["Kibara"] = {["Cost"] = 450, ["Skin"] = 6, ["Name"] = "Kibara", ["Showcase"] = "Shyce"},
        ["Antenaflight"] = {["Showcase"] = "Larvennae", ["Cost"] = 40, ["Name"] = "Antenaflight", ["Skin"] = 6},
        ["Medikrow"] = {["Showcase"] = "Maskrow", ["Cost"] = 75, ["Name"] = "Medikrow", ["Skin"] = 7},
        ["Terruma"] = {["Showcase"] = "Coalt", ["Cost"] = 230, ["Name"] = "Terruma", ["Skin"] = 8},
        ["Runewt"] = {["Showcase"] = "Runewt", ["Cost"] = 150, ["Name"] = "Runewt", ["Skin"] = 2},
        ["Drakothread"] = {["Cost"] = 175, ["Skin"] = 4, ["Name"] = "Drakothread", ["Showcase"] = "Twigon"},
        ["Springling"] = {["Cost"] = 55, ["Skin"] = 8, ["Name"] = "Springling", ["Showcase"] = "Springling"},
        ["Incinelisk"] = {["Showcase"] = "Vipember", ["Cost"] = 405, ["Name"] = "Incinelisk", ["Skin"] = 7}
    },
    ["GetRarityTable"] = "function: 0x00000000d68bb299"
}
