data = {
    "Earthquake",
    "Retribution",
    "Venom Bite",
    "Disarm",
    "Gem Blast",
    "Rainmaker",
    "Food Fight",
    "Burning Orb",
    "Rust",
    "Taunt",
    "Starbreaker",
    "Shifting Winds",
    "Psychoforce",
    "Insect Instinct",
    "Flashbang",
    "Iron Slash",
    "Feral Fury",
    "Firecracker",
    "Cone of Cold",
    "Climate Shot",
    "Daze",
    "Electrify",
    "Tsunami",
    "Pylons",
    "Somnambulism"
}
