data = {
    main = {
        ["ItemsRedeemable"] = "function: 0x0000000049b2ec2d",
        ["AwardExp"] = "function: 0x000000002e416ded",
        ["GetItemsUpdatedSignal"] = "function: 0x00000000d8370fc5",
        ["GetExpChangedSignal"] = "function: 0x00000000fce1a02d",
        ["DAILY_EXP_AMOUNT"] = 500,
        ["EXP_NAME"] = "CandyCorn",
        ["VERSION"] = 10,
        ["GetRankItems"] = "function: 0x00000000150dfe9d",
        ["PREMIUM_THEME"] = Color3.fromRGB(81, 0, 122),
        ["BACKGROUND_IMAGE"] = "rbxassetid://11100915432",
        ["BP_LEVEL_SHIFT"] = -20,
        ["GetHighestTier"] = "function: 0x000000007bd65fe5",
        ["EXP_DROP_RATE"] = 0.4,
        ["EXP_PER_RANK"] = 500,
        ["GetItemsAvailableSignal"] = "function: 0x00000000e19897ed",
        ["Start"] = "function: 0x0000000048b7d36d",
        ["COLOR_THEME"] = Color3.fromRGB(255, 85, 127),
        ["HasPremiumTrack"] = "function: 0x00000000b38fe1bd",
        ["RedeemedItem"] = "function: 0x00000000bbc0427d",
        ["RANK_COST"] = 500,
        ["PurchasePremium"] = "function: 0x000000008caa494d",
        ["GetTimeLeft"] = "function: 0x00000000b96624bd",
        ["IsActive"] = "function: 0x00000000f9e3b5ed",
        ["END_TIME"] = 0,
        ["GetItemRanks"] = "function: 0x00000000c4991b8d",
        ["EXP_PER_MOB"] = 5,
        ["RedeemItem"] = "function: 0x00000000b0a07c6d",
        ["PurchaseRanks"] = "function: 0x00000000a6b13b3d",
        ["WEEKLY_EXP_AMOUNT"] = 1500,
        ["PREMIUM_TEXT_COLOR"] = Color3.fromRGB(254, 69, 216),
        ["GetPlayerExp"] = "function: 0x000000004c9723d5",
        ["GetFolder"] = "function: 0x0000000055b425e5",
        ["Init"] = "function: 0x000000007ff8f00d",
        ["PREMIUM_COST"] = 2000,
        ["GetTrack"] = "function: 0x000000007a7839ad",
        ["FREE_TEXT_COLOR"] = Color3.fromRGB(243, 97, 0),
        ["GetItemRedeemFailedSignal"] = "function: 0x000000003812272d",
        ["GetPremiumChangedSignal"] = "function: 0x00000000b3715f9d",
        ["START_TIME"] = 0,
        ["FindNextItemTier"] = "function: 0x000000008d25607d",
        ["EXP_ICON"] = "rbxassetid://5763298818",
        ["EXTENDED_PREMIUM_THEME"] = Color3.fromRGB(254, 69, 216),
        ["EXTENDED_COLOR_THEME"] = Color3.fromRGB(243, 97, 0),
        ["XP_BAR_COLOR_THEME"] = Color3.fromRGB(170, 0, 0),
        ["BUTTON_COLOR"] = Color3.fromRGB(255, 85, 0)
    },
    Tracklist = {
        ["Track"] = {
            {
                ["PremiumCount"] = 1,
                ["ItemCount"] = 1,
                ["Item"] = "TrickorTreatBucket",
                ["PremiumItem"] = "DragonBoneTail",
                ["PremiumItemLimitedDyeable"] = true,
                ["ItemLimitedDyeable"] = true
            },
            {
                ["PremiumFreeRandomItem"] = "EquipmentChest",
                ["ItemCount"] = 1,
                ["Item"] = "HarvestDyeBox",
                ["PremiumItem"] = "HarvestAuraChest",
                ["PremiumCount"] = 1
            },
            {["PremiumCount"] = 1, ["ItemCount"] = 5, ["Item"] = "PetCandy", ["PremiumItem"] = "HauntedParasol"},
            {
                ["PremiumCount"] = 1,
                ["ItemCount"] = 1,
                ["Item"] = "SuperEquipmentChest",
                ["PremiumItem"] = "HarvestDyeBox"
            },
            {["PremiumCount"] = 400, ["ItemCount"] = 1, ["Item"] = "HarvestAuraChest", ["PremiumItem"] = "Crystals"},
            {
                ["PremiumFreeRandomItem"] = "EquipmentChest",
                ["ItemCount"] = 1,
                ["Item"] = "PumpkinVineTail",
                ["PremiumItem"] = "HarvestAuraChest",
                ["PremiumCount"] = 1
            },
            {["PremiumCount"] = 1, ["ItemCount"] = 1, ["Item"] = "HarvestDyeBox", ["PremiumItem"] = "HandHat"},
            {["PremiumCount"] = 1, ["ItemCount"] = 5, ["Item"] = "PetCandy", ["PremiumItem"] = "ZombieTitle"},
            {
                ["PremiumFreeRandomItem"] = "EquipmentChest",
                ["ItemCount"] = 1,
                ["Item"] = "SuperEquipmentChest",
                ["PremiumItem"] = "HarvestAuraChest",
                ["PremiumCount"] = 1
            },
            {["PremiumCount"] = 400, ["ItemCount"] = 1, ["Item"] = "HarvestAuraChest", ["PremiumItem"] = "Crystals"},
            {
                ["PremiumFreeRandomItem"] = "EquipmentChest",
                ["ItemCount"] = 1,
                ["Item"] = "ScarecrowHat",
                ["PremiumItem"] = "HarvestAuraChest",
                ["PremiumCount"] = 1
            },
            {
                ["PremiumCount"] = 1,
                ["ItemCount"] = 1,
                ["Item"] = "HarvestDyeBox",
                ["PremiumItem"] = "NailHead",
                ["PremiumItemLimitedDyeable"] = true
            },
            {["PremiumCount"] = 1, ["ItemCount"] = 5, ["Item"] = "PetCandy", ["PremiumItem"] = "HarvestDyeBox"},
            {
                ["PremiumFreeRandomItem"] = "EquipmentChest",
                ["ItemCount"] = 1,
                ["Item"] = "CreepyTitle",
                ["PremiumItem"] = "HarvestAuraChest",
                ["PremiumCount"] = 1
            },
            {["PremiumCount"] = 400, ["ItemCount"] = 1, ["Item"] = "HarvestAuraChest", ["PremiumItem"] = "Crystals"},
            {
                ["PremiumFreeRandomItem"] = "EquipmentChest",
                ["ItemCount"] = 1,
                ["Item"] = "SpiderHat",
                ["PremiumItem"] = "HarvestAuraChest",
                ["PremiumCount"] = 1
            },
            {
                ["PremiumCount"] = 1,
                ["ItemCount"] = 1,
                ["Item"] = "HarvestDyeBox",
                ["PremiumItem"] = "JackOLantern",
                ["PremiumItemLimitedDyeable"] = true
            },
            {["PremiumCount"] = 1, ["ItemCount"] = 5, ["Item"] = "PetCandy", ["PremiumItem"] = "WitchTitle"},
            {
                ["PremiumFreeRandomItem"] = "EquipmentChest",
                ["ItemCount"] = 1,
                ["Item"] = "SuperEquipmentChest",
                ["PremiumItem"] = "HarvestAuraChest",
                ["PremiumCount"] = 1
            },
            {["PremiumCount"] = 400, ["ItemCount"] = 1, ["Item"] = "BackKnife", ["PremiumItem"] = "Crystals"},
            {
                ["PremiumFreeRandomItem"] = "EquipmentChest",
                ["ItemCount"] = 1,
                ["Item"] = "SuperEquipmentChest",
                ["PremiumItem"] = "HarvestAuraChest",
                ["PremiumCount"] = 1
            },
            {
                ["PremiumCount"] = 1,
                ["ItemCount"] = 1,
                ["Item"] = "HarvestDyeBox",
                ["PremiumItem"] = "EyesBackground",
                ["PremiumItemLimitedDyeable"] = true
            },
            {["PremiumCount"] = 1, ["ItemCount"] = 5, ["Item"] = "PetCandy", ["PremiumItem"] = "HarvestDyeBox"},
            {
                ["PremiumFreeRandomItem"] = "EquipmentChest",
                ["ItemCount"] = 1,
                ["Item"] = "SuperEquipmentChest",
                ["PremiumItem"] = "HarvestAuraChest",
                ["PremiumCount"] = 1
            },
            {["PremiumCount"] = 400, ["ItemCount"] = 1, ["Item"] = "HarvestAuraChest", ["PremiumItem"] = "Crystals"},
            {
                ["PremiumFreeRandomItem"] = "EquipmentChest",
                ["ItemCount"] = 1,
                ["Item"] = "HarvestDyeBox",
                ["PremiumItem"] = "HarvestAuraChest",
                ["PremiumCount"] = 1
            },
            {
                ["PremiumCount"] = 1,
                ["ItemCount"] = 1,
                ["Item"] = "SuperEquipmentChest",
                ["PremiumItem"] = "SplitBodysuit",
                ["PremiumItemLimitedDyeable"] = true
            },
            {["PremiumCount"] = 1, ["ItemCount"] = 5, ["Item"] = "PetCandy", ["PremiumItem"] = "WebWeaverTitle"},
            {
                ["PremiumCount"] = 1,
                ["ItemCount"] = 1,
                ["Item"] = "SuperEquipmentChest",
                ["PremiumItem"] = "BackTentacles",
                ["PremiumItemLimitedDyeable"] = true
            },
            {
                ["PremiumCount"] = 1,
                ["ItemCount"] = 1,
                ["Item"] = "GhoulSuit2",
                ["PremiumItem"] = "OrangeCatMount",
                ["ItemLimitedDyeable"] = true
            },
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 1, ["ItemCount"] = 1, ["Item"] = "JackOLanternSilver", ["PremiumItem"] = "BatBoxPurple"},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {
                ["PremiumCount"] = 1,
                ["ItemCount"] = 1,
                ["Item"] = "JackOLanternSilver",
                ["PremiumItem"] = "BatBoxPurple",
                ["ItemLimitedDyeable"] = true
            },
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 1, ["ItemCount"] = 1, ["Item"] = "JackOLanternGold", ["PremiumItem"] = "BatBoxPurple"},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {
                ["PremiumCount"] = 1,
                ["ItemCount"] = 1,
                ["Item"] = "JackOLanternGold",
                ["PremiumItem"] = "BatBoxPurple",
                ["ItemLimitedDyeable"] = true
            },
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 1, ["ItemCount"] = 1, ["Item"] = "JackOLanternBlack", ["PremiumItem"] = "BatBoxPurple"},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {
                ["PremiumCount"] = 1,
                ["ItemCount"] = 1,
                ["Item"] = "JackOLanternBlack",
                ["PremiumItem"] = "BatBoxPurple",
                ["ItemLimitedDyeable"] = true
            },
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {["PremiumCount"] = 0, ["ItemCount"] = 0, ["Item"] = "", ["PremiumItem"] = "", ["BlankTile"] = true},
            {
                ["PremiumCount"] = 1,
                ["ItemCount"] = 1,
                ["Item"] = "BlackCatMount",
                ["PremiumItem"] = "VampireHunterTitle"
            }
        },
        ["HighestTier"] = 100
    }
}
