data = {
    {
        ["GoldPerMob"] = 10,
        ["Lives"] = inf,
        ["DisplayWorldID"] = 1,
        ["Subtext"] = "",
        ["LevelRequirement"] = 1,
        ["ID"] = 1,
        ["CompletionExpRatio"] = 3,
        ["WorldID"] = 14,
        ["ShowOnProduction"] = true,
        ["Rewards"] = {},
        ["difficulties"] = {
            {
                ["enemyLevel"] = 1,
                ["onlyUpperTiers"] = false,
                ["damageMultiplier"] = 1,
                ["id"] = 1,
                ["lives"] = 3,
                ["includeUpperTiers"] = true,
                ["levelRequirement"] = 1,
                ["healthMultiplier"] = 1,
                ["rewardLevelRange"] = {1, 4}
            },
            {
                ["enemyLevel"] = 1,
                ["onlyUpperTiers"] = true,
                ["damageMultiplier"] = 2,
                ["id"] = 5,
                ["lives"] = 1,
                ["includeUpperTiers"] = false,
                ["rewardLevelRange"] = {1, 4},
                ["minimumUpperTier"] = 1,
                ["eliteRate"] = 0.5,
                ["healthMultiplier"] = 2,
                ["levelRequirement"] = 1
            }
        },
        ["PetXP"] = 0,
        ["BattlepassExp"] = 250,
        ["CompletionGoldRatio"] = 1,
        ["Tier5EquipmentType"] = "Weapon",
        ["MaxGearLevel"] = 10,
        ["DungeonID"] = "http://www.roblox.com/asset/?id=10299821970",
        ["WorldMissionID"] = 1,
        ["NameTag"] = "Crabby Crusade",
        ["ImageID"] = "http://www.roblox.com/asset/?id=3815148657"
    },
    {
        ["GoldPerMob"] = 12,
        ["Lives"] = 3,
        ["DisplayWorldID"] = 1,
        ["Subtext"] = "",
        ["LevelRequirement"] = 7,
        ["ID"] = 2,
        ["CompletionExpRatio"] = 1,
        ["WorldID"] = 15,
        ["ShowOnProduction"] = true,
        ["Rewards"] = {},
        ["difficulties"] = {
            {
                ["enemyLevel"] = 7,
                ["onlyUpperTiers"] = false,
                ["damageMultiplier"] = 1,
                ["id"] = 1,
                ["lives"] = 3,
                ["includeUpperTiers"] = true,
                ["levelRequirement"] = 7,
                ["healthMultiplier"] = 1,
                ["rewardLevelRange"] = {7, 10}
            },
            {
                ["enemyLevel"] = 7,
                ["onlyUpperTiers"] = true,
                ["damageMultiplier"] = 2,
                ["id"] = 5,
                ["lives"] = 1,
                ["includeUpperTiers"] = false,
                ["rewardLevelRange"] = {7, 10},
                ["minimumUpperTier"] = 1,
                ["eliteRate"] = 0.5,
                ["healthMultiplier"] = 1,
                ["levelRequirement"] = 7
            }
        },
        ["BattlepassExp"] = 250,
        ["CompletionGoldRatio"] = 1,
        ["PetXP"] = 0,
        ["MaxGearLevel"] = 11,
        ["DungeonID"] = "rbxassetid://12215979155",
        ["WorldMissionID"] = 3,
        ["NameTag"] = "Dire Problem",
        ["ImageID"] = "rbxassetid://12215978960"
    },
    {
        ["GoldPerMob"] = 16,
        ["Lives"] = 3,
        ["DisplayWorldID"] = 1,
        ["Subtext"] = "",
        ["LevelRequirement"] = 4,
        ["ID"] = 3,
        ["CompletionExpRatio"] = 0.9,
        ["WorldID"] = 16,
        ["ShowOnProduction"] = true,
        ["Rewards"] = {},
        ["difficulties"] = {
            {
                ["enemyLevel"] = 4,
                ["onlyUpperTiers"] = false,
                ["damageMultiplier"] = 1,
                ["id"] = 1,
                ["lives"] = 3,
                ["includeUpperTiers"] = true,
                ["levelRequirement"] = 4,
                ["healthMultiplier"] = 1,
                ["rewardLevelRange"] = {4, 7}
            },
            {
                ["enemyLevel"] = 4,
                ["onlyUpperTiers"] = true,
                ["damageMultiplier"] = 2,
                ["id"] = 5,
                ["lives"] = 1,
                ["includeUpperTiers"] = false,
                ["rewardLevelRange"] = {4, 7},
                ["minimumUpperTier"] = 1,
                ["eliteRate"] = 0.5,
                ["healthMultiplier"] = 1,
                ["levelRequirement"] = 4
            }
        },
        ["BattlepassExp"] = 250,
        ["CompletionGoldRatio"] = 1,
        ["PetXP"] = 0,
        ["MaxGearLevel"] = 12,
        ["DungeonID"] = "http://www.roblox.com/asset/?id=12186706707",
        ["WorldMissionID"] = 2,
        ["NameTag"] = "Scarecrow Defense",
        ["ImageID"] = "http://www.roblox.com/asset/?id=12186706707"
    },
    {
        ["GoldPerMob"] = 18,
        ["Lives"] = 3,
        ["DisplayWorldID"] = 1,
        ["Subtext"] = "",
        ["LevelRequirement"] = 10,
        ["ID"] = 4,
        ["CompletionExpRatio"] = 0.7,
        ["WorldID"] = 17,
        ["ShowOnProduction"] = true,
        ["Rewards"] = {},
        ["difficulties"] = {
            {
                ["enemyLevel"] = 10,
                ["onlyUpperTiers"] = false,
                ["damageMultiplier"] = 1,
                ["id"] = 1,
                ["lives"] = 3,
                ["includeUpperTiers"] = true,
                ["levelRequirement"] = 10,
                ["healthMultiplier"] = 1,
                ["rewardLevelRange"] = {10, 12}
            },
            {
                ["enemyLevel"] = 10,
                ["onlyUpperTiers"] = true,
                ["damageMultiplier"] = 2,
                ["id"] = 5,
                ["lives"] = 1,
                ["includeUpperTiers"] = false,
                ["rewardLevelRange"] = {10, 12},
                ["minimumUpperTier"] = 1,
                ["eliteRate"] = 0.5,
                ["healthMultiplier"] = 1,
                ["levelRequirement"] = 10
            }
        },
        ["BattlepassExp"] = 250,
        ["CompletionGoldRatio"] = 1,
        ["PetXP"] = 0,
        ["MaxGearLevel"] = 13,
        ["DungeonID"] = "http://www.roblox.com/asset/?id=10226745123",
        ["WorldMissionID"] = 4,
        ["NameTag"] = "Kingslayer",
        ["ImageID"] = "http://www.roblox.com/asset/?id=3815149931"
    },
    {
        ["GoldPerMob"] = 25,
        ["Disabled"] = true,
        ["Lives"] = 3,
        ["DisplayWorldID"] = 1,
        ["Subtext"] = "",
        ["LevelRequirement"] = 9,
        ["ID"] = 5,
        ["CompletionExpRatio"] = 0.55,
        ["WorldID"] = 18,
        ["ShowOnProduction"] = false,
        ["Rewards"] = {},
        ["BattlepassExp"] = 250,
        ["CompletionGoldRatio"] = 1,
        ["PetXP"] = 0,
        ["DungeonID"] = "http://www.roblox.com/asset/?id=10226840289",
        ["WorldMissionID"] = 10,
        ["NameTag"] = "Night of the Dead",
        ["ImageID"] = "http://www.roblox.com/asset/?id=3815150377"
    },
    {
        ["GoldPerMob"] = 28,
        ["Lives"] = 3,
        ["DisplayWorldID"] = 1,
        ["Subtext"] = "",
        ["LevelRequirement"] = 12,
        ["ID"] = 6,
        ["CompletionExpRatio"] = 0.45,
        ["WorldID"] = 7,
        ["difficulties"] = {
            {
                ["enemyLevel"] = 12,
                ["onlyUpperTiers"] = false,
                ["damageMultiplier"] = 1,
                ["id"] = 1,
                ["lives"] = 3,
                ["includeUpperTiers"] = true,
                ["levelRequirement"] = 12,
                ["timeLimit"] = 0,
                ["healthMultiplier"] = 1,
                ["rewardLevelRange"] = {12, 15}
            },
            {
                ["enemyLevel"] = 12,
                ["onlyUpperTiers"] = true,
                ["damageMultiplier"] = 2,
                ["id"] = 5,
                ["lives"] = 1,
                ["includeUpperTiers"] = false,
                ["rewardLevelRange"] = {12, 15},
                ["minimumUpperTier"] = 1,
                ["eliteRate"] = 0.5,
                ["healthMultiplier"] = 1,
                ["levelRequirement"] = 12
            }
        },
        ["Badges"] = {["DevID"] = 2124727272, ["LiveID"] = 2124728530},
        ["ShowOnProduction"] = true,
        ["Rewards"] = {
            {"SplinterAxe", 2, 1},
            {"WickedStaff", 2, 1},
            {"VoidSlayer", 2, 1},
            {"WitchHunterArmor", 2, 1},
            {"BrassGreatsword", 2, 1},
            {"WretchedScythe", 2, 1},
            {"BreakerShield", 2, 1},
            {"WickedBow", 2, 1},
            {"WickedSpear", 2, 1}
        },
        ["FinalWorldMission"] = true,
        ["PetXP"] = 0,
        ["BattlepassExp"] = 250,
        ["CompletionGoldRatio"] = 1,
        ["DungeonID"] = "http://www.roblox.com/asset/?id=3815313560",
        ["MaxGearLevel"] = 15,
        ["ImageID"] = "http://www.roblox.com/asset/?id=3815313560",
        ["WorldMissionID"] = 5,
        ["NameTag"] = "Gravetower Dungeon",
        ["UnlockTier5"] = true
    },
    {
        ["GoldPerMob"] = 30,
        ["Lives"] = 3,
        ["DisplayWorldID"] = 2,
        ["Subtext"] = "",
        ["LevelRequirement"] = 26,
        ["ID"] = 7,
        ["CompletionExpRatio"] = 0.25,
        ["WorldID"] = 6,
        ["difficulties"] = {
            {
                ["enemyLevel"] = 26,
                ["onlyUpperTiers"] = false,
                ["damageMultiplier"] = 1,
                ["id"] = 1,
                ["lives"] = 3,
                ["includeUpperTiers"] = true,
                ["levelRequirement"] = 26,
                ["healthMultiplier"] = 1,
                ["rewardLevelRange"] = {26, 30}
            },
            {
                ["enemyLevel"] = 26,
                ["onlyUpperTiers"] = true,
                ["damageMultiplier"] = 2,
                ["id"] = 5,
                ["lives"] = 1,
                ["includeUpperTiers"] = false,
                ["rewardLevelRange"] = {26, 30},
                ["minimumUpperTier"] = 1,
                ["eliteRate"] = 0.5,
                ["healthMultiplier"] = 1,
                ["levelRequirement"] = 26
            }
        },
        ["Badges"] = {["DevID"] = 0, ["LiveID"] = 2124728596},
        ["ShowOnProduction"] = true,
        ["Rewards"] = {
            {"CerberusStaff", 2, 1},
            {"SpireSlayer", 2, 1},
            {"Spirebane", 2, 1},
            {"LionGreataxe", 2, 1},
            {"CloakOfEmbers", 2, 1},
            {"MoltenShield", 2, 1},
            {"Meteorfall", 2, 1},
            {"Thornbreaker", 2, 1},
            {"Thornmaker", 2, 1}
        },
        ["FinalWorldMission"] = true,
        ["PetXP"] = 0,
        ["BattlepassExp"] = 250,
        ["CompletionGoldRatio"] = 1,
        ["MaxGearLevel"] = 30,
        ["ImageID"] = "rbxassetid://12349841651",
        ["WorldMissionID"] = 4,
        ["NameTag"] = "Volcano Dungeon",
        ["UnlockTier5"] = true
    },
    {
        ["GoldPerMob"] = 32,
        ["Disabled"] = true,
        ["Lives"] = 1,
        ["DisplayWorldID"] = 1,
        ["Subtext"] = "NIGHTMARE",
        ["LevelRequirement"] = 24,
        ["ID"] = 8,
        ["CompletionExpRatio"] = 0.1,
        ["WorldID"] = 7,
        ["ShowOnProduction"] = false,
        ["Rewards"] = {},
        ["BattlepassExp"] = 250,
        ["CompletionGoldRatio"] = 1,
        ["Badges"] = {["DevID"] = 0, ["LiveID"] = 2124728530},
        ["PetXP"] = 0,
        ["WorldMissionID"] = 7,
        ["NameTag"] = "Gravetower",
        ["ImageID"] = "http://www.roblox.com/asset/?id=3815313560"
    },
    {
        ["GoldPerMob"] = 35,
        ["Disabled"] = true,
        ["Lives"] = 1,
        ["DisplayWorldID"] = 2,
        ["Subtext"] = "NIGHTMARE",
        ["LevelRequirement"] = 27,
        ["ID"] = 9,
        ["CompletionExpRatio"] = 0.1,
        ["WorldID"] = 6,
        ["ShowOnProduction"] = false,
        ["Rewards"] = {},
        ["BattlepassExp"] = 250,
        ["CompletionGoldRatio"] = 1,
        ["PetXP"] = 0,
        ["WorldMissionID"] = 4,
        ["NameTag"] = "Volcano Dungeon",
        ["ImageID"] = "rbxassetid://12349841651"
    },
    {
        ["GoldPerMob"] = 35,
        ["Disabled"] = true,
        ["Lives"] = 1,
        ["DisplayWorldID"] = 2,
        ["Subtext"] = "",
        ["LevelRequirement"] = 99,
        ["ID"] = 10,
        ["CompletionExpRatio"] = 100,
        ["WorldID"] = 2,
        ["ShowOnProduction"] = false,
        ["Rewards"] = {},
        ["BattlepassExp"] = 250,
        ["CompletionGoldRatio"] = 1,
        ["PetXP"] = 0,
        ["WorldMissionID"] = 2,
        ["NameTag"] = "Test Matchmake",
        ["ImageID"] = "http://www.roblox.com/asset/?id=3815220149"
    },
    {
        ["GoldPerMob"] = 35,
        ["Lives"] = 3,
        ["DisplayWorldID"] = 2,
        ["Subtext"] = "",
        ["LevelRequirement"] = 15,
        ["ID"] = 11,
        ["CompletionExpRatio"] = 0.4,
        ["WorldID"] = 10,
        ["ShowOnProduction"] = true,
        ["Rewards"] = {},
        ["difficulties"] = {
            {
                ["enemyLevel"] = 15,
                ["onlyUpperTiers"] = false,
                ["damageMultiplier"] = 1,
                ["id"] = 1,
                ["lives"] = 3,
                ["includeUpperTiers"] = true,
                ["levelRequirement"] = 15,
                ["healthMultiplier"] = 1,
                ["rewardLevelRange"] = {15, 18}
            },
            {
                ["enemyLevel"] = 15,
                ["onlyUpperTiers"] = true,
                ["damageMultiplier"] = 2,
                ["id"] = 5,
                ["lives"] = 1,
                ["includeUpperTiers"] = false,
                ["rewardLevelRange"] = {15, 18},
                ["minimumUpperTier"] = 1,
                ["eliteRate"] = 0.5,
                ["healthMultiplier"] = 1,
                ["levelRequirement"] = 15
            }
        },
        ["BattlepassExp"] = 250,
        ["CompletionGoldRatio"] = 1,
        ["PetXP"] = 0,
        ["MaxGearLevel"] = 24,
        ["DungeonID"] = "http://www.roblox.com/asset/?id=10226749201",
        ["WorldMissionID"] = 1,
        ["NameTag"] = "Temple of Ruin",
        ["ImageID"] = "http://www.roblox.com/asset/?id=3885089843"
    },
    {
        ["GoldPerMob"] = 35,
        ["Lives"] = 3,
        ["DisplayWorldID"] = 2,
        ["Subtext"] = "",
        ["LevelRequirement"] = 18,
        ["ID"] = 12,
        ["CompletionExpRatio"] = 0.35,
        ["WorldID"] = 11,
        ["ShowOnProduction"] = true,
        ["Rewards"] = {},
        ["difficulties"] = {
            {
                ["enemyLevel"] = 18,
                ["onlyUpperTiers"] = false,
                ["damageMultiplier"] = 1,
                ["id"] = 1,
                ["lives"] = 3,
                ["includeUpperTiers"] = true,
                ["levelRequirement"] = 18,
                ["healthMultiplier"] = 1,
                ["rewardLevelRange"] = {18, 22}
            },
            {
                ["enemyLevel"] = 18,
                ["onlyUpperTiers"] = true,
                ["damageMultiplier"] = 2,
                ["id"] = 5,
                ["lives"] = 1,
                ["includeUpperTiers"] = false,
                ["rewardLevelRange"] = {18, 22},
                ["minimumUpperTier"] = 1,
                ["eliteRate"] = 0.5,
                ["healthMultiplier"] = 1,
                ["levelRequirement"] = 18
            }
        },
        ["BattlepassExp"] = 250,
        ["CompletionGoldRatio"] = 1,
        ["PetXP"] = 0,
        ["MaxGearLevel"] = 26,
        ["DungeonID"] = "http://www.roblox.com/asset/?id=10226751849",
        ["WorldMissionID"] = 2,
        ["NameTag"] = "Mama Trauma",
        ["ImageID"] = "http://www.roblox.com/asset/?id=3994441119"
    },
    {
        ["GoldPerMob"] = 35,
        ["Lives"] = 3,
        ["DisplayWorldID"] = 2,
        ["Subtext"] = "",
        ["LevelRequirement"] = 22,
        ["ID"] = 13,
        ["CompletionExpRatio"] = 0.3,
        ["WorldID"] = 12,
        ["ShowOnProduction"] = true,
        ["Rewards"] = {},
        ["difficulties"] = {
            {
                ["enemyLevel"] = 22,
                ["onlyUpperTiers"] = false,
                ["damageMultiplier"] = 1,
                ["id"] = 1,
                ["lives"] = 3,
                ["includeUpperTiers"] = true,
                ["levelRequirement"] = 22,
                ["healthMultiplier"] = 1,
                ["rewardLevelRange"] = {22, 26}
            },
            {
                ["enemyLevel"] = 22,
                ["onlyUpperTiers"] = true,
                ["damageMultiplier"] = 2,
                ["id"] = 5,
                ["rewards"] = {
                    {"CerberusStaff", 2, 1},
                    {"SpireSlayer", 2, 1},
                    {"Spirebane", 2, 1},
                    {"LionGreataxe", 2, 1},
                    {"CloakOfEmbers", 2, 1},
                    {"MoltenShield", 2, 1},
                    {"Meteorfall", 2, 1},
                    {"Thornbreaker", 2, 1},
                    {"Thornmaker", 2, 1}
                },
                ["lives"] = 1,
                ["includeUpperTiers"] = false,
                ["rewardLevelRange"] = {22, 26},
                ["minimumUpperTier"] = 1,
                ["eliteRate"] = 0.5,
                ["healthMultiplier"] = 1,
                ["levelRequirement"] = 22
            }
        },
        ["BattlepassExp"] = 250,
        ["CompletionGoldRatio"] = 1,
        ["PetXP"] = 0,
        ["MaxGearLevel"] = 28,
        ["DungeonID"] = "http://www.roblox.com/asset/?id=10226753246",
        ["WorldMissionID"] = 3,
        ["NameTag"] = "Volcano's Shadow",
        ["ImageID"] = "http://www.roblox.com/asset/?id=4048623300"
    },
    {
        ["GoldPerMob"] = 35,
        ["Lives"] = 3,
        ["DisplayWorldID"] = 3,
        ["Subtext"] = "",
        ["LevelRequirement"] = 30,
        ["ID"] = 14,
        ["CompletionExpRatio"] = 0.25,
        ["WorldID"] = 23,
        ["ShowOnProduction"] = true,
        ["Rewards"] = {},
        ["difficulties"] = {
            {
                ["enemyLevel"] = 30,
                ["onlyUpperTiers"] = false,
                ["damageMultiplier"] = 1,
                ["id"] = 1,
                ["lives"] = 3,
                ["includeUpperTiers"] = true,
                ["levelRequirement"] = 30,
                ["healthMultiplier"] = 1,
                ["rewardLevelRange"] = {30, 35}
            },
            {
                ["enemyLevel"] = 12,
                ["onlyUpperTiers"] = true,
                ["damageMultiplier"] = 2,
                ["id"] = 5,
                ["lives"] = 1,
                ["includeUpperTiers"] = false,
                ["rewardLevelRange"] = {30, 35},
                ["minimumUpperTier"] = 1,
                ["eliteRate"] = 0.5,
                ["healthMultiplier"] = 1,
                ["levelRequirement"] = 30
            }
        },
        ["BattlepassExp"] = 250,
        ["CompletionGoldRatio"] = 1,
        ["PetXP"] = 0,
        ["MaxGearLevel"] = 38,
        ["DungeonID"] = "http://www.roblox.com/asset/?id=10227290232",
        ["WorldMissionID"] = 1,
        ["NameTag"] = "Mountain Pass",
        ["ImageID"] = "http://www.roblox.com/asset/?id=4462882691"
    },
    {
        ["GoldPerMob"] = 35,
        ["Lives"] = 3,
        ["DisplayWorldID"] = 3,
        ["Subtext"] = "",
        ["LevelRequirement"] = 35,
        ["ID"] = 15,
        ["CompletionExpRatio"] = 0.26,
        ["WorldID"] = 22,
        ["ShowOnProduction"] = true,
        ["Rewards"] = {},
        ["difficulties"] = {
            {
                ["enemyLevel"] = 35,
                ["onlyUpperTiers"] = false,
                ["damageMultiplier"] = 1,
                ["id"] = 1,
                ["lives"] = 3,
                ["includeUpperTiers"] = true,
                ["levelRequirement"] = 35,
                ["healthMultiplier"] = 1,
                ["rewardLevelRange"] = {35, 40}
            },
            {
                ["enemyLevel"] = 35,
                ["onlyUpperTiers"] = true,
                ["damageMultiplier"] = 2,
                ["id"] = 5,
                ["lives"] = 1,
                ["includeUpperTiers"] = false,
                ["rewardLevelRange"] = {35, 40},
                ["minimumUpperTier"] = 1,
                ["eliteRate"] = 0.5,
                ["healthMultiplier"] = 1,
                ["levelRequirement"] = 35
            }
        },
        ["BattlepassExp"] = 250,
        ["CompletionGoldRatio"] = 1,
        ["PetXP"] = 0,
        ["MaxGearLevel"] = 42,
        ["DungeonID"] = "http://www.roblox.com/asset/?id=10227291076",
        ["WorldMissionID"] = 2,
        ["NameTag"] = "Winter Cavern",
        ["ImageID"] = "http://www.roblox.com/asset/?id=4462884691"
    },
    {
        ["GoldPerMob"] = 35,
        ["Lives"] = 2,
        ["DisplayWorldID"] = 3,
        ["Subtext"] = "",
        ["LevelRequirement"] = 40,
        ["ID"] = 16,
        ["CompletionExpRatio"] = 0.2,
        ["WorldID"] = 21,
        ["difficulties"] = {
            {
                ["enemyLevel"] = 40,
                ["onlyUpperTiers"] = false,
                ["damageMultiplier"] = 1,
                ["id"] = 1,
                ["lives"] = 3,
                ["includeUpperTiers"] = true,
                ["levelRequirement"] = 40,
                ["healthMultiplier"] = 1,
                ["rewardLevelRange"] = {40, 45}
            },
            {
                ["enemyLevel"] = 40,
                ["onlyUpperTiers"] = true,
                ["damageMultiplier"] = 2,
                ["id"] = 5,
                ["lives"] = 1,
                ["includeUpperTiers"] = false,
                ["rewardLevelRange"] = {40, 45},
                ["minimumUpperTier"] = 1,
                ["eliteRate"] = 0.5,
                ["healthMultiplier"] = 1,
                ["levelRequirement"] = 40
            }
        },
        ["Badges"] = {["DevID"] = 0, ["LiveID"] = 2124728591},
        ["ShowOnProduction"] = true,
        ["Rewards"] = {
            {"WintersHeart", 2, 1},
            {"Snowstorm", 2, 1},
            {"Permafrost", 2, 1},
            {"ThrasherLongsword", 2, 1},
            {"WillOTheWisp", 2, 1},
            {"HolyArmor", 2, 1},
            {"ClawOfWinter", 2, 1},
            {"WintersMight", 2, 1},
            {"WintersBite", 2, 1}
        },
        ["FinalWorldMission"] = true,
        ["PetXP"] = 0,
        ["BattlepassExp"] = 250,
        ["CompletionGoldRatio"] = 1,
        ["DungeonID"] = "http://www.roblox.com/asset/?id=10227291854",
        ["MaxGearLevel"] = 45,
        ["ImageID"] = "http://www.roblox.com/asset/?id=4462886806",
        ["WorldMissionID"] = 3,
        ["NameTag"] = "Winter Dungeon",
        ["UnlockTier5"] = true
    },
    {
        ["EnemyLevel"] = 135,
        ["Disabled"] = true,
        ["Lives"] = 2,
        ["DisplayWorldID"] = 101,
        ["Subtext"] = "",
        ["LevelRequirement"] = 1,
        ["ID"] = 17,
        ["CompletionExpRatio"] = 0.18,
        ["WorldID"] = 25,
        ["UpgradedGearDisabled"] = true,
        ["TowerChest"] = {{"HolidayKnightHelmGreen", 1, 1}, {"HolidayCoin", 100, 15}},
        ["EventDungeon"] = true,
        ["UseRewardTable"] = true,
        ["ShowOnProduction"] = true,
        ["Rewards"] = {
            {"HolidayPrizeTicket3", 9500, 3},
            {"HolidayKnightGreen", 300, 1},
            {"GreenCandyCaneAxe", 25, 1},
            {"GreenCandyCaneScythe", 25, 1},
            {"GreenCandyCaneShield", 25, 1},
            {"GreenCandyCaneSpear", 25, 1},
            {"GreenCandyCaneGreatsword", 25, 1},
            {"GreenCandyCaneLongsword", 25, 1},
            {"GreenCandyCaneStaff", 25, 1},
            {"GreenCandyCaneBow", 25, 1}
        },
        ["DungeonID"] = "http://www.roblox.com/asset/?id=4462886806",
        ["FinalBoss"] = "BOSSEvilSanta",
        ["BattlepassExp"] = 250,
        ["EffectiveLevel"] = 125,
        ["PetXP"] = 0,
        ["MaxGearLevel"] = 150,
        ["ImageID"] = "http://www.roblox.com/asset/?id=4462886806",
        ["WorldMissionID"] = 1,
        ["NameTag"] = "Event Arena",
        ["CompletionGoldRatio"] = 1
    },
    {
        ["Lives"] = 1,
        ["DisplayWorldID"] = 4,
        ["Subtext"] = "",
        ["LevelRequirement"] = 55,
        ["ID"] = 18,
        ["CompletionExpRatio"] = 0.18,
        ["WorldID"] = 27,
        ["difficulties"] = {
            {
                ["enemyLevel"] = 55,
                ["onlyUpperTiers"] = false,
                ["damageMultiplier"] = 1,
                ["id"] = 1,
                ["lives"] = 3,
                ["includeUpperTiers"] = true,
                ["levelRequirement"] = 55,
                ["healthMultiplier"] = 1,
                ["rewardLevelRange"] = {55, 60}
            },
            {
                ["enemyLevel"] = 55,
                ["onlyUpperTiers"] = true,
                ["damageMultiplier"] = 2,
                ["id"] = 5,
                ["lives"] = 1,
                ["includeUpperTiers"] = false,
                ["rewardLevelRange"] = {55, 60},
                ["minimumUpperTier"] = 1,
                ["eliteRate"] = 0.5,
                ["healthMultiplier"] = 1,
                ["levelRequirement"] = 55
            }
        },
        ["Badges"] = {["DevID"] = 0, ["LiveID"] = 2124728534},
        ["ShowOnProduction"] = true,
        ["Rewards"] = {
            {"PhoenixHeart", 2, 1},
            {"Deathgod", 2, 1},
            {"WrappedGreatsword", 2, 1},
            {"Titanslayer", 2, 1},
            {"StaffOfScarabs", 2, 1},
            {"PhoenixPlate", 2, 1},
            {"Sandstorm", 2, 1},
            {"Sandblaster", 2, 1},
            {"Royalty", 2, 1}
        },
        ["FinalWorldMission"] = true,
        ["PetXP"] = 0,
        ["BattlepassExp"] = 250,
        ["CompletionGoldRatio"] = 1,
        ["DungeonID"] = "http://www.roblox.com/asset/?id=10227296020",
        ["MaxGearLevel"] = 60,
        ["ImageID"] = "http://www.roblox.com/asset/?id=4462886806",
        ["WorldMissionID"] = 3,
        ["NameTag"] = "Pyramid Dungeon",
        ["UnlockTier5"] = true
    },
    {
        ["Lives"] = 2,
        ["DisplayWorldID"] = 4,
        ["Subtext"] = "",
        ["LevelRequirement"] = 50,
        ["ID"] = 19,
        ["CompletionExpRatio"] = 0.18,
        ["WorldID"] = 30,
        ["ShowOnProduction"] = true,
        ["Rewards"] = {},
        ["difficulties"] = {
            {
                ["enemyLevel"] = 50,
                ["onlyUpperTiers"] = false,
                ["damageMultiplier"] = 1,
                ["id"] = 1,
                ["lives"] = 3,
                ["includeUpperTiers"] = true,
                ["levelRequirement"] = 50,
                ["healthMultiplier"] = 1,
                ["rewardLevelRange"] = {50, 55}
            },
            {
                ["enemyLevel"] = 50,
                ["onlyUpperTiers"] = true,
                ["damageMultiplier"] = 2,
                ["id"] = 5,
                ["lives"] = 1,
                ["includeUpperTiers"] = false,
                ["rewardLevelRange"] = {50, 55},
                ["minimumUpperTier"] = 1,
                ["eliteRate"] = 0.5,
                ["healthMultiplier"] = 1,
                ["levelRequirement"] = 50
            }
        },
        ["BattlepassExp"] = 250,
        ["CompletionGoldRatio"] = 1,
        ["PetXP"] = 0,
        ["MaxGearLevel"] = 58,
        ["DungeonID"] = "http://www.roblox.com/asset/?id=10227295163",
        ["WorldMissionID"] = 2,
        ["NameTag"] = "Deserted Burrowmine",
        ["ImageID"] = "http://www.roblox.com/asset/?id=4462886806"
    },
    {
        ["Lives"] = 2,
        ["DisplayWorldID"] = 4,
        ["Subtext"] = "",
        ["LevelRequirement"] = 45,
        ["ID"] = 20,
        ["CompletionExpRatio"] = 0.18,
        ["WorldID"] = 28,
        ["ShowOnProduction"] = true,
        ["Rewards"] = {},
        ["difficulties"] = {
            {
                ["enemyLevel"] = 45,
                ["onlyUpperTiers"] = false,
                ["damageMultiplier"] = 1,
                ["id"] = 1,
                ["lives"] = 3,
                ["includeUpperTiers"] = true,
                ["levelRequirement"] = 45,
                ["healthMultiplier"] = 1,
                ["rewardLevelRange"] = {45, 50}
            },
            {
                ["enemyLevel"] = 45,
                ["onlyUpperTiers"] = true,
                ["damageMultiplier"] = 2,
                ["id"] = 5,
                ["lives"] = 1,
                ["includeUpperTiers"] = false,
                ["rewardLevelRange"] = {45, 50},
                ["minimumUpperTier"] = 1,
                ["eliteRate"] = 0.5,
                ["healthMultiplier"] = 1,
                ["levelRequirement"] = 45
            }
        },
        ["BattlepassExp"] = 250,
        ["CompletionGoldRatio"] = 1,
        ["PetXP"] = 0,
        ["MaxGearLevel"] = 55,
        ["DungeonID"] = "http://www.roblox.com/asset/?id=10227294186",
        ["WorldMissionID"] = 1,
        ["NameTag"] = "Scrap Canyon",
        ["ImageID"] = "http://www.roblox.com/asset/?id=4462886806"
    },
    {
        ["IsTowerDungeon"] = true,
        ["Lives"] = 1,
        ["DisplayWorldID"] = 5,
        ["Subtext"] = "",
        ["LevelRequirement"] = 70,
        ["ID"] = 21,
        ["Tier5RarityScale"] = 2,
        ["WorldID"] = 32,
        ["MaxDifficultyScale"] = 1,
        ["TowerChest"] = {{"MoltenEgg", 10, 1}, {"Sundae", 15, 5}, {"Doughnut", 25, 5}, {"Strawberry", 50, 5}},
        ["ShowOnProduction"] = true,
        ["Rewards"] = {
            {"SolarHeart", 2, 1},
            {"Blossomfield", 2, 1},
            {"IgnisEye", 2, 1},
            {"JawLongsword", 2, 1},
            {"Firecaster", 2, 1},
            {"Dragonkin", 2, 1},
            {"Ignition", 2, 1},
            {"Torchblazer", 2, 1},
            {"IgnisDraw", 2, 1}
        },
        ["TowerID"] = 1,
        ["FinalBoss"] = "BOSSIgnisFireDragon",
        ["Badges"] = {["DevID"] = 2124727272, ["LiveID"] = 2124730421},
        ["ImageID"] = "http://www.roblox.com/asset/?id=4462886806",
        ["CanLeaveAloneOnSpectate"] = true,
        ["MaxGearLevel"] = 75,
        ["DungeonID"] = "http://www.roblox.com/asset/?id=10227302028",
        ["WorldMissionID"] = 3,
        ["NameTag"] = "Prison Tower",
        ["UnlockTier5"] = true
    },
    {
        ["Disabled"] = false,
        ["DisplayWorldID"] = 102,
        ["Subtext"] = "",
        ["LevelRequirement"] = 1,
        ["ID"] = 22,
        ["CompletionExpRatio"] = 0.18,
        ["WorldID"] = 34,
        ["difficulties"] = {
            {
                ["enemyLevel"] = 135,
                ["onlyUpperTiers"] = false,
                ["UpgradedGearDisabled"] = true,
                ["damageMultiplier"] = 1,
                ["id"] = 1,
                ["rewards"] = {{"HalloweenPrizeTicket4", 9500, 5}},
                ["lives"] = 3,
                ["includeUpperTiers"] = true,
                ["rewardLevelRange"] = {1, 150},
                ["healthMultiplier"] = 1,
                ["levelRequirement"] = 1
            },
            {
                ["enemyLevel"] = 140,
                ["onlyUpperTiers"] = true,
                ["UpgradedGearDisabled"] = true,
                ["damageMultiplier"] = 2,
                ["id"] = 5,
                ["rewards"] = {{"HalloweenPrizeTicket4", 3000, 10}},
                ["lives"] = 1,
                ["includeUpperTiers"] = false,
                ["rewardLevelRange"] = {1, 150},
                ["minimumUpperTier"] = 1,
                ["eliteRate"] = 0.5,
                ["healthMultiplier"] = 1.8,
                ["levelRequirement"] = 1
            }
        },
        ["IncludeAllRewards"] = true,
        ["TowerChest"] = {{"FallenKingCrown", 1, 1}, {"KingsGreatsword", 1, 1}, {"HalloweenPrizeTicket4", 100, 5}},
        ["EventDungeon"] = true,
        ["UseRewardTable"] = true,
        ["ShowOnProduction"] = true,
        ["Rewards"] = {
            {"SkeletonEgg", 1, 1},
            {"BatAxeOrange", 25, 1},
            {"BatScytheOrange", 25, 1},
            {"BatShieldOrange", 25, 1},
            {"BatSpearOrange", 25, 1},
            {"BatGreatswordOrange", 25, 1},
            {"BatLongswordOrange", 25, 1},
            {"BatStaffOrange", 25, 1},
            {"BatBowOrange", 25, 1}
        },
        ["UpgradedGearDisabled"] = true,
        ["FinalBoss"] = "BOSSFallenKing",
        ["EffectiveLevel"] = 125,
        ["CompletionGoldRatio"] = 1,
        ["CustomLayoutOrder"] = 999,
        ["MaxGearLevel"] = 150,
        ["DungeonID"] = "http://www.roblox.com/asset/?id=11162023749",
        ["WorldMissionID"] = 1,
        ["NameTag"] = "Event Arena",
        ["ImageID"] = "http://www.roblox.com/asset/?id=4462886806"
    },
    {
        ["IsTowerDungeon"] = true,
        ["Lives"] = 1,
        ["DisplayWorldID"] = 6,
        ["Subtext"] = "",
        ["LevelRequirement"] = 85,
        ["ID"] = 23,
        ["Tier5RarityScale"] = 2,
        ["WorldID"] = 35,
        ["MaxDifficultyScale"] = 1,
        ["TowerChest"] = {{"OceanEgg", 10, 1}, {"Sundae", 15, 5}, {"Doughnut", 25, 5}, {"Strawberry", 50, 5}},
        ["ShowOnProduction"] = true,
        ["Rewards"] = {
            {"KrakenShield", 2, 1},
            {"KrakenEyes", 2, 1},
            {"SirensWatch", 2, 1},
            {"Deeptrench", 2, 1},
            {"KrakenStaff", 2, 1},
            {"Squidbane", 2, 1},
            {"NeptuneTrident", 2, 1},
            {"NightTerror", 2, 1},
            {"SirensSong", 2, 1},
            {"NightTerrorHood", 1, 1}
        },
        ["TowerID"] = 2,
        ["FinalBoss"] = "BOSSKrakenMain",
        ["Badges"] = {["DevID"] = 2124728601, ["LiveID"] = 2124728601},
        ["ImageID"] = "http://www.roblox.com/asset/?id=4462886806",
        ["CanLeaveAloneOnSpectate"] = true,
        ["MaxGearLevel"] = 90,
        ["DungeonID"] = "http://www.roblox.com/asset/?id=10227302640",
        ["WorldMissionID"] = 3,
        ["NameTag"] = "Atlantis Tower",
        ["UnlockTier5"] = true
    },
    {
        ["Lives"] = 1,
        ["DisplayWorldID"] = 5,
        ["LevelRequirement"] = 60,
        ["ID"] = 24,
        ["CompletionExpRatio"] = 0.18,
        ["WorldID"] = 37,
        ["difficulties"] = {
            {
                ["enemyLevel"] = 60,
                ["onlyUpperTiers"] = false,
                ["damageMultiplier"] = 1,
                ["id"] = 1,
                ["lives"] = 3,
                ["includeUpperTiers"] = true,
                ["levelRequirement"] = 60,
                ["healthMultiplier"] = 1,
                ["rewardLevelRange"] = {60, 65}
            },
            {
                ["enemyLevel"] = 60,
                ["onlyUpperTiers"] = true,
                ["damageMultiplier"] = 2,
                ["id"] = 5,
                ["lives"] = 1,
                ["includeUpperTiers"] = false,
                ["rewardLevelRange"] = {60, 65},
                ["minimumUpperTier"] = 1,
                ["eliteRate"] = 0.5,
                ["healthMultiplier"] = 1,
                ["levelRequirement"] = 60
            }
        },
        ["ShowOnProduction"] = true,
        ["Rewards"] = {
            {"SolarHeart", 2, 1},
            {"Blossomfield", 2, 1},
            {"IgnisEye", 2, 1},
            {"JawLongsword", 2, 1},
            {"Firecaster", 2, 1},
            {"Dragonkin", 2, 1},
            {"Ignition", 2, 1},
            {"Torchblazer", 2, 1},
            {"IgnisDraw", 2, 1}
        },
        ["Badges"] = {["DevID"] = 0, ["LiveID"] = 0},
        ["PetXP"] = 0,
        ["BattlepassExp"] = 250,
        ["CompletionGoldRatio"] = 1,
        ["ImageID"] = "http://www.roblox.com/asset/?id=12636488134",
        ["MaxGearLevel"] = 60,
        ["DungeonID"] = "http://www.roblox.com/asset/?id=12636488134",
        ["WorldMissionID"] = 1,
        ["NameTag"] = "Konoh Heartlands",
        ["UnlockTier5"] = true
    },
    {
        ["difficulties"] = {
            {
                ["enemyLevel"] = 75,
                ["onlyUpperTiers"] = false,
                ["damageMultiplier"] = 1,
                ["id"] = 1,
                ["lives"] = 3,
                ["includeUpperTiers"] = true,
                ["levelRequirement"] = 75,
                ["healthMultiplier"] = 1,
                ["rewardLevelRange"] = {75, 80}
            },
            {
                ["enemyLevel"] = 75,
                ["onlyUpperTiers"] = true,
                ["damageMultiplier"] = 2,
                ["id"] = 5,
                ["lives"] = 1,
                ["includeUpperTiers"] = false,
                ["rewardLevelRange"] = {75, 80},
                ["minimumUpperTier"] = 1,
                ["eliteRate"] = 0.5,
                ["healthMultiplier"] = 2,
                ["levelRequirement"] = 75
            }
        },
        ["Badges"] = {["DevID"] = 0, ["LiveID"] = 0},
        ["ImageID"] = "http://www.roblox.com/asset/?id=6449138798",
        ["DungeonID"] = "http://www.roblox.com/asset/?id=10227298090",
        ["ShowOnProduction"] = true,
        ["Rewards"] = {
            {"KrakenShield", 2, 1},
            {"KrakenEyes", 2, 1},
            {"SirensWatch", 2, 1},
            {"Deeptrench", 2, 1},
            {"KrakenStaff", 2, 1},
            {"Squidbane", 2, 1},
            {"NeptuneTrident", 2, 1},
            {"NightTerror", 2, 1},
            {"SirensSong", 2, 1}
        },
        ["Lives"] = 1,
        ["DisplayWorldID"] = 6,
        ["CompletionExpRatio"] = 0.18,
        ["CompletionGoldRatio"] = 1,
        ["LevelRequirement"] = 75,
        ["MaxGearLevel"] = 60,
        ["ID"] = 25,
        ["WorldMissionID"] = 1,
        ["WorldID"] = 38,
        ["NameTag"] = "Rough Waters"
    },
    {
        ["difficulties"] = {
            {
                ["enemyLevel"] = 90,
                ["onlyUpperTiers"] = false,
                ["damageMultiplier"] = 1,
                ["id"] = 1,
                ["rewards"] = {{"FlameDemonHood", 2, 1}},
                ["lives"] = 3,
                ["includeUpperTiers"] = true,
                ["levelRequirement"] = 90,
                ["healthMultiplier"] = 1,
                ["rewardLevelRange"] = {90, 95}
            },
            {
                ["enemyLevel"] = 90,
                ["onlyUpperTiers"] = true,
                ["damageMultiplier"] = 2,
                ["id"] = 5,
                ["lives"] = 1,
                ["includeUpperTiers"] = false,
                ["rewardLevelRange"] = {90, 95},
                ["minimumUpperTier"] = 1,
                ["eliteRate"] = 0.5,
                ["healthMultiplier"] = 1,
                ["levelRequirement"] = 90
            }
        },
        ["Badges"] = {["DevID"] = 0, ["LiveID"] = 2124852072},
        ["ImageID"] = "http://www.roblox.com/asset/?id=6842273983",
        ["DungeonID"] = "http://www.roblox.com/asset/?id=10227299203",
        ["ShowOnProduction"] = true,
        ["Rewards"] = {
            {"Crestfall", 2, 1},
            {"ShiningBanner", 2, 1},
            {"Legacy", 2, 1},
            {"GuildedChampion", 2, 1},
            {"WingsOfDare", 2, 1},
            {"GrimDay", 2, 1},
            {"Proudmaker", 2, 1},
            {"GreatBow", 2, 1},
            {"AngelArmor", 2, 1}
        },
        ["Lives"] = 1,
        ["DisplayWorldID"] = 7,
        ["CompletionExpRatio"] = 0.18,
        ["CompletionGoldRatio"] = 1,
        ["LevelRequirement"] = 90,
        ["MaxGearLevel"] = 60,
        ["ID"] = 26,
        ["WorldMissionID"] = 1,
        ["WorldID"] = 41,
        ["NameTag"] = "The Underworld"
    },
    {
        ["IsTowerDungeon"] = true,
        ["Lives"] = 1,
        ["DisplayWorldID"] = 7,
        ["Subtext"] = "",
        ["LevelRequirement"] = 100,
        ["ID"] = 27,
        ["Tier5RarityScale"] = 2,
        ["WorldID"] = 42,
        ["MaxDifficultyScale"] = 1,
        ["TowerChest"] = {{"SkyEgg", 10, 1}, {"Sundae", 15, 5}, {"Doughnut", 25, 5}, {"Strawberry", 50, 5}},
        ["ShowOnProduction"] = true,
        ["Rewards"] = {
            {"AngelHood", 2, 1},
            {"AngelHalo", 2, 1},
            {"AngelicWings", 2, 1},
            {"Crestfall", 2, 1},
            {"ShiningBanner", 2, 1},
            {"Legacy", 2, 1},
            {"GuildedChampion", 2, 1},
            {"WingsOfDare", 2, 1},
            {"GrimDay", 2, 1},
            {"Proudmaker", 2, 1},
            {"GreatBow", 2, 1},
            {"AngelArmor", 2, 1}
        },
        ["TowerID"] = 3,
        ["FinalBoss"] = "BOSSZeus",
        ["Badges"] = {["DevID"] = 2124791958, ["LiveID"] = 2124791958},
        ["ImageID"] = "http://www.roblox.com/asset/?id=4462886806",
        ["CanLeaveAloneOnSpectate"] = true,
        ["MaxGearLevel"] = 105,
        ["DungeonID"] = "http://www.roblox.com/asset/?id=10227303334",
        ["WorldMissionID"] = 3,
        ["NameTag"] = "Mezuvian Tower",
        ["UnlockTier5"] = true
    },
    {
        ["MaxDifficultyScale"] = 1,
        ["CanLeaveAloneOnSpectate"] = true,
        ["Badges"] = {["DevID"] = 2124727272, ["LiveID"] = 2124810999},
        ["ShowOnProduction"] = false,
        ["Rewards"] = {},
        ["Lives"] = 3,
        ["DisplayWorldID"] = 104,
        ["Subtext"] = "",
        ["ImageID"] = "http://www.roblox.com/asset/?id=7385290697",
        ["LevelRequirement"] = 1,
        ["MaxGearLevel"] = 100,
        ["ID"] = 28,
        ["WorldMissionID"] = 1,
        ["WorldID"] = 43,
        ["NameTag"] = "Twenty One Pilots Event"
    },
    {
        ["IsTowerDungeon"] = true,
        ["Lives"] = 1,
        ["DisplayWorldID"] = 8,
        ["Subtext"] = "",
        ["LevelRequirement"] = 110,
        ["ID"] = 29,
        ["Tier5RarityScale"] = 2,
        ["WorldID"] = 46,
        ["MaxDifficultyScale"] = 1,
        ["TowerChest"] = {{"AlligatorEgg", 10, 1}, {"Sundae", 15, 5}, {"Doughnut", 25, 5}, {"Strawberry", 50, 5}},
        ["CanRevive"] = false,
        ["ShowOnProduction"] = true,
        ["Rewards"] = {
            {"World8Tier5Longsword", 2, 1},
            {"World8Tier5Axe", 2, 1},
            {"World8Tier5Scythe", 2, 1},
            {"World8Tier5Spear", 2, 1},
            {"World8Tier5Greatsword", 2, 1},
            {"World8Tier5Staff", 2, 1},
            {"World8Tier5Bow", 2, 1},
            {"World8Tier5Shield", 2, 1},
            {"World8Tier5Armor", 2, 1},
            {"TaurhaStaff", 2, 1}
        },
        ["TowerID"] = 4,
        ["FinalBoss"] = "Taurha",
        ["Badges"] = {["DevID"] = 2127174509, ["LiveID"] = 2127174509},
        ["ImageID"] = "http://www.roblox.com/asset/?id=4462886806",
        ["CanLeaveAloneOnSpectate"] = true,
        ["MaxGearLevel"] = 115,
        ["DungeonID"] = "http://www.roblox.com/asset/?id=10299309462",
        ["WorldMissionID"] = 3,
        ["NameTag"] = "Oasis Tower",
        ["UnlockTier5"] = true
    },
    {
        ["difficulties"] = {
            {
                ["enemyLevel"] = 100,
                ["onlyUpperTiers"] = false,
                ["damageMultiplier"] = 1,
                ["id"] = 1,
                ["lives"] = 3,
                ["includeUpperTiers"] = true,
                ["levelRequirement"] = 100,
                ["healthMultiplier"] = 1,
                ["rewardLevelRange"] = {100, 105}
            },
            {
                ["enemyLevel"] = 100,
                ["onlyUpperTiers"] = true,
                ["damageMultiplier"] = 2,
                ["id"] = 5,
                ["lives"] = 1,
                ["includeUpperTiers"] = false,
                ["rewardLevelRange"] = {100, 105},
                ["minimumUpperTier"] = 1,
                ["eliteRate"] = 0.5,
                ["healthMultiplier"] = 1,
                ["levelRequirement"] = 100
            }
        },
        ["Badges"] = {["DevID"] = 0, ["LiveID"] = 0},
        ["ImageID"] = "http://www.roblox.com/asset/?id=6842273983",
        ["DungeonID"] = "http://www.roblox.com/asset/?id=10227300021",
        ["ShowOnProduction"] = true,
        ["Rewards"] = {
            {"World8Tier5Longsword", 3, 1},
            {"World8Tier5Axe", 3, 1},
            {"World8Tier5Scythe", 3, 1},
            {"World8Tier5Spear", 3, 1},
            {"World8Tier5Greatsword", 3, 1},
            {"World8Tier5Staff", 3, 1},
            {"World8Tier5Bow", 3, 1},
            {"World8Tier5Shield", 3, 1},
            {"World8Tier5Armor", 3, 1}
        },
        ["Lives"] = 1,
        ["DisplayWorldID"] = 8,
        ["CompletionExpRatio"] = 0.18,
        ["CompletionGoldRatio"] = 1,
        ["LevelRequirement"] = 100,
        ["MaxGearLevel"] = 115,
        ["ID"] = 30,
        ["WorldMissionID"] = 1,
        ["WorldID"] = 47,
        ["NameTag"] = "Rescue in the Ruins"
    },
    {
        ["difficulties"] = {
            {
                ["enemyLevel"] = 105,
                ["onlyUpperTiers"] = false,
                ["damageMultiplier"] = 1,
                ["id"] = 1,
                ["lives"] = 3,
                ["includeUpperTiers"] = true,
                ["levelRequirement"] = 105,
                ["healthMultiplier"] = 1,
                ["rewardLevelRange"] = {105, 115}
            },
            {
                ["enemyLevel"] = 105,
                ["onlyUpperTiers"] = true,
                ["damageMultiplier"] = 2,
                ["id"] = 5,
                ["lives"] = 1,
                ["includeUpperTiers"] = false,
                ["rewardLevelRange"] = {105, 115},
                ["minimumUpperTier"] = 1,
                ["eliteRate"] = 0.5,
                ["healthMultiplier"] = 1,
                ["levelRequirement"] = 105
            }
        },
        ["Badges"] = {["DevID"] = 2127174789, ["LiveID"] = 2127174789},
        ["ImageID"] = "http://www.roblox.com/asset/?id=6842273983",
        ["DungeonID"] = "http://www.roblox.com/asset/?id=10227300777",
        ["ShowOnProduction"] = true,
        ["Rewards"] = {
            {"World8Tier5Longsword", 3, 1},
            {"World8Tier5Axe", 3, 1},
            {"World8Tier5Scythe", 3, 1},
            {"World8Tier5Spear", 3, 1},
            {"World8Tier5Greatsword", 3, 1},
            {"World8Tier5Staff", 3, 1},
            {"World8Tier5Bow", 3, 1},
            {"World8Tier5Shield", 3, 1},
            {"World8Tier5Armor", 3, 1}
        },
        ["Lives"] = 1,
        ["DisplayWorldID"] = 8,
        ["CompletionExpRatio"] = 0.18,
        ["CompletionGoldRatio"] = 1,
        ["LevelRequirement"] = 105,
        ["MaxGearLevel"] = 115,
        ["ID"] = 31,
        ["WorldMissionID"] = 2,
        ["WorldID"] = 48,
        ["NameTag"] = "Ruin Rush"
    },
    {
        ["difficulties"] = {
            {
                ["enemyLevel"] = 115,
                ["onlyUpperTiers"] = false,
                ["damageMultiplier"] = 1,
                ["id"] = 1,
                ["rewards"] = {},
                ["lives"] = 3,
                ["includeUpperTiers"] = true,
                ["levelRequirement"] = 115,
                ["healthMultiplier"] = 1,
                ["rewardLevelRange"] = {115, 120}
            },
            {
                ["enemyLevel"] = 115,
                ["onlyUpperTiers"] = true,
                ["damageMultiplier"] = 2,
                ["id"] = 5,
                ["lives"] = 1,
                ["includeUpperTiers"] = false,
                ["rewardLevelRange"] = {115, 120},
                ["minimumUpperTier"] = 1,
                ["eliteRate"] = 0.5,
                ["healthMultiplier"] = 1,
                ["levelRequirement"] = 115
            }
        },
        ["Badges"] = {["DevID"] = 0, ["LiveID"] = 0},
        ["ImageID"] = "http://www.roblox.com/asset/?id=10638707360",
        ["DungeonID"] = "http://www.roblox.com/asset/?id=10638707360",
        ["ShowOnProduction"] = true,
        ["Rewards"] = {
            {"W9T5Longsword", 3, 1},
            {"W9T5Axe", 3, 1},
            {"W9T5Scythe", 3, 1},
            {"W9T5Spear", 3, 1},
            {"W9T5Greatsword", 3, 1},
            {"W9T5Staff", 3, 1},
            {"W9T5Bow", 3, 1},
            {"W9T5Shield", 3, 1},
            {"W9T5Armor", 3, 1}
        },
        ["Lives"] = 1,
        ["DisplayWorldID"] = 9,
        ["CompletionExpRatio"] = 0.18,
        ["CompletionGoldRatio"] = 1,
        ["LevelRequirement"] = 115,
        ["MaxGearLevel"] = 130,
        ["ID"] = 32,
        ["WorldMissionID"] = 1,
        ["WorldID"] = 50,
        ["NameTag"] = "Treetop Trouble"
    },
    {
        ["difficulties"] = {
            {
                ["enemyLevel"] = 120,
                ["onlyUpperTiers"] = false,
                ["damageMultiplier"] = 1,
                ["id"] = 1,
                ["rewards"] = {{"AetherCrown", 2, 1}},
                ["lives"] = 3,
                ["includeUpperTiers"] = true,
                ["levelRequirement"] = 120,
                ["healthMultiplier"] = 1,
                ["rewardLevelRange"] = {120, 130}
            },
            {
                ["enemyLevel"] = 120,
                ["onlyUpperTiers"] = true,
                ["damageMultiplier"] = 2,
                ["id"] = 5,
                ["lives"] = 1,
                ["includeUpperTiers"] = false,
                ["rewardLevelRange"] = {120, 130},
                ["minimumUpperTier"] = 1,
                ["eliteRate"] = 0.5,
                ["healthMultiplier"] = 1,
                ["levelRequirement"] = 120
            }
        },
        ["Badges"] = {["DevID"] = 0, ["LiveID"] = 0},
        ["ImageID"] = "http://www.roblox.com/asset/?id=10723493392",
        ["DungeonID"] = "http://www.roblox.com/asset/?id=10723493392",
        ["ShowOnProduction"] = true,
        ["Rewards"] = {
            {"W9T5Longsword", 3, 1},
            {"W9T5Axe", 3, 1},
            {"W9T5Scythe", 3, 1},
            {"W9T5Spear", 3, 1},
            {"W9T5Greatsword", 3, 1},
            {"W9T5Staff", 3, 1},
            {"W9T5Bow", 3, 1},
            {"W9T5Shield", 3, 1},
            {"W9T5Armor", 3, 1}
        },
        ["Lives"] = 1,
        ["DisplayWorldID"] = 9,
        ["CompletionExpRatio"] = 0.18,
        ["CompletionGoldRatio"] = 1,
        ["LevelRequirement"] = 120,
        ["MaxGearLevel"] = 130,
        ["ID"] = 33,
        ["WorldMissionID"] = 2,
        ["WorldID"] = 51,
        ["NameTag"] = "Aether Fortress"
    },
    {
        ["IsTowerDungeon"] = true,
        ["Lives"] = 1,
        ["DisplayWorldID"] = 9,
        ["Subtext"] = "",
        ["LevelRequirement"] = 125,
        ["ID"] = 34,
        ["Tier5RarityScale"] = 2,
        ["WorldID"] = 52,
        ["MaxDifficultyScale"] = 1,
        ["TowerChest"] = {{"FairyEgg", 10, 1}, {"Sundae", 15, 5}, {"Doughnut", 25, 5}, {"Strawberry", 50, 5}},
        ["CanRevive"] = false,
        ["UseRewardTable"] = true,
        ["ShowOnProduction"] = true,
        ["Rewards"] = {
            {"W9T5Longsword", 2.5, 1},
            {"W9T5Axe", 2.5, 1},
            {"W9T5Scythe", 2.5, 1},
            {"W9T5Spear", 2.5, 1},
            {"W9T5Greatsword", 2.5, 1},
            {"W9T5Staff", 2.5, 1},
            {"W9T5Bow", 2.5, 1},
            {"W9T5Shield", 2.5, 1},
            {"W9T5Armor", 2.5, 1},
            {"W9T5Helmet", 1, 1},
            {"AetherEgg", 0.05, 1}
        },
        ["TowerID"] = 5,
        ["FinalBoss"] = "VaneAetherDragon",
        ["Badges"] = {["DevID"] = 2128358927, ["LiveID"] = 2128358927},
        ["ImageID"] = "http://www.roblox.com/asset/?id=10786659404",
        ["CanLeaveAloneOnSpectate"] = true,
        ["MaxGearLevel"] = 130,
        ["DungeonID"] = "http://www.roblox.com/asset/?id=10786659404",
        ["WorldMissionID"] = 2,
        ["NameTag"] = "Aether Tower",
        ["UnlockTier5"] = true
    },
    {
        ["Disabled"] = false,
        ["Lives"] = 1,
        ["DisplayWorldID"] = 5,
        ["LevelRequirement"] = 65,
        ["ID"] = 35,
        ["CompletionExpRatio"] = 0.18,
        ["WorldID"] = 53,
        ["ShowOnProduction"] = true,
        ["Rewards"] = {
            {"SolarHeart", 3, 1},
            {"Blossomfield", 3, 1},
            {"IgnisEye", 3, 1},
            {"JawLongsword", 3, 1},
            {"Firecaster", 3, 1},
            {"Dragonkin", 3, 1},
            {"Ignition", 3, 1},
            {"Torchblazer", 3, 1},
            {"IgnisDraw", 3, 1}
        },
        ["difficulties"] = {
            {
                ["enemyLevel"] = 65,
                ["onlyUpperTiers"] = false,
                ["damageMultiplier"] = 1,
                ["id"] = 1,
                ["rewards"] = {{"GigaSlimeHead", 2, 1}},
                ["lives"] = 3,
                ["includeUpperTiers"] = true,
                ["levelRequirement"] = 65,
                ["healthMultiplier"] = 1,
                ["rewardLevelRange"] = {65, 75}
            },
            {
                ["enemyLevel"] = 65,
                ["onlyUpperTiers"] = true,
                ["damageMultiplier"] = 2,
                ["id"] = 5,
                ["lives"] = 1,
                ["includeUpperTiers"] = false,
                ["rewardLevelRange"] = {65, 75},
                ["minimumUpperTier"] = 1,
                ["eliteRate"] = 0.5,
                ["healthMultiplier"] = 1,
                ["levelRequirement"] = 65
            }
        },
        ["CompletionGoldRatio"] = 1,
        ["Badges"] = {["DevID"] = 0, ["LiveID"] = 2124852057},
        ["MaxGearLevel"] = 65,
        ["DungeonID"] = "http://www.roblox.com/asset/?id=12643662004",
        ["WorldMissionID"] = 2,
        ["NameTag"] = "Konoh Inferno",
        ["ImageID"] = "http://www.roblox.com/asset/?id=12643662004"
    },
    {
        ["Disabled"] = false,
        ["Lives"] = 1,
        ["DisplayWorldID"] = 6,
        ["LevelRequirement"] = 80,
        ["ID"] = 36,
        ["CompletionExpRatio"] = 0.18,
        ["WorldID"] = 54,
        ["ShowOnProduction"] = true,
        ["Rewards"] = {
            {"KrakenShield", 3, 1},
            {"KrakenEyes", 3, 1},
            {"SirensWatch", 3, 1},
            {"Deeptrench", 3, 1},
            {"KrakenStaff", 3, 1},
            {"Squidbane", 3, 1},
            {"NeptuneTrident", 3, 1},
            {"NightTerror", 3, 1},
            {"SirensSong", 3, 1}
        },
        ["difficulties"] = {
            {
                ["enemyLevel"] = 80,
                ["onlyUpperTiers"] = false,
                ["damageMultiplier"] = 1,
                ["id"] = 1,
                ["lives"] = 3,
                ["includeUpperTiers"] = true,
                ["levelRequirement"] = 80,
                ["healthMultiplier"] = 1,
                ["rewardLevelRange"] = {80, 90}
            },
            {
                ["enemyLevel"] = 80,
                ["onlyUpperTiers"] = true,
                ["damageMultiplier"] = 2,
                ["id"] = 5,
                ["lives"] = 1,
                ["includeUpperTiers"] = false,
                ["rewardLevelRange"] = {80, 90},
                ["minimumUpperTier"] = 1,
                ["eliteRate"] = 0.5,
                ["healthMultiplier"] = 1,
                ["levelRequirement"] = 80
            }
        },
        ["CompletionGoldRatio"] = 1,
        ["Badges"] = {["DevID"] = 0, ["LiveID"] = 2124852062},
        ["MaxGearLevel"] = 80,
        ["DungeonID"] = "http://www.roblox.com/asset/?id=11514348692",
        ["WorldMissionID"] = 2,
        ["NameTag"] = "Treasure Hunt",
        ["ImageID"] = "http://www.roblox.com/asset/?id=11514348590"
    },
    {
        ["Disabled"] = false,
        ["Lives"] = 1,
        ["DisplayWorldID"] = 7,
        ["LevelRequirement"] = 95,
        ["ID"] = 37,
        ["CompletionExpRatio"] = 0.18,
        ["WorldID"] = 55,
        ["ShowOnProduction"] = true,
        ["Rewards"] = {
            {"Crestfall", 3, 1},
            {"ShiningBanner", 3, 1},
            {"Legacy", 3, 1},
            {"GuildedChampion", 3, 1},
            {"WingsOfDare", 3, 1},
            {"GrimDay", 3, 1},
            {"Proudmaker", 3, 1},
            {"GreatBow", 3, 1},
            {"AngelArmor", 3, 1}
        },
        ["difficulties"] = {
            {
                ["enemyLevel"] = 95,
                ["onlyUpperTiers"] = false,
                ["damageMultiplier"] = 1,
                ["id"] = 1,
                ["rewards"] = {{"SpartanHelmet", 2, 1}},
                ["lives"] = 3,
                ["includeUpperTiers"] = true,
                ["levelRequirement"] = 95,
                ["healthMultiplier"] = 1,
                ["rewardLevelRange"] = {95, 100}
            },
            {
                ["enemyLevel"] = 95,
                ["onlyUpperTiers"] = true,
                ["damageMultiplier"] = 2,
                ["id"] = 5,
                ["lives"] = 1,
                ["includeUpperTiers"] = false,
                ["rewardLevelRange"] = {95, 100},
                ["minimumUpperTier"] = 1,
                ["eliteRate"] = 0.5,
                ["healthMultiplier"] = 1,
                ["levelRequirement"] = 95
            }
        },
        ["CompletionGoldRatio"] = 1,
        ["Badges"] = {["DevID"] = 0, ["LiveID"] = 2124852072},
        ["MaxGearLevel"] = 95,
        ["DungeonID"] = "http://www.roblox.com/asset/?id=11636762034",
        ["WorldMissionID"] = 2,
        ["NameTag"] = "The Labyrinth",
        ["ImageID"] = "http://www.roblox.com/asset/?id=11636762173"
    },
    {
        ["IsTowerDungeon"] = true,
        ["Disabled"] = false,
        ["Lives"] = 1,
        ["DisplayWorldID"] = 111,
        ["Subtext"] = "",
        ["LevelRequirement"] = 100,
        ["ID"] = 38,
        ["Tier5RarityScale"] = 2,
        ["WorldID"] = 57,
        ["IsInfiniteTower"] = true,
        ["MaxDifficultyScale"] = 1,
        ["ShowOnProduction"] = true,
        ["Rewards"] = {{"SuperEquipmentChest", 100, 1}},
        ["TowerID"] = 0,
        ["FinalBoss"] = "VaneAetherDragon",
        ["Badges"] = {["DevID"] = 0, ["LiveID"] = 0},
        ["ImageID"] = "http://www.roblox.com/asset/?id=13812183126",
        ["CanLeaveAloneOnSpectate"] = true,
        ["MaxGearLevel"] = 150,
        ["DungeonID"] = "http://www.roblox.com/asset/?id=13812183126",
        ["WorldMissionID"] = 3,
        ["NameTag"] = "Infinite Tower",
        ["UnlockTier5"] = true
    },
    {
        ["IsTowerDungeon"] = true,
        ["Disabled"] = false,
        ["Lives"] = 1,
        ["DisplayWorldID"] = 112,
        ["Subtext"] = "",
        ["LevelRequirement"] = 1,
        ["ID"] = 39,
        ["Tier5RarityScale"] = 2,
        ["WorldID"] = 58,
        ["MaxDifficultyScale"] = 1,
        ["TowerID"] = 0,
        ["ShowOnProduction"] = true,
        ["Rewards"] = {{"EquipmentChest", 100, 1}},
        ["Badges"] = {["DevID"] = 0, ["LiveID"] = 0},
        ["FinalBoss"] = "VaneAetherDragon",
        ["CanLeaveAloneOnSpectate"] = true,
        ["ImageID"] = "rbxassetid://14397097681",
        ["DungeonID"] = "rbxassetid://14397097681",
        ["MaxGearLevel"] = 150,
        ["IsCelestialTower"] = true,
        ["WorldMissionID"] = 3,
        ["NameTag"] = "Celestial Tower",
        ["UnlockTier5"] = true
    },
    {
        ["Disabled"] = false,
        ["Lives"] = 1,
        ["DisplayWorldID"] = 113,
        ["LevelRequirement"] = 130,
        ["ID"] = 40,
        ["CompletionExpRatio"] = 0.18,
        ["WorldID"] = 59,
        ["IsDailyDungeon"] = true,
        ["ShowOnProduction"] = true,
        ["Rewards"] = {
            {"Crestfall", 3, 1},
            {"ShiningBanner", 3, 1},
            {"Legacy", 3, 1},
            {"GuildedChampion", 3, 1},
            {"WingsOfDare", 3, 1},
            {"GrimDay", 3, 1},
            {"Proudmaker", 3, 1},
            {"GreatBow", 3, 1},
            {"AngelArmor", 3, 1}
        },
        ["difficulties"] = {
            {
                ["enemyLevel"] = 130,
                ["onlyUpperTiers"] = false,
                ["damageMultiplier"] = 1,
                ["id"] = 1,
                ["lives"] = 3,
                ["includeUpperTiers"] = true,
                ["levelRequirement"] = 130,
                ["healthMultiplier"] = 1,
                ["rewardLevelRange"] = {130, 150}
            },
            {
                ["enemyLevel"] = 130,
                ["onlyUpperTiers"] = true,
                ["damageMultiplier"] = 2,
                ["id"] = 5,
                ["lives"] = 1,
                ["includeUpperTiers"] = false,
                ["rewardLevelRange"] = {130, 150},
                ["minimumUpperTier"] = 1,
                ["eliteRate"] = 0.5,
                ["healthMultiplier"] = 1,
                ["levelRequirement"] = 130
            }
        },
        ["CompletionGoldRatio"] = 1,
        ["Badges"] = {["DevID"] = 0, ["LiveID"] = 0},
        ["MaxGearLevel"] = 150,
        ["DungeonID"] = "rbxassetid://11636762034",
        ["WorldMissionID"] = 3,
        ["NameTag"] = "Daily Dungeon",
        ["ImageID"] = "rbxassetid://11636762034"
    },
    {
        ["Disabled"] = false,
        ["Lives"] = 1,
        ["DisplayWorldID"] = 10,
        ["LevelRequirement"] = 130,
        ["ID"] = 41,
        ["CompletionExpRatio"] = 0.18,
        ["WorldID"] = 60,
        ["ShowOnProduction"] = true,
        ["Rewards"] = {
            {"W10T5Longsword", 3, 1},
            {"W10T5Axe", 3, 1},
            {"W10T5Scythe", 3, 1},
            {"W10T5Spear", 3, 1},
            {"W10T5Greatsword", 3, 1},
            {"W10T5Staff", 3, 1},
            {"W10T5Bow", 3, 1},
            {"W10T5Shield", 3, 1},
            {"W10T5Armor", 3, 1}
        },
        ["difficulties"] = {
            {
                ["enemyLevel"] = 130,
                ["onlyUpperTiers"] = false,
                ["damageMultiplier"] = 1,
                ["id"] = 1,
                ["rewards"] = {},
                ["lives"] = 3,
                ["includeUpperTiers"] = true,
                ["levelRequirement"] = 130,
                ["healthMultiplier"] = 1,
                ["rewardLevelRange"] = {130, 135}
            },
            {
                ["enemyLevel"] = 130,
                ["onlyUpperTiers"] = true,
                ["damageMultiplier"] = 2,
                ["id"] = 5,
                ["lives"] = 1,
                ["includeUpperTiers"] = false,
                ["rewardLevelRange"] = {130, 135},
                ["minimumUpperTier"] = 1,
                ["eliteRate"] = 0.5,
                ["healthMultiplier"] = 1,
                ["levelRequirement"] = 130
            }
        },
        ["CompletionGoldRatio"] = 1,
        ["Badges"] = {["DevID"] = 0, ["LiveID"] = 0},
        ["MaxGearLevel"] = 135,
        ["DungeonID"] = "http://www.roblox.com/asset/?id=14884511593",
        ["WorldMissionID"] = 1,
        ["NameTag"] = "Crystal Chaos",
        ["ImageID"] = "http://www.roblox.com/asset/?id=14884511593"
    },
    {
        ["Disabled"] = false,
        ["Lives"] = 1,
        ["DisplayWorldID"] = 10,
        ["LevelRequirement"] = 135,
        ["ID"] = 42,
        ["CompletionExpRatio"] = 0.18,
        ["WorldID"] = 61,
        ["ShowOnProduction"] = true,
        ["Rewards"] = {
            {"W10T5Longsword", 3, 1},
            {"W10T5Axe", 3, 1},
            {"W10T5Scythe", 3, 1},
            {"W10T5Spear", 3, 1},
            {"W10T5Greatsword", 3, 1},
            {"W10T5Staff", 3, 1},
            {"W10T5Bow", 3, 1},
            {"W10T5Shield", 3, 1},
            {"W10T5Armor", 3, 1}
        },
        ["difficulties"] = {
            {
                ["enemyLevel"] = 135,
                ["onlyUpperTiers"] = false,
                ["damageMultiplier"] = 1,
                ["id"] = 1,
                ["rewards"] = {},
                ["lives"] = 3,
                ["includeUpperTiers"] = true,
                ["levelRequirement"] = 135,
                ["healthMultiplier"] = 1,
                ["rewardLevelRange"] = {135, 150}
            },
            {
                ["enemyLevel"] = 135,
                ["onlyUpperTiers"] = true,
                ["damageMultiplier"] = 2,
                ["id"] = 5,
                ["lives"] = 1,
                ["includeUpperTiers"] = false,
                ["rewardLevelRange"] = {135, 150},
                ["minimumUpperTier"] = 1,
                ["eliteRate"] = 0.5,
                ["healthMultiplier"] = 1,
                ["levelRequirement"] = 135
            }
        },
        ["CompletionGoldRatio"] = 1,
        ["Badges"] = {["DevID"] = 0, ["LiveID"] = 0},
        ["MaxGearLevel"] = 140,
        ["DungeonID"] = "http://www.roblox.com/asset/?id=14967647185",
        ["WorldMissionID"] = 2,
        ["NameTag"] = "Astral Academy",
        ["ImageID"] = "http://www.roblox.com/asset/?id=14967647185"
    },
    {
        ["IsTowerDungeon"] = true,
        ["Lives"] = 1,
        ["DisplayWorldID"] = 10,
        ["Subtext"] = "",
        ["LevelRequirement"] = 140,
        ["ID"] = 43,
        ["Tier5RarityScale"] = 2,
        ["WorldID"] = 62,
        ["MaxDifficultyScale"] = 1,
        ["TowerChest"] = {{"ArcaneEgg", 10, 1}, {"Sundae", 15, 5}, {"Doughnut", 25, 5}, {"Strawberry", 50, 5}},
        ["CanRevive"] = false,
        ["UseRewardTable"] = true,
        ["ShowOnProduction"] = true,
        ["Rewards"] = {
            {"W10T5Longsword", 2.5, 1},
            {"W10T5Axe", 2.5, 1},
            {"W10T5Scythe", 2.5, 1},
            {"W10T5Spear", 2.5, 1},
            {"W10T5Greatsword", 2.5, 1},
            {"W10T5Staff", 2.5, 1},
            {"W10T5Bow", 2.5, 1},
            {"W10T5Shield", 2.5, 1},
            {"W10T5Armor", 2.5, 1}
        },
        ["TowerID"] = 6,
        ["FinalBoss"] = "BOSSKandrix",
        ["Badges"] = {["DevID"] = 2128358927, ["LiveID"] = 2153489069},
        ["ImageID"] = "http://www.roblox.com/asset/?id=10786659404",
        ["CanLeaveAloneOnSpectate"] = true,
        ["MaxGearLevel"] = 150,
        ["DungeonID"] = "http://www.roblox.com/asset/?id=10786659404",
        ["WorldMissionID"] = 2,
        ["NameTag"] = "Arcane Tower",
        ["UnlockTier5"] = true
    }
}
