data = {
    ["DRAFT_SELECTIONS"] = 16,
    ["ANTI_FORFEIT"] = 1.25,
    ["APRIL_FOOL_MODE"] = false,
    ["MIN_PLAYERS_MATCHMAKING"] = 5,
    ["CLR"] = {
        ["Blue"] = Color3.fromRGB(63, 63, 255),
        ["Green"] = Color3.fromRGB(44, 229, 44),
        ["Neutral"] = Color3.fromRGB(255, 255, 255),
        ["Yellow"] = Color3.fromRGB(255, 255, 63),
        ["Red"] = Color3.fromRGB(255, 63, 63)
    },
    ["HARD_QUEST_BB"] = 200,
    ["DEBUGMODE"] = true,
    ["DAILY_RESET_TICK"] = 28800,
    ["REVERSECOLORORDER"] = {["Blue"] = 4, ["Green"] = 3, ["Neutral"] = 1, ["Yellow"] = 5, ["Red"] = 2},
    ["CARDSIZE"] = "470, 750",
    ["COLORORDER"] = {"Neutral", "Red", "Green", "Blue", "Yellow"},
    ["ANTI_TIME"] = 120,
    ["RANDOM_CRITS_ENABLED"] = false,
    ["WEEKLY_RESET_TICK"] = 604800,
    ["DRAFT_CULL_AMOUNT"] = 8,
    ["EVENTCURRENCYICON"] = {["Necroenzyme"] = "ðŸ§ª"},
    ["AUTOSAVE_TIME"] = 20,
    ["CARDZINDEX"] = 2,
    ["ANTI_FARMING_ON"] = true,
    ["CURRENT_OFFER"] = {"HalloweenBundle", "NecrosyndicatesAct3", "StarsBundle", "EggEmporiumBundle", "RPSBundle"},
    ["CLRTXT"] = {["Blue"] = "B", ["Green"] = "G", ["Neutral"] = "C", ["Yellow"] = "Y", ["Red"] = "R"},
    ["FIRST_TICK"] = 1672916400,
    ["EVENT_CURRENCY_START_AMOUNT"] = 5,
    ["EASY_QUEST_BB"] = 100,
    ["DRAFT_ORDER"] = {
        "Early",
        "Buildarounds",
        "Early",
        "Ramp",
        "Early",
        "Meme",
        "Early",
        "Buildarounds",
        "Control",
        "Early",
        "Ramp",
        "Meme",
        "Early",
        "Buildarounds",
        "Early",
        "Meme"
    },
    ["DEFAULT_SETTINGS"] = {["Mute Music"] = false, ["Colorblind Mode"] = false, ["Dark Mode"] = false},
    ["RARECLR"] = {
        ["Legendary"] = Color3.fromRGB(255, 217, 80),
        ["Token"] = Color3.fromRGB(82, 120, 117),
        ["Common"] = Color3.fromRGB(255, 255, 255),
        ["Epic"] = Color3.fromRGB(255, 47, 47),
        ["Uncommon"] = Color3.fromRGB(108, 255, 246),
        ["Rare"] = Color3.fromRGB(192, 103, 255)
    },
    ["RARITYORDER"] = {"Common", "Uncommon", "Rare", "Epic", "Legendary", "Token", "Shedletsky"},
    ["EVENTCURRENCYIMAGE"] = {["Necroenzyme"] = "12522605621"},
    ["RARITIES"] = {
        ["Shedletsky"] = 7,
        ["Legendary"] = 5,
        ["Token"] = 6,
        ["Common"] = 1,
        ["Epic"] = 4,
        ["Uncommon"] = 2,
        ["Rare"] = 3
    },
    ["BGCLR"] = {
        ["Blue"] = Color3.fromRGB(15, 15, 58),
        ["Green"] = Color3.fromRGB(15, 58, 15),
        ["Neutral"] = Color3.fromRGB(58, 58, 58),
        ["Yellow"] = Color3.fromRGB(117, 79, 17),
        ["Red"] = Color3.fromRGB(58, 15, 15)
    },
    ["LOGOS"] = {
        ["Astral"] = "11761920421",
        ["Plurral"] = "11761920206",
        ["Smiley"] = "11761919783",
        ["Arkhive"] = "11761899005",
        ["Lordbreaker"] = "11761920519",
        ["Nefoco"] = "11761920150"
    }
}
