data = {
    ["CashSymbol"] = "$",
    ["LifeSkips"] = "function: 0xeaafc75668227e95",
    ["Suffixes"] = {
        "k",
        "M",
        "B",
        "T",
        "qd",
        "Qn",
        "sx",
        "Sp",
        "O",
        "N",
        "de",
        "Ud",
        "DD",
        "tdD",
        "qdD",
        "QnD",
        "sxD",
        "SpD",
        "OcD",
        "NvD",
        "Vgn",
        "UVg",
        "DVg",
        "TVg",
        "qtV",
        "QnV",
        "SeV",
        "SPG",
        "OVG",
        "NVG",
        "TGN",
        "UTG",
        "DTG",
        "tsTG",
        "qtTG",
        "QnTG",
        "ssTG",
        "SpTG",
        "OcTG",
        "NoTG",
        "QdDR",
        "uQDR",
        "dQDR",
        "tQDR",
        "qdQDR",
        "QnQDR",
        "sxQDR",
        "SpQDR",
        "OQDDr",
        "NQDDr",
        "qQGNT",
        "uQGNT",
        "dQGNT",
        "tQGNT",
        "qdQGNT",
        "QnQGNT",
        "sxQGNT",
        "SpQGNT",
        "OQQGNT",
        "NQQGNT",
        "SXGNTL",
        "USXGNTL",
        "DSXGNTL",
        "TSXGNTL",
        "QTSXGNTL",
        "QNSXGNTL",
        "SXSXGNTL",
        "SPSXGNTL",
        "OSXGNTL",
        "NVSXGNTL",
        "SPTGNTL",
        "USPTGNTL",
        "DSPTGNTL",
        "TSPTGNTL",
        "QTSPTGNTL",
        "QNSPTGNTL",
        "SXSPTGNTL",
        "SPSPTGNTL",
        "OSPTGNTL",
        "NVSPTGNTL",
        "OTGNTL",
        "UOTGNTL",
        "DOTGNTL",
        "TOTGNTL",
        "QTOTGNTL",
        "QNOTGNTL",
        "SXOTGNTL",
        "SPOTGNTL",
        "OTOTGNTL",
        "NVOTGNTL",
        "NONGNTL",
        "UNONGNTL",
        "DNONGNTL",
        "TNONGNTL",
        "QTNONGNTL",
        "QNNONGNTL",
        "SXNONGNTL",
        "SPNONGNTL",
        "OTNONGNTL",
        "NONONGNTL",
        "CENT",
        "UNCENT"
    },
    ["CalculateLifeSkips"] = "function: 0x3cdee0dd2ebce915",
    ["DealWithPoints"] = "function: 0x7f6c5509fb5db8f5",
    ["RebornPrice"] = "function: 0xdd454ab8aa90b105",
    ["HandleMoney"] = "function: 0xbf94db8b49ecbbc5",
    ["ShortToLong"] = "function: 0xdee524e4c4715c55",
    ["HandleLife"] = "function: 0x1fb71ee648496325",
    ["FormatWithComma"] = "function: 0x56a909f6a28b3275"
}
