data = {
    ["WorkbenchMeta"] = {
        ["mapleWorkbench"] = {
            ["id"] = "mapleWorkbench",
            ["canCraft"] = {
                "shieldMaple",
                "treeTap",
                "woodTube",
                "woodTubeMerger",
                "berryBasket",
                "berryBasketIndustrial",
                "sapBoiler",
                "mapleSyrupBottler"
            },
            ["displayName"] = "Maple Workbench"
        },
        ["redBronzeRefinery"] = {
            ["id"] = "redBronzeRefinery",
            ["canCraft"] = {"redBronzeIngot"},
            ["displayName"] = "Red Bronze Refinery"
        },
        ["brewingStand"] = {
            ["id"] = "brewingStand",
            ["canCraft"] = {"potionStrength1", "potionRegen1", "voidPotion", "toxinPotion"},
            ["displayName"] = "Brewing Stand"
        },
        ["cratePacker2"] = {
            ["id"] = "cratePacker2",
            ["canCraft"] = {
                "crateMetalWheat",
                "crateMetalTomato",
                "crateMetalPotato",
                "crateMetalCarrot",
                "crateMetalOnion",
                "crateMetalStarfruit",
                "crateMetalPumpkin",
                "crateMetalMelon",
                "crateMetalRadish",
                "crateMetalApple",
                "crateMetalAvocado",
                "crateMetalCoconut",
                "crateMetalKiwi",
                "crateMetalLemon",
                "crateMetalOrange",
                "crateMetalPlum",
                "crateMetalPineapple",
                "crateMetalCactus",
                "crateMetalSpinach"
            },
            ["displayName"] = "Crate Packer Tier 2"
        },
        ["lightingStation"] = {
            ["id"] = "lightingStation",
            ["gamepass"] = {["gamepassId"] = "LIGHTING_STATION", ["gamepassTitle"] = "LightingStation"},
            ["canCraft"] = {"candle", "lantern", "lampPost", "sealantern", "wallLamp", "lampPost1"},
            ["displayName"] = "Lighting Station"
        },
        ["steelPress"] = {
            ["id"] = "steelPress",
            ["canCraft"] = {"steelRod", "boltSteel", "plateSteel"},
            ["molds"] = {
                {["moldTool"] = "moldRod", ["targetTool"] = "steelRod"},
                {["moldTool"] = "moldBolt", ["targetTool"] = "boltSteel"},
                {["moldTool"] = "moldPlate", ["targetTool"] = "plateSteel"}
            },
            ["displayName"] = "Steel Press"
        },
        ["palletPacker"] = {
            ["id"] = "palletPacker",
            ["canCraft"] = {
                "palletBirch",
                "palletHickory",
                "palletMaple",
                "palletOak",
                "palletPine",
                "palletSpirit",
                "palletCherryBlossom"
            },
            ["displayName"] = "Pallet Packer"
        },
        ["pottery"] = {
            ["id"] = "pottery",
            ["canCraft"] = {"flowerPot1", "flowerPot2", "flowerPot3", "flowerPot4"},
            ["displayName"] = "Pottery Bench"
        },
        ["fireworkBarrel"] = {
            ["id"] = "fireworkBarrel",
            ["gamepass"] = {["gamepassId"] = "FIREWORK_BARREL", ["gamepassTitle"] = "FireworkBarrel"},
            ["canCraft"] = {"fireworkSmall", "fireworkMedium", "fireworkLarge"},
            ["displayName"] = "Firework Barrel"
        },
        ["basic"] = {
            ["categories"] = {
                {["id"] = "recommended", ["toolCategories"] = {}, ["displayName"] = "Recommended"},
                {["id"] = "all", ["toolCategories"] = {}, ["displayName"] = "All"},
                {["id"] = "tool", ["toolCategories"] = {2}, ["displayName"] = "Tools"},
                {["id"] = "block", ["toolCategories"] = {0}, ["displayName"] = "Blocks"},
                {["id"] = "workbench", ["toolCategories"] = {6}, ["displayName"] = "Workbenches"},
                {["id"] = "utility", ["toolCategories"] = {4}, ["displayName"] = "Utility"},
                {["id"] = "factory", ["toolCategories"] = {5}, ["displayName"] = "Factory"},
                {["id"] = "fun", ["toolCategories"] = {7}, ["displayName"] = "Fun"}
            },
            ["nextLevel"] = "workbench2",
            ["canCraft"] = {
                "woodPickaxe",
                "woodAxe",
                "swordWood",
                "malletWood",
                "hammerGranite",
                "stonePickaxe",
                "stoneAxe",
                "stoneSword",
                "hoe",
                "wateringCan",
                "sickleStone",
                "fishingRod",
                "net",
                "bucketEmpty",
                "shovelStone",
                "clippers",
                "campfire",
                "smallFurnace",
                "sawmill",
                "polishingStation",
                "stairOak",
                "oakSlab",
                "woodFence",
                "fenceVineStem",
                "ladder",
                "doorPine",
                "doorPine2",
                "doorGlass",
                "signOak",
                "honeyBlock",
                "boneBlock",
                "torch",
                "lantern1",
                "bannerElephant",
                "slimeBlockGreen",
                "leavesBlock",
                "trapDoorOak",
                "coralBlockBlue",
                "iceCompact",
                "snowCompact",
                "candyCane",
                "woodPlate",
                "targetBlockWood",
                "targetBlockIron",
                "chest",
                "mailbox",
                "trellis",
                "trashCan",
                "workbench2",
                "workbench1",
                "cuttingTable",
                "cookingTable",
                "carpentryStation",
                "animalBench",
                "snowballMachine",
                "instrumentBench",
                "jukebox",
                "obbyKit",
                "floralBench",
                "lightingStation",
                "bannerBench",
                "fireworkBarrel"
            },
            ["id"] = "basic",
            ["displayName"] = "Workbench Tier 1"
        },
        ["cratePacker"] = {
            ["id"] = "cratePacker",
            ["canCraft"] = {
                "crateWheat",
                "crateTomato",
                "cratePotato",
                "crateCarrot",
                "crateOnion",
                "crateStarfruit",
                "cratePumpkin",
                "crateMelon",
                "crateRadish",
                "crateApple",
                "crateAvocado",
                "crateCoconut",
                "crateKiwi",
                "crateLemon",
                "crateOrange",
                "cratePlum",
                "cratePineapple",
                "crateCactus",
                "crateSpinach"
            },
            ["displayName"] = "Crate Packer"
        },
        ["sewingStation"] = {
            ["id"] = "sewingStation",
            ["canCraft"] = {
                "yarnWhite",
                "cactusPlushie",
                "catPlushie",
                "cupcakePlushie",
                "dogPlushie",
                "mushroomPlushie",
                "otterPlushie",
                "pandaPlushie",
                "sealPlushie",
                "sharkPlushie",
                "slimeQueenPlushie",
                "unicornPlushie"
            },
            ["displayName"] = "Sewing Station"
        },
        ["cuttingTable"] = {
            ["id"] = "cuttingTable",
            ["canCraft"] = {
                "pineappleChunk",
                "cutTuna",
                "cutEel",
                "cutRedSnapper",
                "cutSalmon",
                "cutCatfish",
                "cutCarp",
                "cutTrout"
            },
            ["displayName"] = "Cutting Table"
        },
        ["electricalBench"] = {
            ["id"] = "electricalBench",
            ["levels"] = {
                ["upgradeCosts"] = {
                    {
                        ["amount"] = 1,
                        ["components"] = {
                            {["amount"] = 150, ["toolName"] = "steelIngot"},
                            {["amount"] = 20, ["toolName"] = "boltCopper"},
                            {["amount"] = 250, ["toolName"] = "electrite"}
                        },
                        ["toolName"] = "electricalBench"
                    },
                    {
                        ["amount"] = 1,
                        ["components"] = {
                            {["amount"] = 450, ["toolName"] = "steelIngot"},
                            {["amount"] = 50, ["toolName"] = "boltSteel"},
                            {["amount"] = 10, ["toolName"] = "plateCopper"},
                            {["amount"] = 750, ["toolName"] = "electrite"}
                        },
                        ["toolName"] = "electricalBench"
                    }
                },
                ["maxLevel"] = 3,
                ["canCraftLevels"] = {
                    {
                        "wireTool",
                        "ledLight",
                        "logicSwitch",
                        "generatorCoal",
                        "fireworkLauncher",
                        "discoBallRuby",
                        "discoBallGold",
                        "discoBallDiamond",
                        "discoFloorTile1",
                        "discoFloorTile2",
                        "discoFloorTile3",
                        "discoFloorTile4"
                    },
                    {
                        "logicAnd",
                        "logicOr",
                        "logicSplitter",
                        "logicCombiner",
                        "generatorSolarPanel",
                        "logicXor",
                        "logicButton",
                        "conveyorSplitter"
                    },
                    {"steamGenerator", "logicTimer", "totemDisabler", "conveyorSensor"}
                }
            },
            ["canCraft"] = {},
            ["displayName"] = "Electrical Workbench"
        },
        ["bannerBench"] = {
            ["id"] = "bannerBench",
            ["gamepass"] = {["gamepassId"] = "BANNER_BENCH", ["gamepassTitle"] = "BannerBench"},
            ["canCraft"] = {
                "bannerSpark",
                "bannerSnowflake",
                "bannerCrown",
                "bannerLotus",
                "bannerEye",
                "bannerSun",
                "bannerClover",
                "bannerPlant",
                "bannerSword",
                "bannerPig",
                "bannerMoon",
                "bannerPheonix",
                "bannerGoat",
                "bannerElephant",
                "bannerTree",
                "bannerCow",
                "bannerAquamarine"
            },
            ["displayName"] = "Banner Workbench"
        },
        ["copperPress"] = {
            ["id"] = "copperPress",
            ["canCraft"] = {"copperRod", "boltCopper", "plateCopper"},
            ["molds"] = {
                {["moldTool"] = "moldRod", ["targetTool"] = "copperRod"},
                {["moldTool"] = "moldBolt", ["targetTool"] = "boltCopper"},
                {["moldTool"] = "moldPlate", ["targetTool"] = "plateCopper"}
            },
            ["displayName"] = "Copper Press"
        },
        ["anvil"] = {
            ["id"] = "anvil",
            ["canCraft"] = {
                "ironAxe",
                "ironSword",
                "ironPickaxe",
                "sickleIron",
                "ironWarAxe",
                "rageblade",
                "spikeCactus",
                "steelRod",
                "gildedSteelRod",
                "gildedSteelAxe",
                "gildedSteelPickaxe",
                "sickleGildedSteel",
                "diamondAxe",
                "diamondPickaxe",
                "sickleDiamond",
                "diamondSword2",
                "diamondHammer",
                "swordPrismarine",
                "gildedSteelHammer",
                "spellbook",
                "spellbookAquamarine",
                "spellbookSpirit",
                "moldRod",
                "moldBolt",
                "moldPlate",
                "gearbox",
                "staffDesert",
                "obsidianGreatsword",
                "opalSword",
                "opalPickaxe",
                "opalAxe",
                "infernalHammer",
                "rubySword",
                "slimeQueenScepter",
                "serpentsHook",
                "serpentsBane",
                "voidMattock",
                "bow1",
                "bow4",
                "bow5",
                "arrow1",
                "arrow2",
                "arrow3",
                "bow2",
                "bow3",
                "longArrow1",
                "longArrow2",
                "longArrow3",
                "longArrow4",
                "crossbowBolt",
                "noxiousStinger"
            },
            ["displayName"] = "Anvil"
        },
        ["floralBench"] = {
            ["id"] = "floralBench",
            ["gamepass"] = {["gamepassId"] = "FLORAL_BENCH", ["gamepassTitle"] = "FloralBench"},
            ["canCraft"] = {
                "clippers",
                "hedge",
                "bushRed",
                "bushYellow",
                "bushBlue",
                "hedgeMaple",
                "bushMapleRed",
                "bushMapleYellow",
                "bushMapleBlue",
                "potBlue",
                "potRed",
                "potYellow"
            },
            ["displayName"] = "Floral Bench"
        },
        ["instrumentBench"] = {
            ["id"] = "instrumentBench",
            ["gamepass"] = {["gamepassId"] = "INSTRUMENT_BENCH", ["gamepassTitle"] = "InstrumentBench"},
            ["canCraft"] = {
                "instrumentBongo",
                "instrumentTambourine",
                "instrumentPanFlute",
                "instrumentMelodica",
                "instrumentKalimba",
                "instrumentGuitar"
            },
            ["displayName"] = "Instrument Workbench"
        },
        ["workbench3"] = {
            ["categories"] = {
                {["id"] = "recommended", ["toolCategories"] = {}, ["displayName"] = "Recommended"},
                {["id"] = "all", ["toolCategories"] = {}, ["displayName"] = "All"},
                {["id"] = "tool", ["toolCategories"] = {2}, ["displayName"] = "Tools"},
                {["id"] = "block", ["toolCategories"] = {0}, ["displayName"] = "Blocks"},
                {["id"] = "workbench", ["toolCategories"] = {6}, ["displayName"] = "Workbenches"},
                {["id"] = "utility", ["toolCategories"] = {4}, ["displayName"] = "Utility"},
                {["id"] = "factory", ["toolCategories"] = {5}, ["displayName"] = "Factory"},
                {["id"] = "fun", ["toolCategories"] = {7}, ["displayName"] = "Fun"}
            },
            ["nextLevel"] = "workbench4",
            ["canCraft"] = {
                "woodPickaxe",
                "woodAxe",
                "swordWood",
                "malletWood",
                "hammerGranite",
                "stonePickaxe",
                "stoneAxe",
                "stoneSword",
                "hoe",
                "wateringCan",
                "sickleStone",
                "fishingRod",
                "net",
                "bucketEmpty",
                "shovelStone",
                "clippers",
                "fishingRodIron",
                "bait",
                "baitT2",
                "waterJug",
                "quill",
                "pesticideSpray",
                "campfire",
                "smallFurnace",
                "sawmill",
                "polishingStation",
                "stonecutter",
                "composter",
                "vendingMachine",
                "honeyPress",
                "cheesemaker",
                "churner",
                "sprinklerBasic",
                "waterCatcher",
                "waterStorageBarrel",
                "blastFurnace",
                "portalUnderworld",
                "washingStation",
                "stairOak",
                "oakSlab",
                "woodFence",
                "fenceVineStem",
                "ladder",
                "doorPine",
                "doorPine2",
                "doorGlass",
                "signOak",
                "honeyBlock",
                "boneBlock",
                "torch",
                "lantern1",
                "bannerElephant",
                "slimeBlockGreen",
                "leavesBlock",
                "trapDoorOak",
                "coralBlockBlue",
                "iceCompact",
                "snowCompact",
                "candyCane",
                "woodPlate",
                "targetBlockWood",
                "targetBlockIron",
                "prismarineBlock",
                "bambooBlock",
                "bambooDriedBlock",
                "mossyStair",
                "cobblestoneStair",
                "mossyCobblestoneStair",
                "voidStoneStair",
                "voidStoneBrickStair",
                "voidStoneCobbleStair",
                "voidStonePolishedStair",
                "voidStoneCarvedStair",
                "voidStoneTiledStair",
                "checkerTiledStair",
                "cautionStair",
                "stairStoneBrick",
                "stairSlate",
                "marblePillar",
                "pearlBlock",
                "buffalkorCrystalBlock",
                "coalBlock",
                "ironBlock",
                "goldBlock",
                "copperBlock",
                "redBronzeBlock",
                "diamondBlock",
                "rubyBlock",
                "opalBlock",
                "mushroomBlock",
                "mossySlab",
                "cobblestoneSlab",
                "mossyCobblestoneSlab",
                "voidStoneSlab",
                "voidStoneBrickSlab",
                "voidStoneCobbleSlab",
                "voidStonePolishedSlab",
                "voidStoneCarvedSlab",
                "voidStoneTiledSlab",
                "checkerTiledSlab",
                "cautionSlab",
                "stoneBrickMossy",
                "stoneBrickSlab",
                "slateSlab",
                "doorIron",
                "carpet",
                "pond",
                "voidBlock",
                "mossyBlock",
                "cobblestoneBlock",
                "mossyCobblestoneBlock",
                "amethystBlock",
                "voidStoneBrick",
                "voidStoneCobble",
                "voidStonePolished",
                "voidStoneCarved",
                "voidStoneTiled",
                "whiteStair",
                "whiteSlab",
                "pastelRedStair",
                "pastelRedSlab",
                "vineStemLadder",
                "chest",
                "mailbox",
                "trellis",
                "trashCan",
                "chestMedium",
                "foodProcessor2",
                "teleporter",
                "orbSlimeIsland",
                "chestMediumIndustrial",
                "steelMill",
                "chestMediumIndustrialIO",
                "conveyorForward",
                "conveyorRight",
                "conveyorLeft",
                "conveyorRampUp",
                "conveyorRampDown",
                "conveyorRandomizer",
                "conveyorMerger",
                "conveyorSplitterFiltered",
                "smelterIndustrial",
                "steelPress",
                "copperPress",
                "drill",
                "ovenIndustrial",
                "treeCutter",
                "sawmillIndustrial",
                "palletPacker",
                "polishingStationIndustrial",
                "stonecutterIndustrial",
                "washingStationIndustrial",
                "redBronzeRefinery",
                "portalSlime",
                "orbIslandBlack",
                "lanternButterflySilver",
                "lanternButterflyRed",
                "lanternButterflyGreen",
                "workbench4",
                "workbench3",
                "workbench2",
                "workbench1",
                "cuttingTable",
                "cookingTable",
                "carpentryStation",
                "animalBench",
                "anvil",
                "coloringStation",
                "brewingStand",
                "electricalBench",
                "mapleWorkbench",
                "sewingStation",
                "snowballMachine",
                "instrumentBench",
                "jukebox",
                "obbyKit",
                "floralBench",
                "lightingStation",
                "bannerBench",
                "fireworkBarrel"
            },
            ["id"] = "workbench3",
            ["displayName"] = "Workbench Tier 3"
        },
        ["carpentryStation"] = {
            ["id"] = "carpentryStation",
            ["canCraft"] = {
                "1chair",
                "1stool",
                "1table",
                "1bed",
                "1bookshelf",
                "2bed",
                "2cabinet",
                "2chair",
                "2table",
                "3bed",
                "3bed1",
                "3chimney",
                "3couch",
                "3rug",
                "3rug1",
                "3sofa",
                "3table",
                "4bench",
                "4blanket",
                "4chair",
                "4chair1",
                "4grill",
                "4table",
                "4table1",
                "4tableUmbrella",
                "4umbrella",
                "beachBall",
                "beachChair",
                "beachCooler",
                "beachTable",
                "beachTowel1",
                "beachTowel2",
                "beachTowel3",
                "beachTowel4",
                "beachUmbrella",
                "weaponStand",
                "fishTankSmall",
                "fishTankMedium",
                "tankAnchor",
                "tankCastle",
                "tankShipwreck",
                "tankTreasureChestGold",
                "displayCaseSmall",
                "displayCaseLarge",
                "furnitureBell",
                "furnitureBench",
                "furnitureBenchModern",
                "furnitureBunkBed",
                "furnitureCeilingLight",
                "furnitureCeilingLight1",
                "furnitureChandelier",
                "furnitureFirecrackers",
                "furnitureFireHydrant",
                "furnitureFishingPond",
                "furnitureFluorescentLight",
                "furnitureFountain",
                "furnitureFridgeModern",
                "furnitureGong",
                "furnitureLampWall",
                "furnitureLampWooden",
                "furnitureLanternHanging",
                "furnitureLanternRed",
                "furniturePebbles",
                "furniturePlantBamboo",
                "furniturePlantBlueFlower",
                "furniturePlantBonsai",
                "furniturePlantHedge",
                "furniturePlantLeaves",
                "furniturePlantMushroom",
                "furniturePortrait",
                "furnitureShipInBottle",
                "furnitureStreetLamp",
                "furnitureStreetLamp1",
                "furnitureToilet",
                "furnitureToiletGolden",
                "furnitureWell",
                "furnitureWoodWalkway",
                "furnitureCabinetModernBottom",
                "furnitureCabinetModernTop",
                "furnitureOvenModern",
                "furnitureCactus",
                "furnitureCeilingFan",
                "furnitureCeilingLight2",
                "furnitureCeilingLight4",
                "furnitureCeilingLight5",
                "furnitureCeilingLight6",
                "furnitureCeilingLight7",
                "furnitureCeilingLight8",
                "furnitureCouch",
                "furnitureCouch1",
                "furnitureFence",
                "furnitureLantern",
                "furnitureLeaves1",
                "furnitureSink",
                "furnitureSofa",
                "furnitureSofa2",
                "furnitureStool",
                "furnitureStool1",
                "furnitureStool2",
                "furnitureStreetLamp2",
                "furnitureStreetLamp3",
                "furnitureStreetLamp4",
                "furnitureTable1",
                "furnitureTree",
                "furnitureWallLight",
                "furnitureWardrobe",
                "furnitureMedievalBookshelf",
                "furnitureMedievalCastleShield",
                "furnitureMedievalChandelier",
                "furnitureMedievalCouch",
                "furnitureMedievalGrandfatherClock",
                "furnitureMedievalHourglass",
                "furnitureMedievalKnightLampDrawer",
                "furnitureMedievalSwordInStone",
                "furnitureMedievalTable",
                "furnitureMedievalVanity",
                "furnitureMedievalWallTorch",
                "furnitureMedievalWoodenChair",
                "furnitureOrbStand",
                "spiritLavaLamp",
                "spiritBed",
                "targetStand",
                "loungeChairRed",
                "tableTopShort",
                "tableTopRed",
                "tableTopChairRed",
                "hangingGuitarRed",
                "speakerSystem",
                "wetFloorSign",
                "schoolWaterFountain",
                "lunchTableRed",
                "lunchBenchRed",
                "lockerRed",
                "schoolChairRed",
                "schoolDeskChairRed",
                "schoolDeskRed",
                "schoolBellRed",
                "blackboard",
                "whiteboard",
                "blueDinerTable",
                "blueDinerBooth",
                "blueCounterCorner",
                "blueCounterCenter",
                "blueNeonLightFries",
                "blueNeonLightIceCream",
                "blueNeonLightDrink",
                "whiteNeonLightShake",
                "blueNeonLightDiner",
                "blueNeonLightWelcome",
                "burgerNeonLight",
                "vineStemBench",
                "vineStemArchway"
            },
            ["displayName"] = "Furniture Workbench"
        },
        ["coloringStation"] = {
            ["id"] = "coloringStation",
            ["canCraft"] = {
                "whiteBlock",
                "clayWhite",
                "glassPaneRed",
                "glassBlockRed",
                "carpetRed",
                "woolRed",
                "neonWhite",
                "pastelRedBlock"
            },
            ["displayName"] = "Coloring Station"
        },
        ["foodProcessor"] = {
            ["id"] = "foodProcessor",
            ["canCraft"] = {
                "dough",
                "berryDough",
                "blueberryDough",
                "tomatoSauce",
                "tomatoSoup",
                "grapeJam",
                "jamSandwich",
                "pizzaUncooked",
                "carrotCakeBatter",
                "potatoSalad",
                "uncookedPineapplePizza",
                "applePieUncooked",
                "avocadoToast",
                "lemonBreadDough",
                "orangeCakeBatter",
                "starfruitCakeUncooked",
                "carrotRoastedHoney",
                "honeyToast",
                "appleHoney",
                "honeyLemonPuff",
                "orangeHoneycombCandy",
                "eggDeviled",
                "avocadoToastTruffle",
                "pizzaTruffle",
                "pancakeDough",
                "pancake",
                "pancakeSyrup",
                "pancakeSyrupBerries",
                "pancakeFhanhorn",
                "sushiDragonRoll",
                "sushiPhiladelphiaRoll",
                "sushiRoll",
                "sushiTaiNigiri",
                "sushiTunaRoll",
                "dumpling",
                "riceCakes",
                "kueKeju",
                "springRolls",
                "duckEggBenedict",
                "scrambledDuckEggs",
                "potatoDuckEggScramble",
                "dragonfruitAcaiBowl",
                "dragonfruitIcecream",
                "bhutanButterTea",
                "sweetRiceDessert",
                "gondoDatshi",
                "glassMilk"
            },
            ["displayName"] = "Food Processor"
        },
        ["washingStation"] = {
            ["id"] = "washingStation",
            ["canCraft"] = {
                "onionHarvested",
                "carrotHarvested",
                "potatoHarvested",
                "tomatoHarvested",
                "starfruitHarvested"
            },
            ["displayName"] = "Washing Station"
        },
        ["obbyKit"] = {
            ["id"] = "obbyKit",
            ["gamepass"] = {["gamepassId"] = "OBBY_KIT", ["gamepassTitle"] = "ObbyKit"},
            ["canCraft"] = {"parkourStart", "parkourCheckpoint", "parkourFinish", "parkourLeaderboard"},
            ["displayName"] = "Obby Kit"
        },
        ["cookingTable"] = {
            ["id"] = "cookingTable",
            ["canCraft"] = {
                "dough",
                "berryDough",
                "blueberryDough",
                "tomatoSauce",
                "tomatoSoup",
                "grapeJam",
                "jamSandwich",
                "pizzaUncooked",
                "carrotCakeBatter",
                "potatoSalad",
                "uncookedPineapplePizza",
                "applePieUncooked",
                "avocadoToast",
                "lemonBreadDough",
                "orangeCakeBatter",
                "starfruitCakeUncooked",
                "carrotRoastedHoney",
                "honeyToast",
                "appleHoney",
                "honeyLemonPuff",
                "orangeHoneycombCandy",
                "eggDeviled",
                "avocadoToastTruffle",
                "pizzaTruffle",
                "pancakeDough",
                "pancake",
                "pancakeSyrup",
                "pancakeSyrupBerries",
                "pancakeFhanhorn",
                "sushiDragonRoll",
                "sushiPhiladelphiaRoll",
                "sushiRoll",
                "sushiTaiNigiri",
                "sushiTunaRoll",
                "dumpling",
                "riceCakes",
                "kueKeju",
                "springRolls",
                "duckEggBenedict",
                "scrambledDuckEggs",
                "potatoDuckEggScramble",
                "dragonfruitAcaiBowl",
                "dragonfruitIcecream",
                "bhutanButterTea",
                "sweetRiceDessert",
                "gondoDatshi",
                "glassMilk"
            },
            ["displayName"] = "Cooking Table"
        },
        ["animalBench"] = {
            ["id"] = "animalBench",
            ["canCraft"] = {
                "bucketEmpty",
                "nameTag",
                "troughWheat",
                "troughIndustrial",
                "hayBed",
                "shears",
                "circularLoom",
                "scratchingPost",
                "milkerIndustrial",
                "woolPickerIndustrial",
                "barrelTruffleIndustrial",
                "barrelTruffle",
                "mudBed",
                "nest",
                "nestIndustrial"
            },
            ["displayName"] = "Animal Bench"
        },
        ["workbench0"] = {
            ["id"] = "workbench0",
            ["nextLevel"] = "workbench1",
            ["canCraft"] = {"woodPickaxe", "workbench1"},
            ["displayName"] = "Workbench"
        },
        ["workbench4"] = {
            ["id"] = "workbench4",
            ["categories"] = {
                {["id"] = "recommended", ["toolCategories"] = {}, ["displayName"] = "Recommended"},
                {["id"] = "all", ["toolCategories"] = {}, ["displayName"] = "All"},
                {["id"] = "tool", ["toolCategories"] = {2}, ["displayName"] = "Tools"},
                {["id"] = "block", ["toolCategories"] = {0}, ["displayName"] = "Blocks"},
                {["id"] = "workbench", ["toolCategories"] = {6}, ["displayName"] = "Workbenches"},
                {["id"] = "utility", ["toolCategories"] = {4}, ["displayName"] = "Utility"},
                {["id"] = "factory", ["toolCategories"] = {5}, ["displayName"] = "Factory"},
                {["id"] = "fun", ["toolCategories"] = {7}, ["displayName"] = "Fun"}
            },
            ["canCraft"] = {
                "woodPickaxe",
                "woodAxe",
                "swordWood",
                "malletWood",
                "hammerGranite",
                "stonePickaxe",
                "stoneAxe",
                "stoneSword",
                "hoe",
                "wateringCan",
                "sickleStone",
                "fishingRod",
                "net",
                "bucketEmpty",
                "shovelStone",
                "clippers",
                "fishingRodIron",
                "bait",
                "baitT2",
                "waterJug",
                "quill",
                "pesticideSpray",
                "campfire",
                "smallFurnace",
                "sawmill",
                "polishingStation",
                "stonecutter",
                "composter",
                "vendingMachine",
                "honeyPress",
                "cheesemaker",
                "churner",
                "sprinklerBasic",
                "waterCatcher",
                "waterStorageBarrel",
                "blastFurnace",
                "portalUnderworld",
                "washingStation",
                "vendingMachine1",
                "stairOak",
                "oakSlab",
                "woodFence",
                "fenceVineStem",
                "ladder",
                "doorPine",
                "doorPine2",
                "doorGlass",
                "signOak",
                "honeyBlock",
                "boneBlock",
                "torch",
                "lantern1",
                "bannerElephant",
                "slimeBlockGreen",
                "leavesBlock",
                "trapDoorOak",
                "coralBlockBlue",
                "iceCompact",
                "snowCompact",
                "candyCane",
                "woodPlate",
                "targetBlockWood",
                "targetBlockIron",
                "prismarineBlock",
                "bambooBlock",
                "bambooDriedBlock",
                "mossyStair",
                "cobblestoneStair",
                "mossyCobblestoneStair",
                "voidStoneStair",
                "voidStoneBrickStair",
                "voidStoneCobbleStair",
                "voidStonePolishedStair",
                "voidStoneCarvedStair",
                "voidStoneTiledStair",
                "checkerTiledStair",
                "cautionStair",
                "stairStoneBrick",
                "stairSlate",
                "marblePillar",
                "pearlBlock",
                "buffalkorCrystalBlock",
                "coalBlock",
                "ironBlock",
                "goldBlock",
                "copperBlock",
                "redBronzeBlock",
                "diamondBlock",
                "rubyBlock",
                "opalBlock",
                "mushroomBlock",
                "mossySlab",
                "cobblestoneSlab",
                "mossyCobblestoneSlab",
                "voidStoneSlab",
                "voidStoneBrickSlab",
                "voidStoneCobbleSlab",
                "voidStonePolishedSlab",
                "voidStoneCarvedSlab",
                "voidStoneTiledSlab",
                "checkerTiledSlab",
                "cautionSlab",
                "stoneBrickMossy",
                "stoneBrickSlab",
                "slateSlab",
                "doorIron",
                "carpet",
                "pond",
                "voidBlock",
                "mossyBlock",
                "cobblestoneBlock",
                "mossyCobblestoneBlock",
                "amethystBlock",
                "voidStoneBrick",
                "voidStoneCobble",
                "voidStonePolished",
                "voidStoneCarved",
                "voidStoneTiled",
                "whiteStair",
                "whiteSlab",
                "pastelRedStair",
                "pastelRedSlab",
                "vineStemLadder",
                "chest",
                "mailbox",
                "trellis",
                "trashCan",
                "chestMedium",
                "foodProcessor2",
                "teleporter",
                "orbSlimeIsland",
                "chestMediumIndustrial",
                "steelMill",
                "chestMediumIndustrialIO",
                "conveyorForward",
                "conveyorRight",
                "conveyorLeft",
                "conveyorRampUp",
                "conveyorRampDown",
                "conveyorRandomizer",
                "conveyorMerger",
                "conveyorSplitterFiltered",
                "smelterIndustrial",
                "steelPress",
                "copperPress",
                "drill",
                "ovenIndustrial",
                "treeCutter",
                "sawmillIndustrial",
                "palletPacker",
                "polishingStationIndustrial",
                "stonecutterIndustrial",
                "washingStationIndustrial",
                "redBronzeRefinery",
                "portalSlime",
                "orbIslandBlack",
                "lanternButterflySilver",
                "lanternButterflyRed",
                "lanternButterflyGreen",
                "pipe",
                "pipeJunction",
                "pumpjack",
                "oilRefinery",
                "petroleumTank",
                "oilTank",
                "fuelBarrelExtractor",
                "fuelBarrelFiller",
                "petroleumPetrifier",
                "cratePackerIndustrial2",
                "treeFruitShaker",
                "saplingAutoPlanter",
                "troughIndustrial2",
                "flowerPicker",
                "npcRemoteSeller",
                "conveyor1Forward",
                "conveyor1Left",
                "conveyor1Right",
                "conveyor1RampUp",
                "conveyor1RampDown",
                "chestLarge",
                "chestLargeIndustrialIO",
                "chestIndustrialTimed",
                "orbSlimeBoss",
                "diamondChestT1",
                "diamondChestT2",
                "petEggStand1",
                "petEggStand2",
                "petEggStand3",
                "petEggStand4",
                "petEggStand5",
                "atmMachine1",
                "medalDisplay1",
                "gregsHammer",
                "forgeHammer",
                "crystallinePlow",
                "workbench4",
                "workbench3",
                "workbench2",
                "workbench1",
                "cuttingTable",
                "cookingTable",
                "carpentryStation",
                "animalBench",
                "anvil",
                "coloringStation",
                "brewingStand",
                "electricalBench",
                "mapleWorkbench",
                "sewingStation",
                "snowballMachine",
                "instrumentBench",
                "jukebox",
                "obbyKit",
                "floralBench",
                "lightingStation",
                "bannerBench",
                "fireworkBarrel"
            },
            ["displayName"] = "Workbench Tier 4"
        },
        ["workbench2"] = {
            ["categories"] = {
                {["id"] = "recommended", ["toolCategories"] = {}, ["displayName"] = "Recommended"},
                {["id"] = "all", ["toolCategories"] = {}, ["displayName"] = "All"},
                {["id"] = "tool", ["toolCategories"] = {2}, ["displayName"] = "Tools"},
                {["id"] = "block", ["toolCategories"] = {0}, ["displayName"] = "Blocks"},
                {["id"] = "workbench", ["toolCategories"] = {6}, ["displayName"] = "Workbenches"},
                {["id"] = "utility", ["toolCategories"] = {4}, ["displayName"] = "Utility"},
                {["id"] = "factory", ["toolCategories"] = {5}, ["displayName"] = "Factory"},
                {["id"] = "fun", ["toolCategories"] = {7}, ["displayName"] = "Fun"}
            },
            ["nextLevel"] = "workbench3",
            ["canCraft"] = {
                "woodPickaxe",
                "woodAxe",
                "swordWood",
                "malletWood",
                "hammerGranite",
                "stonePickaxe",
                "stoneAxe",
                "stoneSword",
                "hoe",
                "wateringCan",
                "sickleStone",
                "fishingRod",
                "net",
                "bucketEmpty",
                "shovelStone",
                "clippers",
                "fishingRodIron",
                "bait",
                "baitT2",
                "waterJug",
                "quill",
                "pesticideSpray",
                "campfire",
                "smallFurnace",
                "sawmill",
                "polishingStation",
                "stonecutter",
                "composter",
                "vendingMachine",
                "honeyPress",
                "cheesemaker",
                "churner",
                "sprinklerBasic",
                "waterCatcher",
                "waterStorageBarrel",
                "blastFurnace",
                "stairOak",
                "oakSlab",
                "woodFence",
                "fenceVineStem",
                "ladder",
                "doorPine",
                "doorPine2",
                "doorGlass",
                "signOak",
                "honeyBlock",
                "boneBlock",
                "torch",
                "lantern1",
                "bannerElephant",
                "slimeBlockGreen",
                "leavesBlock",
                "trapDoorOak",
                "coralBlockBlue",
                "iceCompact",
                "snowCompact",
                "candyCane",
                "woodPlate",
                "targetBlockWood",
                "targetBlockIron",
                "prismarineBlock",
                "bambooBlock",
                "bambooDriedBlock",
                "mossyStair",
                "cobblestoneStair",
                "mossyCobblestoneStair",
                "voidStoneStair",
                "voidStoneBrickStair",
                "voidStoneCobbleStair",
                "voidStonePolishedStair",
                "voidStoneCarvedStair",
                "voidStoneTiledStair",
                "checkerTiledStair",
                "cautionStair",
                "stairStoneBrick",
                "stairSlate",
                "marblePillar",
                "pearlBlock",
                "buffalkorCrystalBlock",
                "coalBlock",
                "ironBlock",
                "goldBlock",
                "copperBlock",
                "redBronzeBlock",
                "diamondBlock",
                "rubyBlock",
                "opalBlock",
                "mushroomBlock",
                "mossySlab",
                "cobblestoneSlab",
                "mossyCobblestoneSlab",
                "voidStoneSlab",
                "voidStoneBrickSlab",
                "voidStoneCobbleSlab",
                "voidStonePolishedSlab",
                "voidStoneCarvedSlab",
                "voidStoneTiledSlab",
                "checkerTiledSlab",
                "cautionSlab",
                "stoneBrickMossy",
                "stoneBrickSlab",
                "slateSlab",
                "doorIron",
                "carpet",
                "pond",
                "voidBlock",
                "mossyBlock",
                "cobblestoneBlock",
                "mossyCobblestoneBlock",
                "amethystBlock",
                "voidStoneBrick",
                "voidStoneCobble",
                "voidStonePolished",
                "voidStoneCarved",
                "voidStoneTiled",
                "whiteStair",
                "whiteSlab",
                "pastelRedStair",
                "pastelRedSlab",
                "vineStemLadder",
                "chest",
                "mailbox",
                "trellis",
                "trashCan",
                "chestMedium",
                "foodProcessor2",
                "teleporter",
                "orbSlimeIsland",
                "workbench3",
                "workbench2",
                "workbench1",
                "cuttingTable",
                "cookingTable",
                "carpentryStation",
                "animalBench",
                "anvil",
                "coloringStation",
                "brewingStand",
                "electricalBench",
                "mapleWorkbench",
                "sewingStation",
                "snowballMachine",
                "instrumentBench",
                "jukebox",
                "obbyKit",
                "floralBench",
                "lightingStation",
                "bannerBench",
                "fireworkBarrel"
            },
            ["id"] = "workbench2",
            ["displayName"] = "Workbench Tier 2"
        }
    }
}
