data = {
    ["PresentRarities"] = {["Normal"] = 840, ["Legendary"] = 4, ["Common"] = 100, ["Uncommon"] = 50, ["Rare"] = 10},
    ["InitialStarPoints"] = 100,
    ["IsNormalServer"] = true,
    ["IsClient"] = true,
    ["MainPlaceId"] = 192800,
    ["PizzaPlacePartyBranchId"] = 4146150955,
    ["IsStudio"] = false,
    ["IsServer"] = false,
    ["Plateform"] = "Mobile",
    ["JobXPAmount"] = {["Boxer"] = 2, ["Cashier"] = 2, ["Cook"] = 2, ["Delivery"] = 2, ["Supplier"] = 1},
    ["Paychecks"] = {
        ["Bonus Check from Manager"] = 150,
        ["Daily Check"] = 200,
        ["Watching Ad Reward"] = 150,
        ["Starter Check"] = 500
    },
    ["IsTrickOrTreatServer"] = false,
    ["FavoriteFoodImage"] = {
        ["Pepperoni"] = "rbxassetid://14110420836",
        ["Cheese"] = "rbxassetid://14110624467",
        ["Sausage"] = "rbxassetid://14111536550"
    },
    ["VideoMakerPluginVersion"] = 2,
    ["CapsuleProductIds"] = {
        ["Rare"] = 372315710,
        ["Legendary"] = 372315960,
        ["Uncommon"] = 372315513,
        ["Common"] = 372315247
    },
    ["StoryLobbyTestId"] = 5777410634,
    ["MazeOfTerrorGearTrophyId"] = 5864256069,
    ["IsTestPlace"] = false,
    ["TimeInbetweenPresentOpening"] = 300,
    ["ChristmasPresentProduct"] = 437806471,
    ["PizzaPlaceId"] = 192800,
    ["BannedPlacePortalIds"] = {true, true, true, true, true, true, true, true, true, true, true},
    ["DefaultMaterials"] = {
        ["Modern"] = {
            ["Roof"] = "SmoothPlastic",
            ["Frame"] = "Wood",
            ["Wall"] = "SmoothPlastic",
            ["Window"] = "SmoothPlastic",
            ["DoorTouch"] = "Wood",
            ["Door"] = "Wood"
        },
        ["Brick"] = {
            ["Outline"] = "SmoothPlastic",
            ["Stairs2"] = "Wood",
            ["CeilingThirdFloor"] = "Concrete",
            ["Window"] = "SmoothPlastic",
            ["HandRail"] = "SmoothPlastic",
            ["CeilingThirdFloor3"] = "Concrete",
            ["CeilingSecondFloor2"] = "Concrete",
            ["Pillar"] = "SmoothPlastic",
            ["OutdoorTrim"] = "SmoothPlastic",
            ["CeilingBasement"] = "Concrete",
            ["Stairs4"] = "Wood",
            ["Door"] = "Wood",
            ["Stairs"] = "Wood",
            ["HandRail2"] = "SmoothPlastic",
            ["Shutter"] = "SmoothPlastic",
            ["CeilingThirdFloor2"] = "Concrete",
            ["DoorTouch"] = "Wood",
            ["CeilingSecondFloor"] = "Concrete",
            ["Stairs3"] = "Wood",
            ["Ceiling"] = "Concrete",
            ["TrimThirdFloor2"] = "SmoothPlastic",
            ["Roof"] = "Brick",
            ["TrimThirdFloor"] = "SmoothPlastic",
            ["TrimSecondFloor2"] = "SmoothPlastic",
            ["Wall"] = "Brick",
            ["Frame"] = "Wood",
            ["TrimSecondFloor"] = "SmoothPlastic",
            ["Trim"] = "SmoothPlastic"
        },
        ["Brick2"] = {
            ["Outline"] = "SmoothPlastic",
            ["Stairs2"] = "Wood",
            ["CeilingThirdFloor"] = "Concrete",
            ["Window"] = "SmoothPlastic",
            ["HandRail"] = "SmoothPlastic",
            ["CeilingThirdFloor3"] = "Concrete",
            ["CeilingSecondFloor2"] = "Concrete",
            ["Pillar"] = "SmoothPlastic",
            ["OutdoorTrim"] = "SmoothPlastic",
            ["CeilingBasement"] = "Concrete",
            ["Stairs4"] = "Wood",
            ["Door"] = "Wood",
            ["Stairs"] = "Wood",
            ["HandRail2"] = "SmoothPlastic",
            ["Shutter"] = "SmoothPlastic",
            ["CeilingThirdFloor2"] = "Concrete",
            ["DoorTouch"] = "Wood",
            ["CeilingSecondFloor"] = "Concrete",
            ["Stairs3"] = "Wood",
            ["Ceiling"] = "Concrete",
            ["TrimThirdFloor2"] = "SmoothPlastic",
            ["Roof"] = "Brick",
            ["TrimThirdFloor"] = "SmoothPlastic",
            ["TrimSecondFloor2"] = "SmoothPlastic",
            ["Wall"] = "Brick",
            ["Frame"] = "Wood",
            ["TrimSecondFloor"] = "SmoothPlastic",
            ["Trim"] = "SmoothPlastic"
        }
    },
    ["PizzaPlacePartyId"] = 191029074,
    ["AssetTypeToSlotSize"] = {
        ["HatAccessory"] = 3,
        ["Head"] = 0,
        ["Face"] = 0,
        ["WaistAccessory"] = 1,
        ["NeckAccessory"] = 1,
        ["ShouldersAccessory"] = 1,
        ["Shirt"] = 0,
        ["FaceAccessory"] = 1,
        ["Pants"] = 0,
        ["BackAccessory"] = 1,
        ["FrontAccessory"] = 1,
        ["HairAccessory"] = 2
    },
    ["AvatarCategoryToAssetType"] = {
        ["Waist"] = "WaistAccessory",
        ["Neck"] = "NeckAccessory",
        ["Hats"] = "HatAccessory",
        ["Back"] = "BackAccessory",
        ["Faces"] = "Face",
        ["Heads"] = "Head",
        ["Front"] = "FrontAccessory",
        ["Shirts"] = "Shirt",
        ["Pants"] = "Pants",
        ["Face"] = "FaceAccessory",
        ["Shoulder"] = "ShouldersAccessory",
        ["Hair"] = "HairAccessory"
    },
    ["Year"] = 2023,
    ["MazeOfTerrorTrophyId"] = 5864232111,
    ["BranchGameId"] = 4819175680,
    ["EmoteToEmoji"] = {
        ["Sleep"] = "😴",
        ["Bye"] = "👋",
        ["Whistle"] = "🎵",
        ["Glee"] = "😄",
        ["Evil"] = "😈",
        ["Think"] = "🤔",
        ["Shocked"] = "😲",
        ["Laugh"] = "🤣",
        ["Scared"] = "😱",
        ["Sad"] = "😭",
        ["Die"] = "😵",
        ["Disgust"] = "🤢",
        ["Hi"] = "👋",
        ["Clap"] = "👏",
        ["Confused"] = "😕",
        ["Amazed"] = "😮",
        ["Angry"] = "😡"
    },
    ["PizzaPlaceVoiceChatTestId"] = 8080188707,
    ["Translate"] = "function: 0x0000000059634a1f",
    ["AddressImages"] = {
        ["X2"] = 8090471424,
        ["X3"] = 8090471360,
        ["Y1"] = 8090471297,
        ["X1"] = 8090471537,
        ["B5"] = 168772676,
        ["B4"] = 168772663,
        ["B6"] = 168772694,
        ["A3"] = 168772626,
        ["A2"] = 168772610,
        ["A1"] = 168771465,
        ["B3"] = 168772648,
        ["Z3"] = 8090470829,
        ["Z2"] = 8090470978,
        ["Z1"] = 8090471074,
        ["Y3"] = 8090471133,
        ["Y2"] = 8090471220,
        ["C3"] = 168772718,
        ["C2"] = 168772707,
        ["C1"] = 168772702,
        ["B2"] = 168772640,
        ["B1"] = 168772634
    },
    ["CustomerStates"] = {
        ["WaitingForCashier"] = "WaitingForCashier",
        ["WalkingToTable"] = "WalkingToTable",
        ["WalkingToEntrance"] = "WalkingToEntrance",
        ["Leaving"] = "Leaving",
        ["WalkingToCashier"] = "WalkingToCashier",
        ["SittingAtTable"] = "SittingAtTable"
    },
    ["DefaultTextColor"] = Color3.fromRGB(166, 132, 109),
    ["PizzaPlaceBranchId"] = 13902184050,
    ["TestGameId"] = 66680189,
    ["Moneyz"] = {
        ["CoinsLarge"] = {
            ["Sale"] = 10,
            ["AssetId"] = "CoinsLarge",
            ["Name"] = "3600",
            ["ProductId"] = 45123967,
            ["Index"] = 1,
            ["Category"] = "Moneyz",
            ["ImageId"] = 1684427805,
            ["Amount"] = 3600
        },
        ["CoinsChest"] = {
            ["Sale"] = 10,
            ["AssetId"] = "CoinsChest",
            ["Name"] = "45000",
            ["ProductId"] = 45124061,
            ["Index"] = 3,
            ["Category"] = "Moneyz",
            ["ImageId"] = 1684428476,
            ["Amount"] = 45000
        },
        ["CoinsXL"] = {
            ["Sale"] = 10,
            ["AssetId"] = "CoinsXL",
            ["Name"] = "19800",
            ["ProductId"] = 45124003,
            ["Index"] = 2,
            ["Category"] = "Moneyz",
            ["ImageId"] = 1684440624,
            ["Amount"] = 19800
        },
        ["MoneyBag"] = {
            ["Index"] = 5,
            ["GearAssetId"] = 495315981,
            ["ImageId"] = 495323030,
            ["Sale"] = 10,
            ["AssetId"] = "MoneyBag",
            ["Name"] = "3600",
            ["Amount"] = 3600,
            ["Category"] = "Moneyz",
            ["ProductId"] = 45123732
        },
        ["CoinsDoubleChest"] = {
            ["Sale"] = 10,
            ["AssetId"] = "CoinsDoubleChest",
            ["Name"] = "180000",
            ["ProductId"] = 23491618,
            ["Index"] = 4,
            ["Category"] = "Moneyz",
            ["ImageId"] = 1684440910,
            ["Amount"] = 180000
        }
    },
    ["TrickOrTreatTestId"] = 4201882723,
    ["BasePetPool"] = {"Dog", "Cat", "Bunny", "Mouse", "Hamster"},
    ["PartyServerId"] = 191029074,
    ["EyeColorRarities"] = {["Legendary"] = 10, ["Common"] = 500, ["Mythic"] = 1, ["Uncommon"] = 400, ["Rare"] = 100},
    ["TeamNameToBrickColor"] = {
        ["Supplier"] = 1,
        ["Pizza Boxer"] = 106,
        ["Cashier"] = 21,
        ["Cook"] = 24,
        ["Manager"] = 37,
        ["Delivery"] = 23,
        ["On Break"] = 194
    },
    ["StoryLobbyId"] = 5777826399,
    ["TrickOrTreatServerId"] = 4203320911,
    ["AssetTypeIdToAssetType"] = {
        "Pants",
        "Shirt",
        "ShouldersAccessory",
        "Face",
        "NeckAccessory",
        "FaceAccessory",
        "Head",
        "WaistAccessory",
        "HatAccessory",
        "BackAccessory",
        "HairAccessory",
        "FrontAccessory"
    },
    ["NorthPoleId"] = 4537627984,
    ["BackupVersion"] = 4,
    ["TesterOnly"] = true,
    ["OrderBoardImages"] = {
        ["SausagePizza"] = "rbxassetid://3540530535",
        ["MountainDew"] = "rbxassetid://2512571151",
        ["PepperoniPizza"] = "rbxassetid://3540529917",
        ["CheesePizza"] = "rbxassetid://3540529228"
    },
    ["PetProperties"] = {
        ["Hamster"] = {["Name"] = "Hamster", ["TeenColor"] = Color3.fromRGB(0, 0, 0)},
        ["Dog"] = {["Name"] = "Dog", ["TeenColor"] = Color3.fromRGB(0, 0, 0)},
        ["Cat"] = {["Name"] = "Cat", ["TeenColor"] = Color3.fromRGB(0, 0, 0)},
        ["Bunny"] = {["Name"] = "Bunny", ["TeenColor"] = Color3.fromRGB(0, 0, 0)},
        ["Mouse"] = {["Name"] = "Mouse", ["TeenColor"] = Color3.fromRGB(0, 0, 0)},
        ["???"] = {["TeenColor"] = Color3.fromRGB(0, 0, 0)}
    },
    ["DefaultItemCount"] = {["Pepperoni"] = 0, ["Medicine"] = 0, ["Cheese"] = 0, ["Sausage"] = 0},
    ["IsPartyServer"] = false,
    ["LocationName"] = {
        "North Pole",
        "Voice Chat",
        "Party Island",
        "",
        "Trick-or-Treat",
        "Burger Place",
        "Burger Place",
        "Party Island",
        "",
        "Voice Chat",
        "Trick-or-Treat",
        "North Pole"
    },
    ["BrickColorToTeamName"] = {"Supplier", "Pizza Boxer", "Delivery", "Cook", "Cashier", "Manager", "On Break"},
    ["StoryId"] = 5777826766,
    ["BuffIconColors"] = {Color3.fromRGB(1, 132, 255), Color3.fromRGB(36, 171, 58), Color3.fromRGB(104, 38, 203)},
    ["GetNextUpgradeInfo"] = "function: 0x00000000ecbbc2cf",
    ["ContributorsIcons"] = {
        "rbxassetid://2098468482",
        "rbxasset://textures/ui/icon_placeowner.png",
        "rbxassetid://2098469196",
        "rbxassetid://2098468482",
        "rbxassetid://2098468836"
    },
    ["MaxNumPets"] = 25,
    ["MainGameId"] = 47545,
    ["IsPizzaPlace"] = true,
    ["TypeToCategoryInventoryList"] = {
        ["WallsFloors"] = {"Walls", "Floors"},
        ["Furniture"] = {
            "All",
            "Beds",
            "Lights",
            "Seats",
            "Tables",
            "Kitchen/Bath",
            "Decoration",
            "Entertainment",
            "Customization",
            "Holiday"
        },
        ["Vehicles"] = {},
        ["Clothing"] = {"Hats", "Shirts", "Pants", "Packages"},
        ["Gear"] = {},
        ["Moneyz"] = {},
        ["GamePasses"] = {},
        ["Stickers"] = {}
    },
    ["MaxNumPetSlots"] = 3,
    ["ShortFormNumber"] = "function: 0x0000000037ccb457",
    ["CapsuleTypeToColor"] = {
        ["Legendary"] = Color3.fromRGB(255, 0, 191),
        ["Common"] = Color3.fromRGB(0, 0, 255),
        ["Mythic"] = Color3.fromRGB(0, 255, 255),
        ["Limited"] = Color3.fromRGB(73, 179, 49),
        ["Uncommon"] = Color3.fromRGB(0, 255, 0),
        ["Rare"] = Color3.fromRGB(255, 255, 0)
    },
    ["IngredientImages"] = {
        ["Pepperoni"] = "http://www.roblox.com/asset/?id=167850850",
        ["TomatoSauce"] = "http://www.roblox.com/asset/?id=167850867",
        ["Sausage"] = "http://www.roblox.com/asset/?id=167850856",
        ["Dough"] = "http://www.roblox.com/Thumbs/Asset.ashx?Width=110&Height=110&AssetID=170260912",
        ["MountainDew"] = "rbxassetid://2512571151",
        ["Cheese"] = "http://www.roblox.com/asset/?id=167850840",
        ["Box"] = "http://www.roblox.com/Thumbs/Asset.ashx?Width=110&Height=110&AssetID=170260735"
    },
    ["ModelBaseURL"] = "http://www.roblox.com/Thumbs/Asset.ashx?Width=110&Height=110&AssetID=",
    ["Dragables"] = {
        ["Dew"] = true,
        ["CutObject"] = true,
        ["MountainDew"] = true,
        ["Pizza"] = true,
        ["BoxClosed"] = true,
        ["Dough"] = true,
        ["SupplyBox"] = true
    },
    ["ErrorLogTableName"] = "main_error_log",
    ["RobloxLocaleId"] = "en-us",
    ["DeathMeterStart"] = 300,
    ["FormatNumber"] = "function: 0x00000000fcd39c57",
    ["NeonTimeProductId"] = 1287809900,
    ["IsEnglish"] = "function: 0x00000000e655fa37",
    ["Localization"] = {
        ["Translate"] = "function: 0x0000000059634a1f",
        ["FormatNumber"] = "function: 0x00000000fcd39c57",
        ["GetLanguageId"] = "function: 0x00000000f771cd1f",
        ["IsEnglish"] = "function: 0x00000000e655fa37"
    },
    ["CandyTypes"] = {
        {["Name"] = "Lollypop", ["ImageId"] = 2505565107},
        {["Name"] = "CandyCorn", ["ImageId"] = 2505566251},
        {["Name"] = "Roll", ["ImageId"] = 2505568058}
    },
    ["IsVoiceChatServer"] = false,
    ["IsMobile"] = true,
    ["PizzaPlaceChinaId"] = 7783264186,
    ["GamepassDescriptions"] = {
        ["PontoonBoat"] = "Take your friends out to the high seas and visit different islands. Features a music player and seats up to 11 people.",
        ["Radio"] = "Play music from your car",
        ["EmotePack"] = [[Express yourself with this emote expansion pack!\n * Disgust\n * Pass out\n * Shocked\n * Evil Laugh]],
        ["ManagerTeleport"] = "Teleports you to the manager's chair as soon as the manager quits their job.",
        ["VictorianUnlimitedSet"] = "Place an unlimited number of Victorian style pieces in your house.",
        ["FullyUpgradedHouse"] = "Basement + Backyard + Three Story House",
        ["GarageUpgrade"] = "Adds a garage to your house and your own personal car that no one can steal. The colors you paint your car save.",
        ["VIP"] = [[ * 50% more coins per paycheck\n * X2 more coins in daily checks\n * Unlocks new paint materials\n * Able to invite players to teleport to your house to have a party.\n * Able to teleport back to your house at any time.\n * Crown Icon + Yellow chat text\n	]],
        ["Mansion"] = [[ * Tons of space\n * 2 more rooms!\n * You can put stuff in your front yard!\n * Second balcony!\n * Custom ceiling colors, stair colors, and much more]],
        ["DeliveryBike"] = "Deliver pizzas in a timley manner with this speedy bike",
        ["AnimalMorph"] = "Become a dog or rat!",
        ["X3Stickers"] = "Put up to 3 stickers on a wall!",
        ["HangGlider"] = "Get a bird's eye view of all the islands.",
        ["PizzaSlicer"] = "Pizzas that are sliced will earn 10% more coins when delivered.",
        ["Estate"] = [[ * Free Jeep vehicle included\n * Nearly 2X the floor space!\n * New attic!\n * Giant garage! (Garage gamepass required)\n * Able to place furniture in the garage! (Garage gamepass required)\n * Able to place furniture on the side of your house\n	]]
    },
    ["CandyImages"] = {["CandyCorn"] = 2505566251, ["Roll"] = 2505568058, ["Lollypop"] = 2505565107},
    ["ChristmasRewards"] = {
        500,
        736209484,
        100,
        300,
        946453536,
        100,
        300,
        945675566,
        100,
        300,
        500,
        394567456,
        100,
        300,
        500,
        935464576,
        100,
        300,
        500,
        678456323,
        100,
        300,
        500,
        800,
        4098350989
    },
    ["TrickOrTreatId"] = 4203320911,
    ["GamePasses"] = {
        ["PontoonBoat"] = {
            ["Index"] = 5,
            ["ImageId"] = 2308549290,
            ["Sale"] = 0,
            ["AssetId"] = "PontoonBoat",
            ["Name"] = "Pontoon Boat",
            ["Category"] = "GamePasses",
            ["Description"] = "PontoonBoatDescription",
            ["NameId"] = "PontoonBoat",
            ["ProductId"] = 850355
        },
        ["Radio"] = {
            ["Index"] = 7,
            ["ImageId"] = 2481091745,
            ["Sale"] = 50,
            ["AssetId"] = "Radio",
            ["Name"] = "Radio",
            ["Category"] = "GamePasses",
            ["Description"] = "RadioDescription",
            ["NameId"] = "Radio",
            ["ProductId"] = 5260189
        },
        ["EmotePack"] = {
            ["NameId"] = "EmotePack",
            ["ImageId"] = 2647783368,
            ["Sale"] = 25,
            ["AssetId"] = "EmotePack",
            ["Name"] = "Emoji Pack",
            ["ProductId"] = 4347329,
            ["Description"] = "EmotePackDescription",
            ["IsEmotePack"] = true,
            ["Index"] = 14,
            ["Category"] = "GamePasses"
        },
        ["ManagerTeleport"] = {
            ["Index"] = 12,
            ["ImageId"] = 2308549313,
            ["Sale"] = 0,
            ["AssetId"] = "ManagerTeleport",
            ["Name"] = "Manager Teleport",
            ["Category"] = "GamePasses",
            ["Description"] = "ManagerTeleportDescription",
            ["NameId"] = "ManagerTeleport",
            ["ProductId"] = 86893
        },
        ["VictorianUnlimitedSet"] = {
            ["Index"] = 6,
            ["ImageId"] = 4509912207,
            ["Sale"] = 50,
            ["AssetId"] = "VictorianUnlimitedSet",
            ["Name"] = "Victorian Unlimited Set",
            ["Category"] = "GamePasses",
            ["Description"] = "VictorianUnlimitedSetDescription",
            ["NameId"] = "VictorianUnlimitedSet",
            ["ProductId"] = 7744290
        },
        ["FullyUpgradedHouse"] = {
            ["Index"] = 4,
            ["ImageId"] = 620781798,
            ["Sale"] = 0,
            ["AssetId"] = "FullyUpgradedHouse",
            ["Name"] = "Basement",
            ["Category"] = "GamePasses",
            ["Description"] = "FullyUpgradedHouseDescription",
            ["NameId"] = "FullyUpgradedHouse",
            ["ProductId"] = 649461
        },
        ["GarageUpgrade"] = {
            ["Index"] = 10,
            ["ImageId"] = 2308549367,
            ["Sale"] = 0,
            ["AssetId"] = "GarageUpgrade",
            ["Name"] = "Garage Upgrade",
            ["Category"] = "GamePasses",
            ["Description"] = "GarageDescription",
            ["NameId"] = "GarageUpgrade",
            ["ProductId"] = 953263
        },
        ["Mansion"] = {
            ["Index"] = 2,
            ["ImageId"] = 1836057218,
            ["Sale"] = 50,
            ["AssetId"] = "Mansion",
            ["Name"] = "Mansion",
            ["Category"] = "GamePasses",
            ["Description"] = "MansionDescription",
            ["NameId"] = "Mansion",
            ["ProductId"] = 4428831
        },
        ["VIP"] = {
            ["Index"] = 3,
            ["ImageId"] = 2308548834,
            ["Sale"] = 10,
            ["AssetId"] = "VIP",
            ["Name"] = "VIP",
            ["Category"] = "GamePasses",
            ["Description"] = "VIPDescription",
            ["NameId"] = "VIP",
            ["ProductId"] = 58000
        },
        ["DeliveryBike"] = {
            ["NameId"] = "DeliveryBike",
            ["GearAssetId"] = 497502431,
            ["ImageId"] = 2308549298,
            ["Sale"] = 33,
            ["AssetId"] = "DeliveryBike",
            ["Name"] = "Delivery Bike",
            ["ProductId"] = 809502,
            ["Description"] = "DeliveryBikeDescription",
            ["Index"] = 8,
            ["Category"] = "GamePasses"
        },
        ["AnimalMorph"] = {
            ["NameId"] = "AnimalMorph",
            ["ImageId"] = 10047173379,
            ["Sale"] = 50,
            ["AssetId"] = "AnimalMorph",
            ["Name"] = "Animal Morph",
            ["ProductId"] = 52086936,
            ["Description"] = "AnimalMorphDescription",
            ["LegacyGamePassId"] = 7698167,
            ["Index"] = 9,
            ["Category"] = "GamePasses"
        },
        ["X3Stickers"] = {
            ["Index"] = 15,
            ["ImageId"] = 2308549325,
            ["Sale"] = 25,
            ["AssetId"] = "X3Stickers",
            ["Name"] = "X3 Stickers",
            ["Category"] = "GamePasses",
            ["Description"] = "StickersDescription",
            ["NameId"] = "X3Stickers",
            ["ProductId"] = 5086663
        },
        ["HangGlider"] = {
            ["NameId"] = "HangGlider",
            ["GearAssetId"] = 497501382,
            ["ImageId"] = 2308549085,
            ["Sale"] = 0,
            ["AssetId"] = "HangGlider",
            ["Name"] = "Hang Glider",
            ["ProductId"] = 87344,
            ["Description"] = "HangGliderDescription",
            ["Index"] = 11,
            ["Category"] = "GamePasses"
        },
        ["PizzaSlicer"] = {
            ["Index"] = 13,
            ["ImageId"] = 15834881580,
            ["Sale"] = 0,
            ["AssetId"] = "PizzaSlicer",
            ["Name"] = "Pizza Slicer",
            ["Category"] = "GamePasses",
            ["Description"] = "PizzaSlicerDescription",
            ["NameId"] = "PizzaSlicer",
            ["ProductId"] = 681022199
        },
        ["Estate"] = {
            ["Index"] = 1,
            ["ImageId"] = 4509912552,
            ["Sale"] = 50,
            ["AssetId"] = "Estate",
            ["Name"] = "Estate",
            ["Category"] = "GamePasses",
            ["Description"] = "EstateDescription",
            ["NameId"] = "Estate",
            ["ProductId"] = 7698167
        }
    },
    ["GamepadEnabled"] = false,
    ["PizzaPlaceChinaTestId"] = 7782875357,
    ["CapsuleTypeToImage"] = {
        ["Rare"] = "rbxassetid://2258851782",
        ["Legendary"] = "rbxassetid://2258851487",
        ["Uncommon"] = "rbxassetid://2258852098",
        ["Common"] = "rbxassetid://2258850699"
    },
    ["TypeToCatalogCategoryList"] = {
        ["Furniture"] = {
            "All",
            "Beds",
            "Lights",
            "Seats",
            "Tables",
            "Kitchen/Bath",
            "Decoration",
            "Entertainment",
            "Customization",
            "Holiday",
            "VIP only"
        },
        ["Vehicles"] = {},
        ["Clothing"] = {"Hats", "Shirts", "Pants", "Packages"},
        ["Gear"] = {},
        ["Moneyz"] = {},
        ["GamePasses"] = {},
        ["WallsFloors"] = {"Walls", "Floors"}
    },
    ["ChristmasRewardIdToModelId"] = {
        15475644018,
        15475630405,
        15475674024,
        15475624094,
        15475649611,
        15475633930,
        15475619675
    },
    ["DarkThemeDialog"] = false,
    ["CategoryToType"] = {
        ["PetHats"] = "PetHats",
        ["Hats"] = "Clothing",
        ["Packages"] = "Clothing",
        ["Trucks"] = "Vehicles",
        ["Floors"] = "WallsFloors",
        ["Boats"] = "Vehicles",
        ["Holiday"] = "Furniture",
        ["Stickers"] = "Stickers",
        ["Lights"] = "Furniture",
        ["Entertainment"] = "Furniture",
        ["Tables"] = "Furniture",
        ["Seats"] = "Furniture",
        ["Customization"] = "Furniture",
        ["Walls"] = "WallsFloors",
        ["Gear"] = "Gear",
        ["Decoration"] = "Furniture",
        ["Cars"] = "Vehicles",
        ["Shirts"] = "Clothing",
        ["Beds"] = "Furniture",
        ["All"] = "Furniture",
        ["Pants"] = "Clothing",
        ["Kitchen/Bath"] = "Furniture"
    },
    ["AvatarCategories"] = {
        "Hats",
        "Shirts",
        "Pants",
        "Hair",
        "Face",
        "Faces",
        "Neck",
        "Back",
        "Shoulder",
        "Waist",
        "Front",
        "Heads"
    },
    ["PetNameLength"] = 13,
    ["CoolDownTimes"] = {["BackToWork"] = 4, ["GiveBonus"] = 10, ["NominateForBan"] = 11, ["EmployeeOfTheDay"] = 15},
    ["LastChristmasUnwrapTick"] = 1577295000,
    ["DoCutsceneForTraits"] = {
        ["Hatch"] = true,
        ["SkinColor"] = true,
        ["EyeColor"] = true,
        ["Teen"] = true,
        ["Adult"] = true
    },
    ["PizzaPlaceTestId"] = 142872308,
    ["EyeColors"] = {
        ["glowing_gold"] = {["Name"] = "Glowing Gold", ["Rarity"] = "Rare"},
        ["sparkle_yellow"] = {["Name"] = "Sparkle Yellow", ["Rarity"] = "Rare"},
        ["lifeforce_blue"] = {["Name"] = "Lifeforce Blue", ["Rarity"] = "Legendary"},
        ["void_violet"] = {["Rarity"] = "Undead2", ["Name"] = "Void Violet", ["NextEyes"] = "hypervoid_violet"},
        ["brown"] = {["Name"] = "Brown", ["Rarity"] = "Common"},
        ["red"] = {["Name"] = "Red", ["Rarity"] = "Uncommon"},
        ["void_orange"] = {["Rarity"] = "Undead2", ["Name"] = "Void Orange", ["NextEyes"] = "hypervoid_orange"},
        ["blue"] = {["Name"] = "Blue", ["Rarity"] = "Common"},
        ["cinder_orange"] = {["Rarity"] = "Undead1", ["Name"] = "Cinder Orange", ["NextEyes"] = "void_orange"},
        ["autumn_orange"] = {["Name"] = "Autumn Orange", ["Rarity"] = "Rare"},
        ["hypervoid_orange"] = {["Name"] = "Hypervoid Orange", ["Rarity"] = "Undead3"},
        ["light_blue"] = {["Name"] = "Light Blue", ["Rarity"] = "Uncommon"},
        ["nova_blue"] = {["Name"] = "Nova Blue", ["Rarity"] = "Legendary"},
        ["cinder_violet"] = {["Rarity"] = "Undead1", ["Name"] = "Cinder Violet", ["NextEyes"] = "void_violet"},
        ["green"] = {["Name"] = "Green", ["Rarity"] = "Common"},
        ["aura_pink"] = {["Name"] = "Aura Pink", ["Rarity"] = "Mythic"},
        ["light_green"] = {["Name"] = "Light Green", ["Rarity"] = "Uncommon"},
        ["ander"] = {["Name"] = "Ander", ["Rarity"] = "Uncommon"},
        ["hypervoid_violet"] = {["Name"] = "Hypervoid Violet", ["Rarity"] = "Undead3"}
    },
    ["InventorySlotPrices"] = {0, 12000, 40000},
    ["Cutables"] = {["BoxOpen"] = true, ["Dew"] = true, ["MountainDew"] = true, ["Dough"] = true, ["SupplyBox"] = true},
    ["OutsideDisplayProductId1"] = 1710142941,
    ["PresentIdToItemId"] = {4532074010, 4525515040, 4527786585, 4521620501, 4531584703, 4537885522, 4537881197},
    ["Horns"] = {
        ["Car"] = "http://www.roblox.com/asset/?id=272190708",
        ["Truck"] = "http://www.roblox.com/asset/?id=272187203",
        ["Boat"] = "rbxassetid://1195916770"
    },
    ["ShopPrices"] = {
        ["Pepperoni"] = {200, 2600, 8500, 12000, 15000, 30000},
        ["Sausage"] = {200, 2600, 8500, 12000, 15000, 30000},
        ["Egg"] = {2000, 9000, 15000, 30000},
        ["Medicine"] = {50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160},
        ["PetHat"] = {-2},
        ["Cheese"] = {200, 2600, 8500, 12000, 15000, 30000}
    },
    ["OutsideDisplayProductId2"] = 1710143686,
    ["MenuItemImages"] = {
        ["Pepperoni"] = "rbxassetid://3540529917",
        ["MountainDew"] = "rbxassetid://2512571151",
        ["Cheese"] = "rbxassetid://3540529228",
        ["Sausage"] = "rbxassetid://3540530535"
    },
    ["ShopPriceReductionTime"] = 72000,
    ["Sale"] = false,
    ["StarRating"] = {{11, 30}, {31, 80}, {81, 100}, {0, 10}},
    ["OrderNameToIndex"] = {["SausagePizza"] = 3, ["MountainDew"] = 4, ["PepperoniPizza"] = 2, ["CheesePizza"] = 1},
    ["LickableObjects"] = {
        ["BoxOpen"] = true,
        ["Dew"] = true,
        ["MountainDew"] = true,
        ["Pizza"] = true,
        ["BoxClosed"] = true,
        ["Dough"] = true,
        ["SupplyBox"] = true
    },
    ["OrderIndexToName"] = {"CheesePizza", "PepperoniPizza", "SausagePizza", "MountainDew"},
    ["DiscountColors"] = {
        Color3.fromRGB(255, 255, 255),
        Color3.fromRGB(255, 255, 0),
        Color3.fromRGB(0, 0, 255),
        Color3.fromRGB(255, 0, 191),
        Color3.fromRGB(0, 255, 0),
        Color3.fromRGB(255, 255, 255),
        Color3.fromRGB(0, 0, 0)
    },
    ["CapsuleDuplicateAmount"] = {["Rare"] = 100, ["Legendary"] = 200, ["Uncommon"] = 50, ["Common"] = 25},
    ["ValidClothingTypes"] = {"Pants", "Shirt"},
    ["NotificationThreshold"] = 200,
    ["IsOnline"] = true,
    ["ValidAccessoryTypes"] = {true, true, true, true, true, true, true, true},
    ["PreferedLanguageVersion"] = 13,
    ["EngineSounds"] = {["Boat"] = "rbxassetid://280518144", ["Vehicle"] = "rbxassetid://4525667453"},
    ["AvatarCategoryIcons"] = {
        ["Waist"] = 2617537855,
        ["Neck"] = 2617537782,
        ["Hats"] = 2617616611,
        ["Back"] = 2617537790,
        ["Faces"] = 2617537787,
        ["Heads"] = 2617752549,
        ["Front"] = 8010743930,
        ["Shirts"] = 2617537854,
        ["Pants"] = 2617537845,
        ["Face"] = 2617537786,
        ["Shoulder"] = 2617537853,
        ["Hair"] = 2617537791
    },
    ["InventorySubcategoryIcons"] = {
        ["Lights"] = 2619188950,
        ["Entertainment"] = 2619189841,
        ["Tables"] = 2619267206,
        ["Seats"] = 2619188949,
        ["Beds"] = 2619265626,
        ["Walls"] = 2619254177,
        ["Decoration"] = 2619188921,
        ["Floors"] = 2619188925,
        ["Customization"] = 2619265624,
        ["All"] = 2619188923,
        ["Holiday"] = 2619188926,
        ["Kitchen/Bath"] = 2619188922
    },
    ["Lanes"] = {["Right"] = "Right", ["Left"] = "Left", ["DriveThrough"] = "DriveThrough"},
    ["CrossoverEventInfo"] = {
        ["EndTick"] = 0,
        ["StartTick"] = 0,
        ["BadgeId"] = 2124493131,
        ["PlaceId"] = 4580204640,
        ["PrizeAssetId"] = 4537881197,
        ["IsGamepadSupported"] = true
    },
    ["SuperAdmins"] = {["Dued1"] = 3, ["Player"] = 8, ["Player2"] = 10, ["Player1"] = 10},
    ["PresentData"] = {
        ["Normal"] = {
            ["ToolIcon"] = "http://www.roblox.com/Thumbs/Asset.ashx?Width=110&Height=110&AssetID=3942186680",
            ["Rarity"] = "Normal",
            ["Animation"] = {
                ["DropFromSky"] = {
                    ["HasEffects"] = true,
                    ["Priority"] = Enum.AnimationPriority.Action,
                    ["R15"] = 3906767049,
                    ["R6"] = 3906812477
                },
                ["HoldingItem"] = {
                    ["Speed"] = 0.1,
                    ["Priority"] = Enum.AnimationPriority.Movement,
                    ["R15"] = 3875855745,
                    ["R6"] = 4040077647
                },
                ["HoldingPresent"] = {
                    ["Priority"] = Enum.AnimationPriority.Movement,
                    ["R15"] = 3869539929,
                    ["R6"] = 2665338375
                },
                ["OpenPresent"] = {
                    ["R15"] = 3869532477,
                    ["R6"] = 4039854725,
                    ["Speed"] = 0.5,
                    ["Priority"] = Enum.AnimationPriority.Action,
                    ["HasEffects"] = true
                }
            },
            ["Price"] = 350,
            ["Name"] = "Furniture Present",
            ["AssetType"] = "Furniture",
            ["Probability"] = 20
        },
        ["Halloween"] = {
            ["ToolIcon"] = "http://www.roblox.com/Thumbs/Asset.ashx?Width=110&Height=110&AssetID=4101168438",
            ["Rarity"] = "Common",
            ["Animation"] = {
                ["DropFromSky"] = {
                    ["HasEffects"] = true,
                    ["Priority"] = Enum.AnimationPriority.Action,
                    ["R15"] = 3906767049,
                    ["R6"] = 3906812477
                },
                ["HoldingItem"] = {
                    ["Speed"] = 0.1,
                    ["Priority"] = Enum.AnimationPriority.Movement,
                    ["R15"] = 3875855745,
                    ["R6"] = 4040077647
                },
                ["HoldingPresent"] = {
                    ["Priority"] = Enum.AnimationPriority.Movement,
                    ["R15"] = 3869539929,
                    ["R6"] = 2665338375
                },
                ["OpenPresent"] = {
                    ["R15"] = 3869532477,
                    ["R6"] = 4039854725,
                    ["Speed"] = 0.5,
                    ["Priority"] = Enum.AnimationPriority.Action,
                    ["HasEffects"] = true
                }
            },
            ["Price"] = 1100,
            ["Name"] = "Halloween Present",
            ["AssetType"] = "Furniture",
            ["Holiday"] = "Halloween",
            ["Probability"] = 20
        },
        ["Thanksgiving"] = {
            ["ToolIcon"] = "http://www.roblox.com/Thumbs/Asset.ashx?Width=110&Height=110&AssetID=4459209078",
            ["Rarity"] = "Common",
            ["Animation"] = {
                ["DropFromSky"] = {
                    ["HasEffects"] = true,
                    ["Priority"] = Enum.AnimationPriority.Action,
                    ["R15"] = 3906767049,
                    ["R6"] = 3906812477
                },
                ["HoldingItem"] = {
                    ["Speed"] = 0.1,
                    ["Priority"] = Enum.AnimationPriority.Movement,
                    ["R15"] = 3875855745,
                    ["R6"] = 4040077647
                },
                ["HoldingPresent"] = {
                    ["Priority"] = Enum.AnimationPriority.Movement,
                    ["R15"] = 3869539929,
                    ["R6"] = 2665338375
                },
                ["OpenPresent"] = {
                    ["R15"] = 3869532477,
                    ["R6"] = 4039854725,
                    ["Speed"] = 0.5,
                    ["Priority"] = Enum.AnimationPriority.Action,
                    ["HasEffects"] = true
                }
            },
            ["Price"] = 1100,
            ["Name"] = "Thanksgiving Present",
            ["AssetType"] = "Furniture",
            ["Holiday"] = "Thanksgiving",
            ["Probability"] = 20
        },
        ["Gear"] = {
            ["ToolIcon"] = "http://www.roblox.com/Thumbs/Asset.ashx?Width=110&Height=110&AssetID=3942137473",
            ["Rarity"] = "Normal",
            ["Animation"] = {
                ["DropFromSky"] = {
                    ["HasEffects"] = true,
                    ["Priority"] = Enum.AnimationPriority.Action,
                    ["R15"] = 3906767049,
                    ["R6"] = 3906812477
                },
                ["HoldingItem"] = {
                    ["Speed"] = 0.1,
                    ["Priority"] = Enum.AnimationPriority.Movement,
                    ["R15"] = 3875855745,
                    ["R6"] = 4040077647
                },
                ["HoldingPresent"] = {
                    ["Priority"] = Enum.AnimationPriority.Movement,
                    ["R15"] = 3869539929,
                    ["R6"] = 2665338375
                },
                ["OpenPresent"] = {
                    ["R15"] = 3869532477,
                    ["R6"] = 4039854725,
                    ["Speed"] = 0.5,
                    ["Priority"] = Enum.AnimationPriority.Action,
                    ["HasEffects"] = true
                }
            },
            ["Price"] = 200,
            ["Name"] = "Gear Present",
            ["AssetType"] = "Gear",
            ["Probability"] = 5
        },
        ["Fall"] = {
            ["ToolIcon"] = "http://www.roblox.com/Thumbs/Asset.ashx?Width=110&Height=110&AssetID=4043838219",
            ["Rarity"] = "Common",
            ["Animation"] = {
                ["DropFromSky"] = {
                    ["HasEffects"] = true,
                    ["Priority"] = Enum.AnimationPriority.Action,
                    ["R15"] = 3906767049,
                    ["R6"] = 3906812477
                },
                ["HoldingItem"] = {
                    ["Speed"] = 0.1,
                    ["Priority"] = Enum.AnimationPriority.Movement,
                    ["R15"] = 3875855745,
                    ["R6"] = 4040077647
                },
                ["HoldingPresent"] = {
                    ["Priority"] = Enum.AnimationPriority.Movement,
                    ["R15"] = 3869539929,
                    ["R6"] = 2665338375
                },
                ["OpenPresent"] = {
                    ["R15"] = 3869532477,
                    ["R6"] = 4039854725,
                    ["Speed"] = 0.5,
                    ["Priority"] = Enum.AnimationPriority.Action,
                    ["HasEffects"] = true
                }
            },
            ["Price"] = 800,
            ["Season"] = "Fall",
            ["Name"] = "Autumn Present",
            ["AssetType"] = "Furniture",
            ["Probability"] = 10
        },
        ["Movie"] = {
            ["ToolIcon"] = "http://www.roblox.com/Thumbs/Asset.ashx?Width=110&Height=110&AssetID=6213990852",
            ["Rarity"] = "Uncommon",
            ["Animation"] = {
                ["DropFromSky"] = {
                    ["HasEffects"] = true,
                    ["Priority"] = Enum.AnimationPriority.Action,
                    ["R15"] = 3906767049,
                    ["R6"] = 3906812477
                },
                ["HoldingItem"] = {
                    ["Speed"] = 0.1,
                    ["Priority"] = Enum.AnimationPriority.Movement,
                    ["R15"] = 3875855745,
                    ["R6"] = 4040077647
                },
                ["HoldingPresent"] = {
                    ["Priority"] = Enum.AnimationPriority.Movement,
                    ["R15"] = 3869539929,
                    ["R6"] = 2665338375
                },
                ["OpenPresent"] = {
                    ["R15"] = 3869532477,
                    ["R6"] = 4039854725,
                    ["Speed"] = 0.5,
                    ["Priority"] = Enum.AnimationPriority.Action,
                    ["HasEffects"] = true
                }
            },
            ["Price"] = 2800,
            ["Name"] = "Movie Present",
            ["AssetType"] = "Furniture",
            ["Probability"] = 2
        },
        ["Christmas"] = {
            ["ToolIcon"] = "http://www.roblox.com/Thumbs/Asset.ashx?Width=110&Height=110&AssetID=8199364594",
            ["Rarity"] = "Common",
            ["Animation"] = {
                ["DropFromSky"] = {
                    ["HasEffects"] = true,
                    ["Priority"] = Enum.AnimationPriority.Action,
                    ["R15"] = 3906767049,
                    ["R6"] = 3906812477
                },
                ["HoldingItem"] = {
                    ["Speed"] = 0.1,
                    ["Priority"] = Enum.AnimationPriority.Movement,
                    ["R15"] = 3875855745,
                    ["R6"] = 4040077647
                },
                ["HoldingPresent"] = {
                    ["Priority"] = Enum.AnimationPriority.Movement,
                    ["R15"] = 3869539929,
                    ["R6"] = 2665338375
                },
                ["OpenPresent"] = {
                    ["R15"] = 3869532477,
                    ["R6"] = 4039854725,
                    ["Speed"] = 0.5,
                    ["Priority"] = Enum.AnimationPriority.Action,
                    ["HasEffects"] = true
                }
            },
            ["Price"] = 1100,
            ["Name"] = "Christmas Present",
            ["AssetType"] = "Furniture",
            ["Holiday"] = "Christmas",
            ["Probability"] = 2
        }
    },
    ["PetProductId"] = 19024606,
    ["PetNames"] = {
        "Acorn",
        "Alvin",
        "Asia",
        "Audi",
        "Bagel",
        "Balou",
        "Barclay",
        "Barney",
        "Beck",
        "Bellatrix",
        "Bianca",
        "Biloxi",
        "Birdie",
        "Biscuit",
        "Blanca",
        "Bobbafett",
        "Bodie",
        "Bono",
        "Booboo",
        "Bootsie",
        "Bordeaux",
        "Brandy",
        "Bren",
        "Bronco",
        "Bruin",
        "Bubbles",
        "Buffy",
        "Burt",
        "Butler",
        "Button",
        "Calvin",
        "Candy",
        "Carter",
        "Cece",
        "Cessa",
        "Chandler",
        "Chaucer",
        "Chevy",
        "China",
        "Choochoo",
        "Cisco",
        "Claire",
        "Cleopatra",
        "Clooney",
        "Coconut",
        "Connor",
        "Cosmo",
        "Crosby",
        "Cupcake",
        "Daisy",
        "Dallas",
        "Daphne",
        "Delilah",
        "Diva",
        "Doc",
        "Domino",
        "Donna",
        "Donovan",
        "Dulus",
        "Dutch",
        "Ed",
        "Elton",
        "Elwood",
        "Ernie",
        "Faith",
        "Faya",
        "Felix",
        "Fig",
        "Fiona",
        "Foxy",
        "Fritz",
        "Fuse",
        "Giblet",
        "Gibson",
        "Gingi",
        "Goofy",
        "Graysen",
        "Greystoke",
        "Guinness",
        "Hershey",
        "Holly",
        "Honey",
        "Huck",
        "Finn",
        "Hudson",
        "Hutch",
        "Ike",
        "Indira",
        "Iris",
        "Ivory",
        "Jasmine",
        "Jasper",
        "Jazzy",
        "Jeeves",
        "Jenna",
        "Jenne",
        "Joy",
        "Kai",
        "Kalua",
        "Kaly",
        "Kassie",
        "Kaya",
        "Keanna",
        "Keesha",
        "Keiko",
        "Kiefer",
        "Kingston",
        "Koby",
        "Kona",
        "Laguna",
        "Landon",
        "Larissa",
        "Lefty",
        "Leia",
        "Lexi",
        "Lil",
        "bit",
        "Lilypie",
        "Linus",
        "Logan",
        "Lola",
        "Luca",
        "Lucy",
        "Luke",
        "Madonna",
        "Malble",
        "Malibu",
        "Margo",
        "Marshmellow",
        "Marti",
        "Max",
        "Maya",
        "Meadow",
        "Mercedes",
        "Merlot",
        "Merry",
        "Mia",
        "Midnight",
        "Midori",
        "Mika",
        "Milan",
        "Mira",
        "Mischa",
        "Mitzi",
        "Moby",
        "Mochi",
        "Monet",
        "Monkey",
        "Mooshie",
        "Mozart",
        "Mr",
        "Big",
        "Muggles",
        "Mulder",
        "Mulligan",
        "Murphy",
        "Mylo",
        "Nanda",
        "Nate",
        "Nell",
        "Niana",
        "Nico",
        "Noodle",
        "Nugget",
        "Olive",
        "Onyx",
        "Otis",
        "Owen",
        "Ozzie",
        "Paddington",
        "Paisley",
        "Paris",
        "Parker",
        "Paulie",
        "Pazzo",
        "Peanut",
        "Pearl",
        "Pepper",
        "Persia",
        "Pesci",
        "Phoenix",
        "Picasso",
        "Pinot",
        "Pipsie",
        "Pixie",
        "Porche",
        "Quattro",
        "Ramona",
        "Redford",
        "Reece",
        "Rico",
        "Robin",
        "Hood",
        "Rocco",
        "Rocky",
        "Romeo",
        "Roxie",
        "Rufus",
        "Rusty",
        "Scotty",
        "Scout",
        "Shadow",
        "Shaggy",
        "Shane",
        "Shaq",
        "Sheba",
        "Silas",
        "Skip",
        "Skitty",
        "Skyler",
        "Smitty",
        "Snooky",
        "Snoopy",
        "Sookie",
        "Spark",
        "Sprite",
        "Stitch",
        "Strsky",
        "Sugar",
        "Summer",
        "Sunny",
        "Sushi",
        "Sweetpea",
        "Syrah",
        "Tallulah",
        "Tango",
        "Tank",
        "Tanner",
        "Tatertot",
        "Theo",
        "Tibbs",
        "Timber",
        "Tink",
        "Toast",
        "Toffee",
        "Tonka",
        "Vegas",
        "Wednesday",
        "Wilbur",
        "Willow",
        "Winnie",
        "Wolfie",
        "Yoshiko",
        "Zach",
        "Zara",
        "Zeke",
        "Zelda",
        "Zeppelin",
        "ZsaZsa"
    },
    ["PenaltyAmount"] = {
        ["ClosedEmptyBox"] = -5,
        ["SlicedObject"] = -6,
        ["KickedOutOfOrderHole"] = -1,
        ["IncorrectDialogResponse"] = -10,
        ["WrongOrder"] = -10,
        ["HeldDeliveryToolLong"] = -3,
        ["BurnedSoda"] = -5,
        ["BugsOnDough"] = -5,
        ["BurnedObject"] = -5
    },
    ["PetPrice"] = 7000,
    ["BaseURL"] = "http://www.roblox.com/asset/?id=",
    ["HouseInfo"] = {
        ["Modern"] = {
            ["Small"] = {
                ["Id"] = "Small",
                ["Name"] = "Small",
                ["NextUpgrade"] = "Garage",
                ["Price"] = 40000,
                ["MaxFurnitureMemory"] = 32,
                ["ImageId"] = 8912706035,
                ["Index"] = 2
            },
            ["Tiny"] = {
                ["MailboxOffsetZ"] = -8,
                ["Name"] = "Tiny",
                ["NextUpgrade"] = "Small",
                ["Id"] = "Tiny",
                ["MaxFurnitureMemory"] = 16,
                ["ImageId"] = 8912771230,
                ["Index"] = 1
            },
            ["Garage"] = {
                ["Id"] = "Garage",
                ["Name"] = "Garage",
                ["Price"] = 80000,
                ["MaxFurnitureMemory"] = 70,
                ["ImageId"] = 8912709104,
                ["Index"] = 3
            }
        },
        ["Brick"] = {
            ["Small"] = {
                ["Id"] = "Small",
                ["Name"] = "Small",
                ["NextUpgrade"] = "Medium",
                ["Price"] = 1200,
                ["MaxFurnitureMemory"] = 32,
                ["ImageId"] = 8729038004,
                ["Index"] = 3
            },
            ["Shack"] = {
                ["Name"] = "Shack",
                ["NextUpgrade"] = "Tiny",
                ["Id"] = "Shack",
                ["MaxFurnitureMemory"] = 12,
                ["ImageId"] = 8729084725,
                ["Index"] = 1
            },
            ["TwoStory"] = {
                ["Id"] = "TwoStory",
                ["Name"] = "Two Story",
                ["NextUpgrade"] = "ThreeStory",
                ["Price"] = 14900,
                ["MaxFurnitureMemory"] = 150,
                ["ImageId"] = 8728984695,
                ["Index"] = 6
            },
            ["Backyard"] = {
                ["Id"] = "Backyard",
                ["CanAccommodateLargeItems"] = true,
                ["Name"] = "Backyard",
                ["NextUpgrade"] = "Basement",
                ["Price"] = 40000,
                ["MaxFurnitureMemory"] = 290,
                ["ImageId"] = 8728947094,
                ["Index"] = 8
            },
            ["Large"] = {
                ["Id"] = "Large",
                ["Name"] = "Large",
                ["NextUpgrade"] = "TwoStory",
                ["Price"] = 5200,
                ["MaxFurnitureMemory"] = 85,
                ["ImageId"] = 8729051323,
                ["Index"] = 5
            },
            ["Mansion"] = {
                ["Index"] = 10,
                ["Price"] = 200000,
                ["ImageId"] = 1677234302,
                ["Name"] = "Mansion",
                ["Id"] = "Mansion",
                ["MaxFurnitureMemory"] = 1200,
                ["GamepassId"] = "Mansion",
                ["NextUpgrade"] = "Estate",
                ["CanAccommodateLargeItems"] = true
            },
            ["ThreeStory"] = {
                ["Id"] = "ThreeStory",
                ["Name"] = "Three Story",
                ["NextUpgrade"] = "Backyard",
                ["Price"] = 36000,
                ["MaxFurnitureMemory"] = 230,
                ["ImageId"] = 8728926634,
                ["Index"] = 7
            },
            ["Estate"] = {
                ["Id"] = "Estate",
                ["GamepassId"] = "Estate",
                ["Index"] = 11,
                ["CanAccommodateLargeItems"] = true,
                ["MaxFurnitureMemory"] = 1980,
                ["Name"] = "Estate",
                ["ImageId"] = 4509912552,
                ["Price"] = 600000
            },
            ["Tiny"] = {
                ["Id"] = "Tiny",
                ["Name"] = "Tiny",
                ["NextUpgrade"] = "Small",
                ["Price"] = 50,
                ["MaxFurnitureMemory"] = 16,
                ["ImageId"] = 8729100304,
                ["Index"] = 2
            },
            ["Basement"] = {
                ["Index"] = 9,
                ["Price"] = 45000,
                ["ImageId"] = 1684646291,
                ["Name"] = "Basement",
                ["Id"] = "Basement",
                ["MaxFurnitureMemory"] = 390,
                ["GamepassId"] = "FullyUpgradedHouse",
                ["NextUpgrade"] = "Mansion",
                ["CanAccommodateLargeItems"] = true
            },
            ["Medium"] = {
                ["Id"] = "Medium",
                ["Name"] = "Medium",
                ["NextUpgrade"] = "Large",
                ["Price"] = 3700,
                ["MaxFurnitureMemory"] = 70,
                ["ImageId"] = 8729063439,
                ["Index"] = 4
            }
        },
        ["Brick2"] = {
            ["Small"] = {
                ["Id"] = "Small",
                ["Name"] = "Small",
                ["NextUpgrade"] = "Medium",
                ["Price"] = 17000,
                ["MaxFurnitureMemory"] = 32,
                ["ImageId"] = 8729038004,
                ["Index"] = 3
            },
            ["Shack"] = {
                ["Name"] = "Shack",
                ["NextUpgrade"] = "Tiny",
                ["Id"] = "Shack",
                ["MaxFurnitureMemory"] = 12,
                ["ImageId"] = 8729084725,
                ["Index"] = 1
            },
            ["TwoStory"] = {
                ["Id"] = "TwoStory",
                ["Name"] = "Two Story",
                ["NextUpgrade"] = "ThreeStory",
                ["Price"] = 46000,
                ["MaxFurnitureMemory"] = 150,
                ["ImageId"] = 8728984695,
                ["Index"] = 6
            },
            ["Backyard"] = {
                ["Id"] = "Backyard",
                ["CanAccommodateLargeItems"] = true,
                ["Name"] = "Backyard",
                ["NextUpgrade"] = "Basement",
                ["Price"] = 70000,
                ["MaxFurnitureMemory"] = 290,
                ["ImageId"] = 8728947094,
                ["Index"] = 8
            },
            ["Large"] = {
                ["Id"] = "Large",
                ["Name"] = "Large",
                ["NextUpgrade"] = "TwoStory",
                ["Price"] = 35000,
                ["MaxFurnitureMemory"] = 85,
                ["ImageId"] = 8729051323,
                ["Index"] = 5
            },
            ["Mansion"] = {
                ["Id"] = "Mansion",
                ["CanAccommodateLargeItems"] = true,
                ["Name"] = "Mansion",
                ["NextUpgrade"] = "Estate",
                ["Price"] = 300000,
                ["MaxFurnitureMemory"] = 1200,
                ["ImageId"] = 1677234302,
                ["Index"] = 10
            },
            ["ThreeStory"] = {
                ["Id"] = "ThreeStory",
                ["Name"] = "Three Story",
                ["NextUpgrade"] = "Backyard",
                ["Price"] = 65000,
                ["MaxFurnitureMemory"] = 230,
                ["ImageId"] = 8728926634,
                ["Index"] = 7
            },
            ["Estate"] = {
                ["Id"] = "Estate",
                ["CanAccommodateLargeItems"] = true,
                ["Name"] = "Estate",
                ["Price"] = 900000,
                ["MaxFurnitureMemory"] = 1980,
                ["ImageId"] = 4509912552,
                ["Index"] = 11
            },
            ["Tiny"] = {
                ["Id"] = "Tiny",
                ["Name"] = "Tiny",
                ["NextUpgrade"] = "Small",
                ["Price"] = 9000,
                ["MaxFurnitureMemory"] = 16,
                ["ImageId"] = 8729100304,
                ["Index"] = 2
            },
            ["Basement"] = {
                ["Id"] = "Basement",
                ["CanAccommodateLargeItems"] = true,
                ["Name"] = "Basement",
                ["NextUpgrade"] = "Mansion",
                ["Price"] = 75000,
                ["MaxFurnitureMemory"] = 390,
                ["ImageId"] = 1684646291,
                ["Index"] = 9
            },
            ["Medium"] = {
                ["Id"] = "Medium",
                ["Name"] = "Medium",
                ["NextUpgrade"] = "Large",
                ["Price"] = 25000,
                ["MaxFurnitureMemory"] = 70,
                ["ImageId"] = 8729063439,
                ["Index"] = 4
            }
        }
    },
    ["ChristmasUnwrapTickTest"] = true,
    ["AvatarCategoriesChina"] = {"Hats", "Hair", "Face", "Faces", "Neck", "Back", "Shoulder", "Waist"},
    ["TrophyLevels"] = {
        ["Streak"] = {
            {["Goal"] = 14, ["AwardId"] = 783564647},
            {["Goal"] = 60, ["AwardId"] = 739678967},
            {["Goal"] = 182, ["AwardId"] = 957765753},
            {["Goal"] = 365, ["AwardId"] = 490567345}
        },
        ["Inviter"] = {
            {["Goal"] = 1, ["AwardId"] = 694759837},
            {["Goal"] = 3, ["AwardId"] = 719549938},
            {["Goal"] = 5, ["AwardId"] = 810298453}
        }
    },
    ["PaycheckLimit"] = 3000,
    ["DataStoreNames"] = {
        ["MostLikes"] = "MostLikes",
        ["MostOrders"] = "MostOrders",
        ["MostCoinsSpent"] = "MostCoinsSpent"
    },
    ["AccessoryBlacklist"] = {true, true, true, true},
    ["PaintableParts"] = {
        ["Outline"] = true,
        ["Stairs2"] = true,
        ["CeilingThirdFloor"] = true,
        ["Window"] = true,
        ["HandRail"] = true,
        ["CeilingThirdFloor3"] = true,
        ["CeilingSecondFloor2"] = true,
        ["Pillar"] = true,
        ["OutdoorTrim"] = true,
        ["CeilingBasement"] = true,
        ["Stairs4"] = true,
        ["Door"] = true,
        ["Stairs"] = true,
        ["HandRail2"] = true,
        ["Shutter"] = true,
        ["CeilingThirdFloor2"] = true,
        ["DoorTouch"] = true,
        ["CeilingSecondFloor"] = true,
        ["Stairs3"] = true,
        ["Ceiling"] = true,
        ["TrimThirdFloor2"] = true,
        ["Roof"] = true,
        ["TrimThirdFloor"] = true,
        ["TrimSecondFloor2"] = true,
        ["Wall"] = true,
        ["Frame"] = true,
        ["TrimSecondFloor"] = true,
        ["Trim"] = true
    },
    ["Admins"] = {
        ["Dued1"] = 3,
        ["Player2"] = 10,
        ["iStratix"] = 17,
        ["Dert41"] = 4,
        ["MrJesseh"] = 16,
        ["jack123"] = 5,
        ["jelloman"] = 10,
        ["Player"] = 8,
        ["RBXZach"] = 15,
        ["3dCarrot"] = 13,
        ["Dert51"] = 12,
        ["billsayshowdy"] = 11,
        ["Player1"] = 10
    },
    ["ActionXP"] = {
        ["Sleep"] = 20,
        ["CureSickness"] = 40,
        ["Hold"] = 20,
        ["MedicineNotSick"] = 2,
        ["Pet"] = 20,
        ["Feed"] = 30,
        ["Fetch"] = 20
    },
    ["ShopRarities"] = {["Normal"] = 5880, ["Legendary"] = 4, ["Common"] = 100, ["Uncommon"] = 50, ["Rare"] = 10},
    ["IngredientIcons"] = {
        ["Pepperoni"] = "rbxassetid://11751455515",
        ["TomatoSauce"] = "rbxassetid://11751455182",
        ["Sausage"] = "rbxassetid://11751455256",
        ["Dough"] = "rbxassetid://11751455695",
        ["MountainDew"] = "rbxassetid://11751556059",
        ["Cheese"] = "rbxassetid://11751455776",
        ["Box"] = "rbxassetid://11751455369"
    },
    ["IntroSequenceEnabled"] = true,
    ["FreeMode"] = false,
    ["GetHouseInfoFromIndex"] = "function: 0x00000000d726f717",
    ["PetLifeStage"] = {
        ["Hatch"] = {2, 2},
        ["Buff"] = {3, 8},
        ["EyeColor"] = {10, 15},
        ["Buff3"] = {30, 40},
        ["Buff2"] = {20, 25},
        ["PetCommand"] = {3, 4},
        ["StayCommand"] = {14, 20},
        ["FetchCommand"] = {6, 12},
        ["Adult"] = {19, 22},
        ["Teen"] = {11, 13},
        ["Personality"] = {6, 12},
        ["FavoriteFood"] = {3, 6}
    },
    ["DefaultSettingValues"] = {
        ["CarRadio"] = 0.5,
        ["UniformEnabled"] = true,
        ["OldCustomerDialog"] = false,
        ["SoundEffects"] = 0.5,
        ["ManagerTeleportPopup"] = true,
        ["VotekickPopup"] = true,
        ["PartyInvitePopup"] = true,
        ["TiltEnabled"] = false,
        ["Textures"] = true,
        ["VIPCrown"] = true,
        ["WaterEnabled"] = false,
        ["CollisionEnabled"] = false,
        ["Music"] = 0.5,
        ["OldUniform"] = false,
        ["MusicVersion"] = "Newest Music"
    },
    ["IsLocalTestServer"] = false,
    ["StoryTestId"] = 5777421636,
    ["FirstChristmasUnwrapTick"] = 1577293200,
    ["StarPenalty"] = {0.3, 0.8, 1, 0},
    ["DoubleMoneyzDay"] = false,
    ["ChinaServer"] = 7783264186,
    ["GlitchReportsTableName"] = "main_glitch_reports",
    ["UpdateVersion"] = 10,
    ["HouseTypeInfo"] = {
        ["Modern"] = {["YMarkerOffset"] = 1.6, ["FirstUpgrade"] = "Tiny"},
        ["Brick"] = {["FirstUpgrade"] = "Shack"},
        ["Brick2"] = {["FirstUpgrade"] = "Shack"}
    },
    ["Buffs"] = {
        ["QuickCashier"] = {
            {
                ["Value"] = 0.2,
                ["Icon"] = 15106431915,
                ["Name"] = "Quick Cashier I",
                ["Description"] = "Customer's give you their order 20% faster"
            },
            {
                ["Value"] = 0.3,
                ["Icon"] = 15106431915,
                ["Name"] = "Quick Cashier II",
                ["Description"] = "Customer's give you their order 30% faster"
            },
            {
                ["Value"] = 0.7,
                ["Icon"] = 15106431915,
                ["Name"] = "Quick Cashier III",
                ["Description"] = "Customer's give you their order 70% faster"
            }
        },
        ["QuickOven"] = {
            {
                ["Value"] = 0.15,
                ["Icon"] = 15106431821,
                ["Name"] = "Quick Oven I",
                ["Description"] = "Ovens cook 15% faster"
            },
            {
                ["Value"] = 0.5,
                ["Icon"] = 15106431821,
                ["Name"] = "Quick Oven II",
                ["Description"] = "Ovens cook 50% faster"
            },
            {
                ["Value"] = 0.8,
                ["Icon"] = 15106431821,
                ["Name"] = "Quick Oven III",
                ["Description"] = "Ovens cook 80% faster"
            }
        },
        ["FastTruck"] = {
            {
                ["Value"] = 1.1,
                ["Icon"] = 15106740714,
                ["Name"] = "Fast Truck I",
                ["Description"] = "Supply trucks drive 10% faster"
            },
            {
                ["Value"] = 1.3,
                ["Icon"] = 15106740714,
                ["Name"] = "Fast Truck II",
                ["Description"] = "Supply trucks drive 30% faster"
            },
            {
                ["Value"] = 1.7,
                ["Icon"] = 15106740714,
                ["Name"] = "Fast Truck III",
                ["Description"] = "Supply trucks drive 70% faster"
            }
        },
        ["QuickDelivery"] = {
            {
                ["Value"] = 0.1,
                ["Icon"] = 15106431711,
                ["Name"] = "Quick Delivery I",
                ["Description"] = "Delivery cutscene takes 10% less time"
            },
            {
                ["Value"] = 0.3,
                ["Icon"] = 15106431711,
                ["Name"] = "Quick Delivery II",
                ["Description"] = "Delivery cutscene takes 30% less time"
            },
            {
                ["Value"] = 0.6,
                ["Icon"] = 15106431711,
                ["Name"] = "Quick Delivery III",
                ["Description"] = "Delivery cutscene takes 60% less time"
            }
        }
    },
    ["PizzaPlacePartyTestId"] = 191851816,
    ["PizzaPlaceVoiceChatId"] = 8080952959,
    ["PizzaPlaceInsideUniverseTestId"] = 531388577
}
