data = {
    ["BLACKLISTED_KEYCODES"] = {
        Enum.KeyCode.Tab,
        Enum.KeyCode.Escape,
        Enum.KeyCode.CapsLock,
        Enum.KeyCode.LeftShift,
        Enum.KeyCode.Tilde,
        Enum.KeyCode.Slash,
        Enum.KeyCode.BackSlash,
        Enum.KeyCode.W,
        Enum.KeyCode.A,
        Enum.KeyCode.S,
        Enum.KeyCode.D,
        Enum.KeyCode.Space,
        Enum.KeyCode.LeftControl,
        Enum.KeyCode.Backspace,
        Enum.KeyCode.I,
        Enum.KeyCode.O,
        Enum.KeyCode.F12,
        Enum.KeyCode.F11,
        Enum.KeyCode.F10,
        Enum.KeyCode.F9,
        Enum.KeyCode.LeftAlt,
        Enum.KeyCode.KeypadDivide,
        Enum.KeyCode.KeypadMultiply,
        Enum.KeyCode.KeypadPeriod,
        Enum.KeyCode.KeypadOne
    },
    ["IS_DEV_PLACE"] = false,
    ["FIRST_TIME_CHAPTER_GEMS_BONUS"] = 80,
    ["CLAN_DEFAULT_IMAGEID"] = 17176978351,
    ["VALID_ENUM_NAMES"] = {
        ["Tab"] = true,
        ["World40"] = true,
        ["Thumbstick2"] = true,
        ["Right"] = true,
        ["Thumbstick1"] = true,
        ["World45"] = true,
        ["LeftShift"] = true,
        ["DPadDown"] = true,
        ["World21"] = true,
        ["World48"] = true,
        ["Three"] = true,
        ["World16"] = true,
        ["World43"] = true,
        ["DPadUp"] = true,
        ["World95"] = true,
        ["LeftControl"] = true,
        ["Zero"] = true,
        ["World84"] = true,
        ["DPadRight"] = true,
        ["DPadLeft"] = true,
        ["World30"] = true,
        ["World92"] = true,
        ["World72"] = true,
        ["ButtonSelect"] = true,
        ["World53"] = true,
        ["ButtonStart"] = true,
        ["World6"] = true,
        ["ButtonR3"] = true,
        ["Down"] = true,
        ["ButtonL2"] = true,
        ["ButtonR2"] = true,
        ["World54"] = true,
        ["ButtonR1"] = true,
        ["ButtonB"] = true,
        ["GreaterThan"] = true,
        ["PageUp"] = true,
        ["ButtonA"] = true,
        ["World26"] = true,
        ["ButtonL1"] = true,
        ["ButtonX"] = true,
        ["Undo"] = true,
        ["LeftBracket"] = true,
        ["KeypadPlus"] = true,
        ["World68"] = true,
        ["Power"] = true,
        ["Menu"] = true,
        ["World59"] = true,
        ["World36"] = true,
        ["World5"] = true,
        ["Print"] = true,
        ["World4"] = true,
        ["Dollar"] = true,
        ["Eight"] = true,
        ["World79"] = true,
        ["Help"] = true,
        ["Pipe"] = true,
        ["KeypadEquals"] = true,
        ["Mode"] = true,
        ["World57"] = true,
        ["World7"] = true,
        ["Percent"] = true,
        ["RightSuper"] = true,
        ["World28"] = true,
        ["World15"] = true,
        ["World61"] = true,
        ["LeftSuper"] = true,
        ["Four"] = true,
        ["R"] = true,
        ["RightMeta"] = true,
        ["World62"] = true,
        ["World49"] = true,
        ["World56"] = true,
        ["NumLock"] = true,
        ["RightAlt"] = true,
        ["One"] = true,
        ["RightControl"] = true,
        ["RightShift"] = true,
        ["ScrollLock"] = true,
        ["CapsLock"] = true,
        ["Delete"] = true,
        ["F13"] = true,
        ["World83"] = true,
        ["LeftAlt"] = true,
        ["F4"] = true,
        ["F15"] = true,
        ["Break"] = true,
        ["KeypadEnter"] = true,
        ["Euro"] = true,
        ["KeypadPeriod"] = true,
        ["Question"] = true,
        ["World74"] = true,
        ["F9"] = true,
        ["Pause"] = true,
        ["LeftParenthesis"] = true,
        ["A"] = true,
        ["World41"] = true,
        ["C"] = true,
        ["B"] = true,
        ["LessThan"] = true,
        ["D"] = true,
        ["G"] = true,
        ["F"] = true,
        ["I"] = true,
        ["H"] = true,
        ["Period"] = true,
        ["J"] = true,
        ["M"] = true,
        ["L"] = true,
        ["O"] = true,
        ["N"] = true,
        ["Q"] = true,
        ["P"] = true,
        ["S"] = true,
        ["Return"] = true,
        ["U"] = true,
        ["T"] = true,
        ["W"] = true,
        ["V"] = true,
        ["Y"] = true,
        ["X"] = true,
        ["World35"] = true,
        ["Z"] = true,
        ["World10"] = true,
        ["World37"] = true,
        ["ButtonY"] = true,
        ["World13"] = true,
        ["F7"] = true,
        ["Compose"] = true,
        ["F5"] = true,
        ["F3"] = true,
        ["LeftCurly"] = true,
        ["World67"] = true,
        ["F2"] = true,
        ["World3"] = true,
        ["World60"] = true,
        ["RightParenthesis"] = true,
        ["F1"] = true,
        ["World47"] = true,
        ["World94"] = true,
        ["End"] = true,
        ["World93"] = true,
        ["Home"] = true,
        ["Clear"] = true,
        ["Tilde"] = true,
        ["Insert"] = true,
        ["Left"] = true,
        ["Escape"] = true,
        ["Up"] = true,
        ["Caret"] = true,
        ["F6"] = true,
        ["At"] = true,
        ["World81"] = true,
        ["World32"] = true,
        ["F12"] = true,
        ["World24"] = true,
        ["Unknown"] = true,
        ["Five"] = true,
        ["World44"] = true,
        ["F11"] = true,
        ["KeypadMinus"] = true,
        ["KeypadMultiply"] = true,
        ["World69"] = true,
        ["KeypadThree"] = true,
        ["BackSlash"] = true,
        ["World77"] = true,
        ["World70"] = true,
        ["KeypadSix"] = true,
        ["F10"] = true,
        ["KeypadNine"] = true,
        ["Colon"] = true,
        ["Quote"] = true,
        ["World2"] = true,
        ["World64"] = true,
        ["World66"] = true,
        ["RightCurly"] = true,
        ["World51"] = true,
        ["World9"] = true,
        ["Equals"] = true,
        ["Slash"] = true,
        ["World29"] = true,
        ["KeypadSeven"] = true,
        ["World87"] = true,
        ["Six"] = true,
        ["World91"] = true,
        ["World0"] = true,
        ["KeypadFour"] = true,
        ["KeypadTwo"] = true,
        ["KeypadOne"] = true,
        ["KeypadZero"] = true,
        ["KeypadFive"] = true,
        ["World90"] = true,
        ["World85"] = true,
        ["World12"] = true,
        ["World88"] = true,
        ["Comma"] = true,
        ["World86"] = true,
        ["World20"] = true,
        ["World89"] = true,
        ["World82"] = true,
        ["World17"] = true,
        ["World80"] = true,
        ["Ampersand"] = true,
        ["World78"] = true,
        ["World76"] = true,
        ["World75"] = true,
        ["World8"] = true,
        ["World73"] = true,
        ["World33"] = true,
        ["World18"] = true,
        ["QuotedDouble"] = true,
        ["KeypadDivide"] = true,
        ["KeypadEight"] = true,
        ["World23"] = true,
        ["World65"] = true,
        ["Semicolon"] = true,
        ["World22"] = true,
        ["Plus"] = true,
        ["World19"] = true,
        ["World58"] = true,
        ["World34"] = true,
        ["F8"] = true,
        ["World52"] = true,
        ["Backspace"] = true,
        ["Minus"] = true,
        ["World11"] = true,
        ["World31"] = true,
        ["SysReq"] = true,
        ["Backquote"] = true,
        ["PageDown"] = true,
        ["Nine"] = true,
        ["World1"] = true,
        ["Asterisk"] = true,
        ["World42"] = true,
        ["LeftMeta"] = true,
        ["Space"] = true,
        ["World39"] = true,
        ["World38"] = true,
        ["F14"] = true,
        ["Hash"] = true,
        ["E"] = true,
        ["World55"] = true,
        ["World71"] = true,
        ["Underscore"] = true,
        ["Two"] = true,
        ["World27"] = true,
        ["World25"] = true,
        ["World50"] = true,
        ["Seven"] = true,
        ["World63"] = true,
        ["World14"] = true,
        ["World46"] = true,
        ["ButtonL3"] = true,
        ["RightBracket"] = true,
        ["K"] = true
    },
    ["CLAN_TEXT"] = "Guild",
    ["TOOLBAR_LEVEL_REQUIREMENTS"] = {0, 0, 0, 5, 20, 50},
    ["TRADE_BOOTH_CURRENCY"] = "Gems",
    ["TRADE_TRANSACTION_FEE"] = 3,
    ["MouseIcon"] = "rbxassetid://15025035188",
    ["CHALLENGE_REFRESH_DURATION"] = 3600,
    ["SHINY_HUNTER_SUMMON_CHANCE"] = 6,
    ["DISCORD_LINK"] = "discord.gg/Defenders",
    ["BOOTHS"] = {
        ["LEVEL_REQUIREMENT"] = 15,
        ["VALID_TYPES"] = {["Units"] = {["Prefab"] = "UnitGridPrefab", ["GridButtonType"] = "UnitGridButton"}},
        ["LOW_LEVEL_SELL_CAP_PER_DAY"] = 10,
        ["TRANSACTION_FEE"] = 3,
        ["SIMILAR_TRANSACTION_COOLDOWN"] = 21600,
        ["CAN_TRADE_UNIT"] = "function: 0xe8c84cca9f4c9125",
        ["UNIT_RARITY_CEILING_PRICES"] = {999, 350, 1500, inf, inf, inf},
        ["UNIT_RARITY_FLOOR_PRICES"] = {0, 50, 150, 900, 7000, 10000},
        ["CURRENCY"] = "Gems",
        ["LOW_LEVEL_SELL_CAP_REQUIREMENT"] = 20
    },
    ["CHAPTER"] = {["STAT_ENUMS"] = {["Plays"] = 0, ["Wins"] = 0, ["BestClearTime"] = -1}},
    ["CONSOLE_CONTROLS"] = {
        ["Dash"] = Enum.KeyCode.ButtonR2,
        ["Emote"] = Enum.KeyCode.DPadRight,
        ["ShiftLock"] = Enum.KeyCode.ButtonL3
    },
    ["RANK_ROLLABLE_STATS"] = {["Range"] = 3, ["Cooldown"] = 2, ["Damage"] = 1},
    ["CanJoinMatch"] = "function: 0x27e0eb7f867dd6c5",
    ["CLAN_MAX_NAME_LENGTH"] = 8,
    ["UNIT_XP_LOSS_MODIFIER"] = 0.1,
    ["ITEMS"] = {["GRID_PREFAB_NAME"] = "ItemGridPrefab", ["DATA_BIN_NAME"] = "ItemData"},
    ["DEV_LOBBY_PLACE_ID"] = 17620826119,
    ["CHALLENGE_COUNT"] = 3,
    ["TRADING_PLACE_LEVEL_REQUIREMENT"] = 10,
    ["DEFAULT_KEYBINDS"] = {
        ["Unit Place"] = "E",
        ["Unit Rotate"] = "R",
        ["Unit Cancel"] = "C",
        ["Dash Keybind"] = "Q",
        ["Emote Keybind"] = "B"
    },
    ["CLAN_HQ_LEVEL_REQUIREMENT"] = 15,
    ["DASH_COOLDOWN_TIME"] = 0.6,
    ["LIKE_GEM_REWARD"] = 500,
    ["XP_PER_CHAPTER_WIN"] = 50,
    ["IS_NORMAL_PLACE"] = true,
    ["IS_AFK_PLACE"] = false,
    ["ROMAN_NUMBERALS"] = {"I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X"},
    ["NORMAL_PLACE_ID"] = 17017769292,
    ["IS_TRADING_PLACE"] = false,
    ["CLAN_CREATE_COST"] = 25000,
    ["IsPotionActive"] = "function: 0x52bc611ce0318765",
    ["GetPlayerXpFromLevel"] = "function: 0xfd59993e45d56785",
    ["RAIDS"] = {["LEVEL_REQUIREMENT"] = 20, ["FREQUENCY"] = 7200, ["DURATION"] = 3600},
    ["CLAN_MAX_DESCRIPTION_LENGTH"] = 50,
    ["TRAIT_ROLL_COST"] = {["Type"] = "Item", ["Currency"] = "Trait Crystal", ["Amount"] = {1, 1, 2, 3, 4, 5}},
    ["TRADING_PLACE_ID"] = 17490500437,
    ["SORT_FUNCTIONS"] = {
        ["Items"] = "function: 0x0690782e3958d605",
        ["UnitsIndex"] = "function: 0x8314c2684184d4e5",
        ["Mixed"] = "function: 0x95f3f22c0d1309a5",
        ["Emotes"] = "function: 0x3a9b7c6252f722c5",
        ["Units"] = "function: 0x0f788def9dc08745"
    },
    ["DEFAULT_UNLOCKED_MAP"] = "FooshaVillage",
    ["CLAN_CURRENCY"] = "Gold",
    ["RANK_ROLL_COST"] = {["Item"] = "Risky Dice", ["Amount"] = {1, 1, 1, 1, 1, 1}},
    ["INFINITE_MODE_DROP_FREQUENCY"] = 15,
    ["WORD_NUMBER_TO_STRING"] = {
        ["Four"] = "4",
        ["Nine"] = "9",
        ["ButtonA"] = "A",
        ["ButtonR1"] = "R1",
        ["Two"] = "2",
        ["One"] = "1",
        ["DPadRight"] = "DPadRight",
        ["ButtonL2"] = "L2",
        ["DPadUp"] = "DPadUp",
        ["Zero"] = "0",
        ["ButtonR3"] = "R3",
        ["ButtonR2"] = "R2",
        ["Seven"] = "7",
        ["Eight"] = "8",
        ["ButtonB"] = "B",
        ["Six"] = "6",
        ["DPadLeft"] = "DPadLeft",
        ["ButtonL1"] = "L1",
        ["ButtonY"] = "Y",
        ["ButtonX"] = "X",
        ["ButtonL3"] = "L3",
        ["Five"] = "5",
        ["Three"] = "3"
    },
    ["RELOAD_PLACE_ID"] = 17456575820,
    ["VALID_TRADABLES"] = {
        ["Units"] = {["GetPrefabName"] = "function: 0xb21c157a032922e5", ["GridButtonType"] = "UnitPageButton"}
    },
    ["GetUnitXpFromLevel"] = "function: 0x39979571c1aae1c5",
    ["TRAIT_SUMMON_CHANCE"] = 5,
    ["GetPlayerLevelFromXp"] = "function: 0x4c6d5da1f598c625",
    ["CanTeleportToTradeLobby"] = "function: 0x5f5887332211e9c5",
    ["XP_PER_CHAPTER_LOSE"] = 5,
    ["STAT_ENUMS"] = {
        ["SummonedRarity2"] = "SummonedRarity2",
        ["WeeklyQuestsCompleted"] = "WeeklyQuestsCompleted",
        ["UnitUpgraded"] = "UnitUpgraded",
        ["ChallengesCompleted"] = "ChallengesCompleted",
        ["SummonedRarity1"] = "SummonedRarity1",
        ["WavesClearedSolo"] = "WavesClearedSolo",
        ["InfinityWavesCleared"] = "InfinityWavesCleared",
        ["TotalQuestsCompleted"] = "TotalQuestsCompleted",
        ["ItemsUsed"] = "ItemsUsed",
        ["DailyQuestsCompleted"] = "DailyQuestsCompleted",
        ["SummonedRarity6"] = "SummonedRarity6",
        ["StoryCompleted"] = "StoryCompleted",
        ["TraitsRolled"] = "TraitsRolled",
        ["CursedAcademy_InfiniteWavesCleared"] = "CursedAcademy_InfiniteWavesCleared",
        ["WavesCleared"] = "WavesCleared",
        ["AFKPlaytime"] = "AFKPlaytime",
        ["Kills"] = "Kills",
        ["Playtime"] = "Playtime",
        ["WavesClearedMultiplayer"] = "WavesClearedMultiplayer",
        ["VIPQuestsCompleted"] = "VIPQuestsCompleted",
        ["ItemsCrafted"] = "ItemsCrafted",
        ["SummonedRarity5"] = "SummonedRarity5",
        ["BluePlanet_InfiniteWavesCleared"] = "BluePlanet_InfiniteWavesCleared",
        ["UnitsSold"] = "UnitsSold",
        ["UnitsPlaced"] = "UnitsPlaced",
        ["DamageDealt"] = "DamageDealt",
        ["UnitSummons"] = "UnitSummons",
        ["UnderwaterTemple_InfiniteWavesCleared"] = "UnderwaterTemple_InfiniteWavesCleared",
        ["CodesUsed"] = "CodesUsed",
        ["SummonedRarity4"] = "SummonedRarity4",
        ["TradesCompleted"] = "TradesCompleted",
        ["SummonedRarity3"] = "SummonedRarity3",
        ["RaidsCompleted"] = "RaidsCompleted",
        ["NumLogins"] = "NumLogins",
        ["FooshaVillage_InfiniteWavesCleared"] = "FooshaVillage_InfiniteWavesCleared",
        ["MobCity_InfiniteWavesCleared"] = "MobCity_InfiniteWavesCleared"
    },
    ["TEXTBOX_FUNCTIONS"] = {
        ["ClanName"] = "function: 0xd8da70bbf383a8d5",
        ["NumberOnly"] = "function: 0x293bf03f36c43a05",
        ["ClanImage"] = "function: 0xa2ec6f9fb48875a5",
        ["ClanDescription"] = "function: 0x7d9c280a9c24a125",
        ["LeaveClan"] = "function: 0xde5e80dda4d6deb5",
        ["None"] = "function: 0x909b761d1700e0e5"
    },
    ["MATCH"] = {
        ["DURATION"] = 60,
        ["DATA_ENUMS"] = {
            ["Chapter"] = {["Required"] = true, ["IsValid"] = "function: 0x0a33e8cc96f3c765"},
            ["FriendsOnly"] = {["Required"] = true, ["IsValid"] = "function: 0x6e46097adb9f8bc5"},
            ["Difficulty"] = {["Required"] = true, ["IsValid"] = "function: 0xcefeb1ff4e199f75"}
        },
        ["MAX_SIZE"] = 4
    },
    ["MAX_EQUIPPED_UNITS"] = 6,
    ["AFK_PLACE_ID"] = 17513685680,
    ["TD_PLACE_ID"] = 17018663967,
    ["SUMMON_CHAT_ANNOUNCEMENT_MIN_RARITY"] = 4,
    ["UNITS"] = {
        ["GRID_PREFAB_NAME"] = "UnitGridPrefab",
        ["DATA_BIN_NAME"] = "UnitData",
        ["SELL_CURRENCY"] = "Gold",
        ["SELL_PRICES"] = {0, 100, 400, 2000, 8000, 8000},
        ["SORT_INDEXES"] = {["CreatedAt"] = 2, ["None"] = 3, ["Damage"] = 1},
        ["TRACKED_STATS"] = {["Earned"] = "Earned", ["Kills"] = "Kills", ["Damage"] = "Damage"},
        ["TYPES"] = {
            ["Summoner"] = {["Short"] = "SUMN", ["Colors"] = {Color3.fromRGB(175, 93, 249)}},
            ["Hybrid"] = {["Short"] = "HYBD", ["Colors"] = {Color3.fromRGB(255, 0, 186), Color3.fromRGB(0, 233, 255)}},
            ["Farm"] = {["Short"] = "FARM", ["Colors"] = {Color3.fromRGB(255, 207, 59)}},
            ["Buff"] = {["Short"] = "BUFF", ["Colors"] = {Color3.fromRGB(255, 38, 40)}},
            ["Hill"] = {["Short"] = "HILL", ["Colors"] = {Color3.fromRGB(93, 221, 52)}},
            ["Ground"] = {["Short"] = "GRND", ["Colors"] = {Color3.fromRGB(127, 96, 68)}},
            ["Support"] = {["Short"] = "SUPP", ["Colors"] = {Color3.fromRGB(16, 154, 233)}}
        },
        ["TRADED_EQUIP_LEVEL_REQUIREMENT"] = {0, 15, 15, 20, 25, 25},
        ["STATS"] = {
            ["BleedDuration"] = true,
            ["CritChance"] = true,
            ["Bleed"] = true,
            ["CurseDuration"] = true,
            ["Curse"] = true,
            ["Burn"] = true,
            ["Range"] = true,
            ["XpBoost"] = true,
            ["FreezeDuration"] = true,
            ["BurnDuration"] = true,
            ["Cap"] = true,
            ["Farm"] = true,
            ["MoneyBoost"] = true,
            ["CritMult"] = true,
            ["Cooldown"] = true,
            ["Damage"] = true
        }
    },
    ["RANK_ROLL_FREEZE_ITEM"] = "Frost Bind",
    ["CLAN_CREATE_PLAYTIME_REQUIREMENT"] = 3600,
    ["SHINY_SUMMON_CHANCE"] = 2.5,
    ["IS_TD_PLACE"] = false,
    ["TRAIT_SECONDARY_ROLL_CHANCE"] = 5,
    ["MAX_TEAMS"] = 4,
    ["AFK"] = {["CURRENCY_PER_HOUR"] = 160, ["LEVEL_REQUIREMENT"] = 10, ["CURRENCY"] = "Gems", ["TIME_PER_ROLL"] = 90},
    ["TRADING_PLACE_PLAYTIME_REQUIREMENT"] = 20
}
