data = {
    ["Rotation"] = {
        "Confetti Cannon",
        "The Blue Strange",
        "Apathetic",
        "Tall Friend",
        "AFK Sign",
        "Yellow Ringed",
        "Idea",
        "Kenny the Koala",
        "Megagavel",
        "Rainbow Sparkles",
        "Idealist",
        "Round Cat",
        "Liberty Torch",
        "Conscience",
        "Double Cheezburger",
        "Arctic Fowl",
        "Kazoos",
        "Jumbo Snail",
        "Blueberry Pie",
        "8-bit Duck",
        "Slurpee",
        "Musician",
        "Flowers",
        "Kooki the Kookaburra",
        "Sign: This Is Epic",
        "Purple Lightning Storm",
        "Blobby Fish",
        "Fairy Wings",
        "Yellow Anime Aura",
        "Flying Angel",
        "TOMATOES!",
        "Royal",
        "Azure Eye",
        "Untouchable",
        "Red Divergent",
        "Bird of Prey",
        "Sign: This Is NOT Epic",
        "Blue Ringed",
        "Fiery Phoenix",
        "Discombobulated",
        "White Divergent",
        "Flying Devil",
        "Speech Bubble",
        "Atomizer",
        "Herbert T. Shark",
        "Superior",
        "EPIC Stamper",
        "Percy the Platypus",
        "Noob Pop",
        "Disestablishmentarianist",
        "Goofy Spider",
        "Tornados",
        "Security Bot",
        "Cups of tea",
        "Bri'ish",
        "Crumpets",
        "Red Anime Aura",
        "eyesnlips",
        "Shuriken",
        "Toxic Fowl",
        "Piggybank",
        "Introvert",
        "Orange Balloon Animal",
        "Big Heads",
        "Korblox Bird",
        "Sinister",
        "Chicken Gun",
        "Ascend",
        "Ethereal Mist",
        "Extrovert",
        "Science Project: Volcano",
        "Ellie the Emu",
        "Robo Companion",
        "MURICAN",
        "Freedom Eagle",
        "Rings",
        "Royal Frog",
        "Books",
        "Crab Horde",
        "Awake",
        "Plasma",
        "Haggard",
        "Ink Launcher",
        "Redrune Raider",
        "Noob Hot Chocolate",
        "Alert",
        "Swamp Monster",
        "Magic Barrier",
        "Motley Parrot",
        "Spirals",
        "Science Project: Potato",
        "Blorb",
        "Orinthian Falcon",
        "Simpleton",
        "Squid Launcher",
        "Worst Thing I've Ever Seen",
        "Shark Launcher",
        "Neanderthal",
        "Void Sheep",
        "The Claw",
        "Bouncy",
        "Musical Barrier",
        "Hedgehog Friend",
        "Scary Polar Bear",
        "Comic Thwack",
        "barcode",
        "Dragon Plushie",
        "Wally the Wombat",
        "Skeletonize",
        "skulls",
        "Bighead Potion",
        "Lightning",
        "Song Bird",
        "Caution Crazy",
        "Alpaca Plushie",
        "Shark Attack",
        "Gravestone",
        "shrugface",
        "Vanish",
        "Killer Whale Launcher"
    },
    ["randomSortOffset"] = 0,
    ["rotationTimeStart"] = 1690502400,
    ["timeOffset"] = 0,
    ["randomise"] = false
}
