data = {
    {
        ["Rock Throw"] = 2,
        ["Bow and Arrow"] = 1,
        ["Rock Smash"] = 1,
        ["Scratch"] = 2,
        ["Toxic Knife"] = 1,
        ["Poison Dagger"] = 2,
        ["Wooden Club Slam"] = 2,
        ["Rusty Knife"] = 2,
        ["Bear Trap"] = 2
    },
    {["Disperse Winds"] = 1},
    {
        ["Tranquilizer"] = 4,
        ["Poison Dart"] = 4,
        ["Shield Bash"] = 4,
        ["Arcovian Resilience"] = 3,
        ["Bow and Arrow"] = 3,
        ["Yew Longbow"] = 2,
        ["Bear Trap"] = 2,
        ["Ice Axe"] = 2,
        ["Ramparts"] = 2,
        ["Tripwire"] = 4,
        ["Iron Shield"] = 4,
        ["Rusty Knife"] = 3,
        ["Wooden Club Slam"] = 4,
        ["Rock Smash"] = 4,
        ["Iron Broadsword"] = 4
    },
    {
        ["Lacerate"] = 2,
        ["Corroded Dagger"] = 4,
        ["Befouling Denouncement"] = 2,
        ["Feint"] = 4,
        ["Bandit's Bugle"] = 1,
        ["Assassin's Dagger"] = 2,
        ["Envenomed Venomshank"] = 2
    },
    {
        ["Rotten Claw"] = 1,
        ["Shadow Trade"] = 2,
        ["Megaquake"] = 1,
        ["Radiant Indemnity"] = 1,
        ["Soul Blast"] = 1,
        ["Breath of Death"] = 1,
        ["Winds of Decay"] = 1,
        ["Intimidation"] = 1
    },
    {["Lu Cian"] = 1, ["KipEffect8"] = 1, ["KipAttack18"] = 3},
    "function: 0x0000000013bb17bd",
    {
        ["Arcane Blast"] = 2,
        ["Wand Zap"] = 3,
        ["Earthquake"] = 1,
        ["Wisp"] = 2,
        ["Chain Lightning"] = 5,
        ["Soul Missile"] = 2,
        ["Lightning Bolt"] = 2,
        ["Spell Backfire"] = 2
    },
    {["Mask of Truth"] = 1, ["Devour"] = 2, ["Mind Poison"] = 3, ["Other Wing"] = 3, ["Bird Call"] = 3},
    {["Blunder"] = 1},
    {},
    {
        ["Hivemind"] = 1,
        ["Army of One"] = 1,
        ["Protecting Plumage"] = 1,
        ["Wings of Many"] = 1,
        ["Do not be not afraid"] = 1,
        ["Warped Perception"] = 1,
        ["Inhuman"] = 1
    },
    {},
    "function: 0x000000008ecf21f5",
    {["Unyielding Blade"] = 5},
    {
        ["Corrupt"] = 2,
        ["Shadowbolt"] = 1,
        ["Dark Trade"] = 3,
        ["Shadowball"] = 2,
        ["Soul Blast"] = 2,
        ["Soul Missile"] = 3
    },
    {
        ["Attack Debuff"] = 2,
        ["Poisonous Vial"] = 1,
        ["Potion Throw"] = 2,
        ["Feint"] = 2,
        ["Mystery Elixir Throw"] = 1,
        ["Unstable Concoction"] = 1
    },
    {
        ["Fireball"] = 3,
        ["Snowville's Welcome"] = 1,
        ["Enlighten"] = 3,
        ["Small Blessing"] = 3,
        ["Frost"] = 1,
        ["Wand Zap"] = 4,
        ["Meditation"] = 1,
        ["Guided Strike"] = 4,
        ["High Cognition"] = 3,
        ["Lightning Bolt"] = 2,
        ["Ember"] = 2,
        ["Wind Powered"] = 2,
        ["Firestarter"] = 3,
        ["Glacial Impalement"] = 1,
        ["Wisp"] = 4,
        ["Arcane Blast"] = 2,
        ["Holy Ground"] = 4,
        ["Zoink"] = 4,
        ["Arcovian Resilience"] = 3
    },
    "function: 0x00000000471964a5",
    {["Jab Combo"] = 4, ["KipAttack13"] = 3, ["Boxer's Rushdown"] = 2, ["The Ole' One-Two"] = 3, ["Boxer's Stance"] = 1},
    {
        ["Strong Gust"] = 2,
        ["Displacement Rune"] = 1,
        ["Lightning Bolt"] = 1,
        ["Choke"] = 1,
        ["Chain Lightning"] = 2,
        ["Meditation"] = 1
    },
    {},
    {["Command"] = 1, ["Ramparts"] = 2, ["High Cognition"] = 2},
    {
        ["Ramparts"] = 1,
        ["Shadow Trade"] = 1,
        ["High Cognition"] = 2,
        ["Wild Roar"] = 2,
        ["Winds of Regeneration"] = 1,
        ["World Tear"] = 3,
        ["Strength Duality"] = 2,
        ["Meditation"] = 1
    },
    {},
    {},
    "function: 0x00000000c8eb92d5",
    "function: 0x00000000e6838efd",
    {["Shadowbolt"] = 2, ["Shadow Trade"] = 1, ["Rock Smash"] = 2, ["Astral Blessing"] = 1},
    {
        ["Fireball"] = 2,
        ["High Cognition"] = 1,
        ["Core Infliction"] = 1,
        ["Darksteel Longblade"] = 1,
        ["Lightning Bolt"] = 2,
        ["Cursed Spot"] = 1,
        ["Shadow Trade"] = 2,
        ["Soul Missile"] = 2,
        ["Ignite"] = 2,
        ["Arcane Blast"] = 2,
        ["Wand Zap"] = 2,
        ["Chain Lightning"] = 1,
        ["Cursed Rune"] = 1
    },
    {
        ["Fireball"] = 3,
        ["High Cognition"] = 3,
        ["Enlighten"] = 3,
        ["Small Blessing"] = 3,
        ["Holy Ground"] = 4,
        ["Arcane Blast"] = 2,
        ["Horn of the Unicorn"] = 2,
        ["Wisp"] = 4,
        ["Guided Strike"] = 4,
        ["Wand Zap"] = 4,
        ["Lightning Bolt"] = 2,
        ["Zoink"] = 4
    },
    {["Smack"] = 4},
    {["High Tide"] = 1},
    {["Claw Impale"] = 3, ["Vitality"] = 3, ["Immolation"] = 1, ["Life Drain"] = 3, ["Enchanted Polyphone"] = 1},
    {["Dark Claw"] = 1, ["Miasma"] = 1},
    {
        ["Defense Debuff"] = 1,
        ["Unholy Prayer"] = 1,
        ["Grow Sprouts"] = 2,
        ["Cursed Prayer"] = 1,
        ["Magician's Secret"] = 4,
        ["Shadow Trade"] = 2,
        ["Attack Buff"] = 1,
        ["Toxic Plant"] = 4
    },
    {["Greater Fireball"] = 3, ["Greater Singe"] = 2},
    {["Scimitar"] = 3, ["Wooden Sword"] = 2, ["The Ole' One-Two"] = 1},
    {["KipAttack"] = 2},
    "function: 0x00000000c5fcdb0d",
    {},
    {["Stupify"] = 2, ["Ramparts"] = 1, ["Smack"] = 2, ["Beauty Sleep"] = 2},
    {["Smack"] = 1},
    {["Intensifier"] = 69},
    {
        ["Scattered Scrolls"] = 1,
        ["Enhanced Arms Race"] = 3,
        ["Papercut"] = 1,
        ["Extinguish"] = 1,
        ["Stargazer's Eye"] = 1,
        ["Meditation"] = 2
    },
    {["Obscure"] = 1},
    {["Lu Cian"] = 1, ["KipAttack18"] = 2, ["Curtain Call"] = 1},
    {},
    {
        ["Trick or Treat"] = 2,
        ["Defense Buff"] = 4,
        ["Exploding Arrow"] = 2,
        ["Sugar Rush"] = 3,
        ["Smokescreen"] = 2,
        ["Karaoke"] = 2,
        ["Blinding Flash"] = 2,
        ["Pollute"] = 2
    },
    {["Kathruul's Torment"] = 1, ["Cold Feet"] = 1, ["Pollute"] = 3, ["Cold Shoulder"] = 1, ["Meditation"] = 1},
    {},
    "function: 0x000000001962674d",
    {["KipAttack19"] = 1},
    {
        ["Cursed Spot"] = 1,
        ["Shadow Trade"] = 2,
        ["Unnatural Regeneration"] = 1,
        ["Radiant Indemnity"] = 1,
        ["Axe Slash"] = 1,
        ["Soul Missile"] = 1,
        ["Plated Sword"] = 1
    },
    {["Authority"] = 1},
    {["Flurry"] = 2, ["Icy Heal"] = 2, ["Cold Mark"] = 1, ["Iced Rapier"] = 3},
    {
        ["Spell Backfire"] = 1,
        ["Wisp"] = 2,
        ["Chain Lightning"] = 1,
        ["Wand Zap"] = 3,
        ["Lightning Bolt"] = 1,
        ["Zoink"] = 2
    },
    {["Chains of Pain"] = 1, ["Swing Staff"] = 3},
    {["Blunder"] = 1},
    {["KipAttack5"] = 1},
    {
        ["Cursed Spot"] = 1,
        ["Shadow Trade"] = 2,
        ["Scratch"] = 3,
        ["Soul Missile"] = 2,
        ["Earthquake"] = 1,
        ["Pollute"] = 2
    },
    {
        ["KipAttack3"] = 1,
        ["SFOTH Ice Dagger"] = 1,
        ["SFOTH Firebrand"] = 1,
        ["Axe Slash"] = 1,
        ["Venomshank"] = 1,
        ["Ice Sword"] = 1,
        ["Cold Mark"] = 1,
        ["SFOTH Windforce"] = 1,
        ["Short Sword"] = 1,
        ["Hunter's Mark"] = 1,
        ["Thaw-maturgy"] = 1,
        ["Sub-Zero Swing"] = 1,
        ["Iron Broadsword"] = 1,
        ["Toe Stab"] = 1,
        ["Iced Rapier"] = 1,
        ["Telesword"] = 1,
        ["Plated Sword"] = 1,
        ["SFOTH Ghostwalker"] = 1,
        ["Darksteel Longblade"] = 1,
        ["SFOTH Darkheart"] = 1,
        ["Rapier Thrust"] = 1,
        ["SFOTH Illumina"] = 1,
        ["SFOTH Venomshank"] = 1,
        ["Silver Blade"] = 1,
        ["Retiarice Thrust"] = 1,
        ["KipAttack10"] = 1,
        ["Sword and Buckler"] = 1,
        ["Dynamic Bolt"] = 1,
        ["Scimitar"] = 1
    },
    {["KipEffect5"] = 10},
    {["Pie Swarm"] = 3, ["Tasty Pie"] = 5, ["Ramparts"] = 1, ["Book of Lore"] = 1},
    {["Blue Elixir"] = 1, ["Jack o' Lantern Throw"] = 1, ["Pumpkin Bomb"] = 1, ["Iron Broadsword"] = 1},
    {["Swing Blade"] = 2, ["Throwing Dagger"] = 1},
    {["Ramparts"] = 1, ["Iron Shield"] = 1, ["Afternoon Delight"] = 2, ["Command"] = 1, ["Sword and Buckler"] = 3},
    {},
    {["Blunder"] = 1},
    {["Hellfire"] = 1},
    {["The Ole' One-Two"] = 1, ["Rock Smash"] = 2, ["Bow and Arrow"] = 3, ["Poison Dagger"] = 3, ["Pollute"] = 2},
    {
        ["Shadow Trade"] = 1,
        ["Iron Shield"] = 2,
        ["Afternoon Delight"] = 3,
        ["Soul Missile"] = 2,
        ["Rock Smash"] = 2,
        ["Iron Broadsword"] = 2
    },
    {},
    {["KipEffect2"] = 7},
    {
        ["Ember"] = 6,
        ["Horn of the Unicorn"] = 1,
        ["Pumpkin Collection"] = 1,
        ["Telesword"] = 3,
        ["Meditation"] = 1,
        ["Pumpkin Bomb Fling"] = 1
    },
    {["Rock Throw"] = 3, ["Darksteel Pick"] = 5, ["Soul Missile"] = 2, ["Rusty Knife"] = 3, ["Rock Smash"] = 3},
    {
        ["Wind Powered"] = 1,
        ["Ramparts"] = 1,
        ["High Cognition"] = 1,
        ["Snowball"] = 3,
        ["Ice Bow"] = 1,
        ["Meditation"] = 2
    },
    {["Grave Rave"] = 5, ["Attack Debuff"] = 5, ["Catalyst"] = 4, ["Perish"] = 7, ["Stitch Up"] = 5, ["Apocalypse"] = 1},
    {
        ["Tranquilizer"] = 4,
        ["Exploding Arrow"] = 1,
        ["Rock Throw"] = 4,
        ["Bow and Arrow"] = 3,
        ["Slingshot"] = 2,
        ["Tripwire"] = 4,
        ["Yew Longbow"] = 2,
        ["Bear Trap"] = 2,
        ["Rusty Knife"] = 3,
        ["Poison Dart"] = 4
    },
    {
        ["Hyperbolt"] = 1,
        ["Frost"] = 5,
        ["Glacial Impalement"] = 1,
        ["Avalanche"] = 2,
        ["Command"] = 2,
        ["Glacial Imprisonment"] = 1,
        ["Snowville's Welcome"] = 3,
        ["Arcovian Resilience"] = 3
    },
    {["Repertoire Announcement"] = 1},
    {["Arcane Overload"] = 33},
    {["KipAttack10"] = 2},
    {
        ["Heat Relief"] = 1,
        ["Core Infliction"] = 1,
        ["KipAttack19"] = 1,
        ["Vitality"] = 1,
        ["Enhanced Meteor Strike"] = 1,
        ["Hyperbolt"] = 1,
        ["Life Drain"] = 1,
        ["Toxic Plant"] = 1,
        ["Glacial Impalement"] = 1,
        ["Astral Blessing"] = 1,
        ["Command"] = 2,
        ["Arcane Barrage"] = 1,
        ["Infernal Blast"] = 1,
        ["Snowville's Slumber"] = 1
    },
    {
        ["Cursed Spot"] = 1,
        ["Scratch"] = 3,
        ["Cursed Rune"] = 2,
        ["Uppercut"] = 2,
        ["Soul Missile"] = 2,
        ["Rock Smash"] = 1,
        ["Pollute"] = 2
    },
    {["SFOTH Windforce"] = 3},
    {["Rock Smash"] = 1, ["Scratch"] = 3, ["Pollute"] = 2},
    {["KipEffect4"] = 10},
    {
        ["Fireball"] = 1,
        ["High Cognition"] = 1,
        ["Zoink"] = 2,
        ["Lightning Bolt"] = 2,
        ["Arcane Blast"] = 1,
        ["Enlighten"] = 2,
        ["Soul Missile"] = 2,
        ["Spell Backfire"] = 2,
        ["Wisp"] = 2,
        ["Ignite"] = 2,
        ["Wand Zap"] = 3,
        ["Chain Lightning"] = 1,
        ["Cursed Rune"] = 2
    },
    "function: 0x000000006605e3cd",
    {
        ["Tranquilizer"] = 1,
        ["Bow and Arrow"] = 2,
        ["Wind Powered"] = 3,
        ["Ramparts"] = 1,
        ["Cold Shoulder"] = 1,
        ["Yew Longbow"] = 2,
        ["Dynamite"] = 1,
        ["Ice Tipped Arrow"] = 2,
        ["Blue Elixir"] = 2,
        ["Arcovian Resilience"] = 1
    },
    {
        ["Deadly Presence"] = 2,
        ["Putrid Odor"] = 2,
        ["Scratch"] = 1,
        ["Bite"] = 1,
        ["Scimitar"] = 2,
        ["Corroded Scimitar"] = 2,
        ["Backhand Smack"] = 1,
        ["Shadow Trade"] = 2
    },
    {["Imbued Blade"] = 1},
    {["Blunder"] = 1},
    {["Rothgar Altar: Maintain Corruption"] = 1, ["Rothgar Altar: Corrupt Airflow"] = 4},
    {
        ["Poison Dagger"] = 3,
        ["Yew Longbow"] = 2,
        ["Uppercut"] = 2,
        ["Venomshank"] = 1,
        ["The Ole' One-Two"] = 2,
        ["Toxic Knife"] = 2
    },
    {["Shadowbolt"] = 2, ["Shadow Trade"] = 1, ["Rock Smash"] = 2, ["Astral Blessing"] = 1},
    {["Violent Horrors"] = 1},
    {["FriendlyFriend"] = 1},
    {
        ["SFOTH Battle Armor"] = 1,
        ["Classic Bomb"] = 4,
        ["Classic Superball"] = 5,
        ["Classic Linked Sword"] = 2,
        ["Classic Medkit"] = 3,
        ["Classic Slingshot"] = 2,
        ["Classic Rocket Launcher"] = 3
    },
    "function: 0x000000000d71748d",
    {["SFOTH Ice Dagger"] = 3},
    {},
    {["SFOTH Ghostwalker"] = 3},
    {["SFOTH Illumina"] = 3},
    "function: 0x000000006d06eb15",
    {["Ethereal Ball"] = 2, ["Elemental Swipe"] = 1, ["Elemental Surge"] = 6, ["Elemental Claw"] = 2},
    {["Raise Husk"] = 2, ["Pollute"] = 3, ["Panic"] = 1, ["Wraith Call"] = 1},
    {["Murderous Cut"] = 6, ["Throwing Dagger"] = 2, ["Haste"] = 2, ["Victimize"] = 4, ["Murderous Intent"] = 2},
    {["Sword and Buckler"] = 3, ["Defense Buff"] = 1, ["Distraction"] = 3},
    {["Classic Linked Sword"] = 5},
    {},
    {["Uppercut"] = 1, ["Iron Broadsword"] = 3, ["Meditation"] = 2},
    {
        ["Mask of Calamity"] = 2,
        ["Core Infliction"] = 1,
        ["Defense Debuff"] = 5,
        ["Dispel"] = 1,
        ["Wind Powered"] = 2,
        ["Shadow Trade"] = 2,
        ["Dynamic Bolt"] = 1,
        ["Focus"] = 1,
        ["Winds of Regeneration"] = 2,
        ["Wisp"] = 1,
        ["Blue Elixir"] = 2,
        ["Hot Cocoa"] = 2
    },
    {["Flee"] = 40},
    {},
    {["Ember"] = 3, ["Ignite"] = 2},
    {["Warp Rift"] = 1},
    "function: 0x00000000898469fd",
    {
        ["Shadow Combustion"] = 2,
        ["Sigil Scribble"] = 2,
        ["Lightning Chain"] = 2,
        ["Shadowstorm"] = 2,
        ["Shadow Sphere"] = 2,
        ["Pilfer"] = 2
    },
    {["Dark Pilfer"] = 3, ["Shadowball"] = 1, ["Corrupt"] = 1, ["Shadow Drain"] = 2},
    {["Glaive"] = 20},
    {
        ["High Cognition"] = 2,
        ["Rapier Thrust"] = 3,
        ["Wind Powered"] = 5,
        ["Ramparts"] = 2,
        ["Arcovi-Bolt"] = 2,
        ["Ice Sword"] = 1,
        ["Arcovian Resilience"] = 1,
        ["Blue Elixir"] = 3,
        ["Iron Broadsword"] = 3
    },
    {
        ["Curse of the Forsaken"] = 1,
        ["Wandering Star"] = 1,
        ["Fervid Drain"] = 3,
        ["Unstable Charge"] = 1,
        ["Unstable Impact"] = 1,
        ["Unstable Power"] = 1
    },
    {
        ["Attack Buff"] = 2,
        ["Deep Blight"] = 1,
        ["Feint"] = 2,
        ["Lacerate"] = 2,
        ["Rock Smash"] = 1,
        ["Poisoned Spikes"] = 1
    },
    {["KipEffect7"] = 3},
    "function: 0x0000000048208d4d",
    {
        ["Smack"] = 1,
        ["Scratch"] = 1,
        ["Soul Missile"] = 1,
        ["Uppercut"] = 1,
        ["Backhand Smack"] = 1,
        ["The Ole' One-Two"] = 2,
        ["Vile Odor"] = 1
    },
    "function: 0x000000004859fd9d",
    {
        ["Tome: Zap"] = 2,
        ["Tome: Minor Burn"] = 3,
        ["Panic"] = 2,
        ["Tome: Bewilder"] = 2,
        ["Student's Tome"] = 3,
        ["Wisp"] = 2,
        ["Channel Arcane Barrage"] = 2,
        ["Tome: Torment"] = 2,
        ["Tome: Confuse"] = 3,
        ["Chain Lightning"] = 2,
        ["Tome: Strike"] = 1
    },
    {["Snow Bros"] = 4},
    {
        ["Sneal Battlecry"] = 1,
        ["Defense Buff"] = 2,
        ["Core Infliction"] = 1,
        ["Haste"] = 1,
        ["Ramparts"] = 2,
        ["Zoink"] = 1
    },
    {["Pollute"] = 1, ["Decaying Ray"] = 1, ["Graveyard"] = 1, ["Well of the Dead"] = 2},
    {["Bite"] = 2, ["Wild Roar"] = 1, ["Feast"] = 1, ["Heavy Flop"] = 4, ["Ungodly Stench"] = 3, ["Accelerate"] = 3},
    {["Flop"] = 20},
    {
        ["Exploding Arrow"] = 2,
        ["Silver Blade"] = 2,
        ["Command"] = 1,
        ["Throwing Dagger"] = 3,
        ["Hunter's Mark"] = 3,
        ["Scimitar"] = 2
    },
    {},
    {["KipAttack20"] = 1},
    {["Smack"] = 3},
    {["KipAttack19"] = 1},
    "function: 0x000000003b21d995",
    {["Blunder"] = 1},
    {},
    {["Super Aoe World Tear"] = 69},
    {
        ["Wind Powered"] = 3,
        ["Mind Control"] = 1,
        ["Enchanted Staff of Azure"] = 1,
        ["Frost"] = 4,
        ["Protection Seal"] = 1,
        ["Ramparts"] = 2
    },
    {
        ["Classic Paintball Gun"] = 3,
        ["Classic Bomb"] = 1,
        ["Classic Rocket Launcher"] = 2,
        ["Classic Medkit"] = 1,
        ["SFOTH Battle Armor"] = 1,
        ["Classic Slingshot"] = 5
    },
    {["KipAttack17"] = 1},
    {["Claw Impale"] = 3, ["Vitality"] = 1, ["Lesser Exsanguinate"] = 1, ["Minor Time Warp"] = 2, ["Life Drain"] = 1},
    {["Blunder"] = 1},
    {},
    "function: 0x000000007b9f879d",
    {
        ["Wind Powered"] = 2,
        ["Hot Cocoa"] = 2,
        ["Unstable Blast"] = 4,
        ["Fervid Drain"] = 3,
        ["Curse of the Forsaken"] = 1,
        ["Unstable Corruption"] = 5,
        ["Unstable Impact"] = 1,
        ["Unstable Concoction"] = 3
    },
    {
        ["Mask of Calamity"] = 2,
        ["Core Infliction"] = 1,
        ["Defense Debuff"] = 5,
        ["Dispel"] = 1,
        ["Wisp"] = 1,
        ["Wind Powered"] = 2,
        ["Shadow Trade"] = 2,
        ["Dynamic Bolt"] = 1,
        ["Focus"] = 1,
        ["Winds of Regeneration"] = 2,
        ["Hot Cocoa"] = 2,
        ["Blue Elixir"] = 2,
        ["Shadowbolt"] = 2
    },
    {["Spin Chair"] = 3, ["Wild Roar"] = 1, ["Chair Toss"] = 3, ["Chair Bash"] = 3},
    {["Afternoon Delight"] = 2, ["Defense Buff"] = 1, ["Sword and Buckler"] = 3, ["Distraction"] = 3},
    {["Classic Linked Sword"] = 3},
    {["Imbued Blade"] = 1},
    {["Enhanced Arms Race"] = 1},
    {["KipAttack2"] = 20},
    {["KipAttack2"] = 20},
    {},
    {["Greater Fireball"] = 3, ["Greater Singe"] = 2},
    {
        ["KipAttack3"] = 33,
        ["Shield Bash"] = 3,
        ["Stupify"] = 5,
        ["Bow and Arrow"] = 3,
        ["Chomp"] = 5,
        ["Sword and Buckler"] = 5,
        ["Scratch"] = 4,
        ["Rock Smash"] = 3,
        ["Rusty Nails"] = 2,
        ["Bardiche Chop"] = 3,
        ["Poison Dagger"] = 3,
        ["Iron Broadsword"] = 2
    },
    {["SFOTH Firebrand"] = 3},
    {
        ["Wind Powered"] = 3,
        ["Iron Shield"] = 2,
        ["Command"] = 2,
        ["Toe Stab"] = 2,
        ["Retiarice Thrust"] = 2,
        ["Arcovian Resilience"] = 1
    },
    {},
    {
        ["Arcane Blast"] = 1,
        ["Chain Lightning"] = 2,
        ["High Cognition"] = 1,
        ["Wisp"] = 2,
        ["Aura Pierce"] = 1,
        ["Wand Zap"] = 2,
        ["Lightning Bolt"] = 2,
        ["Zoink"] = 2
    },
    {},
    {["Blunder"] = 1},
    "function: 0x000000007b88a0f5",
    {},
    {["Uppercut"] = 2, ["Banana Peel"] = 1, ["Smack"] = 2, ["Rock Throw"] = 2},
    {["KipAttack6"] = 3, ["KipAttack7"] = 3},
    {["C4"] = 6},
    {["Blunder"] = 1},
    {
        ["Defense Debuff"] = 1,
        ["Attack Buff"] = 1,
        ["High Cognition"] = 2,
        ["Vampire's Claw"] = 2,
        ["Shadow Trade"] = 1,
        ["Guided Strike"] = 1
    },
    {["Flop"] = 20},
    {["Astral Destabilization"] = 1},
    {
        ["Burning Pledge"] = 2,
        ["Pumpkin Collection"] = 1,
        ["Hellfire"] = 1,
        ["Dullahan's Calamity"] = 1,
        ["Horn of the Unicorn"] = 1,
        ["Trick or Treat"] = 2,
        ["Telesword"] = 2,
        ["Ignite"] = 3,
        ["Pumpkin Bomb Fling"] = 1
    },
    {
        ["Inflame"] = 3,
        ["Burst Flare"] = 4,
        ["Hot Sauce"] = 2,
        ["Kindling Fury"] = 2,
        ["Chad's Firestarter"] = 4,
        ["Meditation"] = 1
    },
    {["Rock Smash"] = 1, ["Scratch"] = 3, ["Pollute"] = 2},
    {["Aoe World Tear"] = 69},
    {["Fireball"] = 1, ["Bow and Arrow"] = 1, ["Blue Elixir"] = 1, ["Iron Broadsword"] = 1},
    {["Wildfire"] = 1},
    {["Sugar Rush"] = 1, ["Attack Buff"] = 2, ["Cold Shoulder"] = 1, ["MUSCLE PUNCH"] = 1},
    {
        ["Reckless Cut"] = 1,
        ["Poor Hacking"] = 4,
        ["Amputate"] = 2,
        ["Butcher"] = 6,
        ["'Just another day at work'"] = 6,
        ["Bloodlust"] = 3
    },
    {
        ["Bite"] = 1,
        ["Shadow Trade"] = 2,
        ["Putrid Odor"] = 2,
        ["Pandemic"] = 1,
        ["Plagued Touch"] = 1,
        ["Mushroom Growth"] = 1,
        ["Pollute"] = 1,
        ["Disable"] = 2
    },
    {["KipAttack11"] = 1},
    "function: 0x00000000eea26525",
    {["Swing Blade"] = 2},
    {["Swing Blade"] = 2},
    {["Ember"] = 4, ["Burning Pledge"] = 1, ["Waelyn's Penance"] = 2},
    {["Scimitar"] = 4, ["Stun Baton"] = 1},
    {["Smuggled Gun"] = 1, ["Smuggled Shotgun"] = 1, ["Smuggled Rifle"] = 1},
    {["Dissonant Reverberation"] = 1},
    "function: 0x000000003ae63b85",
    {
        ["Tranquilizer"] = 2,
        ["Exploding Arrow"] = 1,
        ["Bow and Arrow"] = 3,
        ["Ice Bow"] = 3,
        ["Wind Powered"] = 5,
        ["Ramparts"] = 2,
        ["Cold Shoulder"] = 2,
        ["Yew Longbow"] = 2,
        ["High Cognition"] = 2,
        ["Blue Elixir"] = 3,
        ["Bear Trap Collection"] = 1,
        ["Arcovian Resilience"] = 1
    },
    {
        ["Avalanche"] = 2,
        ["Glacial Imprisonment"] = 1,
        ["Sub-Zero Swing"] = 2,
        ["Command"] = 2,
        ["Mattan's Respite"] = 3,
        ["Thaw-maturgy"] = 2,
        ["Arcovian Resilience"] = 3
    },
    {["Ram"] = 1},
    {["Blunder"] = 1},
    {
        ["Attack Buff"] = 1,
        ["Burning Pledge"] = 1,
        ["Shadow Trade"] = 1,
        ["Vampiric Brew"] = 1,
        ["Vampire's Claw"] = 3,
        ["Attack Debuff"] = 1,
        ["Vampiric Mindflay"] = 1
    },
    {["KipAttack10"] = 2},
    {["Wind Powered"] = 2, ["Snowball Throw"] = 5, ["SFOTH Ice Dagger"] = 1, ["Snowball"] = 8, ["Hot Cocoa"] = 2},
    {
        ["Prismacite Blade"] = 2,
        ["Healing Prismacite"] = 1,
        ["Unstable Power"] = 1,
        ["Astral Blessing"] = 3,
        ["Astral Blast"] = 5,
        ["Astral Bastion"] = 2,
        ["Astral Projection"] = 2,
        ["Unstable Charge"] = 2
    },
    {["Jab Combo"] = 2, ["KipAttack13"] = 5, ["Boxer's Rushdown"] = 1, ["Uppercut"] = 2, ["The Ole' One-Two"] = 3},
    {
        ["Psychic Wave"] = 2,
        ["Shield Bash"] = 2,
        ["Axe Slash"] = 1,
        ["Haste"] = 1,
        ["Vampiric Goblet"] = 2,
        ["Command"] = 2,
        ["Lantern Throw"] = 3,
        ["Silver Blade"] = 5,
        ["Short Sword"] = 2,
        ["Hunter's Mark"] = 3,
        ["Bardiche Chop"] = 2,
        ["Purge"] = 1,
        ["Chain Link"] = 1
    },
    {},
    {
        ["Crustum's Pie Throw"] = 15,
        ["Pumpkin Collection"] = 1,
        ["Box Jester Swarm"] = 1,
        ["Final Joke"] = 1,
        ["P I E   T I M E"] = 3,
        ["Mass Warp"] = 5
    },
    {
        ["Ember"] = 4,
        ["Inferno Blast"] = 3,
        ["Eternal Flame"] = 3,
        ["Soothing Flame"] = 2,
        ["Heat Relief"] = 2,
        ["Ignite"] = 3,
        ["Inferno Wand"] = 2,
        ["Infernal Blast"] = 2,
        ["Firestarter"] = 2
    },
    {
        ["Dynamite Toss"] = 2,
        ["Putrid Odor"] = 2,
        ["Smack"] = 1,
        ["Bite"] = 1,
        ["Corroded Arrow"] = 3,
        ["Scratch"] = 1,
        ["Shadow Trade"] = 1,
        ["Bow Smack"] = 2
    },
    {["Poisonous Vial"] = 3},
    {["Blaze Rune"] = 2, ["Scrapyard"] = 1, ["Dynamite"] = 1, ["Cursed Rune"] = 2},
    {
        ["Stupify"] = 1,
        ["Smokescreen"] = 2,
        ["Blinding Flash"] = 2,
        ["Core Infliction"] = 2,
        ["Book of Lore"] = 1,
        ["Hellfire"] = 1,
        ["Eternal Flame"] = 1,
        ["Zoink"] = 2
    },
    "function: 0x00000000c8bd50fd",
    {["Arcane Barrage"] = 1},
    "function: 0x000000009fe8ccad",
    {["Flop"] = 20},
    {
        ["Putrid Odor"] = 2,
        ["Old Flintlock"] = 2,
        ["Swashbuckler's Brew"] = 1,
        ["Corroded Cutlass"] = 3,
        ["Guillotine"] = 1,
        ["Shadow Trade"] = 2
    },
    {["KipAttack2"] = 20},
    {["Blunder"] = 1},
    {["Blunder"] = 1},
    {
        ["Zombie Resilience"] = 3,
        ["Putrid Odor"] = 3,
        ["Bite"] = 2,
        ["Shadow Trade"] = 3,
        ["Scratch"] = 2,
        ["Corroded Sword and Buckler"] = 4,
        ["Grave Rave"] = 3,
        ["Zombie Rally"] = 1,
        ["Wild Roar"] = 2
    },
    {["Toxic Secretion"] = 1},
    {["Blunder"] = 1},
    {["KipAttack18"] = 2, ["Lu Cian"] = 1},
    {
        ["Toe Stab"] = 2,
        ["Arctic Assault"] = 4,
        ["Ice Bow"] = 3,
        ["Cold Mark"] = 1,
        ["Ice Axe"] = 4,
        ["Yew Longbow"] = 2,
        ["Command"] = 2,
        ["Iced Rapier"] = 3,
        ["Retiarice Thrust"] = 2,
        ["Arcovian Resilience"] = 3
    },
    {["KipAttack16"] = 1},
    {["KipAttack15"] = 1},
    {["KipEffect3"] = 1},
    {["KipAttack14"] = 1},
    {["KipAttack12"] = 1},
    {["FieldKip"] = 1},
    {["KipAttack9"] = 7},
    {
        ["Arcane Blast"] = 3,
        ["Snowball"] = 3,
        ["Lightning Bolt"] = 2,
        ["Wind Powered"] = 5,
        ["Cold Shoulder"] = 2,
        ["Zoink"] = 2,
        ["Winds of Regeneration"] = 2,
        ["Enlighten"] = 3,
        ["Icy Horn"] = 1,
        ["Arcovian Resilience"] = 1
    },
    {["KipAttack8"] = 7},
    {["Blue Elixir"] = 1, ["Backhand Smack"] = 1, ["Pumpkin Bomb"] = 1, ["Smack"] = 1},
    {["KipEffect6"] = 3},
    "function: 0x0000000010a0fd7d",
    {["KipHeal"] = 10},
    {["KipAttack4"] = 1},
    {},
    "function: 0x00000000fbbc887d",
    {},
    "function: 0x00000000498a21cd",
    {
        ["Wooden Sword"] = 4,
        ["Shield Bash"] = 4,
        ["Disarm"] = 3,
        ["Darksteel Longblade"] = 1,
        ["Aurite Shield"] = 1,
        ["Ramparts"] = 2,
        ["Protectorate"] = 4,
        ["Iron Shield"] = 4,
        ["Uppercut"] = 4,
        ["Wooden Club Slam"] = 4,
        ["Rock Smash"] = 4,
        ["Iron Broadsword"] = 4
    },
    {
        ["Classic Brigand Sword"] = 1,
        ["SFOTH Venomshank"] = 1,
        ["SFOTH Windforce"] = 1,
        ["SFOTH Firebrand"] = 1,
        ["SFOTH Ghostwalker"] = 1,
        ["SFOTH Illumina"] = 1,
        ["SFOTH Darkheart"] = 1,
        ["Classic Linked Sword"] = 1
    },
    {["SFOTH Venomshank"] = 3},
    {["SFOTH Darkheart"] = 3},
    {["Rune Scimitar"] = 7, ["Chomp"] = 20, ["Fatal Chomp"] = 2},
    "function: 0x00000000c6713345",
    {["Ember"] = 3, ["Ignite"] = 2},
    {["Scimitar"] = 3, ["Wooden Sword"] = 2, ["The Ole' One-Two"] = 1},
    {},
    "function: 0x00000000001c8965",
    {["Obscure"] = 1},
    {
        ["Wind Powered"] = 2,
        ["Brutalize"] = 3,
        ["Reckless Frenzy"] = 5,
        ["Berserker's Axe"] = 2,
        ["Arcovian Resilience"] = 1
    },
    {},
    {},
    {["Piercing Gaze"] = 1, ["Single Out"] = 1, ["Foresight"] = 5, ["Seeking Stare"] = 4},
    {["Masquerade"] = 1, ["Soul Missile"] = 5, ["Summon Pie"] = 1, ["Pollute"] = 1},
    {["Cursed Spot"] = 1, ["Soul Missile"] = 2, ["Scratch"] = 3, ["Pollute"] = 2},
    "function: 0x0000000092841265",
    {
        ["Flamewarden's Guardianship"] = 3,
        ["Burning Pledge"] = 3,
        ["Zealot's Scripture"] = 2,
        ["Harness the Eternal"] = 3,
        ["Flamewarden's Sabre"] = 2,
        ["Share the Eternal"] = 3
    },
    {
        ["Dark Claw"] = 1,
        ["Attack Buff"] = 1,
        ["Corrupt"] = 1,
        ["Uppercut"] = 3,
        ["Spin Sword"] = 3,
        ["Graveyard"] = 1,
        ["Earthshatter"] = 2
    },
    {
        ["Guided Strike"] = 1,
        ["Earthquake"] = 1,
        ["Yew Longbow"] = 2,
        ["Darksteel Longblade"] = 1,
        ["Bear Trap"] = 2,
        ["Iron Shield"] = 2
    },
    {
        ["Lantern Throw"] = 2,
        ["Short Sword"] = 2,
        ["Hunter's Mark"] = 1,
        ["Purge"] = 1,
        ["Chain Link"] = 1,
        ["Rapier Thrust"] = 3
    },
    {
        ["Defense Debuff"] = 2,
        ["Attack Buff"] = 2,
        ["Soul Missile"] = 1,
        ["Backhand Smack"] = 3,
        ["Cursed Spot"] = 2,
        ["Pollute"] = 2
    },
    {
        ["Horn of the Unicorn"] = 1,
        ["Divine Grace"] = 2,
        ["Wand Heal"] = 2,
        ["Winds of Regeneration"] = 1,
        ["Huge Blessing"] = 1,
        ["Small Blessing"] = 2
    },
    {["Air Raid"] = 1},
    "function: 0x0000000054152045",
    {
        ["Bloodline Swarm"] = 1,
        ["Burning Pledge"] = 1,
        ["Vampire's Claw"] = 2,
        ["High Cognition"] = 2,
        ["Exsanguinate"] = 1,
        ["Vampiric Goblet"] = 1
    },
    {},
    "function: 0x00000000789e246d",
    {
        ["Defense Debuff"] = 1,
        ["Attack Buff"] = 1,
        ["Armor Breaker"] = 1,
        ["Wand Heal"] = 1,
        ["Wand Zap"] = 1,
        ["Defense Buff"] = 1,
        ["Attack Debuff"] = 1
    },
    {
        ["Arcane Blast"] = 1,
        ["Conjure Arcane Energy"] = 2,
        ["Zealot's Manuscript"] = 2,
        ["Arcane Barrage"] = 1,
        ["Coffee"] = 1,
        ["Meditation"] = 2
    },
    {["The Ole' One-Two"] = 1},
    {
        ["Defense Debuff"] = 3,
        ["Attack Buff"] = 3,
        ["Rock Throw"] = 2,
        ["Bow and Arrow"] = 1,
        ["Rock Smash"] = 1,
        ["Toxic Knife"] = 1,
        ["Poison Dagger"] = 2,
        ["Smack"] = 2,
        ["Bear Trap"] = 2,
        ["Uppercut"] = 2,
        ["Wooden Club Slam"] = 2,
        ["Rusty Knife"] = 2,
        ["Pollute"] = 1
    },
    {["Rock Smash"] = 1, ["Scratch"] = 3, ["Pollute"] = 2},
    {["Warping Wail"] = 4, ["Earthquake"] = 1, ["Earthshatter"] = 1},
    {["Obscure"] = 1},
    {["Woozy Whirl"] = 1},
    {["Snowball Throw"] = 4, ["Defense Buff"] = 1, ["Small Blessing"] = 1},
    {["Smack"] = 1, ["Scratch"] = 1},
    "function: 0x00000000a466ce4d",
    {
        ["Foul Breath"] = 1,
        ["Shadow Trade"] = 2,
        ["Unnatural Regeneration"] = 1,
        ["Radiant Indemnity"] = 1,
        ["Scratch"] = 1,
        ["Soul Missile"] = 1,
        ["Rotten Claw"] = 1,
        ["Pollute"] = 1
    },
    {["Conversion"] = 1, ["Ramparts"] = 3, ["Psychic Wave"] = 1, ["Vampire's Claw"] = 1, ["Pride of the House"] = 1},
    "function: 0x0000000070ca379d",
    {["Wraith Transform"] = 1, ["Vase Throw"] = 6},
    {["Flop"] = 20},
    "function: 0x000000005cdd4865",
    {["Elemental Blast"] = 1, ["Elemental Surge"] = 3, ["Elemental Swipe"] = 1}
}
