data = {
    ["Normal Face"] = {["BubbleIncrease"] = 0},
    ["Blue Bubble"] = {["BubbleIncrease"] = 645},
    ["Daring Beard"] = {["BubbleIncrease"] = 720},
    ["Crimsonwrath"] = {["BubbleIncrease"] = 6666},
    ["TestFace"] = {["BubbleIncrease"] = 100},
    ["Vampire"] = {["BubbleIncrease"] = 7800},
    ["Finn McCool"] = {["BubbleIncrease"] = 220},
    ["Red Glowing Eyes"] = {["BubbleIncrease"] = 3050},
    ["Stitches"] = {["BubbleIncrease"] = 9000},
    ["Friendly Pirate"] = {["BubbleIncrease"] = 300},
    ["Red Tango"] = {["BubbleIncrease"] = 2260},
    ["Azurewrath"] = {["BubbleIncrease"] = 5250},
    ["Bubble Trouble"] = {["BubbleIncrease"] = 100},
    ["Crimson Evil Eye"] = {["BubbleIncrease"] = 1800},
    ["Evil Skeptic"] = {["BubbleIncrease"] = 3850},
    ["Beast Mode"] = {["BubbleIncrease"] = 4350},
    ["Yum!"] = {["BubbleIncrease"] = 1400},
    ["Emeraldwrath"] = {["BubbleIncrease"] = 4850},
    ["Red Rawr"] = {["BubbleIncrease"] = 3250},
    ["Zombie"] = {["BubbleIncrease"] = 1550},
    ["Scar Face"] = {["BubbleIncrease"] = 1000},
    ["Red Goof"] = {["BubbleIncrease"] = 745},
    ["Green Bubble"] = {["BubbleIncrease"] = 565},
    ["XD"] = {["BubbleIncrease"] = 900}
}
