data = {
    ["DailyColorBoost"] = {
        {["Amount"] = 0.2, ["Type"] = "Luck"},
        {["Amount"] = 0.05, ["Type"] = "Acceleration"},
        {["Amount"] = 0.1, ["Type"] = "Acceleration"},
        {["Amount"] = 0.1, ["Type"] = "Wins"},
        {["Amount"] = 0.2, ["Type"] = "Wins"},
        {["Amount"] = 0.15, ["Type"] = "Acceleration"},
        {["Amount"] = 0.3, ["Type"] = "Wins"},
        {["Amount"] = 0.4, ["Type"] = "Wins"}
    },
    ["UpgradeColors"] = {Color3.fromRGB(255, 200, 0), Color3.fromRGB(255, 0, 0), Color3.fromRGB(255, 255, 255)},
    ["Cars"] = {
        ["Bank Truck"] = {
            ["Acceleration"] = 2.7,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(99, 99, 99),
            ["CarColor"] = Color3.fromRGB(99, 99, 99),
            ["Name"] = "Bank Truck",
            ["Price"] = {["Value"] = 2500000000000, ["Currency"] = "Wins"},
            ["WinMultiplier"] = 18,
            ["Icon"] = "rbxassetid://14070047872",
            ["Passengers"] = 1
        },
        ["Coconut"] = {
            ["Acceleration"] = 4,
            ["Upgrades"] = 1,
            ["NameColor"] = Color3.fromRGB(255, 85, 0),
            ["CarColor"] = Color3.fromRGB(163, 162, 165),
            ["Name"] = "Coconut",
            ["WinMultiplier"] = 52,
            ["IsSeasonPassCar"] = true,
            ["UpgradePrice"] = {["Value"] = 25000000, ["Currency"] = "Wins"},
            ["Icon"] = "rbxassetid://18155814132",
            ["Passengers"] = 0
        },
        ["Snowball"] = {
            ["Acceleration"] = 8.8,
            ["Upgrades"] = 1,
            ["NameColor"] = Color3.fromRGB(187, 255, 250),
            ["CarColor"] = Color3.fromRGB(255, 255, 255),
            ["Name"] = "Snowball",
            ["WinMultiplier"] = 58,
            ["IsSeasonPassCar"] = true,
            ["UpgradePrice"] = {["Value"] = 667000, ["Currency"] = "Wins"},
            ["Icon"] = "rbxassetid://75096547224650",
            ["Passengers"] = 0
        },
        ["Buggy"] = {
            ["Acceleration"] = 0,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(7, 197, 255),
            ["CarColor"] = Color3.fromRGB(9, 137, 207),
            ["Name"] = "Buggy",
            ["WinMultiplier"] = 17,
            ["UpgradePrice"] = {["Value"] = 700000, ["Currency"] = "Event.Currency"},
            ["Icon"] = "rbxassetid://14002612850",
            ["Passengers"] = 1
        },
        ["Speedy Demon"] = {
            ["Acceleration"] = 0,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(212, 0, 212),
            ["CarColor"] = Color3.fromRGB(170, 0, 170),
            ["Name"] = "Speedy Demon",
            ["Price"] = {["Value"] = 1250000000, ["Currency"] = "Wins"},
            ["WinMultiplier"] = 2.6,
            ["Icon"] = "rbxassetid://12081589572",
            ["Passengers"] = 1
        },
        ["School Bus"] = {
            ["Acceleration"] = 2,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(223, 205, 6),
            ["CarColor"] = Color3.fromRGB(230, 233, 57),
            ["Name"] = "School Bus",
            ["WinMultiplier"] = 15,
            ["UpgradePrice"] = {["ProductIds"] = {1587964871, 1587964991}, ["Currency"] = "Robux"},
            ["Icon"] = "rbxassetid://13784770501",
            ["Passengers"] = 10
        },
        ["Velocity GT"] = {
            ["Acceleration"] = 0,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(255, 170, 0),
            ["CarColor"] = Color3.fromRGB(255, 170, 0),
            ["Name"] = "Velocity GT",
            ["WinMultiplier"] = 10,
            ["UpgradePrice"] = {["ProductIds"] = {1556267266, 1556267323}, ["Currency"] = "Robux"},
            ["Icon"] = "rbxassetid://13711935316",
            ["Passengers"] = 1
        },
        ["Space Plow"] = {
            ["WinMultiplier"] = 210,
            ["Acceleration"] = 110,
            ["Name"] = "Space Plow",
            ["Upgrades"] = 0,
            ["NameColor"] = Color3.fromRGB(75, 152, 253),
            ["Passengers"] = 3,
            ["Icon"] = "rbxassetid://114010685610691",
            ["CarColor"] = Color3.fromRGB(75, 152, 253)
        },
        ["Hyper Bike"] = {
            ["Acceleration"] = 0,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(229, 235, 238),
            ["CarColor"] = Color3.fromRGB(159, 161, 172),
            ["Name"] = "Hyper Bike",
            ["Price"] = {["Value"] = 500000, ["Currency"] = "Wins"},
            ["WinMultiplier"] = 1.15,
            ["Icon"] = "rbxassetid://11656289647",
            ["Passengers"] = 0
        },
        ["Clown Caravan"] = {
            ["Acceleration"] = 0,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(255, 200, 0),
            ["CarColor"] = Color3.fromRGB(255, 176, 0),
            ["Name"] = "Clown Caravan",
            ["Price"] = {["Value"] = 25000000000, ["Currency"] = "Wins"},
            ["WinMultiplier"] = 4.5,
            ["Icon"] = "rbxassetid://12679559141",
            ["Passengers"] = 1
        },
        ["Arcade Yacht"] = {
            ["Acceleration"] = 1.9,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(239, 148, 68),
            ["CarColor"] = Color3.fromRGB(248, 248, 248),
            ["Name"] = "Arcade Yacht",
            ["AdjustPets"] = true,
            ["WinMultiplier"] = 20,
            ["UpgradePrice"] = {["Value"] = 1000000, ["Currency"] = "Event.Currency"},
            ["Icon"] = "rbxassetid://14226605332",
            ["Passengers"] = 6
        },
        ["Bike Blaze"] = {
            ["Acceleration"] = 2,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(196, 40, 28),
            ["CarColor"] = Color3.fromRGB(196, 40, 28),
            ["Passengers"] = 0,
            ["Name"] = "Bike Blaze",
            ["WinMultiplier"] = 25,
            ["IsShopEventCar"] = true,
            ["UpgradePrice"] = {["Value"] = 1000000, ["Currency"] = "Event.Currency"},
            ["Icon"] = "rbxassetid://14687585183",
            ["Anime WinsMultiplier"] = 4
        },
        ["Sun"] = {
            ["Acceleration"] = 40,
            ["Upgrades"] = 1,
            ["NameColor"] = Color3.fromRGB(255, 85, 0),
            ["CarColor"] = Color3.fromRGB(163, 162, 165),
            ["Name"] = "Sun",
            ["WinMultiplier"] = 96,
            ["IsSeasonPassCar"] = true,
            ["UpgradePrice"] = {["Value"] = 25000000, ["Currency"] = "Wins"},
            ["Icon"] = "rbxassetid://18155817730",
            ["Passengers"] = 0
        },
        ["Prison Transport"] = {
            ["Acceleration"] = 15.2,
            ["Upgrades"] = 1,
            ["NameColor"] = Color3.fromRGB(255, 57, 57),
            ["CarColor"] = Color3.fromRGB(13, 13, 13),
            ["Name"] = "Prison Transport",
            ["WinMultiplier"] = 60,
            ["Price"] = {["Value"] = 400000000000000000, ["Currency"] = "Wins"},
            ["UpgradePrice"] = {["Value"] = 533500000000000000, ["Currency"] = "Wins"},
            ["Icon"] = "rbxassetid://91105188802334",
            ["Passengers"] = 1
        },
        ["Hay Bayle"] = {
            ["Acceleration"] = 16,
            ["Upgrades"] = 1,
            ["NameColor"] = Color3.fromRGB(255, 170, 0),
            ["CarColor"] = Color3.fromRGB(163, 162, 165),
            ["Name"] = "Hay Bayle",
            ["WinMultiplier"] = 80,
            ["IsSeasonPassCar"] = true,
            ["UpgradePrice"] = {["Value"] = 10000000, ["Currency"] = "Wins"},
            ["Icon"] = "rbxassetid://73250117409116",
            ["Passengers"] = 0
        },
        ["Sunfire Cruiser"] = {
            ["Acceleration"] = 0,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(196, 40, 28),
            ["CarColor"] = Color3.fromRGB(196, 40, 28),
            ["Name"] = "Sunfire Cruiser",
            ["WinMultiplier"] = 15,
            ["UpgradePrice"] = {["Value"] = 700000, ["Currency"] = "Event.Currency"},
            ["Icon"] = "rbxassetid://13917024720",
            ["Passengers"] = 3
        },
        ["Police Truck"] = {
            ["Acceleration"] = 2.4,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(0, 170, 255),
            ["CarColor"] = Color3.fromRGB(0, 170, 255),
            ["Name"] = "Police Truck",
            ["Price"] = {["Value"] = 1000000000000, ["Currency"] = "Wins"},
            ["WinMultiplier"] = 17,
            ["Icon"] = "rbxassetid://14070047696",
            ["Passengers"] = 1
        },
        ["NeoRider"] = {
            ["Acceleration"] = 2.5,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(226, 79, 11),
            ["CarColor"] = Color3.fromRGB(226, 79, 11),
            ["Name"] = "NeoRider",
            ["WinMultiplier"] = 25,
            ["UpgradePrice"] = {["Value"] = 3500000, ["Currency"] = "Event.Currency"},
            ["Icon"] = "rbxassetid://14853807369",
            ["Passengers"] = 1
        },
        ["Minecart"] = {
            ["Acceleration"] = 8.8,
            ["Upgrades"] = 1,
            ["NameColor"] = Color3.fromRGB(255, 170, 0),
            ["CarColor"] = Color3.fromRGB(126, 126, 126),
            ["Name"] = "Minecart",
            ["WinMultiplier"] = 46,
            ["Price"] = {["Value"] = 100000000000000000, ["Currency"] = "Wins"},
            ["UpgradePrice"] = {["Value"] = 200000000000000000, ["Currency"] = "Wins"},
            ["Icon"] = "rbxassetid://17788053994",
            ["Passengers"] = 0
        },
        ["Dolphin"] = {
            ["Acceleration"] = 4,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(32, 170, 255),
            ["CarColor"] = Color3.fromRGB(72, 90, 106),
            ["Name"] = "Dolphin Rider",
            ["Price"] = {["Value"] = 1000000000000000, ["Currency"] = "Wins"},
            ["WinMultiplier"] = 31,
            ["UpgradePrice"] = {["Value"] = 1000000000000000, ["Currency"] = "Wins"},
            ["Icon"] = "rbxassetid://15125248253",
            ["Passengers"] = 2
        },
        ["AeroSonic"] = {
            ["Acceleration"] = 0,
            ["Upgrades"] = 1,
            ["NameColor"] = Color3.fromRGB(170, 0, 0),
            ["CarColor"] = Color3.fromRGB(170, 0, 0),
            ["Name"] = "AeroSonic",
            ["WinMultiplier"] = 2,
            ["UpgradePrice"] = {["ProductIds"] = {1548584386, 1548584465}, ["Currency"] = "Robux"},
            ["Icon"] = "rbxassetid://13534548544",
            ["Passengers"] = 1
        },
        ["Semi Truck"] = {
            ["IsInSpinWheel"] = true,
            ["Acceleration"] = 75,
            ["Upgrades"] = 0,
            ["NameColor"] = Color3.fromRGB(253, 96, 96),
            ["CarColor"] = Color3.fromRGB(253, 96, 96),
            ["Name"] = "Semi Truck",
            ["WinMultiplier"] = 180,
            ["Priority"] = true,
            ["Icon"] = "rbxassetid://73354230168957",
            ["Passengers"] = 1
        },
        ["Cyborg Racer"] = {
            ["Acceleration"] = 0,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(197, 206, 229),
            ["CarColor"] = Color3.fromRGB(99, 95, 98),
            ["Name"] = "Cyborg Racer",
            ["Price"] = {["Value"] = 7500000000, ["Currency"] = "Wins"},
            ["WinMultiplier"] = 3.5,
            ["Icon"] = "rbxassetid://12250701313",
            ["Passengers"] = 1
        },
        ["Leaf"] = {
            ["Acceleration"] = 8,
            ["Upgrades"] = 1,
            ["NameColor"] = Color3.fromRGB(255, 170, 0),
            ["CarColor"] = Color3.fromRGB(163, 162, 165),
            ["Name"] = "Leaf",
            ["WinMultiplier"] = 56,
            ["IsSeasonPassCar"] = true,
            ["UpgradePrice"] = {["Value"] = 1000000, ["Currency"] = "Wins"},
            ["Icon"] = "rbxassetid://87055557410902",
            ["Passengers"] = 0
        },
        ["Twilight Truck"] = {
            ["WinMultiplier"] = 25,
            ["Acceleration"] = 5,
            ["Name"] = "Twilight Truck",
            ["Upgrades"] = 0,
            ["NameColor"] = Color3.fromRGB(255, 57, 57),
            ["Passengers"] = 1,
            ["Icon"] = "rbxassetid://89660062014876",
            ["CarColor"] = Color3.fromRGB(165, 47, 59)
        },
        ["Emoji"] = {
            ["Acceleration"] = 12,
            ["Upgrades"] = 1,
            ["NameColor"] = Color3.fromRGB(255, 170, 0),
            ["CarColor"] = Color3.fromRGB(126, 126, 126),
            ["Name"] = "Emoji",
            ["WinMultiplier"] = 32,
            ["UpgradePrice"] = {["Value"] = 100000000, ["Currency"] = "Wins"},
            ["Icon"] = "rbxassetid://18987587933",
            ["Passengers"] = 0
        },
        ["Bike"] = {
            ["WinMultiplier"] = 0.5,
            ["Acceleration"] = 0.15,
            ["Name"] = "Bike",
            ["Upgrades"] = 0,
            ["NameColor"] = Color3.fromRGB(253, 96, 96),
            ["Passengers"] = 0,
            ["Icon"] = "rbxassetid://94310964995843",
            ["CarColor"] = Color3.fromRGB(253, 96, 96)
        },
        ["Kurama"] = {
            ["Acceleration"] = 3,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(170, 85, 0),
            ["CarColor"] = Color3.fromRGB(170, 85, 0),
            ["Name"] = "Eleven-Tailed Wolf",
            ["YOffset"] = {-3.5, -3.5, -0.75},
            ["WinMultiplier"] = 45,
            ["UpgradePrice"] = {["ProductIds"] = {1650313984, 1650314036}, ["Currency"] = "Robux"},
            ["Icon"] = "rbxassetid://14853773915",
            ["Passengers"] = 0
        },
        ["Future Racer"] = {
            ["Acceleration"] = 0.1,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(196, 204, 209),
            ["CarColor"] = Color3.fromRGB(159, 161, 172),
            ["Name"] = "Future Racer",
            ["Price"] = {["Value"] = 500000000, ["Currency"] = "Wins"},
            ["WinMultiplier"] = 2.05,
            ["Icon"] = "rbxassetid://11719912430",
            ["Passengers"] = 1
        },
        ["Christmas Tree"] = {
            ["Acceleration"] = 64,
            ["Upgrades"] = 1,
            ["NameColor"] = Color3.fromRGB(135, 255, 126),
            ["CarColor"] = Color3.fromRGB(115, 203, 96),
            ["Name"] = "Christmas Tree",
            ["WinMultiplier"] = 128,
            ["IsSeasonPassCar"] = true,
            ["UpgradePrice"] = {["Value"] = 667000000000, ["Currency"] = "Wins"},
            ["Icon"] = "rbxassetid://118611071258528",
            ["Passengers"] = 0
        },
        ["VIP Car"] = {
            ["Acceleration"] = 0,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(239, 184, 56),
            ["Untradeable"] = true,
            ["CarColor"] = Color3.fromRGB(239, 184, 56),
            ["Name"] = "VIP Car",
            ["WinMultiplier"] = 2.5,
            ["Price"] = {["Value"] = 300, ["Currency"] = "Robux", ["GamepassId"] = 75873430},
            ["UpgradePrice"] = {["ProductIds"] = {1555210902, 1555210973}, ["Currency"] = "Robux"},
            ["Icon"] = "rbxassetid://13690863079",
            ["Passengers"] = 1
        },
        ["Winter Train"] = {
            ["Acceleration"] = 80,
            ["Upgrades"] = 1,
            ["NameColor"] = Color3.fromRGB(135, 255, 126),
            ["CarColor"] = Color3.fromRGB(115, 203, 96),
            ["YOffset"] = 1.5,
            ["Priority"] = true,
            ["Name"] = "Winter Train",
            ["WinMultiplier"] = 160,
            ["IsSeasonSpinCar"] = true,
            ["UpgradePrice"] = {["Value"] = 667000000000, ["Currency"] = "Wins"},
            ["Icon"] = "rbxassetid://93546683956029",
            ["Passengers"] = 0
        },
        ["Scooter"] = {
            ["Acceleration"] = 0,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(28, 232, 177),
            ["CarColor"] = Color3.fromRGB(75, 151, 75),
            ["Name"] = "Scooter",
            ["Price"] = {["Value"] = 20000, ["Currency"] = "Wins"},
            ["WinMultiplier"] = 0.65,
            ["Icon"] = "rbxassetid://11780139423",
            ["Passengers"] = 0
        },
        ["Broomstick"] = {
            ["Candy CornMultiplier"] = 10.4,
            ["Acceleration"] = 12,
            ["Upgrades"] = 1,
            ["NameColor"] = Color3.fromRGB(170, 85, 255),
            ["CarColor"] = Color3.fromRGB(126, 126, 126),
            ["Name"] = "Broomstick",
            ["WinMultiplier"] = 52,
            ["IsShopEventCar"] = true,
            ["UpgradePrice"] = {["Value"] = 55000000, ["Currency"] = "Event.Currency"},
            ["Icon"] = "rbxassetid://119507640421418",
            ["Passengers"] = 0
        },
        ["Radiation Racer"] = {
            ["Acceleration"] = 0,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(245, 247, 51),
            ["CarColor"] = Color3.fromRGB(255, 255, 0),
            ["Name"] = "Radiation Racer",
            ["Price"] = {["Value"] = 45000000000, ["Currency"] = "Wins"},
            ["WinMultiplier"] = 5,
            ["Icon"] = "rbxassetid://12976398446",
            ["Passengers"] = 1
        },
        ["Pumpkin Car"] = {
            ["Acceleration"] = 5,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(255, 85, 0),
            ["Spooky WinsMultiplier"] = 15,
            ["CarColor"] = Color3.fromRGB(255, 85, 0),
            ["AdjustPets"] = true,
            ["Name"] = "Pumpkin Car",
            ["WinMultiplier"] = 30,
            ["IsShopEventCar"] = true,
            ["UpgradePrice"] = {["Value"] = 500000, ["Currency"] = "Event.Currency"},
            ["Icon"] = "rbxassetid://15072611335",
            ["Passengers"] = 0
        },
        ["Thunderstrike"] = {
            ["Acceleration"] = 0,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(163, 162, 165),
            ["CarColor"] = Color3.fromRGB(163, 162, 165),
            ["Name"] = "Thunderstrike",
            ["WinMultiplier"] = 20,
            ["UpgradePrice"] = {["ProductIds"] = {1548584298, 1548584331}, ["Currency"] = "Robux"},
            ["Icon"] = "rbxassetid://13534548338",
            ["Passengers"] = 1
        },
        ["AtlantisRacer"] = {
            ["Acceleration"] = 5,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(255, 42, 46),
            ["YOffset"] = -5,
            ["CarColor"] = Color3.fromRGB(165, 47, 59),
            ["PostYOffset"] = -6,
            ["Priority"] = true,
            ["Name"] = "Atlantis Racer",
            ["Price"] = {["Value"] = 1299, ["Currency"] = "Robux", ["ProductId"] = 1672579256},
            ["WinMultiplier"] = 57,
            ["UpgradePrice"] = {["ProductIds"] = {1675115468, 1675115519}, ["Currency"] = "Robux"},
            ["Icon"] = "rbxassetid://15125982241",
            ["Passengers"] = 20
        },
        ["Shark"] = {
            ["Acceleration"] = 6,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(0, 255, 255),
            ["CarColor"] = Color3.fromRGB(78, 131, 255),
            ["Name"] = "Shark",
            ["Price"] = {["Value"] = 10000000000000000, ["Currency"] = "Wins"},
            ["WinMultiplier"] = 37,
            ["UpgradePrice"] = {["Value"] = 15000000000000000, ["Currency"] = "Wins"},
            ["Icon"] = "rbxassetid://16497990891",
            ["Passengers"] = 2
        },
        ["OceanExplorer"] = {
            ["Acceleration"] = 5,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(255, 42, 46),
            ["CarColor"] = Color3.fromRGB(165, 47, 59),
            ["Name"] = "Ocean Explorer",
            ["Price"] = {["Value"] = 5000000000000000, ["Currency"] = "Wins"},
            ["WinMultiplier"] = 34,
            ["Icon"] = "rbxassetid://15125259149",
            ["Passengers"] = 2
        },
        ["Spooky Car"] = {
            ["Acceleration"] = 2.5,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(255, 85, 0),
            ["Spooky WinsMultiplier"] = 5,
            ["CarColor"] = Color3.fromRGB(255, 85, 0),
            ["AdjustPets"] = true,
            ["Name"] = "Spooky Car",
            ["WinMultiplier"] = 32,
            ["IsShopEventCar"] = true,
            ["UpgradePrice"] = {["Value"] = 1000000, ["Currency"] = "Event.Currency"},
            ["Icon"] = "rbxassetid://15072620310",
            ["Passengers"] = 1
        },
        ["Private Jet"] = {
            ["Acceleration"] = 5,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(248, 248, 248),
            ["CarColor"] = Color3.fromRGB(229, 0, 0),
            ["Name"] = "Private Jet",
            ["YOffset"] = 6,
            ["WinMultiplier"] = 33,
            ["UpgradePrice"] = {["ProductIds"] = {1630397727, 1630397815}, ["Currency"] = "Robux"},
            ["Icon"] = "rbxassetid://14365035130",
            ["Passengers"] = 8
        },
        ["IceSloth"] = {
            ["Acceleration"] = 2.5,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(75, 255, 189),
            ["CarColor"] = Color3.fromRGB(13, 165, 89),
            ["Name"] = "Ice Sloth",
            ["Price"] = {["Value"] = 500000000000000, ["Currency"] = "Wins"},
            ["WinMultiplier"] = 28,
            ["UpgradePrice"] = {["Value"] = 500000000000000, ["Currency"] = "Wins"},
            ["Icon"] = "rbxassetid://15123762200",
            ["Passengers"] = 0
        },
        ["AquaWaveExpress"] = {
            ["Acceleration"] = 2,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(67, 174, 255),
            ["CarColor"] = Color3.fromRGB(37, 189, 203),
            ["Name"] = "AquaWave Express",
            ["Price"] = {["Value"] = 100000000000000, ["Currency"] = "Wins"},
            ["WinMultiplier"] = 25,
            ["UpgradePrice"] = {["Value"] = 100000000000000, ["Currency"] = "Wins"},
            ["Icon"] = "rbxassetid://15123745386",
            ["Passengers"] = 0
        },
        ["Turbo Racer"] = {
            ["Acceleration"] = 0,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(0, 255, 255),
            ["CarColor"] = Color3.fromRGB(0, 255, 255),
            ["Name"] = "Turbo Racer",
            ["WinMultiplier"] = 7,
            ["UpgradePrice"] = {["ProductIds"] = {1556267540, 1556267580}, ["Currency"] = "Robux"},
            ["Icon"] = "rbxassetid://13711932482",
            ["Passengers"] = 1
        },
        ["Mammoth"] = {
            ["Acceleration"] = 4,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(118, 79, 47),
            ["CarColor"] = Color3.fromRGB(105, 64, 40),
            ["Name"] = "Mammoth",
            ["Passengers"] = 2,
            ["WinMultiplier"] = 30,
            ["UpgradePrice"] = {["Value"] = 5000000, ["Currency"] = "Event.Currency"},
            ["Icon"] = "rbxassetid://14989205724",
            ["Anime WinsMultiplier"] = 10
        },
        ["Skeleton"] = {
            ["Acceleration"] = 7,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(255, 85, 0),
            ["Spooky WinsMultiplier"] = 10,
            ["CarColor"] = Color3.fromRGB(255, 85, 0),
            ["AdjustPets"] = true,
            ["Name"] = "Skeleton",
            ["WinMultiplier"] = 40,
            ["IsShopEventCar"] = true,
            ["UpgradePrice"] = {["Value"] = 5000000, ["Currency"] = "Event.Currency"},
            ["Icon"] = "rbxassetid://15271968834",
            ["Passengers"] = 0
        },
        ["Neo Velocity"] = {
            ["Acceleration"] = 2,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(237, 234, 234),
            ["CarColor"] = Color3.fromRGB(237, 234, 234),
            ["Name"] = "Neo Velocity",
            ["WinMultiplier"] = 27,
            ["UpgradePrice"] = {["ProductIds"] = {1631972419, 1631972487}, ["Currency"] = "Robux"},
            ["Icon"] = "rbxassetid://14651880271",
            ["Passengers"] = 3
        },
        ["Speedboat"] = {
            ["Acceleration"] = 2.5,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(237, 234, 234),
            ["CarColor"] = Color3.fromRGB(237, 234, 234),
            ["Name"] = "Speedboat",
            ["WinMultiplier"] = 17,
            ["UpgradePrice"] = {["ProductIds"] = {1569888036, 1569888071}, ["Currency"] = "Robux"},
            ["Icon"] = "rbxassetid://13907129948",
            ["Passengers"] = 2
        },
        ["Speed Blast"] = {
            ["Acceleration"] = 1,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(239, 184, 56),
            ["CarColor"] = Color3.fromRGB(239, 184, 56),
            ["Name"] = "Speed Blast",
            ["WinMultiplier"] = 7,
            ["UpgradePrice"] = {["ProductIds"] = {1568885629, 1568885754}, ["Currency"] = "Robux"},
            ["Icon"] = "rbxassetid://14001420564",
            ["Passengers"] = 1
        },
        ["Boia Kart"] = {
            ["Acceleration"] = 0,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(85, 170, 255),
            ["CarColor"] = Color3.fromRGB(85, 170, 255),
            ["Name"] = "Boia Kart",
            ["Price"] = {["Value"] = 250000000000, ["Currency"] = "Wins"},
            ["WinMultiplier"] = 10,
            ["Icon"] = "rbxassetid://13641733238",
            ["Passengers"] = 1
        },
        ["Anniversary Car"] = {
            ["Acceleration"] = 3,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(255, 89, 172),
            ["CarColor"] = Color3.fromRGB(248, 248, 248),
            ["Birthday WinsMultiplier"] = 4,
            ["Name"] = "Anniversary Car",
            ["WinMultiplier"] = 21,
            ["IsShopEventCar"] = true,
            ["UpgradePrice"] = {["Value"] = 1000000, ["Currency"] = "Event.Currency"},
            ["Icon"] = "rbxassetid://14447734969",
            ["Passengers"] = 1
        },
        ["Castle Chariot"] = {
            ["Acceleration"] = 0,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(196, 205, 213),
            ["CarColor"] = Color3.fromRGB(137, 136, 139),
            ["AdjustPets"] = true,
            ["Name"] = "Castle Chariot",
            ["WinMultiplier"] = 3,
            ["Price"] = {["Value"] = 3000000000, ["Currency"] = "Wins"},
            ["CameraOffset"] = Vector3.new(0, 2, -4),
            ["Icon"] = "rbxassetid://12151344305",
            ["Passengers"] = 2
        },
        ["Ambulance"] = {
            ["Acceleration"] = 0,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(255, 73, 73),
            ["CarColor"] = Color3.fromRGB(202, 203, 209),
            ["Name"] = "Ambulance",
            ["WinMultiplier"] = 9.25,
            ["UpgradePrice"] = {["Value"] = 125000000000, ["Currency"] = "Wins"},
            ["Icon"] = "rbxassetid://13546353450",
            ["Passengers"] = 1
        },
        ["Flower"] = {
            ["Acceleration"] = 8,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(0, 170, 127),
            ["Flower WinsMultiplier"] = 10,
            ["CarColor"] = Color3.fromRGB(0, 170, 127),
            ["AdjustPets"] = true,
            ["Name"] = "Flower",
            ["WinMultiplier"] = 45,
            ["IsShopEventCar"] = true,
            ["UpgradePrice"] = {["Value"] = 10000000, ["Currency"] = "Event.Currency"},
            ["Icon"] = "rbxassetid://16591802357",
            ["Passengers"] = 0
        },
        ["Arcade Car"] = {
            ["Acceleration"] = 2.5,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(239, 148, 68),
            ["CarColor"] = Color3.fromRGB(248, 248, 248),
            ["Name"] = "Arcade Car",
            ["WinMultiplier"] = 22.5,
            ["UpgradePrice"] = {["ProductIds"] = {1612547064, 1612547136}, ["Currency"] = "Robux"},
            ["Icon"] = "rbxassetid://14318916123",
            ["Passengers"] = 7
        },
        ["RacerX"] = {
            ["Acceleration"] = 1.5,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(232, 222, 26),
            ["CarColor"] = Color3.fromRGB(232, 222, 26),
            ["Name"] = "RacerX",
            ["WinMultiplier"] = 15,
            ["UpgradePrice"] = {["Value"] = 500000, ["Currency"] = "Event.Currency"},
            ["Icon"] = "rbxassetid://13917025395",
            ["Passengers"] = 1
        },
        ["Snow Mobile"] = {
            ["Acceleration"] = 0,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(12, 238, 235),
            ["CarColor"] = Color3.fromRGB(9, 137, 207),
            ["Name"] = "Snow Mobile",
            ["WinMultiplier"] = 2.25,
            ["UpgradePrice"] = {["Value"] = 2000000000, ["Currency"] = "Wins"},
            ["Icon"] = "rbxassetid://11837664492",
            ["Passengers"] = 0
        },
        ["Jetski"] = {
            ["Acceleration"] = 0,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(0, 170, 255),
            ["CarColor"] = Color3.fromRGB(0, 170, 255),
            ["Name"] = "Jetski",
            ["WinMultiplier"] = 6.5,
            ["UpgradePrice"] = {["Value"] = 80000000000, ["Currency"] = "Wins"},
            ["Icon"] = "rbxassetid://13513184768",
            ["Passengers"] = 1
        },
        ["Poop"] = {
            ["Emoji WinsMultiplier"] = 10.8,
            ["Acceleration"] = 9.6,
            ["Upgrades"] = 1,
            ["NameColor"] = Color3.fromRGB(255, 170, 0),
            ["CarColor"] = Color3.fromRGB(126, 126, 126),
            ["Name"] = "Poop",
            ["WinMultiplier"] = 48,
            ["IsShopEventCar"] = true,
            ["UpgradePrice"] = {["Value"] = 75000000, ["Currency"] = "Event.Currency"},
            ["Icon"] = "rbxassetid://18996366030",
            ["Passengers"] = 0
        },
        ["Banana Boat"] = {
            ["Acceleration"] = 0,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(255, 255, 0),
            ["CarColor"] = Color3.fromRGB(255, 255, 0),
            ["Name"] = "Banana Boat",
            ["WinMultiplier"] = 8.5,
            ["UpgradePrice"] = {["Value"] = 100000000000, ["Currency"] = "Wins"},
            ["Icon"] = "rbxassetid://13633617698",
            ["Passengers"] = 3
        },
        ["Smooth Rider"] = {
            ["Acceleration"] = 0,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(238, 239, 40),
            ["CarColor"] = Color3.fromRGB(255, 255, 0),
            ["Name"] = "Smooth Rider",
            ["Price"] = {["Value"] = 6000000, ["Currency"] = "Wins"},
            ["WinMultiplier"] = 1.55,
            ["Icon"] = "rbxassetid://11656301452",
            ["Passengers"] = 0
        },
        ["Santa's Sleigh"] = {
            ["Acceleration"] = 0.25,
            ["Upgrades"] = 0,
            ["NameColor"] = Color3.fromRGB(248, 47, 47),
            ["CarColor"] = Color3.fromRGB(255, 0, 0),
            ["AdjustPets"] = true,
            ["PresentsMultiplier"] = 2,
            ["Name"] = "Santa's Sleigh",
            ["WinMultiplier"] = 4,
            ["Passengers"] = 4,
            ["CameraOffset"] = Vector3.new(0, 0, 4),
            ["Icon"] = "rbxassetid://11837666897",
            ["ExpiresAt"] = 1672506000
        },
        ["Skateboard"] = {
            ["Acceleration"] = 0,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(140, 171, 204),
            ["CarColor"] = Color3.fromRGB(170, 85, 0),
            ["Name"] = "Skateboard",
            ["Price"] = {["Value"] = 750, ["Currency"] = "Wins"},
            ["WinMultiplier"] = 0.35,
            ["Icon"] = "rbxassetid://11780149392",
            ["Passengers"] = 0
        },
        ["Christmas Rider"] = {
            ["Acceleration"] = 0,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(94, 236, 111),
            ["CarColor"] = Color3.fromRGB(31, 128, 29),
            ["Name"] = "Christmas Rider",
            ["WinMultiplier"] = 2.5,
            ["UpgradePrice"] = {["Value"] = 137500, ["Currency"] = "Event.Currency"},
            ["Icon"] = "rbxassetid://11908186018",
            ["Passengers"] = 1
        },
        ["Eggspress Speeder"] = {
            ["Acceleration"] = 0,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(248, 217, 109),
            ["CarColor"] = Color3.fromRGB(248, 217, 109),
            ["Name"] = "Eggspress Speeder",
            ["WinMultiplier"] = 5.5,
            ["UpgradePrice"] = {["Value"] = 75000000000, ["Currency"] = "Wins"},
            ["Icon"] = "rbxassetid://13159303280",
            ["Passengers"] = 1
        },
        ["Grim's Car"] = {
            ["WinMultiplier"] = 1,
            ["Acceleration"] = 0,
            ["Name"] = "Grim's Car",
            ["Upgrades"] = 0,
            ["NameColor"] = Color3.fromRGB(157, 60, 157),
            ["Passengers"] = 1,
            ["Icon"] = "rbxassetid://14166517519",
            ["CarColor"] = Color3.fromRGB(123, 47, 123)
        },
        ["Sled"] = {
            ["Acceleration"] = 18,
            ["Upgrades"] = 1,
            ["NameColor"] = Color3.fromRGB(255, 186, 137),
            ["CarColor"] = Color3.fromRGB(255, 188, 161),
            ["Name"] = "Sled",
            ["WinMultiplier"] = 88,
            ["IsSeasonPassCar"] = true,
            ["UpgradePrice"] = {["Value"] = 6667000, ["Currency"] = "Wins"},
            ["Icon"] = "rbxassetid://105417472718940",
            ["Passengers"] = 1
        },
        ["Butterfly"] = {
            ["Acceleration"] = 8,
            ["Upgrades"] = 1,
            ["NameColor"] = Color3.fromRGB(255, 170, 255),
            ["CarColor"] = Color3.fromRGB(163, 162, 165),
            ["YOffset"] = 5,
            ["Name"] = "Butterfly",
            ["IsSeasonPassCar"] = true,
            ["WinMultiplier"] = 60,
            ["UpgradePrice"] = {["Value"] = 25000000, ["Currency"] = "Wins"},
            ["Icon"] = "rbxassetid://16955782877",
            ["Passengers"] = 0
        },
        ["Jack O Lantern"] = {
            ["Acceleration"] = 60,
            ["Upgrades"] = 1,
            ["NameColor"] = Color3.fromRGB(255, 170, 0),
            ["CarColor"] = Color3.fromRGB(163, 162, 165),
            ["Name"] = "Jack O Lantern",
            ["WinMultiplier"] = 120,
            ["IsSeasonPassCar"] = true,
            ["UpgradePrice"] = {["Value"] = 1000000000000, ["Currency"] = "Wins"},
            ["Icon"] = "rbxassetid://103230609647817",
            ["Passengers"] = 0
        },
        ["Train"] = {
            ["Acceleration"] = 4.1,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(211, 228, 231),
            ["CarColor"] = Color3.fromRGB(248, 248, 248),
            ["Name"] = "Train",
            ["AdjustPets"] = true,
            ["WinMultiplier"] = 25,
            ["UpgradePrice"] = {["ProductIds"] = {1600508219, 1600508515}, ["Currency"] = "Robux"},
            ["Icon"] = "rbxassetid://14314199265",
            ["Passengers"] = 20
        },
        ["Turkey Rider"] = {
            ["WinMultiplier"] = 1.9,
            ["Acceleration"] = 0,
            ["Name"] = "Turkey Rider",
            ["Upgrades"] = 0,
            ["NameColor"] = Color3.fromRGB(165, 110, 74),
            ["Passengers"] = 1,
            ["Icon"] = "rbxassetid://11673273479",
            ["CarColor"] = Color3.fromRGB(94, 59, 35)
        },
        ["Helicopter"] = {
            ["Acceleration"] = 2.5,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(232, 232, 232),
            ["CarColor"] = Color3.fromRGB(237, 234, 234),
            ["Name"] = "Helicopter",
            ["AdjustPets"] = true,
            ["WinMultiplier"] = 15,
            ["UpgradePrice"] = {["ProductIds"] = {1644290210, 1644290289}, ["Currency"] = "Robux"},
            ["Icon"] = "rbxassetid://14784262438",
            ["Passengers"] = 5
        },
        ["Airplane"] = {
            ["Acceleration"] = 0.25,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(248, 248, 248),
            ["CarColor"] = Color3.fromRGB(0, 223, 0),
            ["Name"] = "Airplane",
            ["YOffset"] = 6,
            ["Price"] = {["Value"] = 10000000000000, ["Currency"] = "Wins"},
            ["WinMultiplier"] = 21,
            ["Icon"] = "rbxassetid://14365036951",
            ["Passengers"] = 14
        },
        ["Independence Car"] = {
            ["Acceleration"] = 0,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(255, 66, 51),
            ["CarColor"] = Color3.fromRGB(196, 40, 28),
            ["Name"] = "Independence Car",
            ["WinMultiplier"] = 14,
            ["UpgradePrice"] = {["Value"] = 1000000, ["Currency"] = "Event.Currency"},
            ["Icon"] = "rbxassetid://13955223829",
            ["Passengers"] = 1
        },
        ["Grim Friend"] = {
            ["WinMultiplier"] = 17,
            ["Acceleration"] = 3,
            ["Name"] = "Grim Friend",
            ["Upgrades"] = 0,
            ["NameColor"] = Color3.fromRGB(157, 60, 157),
            ["Passengers"] = 0,
            ["Icon"] = "rbxassetid://14320732064",
            ["CarColor"] = Color3.fromRGB(123, 47, 123)
        },
        ["Veloce Luxe"] = {
            ["Acceleration"] = 0,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(0, 170, 0),
            ["CarColor"] = Color3.fromRGB(0, 170, 0),
            ["Name"] = "Veloce Luxe",
            ["WinMultiplier"] = 4.5,
            ["UpgradePrice"] = {["ProductIds"] = {1548557789, 1548584119}, ["Currency"] = "Robux"},
            ["Icon"] = "rbxassetid://13534548617",
            ["Passengers"] = 1
        },
        ["Quantum Racer"] = {
            ["Acceleration"] = 0,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(255, 255, 0),
            ["CarColor"] = Color3.fromRGB(4, 175, 236),
            ["Name"] = "Quantum Racer",
            ["WinMultiplier"] = 3.5,
            ["UpgradePrice"] = {["ProductIds"] = {1554595875, 1554595969}, ["Currency"] = "Robux"},
            ["Icon"] = "rbxassetid://13682041375",
            ["Passengers"] = 1
        },
        ["Lightning Speed"] = {
            ["Acceleration"] = 0,
            ["Upgrades"] = 0,
            ["NameColor"] = Color3.fromRGB(187, 238, 141),
            ["CarColor"] = Color3.fromRGB(142, 231, 94),
            ["Name"] = "Lightning Speed",
            ["Price"] = {["Value"] = 699, ["Currency"] = "Robux", ["ProductId"] = 1339874179},
            ["WinMultiplier"] = 3.25,
            ["Icon"] = "rbxassetid://11656306155",
            ["Passengers"] = 1
        },
        ["Lava Bike"] = {
            ["Acceleration"] = 0,
            ["Upgrades"] = 0,
            ["NameColor"] = Color3.fromRGB(255, 221, 53),
            ["CarColor"] = Color3.fromRGB(27, 42, 53),
            ["Name"] = "Lava Bike",
            ["Price"] = {["Value"] = 399, ["Currency"] = "Robux", ["ProductId"] = 1339874200},
            ["WinMultiplier"] = 2.25,
            ["Icon"] = "rbxassetid://11656308127",
            ["Passengers"] = 0
        },
        ["Velocity Insecta"] = {
            ["Acceleration"] = 0,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(255, 255, 0),
            ["CarColor"] = Color3.fromRGB(255, 255, 0),
            ["Progressions"] = {
                {["WinMultiplier"] = 5, ["Acceleration"] = 5},
                {["WinMultiplier"] = 20, ["Acceleration"] = 5},
                {["WinMultiplier"] = 10, ["Acceleration"] = 5}
            },
            ["Name"] = "Velocity Insecta",
            ["IsProgressive"] = true,
            ["WinMultiplier"] = 0,
            ["UpgradePrice"] = {["ProductIds"] = {1612539449, 1612539689}, ["Currency"] = "Robux"},
            ["Icon"] = "rbxassetid://14403754193",
            ["Passengers"] = 1
        },
        ["School Van"] = {
            ["Acceleration"] = 0.5,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(255, 255, 0),
            ["CarColor"] = Color3.fromRGB(255, 255, 0),
            ["Name"] = "School Van",
            ["Price"] = {["Value"] = 500000000000, ["Currency"] = "Wins"},
            ["WinMultiplier"] = 11,
            ["Icon"] = "rbxassetid://13917025132",
            ["Passengers"] = 5
        },
        ["Race Kart"] = {
            ["Acceleration"] = 0,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(245, 78, 51),
            ["CarColor"] = Color3.fromRGB(255, 0, 0),
            ["Name"] = "Race Kart",
            ["Price"] = {["Value"] = 2000000, ["Currency"] = "Wins"},
            ["WinMultiplier"] = 1.35,
            ["Icon"] = "rbxassetid://11656298080",
            ["Passengers"] = 0
        },
        ["Birthday Caravan"] = {
            ["Acceleration"] = 2,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(254, 208, 19),
            ["CarColor"] = Color3.fromRGB(248, 248, 248),
            ["Birthday WinsMultiplier"] = 3,
            ["Name"] = "Birthday Caravan",
            ["WinMultiplier"] = 23,
            ["UpgradePrice"] = {["Value"] = 1000000, ["Currency"] = "Event.Currency"},
            ["Icon"] = "rbxassetid://14482531431",
            ["Passengers"] = 1
        },
        ["Zheroni"] = {
            ["Acceleration"] = 3.5,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(0, 200, 0),
            ["CarColor"] = Color3.fromRGB(0, 200, 0),
            ["AdjustPets"] = true,
            ["Passengers"] = 3,
            ["Name"] = "Zheroni",
            ["WinMultiplier"] = 29.5,
            ["IsShopEventCar"] = true,
            ["UpgradePrice"] = {["Value"] = 3500000, ["Currency"] = "Event.Currency"},
            ["Icon"] = "rbxassetid://14782664950",
            ["Anime WinsMultiplier"] = 11
        },
        ["Roller Coaster"] = {
            ["Acceleration"] = 0,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(255, 170, 0),
            ["CarColor"] = Color3.fromRGB(255, 255, 0),
            ["Name"] = "Roller Coaster",
            ["Price"] = {["Value"] = 150000000000, ["Currency"] = "Wins"},
            ["WinMultiplier"] = 7,
            ["Icon"] = "rbxassetid://13633617811",
            ["Passengers"] = 3
        },
        ["Bumper"] = {
            ["Acceleration"] = 0,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(255, 0, 0),
            ["CarColor"] = Color3.fromRGB(170, 0, 0),
            ["Name"] = "Bumper",
            ["Price"] = {["Value"] = 100000000000, ["Currency"] = "Wins"},
            ["WinMultiplier"] = 6,
            ["Icon"] = "rbxassetid://13633617504",
            ["Passengers"] = 0
        },
        ["Super Yacht"] = {
            ["Acceleration"] = 4,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(211, 228, 231),
            ["CarColor"] = Color3.fromRGB(248, 248, 248),
            ["Name"] = "Super Yacht",
            ["WinMultiplier"] = 20,
            ["UpgradePrice"] = {["ProductIds"] = {1560747816, 1560747852}, ["Currency"] = "Robux"},
            ["Icon"] = "rbxassetid://13917024232",
            ["Passengers"] = 10
        },
        ["Burger"] = {
            ["Acceleration"] = 10.4,
            ["Upgrades"] = 1,
            ["NameColor"] = Color3.fromRGB(255, 170, 0),
            ["CarColor"] = Color3.fromRGB(255, 170, 0),
            ["Food WinsMultiplier"] = 11,
            ["Name"] = "Burger",
            ["WinMultiplier"] = 57.6,
            ["IsShopEventCar"] = true,
            ["UpgradePrice"] = {["Value"] = 70000000, ["Currency"] = "Event.Currency"},
            ["Icon"] = "rbxassetid://17463622727",
            ["Passengers"] = 0
        },
        ["Cupid's Ride"] = {
            ["Acceleration"] = 0,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(222, 210, 231),
            ["CarColor"] = Color3.fromRGB(224, 178, 208),
            ["Name"] = "Cupid's Ride",
            ["WinMultiplier"] = 4.2,
            ["UpgradePrice"] = {["Value"] = 15000000000, ["Currency"] = "Wins"},
            ["Icon"] = "rbxassetid://12528877868",
            ["Passengers"] = 1
        },
        ["Snowman"] = {
            ["Acceleration"] = 14,
            ["Upgrades"] = 1,
            ["NameColor"] = Color3.fromRGB(255, 255, 255),
            ["CarColor"] = Color3.fromRGB(126, 126, 126),
            ["SnowflakesMultiplier"] = 10.4,
            ["Name"] = "Snowman",
            ["WinMultiplier"] = 56,
            ["IsShopEventCar"] = true,
            ["UpgradePrice"] = {["Value"] = 56667000, ["Currency"] = "Event.Currency"},
            ["Icon"] = "rbxassetid://134800512766550",
            ["Passengers"] = 0
        },
        ["Cauldron"] = {
            ["Candy CornMultiplier"] = 2,
            ["Acceleration"] = 0.4,
            ["Upgrades"] = 0,
            ["NameColor"] = Color3.fromRGB(170, 85, 255),
            ["CarColor"] = Color3.fromRGB(126, 126, 126),
            ["Name"] = "Cauldron",
            ["IsShopEventCar"] = true,
            ["WinMultiplier"] = 2,
            ["Icon"] = "rbxassetid://103754424363045",
            ["Passengers"] = 0
        },
        ["Guard"] = {
            ["Acceleration"] = 0.3,
            ["Upgrades"] = 0,
            ["NameColor"] = Color3.fromRGB(255, 57, 57),
            ["CarColor"] = Color3.fromRGB(165, 47, 59),
            ["Name"] = "Guard",
            ["WinMultiplier"] = 1,
            ["Price"] = {["Value"] = 50000, ["Currency"] = "Wins"},
            ["Priority"] = true,
            ["Icon"] = "rbxassetid://136152112347880",
            ["Passengers"] = 0
        },
        ["Yacht"] = {
            ["Acceleration"] = 2.5,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(211, 228, 231),
            ["CarColor"] = Color3.fromRGB(248, 248, 248),
            ["Name"] = "Yacht",
            ["WinMultiplier"] = 17,
            ["UpgradePrice"] = {["Value"] = 1000000, ["Currency"] = "Event.Currency"},
            ["Icon"] = "rbxassetid://13917023852",
            ["Passengers"] = 5
        },
        ["MechaRider"] = {
            ["Acceleration"] = 3,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(0, 200, 0),
            ["CarColor"] = Color3.fromRGB(0, 200, 0),
            ["Name"] = "MechaRider",
            ["YOffset"] = {0, -2.5, 0},
            ["WinMultiplier"] = 30,
            ["UpgradePrice"] = {["Value"] = 3500000, ["Currency"] = "Event.Currency"},
            ["Icon"] = "rbxassetid://14853767329",
            ["Passengers"] = 1
        },
        ["Moped"] = {
            ["Acceleration"] = 0,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(23, 217, 245),
            ["CarColor"] = Color3.fromRGB(0, 146, 236),
            ["Name"] = "Moped",
            ["Price"] = {["Value"] = 100000, ["Currency"] = "Wins"},
            ["WinMultiplier"] = 0.95,
            ["Icon"] = "rbxassetid://11656282991",
            ["Passengers"] = 0
        },
        ["Horse"] = {
            ["Acceleration"] = 8,
            ["Upgrades"] = 1,
            ["NameColor"] = Color3.fromRGB(255, 85, 0),
            ["CarColor"] = Color3.fromRGB(255, 85, 0),
            ["Name"] = "Horse",
            ["WinMultiplier"] = 40,
            ["Price"] = {["Value"] = 50000000000000000, ["Currency"] = "Wins"},
            ["UpgradePrice"] = {["Value"] = 100000000000000000, ["Currency"] = "Wins"},
            ["Icon"] = "rbxassetid://17125039696",
            ["Passengers"] = 0
        },
        ["Red Rocket"] = {
            ["Acceleration"] = 0,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(236, 38, 55),
            ["CarColor"] = Color3.fromRGB(255, 0, 0),
            ["Name"] = "Red Rocket",
            ["Price"] = {["Value"] = 40000000, ["Currency"] = "Wins"},
            ["WinMultiplier"] = 1.75,
            ["Icon"] = "rbxassetid://11656304165",
            ["Passengers"] = 1
        },
        ["Rainbow"] = {
            ["Acceleration"] = 16,
            ["Upgrades"] = 1,
            ["NameColor"] = Color3.fromRGB(255, 170, 0),
            ["CarColor"] = Color3.fromRGB(163, 162, 165),
            ["Name"] = "Rainbow",
            ["WinMultiplier"] = 80,
            ["IsSeasonPassCar"] = true,
            ["UpgradePrice"] = {["Value"] = 25000000, ["Currency"] = "Wins"},
            ["Icon"] = "rbxassetid://16955785898",
            ["Passengers"] = 0
        },
        ["Limo"] = {
            ["Acceleration"] = 2.5,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(211, 228, 231),
            ["CarColor"] = Color3.fromRGB(248, 248, 248),
            ["Name"] = "Limo",
            ["AdjustPets"] = true,
            ["WinMultiplier"] = 17,
            ["UpgradePrice"] = {["ProductIds"] = {1600533478, 1600533615}, ["Currency"] = "Robux"},
            ["Icon"] = "rbxassetid://14314441993",
            ["Passengers"] = 5
        },
        ["Beachball"] = {
            ["Acceleration"] = 12,
            ["Upgrades"] = 1,
            ["NameColor"] = Color3.fromRGB(255, 85, 0),
            ["CarColor"] = Color3.fromRGB(163, 162, 165),
            ["Name"] = "Beachball",
            ["WinMultiplier"] = 64,
            ["IsSeasonPassCar"] = true,
            ["UpgradePrice"] = {["Value"] = 25000000, ["Currency"] = "Wins"},
            ["Icon"] = "rbxassetid://18155816341",
            ["Passengers"] = 0
        },
        ["Jungle Cruiser"] = {
            ["Acceleration"] = 0,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(60, 226, 141),
            ["CarColor"] = Color3.fromRGB(52, 142, 64),
            ["Name"] = "Jungle Cruiser",
            ["Price"] = {["Value"] = 15000000000, ["Currency"] = "Wins"},
            ["WinMultiplier"] = 4,
            ["Icon"] = "rbxassetid://12375980625",
            ["Passengers"] = 1
        },
        ["Spooky Wolf"] = {
            ["Acceleration"] = 5,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(255, 175, 94),
            ["Spooky WinsMultiplier"] = 7,
            ["CarColor"] = Color3.fromRGB(189, 118, 61),
            ["AdjustPets"] = true,
            ["Name"] = "Spooky Wolf",
            ["WinMultiplier"] = 37,
            ["IsShopEventCar"] = true,
            ["UpgradePrice"] = {["Value"] = 2000000, ["Currency"] = "Event.Currency"},
            ["Icon"] = "rbxassetid://15271970484",
            ["Passengers"] = 0
        },
        ["Silent Bike"] = {
            ["Acceleration"] = 5,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(11, 162, 232),
            ["CarColor"] = Color3.fromRGB(159, 243, 233),
            ["Passengers"] = 0,
            ["Name"] = "Silent Bike",
            ["WinMultiplier"] = 30,
            ["IsShopEventCar"] = "Event",
            ["UpgradePrice"] = {["Value"] = 1000000, ["Currency"] = "Event.Currency"},
            ["Icon"] = "rbxassetid://14961107711",
            ["Anime WinsMultiplier"] = 20
        },
        ["Supersonic Elegence"] = {
            ["Acceleration"] = 0,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(255, 255, 0),
            ["CarColor"] = Color3.fromRGB(255, 255, 0),
            ["Name"] = "Supersonic Elegence",
            ["WinMultiplier"] = 5,
            ["UpgradePrice"] = {["ProductIds"] = {1548584522, 1548584570}, ["Currency"] = "Robux"},
            ["Icon"] = "rbxassetid://13534548417",
            ["Passengers"] = 1
        },
        ["Galactic Ship"] = {
            ["Acceleration"] = 3.5,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(163, 162, 165),
            ["CarColor"] = Color3.fromRGB(163, 162, 165),
            ["Name"] = "Galactic Ship",
            ["WinMultiplier"] = 31.5,
            ["UpgradePrice"] = {["Value"] = 3500000, ["Currency"] = "Event.Currency"},
            ["Icon"] = "rbxassetid://14853786771",
            ["Passengers"] = 0
        },
        ["Gegagedigedagedago"] = {
            ["Acceleration"] = 10,
            ["Upgrades"] = 1,
            ["NameColor"] = Color3.fromRGB(85, 255, 255),
            ["CarColor"] = Color3.fromRGB(163, 162, 165),
            ["Name"] = "Gegagedigedagedago",
            ["WinMultiplier"] = 50,
            ["Price"] = {["Value"] = 200000000000000000, ["Currency"] = "Wins"},
            ["UpgradePrice"] = {["Value"] = 300000000000000000, ["Currency"] = "Wins"},
            ["Icon"] = "rbxassetid://111640902096148",
            ["Passengers"] = 0
        },
        ["Joyride"] = {
            ["Acceleration"] = 1.9,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(239, 148, 68),
            ["CarColor"] = Color3.fromRGB(213, 115, 61),
            ["Name"] = "Joyride",
            ["WinMultiplier"] = 20,
            ["UpgradePrice"] = {["Value"] = 1000000, ["Currency"] = "Event.Currency"},
            ["Icon"] = "rbxassetid://14148087306",
            ["Passengers"] = 3
        },
        ["BlazeRacer"] = {
            ["Acceleration"] = 0,
            ["Upgrades"] = 2,
            ["NameColor"] = Color3.fromRGB(85, 0, 0),
            ["CarColor"] = Color3.fromRGB(85, 0, 0),
            ["Name"] = "BlazeRacer",
            ["WinMultiplier"] = 5.5,
            ["UpgradePrice"] = {["ProductIds"] = {1548557372, 1548557790}, ["Currency"] = "Robux"},
            ["Icon"] = "rbxassetid://13534548480",
            ["Passengers"] = 1
        },
        ["Bumblee Bee"] = {
            ["Acceleration"] = 6,
            ["Upgrades"] = 1,
            ["NameColor"] = Color3.fromRGB(255, 255, 0),
            ["CarColor"] = Color3.fromRGB(163, 162, 165),
            ["Name"] = "Bumblee Bee",
            ["WinMultiplier"] = 48,
            ["IsSeasonPassCar"] = true,
            ["UpgradePrice"] = {["Value"] = 25000000, ["Currency"] = "Wins"},
            ["Icon"] = "rbxassetid://16955780440",
            ["Passengers"] = 0
        }
    },
    ["DailyColorNames"] = {"Pink", "Orange", "Yellow", "Green", "Turquoise", "Light Blue", "Dark Blue", "Purple"},
    ["UpgradePrefix"] = {"Reformed ", "Enhanced ", ""}
}
